Repository AudiusProject/apps, pull requests merged in 2020-07, with the labels that each got.

#546 [L06] Misleading comments, docstrings, and typographical errors
  eth-contracts/contracts/ServiceProviderFactory.sol
  eth-contracts/contracts/Staking.sol
Labels: audit-feedback

#580 [L03] Duplicated staker check
  eth-contracts/contracts/ClaimsManager.sol
  eth-contracts/contracts/Governance.sol
  eth-contracts/contracts/ServiceTypeManager.sol
  eth-contracts/contracts/Staking.sol
  eth-contracts/contracts/registry/Registry.sol
  eth-contracts/test/governance.test.js
Labels: audit-feedback

#569 [M04] Lack of input validation
  eth-contracts/contracts/ClaimsManager.sol
  eth-contracts/contracts/DelegateManager.sol
  eth-contracts/contracts/Governance.sol
  eth-contracts/contracts/ServiceProviderFactory.sol
  eth-contracts/contracts/ServiceTypeManager.sol
  eth-contracts/contracts/Staking.sol
  eth-contracts/contracts/registry/Registry.sol
  eth-contracts/contracts/test/MockStakingCaller.sol
  eth-contracts/test/claimsManager.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/serviceProvider.test.js
Labels: audit-feedback

#589 [M10] Some state variables are not set during initialize
  eth-contracts/contracts/ClaimsManager.sol
  eth-contracts/contracts/DelegateManager.sol
  eth-contracts/contracts/Governance.sol
  eth-contracts/contracts/ServiceProviderFactory.sol
  eth-contracts/contracts/Staking.sol
  eth-contracts/contracts/test/MockStakingCaller.sol
  eth-contracts/test/serviceProvider.test.js
  eth-contracts/utils/lib.js
Labels: audit-feedback

#594 [M02 - pt2 - please see pt1 PR] Inconsistently checking initialization
  eth-contracts/contracts/Governance.sol
  eth-contracts/contracts/ServiceTypeManager.sol
Labels: audit-feedback

#596 [L08] Votes can be overwritten by calling the same function for the first vote
  eth-contracts/contracts/Governance.sol
  eth-contracts/test/governance.test.js
Labels: audit-feedback

#550 [L01] Governance proposal description only stored in log
  eth-contracts/contracts/Governance.sol
  eth-contracts/migrations/3_governance_migration.js
  eth-contracts/test/governance.test.js
  eth-contracts/utils/lib.js
Labels: audit-feedback

#604 Remove unnused var from and add natspec to InitializableV2
  eth-contracts/contracts/InitializableV2.sol
Labels: eth-contracts

#609 [H04 - pt 2 of 2] No incentive for evaluating proposals with outcome other than Yes
  eth-contracts/contracts/Governance.sol
  eth-contracts/test/governance.test.js
Labels: audit-feedback, eth-contracts

#611 [Coverage] Remove unreachable line
  eth-contracts/contracts/Governance.sol
Labels: eth-contracts

#607 Vulnerability in proposal execution, which allows circumvention of guardian veto
  eth-contracts/contracts/Governance.sol
  eth-contracts/migrations/3_governance_migration.js
  eth-contracts/test/audiusToken.test.js
  eth-contracts/test/claimsManager.test.js
  eth-contracts/test/delegateManager.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/serviceProvider.test.js
  eth-contracts/test/staking.test.js
  eth-contracts/test/upgradeability.test.js
  eth-contracts/utils/lib.js
Labels: eth-contracts

#616 Add ability for guardianAddress to submit proposals + add test
  eth-contracts/contracts/Governance.sol
  eth-contracts/test/governance.test.js
Labels: eth-contracts

#622 libs patch
  libs/package-lock.json
  libs/package.json
Labels: libs

#623 Query creator node users by spID
  discovery-provider/src/queries/queries.py
  libs/data-contracts/ABIs/UserReplicaSetManager.json
  libs/src/services/discoveryProvider/index.js
  libs/src/services/discoveryProvider/requests.js
  libs/tests/helpers.js
  libs/tests/userReplicaSetManagerTest.js
Labels: creator-node

#627 [mainnet] Consume UpgradeabilityProxy in AudiusAdminUpgradeabilityProxy
  eth-contracts/contracts/AudiusAdminUpgradeabilityProxy.sol
  eth-contracts/contracts/test/MockStakingCaller.sol
  eth-contracts/migrations/2_registry_migration.js
  eth-contracts/migrations/3_governance_migration.js
  eth-contracts/migrations/4_token_migration.js
  eth-contracts/migrations/5_staking_migration.js
  eth-contracts/migrations/6_claims_manager_migration.js
  eth-contracts/migrations/7_versioning_service_migration.js
  eth-contracts/migrations/8_delegate_manager_migration.js
  eth-contracts/test/claimsManager.test.js
  eth-contracts/test/delegateManager.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/registry.test.js
  eth-contracts/test/serviceProvider.test.js
  eth-contracts/test/staking.test.js
  eth-contracts/test/upgradeability.test.js
  eth-contracts/utils/lib.js
Labels: audit-feedback

#630 Creator node gateway /ipfs/* order of operations
  creator-node/src/routes/files.js
Labels: creator-node

#677 Comment updates
  eth-contracts/contracts/DelegateManager.sol
  eth-contracts/contracts/ServiceProviderFactory.sol
Labels: audit-feedback-2

#624 rehydrate queue for ipfs calls
  creator-node/default-config.json
  creator-node/src/RehydrateIpfsQueue.js
  creator-node/src/app.js
  creator-node/src/config.js
  creator-node/src/index.js
  creator-node/src/ipfsClient.js
  creator-node/src/routes/files.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/routes/tracks.js
  creator-node/src/utils.js
Labels: creator-node
