Repository AudiusProject/apps, pull requests merged in 2021-12, with the labels that each got.

#2112 Bump libs version
  libs/package-lock.json
  libs/package.json
Labels: libs

#2120 [ASI-604] Update libs Content Node selection to optionally prefer higher patch version for primary and secondaries
  libs/src/api/serviceProvider.js
  libs/src/api/user.js
  libs/src/api/user.test.js
  libs/src/index.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/services/creatorNode/CreatorNodeSelection.js
  libs/src/services/creatorNode/CreatorNodeSelection.test.js
  libs/src/utils/network.js
  libs/src/utils/network.test.js
Labels: feature, libs

#2093 Remove old trending
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/ePWJD_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  discovery-provider/tests/test_trending_challenge.py
  discovery-provider/tests/test_update_trending.py
Labels: discovery-node

#2071 ASI-738 fixes for provisioning remote dev host easily; bake image script
  libs/package.json
  service-commands/scripts/bake-dev-image.sh
  service-commands/scripts/create-instance.sh
  service-commands/scripts/init-repos.sh
  service-commands/scripts/provision-dev-env.sh
  service-commands/scripts/registerAAO.sh
  service-commands/scripts/set-git-refs.sh
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/setup-k8s-manifests.sh
  service-commands/scripts/utils.sh
Labels: size/L

#2165 Remove configuring of etc/hosts and gitconfig
  service-commands/scripts/setup-instance.sh
Labels: size/XS

#2168 Fix import in user listening history
  discovery-provider/integration_tests/tasks/test_index_user_listening_history.py
Labels: size/XS

#1842 Skip entire block for failure to session.commit a bad tx
  contracts/scripts/migrate-contracts.js
  discovery-provider/.gitignore
  discovery-provider/compose/.env
  discovery-provider/compose/docker-compose.backend.yml
  discovery-provider/compose/docker-compose.db.yml
  discovery-provider/compose/env/base.env
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/challenges/test_create_new_challenges.py
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/utils/test_index_operations.py
  discovery-provider/scripts/circle-ci.sh
  discovery-provider/scripts/dev-server.sh
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/setup.sh
  discovery-provider/scripts/test.sh
  discovery-provider/src/app.py
  discovery-provider/src/tasks/cache_user_balance.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_blacklist.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/ipld_blacklist.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/config.py
  eth-contracts/scripts/migrate-contracts.js
  libs/scripts/migrate_contracts.sh
  service-commands/src/commands/service-commands.json
Labels: discovery-node, service-commands, size/XL

#2103 [AUD-1114] Add plays slot diff selection criteria
  libs/src/index.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
  libs/src/services/discoveryProvider/index.js
Labels: size/L

#2172 Libs v1.2.38
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2164 Create hourly play metrics table and indexing
  discovery-provider/alembic/versions/a41727360622_create_hourly_play_metrics_table.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
  discovery-provider/integration_tests/test_index_hourly_play_counts.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/app.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/models.py
  discovery-provider/src/tasks/index_aggregate_plays.py
  discovery-provider/src/tasks/index_hourly_play_counts.py
Labels: size/L

#2180 Add headers to send when making discovery node request
  libs/src/services/discoveryProvider/index.js
Labels: size/XS

#2181 v1.2.39
  libs/package-lock.json
  libs/package.json
  libs/src/services/discoveryProvider/index.js
Labels: size/XS

#2146 Deactivated Account Changes
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/challenges/challenge.py
  discovery-provider/src/queries/get_attestation.py
  discovery-provider/src/queries/get_tracks.py
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: discovery-node, identity-service, size/M

#2188 Update gas limit and price estimation and min/max
  libs/src/services/ethWeb3Manager/index.js
Labels: size/S

#2170 Minor fixes for Automating Remote Dev Box doc
  service-commands/scripts/.zshrc
  service-commands/scripts/provision-dev-env.sh
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/utils.sh
Labels: size/L

#2193 Fix zshenv provisioning
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/utils.sh
Labels: size/S

#2194 Add inspect flag for debugger mode CN
  creator-node/scripts/start.sh
Labels: size/XS

#2196 AUD-1111 Add " and {} to url slug exclusion list
  discovery-provider/src/utils/helpers.py
Labels: size/XS

#2191 Keep existing user event data on update
  discovery-provider/src/tasks/users.py
Labels: size/M

#2157 Only build and push Docker images when changed
  .circleci/config.yml
Labels: size/S

#2197 Add additional rewards fixes
  discovery-provider/.vscode/settings.json
  discovery-provider/integration_tests/queries/test_undisbursed_challeges.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/get_balances.py
  discovery-provider/src/queries/get_undisbursed_challenges.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
  libs/package-lock.json
  libs/package.json
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/src/services/solanaWeb3Manager/userBank.js
  libs/src/services/solanaWeb3Manager/utils.js
  libs/src/utils/utils.js
Labels: size/L

#2202 Add migration to add SolanaNotifications andSolanaNotificationActions indexes
  identity-service/sequelize/migrations/20211223183608-add-solana-notification-indexes.js
Labels: size/S

#2138 ASI-679 Add more logs for phases during upload flow
  creator-node/src/FileProcessingQueue.js
  creator-node/src/TranscodingQueue.js
  creator-node/src/diskManager.js
  creator-node/src/ffmpeg.js
  creator-node/src/ipfsClient.js
  creator-node/src/routes/tracks.js
Labels: size/L
