Repository AudiusProject/apps, pull requests merged in 2022-11, with the labels that each got.

#4240 Fixes audio_tx_hist index_spl_token bug
  discovery-provider/src/tasks/index_spl_token.py
Labels: size/XS

#4243 [CON-486] Optional chain potentially null syncStatus
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
Labels: content-node, size/XS

#4244 CN - reduce DAYS_BEFORE_PRUNING_ORPHANED_CONTENT from 7 to 4
  creator-node/src/diskManager.ts
Labels: size/XS

#4184 Add hook to bunyan to create tracer events
  creator-node/src/tracer.ts
Labels: size/XS

#4215 [CON-471] Remove leftover active sync jobs during `syncQueue` start up
  creator-node/src/serviceRegistry.js
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.ts
  creator-node/test/AsyncProcessingQueue.test.js
  creator-node/test/lib/app.js
  creator-node/test/sync.test.js
Labels: size/M

#4245 Update logic for circleci release-week gate
  .circleci/config.yml
Labels: size/XS

#4247 INF Use full if statements, dont rely on built-in true
  .circleci/config.yml
Labels: size/XS

#4248 Convert `trackComponentService` to typescript
  creator-node/src/components/tracks/tracksComponentService.ts
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
Labels: size/M

#4249 Make init worker detection more reliable
  creator-node/src/index.ts
  creator-node/src/utils/clusterUtils.ts
Labels: content-node, size/S

#4236 Add flag to disable sync tracking
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateReconciliation/SecondarySyncHealthTracker.ts
  creator-node/test/stateMonitoringUtils.test.js
Labels: size/L

#4246 Fix artist dashboard on no plays
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/api/v1/users_unit_test.py
Labels: size/M

#4260 CN - trackUploadArtifactDeletionEnabled
  creator-node/src/config.js
  creator-node/src/fileManager.js
Labels: size/S

#4149 Add code for local AAO
  dev-tools/audius-compose
  dev-tools/config.json
  docker-compose.yml
  eth-contracts/contract-config.js
Labels: size/M

#4255 [PLAT-375] Add m3u playlist API
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/app.py
Labels: size/S

#4251 Concert `TrackContentUploadManager` to typescript
  creator-node/src/AsyncProcessingQueue.ts
  creator-node/src/ImageProcessingQueue.ts
  creator-node/src/TranscodingQueue.js
  creator-node/src/apiHelpers.ts
  creator-node/src/components/replicaSet/syncQueueComponentService.ts
  creator-node/src/components/tracks/trackContentUploadManager.ts
  creator-node/src/components/tracks/tracksComponentService.ts
  creator-node/src/ffmpeg.js
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/services/sync/syncQueue.ts
Labels: size/L

#4262 Fixes OpenAPI client gen for audius-compose
  libs/src/sdk/api/generator/gen.js
Labels: size/XS

#4264 INF Extend timeout for `audius-cli launch`
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4266 CN: Gate expensive DB step behind syncForceWipeDiskEnabled + fix lint
  creator-node/src/fileManager.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
Labels: size/S

#4268 INT Missing commas break lint
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4269 Update README.md
  README.md
Labels: size/XS

#4270 fix builds on main
  creator-node/test/fileManager.test.js
  dev-tools/audius-compose
  discovery-provider/alembic/versions/03dbd1b775c5_create_subscriptions_table.py
Labels: size/XS

#4258 [INF-307] Use delegate owner key instead of url for openresty
  discovery-provider/nginx_conf/config.lua
  discovery-provider/nginx_conf/main.lua
Labels: size/S

#4259 Remove default-config.json
  creator-node/compose/env/base.env
  creator-node/default-config.json
  creator-node/src/config.js
  creator-node/test/pollingTracks.test.js
Labels: size/L

#4055 Make mad dog work with local compose
  dev-tools/audius-compose
  dev-tools/setup-dev.sh
  dev-tools/startup/creator-node.sh
  dev-tools/startup/sshuttle-server.sh
  docker-compose.yml
  libs/initScripts/helpers/utils.js
  libs/initScripts/local.js
  mad-dog/src/helpers.js
  mad-dog/src/index.js
  mad-dog/src/madDog.js
  mad-dog/src/tests/test_integration.js
  mad-dog/src/tests/test_ipldBlacklist.js
  mad-dog/src/tests/test_snapbackSM.js
  mad-dog/src/tests/test_userReplicaSetManager.js
  mad-dog/src/tests/test_userReplicaSetNodes/deregisterRandomCreatorNode.js
  mad-dog/src/tests/test_userReplicaSetNodes/setNumCreatorNodes.js
  mad-dog/src/tests/test_userReplicaSetNodes/verifyValidCN.js
  mad-dog/src/utils/uploadTracksForUsers.js
  service-commands/scripts/A
  service-commands/src/commands/service-commands.json
  service-commands/src/libs.js
  service-commands/src/setup.js
  service-commands/src/utils/constants.js
  solana-programs/scripts/build.sh
  solana-programs/scripts/deploy.sh
Labels: size/XL

#4242 [PAY-664] Backfill audio_tx_history userbank indexing
  discovery-provider/alembic/versions/3e99d419fd63_add_sig_to_indexing_checkpoints.py
  discovery-provider/alembic/versions/93fc0b994aba_spl_token_backfill.py
  discovery-provider/alembic/versions/ab4f1c314c43_user_bank_backfill.py
  discovery-provider/alembic/versions/fcb40409e0a4_rewards_manager_backfill.py
  discovery-provider/src/app.py
  discovery-provider/src/models/indexing/indexing_checkpoints.py
  discovery-provider/src/models/indexing/spl_token_backfill_transaction.py
  discovery-provider/src/models/rewards/rewards_manager_backfill.py
  discovery-provider/src/models/users/user_bank_backfill.py
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
  discovery-provider/src/tasks/index_user_bank_backfill.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/XXL

#4261 [PAY-523] Create audio_tx_history endpoint
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/transactions.py
  discovery-provider/src/api/v1/transactions.py
  discovery-provider/src/queries/get_audio_transactions_history.py
  discovery-provider/src/queries/query_helpers.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/TransactionsApi.ts
  libs/src/sdk/api/generated/full/apis/index.ts
  libs/src/sdk/api/generated/full/models/TransactionDetails.ts
  libs/src/sdk/api/generated/full/models/TransactionHistoryResponse.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#4252 Rebuild aggregate monthly plays
  discovery-provider/alembic/versions/f91c041d1d8d_rebuild_aggregate_monthly_plays_table.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_aggregate_monthly_plays.py
Labels: size/M

#4278 es-indexer: if red index, delete all indices
  discovery-provider/es-indexer/src/conn.ts
  discovery-provider/es-indexer/src/main.ts
Labels: size/S

#4282 Ability to filter out reconfigs in identity relays
  identity-service/src/config.js
  identity-service/src/relay/txRelay.js
Labels: size/M

#4281 Fix multiple migration heads breaking builds on main
  discovery-provider/alembic/versions/f91c041d1d8d_rebuild_aggregate_monthly_plays_table.py
Labels: size/XS

#4286 Fix audius-compose exec permission
  dev-tools/audius-compose
Labels: size/XS

#4267 Fix CN tests
  creator-node/test/fileManager.test.js
Labels: size/S

#4284 Re-enable sync success tracking by default
  creator-node/src/config.js
  creator-node/test/stateMonitoringUtils.test.js
Labels: size/XS

#4271 Add subscriptions to entity manager
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/utils.py
  libs/src/api/Users.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/L

#4288 Change frequent sync logs from info to debug
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
Labels: content-node, size/XS

#4241 [PAY-489] Add endpoint to get ethereum-nft-gated premium track signatures
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/src/abis/ERC1155.json
  discovery-provider/src/abis/ERC721.json
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/queries/get_premium_track_signatures.py
  discovery-provider/src/schemas/track_schema.json
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/sdk/api/generated/full/models/index.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/XXL

#4276 [PAY-722] Check if audio_tx_hist backfilling complete
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
  discovery-provider/src/tasks/index_user_bank_backfill.py
Labels: size/L

#4279 INF Set owner wallet for prometheus scrapers
  monitoring/prometheus/.env.stage
Labels: size/XS

#4257 Add migration file for playlist routes table with backfill query
  discovery-provider/alembic/versions/bead88b41a20_create_playlist_routes_table.py
  discovery-provider/src/models/playlists/playlist_route.py
Labels: size/L

#4289 INF-266 add stablized exporters
  creator-node/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/nginx.conf
Labels: size/M

#4290 CON-445 add new and future exporter scrapers
  monitoring/prometheus/generateProm.js
Labels: size/M

#4250 Remove ELK
  logging/.env.template
  logging/.gitignore
  logging/README.md
  logging/bin/build-image.sh
  logging/bin/create-data-view.sh
  logging/bin/create-operator-es-api-keys.sh
  logging/bin/dev-image.sh
  logging/bin/install-elastic-agent.sh
  logging/bin/start.sh
  logging/bin/stop.sh
  logging/current_index_version
  logging/docker-compose.yml
  logging/filebeat/Dockerfile
  logging/filebeat/filebeat.docker.yml
  logging/metricbeat/Dockerfile
  logging/metricbeat/start.sh
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
Labels: size/XL

#4294 INF-280 finish and safeguard slashing trigger pipeline
  .circleci/config.yml
Labels: size/M

#4206 Remove foreign key constraints
  creator-node/sequelize/migrations/20200922131913-post_vector_clock_db_migrations.js
  creator-node/sequelize/migrations/20221027131913-remove-foreign-key-constraints.js
  creator-node/src/models/audiususer.js
  creator-node/src/models/track.js
Labels: content-node, size/L

#4297 INF Evaluate governance proposals on Saturday as well, this week
  .circleci/config.yml
Labels: size/XS

#4298 INF-280 Add alerts.json for signer:discord_handle relationships
  monitoring/slashing-relay/alerts.json
Labels: size/XS

#4277 Better entity manager validation logs
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
Labels: size/M

#4253 Productionize switch to nethermind (stage only)
  .circleci/config.yml
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/redis_constants.py
  discovery-provider/src/utils/web3_provider.py
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/config.js
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/healthCheck.js
Labels: size/L

#4186 [PAY-674] Send handle early to relay
  identity-service/src/authMiddleware.js
  identity-service/src/routes/relay.js
  identity-service/src/utils/antiAbuse.js
  libs/src/services/identity/IdentityService.ts
  libs/src/services/web3Manager/Web3Manager.ts
Labels: size/M

#4256 Convert `ffmpeg` to typescript
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/TranscodingQueue.js
  creator-node/src/ffmpeg.ts
Labels: size/M

#4302 CON-488 Expose CN config in route (excludes sensitive configs)
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/config.js
Labels: size/M

#4303 Add ability to set premium track with audius-cmd
  dev-tools/commands/src/upload-track.mjs
Labels: size/XS

#4274 prod release patches
  identity-service/src/notifications/processNotifications/playlistUpdateNotification.js
  identity-service/src/routes/notifications.js
Labels: size/S

#4300 Only use web3 nethermind when indexing nethermind txs
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/M

#4308 Check for existent of user
  identity-service/src/routes/relay.js
Labels: size/XS

#4309 CON-488 Fix CN GET /config_check route
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/test/healthChecks.test.js
Labels: size/M

#4310 Add separate nethermind web3 provider to identity
  discovery-provider/src/tasks/index_nethermind.py
  identity-service/compose/.env
  identity-service/default-config.json
  identity-service/scripts/run-tests.sh
  identity-service/src/config.js
  identity-service/src/relay/txRelay.js
  identity-service/src/web3.js
Labels: size/M

#4295 CON-445 Add prefixes for new exporters
  monitoring/docker-compose.yml
  monitoring/prometheus/generateProm.js
Labels: size/S

#4316 CN Shorten queue logs
  creator-node/package-lock.json
  creator-node/src/TranscodingQueue.js
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/services/SessionExpirationQueue.ts
Labels: size/L

#4320 Hotfix index_spl_token_backfill.py
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
Labels: size/XS

#4321 Check backfillers progress
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
  discovery-provider/src/tasks/index_user_bank_backfill.py
Labels: size/L

#4318 Make server read only until spID has been recovered
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.js
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.js
  creator-node/src/serviceRegistry.js
Labels: size/L

#4324 Revert playlist_routes migration commit 5a175afbb
  discovery-provider/alembic/versions/bead88b41a20_create_playlist_routes_table.py
  discovery-provider/src/models/playlists/playlist_route.py
Labels: size/L

#4301 Extract slug+collision logic to its own function
  discovery-provider/src/tasks/task_helpers.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/helpers_unit_test.py
Labels: size/L

#4327 Use storagePath from receiving node in syncs
  creator-node/src/diskManager.test.js
  creator-node/src/diskManager.ts
  creator-node/src/fileManager.js
  creator-node/src/resizeImage.js
  creator-node/src/routes/files.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/test/audiusUsers.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/playlists.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
  creator-node/test/syncAssets/sampleExportDummyCID.json
  creator-node/test/syncAssets/sampleExportDummyCIDFromClock2.json
Labels: content-node, size/XL

#4325 Convert `requestRange.test.js` to typescript
  creator-node/src/utils/requestRange.test.ts
  creator-node/src/utils/requestRange.ts
Labels: size/S

#4330 Small description fix
  dev-tools/commands/src/upload-track.mjs
Labels: size/XS

#4263 Speed up local discprov tests
  dev-tools/audius-compose
  discovery-provider/integration_tests/conftest.py
  docker-compose.test.yml
Labels: size/L

#4337 [C-1454] When content is unavail in replica set, only try entire network once
  libs/src/api/File.ts
Labels: size/XS

#4343 Clean up nginx rules for content caching
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#4344 dm-restructure-fetchCIDInNetwork Changes
  creator-node/src/config.js
  creator-node/src/fileManager.js
  creator-node/src/routes/files.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/test/sync.test.js
Labels: size/L

#4347 Fix nethermind reverse proxy config
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#4338 Add subscribers getters to libs
  libs/src/api/Users.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#4340 Update BullMQ and bull-board
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/patches/README.md
  creator-node/patches/bullmq+1.91.1.patch
  creator-node/scripts/start.sh
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
Labels: content-node, size/M

#4346 [PAY-729] Block high digit threshold from relay
  identity-service/src/utils/antiAbuse.js
Labels: size/XS

#4352 Change content-node exit log to error
  creator-node/src/index.ts
Labels: size/XS

#4335 Fix updated_at for EM indexing
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
Labels: size/S

#4332 CON-511 Replace findCIDInNetwork with better network content scan
  creator-node/src/config.js
  creator-node/src/fileManager.js
  creator-node/src/routes/files.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/fsUtils.ts
  creator-node/src/utils/index.ts
  creator-node/test/fileManager.test.js
  creator-node/test/sync.test.js
Labels: size/XL

#4339 Change OpenAPI generator README gen:dev to localhost
  libs/src/sdk/api/generator/README.md
Labels: size/XS

#4341 Remove dependencies on ordered IDs in discovery API
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_latest_entities.py
  discovery-provider/src/queries/get_max_id.py
  discovery-provider/src/queries/get_top_playlists.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/utils/auth_middleware.py
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#4355 identity notification upsert
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/src/notifications/sendDownloadAppEmails.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
  identity-service/src/routes/notifications.js
  identity-service/src/routes/push_notifications.js
  identity-service/src/routes/userEvents.js
  identity-service/src/routes/welcomeEmail.js
Labels: size/L

#4275 Convert `logging` to typescript
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/AsyncProcessingQueue.ts
  creator-node/src/ImageProcessingQueue.ts
  creator-node/src/apiHelpers.ts
  creator-node/src/app.ts
  creator-node/src/components/replicaSet/syncQueueComponentService.ts
  creator-node/src/components/tracks/trackContentUploadManager.ts
  creator-node/src/components/tracks/tracksComponentService.ts
  creator-node/src/logging.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/services/sync/syncQueue.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/types.ts
  creator-node/src/utils/utils.ts
  creator-node/src/utils/validateAudiusUserMetadata.ts
Labels: size/L

#4366 Fix release script branch
  .circleci/config.yml
Labels: size/XS

#4370 Short circuit background disk deletion
  creator-node/src/diskManager.ts
Labels: size/XS

#4333 Read subscriptions from discovery in notifications system in identity
  identity-service/src/featureFlag.js
  identity-service/src/notifications/index.js
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/src/notifications/processNotifications/index.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
  identity-service/src/notifications/sendNotifications/index.js
  identity-service/src/notifications/utils.js
Labels: size/L

#4371 Hotfix backfill indexer db leaks
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
  discovery-provider/src/tasks/index_user_bank_backfill.py
Labels: size/M

#4369 fetchFileFromNetwork bugfix + Add localOnly queryParam for CN->CN network fetches to prevent additional network fetches internally
  creator-node/package-lock.json
  creator-node/src/fileManager.js
  creator-node/src/routes/files.js
Labels: size/M

#4354 Add notification settings to users/update
  identity-service/src/routes/user.js
Labels: size/XS

#4312 update playlist routes table migration to compare lowercased playlist…
  discovery-provider/alembic/versions/bead88b41a20_create_playlist_routes_table.py
  libs/package-lock.json
  libs/package.json
Labels: size/L

#4375 Libs: Expose error details to consumer
  libs/src/api/Users.ts
Labels: size/S

#4305 Update playlist routes in playlist indexing
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/src/models/playlists/playlist_route.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#4372 [PAY-730] Pass headers to requests in SDK
  libs/src/sdk/sdk.ts
Labels: size/S

#4378 Add method to transaction API
  discovery-provider/src/api/v1/models/transactions.py
  libs/src/sdk/api/generated/full/models/TransactionDetails.ts
Labels: size/S

#4373 Add storage to healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/S

#4319 [PAY-727] Stream premium tracks from DN
  creator-node/src/routes/tracks.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/sync.test.js
  discovery-provider/alembic/versions/959f15b94094_add_track_cid.py
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
  discovery-provider/src/queries/get_authed_user.py
  discovery-provider/src/queries/get_premium_track_signatures.py
  discovery-provider/src/queries/get_track_stream_signature.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/tasks/tracks.py
  libs/src/sdk/api/generated/default/apis/TracksApi.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/utils/types.ts
Labels: size/XL

#3929 [PAY-646] Prevent the adding of a premium track to playlist in DN indexing
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
Labels: requires-special-attention, size/M

#4351 add nginx rule for comms server
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#4379 Add subsequent tracks API
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_subsequent_tracks.py
Labels: size/M

#4386 Swallow nethermind indexing errors when disabled
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/XS

#4387 remove raise_if_stale code.
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/utils/elasticdsl.py
Labels: size/S

#4385 Foundation node sync override for easier manual syncs for test purposes
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/components/replicaSet/syncQueueComponentService.ts
  creator-node/src/config.js
  creator-node/src/dbManager.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.ts
  creator-node/src/services/sync/syncUtil.ts
Labels: size/M

#4349 [PAY-707] Block abusive users from emails
  identity-service/sequelize/migrations/20221115014540-blocked-from-emails-column.js
  identity-service/src/models/user.js
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/routes/relay.js
  identity-service/src/routes/welcomeEmail.js
  identity-service/src/utils/antiAbuse.js
Labels: size/M

#4381 Replace some findOrCreates in identity notifications
  identity-service/src/notifications/processNotifications/challengeRewardNotification.js
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/src/notifications/processNotifications/followNotification.js
  identity-service/src/notifications/processNotifications/remixCreateNotification.js
  identity-service/src/notifications/processNotifications/repostNotification.js
Labels: size/L

#4389 Skip notifs
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
Labels: size/XS

#4363 [CON-510] Migrate legacy storage paths in background
  creator-node/src/config.js
  creator-node/src/dbManager.js
  creator-node/src/diskManager.test.js
  creator-node/src/diskManager.ts
  creator-node/src/fileManager.js
  creator-node/src/index.ts
  creator-node/src/resizeImage.js
  creator-node/src/routes/files.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/utils/fsUtils.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/utils.test.ts
  creator-node/src/utils/utils.ts
  creator-node/test/audiusUsers.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/playlists.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
Labels: content-node, size/XL

#4384 Optimize create subscription notifications bulk
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/test/processNotifications/createNotification.js
Labels: size/L

#4377 [CON-517] Add a route to translate trackBlockchainId to copy320 CID
  creator-node/src/routes/files.js
Labels: size/M

#4392 Add user created_at index
  discovery-provider/alembic/versions/1eec1d124caf_create_index_on_users_created_at.py
Labels: size/M

#4391 Use max block number for trending notif query
  identity-service/test/processNotifications/trendingTrackNotification.js
Labels: size/L

#4393 Pull before cutting release so checklist is correct
  .circleci/config.yml
Labels: size/XS

#4395 Add missing fields when copying track in entity manager
  discovery-provider/src/tasks/entity_manager/track.py
Labels: size/XS

#4397 [C-1547] Add favoriteAlbums and favoriteTracks routes
  discovery-provider/src/api/v1/users.py
Labels: size/M

#4365 convert `readOnlyMiddlware` to typescript
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.ts
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts
Labels: size/M

#4383 Test update playlist notification volume
  identity-service/src/notifications/processNotifications/playlistUpdateNotification.js
  identity-service/src/utils/logTimer.js
  identity-service/test/index.js
  identity-service/test/lib/dataSeeds.js
  identity-service/test/processNotifications/playlistUpdateNotification.js
Labels: size/L

#4382 update get user notifications settings
  identity-service/src/notifications/sendNotifications/index.js
  identity-service/test/index.js
  identity-service/test/sendNotifications/getUserNotificationSettings.js
  identity-service/test/sendNotifications/index.js
Labels: size/L

#4398 [C-1558] Allow streaming of unlisted tracks
  discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#4399 Clean up storage path logs
  creator-node/src/diskManager.ts
  creator-node/src/utils/fsUtils.ts
  creator-node/src/utils/utils.ts
  libs/src/utils/fileHasher.ts
Labels: content-node, size/S

#4405 Update instagram
  identity-service/src/routes/instagram.js
Labels: size/XS

#4403 [C-1558] Allow streaming of unlisted tracks - fix
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_track_user_creator_node.py
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
Labels: size/M

#4315 Recover empty queues, fix 1 cause of missing Bull locks
  creator-node/src/AsyncProcessingQueue.ts
  creator-node/src/ImageProcessingQueue.ts
  creator-node/src/TranscodingQueue.js
  creator-node/src/blacklistManager.js
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/models/index.js
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/routes/prometheusMetricsRoutes.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/SessionExpirationQueue.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.ts
  creator-node/src/utils/cluster/README.md
  creator-node/src/utils/cluster/clusterUtils.ts
  creator-node/src/utils/cluster/clusterUtilsForPrimary.ts
  creator-node/src/utils/cluster/clusterUtilsForWorker.ts
  creator-node/src/utils/clusterUtils.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/utils.ts
  creator-node/test/StateMonitoringManager.test.js
  dev-tools/audius-compose
Labels: content-node, size/XL

#4407 Add missing user and social feature challenges to entity manager
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/user.py
Labels: size/M

#4402 Update storage properties for content nodes in healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XS

#4411 Only record sync failures
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
Labels: size/XS
