Repository AudiusProject/apps, pull requests merged in 2022-07, with the labels that each got.

#3354 Add libs explore endpoints
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#3316 [CON-187] Send Network Monitoring job metadata to prometheus + add new metrics
  discovery-provider/plugins/network-monitoring/docker-compose.yaml
  discovery-provider/plugins/network-monitoring/grafana/Dockerfile
  discovery-provider/plugins/network-monitoring/grafana/bin/create-data-sources.sh
  discovery-provider/plugins/network-monitoring/grafana/bin/save-dashboards.sh
  discovery-provider/plugins/network-monitoring/grafana/bin/upload-dashboards.sh
  discovery-provider/plugins/network-monitoring/prometheus/.env.prod
  discovery-provider/plugins/network-monitoring/prometheus/.env.stage
  discovery-provider/plugins/network-monitoring/prometheus/.gitignore
  discovery-provider/plugins/network-monitoring/prometheus/config/prometheus.yml
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_tables.ts
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/discovery/index.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
  package-lock.json
Labels: size/XL

#3367 Make get_users_cnode cache configurable
  discovery-provider/default_config.ini
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#3329 [CON-152] Add state machine metrics - job runtime length and more
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/stateMachineManager/processJob.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/processJob.test.js
  creator-node/test/stateMonitoringUtils.test.js
Labels: content-node, size/XL

#3369 Fix prometheusRegistry not being passed to state machine job processor
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
Labels: size/M

#3364 [PAY-385] Updated Send First Tip Reward Amount
  discovery-provider/src/challenges/challenges.dev.json
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
Labels: size/XS

#3371 Oops fix reconciliation prometheusRegistry too
  creator-node/src/services/stateMachineManager/index.js
Labels: content-node, size/XS

#3370 Reorder try/catch for start/finish redis key
  discovery-provider/src/tasks/update_track_is_available.py
Labels: discovery-node, size/M

#3351 Tweak transcode handoff on content node to be useful as an upload health check
  creator-node/package-lock.json
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/routes/tracks.js
Labels: size/L

#3372 Perform init db calls with db txn
  creator-node/src/blacklistManager.js
Labels: size/M

#3374 Add update_track_is_available metrics
  discovery-provider/src/tasks/update_track_is_available.py
Labels: size/S

#3310 CON-38 - PR #3 V2 - Divergent State - Consume filesHash logic in stateMachine
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/sequelize/migrations/20220622152119-add-index-cnodeuser-multihash-clock.js
  creator-node/src/dbManager.js
  creator-node/src/routes/users.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/src/utils.js
  creator-node/test/dbManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/lib/helpers.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/snapbackSM.test.js
  creator-node/test/stateMachineUtils.test.js
  creator-node/test/stateMonitoringUtils.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/XXL

#3379 Remove old run data from network monitoring DB
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_tables.ts
  discovery-provider/plugins/network-monitoring/src/discovery/index.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
Labels: size/M

#3380 Add support for content nodes as prometheus targets
  monitoring/prometheus/generateProm.js
Labels: size/XS

#3382 Add success true and false metrics w prometheus
  discovery-provider/src/tasks/update_track_is_available.py
Labels: discovery-node, size/S

#3383 [AUD-1964] Add read replica to celery and trending cache job
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/tasks/cache_trending_playlists.py
Labels: size/S

#3381 Add Ghost Users Metric
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
Labels: size/M

#3384 Add Slack Alerts from Network Monitoring
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
Labels: size/M

#3366 Update libs name
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/S

#3376 Add v1 user routes for v1 full parity
  discovery-provider/src/api/v1/users.py
Labels: size/XL

#3387 Fix Network Monitoring functions for fetching a user wallet batch from DB
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
Labels: size/XS

#3363 Refactor libs base.js and serviceProvider.js classes to Typescript
  libs/src/api/ServiceProvider.ts
  libs/src/api/base.d.ts
  libs/src/api/base.js
  libs/src/api/base.ts
  libs/src/api/reactions.ts
  libs/src/libs.js
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/utils/network.ts
Labels: size/L

#3378 Add metric for find-syncs and fix reconciliation queue history
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: content-node, size/XL

#3391 demote error|warn logs
  discovery-provider/src/tasks/index.py
Labels: size/XS

#3386 [PAY-385] Added First Playlist Challenge
  discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  discovery-provider/src/challenges/challenge_event.py
  discovery-provider/src/challenges/challenge_event_bus.py
  discovery-provider/src/challenges/challenges.dev.json
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
  discovery-provider/src/challenges/first_playlist_challenge.py
  discovery-provider/src/tasks/playlists.py
Labels: size/L

#3356 Revisit Discovery Provider Overview Dashboards with additional celery metrics
  discovery-provider/src/monitors/celery.py
  discovery-provider/src/monitors/monitoring_queue.py
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/tasks/cache_trending_playlists.py
  discovery-provider/src/tasks/cache_user_balance.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_aggregate_monthly_plays.py
  discovery-provider/src/tasks/index_aggregate_tips.py
  discovery-provider/src/tasks/index_blacklist.py
  discovery-provider/src/tasks/index_challenges.py
  discovery-provider/src/tasks/index_eth.py
  discovery-provider/src/tasks/index_hourly_play_counts.py
  discovery-provider/src/tasks/index_materialized_views.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/index_oracles.py
  discovery-provider/src/tasks/index_reactions.py
  discovery-provider/src/tasks/index_related_artists.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/tasks/index_solana_user_data.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/tasks/prune_plays.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
  discovery-provider/src/tasks/vacuum_db.py
  discovery-provider/src/utils/prometheus_metric.py
  monitoring/README.md
  monitoring/grafana/bin/create-data-sources.sh
  monitoring/grafana/bin/save-dashboards.sh
  monitoring/grafana/bin/upload-dashboards.sh
  monitoring/grafana/dashboards/audius-boilerplate.json
  monitoring/grafana/dashboards/audius-discovery-provider-blockchain-indexing.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-task-details.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-tasks.json
  monitoring/grafana/dashboards/audius-discovery-provider-latency.json
  monitoring/grafana/dashboards/audius-discovery-provider-overview.json
  monitoring/grafana/dashboards/audius-internal-health.json
  monitoring/grafana/dashboards/discovery-provider.json
  monitoring/grafana/dashboards/general-alerting.json
  monitoring/grafana/dashboards/joaquin-playground.json
  monitoring/grafana/dashboards/load-test.json
  monitoring/scripts/down.sh
Labels: size/XXL

#3392 Update SDK README
  libs/README.md
Labels: size/S

#3394 SDK 0.0.11
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3385 Initialize everything in ServiceRegistry constructor
  creator-node/src/serviceRegistry.js
  mad-dog/src/index.js
Labels: size/L

#3393 Saving new Grafana Dashboards
  monitoring/grafana/dashboards/audius-discovery-provider-blockchain-indexing.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-tasks.json
  monitoring/grafana/dashboards/audius-discovery-provider-latency.json
  monitoring/grafana/dashboards/audius-discovery-provider-overview.json
  monitoring/grafana/dashboards/audius-network-monitoring.json
  monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json
  monitoring/grafana/dashboards/joaquin-network-monitoring-v2.json
  monitoring/grafana/dashboards/joaquin-playground.json
  monitoring/grafana/dashboards/network-monitoring.json
Labels: size/XXL

#3389 Updated data contract migration, updated svc commands flow
  contracts/.gitignore
  contracts/contract-config.js
  contracts/migrations/2_registry_migration.js
  contracts/migrations/4_user_replica_set_migration.js
  contracts/migrations/5_audius_data_migration.js
  contracts/scripts/migrate-contracts.js
  service-commands/scripts/bootstrap-eth-contracts-docker.js
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
Labels: size/M

#3403 Add delete playlist to audius data libs + indexing
  discovery-provider/src/tasks/audius_data.py
  libs/src/api/audiusData.ts
Labels: size/M

#3401 ServiceRegistry initialization minor fixes
  creator-node/src/index.ts
  creator-node/src/serviceRegistry.js
Labels: size/M

#3405 Remove retrieve peers from db
  discovery-provider/src/tasks/index_network_peers.py
Labels: size/S

#3406 Make `verifyToken` endpoint expect either hashid or int user id (eventually just hashid)
  discovery-provider/src/api/v1/users.py
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/XS

#3409 Use aggregate calls
  discovery-provider/src/queries/get_trending_playlists.py
Labels: size/S

#3330 related artists minhash
  discovery-provider/Dockerfile
  discovery-provider/integration_tests/queries/test_get_related_artists.py
  discovery-provider/integration_tests/tasks/test_index_related_artists.py
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_related_artists.py
  discovery-provider/src/queries/get_related_artists_minhash.py
  discovery-provider/src/tasks/index_related_artists.py
  discovery-provider/src/tasks/social_features.py
Labels: size/XL

#3404 Create a CN-like metric registry for DN's Prometheus metrics
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/aggregates/__init__.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/prometheus_metric.py
  discovery-provider/src/utils/redis_metrics.py
  monitoring/README.md
  monitoring/grafana/dashboards/audius-boilerplate.json
  monitoring/grafana/dashboards/audius-discovery-provider-blockchain-indexing.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-task-details.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-tasks.json
  monitoring/grafana/dashboards/audius-discovery-provider-overview.json
  monitoring/grafana/dashboards/audius-network-monitoring.json
  monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json
  monitoring/grafana/dashboards/joaquin-network-monitoring-v2.json
  monitoring/grafana/dashboards/joaquin-playground.json
Labels: size/XL

#3333 Add third-party exporters for local-dev and related documentation
  monitoring/README.md
  monitoring/docker-compose.yml
  monitoring/prometheus/ymls/local.yml
Labels: size/L

#3414 Grafana Production Dashboard Snapshot
  monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json
Labels: size/M

#3419 Lower cache size to 4gb
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#3418 Revert "Disable 2 day download app email (#3204)"
  identity-service/src/notifications/index.js
Labels: size/XS

#3412 INF Cleanup unused label
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/S

#3421 Update notifications track added to playlist
  discovery-provider/src/queries/notifications.py
Labels: size/S

#3390 [CON-225] Remove manual sync from snapbackSM
  creator-node/package-lock.json
  creator-node/src/middlewares.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/test/StateReconciliationManager.test.js
Labels: size/L

#3423 Remove old/outdated dev comments from network monitoring
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
Labels: size/M

#3424 Identity verify email
  identity-service/sequelize/migrations/20220711214812-add-deliverability.js
  identity-service/src/models/user.js
  identity-service/src/notifications/sendDownloadAppEmails.js
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/routes/user.js
Labels: size/M

#3422 Remove Network Monitoring Models
  discovery-provider/plugins/network-monitoring/src/db/models/cid_from_cn.ts
  discovery-provider/plugins/network-monitoring/src/db/models/cid_from_dn.ts
  discovery-provider/plugins/network-monitoring/src/db/models/content_node.ts
  discovery-provider/plugins/network-monitoring/src/db/models/index_block.ts
  discovery-provider/plugins/network-monitoring/src/db/models/user.ts
Labels: size/L

#3427 Fix claimable tokens typo
  solana-programs/scripts/deploy.sh
Labels: size/XS

#3432 Disable anchor build due to bpfel-unknown-unknown
  service-commands/scripts/init-repos.sh
Labels: size/S

#3433 @audius/sdk 0.0.12
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3434 Register content nodes prior to discovery UP in local to avoid endpoint fetch race condition
  libs/initScripts/helpers/spRegistration.js
  libs/src/services/ethContracts/ServiceProviderFactoryClient.ts
  service-commands/src/setup.js
Labels: size/M

#3415 CON-247 Update redis write locking (Divergent State Recovery #1)
  creator-node/package-lock.json
  creator-node/src/dbManager.js
  creator-node/src/middlewares.js
  creator-node/src/redis.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/files.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/routes/playlists.js
  creator-node/src/routes/tracks.js
  creator-node/src/routes/users.js
  creator-node/src/services/sync/processSync.js
  creator-node/test/redis.test.js
Labels: size/L

#3438 Update README.md
  libs/README.md
Labels: size/XS

#3436 Add content verification + retries for metadata writes
  creator-node/src/fileManager.js
Labels: size/M

#3441 Fix Redis circular dependency
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/redis.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/utils.js
  creator-node/src/utils/asyncRetry.js
  creator-node/test/utils.test.js
Labels: size/L

#3435 Added xmlhttprequest to internal browser bundle
  libs/rollup.config.js
Labels: size/XS

#3445 @audius/sdk v0.0.13
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3446 issueSyncRequestsUntilSynced - log nit
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
Labels: size/XS

#3417 Update playlist on EntityManager
  discovery-provider/src/tasks/audius_data.py
  libs/src/api/entityManager.ts
Labels: size/L

#3448 Bump to version 0.3.62
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3450 handle negative values in ranking field
  discovery-provider/src/queries/search_es.py
Labels: size/S

#3451 Add note to sdk readme about web3 polyfill
  libs/README.md
Labels: size/XS

#3437 [PAY-414] Fix unsending reactions
  identity-service/src/notifications/processNotifications/reactionNotification.js
  identity-service/src/routes/reactions.js
Labels: size/S

#3454 fix /celery_tasks_check
  discovery-provider/src/queries/health_check.py
Labels: size/XS

#3455 [CON-183] Fix libs logger issue in CN by consuming latest typed libs
  libs/src/services/contracts/ContractClient.ts
  libs/src/utils/types.ts
Labels: libs, size/XS

#3425 CON-238 - primarySyncFromSecondary (Divergent State Recovery #2)
  creator-node/package-lock.json
  creator-node/scripts/run-tests.sh
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/processSync.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/test/lib/app.js
  creator-node/test/lib/dataSeeds.js
  creator-node/test/nodesync.test.js
  creator-node/test/sync.test.js
  creator-node/test/sync/assets/export.json
  creator-node/test/sync/assets/files/1vK/QmZQd76dJjyd4bLL29gT5urxqY6JRS9vjnAUpuwkS91vKJ
  creator-node/test/sync/assets/files/28C/QmdkuVqHUDhYePhXska15UEZHPike11NPHu5tsy9eY28Ch
  creator-node/test/sync/assets/files/38t/QmZwxEQSjS6uruo4vXwkh6fUhvjBK4Yp83qq9AHX4R38tr
  creator-node/test/sync/assets/files/5CP/QmPuDcNoaa8NmSa7mYPWneNDPqMmwiDoTnr6pAsrAg5CPY
  creator-node/test/sync/assets/files/5TX/QmX1mAPkDpBTooEAoZbLv1PWFfaaq2aQ9gLX2Bcktd5TXT
  creator-node/test/sync/assets/files/6EK/QmcKcZfASQZJUVaHKtFxN7CqyhwD9oiQNeCkZxfDo36EKA
  creator-node/test/sync/assets/files/BrU/QmcyuCtU24R2N9Ejs5tsm7vebBhs3g6Qnhh6w3ZoEYBrUE
  creator-node/test/sync/assets/files/Bza/QmRiU48Xr3vD3n6KhzJAvcuchmPbbumBefa3y7aeNaBzan
  creator-node/test/sync/assets/files/GMk/Qmb5QCepqy2k26gvFKALcP74YvAaPS3AtCqNhXeH9YGMkB
  creator-node/test/sync/assets/files/Jto/QmNpX6fcViqDTBBJmVKsAVcNmQdqZRV4zqzUuxfP4DJtot
  creator-node/test/sync/assets/files/Kuk/QmSMQGu2vrE6UwXiZDCxyJwTsCcpPrYNBPJBL4by4LKukd
  creator-node/test/sync/assets/files/LZX/QmZEnMbMH9FzkLHn4LW4CGjW5FPHg6dw3PCYhHjCXrLZXy
  creator-node/test/sync/assets/files/MFa/QmbJ9JdEDT6bzdcsY5grX71nq2etzNZXsCM6H84k1GMFas
  creator-node/test/sync/assets/files/MdW/QmULEs3yq1kCVMBoiSMSVv7JopVz6K3TgncqcriioNMdWi
  creator-node/test/sync/assets/files/NDx/QmPyxEWcfJ9qnQm8CNPChzLoDinhTbi9zVtyGTJBeoNDxB
  creator-node/test/sync/assets/files/QEL/QmX9ePR6kL5djVNvGKzXogjigPfRtA75XKj3d71ZiAQELF
  creator-node/test/sync/assets/files/SQ9/QmNbt57KLtgbEKz97qSoJDZ2DteEjmg455ZBvnoCHySQ9q
  creator-node/test/sync/assets/files/TAE/QmekrmmfT4oHvRst8aYioWLTPGAGHcNEj3as8cVgo1TAE8
  creator-node/test/sync/assets/files/TLk/QmQQhdN8918ix1MibmSek9orTLKqZSSzqUvJAtEfMqTLku
  creator-node/test/sync/assets/files/VSE/QmYCWrB5vGJ3REaTRkL35QgpZNDN25E1XtEpMQVctPVSEx
  creator-node/test/sync/assets/files/VvS/QmPhEZL5o7uAtes7g1kmxRGaLeRXE9YF4h8CPHk1KYVvSk
  creator-node/test/sync/assets/files/Wmj/QmTacAUYq6qUdMqkNEUPohYLbAu3eEetwAW9QYn53TWmj7
  creator-node/test/sync/assets/files/XTd/QmckKtz4nhmwsyFGNJ8pLpLSPPkgPGXq44bQRQwi75XTdp
  creator-node/test/sync/assets/files/ZJK/QmWbAbeaDGSM3LiARCKk2EWnLtgUqKcD3hK4nvHwdUZJK9
  creator-node/test/sync/assets/files/ZNj/QmYG4TY55oLoe5RjsABJmcUrAUWgyCc8jRpvBTWkT7ZNjH
  creator-node/test/sync/assets/files/aPa/QmcYCwJHfCScqDFEXd78hkdFbyn98mJWXhej4QhQx2aPaZ
  creator-node/test/sync/assets/files/c2i/QmaqSv1buZQ6enNwsae4B3paPDAXjcXZTRY6cUscPoc2ik
  creator-node/test/sync/assets/files/iRH/QmXLcCb5PTVtUusxtyo3pckJjCqeZKUt5VNv1FAbEdiRHn
  creator-node/test/sync/assets/files/n63/QmXyGwndsBXmM2xCW4VaWkRqp3pv4Cr6yAKfHnYDDTn63d
  creator-node/test/sync/assets/files/qgG/QmZJipWYtJDebvUbti2xSA3cijYxQ6YmVnkotA5SXiqgGF
  creator-node/test/sync/assets/files/sHo/QmdjBYvYirb4ANjK55ktmE4eokEKVsej9tjeWuZDxasHoh
  creator-node/test/sync/assets/files/wDS/QmZjt4SvTXhTqeoKTNPAKTPwfd8QadRWz9tjKXg9fEwDSY
  creator-node/test/sync/assets/files/xvg/QmVLLQTLByH65Ht2J3bKyFXZaKjUDho6742dSqk9nqxvgP
  creator-node/test/sync/assets/files/zHn/QmZw9kq8iVcVtNzRapsS9K3zRiaLNsa8bD9Dbw4QBXzHnJ
  creator-node/test/sync/assets/realExport.json
  creator-node/test/sync/assets/trackMetadata.json
  creator-node/test/sync/assets/userMetadata.json
Labels: size/XXL

#3456 Libs - Remove invalid Logger.verbose
  libs/package-lock.json
  libs/src/utils/types.ts
Labels: size/XS

#3458 Bump sdk to v0.0.15
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3459 Bump sdk version on content node to 0.0.15
  creator-node/package.json
Labels: size/XS

#3420 Use new Hedgehog custom local storage option
  libs/package-lock.json
  libs/package.json
  libs/src/api/account.js
  libs/src/libs.js
  libs/src/services/hedgehog/Hedgehog.ts
  libs/types/@audius-hedgehog/index.d.ts
Labels: size/L

#3463 Bump SDK to version 0.0.16
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3443 Renaming AudiusData Contract to EntityManager
  contracts/contracts/EntityManager.sol
  contracts/migrations/5_entity_manager_migration.js
  contracts/signature_schemas/signatureSchemas.js
  contracts/test/_lib/artifacts.js
  contracts/test/entityManager.js
Labels: size/M

#3468 Fix truncating null objects and update Bull Board
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/serviceRegistry.js
Labels: size/XS

#3471 Default write quorum to on for local
  creator-node/compose/env/base.env
Labels: content-node, size/XS

#3461 [PLAT-235] Remove IPLD blacklist mgr code
  discovery-provider/alembic/versions/b3f2c32a2796_remove_ipld_blacklist.py
  discovery-provider/default_config.ini
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/src/app.py
  discovery-provider/src/models/indexing/ipld_blacklist.py
  discovery-provider/src/models/indexing/ipld_blacklist_block.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/health_check.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/solana/solana_program_indexer.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_blacklist.py
  discovery-provider/src/tasks/ipld_blacklist.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/XL

#3473 Bump @audius/sdk to v0.0.17
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3426 CON-250 - stateMachine updates to consume primarySyncFromSecondary (Divergent state recovery #3)
  creator-node/default-config.json
  creator-node/src/config.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/XXL

#3467 [INF-180] Add SOCKS5 proxy for use with client
  dev-tools/audius-compose
  dev-tools/startup/discovery-provider.sh
  dev-tools/startup/socks5-proxy-pac.py
  discovery-provider/scripts/start.sh
  docker-compose.yml
Labels: infrastructure, size/M

#3485 Move trusted notifier init back to await-ed init
  creator-node/src/serviceRegistry.js
Labels: size/S

#3447 INF-86 Automate publishing libs in CircleCI
  .circleci/config.yml
  libs/scripts/release.sh
Labels: size/L

#3475 [PLAT-254] Remove is_creator usage across protocol
  discovery-provider/.test.env
  discovery-provider/alembic/versions/08becec375f3_remove_is_creator.py
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  discovery-provider/integration_tests/challenges/test_referral_challenge.py
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/integration_tests/queries/test_undisbursed_challeges.py
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/scripts/seed.py
  discovery-provider/scripts/test.sh
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_top_genre_users.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/user_event_constants.py
  identity-service/test/sendNotifications/mockLibs.js
  libs/src/api/account.js
  libs/src/api/user.js
  libs/src/api/user.test.js
  libs/src/sanityChecks/addSecondaries.js
  libs/src/sanityChecks/index.js
  libs/src/sanityChecks/isCreator.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/sanityChecks/sanitizeNodes.js
  libs/src/sanityChecks/syncNodes.js
  libs/src/sdk/api/generated/full/models/UserFull.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/userStateManager.ts
  libs/tests/userClientTest.js
  mad-dog/src/helpers.js
  mad-dog/src/tests/test_integration.js
  service-commands/src/commands/users.js
  service-commands/src/libs.js
  service-commands/src/utils/random.js
Labels: size/XL

#3483 Increase start.sh timeout
  discovery-provider/scripts/start.sh
Labels: size/XS

#3489 Fix migration ordering
  discovery-provider/alembic/versions/08becec375f3_remove_is_creator.py
Labels: size/XS

#3491 [INF-188] Verify contracts on POA for block explorer
  contracts/Dockerfile.dev
  contracts/package-lock.json
  contracts/package.json
  contracts/scripts/setup-predeployed-ganache.sh
  contracts/truffle-config.js
  dev-tools/startup/poa-ganache.sh
  docker-compose.yml
Labels: size/M

#3492 Cleanup output
  dev-tools/startup/poa-ganache.sh
Labels: size/XS

#3493 C-662 Throw error for function requiring window
  libs/src/services/wormhole/index.js
Labels: size/XS

#3496 Make new beatfile in each discovery node context
  discovery-provider/.dockerignore
  discovery-provider/scripts/start.sh
Labels: size/XS

#3499 Run image bake without monitoring
  .circleci/config.yml
Labels: size/XS

#3497 Always require syncMode to be defined
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/M

#3487 Misc state machine improvements / bug fixes
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/snapbackSM/secondarySyncHealthTracker.js
Labels: content-node, size/L

#3501 Fix CN nodejs version
  creator-node/Dockerfile
Labels: size/XS

#3498 Dont dedupe manual syncs
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
Labels: size/XS

#3502 Fix Hedgehog fn types
  libs/types/@audius-hedgehog/index.d.ts
Labels: size/XS

#3505 Fix unread count for tipping notifs
  identity-service/src/routes/notifications.js
Labels: size/XS

#3439 INF-173 Fix upload-dashboards.sh and support library panels
  monitoring/README.md
  monitoring/bin/setup-node
  monitoring/grafana/bin/save-dashboards.sh
  monitoring/grafana/bin/upload-dashboards.sh
  monitoring/grafana/bin/upload-library-panels.sh
  monitoring/grafana/dashboards/audius-boilerplate.json
  monitoring/grafana/dashboards/audius-discovery-provider-blockchain-indexing.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-task-details.json
  monitoring/grafana/dashboards/audius-discovery-provider-celery-tasks.json
  monitoring/grafana/dashboards/audius-discovery-provider-overview.json
  monitoring/grafana/dashboards/audius-network-monitoring.json
  monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json
  monitoring/grafana/dashboards/joaquin-network-monitoring-v2.json
  monitoring/grafana/dashboards/joaquin-playground.json
  monitoring/grafana/dashboards/library.json
  monitoring/scripts/up.sh
Labels: size/XXL

#3500 Add npmrc credential
  .circleci/config.yml
Labels: size/XS

#3462 [CON-221] Create metric to track users entirely on foundation nodes
  dev-tools/startup/socks5-proxy-pac.py
  discovery-provider/plugins/network-monitoring/README.md
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
Labels: size/M

#3508 INF-86 use new audius-infra ssh key for merging audius-sdk branches
  .circleci/config.yml
Labels: size/XS

#3511 INF-86 working publishing of audius-sdk
  .circleci/config.yml
  libs/scripts/release.sh
Labels: size/XS

#3507 Fix primarySyncFromSecondary circular dep by moving initAudiusLibs to separate file
  creator-node/package-lock.json
  creator-node/src/fileManager.js
  creator-node/src/middlewares.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/initAudiusLibs.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/test/sync.test.js
Labels: size/L

#3478 CON-258 Modify findSyncRequest.jobProcessor with more detailed metrics
  creator-node/package-lock.json
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/XL

#3518 Clean up misc state machine
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
Labels: content-node, size/XS

#3519 [CON-103] - Enable cid cache
  creator-node/compose/env/commonEnv.sh
  creator-node/src/config.js
  libs/initScripts/local.js
Labels: size/M

#3521 Increase write quorum timeout to 1m
  creator-node/src/config.js
Labels: content-node, size/XS

#3494 [CON-243] - Use prometheus middleware package to track route duration
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/app.js
  creator-node/src/routes/tracks.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/README.md
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/lib/app.js
  creator-node/test/prometheus.test.js
Labels: size/XL

#3520 [CON-262] Add more test coverage for /export
  creator-node/src/components/replicaSet/exportComponentService.js
  creator-node/src/routes/nodeSync.js
  creator-node/test/sync.test.js
Labels: size/XL

#3522 More state machine cleanup
  creator-node/default-config.json
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
Labels: content-node, size/L

#3524 [CON-233] Add queue history for all remaining queues
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/ImageProcessingQueue.js
  creator-node/src/TranscodingQueue.js
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/services/sync/syncQueue.js
Labels: size/M

#3515 [PAY-455] SDK: Convert TransactionHandler to TypeScript and export on core
  libs/src/core.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/services/solanaWeb3Manager/transactionHandler.ts
Labels: libs, size/L

#3529 Revert [PLAT-254] Remove is_creator usage across protocol (#3475)
  discovery-provider/.test.env
  discovery-provider/alembic/versions/08becec375f3_remove_is_creator.py
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  discovery-provider/integration_tests/challenges/test_referral_challenge.py
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/integration_tests/queries/test_undisbursed_challeges.py
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/scripts/seed.py
  discovery-provider/scripts/test.sh
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_top_genre_users.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/user_event_constants.py
  identity-service/test/sendNotifications/mockLibs.js
  libs/src/api/account.js
  libs/src/api/user.js
  libs/src/api/user.test.js
  libs/src/sanityChecks/addSecondaries.js
  libs/src/sanityChecks/index.js
  libs/src/sanityChecks/isCreator.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/sanityChecks/sanitizeNodes.js
  libs/src/sanityChecks/syncNodes.js
  libs/src/sdk/api/generated/full/models/UserFull.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/userStateManager.ts
  libs/tests/userClientTest.js
  mad-dog/src/helpers.js
  mad-dog/src/tests/test_integration.js
  service-commands/src/commands/users.js
  service-commands/src/libs.js
  service-commands/src/utils/random.js
Labels: size/XL

#3530 Revert Revert [PLAT-254] Remove is_creator usage across protocol
  discovery-provider/.test.env
  discovery-provider/alembic/versions/08becec375f3_remove_is_creator.py
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  discovery-provider/integration_tests/challenges/test_referral_challenge.py
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/integration_tests/queries/test_undisbursed_challeges.py
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/scripts/seed.py
  discovery-provider/scripts/test.sh
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_top_genre_users.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/user_event_constants.py
  identity-service/test/sendNotifications/mockLibs.js
  libs/src/api/account.js
  libs/src/api/user.js
  libs/src/api/user.test.js
  libs/src/sanityChecks/addSecondaries.js
  libs/src/sanityChecks/index.js
  libs/src/sanityChecks/isCreator.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/sanityChecks/sanitizeNodes.js
  libs/src/sanityChecks/syncNodes.js
  libs/src/sdk/api/generated/full/models/UserFull.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/userStateManager.ts
  libs/tests/userClientTest.js
  mad-dog/src/helpers.js
  mad-dog/src/tests/test_integration.js
  service-commands/src/commands/users.js
  service-commands/src/libs.js
  service-commands/src/utils/random.js
Labels: size/XL

#3531 Sanity check setIsCreatorToTrue
  libs/src/api/user.js
  libs/src/sanityChecks/index.js
  libs/src/sanityChecks/setIsCreatorToTrue.js
  libs/src/services/dataContracts/UserFactoryClient.ts
Labels: size/M

#3535 Add error msg to write quorum error logging
  creator-node/src/middlewares.js
Labels: size/XS

#3527 Only track metrics for explicit routes
  creator-node/src/app.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/contact.js
  creator-node/src/routes/files.js
  creator-node/src/routes/healthCheck.js
  creator-node/src/routes/index.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/routes/playlists.js
  creator-node/src/routes/prometheusMetricsRoutes.js
  creator-node/src/routes/tracks.js
  creator-node/src/routes/users.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.js
  creator-node/test/prometheus.test.js
Labels: size/XXL

#3523 [PAY-433] Fixed Ray's broken prod account
  discovery-provider/alembic/versions/ab56e2d974a6_fix_ray_account.py
Labels: size/S

#3525 [CON-265] Add percentage based metrics to network monitoring
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
Labels: size/L

#3537 CN - Fix export bug
  creator-node/src/components/replicaSet/exportComponentService.js
  creator-node/test/sync.test.js
Labels: size/M

#3540 Skip bad notifs
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: size/XS

#3541 Add force_export query param to /export route for MergePrimaryAndSecondary
  creator-node/src/components/replicaSet/exportComponentService.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
Labels: size/S

#3534 Fix bucketing fn + variable name change
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/prometheusMonitoring/prometheusUtils.js
Labels: size/S

#3532 Add prometheus metrics for `secondarySyncFromPrimary`
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/lib/app.js
  creator-node/test/sync.test.js
Labels: size/L

#3543 Fix prometheus metrics name error
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
Labels: size/XS

#3539 State machine - split queues and fix many bugs
  creator-node/compose/env/commonEnv.sh
  creator-node/default-config.json
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/monitors/stateMachine.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/processJob.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/processJob.test.js
  creator-node/test/snapbackSM.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: content-node, size/XXL

#3544 Add container-side pidfile for celery
  discovery-provider/scripts/start.sh
Labels: size/XS

#3548 Small improvements to the test-sdk ci job
  .circleci/config.yml
  libs/scripts/verify-types.sh
Labels: size/S

#3550 Log cnode to sp id map when determining replica set updates
  creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
Labels: size/S

#3549 [CON-294] Make manual sync queue less backed up
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
Labels: content-node, size/M

#3553 [CON-281] - Add CNodeToSpIdMapManager init in stateMachineManager init
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/test/CNodeToSpIdMapManager.test.js
Labels: size/S

#3546 [CON-283] Add upload success metrics
  creator-node/package.json
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
  creator-node/src/services/prometheusMonitoring/prometheusUtils.ts
  creator-node/test/AsyncProcessingQueue.test.js
  creator-node/test/lib/app.js
  creator-node/test/lib/asyncProcessingQueueMock.js
Labels: size/L

#3554 [CON-201] Remove QueueInterfacer + increase RS update concurrency
  creator-node/src/config.js
  creator-node/src/services/initAudiusLibs.js
  creator-node/src/services/stateMachineManager/QueueInterfacer.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: content-node, size/M

#3556 Factor _score in to script_score script
  discovery-provider/src/queries/search_es.py
Labels: size/XS

#3558 Unpin Python to fix discovery build
  discovery-provider/Dockerfile
Labels: size/S

#3559 Bump to version 0.3.63
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3561 Don't set the nginx cache in the application layer
  creator-node/Dockerfile
  creator-node/src/config.js
Labels: size/XS

#3562 CircleCI GCP image bake env var was undefined
  .circleci/config.yml
Labels: size/XS

#3557 [C-726] Consume typed @audius/hedgehog
  libs/package-lock.json
  libs/package.json
  libs/src/libs.js
  libs/src/services/hedgehog/Hedgehog.ts
  libs/src/utils/localStorage.ts
  libs/types/@audius-hedgehog/index.d.ts
Labels: size/L

#3565 [CON-295, CON-280] Typescriptify most of state machine & fix bugs
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/processJob.ts
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/SecondarySyncHealthTracker.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/services/stateMachineManager/types.ts
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/processJob.test.js
  creator-node/test/stateMonitoringUtils.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
  creator-node/tsconfig.json
Labels: content-node, size/XXL

#3564 Fix reactions
  identity-service/src/routes/reactions.js
Labels: size/S

#3566 Fixes for Discovery Dockerfile following alpine update
  discovery-provider/Dockerfile
  discovery-provider/requirements.txt
Labels: size/M

#3568 Fix upload track w prom metrics
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
Labels: size/S

#3569 Fix hedgehog privateKey access
  libs/src/services/wormhole/index.js
  service-commands/src/commands/seed/SeedSession.js
Labels: size/XS

#3377 Add tip email notifs
  identity-service/src/notifications/components/Body.jsx
  identity-service/src/notifications/components/notifications/Notification.jsx
  identity-service/src/notifications/constants.js
  identity-service/src/notifications/fetchNotificationMetadata.js
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/renderEmail/Body.js
  identity-service/src/notifications/renderEmail/notifications/Notification.js
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/routes/notifications.js
Labels: size/L

#3563 [C-324] Migrate solana service to typescript
  libs/.eslintrc
  libs/src/api/base.ts
  libs/src/api/rewards.js
  libs/src/core.ts
  libs/src/libs.js
  libs/src/services/identity/IdentityService.ts
  libs/src/services/solana/SolanaUtils.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solana/errors.ts
  libs/src/services/solana/index.ts
  libs/src/services/solana/padBNToUint8Array.ts
  libs/src/services/solana/rewards.ts
  libs/src/services/solana/rewardsAttester.ts
  libs/src/services/solana/tokenAccount.ts
  libs/src/services/solana/transactionHandler.ts
  libs/src/services/solana/transfer.ts
  libs/src/services/solana/userBank.ts
  libs/src/services/solana/wAudio.test.js
  libs/src/services/solana/wAudio.ts
  libs/src/services/solanaAudiusData/index.ts
  libs/src/services/solanaWeb3Manager/index.d.ts
  libs/src/services/solanaWeb3Manager/utils.d.ts
  libs/src/services/wormhole/index.js
  libs/src/utils/utils.ts
  libs/tests/rewardsAttesterTest.js
  service-commands/scripts/createSolanaUserBanks.js
Labels: size/XXL

#3528 Unwrap transaction signature from identity relay response
  libs/src/services/solana/transactionHandler.ts
Labels: size/XS

#3571 [CON-299] Fix reading clock of undefined
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/stateMachineUtils.test.js
Labels: content-node, size/L

#3560 [CON-289] Bug - cnodeUser.clock inconsistent with clockRecord data
  creator-node/sequelize/migrations/20220727182536-sync-inconsistent-clock-values.js
  creator-node/src/components/replicaSet/exportComponentService.js
  creator-node/src/dbManager.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/sync.test.js
Labels: size/M

#3572 Dont reissue manual syncs + separate manual sync timeout
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
Labels: size/M

#3578 Revert "Sanity check setIsCreatorToTrue (#3531)"
  libs/src/api/user.js
  libs/src/sanityChecks/index.js
  libs/src/sanityChecks/setIsCreatorToTrue.js
  libs/src/services/dataContracts/UserFactoryClient.ts
Labels: size/M

#3573 [CON-293] Allow selecting nodes with pre-existing state
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: content-node, size/M
