Repository AudiusProject/apps, pull requests merged in 2022-02, with the labels that each got.

#2414 Always submit get_metadata function to ThreadPoolExecutor
  discovery-provider/src/tasks/index.py
Labels: size/S

#2415 Do not redirect /notifications requests
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#2418 Modify listen tracking window and key lifetime
  identity-service/src/routes/trackListens.js
Labels: size/M

#2421 Fix wormhole rpc hosts
  libs/src/index.js
Labels: bug, libs, size/XS

#2422 Bump libs version to v1.2.62
  libs/package-lock.json
  libs/package.json
Labels: libs, size/XS

#2420 Add get_prev_track_entries query to batch query for notifications and add basic test
  discovery-provider/integration_tests/queries/test_get_prev_track_entries.py
  discovery-provider/src/queries/get_prev_track_entries.py
  discovery-provider/src/queries/notifications.py
Labels: size/L

#2425 Fix linting errors
  discovery-provider/integration_tests/queries/test_get_prev_track_entries.py
  discovery-provider/src/queries/get_prev_track_entries.py
Labels: size/L

#2423 Update libs dep
  identity-service/package-lock.json
  identity-service/package.json
Labels: identity-service, size/XS

#2395 Fix OpenResty on master; Use URL instead of Hostname
  discovery-provider/default_config.ini
  discovery-provider/nginx_conf/config.lua
  discovery-provider/nginx_conf/main.lua
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/scripts/start.sh
  discovery-provider/src/queries/get_redirect_weights.py
Labels: size/M

#2437 Bump worker connections to 4096
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#2424 Enable multiple feepayers for Solana relay
  identity-service/src/config.js
  identity-service/src/solana-client.js
  identity-service/test/configTest.js
  libs/initScripts/manageProdRelayerWallets.js
Labels: size/L

#2426 Add delay to rewardsAttester
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/tests/rewardsAttesterTest.js
Labels: size/L

#2438 Libs 1.2.63
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2439 Move solana relay funding to fundSolanaFeePayer.js and update sol_balance_check
  identity-service/scripts/fundSolanaFeePayer.js
  identity-service/src/routes/healthCheck.js
  libs/initScripts/manageProdRelayerWallets.js
Labels: size/L

#2441 Fix get-prev-track-entries call
  discovery-provider/src/queries/notifications.py
Labels: size/XS

#2427 Consume delayable attester in identity
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/app.js
  identity-service/src/remoteConfig.js
  identity-service/src/routes/healthCheck.js
  identity-service/src/utils/configureAttester.js
  libs/tests/index.js
  libs/tests/rewardsAttesterTest.js
Labels: size/L

#2352 Convert aggregate_track from matview to table
  discovery-provider/alembic/versions/dc7f691adc79_add_aggregate_track_table.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/queries/test_populate_track_metadata.py
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_track.py
  discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/aggregates/__init__.py
  discovery-provider/src/tasks/aggregates/index_aggregate_plays.py
  discovery-provider/src/tasks/aggregates/index_aggregate_track.py
  discovery-provider/src/tasks/index_aggregate_plays.py
  discovery-provider/src/tasks/index_aggregate_views.py
  service-commands/scripts/find-alembic-changes.sh
Labels: size/XXL

#2436 Identity wormhole fix
  identity-service/src/app.js
  identity-service/src/routes/wormhole.js
Labels: size/XS

#2417 Remove previous ML51L trending strategy
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/src/trending_strategies/ML51L_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/ML51L_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/ML51L_underground_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/L

#2347 Drop aggregate_interval_plays year count column
  discovery-provider/alembic/versions/98e2a0a25ada_drop_aggregate_interval_plays_year_count.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/models/aggregate_interval_play.py
Labels: size/L

#2385 [AUD-1374] [AUD-1372] Add new favorites endpoints and include referenced metadata
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/api/v1/models/favorites.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_saves.py
Labels: discovery-node, size/L

#2445 Add user bank to API responses
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/user_bank.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
Labels: size/M

#2449 Move create_new_challenges init to fix race condition
  discovery-provider/src/app.py
Labels: size/S

#2451 [AUD-1448] - Fetch blockhash with confirmed state
  identity-service/src/solana-client.js
Labels: size/XS

#2456 Refactor RewardsAttester to support clientside flow
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/tests/rewardsAttesterTest.js
Labels: size/L

#2457 Libs 1.2.64
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2458 Revert "Add missing functions and use them"
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/tests/audius-data.ts
Labels: size/L

#2460 Revert "[ASI-756] PR #3 - Update snapback logic to consume filesHash (#2186)"
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/snapbackSM/computeSyncModeForUserAndReplica.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/snapbackSM/snapbackSM.test.js
  creator-node/test/snapbackSM.test.js
Labels: size/XL

#2463 Bump libs to v1.2.65
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2455 [AUD-1463][ASI-847] Refactor anchor typescript code
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/L

#2468 Improve attestation error handling
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2469 Libs 1.2.66
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2453 Support Multiple Fee Payers
  identity-service/default-config.json
  identity-service/src/audiusLibsInstance.js
  identity-service/src/config.js
  identity-service/src/routes/healthCheck.js
  identity-service/src/routes/solana.js
  identity-service/src/routes/wormhole.js
  identity-service/src/solana-client.js
  identity-service/test/configTest.js
  libs/src/api/account.js
  libs/src/api/rewards.js
  libs/src/index.js
  libs/src/services/identity/index.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/src/services/solanaWeb3Manager/userBank.js
  libs/src/services/solanaWeb3Manager/utils.js
  service-commands/scripts/createSolanaUserBanks.js
  service-commands/scripts/rewardManagerLocal.js
  service-commands/src/utils/constants.js
  service-commands/src/utils/seed.js
  solana-programs/.gitignore
  solana-programs/reward-manager/README.md
  solana-programs/start.sh
Labels: size/L

#2475 Bump libs in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2476 Fix fee payer
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/S

#2477 Libs 1.2.68
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2478 Wire up sendAttestationResult in libs
  libs/src/api/rewards.js
  libs/src/services/identity/index.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2480 Libs 1.2.69
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2479 Add attestation_result route
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/routes/rewards.js
  identity-service/src/utils/configureAttester.js
  identity-service/src/utils/rewardsReporter.js
Labels: size/M

#2473 Ignore non-existant tracks while calc listen count milestones
  discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py
  discovery-provider/src/tasks/index_listen_count_milestones.py
Labels: bug, discovery-node, size/S

#2450 Identity ref-v notifications
  identity-service/src/notifications/components/notifications/Notification.jsx
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/renderEmail/notifications/Notification.js
  identity-service/test/emailNotifications/renderEmail.js
  identity-service/test/emailNotifications/renderedEmails/additionalChallengeEmail.html
  identity-service/test/emailNotifications/renderedEmails/challengeEmail.html
  identity-service/test/sendNotifications/index.js
  identity-service/test/sendNotifications/mockNotifications/challengeReward.json
Labels: identity-service, size/M

#2472 Optimize identity sending emails
  identity-service/package.json
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/notifications/utils.js
  identity-service/test/index.js
  identity-service/test/sendNotifications/mockExpress.js
  identity-service/test/sendNotifications/sendNotificationEmail.js
Labels: identity-service, size/L

#2484 Revert "[AUD-1374] [AUD-1372] Add new favorites endpoints and include referenced metadata"
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/api/v1/models/favorites.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_saves.py
Labels: size/L

#2485 Add `aup` alias for local setup
  service-commands/scripts/.zshrc
Labels: size/S

#2483 [AUD-1516] Fix fee payer bug
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/XS

#2486 Bump libs
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2487 Consume libs 1.2.71 in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2489 SnapbackSM log nit
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/XS

#2488 Add logs for playlist update notifications
  identity-service/src/notifications/processNotifications/playlistUpdateNotification.js
Labels: size/S

#2482 Add analytics for Identity Attesting
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/analytics.js
  identity-service/src/config.js
  identity-service/src/utils/rewardsReporter.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/L

#2491 Use Alpine Linux mirror for Identity
  identity-service/Dockerfile
Labels: size/XS

#2492 Fix transaction handler bug
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/S

#2493 Libs 1.2.72
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2494 Consume libs 1.2.72 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2496 Harden openresty code
  discovery-provider/nginx_conf/main.lua
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/src/queries/get_redirect_weights.py
Labels: size/M

#2498 Fix notifications
  discovery-provider/integration_tests/queries/test_get_prev_track_entries.py
  discovery-provider/src/queries/get_prev_track_entries.py
Labels: size/M

#2443 [AUD-1178] Remove old /unlisted endpoint on content node in libs
  libs/src/api/track.js
  libs/src/services/creatorNode/index.js
Labels: size/S

#2490 [ASI-858] Add dataProviderUrl config to CN health check
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
Labels: size/XS

#2499 Move parallelization to optimizely
  identity-service/src/config.js
  identity-service/src/remoteConfig.js
  identity-service/src/utils/configureAttester.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2500 Bump libs
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2501 Consume latest libs in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2503 Improve attestation logging
  identity-service/src/analytics.js
  identity-service/src/routes/rewards.js
  identity-service/src/utils/rewardsReporter.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2505 Libs 1.2.74
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2507 Consume libs 1.2.74
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2508 Do not redirect challenges
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#2509 Stop sending blockhash for rewards
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/S

#2510 Libs 1.2.75
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2511 Migration to backfill mobile install
  discovery-provider/alembic/versions/d3325cbc0bec_backfill_mobile_app_install_challenge.py
Labels: size/M

#2512 [AUD-1536] Don't override step count if complete
  discovery-provider/src/queries/get_challenges.py
Labels: size/S

#2513 [AUD-1540] Skip if user not found instead of error (reward manager)
  discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/M

#2516 Fix attester starting block
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/S

#2517 Libs 1.2.76
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2519 Recalculate challenges
  discovery-provider/alembic/versions/d180b0c624de_recalculate_challenge_step_counts.py
Labels: size/M

#2518 [AUD-1540] Skip if user not found instead of error (reward manager)
  discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/M

#2520 Include missing DN attestation error type
  libs/src/api/rewards.js
Labels: size/XS

#2521 Libs 1.2.77
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2522 Consume libs 1.2.77
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2524 Update wormhole error slack url to match new channel
  identity-service/src/app.js
  identity-service/src/config.js
  identity-service/src/routes/wormhole.js
Labels: size/S

#2495 Refactor more anchor typescript
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
Labels: size/XL

#2515 Add wallet provision step to discovery node web server setup
  service-commands/src/commands/service-commands.json
Labels: size/XS

#2527 Add timeout to discovery indexing redis lock
  discovery-provider/src/tasks/index.py
Labels: size/XS

#2526 Fix referrals challenge
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#2528 Avoid NoneType URSM
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#2531 Fix current user query
  discovery-provider/src/queries/get_user_history.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#2532 Fix current user query (#2531)
  discovery-provider/src/queries/get_user_history.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#2529 Add unhealthy block diff to libs
  libs/src/index.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
  libs/src/services/discoveryProvider/constants.js
  libs/src/services/discoveryProvider/index.js
Labels: libs, size/M

#2533 Bump libs version to v1.2.78
  libs/package-lock.json
  libs/package.json
Labels: libs, size/XS

#2536 Add is_current in additional missing spot
  discovery-provider/src/tasks/users.py
Labels: size/XS

#2538 Dont wipe state on secondary until divergent state merged
  creator-node/src/services/sync/processSync.js
Labels: size/S

#2540 Decrease reward aggregation attempts in Identity
  identity-service/src/utils/configureAttester.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/S

#2542 Libs 1.2.79
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2544 Consume libs 1.2.79
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2539 User signup logs
  libs/src/api/user.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
Labels: size/M

#2547 Upgrade libs in content-node to 1.2.80
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/serviceRegistry.js
Labels: size/S

#2546 Shift libs user signup from Discprov indexing to direct chain call
  libs/src/api/user.js
  libs/src/utils/utils.js
Labels: size/L

#2514 [AUD-1420] Adds does_follow_current_user boolean to user API response
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/M

#2541 Use selection logic on whitelist
  libs/src/api/serviceProvider.js
  libs/src/service-selection/ServiceSelection.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2553 Bump libs to 1.2.82
  libs/package.json
Labels: size/XS

#2554 Libs 1.2.82
  libs/package-lock.json
Labels: size/XS

#2559 Add fetch ipfs timeout and optimize user indexing
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/users.py
Labels: size/M

#2562 Libs 1.2.85
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2563 Fix autocomplete search regression
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#2564 Fix total balance & user balance indexing
  discovery-provider/src/queries/get_balances.py
  discovery-provider/src/tasks/cache_user_balance.py
  discovery-provider/src/utils/spl_audio.py
Labels: size/M

#2565 [AUD-1584] Parallel user tx processing
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/ipfs_lib.py
Labels: size/L

#2560 Limit IG and Twitter verification to one Audius acct per social acct
  identity-service/src/featureFlag.js
  identity-service/src/routes/instagram.js
  identity-service/src/routes/solana.js
  identity-service/src/routes/twitter.js
  identity-service/src/utils/relayHelpers.js
  identity-service/test/index.js
  identity-service/test/lib/instructionMocks.js
  identity-service/test/routes/solanaTest.js
  identity-service/test/sendNotifications/sendNotificationEmail.js
Labels: size/XL

#2568 Improve timeouts
  discovery-provider/default_config.ini
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/ipfs_lib.py
Labels: size/L

#2572 Fix auth middleware bug in solana relay
  identity-service/src/authMiddleware.js
  identity-service/src/routes/solana.js
  identity-service/test/routes/solanaTest.js
Labels: size/L

#2570 Remove IPFS from discovery node critical paths
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/utils/test_ipfs_functionality.py
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/ipfs_lib.py
Labels: size/XXL

#2571 Timing decision tree logging for getCID
  creator-node/src/routes/files.js
Labels: size/L

#2573 Index perf tracking
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/utils/index_blocks_performance.py
Labels: size/M

#2576 CN make getCID log info level + remove unused import
  creator-node/src/routes/files.js
Labels: size/XS

#2574 Allow non verified insta link
  identity-service/src/routes/instagram.js
Labels: size/XS

#2552 IssueSyncRequestsToSecondaries error log
  creator-node/src/middlewares.js
Labels: size/S

#2579 CN CID fetch - do FS check before DB check
  creator-node/src/diskManager.js
  creator-node/src/routes/files.js
Labels: size/L

#2580 Fix CN CID Fetch - DB Dir case
  creator-node/src/routes/files.js
Labels: size/S

#2584 Increase ethWeb3Manager max gas limit
  libs/src/services/ethWeb3Manager/index.js
Labels: size/XS

#2583 Make unique ids across accounts
  identity-service/sequelize/migrations/20220222034002-add-cognito-flow-identities-table.js
  identity-service/src/config.js
  identity-service/src/models/cognitoFlowIdentities.js
  identity-service/src/routes/cognito.js
  identity-service/src/utils/cognitoHelpers.js
Labels: size/L

#2588 Consume libs 1.2.85 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2586 Fix CID fetch invalid CID hanging
  creator-node/src/routes/files.js
Labels: size/S

#2590 fix getCID Regression
  creator-node/src/routes/files.js
Labels: size/XS

#2592 install yq for load-test-tools
  service-commands/scripts/provision-dev-env.sh
Labels: size/XS

#2598 Update libs to 1.2.86
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2596 Consume libs 1.2.86 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2378 Add prune plays task
  discovery-provider/alembic/versions/df4709b4391b_create_archived_plays_table.py
  discovery-provider/integration_tests/tasks/test_prune_plays.py
  discovery-provider/src/app.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/models.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/queries/get_oldest_unarchived_play.py
  discovery-provider/src/tasks/prune_plays.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/L

#2595 Change update playlists to be bulk query
  identity-service/src/notifications/processNotifications/playlistUpdateNotification.js
Labels: size/M

#2600 Speed up playlist updates by removing reduce
  identity-service/src/notifications/processNotifications/playlistUpdateNotification.js
Labels: size/M

#2601 Increase gunicorn timeout and add notif logging
  discovery-provider/scripts/prod-server.sh
  discovery-provider/src/queries/notifications.py
Labels: size/M

#2502 Cleanup transfer script
  libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
Labels: size/XS

#2604 Use lightning verification values for identity
  identity-service/src/routes/cognito.js
Labels: size/S

#2593 Reduce cache timeout
  creator-node/nginx_conf/nginx.conf
Labels: size/S

#2587 [ASI-851] Upgrade anchor to v0.22.x
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/programs/audius-data/Cargo.toml
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/yarn.lock
Labels: size/L

#2607 Fix attester endpoint bug
  identity-service/src/utils/configureAttester.js
Labels: size/XS

#2605 Change SMEMBERS to SCARD in discovery health check
  discovery-provider/src/queries/get_health.py
Labels: size/XS

#2606 Reconcile release-v0.3.52 with mainline (part 1)
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/utils/test_ipfs_functionality.py
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/index_blocks_performance.py
  discovery-provider/src/utils/ipfs_lib.py
Labels: size/XXL

#2597 [PAY-32] Fix resp.data undefined error
  libs/src/services/identity/index.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/XS

#2504 Expose metrics for prometheus
  discovery-provider/Dockerfile
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_user.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/queries/prometheus_metrics_exporter.py
  discovery-provider/src/tasks/aggregates/__init__.py
  discovery-provider/src/tasks/aggregates/index_aggregate_plays.py
  discovery-provider/src/tasks/aggregates/index_aggregate_track.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_aggregate_user.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/utils/prometheus_metric.py
  discovery-provider/src/utils/redis_metrics.py
  discovery-provider/src/wsgi.py
  service-commands/scripts/requirements.txt
Labels: size/L

#2617 fix slow query for get followers followees
  discovery-provider/src/queries/get_followees_for_user.py
  discovery-provider/src/queries/get_followers_for_user.py
Labels: size/L

#2618 Add logging reminder to PR template
  .github/pull_request_template.md
Labels: size/XS

#2616 issue sync requests on metadata upload
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/tracks.js
Labels: size/XS

#2619 top playlists uses aggregate table
  discovery-provider/src/queries/get_top_playlists.py
Labels: size/S

#2615 [AUD-1203] Add admin account writes enabled flag for user creation
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
Labels: size/L

#2612 Add endpoint to retry flow session for handle
  identity-service/src/cognitoFlowMiddleware.js
  identity-service/src/config.js
  identity-service/src/routes/cognito.js
Labels: size/L

#2621 fix windowed track query
  discovery-provider/src/queries/get_top_followee_windowed.py
Labels: size/S

#2625 Add indices for users and cognito flows
  identity-service/sequelize/migrations/20220227180347-add-indices.js
  identity-service/src/models/InstagramUser.js
  identity-service/src/models/cognitoFlows.js
  identity-service/src/models/notificationemail.js
  identity-service/src/models/twitterUser.js
  identity-service/src/models/user.js
Labels: size/M

#2626 Add log for indexing commit time
  discovery-provider/src/tasks/index.py
Labels: size/XS

#2623 Add util in libs to convert from on chain digest -> CID
  libs/src/utils/utils.js
  libs/src/utils/utils.test.js
Labels: size/M

#2628 Add more logs to index_blocks
  discovery-provider/src/tasks/index.py
Labels: size/M

#2631 Fix send email logs / model
  identity-service/src/models/notificationemail.js
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/test/sendNotifications/sendNotificationEmail.js
Labels: bug, identity-service, size/M

#2613 Fix indexing integration tests
  discovery-provider/integration_tests/tasks/test_index_operations.py
Labels: size/XXL

#2630 Move contract init to start of indexing
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
Labels: size/L
