Repository AudiusProject/apps, pull requests merged in 2022-04, with the labels that each got.

#2785 Port RewardsAttester to typescript
  libs/.eslintrc
  libs/src/api/rewards.d.ts
  libs/src/api/rewards.js
  libs/src/index.js
  libs/src/service-selection/ServiceSelection.ts
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
  libs/src/utils/network.ts
  libs/tests/rewardsAttesterTest.js
Labels: size/XXL

#2799 Prepare Metrics API for typegen
  discovery-provider/src/api/v1/metrics.py
Labels: size/S

#2778 [AUD-1375] Prepare User and Track APIs for Type Generation
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/api/v1/utils/resolve_url.py
Labels: size/XL

#2797 Prepare Playlist API for Typegen
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/playlists.py
Labels: size/L

#2798 Prepare Resolve API for Type gen
  discovery-provider/src/api/v1/resolve.py
Labels: size/S

#2795 [ASI-945] Remove more IPFS functionality
  creator-node/sequelize/migrations/20200623002237-add-parent-file-data.js
  creator-node/src/app.js
  creator-node/src/components/tracks/trackContentUploadManager.js
  creator-node/src/config.js
  creator-node/src/fileHasher.js
  creator-node/src/fileManager.js
  creator-node/src/index.ts
  creator-node/src/ipfsClient.js
  creator-node/src/monitors/ipfs.js
  creator-node/src/monitors/monitors.js
  creator-node/src/pinCID.js
  creator-node/src/resizeImage.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/files.js
  creator-node/src/routes/healthCheck.js
  creator-node/src/routes/nodeSync.js
  creator-node/src/routes/tracks.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/sync/processSync.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/src/utils.js
  creator-node/test/audiusUsers.test.js
  creator-node/test/blacklistManager.test.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/ensureStorageMiddleware.test.js
  creator-node/test/expressApp.test.js
  creator-node/test/fileHasher.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/ipfsAdd.test.js
  creator-node/test/lib/app.js
  creator-node/test/lib/ipfsMock.js
  creator-node/test/nodesync.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
  creator-node/test/sessionManager.test.js
  creator-node/test/snapbackSM.test.js
  creator-node/test/syncAssets/sampleExport.json
  creator-node/test/syncAssets/sampleExportDummyCID.json
  creator-node/test/syncAssets/sampleExportDummyCIDFromClock2.json
  creator-node/test/users.test.js
  mad-dog/config.js
  mad-dog/package-lock.json
  mad-dog/package.json
  mad-dog/src/ipfsClient.js
  mad-dog/src/tests/test_ipldBlacklist.js
  mad-dog/src/utils/fileHasher.js
Labels: requires-special-attention, size/XXL

#2780 Run seed CLI in circleci
  .circleci/config.yml
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
Labels: size/XL

#2801 Update AAO error types for rewards
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
Labels: size/S

#2808 Bump libs to 1.2.98
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2731 [AUD-1752] Build @audius/anchor-audius-data with rollup
  solana-programs/.gitignore
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/rollup.config.js
  solana-programs/anchor/audius-data/tsconfig.json
Labels: size/M

#2806 [AUD-1795] Apply prettier to typescript files in libs
  libs/.eslintrc
  libs/.prettierrc.js
  libs/package-lock.json
  libs/package.json
  libs/src/api/rewards.d.ts
  libs/src/service-selection/ServiceSelection.test.ts
  libs/src/service-selection/ServiceSelection.ts
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
  libs/src/utils/apiSigning.ts
  libs/src/utils/captcha.ts
  libs/src/utils/estimateGas.ts
  libs/src/utils/importContractABI.d.ts
  libs/src/utils/multiProvider.ts
  libs/src/utils/network.test.ts
  libs/src/utils/network.ts
  libs/src/utils/promiseFight.test.ts
  libs/src/utils/promiseFight.ts
  libs/src/utils/signatures.ts
  libs/src/utils/utils.test.ts
  libs/src/utils/utils.ts
Labels: size/XXL

#2809 Update get_transaction to be base64
  discovery-provider/solana-tx-parser/tx_parser.py
  discovery-provider/solana-tx-parser/utils.py
Labels: size/M

#2811 Update AAO error types
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
Labels: size/S

#2812 Bump libs to 1.2.99
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2814 Prepare Search API for type gen
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/search.py
Labels: size/M

#2818 Fix ts import
  libs/examples/initAudiusLibs.js
Labels: size/S

#2807 Prepare Challenges API for typegen
  discovery-provider/src/api/v1/challenges.py
Labels: size/M

#2822 More API documentation cleanup
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/search.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
Labels: size/M

#2786 Add test to ensure documentation for API
  discovery-provider/src/api/v1/api_unit_test.py
Labels: size/L

#2787 Add lint check plugin for DN API endpoints
  discovery-provider/.vscode/settings.json
  discovery-provider/flake8_plugins/__init__.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/README.md
  discovery-provider/flake8_plugins/flask_decorator_plugin/__init__.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/flask_decorator_plugin.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/flask_decorator_plugin_test.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/visitor.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/visitor_helpers.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  setup.cfg
Labels: size/XL

#2816 [ASI-837] Allow typescript + javascript interoperability in content-node
  creator-node/scripts/run-tests.sh
  creator-node/src/hashids.ts
  creator-node/src/routes/tracks.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/tsconfig.json
Labels: size/M

#2817 Update AAO error types, include unknown response
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
Labels: size/XS

#2827 Bump libs to 1.2.100
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2829 Bump libs to 101
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2444 [AUD-1444] Update instruction loaders
  .circleci/config.yml
  solana-programs/Dockerfile
  solana-programs/audius_eth_registry/Cargo.lock
  solana-programs/audius_eth_registry/Cargo.toml
  solana-programs/audius_eth_registry/src/processor.rs
  solana-programs/audius_eth_registry/tests/tests.rs
  solana-programs/claimable-tokens/cli/Cargo.lock
  solana-programs/claimable-tokens/cli/Cargo.toml
  solana-programs/claimable-tokens/program/Cargo.lock
  solana-programs/claimable-tokens/program/Cargo.toml
  solana-programs/claimable-tokens/program/src/error.rs
  solana-programs/claimable-tokens/program/src/processor.rs
  solana-programs/claimable-tokens/program/tests/tests.rs
  solana-programs/cli/Cargo.toml
  solana-programs/reward-manager/cli/Cargo.toml
  solana-programs/reward-manager/program/Cargo.toml
  solana-programs/reward-manager/program/src/error.rs
  solana-programs/reward-manager/program/src/utils/signs.rs
  solana-programs/reward-manager/program/tests/verify_transfer_signature.rs
Labels: size/L

#2828 Consume libs 1.2.101
  identity-service/package-lock.json
  identity-service/package.json
  libs/package.json
Labels: size/XS

#2793 Discovery solana DB slot migration
  discovery-provider/alembic/versions/11060779bb3a_solana_slots_migration.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/models.py
  discovery-provider/src/models/user_events.py
  discovery-provider/src/tasks/users.py
Labels: discovery-node, size/L

#2821 [AUD-1808] Refactor CreatorNodeSelection to typescript
  libs/package.json
  libs/src/service-selection/ServiceSelection.ts
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/creatorNode/constants.js
  libs/src/services/creatorNode/constants.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
  libs/src/utils/index.ts
  libs/src/utils/network.ts
Labels: size/XL

#2819 Refactor fetching CID metadata into util
  discovery-provider/integration_tests/challenges/index_helpers.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_blacklist.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/ipld_blacklist.py
  discovery-provider/src/utils/cid_metadata_client.py
Labels: size/L

#2831 Add user subscription to audius data program
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/user-social-actions.ts
Labels: size/L

#2815 [ASI-986] Calculate intersection logic for audius_data_txs table
  discovery-provider/Dockerfile
  discovery-provider/default_config.ini
  discovery-provider/idl/audius_data.json
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/models/models.py
  discovery-provider/src/solana/anchor_parser.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/solana/solana_program_indexer.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/tasks/index_solana_user_data.py
  discovery-provider/src/utils/helpers.py
  libs/initScripts/configureLocalDiscProv.js
  service-commands/src/commands/service-commands.json
Labels: size/XXL

#2843 Updating solana web3py to get_transaction from get_confirmed_transaction
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/solana/solana_client_manager_unit_test.py
Labels: size/S

#2842 Add delegation functions to lib
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/XXL

#2840 [ASI-1021] Fix init-repos installation and linking
  contracts/package-lock.json
  mad-dog/package.json
  service-commands/scripts/init-repos.sh
Labels: size/M

#2846 [PAY-30] Fix attester offset calculation error
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
  libs/tests/rewardsAttesterTest.js
Labels: size/L

#2847 [] update `utils.sh` to reflect recent gcloud changes
  service-commands/scripts/utils.sh
Labels: size/XS

#2824 Extract fileHasher util to libs
  libs/.gitignore
  libs/package-lock.json
  libs/package.json
  libs/src/utils/fileHasher.ts
  libs/src/utils/utils.ts
  libs/tests/assets/static_image.png
  libs/tests/assets/static_text.txt
  libs/tests/fileHasherTest.js
  libs/tests/index.js
Labels: size/L

#2850 Remove userbank creation signup feature flag
  libs/src/api/account.js
Labels: size/XS

#2851 Libs 1.2.102
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2826 [ASI-1012] GovernanceV2 contract + delegate_manager_v2_migration.js bugfix + additional test coverage
  eth-contracts/contracts/GovernanceV2.sol
  eth-contracts/migrations/13_delegate_manager_v2_migration.js
  eth-contracts/migrations/14_governance_v2_migration.js
  eth-contracts/test/delegateManager.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/trustedNotifierManager.test.js
  eth-contracts/test/upgradeability.test.js
Labels: size/XXL

#2849 Add admin storage public key to local disc prov config
  discovery-provider/default_config.ini
  libs/initScripts/configureLocalDiscProv.js
  solana-programs/start.sh
Labels: size/M

#2841 Initialize content node identity in audius-data program local setup
  .circleci/config.yml
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/constants.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
Labels: size/L

#2858 [] fix typo
  libs/src/services/creatorNode/index.js
Labels: size/XS

#2852 Libs 1.2.103
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2853 Consume libs 1.2.103 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2848 [PAY-106] Fix error propagation
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
  libs/tests/rewardsAttesterTest.js
Labels: size/L

#2864 Fix libs browser config
  libs/package.json
Labels: size/XS

#2861 [ASI-976] [REPLICA] Fix StateMachineQueue unreliability + expose stateMachineQueue status via health check
  creator-node/compose/env/base.env
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/config.js
  creator-node/src/monitors/monitors.js
  creator-node/src/monitors/stateMachine.js
  creator-node/src/redis.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/L

#2447 [ASI-836] [CN] Add reconfigNodewhitelist envvar & consume in reconfig
  creator-node/src/config.js
  creator-node/src/snapbackSM/snapbackSM.js
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
Labels: size/M

#2865 Consume libs 1.2.104 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2863 [ASI-1023] Testing for updated indexing class
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
Labels: size/L

#2825 [ASI-1013] Remove remaining IPFS from creator-node
  creator-node/Dockerfile
  creator-node/README.md
  creator-node/compose/default-config.json
  creator-node/compose/env/base.env
  creator-node/default-config.json
  creator-node/nginx_conf/nginx.conf
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  creator-node/scripts/start.sh
  creator-node/src/components/tracks/trackContentUploadManager.js
  creator-node/src/config.js
  creator-node/src/fileHasher.js
  creator-node/src/fileManager.js
  creator-node/src/logging.js
  creator-node/src/models/file.js
  creator-node/src/resizeImage.js
  creator-node/src/routes/files.js
  creator-node/src/utils.js
  creator-node/test/dbManager.test.js
  creator-node/test/fileHasher.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
  mad-dog/src/tests/test_ipldBlacklist.js
  mad-dog/src/utils/fileHasher.js
Labels: size/XL

#2866 Update anchor parser to map account names and pubkeys
  discovery-provider/src/solana/anchor_parser.py
  discovery-provider/src/solana/anchor_program_indexer.py
Labels: size/L

#2868 Add create user and udpate admin cli bindings
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/M

#2870 Fix User ID url params
  discovery-provider/src/api/v1/users.py
Labels: size/M

#2860 Set default WASM to fix error with wormhole sdk
  libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
Labels: size/XS

#2856 [AUD-1828] Remove routes from external documentation
  discovery-provider/flake8_plugins/flask_decorator_plugin/flask_decorator_plugin_test.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/visitor.py
  discovery-provider/flake8_plugins/flask_decorator_plugin/visitor_helpers.py
  discovery-provider/src/api/v1/challenges.py
  discovery-provider/src/api/v1/metrics.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
Labels: size/L

#2830 Update libs to return transactions
  .circleci/config.yml
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
  solana-programs/anchor/audius-data/tests/user-social-actions.ts
Labels: size/XXL

#2855 [AUD-1833] Refactor "Get Tracks" endpoint
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/utils/resolve_url.py
Labels: discovery-node, size/L

#2862 Add deterministic ganache account generation and URSM initContentNode…
  service-commands/src/commands/service-commands.json
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/constants.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/scripts/build-dev.sh
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
  solana-programs/start.sh
Labels: size/L

#2839 [AUD-1814] Refactor CreatorNode to typescript
  libs/package-lock.json
  libs/package.json
  libs/src/api/account.js
  libs/src/api/serviceProvider.js
  libs/src/api/track.js
  libs/src/api/user.js
  libs/src/constants.js
  libs/src/constants.ts
  libs/src/index.js
  libs/src/sanityChecks/addSecondaries.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/sanityChecks/syncNodes.js
  libs/src/services/ABIDecoder/index.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/creatorNode/index.ts
  libs/src/services/schemaValidator/SchemaValidator.ts
  libs/src/services/schemaValidator/index.js
  libs/src/services/schemaValidator/index.ts
  libs/src/services/web3Manager/index.d.ts
  libs/src/services/web3Manager/index.js
  libs/src/userStateManager.ts
  libs/src/utils/importContractABI.d.ts
  libs/src/utils/index.ts
  libs/tsconfig.json
  libs/types/abi-decoder/index.d.ts
Labels: size/XXL

#2867 Add instruction validation to anchor program indexer
  discovery-provider/src/app.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/solana_program_indexer.py
Labels: size/M

#2875 Fix anchor program indexer test by passing admin key
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
Labels: size/S

#2874 Fix attester stall
  identity-service/src/routes/healthCheck.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
Labels: size/S

#2877 Add DN Node registration job to Identity
  identity-service/src/app.js
  identity-service/src/solanaNodeRegistration.js
Labels: size/M

#2878 Libs 1.2.105
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2880 Consume Libs 1.2.105 in Identity
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/routes/healthCheck.js
Labels: size/XS

#2883 Fix stateMachineQueue health check
  creator-node/src/components/healthCheck/healthCheckController.js
Labels: size/XS

#2871 [ASI-1007] remove `getMode()` and default to `--run-all`
  creator-node/src/index.ts
Labels: size/M

#2881 Fix rollup babel config
  libs/babel.config.js
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
Labels: size/XS

#2884 Update .zshrc to remove `aup` alias
  service-commands/scripts/.zshrc
Labels: size/S

#2889 [AUD-1451] Add new playlist trending strategy
  discovery-provider/src/queries/get_trending_playlists.py
  discovery-provider/src/trending_strategies/BDNxn_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/M

#2893 Split solana slot migration
  discovery-provider/alembic/versions/11060779bb3a_solana_slots_migration.py
  discovery-provider/alembic/versions/2cfd17a60647_solana_slot_follows.py
  discovery-provider/alembic/versions/2dbbc9c484e3_solana_slot_tracks.py
  discovery-provider/alembic/versions/3a3f2c9f5320_solana_slot_playlists.py
  discovery-provider/alembic/versions/a9215207bb7c_solana_slot_socials.py
Labels: discovery-node, size/L

#2879 [PAY-105] Fix create sender public
  libs/src/api/rewards.js
  libs/src/api/serviceProvider.js
  libs/src/services/identity/index.js
Labels: size/S

#2897 Fix create user seed session command
  service-commands/src/commands/seed/SeedSession.js
Labels: size/XS

#2894 Bump @audius/libs v1.2.106
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2854 [ASI-991] Create SOL pubKey with delegatePrivateKey as seed
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  creator-node/src/index.ts
Labels: size/M

#2823 [AUD-1809] Publish audius-data types
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/rollup.config.js
Labels: size/L

#2886 Add metadata fetching to anchor program indexer
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/app.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/solana_program_indexer.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/utils/cid_metadata_client.py
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/L

#2895 Add txhash to slot tx migration
  discovery-provider/alembic/versions/11060779bb3a_solana_slots_migration.py
  discovery-provider/alembic/versions/2cfd17a60647_solana_slot_follows.py
  discovery-provider/alembic/versions/2dbbc9c484e3_solana_slot_tracks.py
  discovery-provider/alembic/versions/3a3f2c9f5320_solana_slot_playlists.py
  discovery-provider/alembic/versions/a9215207bb7c_solana_slot_socials.py
Labels: discovery-node, size/S

#2896 [ASI-1024] - Improve tx submission retry policy
  identity-service/package.json
  identity-service/src/featureFlag.js
  identity-service/src/routes/trackListens.js
  identity-service/src/solana-client.js
  identity-service/test/routes/trackListensTest.js
Labels: size/L

#2908 [ASI-1024] Max retries explicitly to 0 in TrackListen sendRawTransaction
  identity-service/src/solana-client.js
Labels: size/XS

#2909 Update admin account name to be consistent for instruction validation
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/solana/anchor_program_indexer.py
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/user-social-actions.ts
Labels: size/L

#2910 Bump to v0.3.56
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2912 Paginate insert into redis
  creator-node/src/blacklistManager.js
Labels: size/S

#2913 Refresh balances when indexing Transfer instructions
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/XS

#2869 Update index user
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/solana/anchor_parser.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/solana/solana_program_indexer.py
  discovery-provider/src/utils/cid_metadata_client.py
Labels: discovery-node, size/XL

#2898 Fix ipld blacklist tests
  libs/src/api/playlist.js
  libs/src/api/user.js
  libs/src/services/creatorNode/CreatorNode.ts
  mad-dog/src/tests/test_ipldBlacklist.js
  service-commands/src/commands/playlists.js
  service-commands/src/commands/tracks.js
  service-commands/src/commands/users.js
  service-commands/src/libs.js
Labels: size/XXL

#2914 Upgrade anchor to v0.24.x
  service-commands/src/commands/service-commands.json
  solana-programs/Dockerfile
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/constants.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/programs/audius-data/Cargo.toml
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
  solana-programs/anchor/audius-data/tests/user-social-actions.ts
  solana-programs/anchor/audius-data/yarn.lock
Labels: size/XXL

#2904 [PAY-142] Improve Attester Reselection
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
Labels: size/L

#2915 Libs 1.2.107
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2916 Consume libs 1.2.107 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2903 Export types from libs
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/package.json
Labels: solana, size/M

#2918 Tweak pre-commit logic in init-repos.sh
  service-commands/scripts/init-repos.sh
Labels: size/XS

#2919 Bump solana/web3.js
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2882 Reformat audius-data cli
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/L

#2926 Bump Libs to v1.2.108
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2927 skip playlist track if unlisted
  discovery-provider/src/queries/get_feed.py
Labels: size/XS

#2928 Fix audius data cli boolean options
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/XS

#2917 Add db seed restore status check
  discovery-provider/src/queries/get_db_seed_restore_status.py
  discovery-provider/src/queries/health_check.py
Labels: size/M

#2931 Fix content node init in solana-programs
  solana-programs/start.sh
Labels: size/M

#2902 [ASI-725] Discovery node worker observability
  .pre-commit-config.yaml
  discovery-provider/requirements.txt
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/queries/get_celery_tasks_unit_test.py
  discovery-provider/src/queries/health_check.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/M, python

#2929 Consume getLatestBlockhash in relay
  identity-service/package.json
  identity-service/src/routes/trackListens.js
  identity-service/src/solana-client.js
Labels: size/XS

#2932 Reload celery tasks when python files change
  discovery-provider/requirements.txt
  discovery-provider/scripts/start.sh
Labels: discovery-node, size/XS

#2934 Finalize deprecating recentBlockhash
  libs/src/services/solanaWeb3Manager/tokenAccount.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/src/services/wormhole/index.js
  service-commands/package.json
  service-commands/scripts/rewardManagerLocal.js
Labels: size/S

#2930 set client branch default to main from master to align with dev flow
  service-commands/scripts/bake-dev-image.sh
  service-commands/scripts/utils.sh
Labels: size/XS

#2935 Fix solana programs start script typo
  solana-programs/start.sh
Labels: size/XS

#2885 Add ability to check if user exists on solana to libs
  libs/package-lock.json
  libs/package.json
  libs/src/api/account.js
  libs/src/api/base.js
  libs/src/index.js
  libs/src/services/solanaWeb3Manager/index.js
  service-commands/package.json
  service-commands/scripts/init-repos.sh
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/dist/index.d.ts
  solana-programs/anchor/audius-data/dist/index.js
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/rollup.config.js
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
  solana-programs/anchor/audius-data/yarn.lock
Labels: size/XXL

#2939 fix init repos by removing programId from exports due to lack of type…
  libs/src/api/account.js
  libs/src/index.js
  libs/src/services/solanaWeb3Manager/index.js
  service-commands/scripts/init-repos.sh
  solana-programs/anchor/audius-data/dist/index.d.ts
  solana-programs/anchor/audius-data/dist/index.js
  solana-programs/anchor/audius-data/lib/lib.ts
Labels: size/M

#2938 Add scripts for seeding audio and tipping
  service-commands/scripts/seed-audio.sh
  service-commands/src/commands/seed/SeedSession.js
  service-commands/src/commands/seed/UserCache.js
Labels: size/M

#2945 [AUD-1926] Support per-SP min delegation
  libs/src/services/ethContracts/delegateManagerClient.js
  libs/src/services/ethContracts/index.js
Labels: size/S

#2946 Libs 1.2.109
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2947 Libs 1.2.110
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2949 Mount solana-programs volume in identity-service and creator-node
  creator-node/compose/docker-compose.yml
  identity-service/compose/docker-compose.full.yml
Labels: size/XS

#2952 Fix docker build in libs
  libs/Dockerfile
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2951 [AUD-1930] Pass-through file 403 to client
  libs/src/api/file.js
  libs/src/utils/network.ts
Labels: size/S

#2950 Require audius-data dep from npm
  libs/Dockerfile
  libs/package-lock.json
  libs/package.json
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
Labels: size/XS

#2948 Update/fix track listens test
  identity-service/src/routes/trackListens.js
  identity-service/test/lib/app.js
  identity-service/test/routes/trackListensTest.js
Labels: size/L

#2942 Fetch metadata from user replica set and index endpoints
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
Labels: size/L

#2959 Remove local link step to prevent setup errors
  service-commands/scripts/init-repos.sh
Labels: size/XS

#2963 Mad-dog QoL: 5 minor improvements
  mad-dog/README.md
  mad-dog/package-lock.json
  mad-dog/package.json
  mad-dog/src/index.js
  service-commands/scripts/init-repos.sh
  service-commands/src/utils/constants.js
Labels: size/L

#2940 [ASI-725] Discovery node worker observability
  discovery-provider/src/monitors/celery.py
  discovery-provider/src/monitors/monitor_names.py
  discovery-provider/src/monitors/monitors.py
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/queries/get_celery_tasks_unit_test.py
  discovery-provider/src/queries/health_check.py
Labels: bug, discovery-node, size/L

#2943 Add alternate core libs entrypoint
  libs/package.json
  libs/rollup.config.js
  libs/src/core.ts
Labels: size/M

#2964 Add new track indexing to anchor program indexer
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/L

#2967 Update email
  identity-service/src/notifications/emails/welcome.html
Labels: size/XS

#2962 Remove IPFS gateway usage from libs
  libs/package-lock.json
  libs/src/api/base.js
  libs/src/api/file.js
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/M

#2969 Fix elapsed measurement bug in TrackListen tx submission
  identity-service/src/solana-client.js
Labels: size/XS

#2973 Fix welcome download email
  identity-service/src/notifications/emails/welcomeDownload.html
Labels: size/XS

#2972 [PLAT-111] Install Anchor deps in init-repos
  service-commands/scripts/init-repos.sh
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
Labels: size/S

#2974 Fix lint issues
  discovery-provider/integration_tests/tasks/test_index_users.py
Labels: size/S

#2844 [AUD-1821]: Refactor EthWeb3Manager to typescript
  libs/package.json
  libs/src/core.ts
  libs/src/index.js
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/ethWeb3Manager/EthWeb3Manager.ts
  libs/src/services/ethWeb3Manager/index.js
  libs/src/services/ethWeb3Manager/index.ts
  libs/src/services/hedgehog/Hedgehog.ts
  libs/src/services/hedgehog/index.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/services/identity/index.js
  libs/src/services/identity/index.ts
  libs/src/services/identity/requests.ts
  libs/src/utils/captcha.ts
  libs/src/utils/estimateGas.ts
  libs/src/utils/index.ts
  libs/src/utils/multiProvider.ts
  libs/src/utils/types.ts
  libs/tests/providerSelectionTest.js
  libs/types/@audius-hedgehog/index.d.ts
  libs/types/abi-decoder/index.d.ts
Labels: size/XXL

#2975 Bump libs to v1.2.112
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2901 Simplify logic for common object calls
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/S

#2971 Local setup fixes 04/26/22
  service-commands/scripts/provision-dev-env.sh
  service-commands/scripts/setup-instance.sh
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
Labels: size/S

#2713 [ASI-742] - Load balance transcode
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/apiSigning.js
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/components/tracks/trackContentUploadManager.js
  creator-node/src/components/tracks/tracksComponentService.js
  creator-node/src/fileManager.js
  creator-node/src/routes/tracks.js
  creator-node/src/serviceRegistry.js
  creator-node/src/utils.js
  creator-node/test/TranscodeDelegationManager.test.js
  creator-node/test/apiSigning.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/lib/asyncProcessingQueueMock.js
  creator-node/test/lib/helpers.js
  creator-node/test/lib/libsMock.js
  creator-node/test/lib/utils.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/transcodeAndSegment.test.js
  creator-node/test/utils.test.js
Labels: content-node, size/XXL

#2961 [ASI-1029] Remove Content Node IPFS leftovers
  .circleci/config.yml
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/diskManager.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/tracks.js
Labels: size/S

#2706 get_feed from ES
  discovery-provider/.gitignore
  discovery-provider/Dockerfile
  discovery-provider/compose/docker-compose.redis.yml
  discovery-provider/es-indexer/.editorconfig
  discovery-provider/es-indexer/.gitignore
  discovery-provider/es-indexer/.prettierrc
  discovery-provider/es-indexer/README.md
  discovery-provider/es-indexer/docker-compose.yml
  discovery-provider/es-indexer/nuke.ts
  discovery-provider/es-indexer/package-lock.json
  discovery-provider/es-indexer/package.json
  discovery-provider/es-indexer/src/conn.ts
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
  discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/listener.ts
  discovery-provider/es-indexer/src/logger.ts
  discovery-provider/es-indexer/src/main.ts
  discovery-provider/es-indexer/src/setup.ts
  discovery-provider/es-indexer/src/types/blocknumber_checkpoint.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/es-indexer/src/types/docs.ts
  discovery-provider/es-indexer/tsconfig.json
  discovery-provider/requirements.txt
  discovery-provider/scripts/dev-server.sh
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/health_check.py
  discovery-provider/src/utils/elasticdsl.py
Labels: size/XXL

#2984 Remove error log comparing new and legacy paths
  creator-node/src/routes/files.js
Labels: content-node, size/XS

#2887 New Migration Tool
  service-commands/README.md
  service-commands/scripts/.env/.aliases/10.audius_aliases
  service-commands/scripts/.env/.aliases/10.cloud_aliases
  service-commands/scripts/.env/.aliases/10.docker_aliases
  service-commands/scripts/.env/.aliases/10.git_aliases
  service-commands/scripts/.env/.aliases/10.k8s_aliases
  service-commands/scripts/.env/.aliases/10.troubleshooting_aliases
  service-commands/scripts/.env/.gitignore
  service-commands/scripts/.env/README.md
  service-commands/scripts/.env/bin/.env.add
  service-commands/scripts/.env/bin/.env.install
  service-commands/scripts/.env/bin/apt-install
  service-commands/scripts/.env/bin/migrate
  service-commands/scripts/.p10k.zsh
  service-commands/scripts/.zshenv
  service-commands/scripts/.zshrc
  service-commands/scripts/provision-dev-env.sh
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/utils.sh
  service-commands/src/commands/service-commands.json
Labels: size/XXL

#2990 Expose transcode load balancing details
  creator-node/src/TranscodingQueue.js
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
Labels: content-node, size/M

#2936 Index User Tips
  discovery-provider/alembic/versions/8c10373f2615_user_tips.py
  discovery-provider/src/app.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/aggregate_user_tips.py
  discovery-provider/src/models/user_tip.py
  discovery-provider/src/tasks/index_aggregate_tips.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/utils/alembic_helpers.py
Labels: discovery-node, size/L

#2995 tabs != spaces
  service-commands/scripts/.env/README.md
Labels: size/XS

#2996 Update README.md
  service-commands/scripts/.env/README.md
Labels: size/S

#2981 [PLAT-7] init_user + init_user_sol_pubkey indexing
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/solana/solana_program_indexer.py
Labels: size/L

#3001 Fix claimable relay check
  identity-service/src/utils/relayHelpers.js
Labels: size/XS

#3000 ES fixes
  discovery-provider/es-indexer/package-lock.json
  discovery-provider/es-indexer/package.json
  discovery-provider/scripts/start.sh
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/get_max_id.py
Labels: size/S

#2986 PLAT-125: Move migrations and es-indexer start points
  discovery-provider/scripts/dev-server.sh
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
Labels: size/M

#3003 Fix es-indexer repost handler for playlist.
  discovery-provider/es-indexer/src/listener.ts
Labels: size/XS

#2978 Update audius data consistency
  solana-programs/anchor/audius-data/.eslintrc.js
  solana-programs/anchor/audius-data/.gitignore
  solana-programs/anchor/audius-data/Anchor.toml
  solana-programs/anchor/audius-data/README.md
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/dist/index.d.ts
  solana-programs/anchor/audius-data/dist/index.js
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/utils.rs
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
  solana-programs/anchor/audius-data/tests/user-social-actions.ts
Labels: solana, size/XXL

#3005 Unblock bringing down services because of prune
  service-commands/src/commands/service-commands.json
Labels: size/XS
