Repository AudiusProject/apps, pull requests merged in 2022-09, with the labels that each got.

#3797 Better get_feed_es error logging. Fix fetch related saves + reposts
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/utils/elasticdsl.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#3805 INF-224 remove unneeded mount, since we don't load these modules
  logging/docker-compose.yml
Labels: size/XS

#3806 Fix typo in enum value
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/S

#3773 [PAY-587] Add transaction metadata to identity for transaction details
  identity-service/package.json
  identity-service/sequelize/migrations/20220826063452-create-user-bank-transaction-metadata.js
  identity-service/src/models/userBankTransactionMetadata.js
  identity-service/src/routes/userBankTransactionMetadata.js
Labels: identity-service, size/L

#3807 Make queues limit how many jobs they add to each other
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/types.ts
Labels: size/M

#3804 [PAY-603] Add a libs function to save transaction metadata
  libs/src/services/identity/IdentityService.ts
Labels: size/S

#3808 Update replica set and sync concurrency
  creator-node/src/config.js
Labels: size/XS

#3809 Clear write locks on init
  creator-node/src/index.ts
  creator-node/src/redis.js
  creator-node/test/redis.test.js
Labels: size/L

#3798 [PAY-549] Write out IP with each call to relay
  identity-service/src/routes/idSignals.js
  identity-service/src/routes/relay.js
  identity-service/src/utils/antiAbuse.js
Labels: size/M

#3810 Fix get tracks by removing shared cache
  discovery-provider/src/queries/get_tracks.py
Labels: size/S

#3811 INF-224 Set ${PROTOCOL_DIR} within provision-dev-env.sh
  service-commands/scripts/provision-dev-env.sh
Labels: size/XS

#3813 Fix registration on dev setup
  creator-node/nodemon.json
  dev-tools/startup/creator-node.sh
  dev-tools/startup/discovery-provider.sh
  libs/src/data-contracts/ABIs/Context.json
  libs/src/data-contracts/ABIs/TestEntityManager.json
Labels: size/L

#3795 Add social features to entity manager
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#3815 Let orphaned data recovery run 24/7
  creator-node/src/config.js
Labels: content-node, size/XS

#3781 [CON-284] Instrumentation of AsyncProcessingQueue
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/routes/tracks.js
  creator-node/src/tracer.ts
Labels: size/M

#3782 [CON-284] Instrumentation of State Machine Queues
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/processJob.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
Labels: size/L

#3758 fix inconsistency with trailing zero
  discovery-provider/integration_tests/notifications/test_reaction.py
Labels: size/XS

#3823 remove utils.js
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/playlists.js
  creator-node/src/utils/index.ts
  creator-node/src/utils/legacyUtils.js
  creator-node/src/utils/validateAudiusUserMetadata.js
Labels: size/L

#3824 Update random SPs selection
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/test/TrackTranscodeHandoffManager.test.js
  creator-node/test/lib/libsMock.js
Labels: size/M

#3820 Better logging after syncs
  creator-node/src/services/sync/secondarySyncFromPrimary.js
Labels: size/M

#3828 Increase recurring sync queue waiting size from 1000 to 10000
  creator-node/src/services/stateMachineManager/index.js
Labels: size/XS

#3827 Fix duplicate export causing TypeError
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
Labels: content-node, size/S

#3829 Optimize Entity Manager DB fetch
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#3825 Update findCIDInNetwork
  creator-node/src/fileManager.js
  creator-node/src/routes/files.js
  creator-node/src/utils/index.ts
  creator-node/src/utils/legacyUtils.js
  creator-node/test/sync.test.js
  creator-node/test/utils.test.js
Labels: size/L

#3831 Retry on cid verification
  creator-node/src/utils/legacyUtils.js
Labels: size/XS

#3833 Move bail() up one level
  creator-node/src/fileManager.js
Labels: size/L

#3765 CON-358 - Skip delisted content and do not fail sync jobs anymore
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/fileManager.js
  creator-node/src/services/sync/UserSyncFailureCountService.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/utils/asyncRetry.js
  creator-node/src/utils/decisionTree.ts
  creator-node/src/utils/legacyUtils.js
  creator-node/test/asyncRetry.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/sync.test.js
Labels: size/XXL

#3835 Bump to version 0.3.66
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3830 Gate reconfig of primary to node endpoint changing
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: content-node, size/S

#3836 Add coalesce for release date sort for favorites query
  discovery-provider/src/queries/get_save_tracks.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/get_user_listening_history.py
Labels: size/S

#3814 Add entity manager social features to libs
  libs/src/api/entityManager.ts
Labels: size/L

#3816 Simplify EM social feature deletes to not rely on existing records
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#3839 Fix prune plays test cutoff time
  discovery-provider/integration_tests/tasks/test_prune_plays.py
Labels: size/XS

#3837 [CON-353] Add tracing visualization
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/config.js
  creator-node/src/tracer.ts
Labels: size/M

#3783 [PAY-487] DN - Handle premium track access for track apis
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/integration_tests/queries/test_populate_track_metadata.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/premium_content/premium_content_constants.py
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/get_max_id.py
  discovery-provider/src/queries/get_playlist_tracks.py
  discovery-provider/src/queries/get_recommended_tracks.py
  discovery-provider/src/queries/get_remixes_of.py
  discovery-provider/src/queries/get_sol_plays.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/get_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/queries/search.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/queries/search_queries.py
  discovery-provider/src/queries/search_track_tags.py
  discovery-provider/src/queries/sol_play_helpers.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/user_library.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/models/PremiumConditions.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: discovery-node, size/XXL

#3834 Split Up `legacyUtil.js`
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/contentNodeUtils.ts
  creator-node/src/utils/fsUtils.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/legacyUtils.js
  creator-node/src/utils/runShellCommand.ts
  creator-node/src/utils/utils.ts
  creator-node/test/utils.test.js
Labels: size/XXL

#3842 [C-991] Add entity-manager to native-libs
  libs/src/NativeAudiusLibs.ts
Labels: size/S

#3845 Decrease sync monitoring retry time from 15s to 5s
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
Labels: size/XS

#3847 Convert histogram observation from ms to seconds
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
Labels: size/XS

#3843 [PAY-597] Fetch token account info with 'processed' commitment
  libs/src/services/solana/tokenAccount.ts
Labels: size/XS

#3840 Speed up audius-cmd and add more functions
  dev-tools/audius-cmd
  dev-tools/commands/package-lock.json
  dev-tools/commands/package.json
  dev-tools/commands/src/create-playlist.mjs
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/favorite-playlist.mjs
  dev-tools/commands/src/favorite-track.mjs
  dev-tools/commands/src/follow.mjs
  dev-tools/commands/src/index.mjs
  dev-tools/commands/src/mint-audio.mjs
  dev-tools/commands/src/repost-playlist.mjs
  dev-tools/commands/src/repost-track.mjs
  dev-tools/commands/src/tip-audio.mjs
  dev-tools/commands/src/unfollow.mjs
  dev-tools/commands/src/utils.mjs
  docker-compose.yml
Labels: size/L

#3848 Change borsh imports to named imports
  libs/src/services/solana/rewards.ts
  libs/src/services/solana/transfer.ts
Labels: size/S

#3849 Fix TS error
  libs/src/services/solana/tokenAccount.ts
Labels: size/XS

#3855 Modify CN state machine params for prod to improve throughput
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/index.js
Labels: size/S

#3856 Decrease primarySyncFromSecondary db query limit from 10k to 1k
  creator-node/src/services/sync/primarySyncFromSecondary.js
Labels: size/XS

#3850 Fix track ids after filtering premium tracks
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/M

#3857 Add IdentitiesOnly to config
  .circleci/config.yml
Labels: size/XS

#3861 Add better logging around outgoing syncs
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/S

#3864 UserBankTransaction purchase metadata v2
  identity-service/src/routes/userBankTransactionMetadata.js
Labels: identity-service, size/XS

#3863 Print out err stack trace in reconfig
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/XS

#3854 Add granularity to secondary sync from primary metric recording
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/syncUtil.ts
  creator-node/test/sync.test.js
Labels: content-node, size/L

#3859 Enable social features on entity manager
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/M

#3867 Fix remaining borsh serialize import
  libs/src/services/solana/userBank.ts
Labels: size/XS

#3858 Enable all reconfig modes on prod by default
  creator-node/src/config.js
Labels: size/XS

#3866 Add multi-root VSCode workspace
  audius.code-workspace
Labels: size/M

#3869 Breakup try/catch
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/XS

#3870 Test apply early limit true
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_underground_trending.py
Labels: size/XS

#3872 Remove redundant stack trace log log
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/XS

#3873 Fix generated types
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/models/PremiumContentSignature.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/M

#3876 Increase node mem in cnode
  creator-node/scripts/start.sh
Labels: size/XS

#3800 [INF-187] Add elastic search to discovery provider
  dev-tools/audius-compose
  dev-tools/startup/discovery-provider.sh
  docker-compose.yml
Labels: size/M

#3844 Update final retry call and add async retry tests
  creator-node/src/fileManager.js
  creator-node/src/utils/asyncRetry.js
  creator-node/src/utils/cidUtils.ts
  creator-node/test/asyncRetry.test.js
Labels: size/M

#3545 INF-194 Add staging deploys to CircleCi
  .circleci/bin/deploy-ci.py
  .circleci/config.yml
Labels: size/XL

#3880 First Playlist Challenge Playlist Notifications
  identity-service/src/notifications/components/notifications/Icons.jsx
  identity-service/src/notifications/components/notifications/Notification.jsx
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/renderEmail/notifications/Icons.js
  identity-service/src/notifications/renderEmail/notifications/Notification.js
  identity-service/test/emailNotifications/renderEmail.js
  identity-service/test/sendNotifications/index.js
  identity-service/test/sendNotifications/mockNotifications/challengeReward.json
Labels: size/M

#3871 Set reconfig blacklist
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/M

#3877 Add aborts for primary sync from secondary
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/L

#3884 Add ESLint rules to prevent easy errors
  creator-node/.eslintrc.js
  creator-node/.prettierrc.js
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/files.js
  creator-node/src/routes/tracks.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/tracer.ts
Labels: size/L

#3852 Add auth headers cmd for local dev
  dev-tools/commands/src/auth-headers.mjs
  dev-tools/commands/src/index.mjs
Labels: size/S

#3658 CON-321 Clean up sanity checks
  libs/src/sanityChecks/index.ts
  libs/src/sanityChecks/rolloverNodes.ts
  libs/src/sanityChecks/sanitizeNodes.ts
Labels: size/L

#3887 [CON-395] Add start time to network monitoring slack alert
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
Labels: size/S

#3888 Fix email delieverable
  identity-service/src/routes/user.js
Labels: size/XS

#3885 INF clear exporter's tallies for new proposals
  monitoring/exporters/sdk/main.js
Labels: size/XS

#3892 Run is_available job every 3 hours
  discovery-provider/src/app.py
Labels: size/XS

#3891 [CON-395] Add duration to network monitoring metrics
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
Labels: size/S

#3886 More grafana granularity and track sync failure per wallet
  creator-node/src/middlewares.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
Labels: size/L

#3898 Add FsInstrumentation to content node
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/tracer.ts
Labels: size/XS

#3889 Include 2 new challenges in notification tests
  identity-service/test/emailNotifications/renderEmail.js
  identity-service/test/emailNotifications/renderedEmails/additionalChallengeEmail.html
  identity-service/test/sendNotifications/index.js
Labels: size/XS

#3899 Also log aborts in issuing sync flow
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
Labels: size/XS

#3900 Change tsconfig root dir
  creator-node/.eslintrc.js
Labels: size/XS

#3874 Add timings to sync steps
  creator-node/src/logging.js
  creator-node/src/middlewares.js
  creator-node/src/services/ContentNodeInfoManager.ts
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/utils.ts
  creator-node/test/sync.test.js
Labels: content-node, size/L

#3896 Add feeling lucky route
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_random_tracks.py
Labels: size/M

#3895 Add feeling lucky API to libs
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/M

#3894 Make block explorer optional
  contracts/package-lock.json
  contracts/package.json
  dev-tools/audius-compose
  docker-compose.yml
  eth-contracts/package-lock.json
  eth-contracts/package.json
Labels: size/S

#3893 INF-251 Automate Production Deployments
  .circleci/bin/deploy-ci.py
  .circleci/config.yml
Labels: size/L

#3879 [PAY-568] Add route to identity to create a Stripe session
  identity-service/default-config.json
  identity-service/src/config.js
  identity-service/src/routes/stripe.js
Labels: size/M

#3902 INF deploy-master-hold
  .circleci/config.yml
Labels: size/XS

#3878 [PAY-645] Add a route to start a stripe session in SDK
  libs/src/services/identity/IdentityService.ts
Labels: libs, size/S

#3883 Increase CN nginx worker procs
  creator-node/nginx_conf/nginx.conf
Labels: size/S

#3851 Creator node Track owner validation from discovery
  creator-node/src/routes/tracks.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/sync.test.js
Labels: size/L

#3907 remove start time from slack alert
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
Labels: size/XS

#3909 bump network monitoring connection pool max
  discovery-provider/plugins/network-monitoring/src/db/index.ts
Labels: size/XS

#3910 INF-251 Allow for surgical deployments via a trigger pipeline
  .circleci/config.yml
Labels: size/M

#3911 INF-251 use set-tag for prod
  .circleci/bin/deploy-ci.py
Labels: size/M

#3912 Fix artist name sorter
  discovery-provider/src/queries/get_save_tracks.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/get_user_listening_history.py
Labels: size/XS

#3913 Bump to version 0.3.67
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3917 [CON-408] Randomize order of orphaned data recovery
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
Labels: content-node, size/S

#3919 INF-251 throttle prod releases
  .circleci/bin/deploy-ci.py
Labels: size/M

#3920 INF-251 don't block releases for test-eth-contracts
  .circleci/config.yml
Labels: size/XS

#3922 Update stage contract addresses to goerli
  monitoring/prometheus/.env.stage
Labels: size/XS

#3925 Add check for GCP DBs in check-secrets.sh
  check_secrets.sh
Labels: size/XS

#3908 CON-402 CN Remove all synchronous disk ops
  creator-node/package-lock.json
  creator-node/src/components/replicaSet/syncQueueComponentService.js
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/config.js
  creator-node/src/diskManager.js
  creator-node/src/diskManager.test.js
  creator-node/src/ffmpeg.js
  creator-node/src/fileManager.js
  creator-node/src/models/index.js
  creator-node/src/resizeImage.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/files.js
  creator-node/src/routes/index.js
  creator-node/src/routes/playlists.js
  creator-node/src/routes/tracks.js
  creator-node/src/segmentDuration.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/test/audiusUsers.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/ensureStorageMiddleware.test.js
  creator-node/test/ffmpeg.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/lib/helpers.js
  creator-node/test/playlists.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
  creator-node/test/sync.test.js
Labels: size/XL

#3915 Add upload track to audius-cmd
  dev-tools/audius-cmd
  dev-tools/commands/Dockerfile
  dev-tools/commands/src/index.mjs
  dev-tools/commands/src/upload-track.mjs
Labels: size/L

#3921 Remove handle relay blocking logic
  identity-service/src/config.js
  identity-service/src/utils/antiAbuse.js
Labels: size/M

#3926 INF-251 remove hold job for auto-deploying to staging
  .circleci/config.yml
Labels: size/S

#3924 INF-251 always deploy to canaries first
  .circleci/bin/deploy-ci.py
Labels: size/S

#3927 INF-251 reorg production deployment flow w/release-day lessons
  .circleci/config.yml
Labels: size/M

#3930 Block notifs on error 7
  identity-service/src/utils/antiAbuse.js
Labels: size/XS

#3932 INF-251 add host to post-health check logs
  .circleci/bin/deploy-ci.py
Labels: size/XS

#3934 INF-251 Streamlined reorg for Deployment Pipeline
  .circleci/config.yml
Labels: size/L

#3933 Patch staging CN
  creator-node/src/config.js
  creator-node/src/services/URSMRegistrationManager.js
  creator-node/src/services/initAudiusLibs.js
Labels: size/M

#3935 INF-251 don't send Starting nor Success slack messages for auto-deploys
  .circleci/config.yml
Labels: size/S

#3931 Add Hyperpop to trending
  discovery-provider/src/tasks/index_trending.py
Labels: size/XS

#3881 Run Content Node on multiple cluster processes and migrate Bull->BullMQ
  creator-node/.eslintrc.js
  creator-node/compose/env/base.env
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/patches/README.md
  creator-node/patches/bullmq+1.91.1.patch
  creator-node/scripts/start.sh
  creator-node/src/AsyncProcessingQueue.js
  creator-node/src/ImageProcessingQueue.js
  creator-node/src/TranscodingQueue.js
  creator-node/src/blacklistManager.js
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/SessionExpirationQueue.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/SyncRequestDeDuplicator.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/services/stateMachineManager/types.ts
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/utils/clusterUtils.ts
  creator-node/src/utils/index.ts
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/blacklistManager.test.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/genericBullQueueMock.js
  creator-node/test/prometheus.test.js
Labels: content-node, size/XXL

#3937 Await CN services before starting server
  creator-node/src/index.ts
  creator-node/src/serviceRegistry.js
Labels: content-node, size/M

#3841 [PAY-480][PAY-482][PAY-488][PAY-503][PAY-520][PAY-588] Activate premium content middleware
  creator-node/src/apiSigning.js
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.test.ts
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.ts
  creator-node/src/premiumContent/helpers.test.ts
  creator-node/src/premiumContent/helpers.ts
  creator-node/src/premiumContent/premiumContentAccessChecker.ts
  creator-node/src/premiumContent/stubPremiumContentAccessChecker.ts
  creator-node/src/premiumContent/types.ts
  creator-node/src/routes/files.js
  creator-node/src/serviceRegistry.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/libsMock.js
  creator-node/test/premiumContentAccessChecker.test.ts
  creator-node/test/prometheus.test.js
  libs/src/api/Track.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  service-commands/src/utils/random.js
Labels: size/XXL

#3938 Update readme for audius-compose
  README.md
Labels: size/S

#3942 Only show diff in libs folder between versions
  libs/scripts/release.sh
Labels: size/XS

#3940 INF-255 Reservation CLI Tool
  .circleci/bin/deploy-ci.py
  .circleci/config.yml
Labels: size/L

#3941 INF-260 restrict cn deploys to release*-patch-* branches
  .circleci/config.yml
Labels: size/S

#3526 [PLAT-255] Remove IPFS
  .circleci/config.yml
  discovery-provider/compose/.env
  discovery-provider/compose/.test.env
  discovery-provider/compose/docker-compose.backend.yml
  discovery-provider/compose/docker-compose.ipfs.yml
  discovery-provider/compose/docker-compose.web-server.yml
  discovery-provider/compose/env/shellEnv1.sh
  discovery-provider/compose/env/shellEnv2.sh
  discovery-provider/compose/env/shellEnv3.sh
  discovery-provider/compose/env/shellEnv4.sh
  discovery-provider/compose/env/shellEnv5.sh
  discovery-provider/compose/env/shellEnv6.sh
  discovery-provider/compose/env/shellEnv7.sh
  discovery-provider/compose/env/shellEnv8.sh
  discovery-provider/compose/env/shellEnv9.sh
  discovery-provider/compose/env/unsetShellEnv.sh
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/requirements.txt
  discovery-provider/scripts/test.sh
  discovery-provider/scripts/up.sh
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/queries/index_block_stats.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/cid_metadata_client.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/index_blocks_performance.py
Labels: size/L

#3897 user and replica set entity manager
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/middlewares.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/services/initAudiusLibs.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/lib/libsMock.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
  discovery-provider/integration_tests/challenges/index_helpers.py
  discovery-provider/integration_tests/tasks/entity_manager/test_ursm_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/queries/get_user_replica_set.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/user_replica_set_unit_test.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/eth_manager.py
  discovery-provider/src/utils/redis_cache.py
  libs/src/api/Account.ts
  libs/src/api/Users.ts
  libs/src/data-contracts/signatureSchemas.js
  libs/src/sdk/api/generated/default/.openapi-generator/FILES
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/default/models/UserReplicaSet.ts
  libs/src/sdk/api/generated/default/models/UsersByContentNode.ts
  libs/src/sdk/api/generated/default/models/index.ts
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/UserReplicaSet.ts
  libs/src/sdk/api/generated/full/models/UsersByContentNode.ts
  libs/src/sdk/api/generated/full/models/index.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/utils/types.ts
Labels: size/XXL

#3949 Fix path in libs release script
  libs/scripts/release.sh
Labels: size/XS

#3950 INF Attempt to get @mentions working for @joe
  .circleci/config.yml
Labels: size/XS

#3951 INF remove deadlink to gov.audius.org
  docs/docs/token/running-a-node/hardware-requirements.md
Labels: size/XS

#3953 Update @audius/sdk version in content node
  creator-node/package-lock.json
  creator-node/package.json
Labels: size/XS

#3944 Add trending/underground non-full endpoint
  discovery-provider/src/api/v1/tracks.py
  libs/src/sdk/api/generated/default/apis/TracksApi.ts
Labels: size/L

#3962 [PAY-660] Add a getter for userBankTransactionMetadata in libs
  libs/src/services/identity/IdentityService.ts
Labels: libs, size/S

#3939 Aggregate metrics across cluster
  creator-node/src/app.js
  creator-node/src/index.ts
  creator-node/src/routes/prometheusMetricsRoutes.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
  creator-node/test/prometheus.test.js
Labels: size/L

#3968 Set up tracing before anything else
  creator-node/src/index.ts
Labels: size/XS

#3966 set mem limit for celery workers
  discovery-provider/scripts/start.sh
Labels: size/XS

#3972 Add aggregator config to each metric
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
Labels: size/M

#3957 INF-259 Alert more often in #eng-deploys-announcements
  .circleci/bin/deploy-ci.py
Labels: size/XS

#3965 Gating entity manager replica set updates with identity service
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  identity-service/src/config.js
  identity-service/src/routes/relay.js
  libs/src/api/Users.ts
Labels: size/L

#3978 Add local CN owners to dev tools config
  dev-tools/config.json
Labels: size/XS

#3955 INF Increase production buffer time between nodes to 30 minutes
  .circleci/bin/deploy-ci.py
Labels: size/XS

#3969 Register CN before healthy
  creator-node/scripts/register.js
  dev-tools/audius-cmd
Labels: size/S

#3945 [INF-183] Add AAO to local compose stack
  dev-tools/audius-compose
  dev-tools/config.json
  docker-compose.yml
  eth-contracts/contract-config.js
Labels: size/M

#3981 Revert "[INF-183] Add AAO to local compose stack"
  dev-tools/audius-compose
  dev-tools/config.json
  docker-compose.yml
  eth-contracts/contract-config.js
Labels: size/M

#3980 Upgrade identity libs to 1.0.8
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3979 Upgrade CN libs to 1.0.8
  creator-node/package-lock.json
  creator-node/package.json
Labels: size/XS

#3964 Support unlisted track filtering in user tracks api
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_tracks.py
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/M

#3982 Fix EM flag for replica sets
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/S

#3918 [CON-392] Trace Network Monitoring
  discovery-provider/plugins/network-monitoring/package-lock.json
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/src/config.ts
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_foreign_connection.ts
  discovery-provider/plugins/network-monitoring/src/discovery/index.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
  discovery-provider/plugins/network-monitoring/src/tracer.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
Labels: size/XXL

#3974 Disable premium content
  creator-node/compose/env/base.env
  creator-node/scripts/run-tests.sh
  creator-node/src/config.js
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.test.ts
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.ts
Labels: size/L

#3967 Add Identity Typescript Support
  identity-service/.gitignore
  identity-service/Dockerfile
  identity-service/nodemon.json
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/scripts/dev-server.sh
  identity-service/scripts/start.sh
  identity-service/src/index.ts
  identity-service/tsconfig.base.json
  identity-service/tsconfig.build.json
  identity-service/tsconfig.json
Labels: size/L

#3983 get_feed_es supports explicit IDs
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/queries/get_feed_es.py
Labels: size/M

#3943 search: boost exact track title match
  discovery-provider/scripts/search_quality.py
  discovery-provider/src/queries/search_es.py
Labels: size/L

#3928 [PAY-649] Add premium follow gate logic
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/premium_content/premium_content_types.py
  discovery-provider/src/schemas/track_schema.json
  libs/src/api/File.ts
  libs/src/sdk/api/generated/full/models/PremiumConditions.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/L
