Repository AudiusProject/apps, pull requests merged in 2022-10, with the labels that each got.

#3985 Add cluster worker number in logger
  creator-node/src/logging.js
Labels: size/XS

#3963 INF-242 Fix Gauge metrics for health-check metrics. Add basic Summary support.
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/M

#3958 INF-272 Replace noop jobs with new release-scripts jobs
  .circleci/config.yml
Labels: size/M

#3987 Change Content Node `index.ts` `require`s to `import`s
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/index.ts
Labels: size/M

#3989 INF-272 run ssh-keyscan before cloning
  .circleci/config.yml
Labels: size/XS

#3991 INF-272 Convert cut-release job to trigger job
  .circleci/config.yml
Labels: size/M

#3992 INF-272 ssh-keyscan for release-scripts, not deploy
  .circleci/config.yml
Labels: size/XS

#3993 INF-272 cd audius-tooling
  .circleci/config.yml
Labels: size/XS

#3996 INF-272 cp ssh_keys
  .circleci/config.yml
Labels: size/XS

#3995 Update CN old delegate wallet patch
  creator-node/src/services/URSMRegistrationManager.js
Labels: size/XS

#3990 [CON-437] Add env var to disable cluster mode
  creator-node/package-lock.json
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/routes/prometheusMetricsRoutes.js
  creator-node/src/utils/clusterUtils.ts
Labels: size/L

#3973 Add Discovery Sitemap Endpoint
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/requirements.txt
  discovery-provider/src/queries/get_sitemap.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/L

#3961 INF-277 Create --dry-run jobs for foundation content nodes
  .circleci/config.yml
Labels: size/S

#3998 INF-251 add Slack details on failed deploy
  .circleci/config.yml
Labels: size/XS

#3997 INF-273 automate release checklist text
  .circleci/config.yml
Labels: size/S

#4000 INF-251 Always store $SLACK_DETAIL
  .circleci/config.yml
Labels: size/XS

#3971 [CON-205]Add gauges for all monitors in content node
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/monitors/monitors.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
Labels: size/L

#4006 Remove default image in audius cloud create
  dev-tools/audius-cloud
Labels: size/XS

#3984 [INF-267][INF-269] Add sshuttle
  dev-tools/README.md
  dev-tools/audius-compose
  dev-tools/startup/build-audius-libs.sh
  dev-tools/startup/port-forwarder.sh
  dev-tools/startup/socks5-proxy-pac.py
  docker-compose.yml
  libs/rollup.config.js
Labels: size/L

#3948 [INF-244] Add additional script for dev setup
  contracts/.nvmrc
  contracts/.python-version
  creator-node/.nvmrc
  creator-node/.python-version
  dev-tools/setup-dev.sh
  dev-tools/setup.sh
  eth-contracts/.nvmrc
  eth-contracts/.python-version
  identity-service/.nvmrc
  identity-service/.python-version
  libs/.nvmrc
  libs/.python-version
  solana-programs/.nvmrc
Labels: size/S

#4008 Add prune to audius-compose
  dev-tools/audius-cloud
  dev-tools/audius-compose
  dev-tools/setup.sh
Labels: size/M

#4001 Convert `app.js` -> `app.ts`
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/app.ts
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/index.ts
  creator-node/src/services/prometheusMonitoring/prometheusUtils.ts
  creator-node/test/expressApp.test.js
  creator-node/test/lib/app.js
Labels: size/L

#3905 Rename service types in service migrations
  eth-contracts/migrations/7_versioning_service_migration.js
  eth-contracts/test/delegateManager.test.js
  eth-contracts/test/delegateManagerV2.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/random/random.test.js
  eth-contracts/test/serviceProvider.test.js
Labels: size/S

#4010 INF Skip deploying to cn11 temporarily + short slack notifications
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4012 Fix ES tag search, add tests.
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/src/queries/search_es.py
Labels: size/L

#4005 CN - Fix URSM / Entity Manager short circuit logic
  creator-node/package-lock.json
  creator-node/src/config.js
  creator-node/src/services/URSMRegistrationManager.js
  creator-node/src/services/initAudiusLibs.js
  mad-dog/src/tests/test_integration.js
Labels: size/M

#4019 Increase file watchers for nodemon
  dev-tools/setup.sh
Labels: size/XS

#4016 Remove build from README
  dev-tools/README.md
Labels: size/XS

#4021 Change local creator nodes default to 4
  dev-tools/audius-compose
Labels: size/XS

#4025 INF-276 Send reservation information to Slack
  .circleci/config.yml
Labels: size/S

#4026 INF-274 Add Discord notifications
  .circleci/config.yml
Labels: size/S

#4029 Disable EM replica sets in local so mad dog passes
  creator-node/compose/env/base.env
Labels: size/XS

#3923 INF production Grafana snapshot
  monitoring/grafana/dashboards/audius-content-node-bull-queue.json
  monitoring/grafana/dashboards/audius-content-node-overview.json
  monitoring/grafana/dashboards/audius-content-node-profiling.json
  monitoring/grafana/dashboards/audius-content-node-syncs.json
  monitoring/grafana/dashboards/audius-content-node-update-replica-set.json
  monitoring/grafana/dashboards/audius-entity-manager.json
  monitoring/grafana/dashboards/audius-network-monitoring.json
  monitoring/grafana/dashboards/ray-test.json
  monitoring/grafana/metadata/contact-points.json
  monitoring/grafana/metadata/templates.json
Labels: size/XXL

#4031 [CON-429] Network Monitoring: user status by replica
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
Labels: size/L

#4030 [PAY-672] Fix saveUserBankTransactionMetadata in SDK
  libs/src/services/identity/IdentityService.ts
Labels: size/XS

#4034 INF-288 add commit details to `reservations`
  .circleci/bin/deploy-ci.py
Labels: size/XS

#3812 Fix expired Discord link
  README.md
Labels: size/XS

#4041 export ErrorBadRequest
  creator-node/src/apiHelpers.ts
Labels: size/XS

#4027 Add artist pick track id to user metadata in entity manager
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/tasks/users.py
Labels: size/L

#4045 INF-251 use correct prod-user-metadata hostname
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4046 [CON-382] Track metrics for sync queues
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
Labels: size/XS

#4043 Use env vars for ODR and make other env vars consistent
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
Labels: size/M

#3954 Delete files from disk when deleting from db
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/dbManager.js
  creator-node/src/diskManager.js
  creator-node/src/middlewares.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/fileManager.test.js
  discovery-provider/alembic/versions/a8752810936c_add_artist_pick_track_id_to_users_table.py
Labels: size/L

#4035 Discovery indexing user verification
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#4052 Fix local upload track for premium content
  dev-tools/commands/src/upload-track.mjs
Labels: size/XS

#4044 INF-251 reduce Slack messages' vertical height
  .circleci/config.yml
Labels: size/M

#4057 [INF-292] Auto delete CI spot instances
  service-commands/scripts/auto-delete-gcloud-instance.sh
  service-commands/scripts/create-instance.sh
Labels: size/S

#4050 User verification via entity manager in identity
  dev-tools/audius-compose
  discovery-provider/default_config.ini
  docker-compose.yml
  identity-service/compose/.env
  identity-service/src/audiusLibsInstance.js
  identity-service/src/config.js
  identity-service/src/routes/instagram.js
  identity-service/src/routes/twitter.js
  libs/src/api/Users.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/L

#4053 [PLAT-395] Get pytest working on audius-compose
  discovery-provider/.test.env
  discovery-provider/README.md
  discovery-provider/integration_tests/conftest.py
  discovery-provider/scripts/test.sh
  discovery-provider/scripts/test_setup.sh
  docker-compose.yml
Labels: size/L

#4064 INF-256 consume governance secrets
  .circleci/config.yml
Labels: size/XS

#4066 INF-274 Nicer discord messages
  .circleci/config.yml
Labels: size/S

#4068 Update sshuttle readme DN hostname
  dev-tools/README.md
Labels: size/XS

#4003 [C-1116] Implement proxy wormhole only entrypoint
  libs/src/NativeAudiusLibs.ts
  libs/src/services/wormhole/ProxyWormhole.ts
  libs/src/services/wormhole/Wormhole.ts
  libs/src/services/wormhole/index.ts
Labels: size/L

#4063 Increase timeout for wormhole relay route
  identity-service/src/routes/wormhole.js
Labels: size/XS

#4038 Convert MigrationManager to typescript
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/migrationManager.ts
Labels: size/S

#4065 [CON-389] Content node log cleanup & reduction [pt 1]
  creator-node/src/fileManager.js
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/routes/files.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/utils.ts
Labels: size/M

#4062 CON-451 Expose new getTracksVerbose from Libs to expose block number metadata
  libs/package-lock.json
  libs/src/api/Track.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/L

#4071 INF Wait 15 seconds to SSH into a node
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4073 Bump sdk in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#4077 CON-451 Reduce CN tracks upload errors by consuming new libs getTracksVerbose & improving logic
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/components/contentBlacklist/contentBlacklistController.js
  creator-node/src/routes/tracks.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/sync.test.js
Labels: size/L

#4072 INF Use only lowercase for slack @mentions
  .circleci/config.yml
Labels: size/XS

#4040 Convert SessionManager to Typescript
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/dbManager.js
  creator-node/src/sessionManager.js
  creator-node/src/sessionManager.ts
Labels: size/L

#4080 CON-451 CN track upload validation improvements
  creator-node/compose/env/base.env
  creator-node/src/routes/tracks.js
  creator-node/src/utils/asyncRetry.js
Labels: size/S

#4081 [CON-440] Use min concurrency instead of max for Bull
  creator-node/src/utils/clusterUtils.ts
Labels: size/S

#3695 Subgraph Docs
  docs/docs/developers/subgraph/entities.md
  docs/docs/developers/subgraph/queries.md
  docs/docs/developers/subgraph/subgraphdata.md
Labels: size/XL

#4085 INF Remove stg-cn4 from deploy script
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4086 Fix args passed to detectAbuse
  identity-service/src/routes/relay.js
Labels: size/XS

#4056 Add formatter to eslint output
  creator-node/package.json
Labels: size/XS

#4088 Add new abuse rules and fix bugs
  identity-service/src/routes/relay.js
  identity-service/src/routes/user.js
  identity-service/src/utils/antiAbuse.js
Labels: size/M

#4074 [CON-313] Network Monitoring: Differentiate between missed users and users with -1 clock values
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
Labels: size/M

#4092 Hotfix track upload - Fix CN asyncretry options bug
  creator-node/src/routes/tracks.js
Labels: size/S

#4093 Add skip unlisted filter
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/queries.py
Labels: size/XS

#4089 Convert `secondarySyncFromPrimary` to typescript
  creator-node/src/middlewares.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/src/services/sync/syncUtil.ts
  creator-node/test/sync.test.js
Labels: size/L

#4037 Convert `SyncComponentService` to typescript
  creator-node/src/components/replicaSet/syncQueueComponentService.js
  creator-node/src/components/replicaSet/syncQueueComponentService.ts
Labels: size/M

#4032 ES: whitespace tolerance, faster feed
  discovery-provider/es-indexer/README.md
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
  discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/indexers/sharedIndexSettings.ts
  discovery-provider/scripts/search_quality.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/utils/elasticdsl.py
Labels: size/L, elasticsearch

#4082 Deploy EM to nethermind + tx script
  contracts/contract-config.js
  contracts/migrations/6_nethermind_entity_manager_migration.js
  contracts/scripts/nethermind_entity_manager_tx.js
  contracts/truffle-config.js
Labels: size/M

#4094 [INF-292] Cleanup GCP VMs created in CI pt. 2
  service-commands/scripts/create-instance.sh
Labels: size/S

#4054 Modify user API endpoints to accommodate artist pick tracks
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/get_tracks.py
  libs/src/sdk/api/generated/default/models/User.ts
  libs/src/sdk/api/generated/full/models/UserFull.ts
Labels: size/L

#4102 Fix followers API for users without replica set
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#3826 [CON-332] Refactor CN middlewares to use SP IDs as source of truth
  creator-node/src/apiSigning.js
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/fileManager.js
  creator-node/src/logging.js
  creator-node/src/middlewares.js
  creator-node/src/routes/files.js
  creator-node/src/services/ContentNodeInfoManager.ts
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/services/types.ts
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/contentNodeUtils.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/strToReplicaSet.ts
  creator-node/src/utils/utils.ts
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/secondarySyncFromPrimaryUtils.test.js
  creator-node/test/sync.test.js
Labels: content-node, size/XXL

#4059 Content Node: Add eslint promise linters
  creator-node/.eslintrc.js
  creator-node/package-lock.json
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
Labels: size/XS

#4078 [PAY-662] Create audio_transactions_history table
  discovery-provider/alembic/versions/42d5afb85d42_create_audio_transactions_history.py
  discovery-provider/src/models/users/audio_transactions_history.py
Labels: size/L

#4079 [PAY-666] Indexing user bank for audio_tx_history
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#4106 Change CN db connection pool to be a function of numWorkers
  creator-node/package-lock.json
  creator-node/src/models/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/utils/clusterUtils.ts
Labels: size/S

#4047 Add artist pick field to user metadata types in libs
  discovery-provider/src/schemas/user_schema.json
  libs/src/api/Users.ts
  libs/src/services/schemaValidator/schemas/userSchema.json
  libs/src/utils/types.ts
Labels: size/S

#4099 ES feed: dedupe track uploads that also appear in a playlist
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/queries/get_feed_es.py
Labels: size/M

#4101 Make another gigantic log a debug
  creator-node/src/services/stateMachineManager/processJob.ts
  creator-node/test/processJob.test.js
Labels: size/XS

#4104 Fix health check relay when tx is pending
  identity-service/src/routes/healthCheck.js
Labels: size/XS

#4115 Revert "Change CN db connection pool to be a function of numWorkers (#4106)"
  creator-node/package-lock.json
  creator-node/src/models/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/utils/clusterUtils.ts
Labels: size/S

#4111 Pause sending local dev logs to elk by default
  service-commands/src/setup.js
Labels: size/XS

#4117 Re-enable "Change CN db connection pool to be a function of numWorkers"
  creator-node/package-lock.json
  creator-node/scripts/run-tests.sh
  creator-node/src/ImageProcessingQueue.ts
  creator-node/src/models/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/utils/clusterUtils.ts
Labels: size/M

#4120 Fix mad dog breaking from (#4117)
  creator-node/compose/docker-compose.yml
Labels: size/XS

#4121 [CON-468] Fix _issueAndWaitForSecondarySyncRequests bug with creatorNodeEndpoints
  creator-node/src/middlewares.js
Labels: size/XS

#4113 Update push notifications payload to include the notification object for client side routing
  identity-service/src/awsSNS.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: size/M

#4122 Fix SP ID related bugs
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
Labels: content-node, size/S

#4112 CON-470 Content Node: Add query timeout
  creator-node/src/config.js
  creator-node/src/models/index.js
  creator-node/test/sequelize.test.js
Labels: size/M

#4126 Update max reversion blocks
  discovery-provider/src/tasks/index.py
Labels: size/XS

#4118 INF-262 CircleCI: Remove emojis, add new cron triggers, restrict deployment jobs, don't autodeploy needlessly, add slashing trigger
  .circleci/config.yml
Labels: size/L

#4067 Add endpoint and query to fetch users track listen count data by month
  discovery-provider/integration_tests/queries/test_get_user_listen_counts_monthly.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/api/v1/users_unit_test.py
  discovery-provider/src/queries/get_user_listen_counts_monthly.py
  discovery-provider/src/utils/redis_cache.py
  libs/src/sdk/api/generated/default/.openapi-generator/FILES
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/default/models/ListenCount.ts
  libs/src/sdk/api/generated/default/models/MonthlyAggregatePlay.ts
  libs/src/sdk/api/generated/default/models/UserTrackListenCountsResponse.ts
  libs/src/sdk/api/generated/default/models/UserTrackListenCountsResponseData.ts
  libs/src/sdk/api/generated/default/models/WildMonthModel.ts
  libs/src/sdk/api/generated/default/models/index.ts
Labels: size/XL

#4129 CN config tweaks - nodeSyncFileSaveMaxConcurrency & contentCacheLayerEnabled
  creator-node/src/config.js
Labels: size/XS

#4128 inf-294 only wait 1 minute when releasing to one node at a time
  .circleci/bin/deploy-ci.py
Labels: size/XS

#4130 Fix libs type and allow setting null artist pick in backend
  discovery-provider/src/tasks/users.py
  libs/src/utils/types.ts
Labels: size/XS

#4133 INF-295 Activate cut-release job
  .circleci/config.yml
Labels: size/XS

#4132 Update comment
  discovery-provider/src/tasks/index.py
Labels: size/XS

#4137 Silence cron triggers until we fix bi-weekly
  .circleci/config.yml
Labels: size/L

#4140 remove test failing mypy hook
  discovery-provider/integration_tests/queries/test_get_user_listen_counts_monthly.py
Labels: size/L

#4135 Convert `creator-node/src/services/SessionExpirationQueue.js` to Typescript
  creator-node/src/serviceRegistry.js
  creator-node/src/services/SessionExpirationQueue.ts
Labels: size/S, hacktoberfest-accepted

#4142 fix failing flake8 hook
  discovery-provider/integration_tests/queries/test_get_user_listen_counts_monthly.py
Labels: size/XS

#4087 Convert segmentDuration to typescript
  creator-node/src/segmentDuration.ts
Labels: size/XS

#4127 Fix base sitemapp
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/src/queries/get_sitemap.py
Labels: size/M

#4145 CN performance stabilization tweaks
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/utils/clusterUtils.ts
Labels: size/S

#4083 Convert syncQueue to typescript
  creator-node/src/serviceRegistry.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/syncQueue.ts
  creator-node/test/lib/app.js
Labels: size/M

#4105 [CON-455] - Fix content blacklist tests and mocks
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/dataSeeds.js
  creator-node/test/lib/libsMock.js
Labels: size/L

#4060 Content Node: Turn on no useless catch
  creator-node/.eslintrc.js
  creator-node/src/diskManager.js
  creator-node/src/routes/tracks.js
Labels: size/XS

#4116 Add flow for testing discovery provider
  dev-tools/audius-compose
  discovery-provider/README.md
  discovery-provider/scripts/init-db.sh
  discovery-provider/scripts/start.sh
  discovery-provider/scripts/test_entrypoint.sh
  discovery-provider/scripts/test_setup.sh
  docker-compose.test.yml
  docker-compose.yml
Labels: size/L

#4147 Add getUserListenCountsMonthly to libs for artist dashbaord
  libs/src/api/Users.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#4070 [CON-239] Poll for sync status
  creator-node/package-lock.json
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.ts
  creator-node/src/services/sync/syncUtil.ts
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  dev-tools/audius-compose
Labels: size/L

#4098 Convert `AsyncProcessingQueue` to typescript
  creator-node/src/AsyncProcessingQueue.ts
  creator-node/src/serviceRegistry.js
  creator-node/test/AsyncProcessingQueue.test.js
  creator-node/test/lib/asyncProcessingQueueMock.js
Labels: size/L

#4156 Check that errored array has length when checking for forbidden
  libs/src/api/File.ts
Labels: size/S

#4131 [CON-450] Refactor CNodeHealthManager w secondary grace period
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/CNodeHealthManager.js
  creator-node/src/services/stateMachineManager/CNodeHealthManager.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/CNodeHealthManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/XL

#4157 Remove unpopulated cache for tracks, users, playlists
  discovery-provider/src/queries/get_unpopulated_playlists.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/get_unpopulated_users.py
Labels: size/L

#4151 INF-295 Fix release-week logic checking
  .circleci/config.yml
Labels: size/L

#4158 Only delete disk on secondaries
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/test/sync.test.js
Labels: size/M

#4143 INF-290 Nicer discord messages
  .circleci/config.yml
Labels: size/XS

#4160 Update reconfigSPIdBlacklistString to include any node > 75% storage utilization
  creator-node/src/config.js
Labels: size/XS

#4163 Clean up unused libs param
  creator-node/src/fileManager.js
  creator-node/test/fileManager.test.js
Labels: content-node, size/XS

#4161 CN Reconfig mode primary only override
  creator-node/package-lock.json
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/L

#4165 Revert "INF-266 reroute nginx paths to new prometheus exporters (new exporter images included)"
  creator-node/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/nginx.conf
  monitoring/exporters/postgres/Dockerfile
  monitoring/exporters/postgres/docker-entrypoint.sh
  monitoring/exporters/redis/Dockerfile
  monitoring/exporters/redis/docker-entrypoint.sh
Labels: size/L

#4164 Fix TypeError & undefined bugs
  creator-node/src/services/stateMachineManager/CNodeHealthManager.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
  creator-node/test/monitorState.jobProcessor.test.js
Labels: size/M

#4167 Update primary reconfig configs
  creator-node/compose/env/base.env
  creator-node/src/config.js
Labels: size/XS

#4168 Remove performSimpleCheck flag
  creator-node/src/services/stateMachineManager/CNodeHealthManager.ts
  creator-node/test/CNodeHealthManager.test.js
Labels: size/S

#4166 Substitute main for master
  .circleci/bin/deploy-ci.py
  .circleci/config.yml
  .circleci/triggers/__init__.py
  .circleci/triggers/deploy-sdk.py
  README.md
  contracts/package.json
  dev-tools/README.md
  dev-tools/audius-cloud
  diff.sh
  discovery-provider/README.md
  discovery-provider/alembic/versions/88daa6a4f269_index_repair.py
  discovery-provider/src/utils/prometheus_metric.py
  docs/docs/protocol/content-node/architecture.md
  docs/docs/protocol/content-node/overview.md
  docs/docs/protocol/discovery-node/architecture.md
  docs/docs/protocol/discovery-node/overview.md
  docs/docs/protocol/overview.md
  docs/docs/token/running-a-node/advanced_setup.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/content-node.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/content-node/architecture.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/content-node/overview.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/discovery-node/architecture.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/discovery-node/overview.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/protocol/overview.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/token/running-a-node/advanced_setup.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/token/running-a-node/setup-instructions.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/protocol/overview.md
  docs/i18n/es/docusaurus-plugin-content-docs/current/token/running-a-node/setup-instructions.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/protocol/overview.md
  docs/i18n/fr/docusaurus-plugin-content-docs/current/token/running-a-node/setup-instructions.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/protocol/overview.md
  docs/i18n/ko/docusaurus-plugin-content-docs/current/token/running-a-node/setup-instructions.md
  docs/i18n/zh/docusaurus-plugin-content-docs/current/protocol/overview.md
  docs/i18n/zh/docusaurus-plugin-content-docs/current/token/running-a-node/setup-instructions.md
  eth-contracts/README.md
  libs/package.json
  libs/scripts/release.sh
  libs/src/services/solana/padBNToUint8Array.ts
  monitoring/README.md
  service-commands/scripts/A
  service-commands/scripts/bake-dev-image.sh
  service-commands/scripts/utils.sh
Labels: size/L

#4169 Disable reconfigModePrimaryOnly
  creator-node/compose/env/base.env
  creator-node/src/config.js
Labels: size/XS

#4173 Fix premium conditions type in libs trackSchema.json
  libs/src/services/schemaValidator/schemas/trackSchema.json
Labels: size/XS

#4172 Switch to debug logs for renderAndSendNotificatoinEmail
  identity-service/src/notifications/index.js
  identity-service/src/notifications/sendDownloadAppEmails.js
  identity-service/src/notifications/sendNotificationEmails.js
Labels: size/S

#4174 [CON-389] Remove useless logs and move semi-useful logs to be `debug`
  creator-node/src/apiHelpers.ts
  creator-node/src/app.ts
  creator-node/src/logging.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/sync/syncUtil.ts
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/fsUtils.ts
  creator-node/src/utils/validateAudiusUserMetadata.ts
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: size/M

#4176 Remove CN 2,3,27 from reconfigSpIDBlacklist
  creator-node/src/config.js
Labels: size/XS

#4177 Fix deletion query and add debug
  creator-node/src/dbManager.js
Labels: content-node, size/S

#4179 Fall back to entire network on fetchCID
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/api/File.ts
Labels: size/M

#4154 [CON-481] Remove tmp track artifacts on Content Node startup
  creator-node/src/diskManager.js
  creator-node/src/index.ts
Labels: size/S

#4170 Remove redis cache indexing
  discovery-provider/src/tasks/index.py
  discovery-provider/src/utils/redis_cache.py
Labels: size/M

#4183 Add repost playlists on EM to libs
  libs/src/api/entityManager.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/M

#4182 Skip storage middleware for force wipes
  creator-node/src/components/replicaSet/replicaSetController.js
Labels: content-node, size/XS

#4185 CON-482 Prioritize force wipe syncs
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/sync/syncQueue.ts
Labels: size/M

#4097 [CON-458] - Bump async-retry timeout to 10m from 5s
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/fileManager.js
  creator-node/src/redis.js
  creator-node/src/routes/tracks.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/utils/asyncRetry.ts
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/getRegisteredDiscoveryNodes.ts
  creator-node/test/asyncRetry.test.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/peerSetManager.test.js
  creator-node/test/stateMonitoringUtils.test.js
Labels: size/XL

#4175 Scan and prune files on disk
  creator-node/.eslintrc.js
  creator-node/src/diskManager.js
  creator-node/src/diskManager.test.js
  creator-node/src/index.ts
Labels: size/L

#4107 Rewards indexing for audio_transactions_history
  discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#4189 Rethrow errors in asyncRetry
  creator-node/src/services/ContentNodeInfoManager.ts
  creator-node/src/utils/asyncRetry.ts
Labels: size/S

#4191 Add directory size to tmp track artifacts deletion logs
  creator-node/src/diskManager.js
  creator-node/src/index.ts
Labels: size/S

#4193 Lower ensurePrimaryMiddleware maxRetries
  creator-node/src/services/ContentNodeInfoManager.ts
Labels: size/XS
