Repository AudiusProject/apps, pull requests merged in 2022-08, with the labels that each got.

#3592 Concurrency of 15 for updateReplicaSet might be too high for the network
  creator-node/src/config.js
Labels: size/XS

#3594 [INF-215] Kill queries before running online migrations
  discovery-provider/alembic/README.md
  discovery-provider/alembic/env.py
Labels: size/S

#3596 INF-210 Collection of fixes to streamline SDK Publishing job
  .circleci/config.yml
  .circleci/triggers/deploy-sdk.py
  libs/scripts/release.sh
Labels: size/L

#3593 Cache healthy nodes in RS update
  creator-node/src/serviceRegistry.js
  creator-node/src/services/initAudiusLibs.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
Labels: size/L

#3599 INF-210 Prime audius.releaseSHA in libs/package.json
  libs/package.json
Labels: size/XS

#3600 Change the lock duration to correct time
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
Labels: size/XS

#3601 INF-210 use mktemp instead of sponge
  libs/scripts/release.sh
Labels: size/XS

#3603 INF-210 Squash merge commits when publishing SDK
  libs/scripts/release.sh
Labels: size/S

#3602 Clear all reconciliation jobs on restart
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
Labels: content-node, size/XS

#3604 INF-210 Use set -e within merge-bump to catch all errors
  .circleci/config.yml
  libs/scripts/release.sh
Labels: size/M

#3605 Short circuit when sync queue hasn't initialized
  creator-node/src/components/replicaSet/replicaSetController.js
Labels: content-node, size/S

#3607 INF-210 explicitly catch errors and exit out of subshell
  libs/scripts/release.sh
Labels: size/S

#3609 Fix GCP Image bake and local service registration
  .circleci/config.yml
  libs/examples/initAudiusLibs.js
Labels: size/XS

#3611 Rename libs to sdk
  creator-node/scripts/register.js
  dev-tools/startup/creator-node.sh
Labels: size/XS

#3608 De-dupe manual syncs in state machine
  creator-node/src/services/stateMachineManager/stateReconciliation/SyncRequestDeDuplicator.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
Labels: size/M

#3613 triggers count from scratch
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/trigger_sql/handle_user.sql
  discovery-provider/alembic/versions/90ad232bfe92_triggers_count_from_scratch.py
Labels: size/L

#3615 [C-739] Re-initialize contract test cases
  eth-contracts/test/audiusToken.test.js
  eth-contracts/test/delegateManagerV2.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/staking.test.js
Labels: size/M

#3614 [PAY-494] Fixes bug in A up --with-aao
  service-commands/src/setup.js
Labels: size/XS

#3616 INF-210 Rename publish-libs job to publish-sdk
  .circleci/config.yml
  libs/scripts/release.sh
Labels: size/S

#3178 Fix runtime includes TypeError
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/XS

#3514 Land #21 from docs.audius.org
  docs/docs/developers/log-in-with-audius.md
  docs/docs/developers/sdk-oauth-methods.md
  docs/docs/developers/sdk/index.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/api/log-in-with-audius.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/api/sdk-oauth-methods.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/api/sdk/index.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/developers/log-in-with-audius.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk-oauth-methods.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk/index.md
  docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk/index.mdx
Labels: size/S

#3620 Change path due to recent libs change
  dev-tools/startup/build-audius-libs.sh
Labels: size/S

#3621 Related artists index2
  discovery-provider/alembic/versions/35584b65c55e_related_artists_index.py
  discovery-provider/src/models/users/related_artist.py
Labels: size/M

#3622 Fix attemptNumber not getting updated
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
Labels: content-node, size/M

#3617 INF-210 Finishing changes
  .circleci/triggers/__init__.py
  .circleci/triggers/deploy-sdk.py
  libs/scripts/release.sh
Labels: size/M

#3623 Tests for aggregate table triggers
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/versions/d0dfb103535b_update_triggers_to_remove_duplicate_.py
  discovery-provider/integration_tests/models/test_aggregate_counters.py
  discovery-provider/src/utils/alembic_helpers.py
Labels: size/L

#3625 Throw error in syncImmediateQueue
  creator-node/src/services/sync/syncImmediateQueue.js
Labels: size/XS

#3624 CON-303 Cache CN 200-status /health_check responses for 1sec in nginx
  creator-node/nginx_conf/nginx.conf
Labels: size/M

#3595 [CON-301] add prometheus to queues
  creator-node/package-lock.json
  creator-node/src/ImageProcessingQueue.js
  creator-node/src/routes/files.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/lib/app.js
  creator-node/test/prometheus.test.js
  dev-tools/audius-cloud
Labels: size/L

#3628 Remove unused labels
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/sync.test.js
Labels: content-node, size/S

#3629 Fix add track to playlist notification timestamp
  discovery-provider/src/queries/notifications.py
Labels: size/XS

#3584 [C-739] Patch @openzeppelin/upgrades Initializable.sol fields
  .circleci/config.yml
  eth-contracts/package-lock.json
  eth-contracts/package.json
  eth-contracts/patches/@openzeppelin+upgrades+2.8.0.patch
  eth-contracts/test/audiusToken.test.js
  eth-contracts/test/delegateManagerV2.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/staking.test.js
Labels: size/M

#3626 [C-765] Add native libs entrypoint
  libs/rollup.config.js
  libs/src/NativeAudiusLibs.ts
  libs/src/native-libs.ts
Labels: size/XL

#3635 INF-210 fix || exit 1 logic
  libs/scripts/release.sh
Labels: size/XS

#3634 Remove extra done() callback
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
Labels: content-node, size/M

#3636 INF-210 grab VERSION after exiting subshell that bumped version
  libs/scripts/release.sh
Labels: size/XS

#3639 Fix core libs bundle so it can be consumed in client
  libs/rollup.config.js
Labels: size/XS

#3637 INF-210 rename GIT_TAG to GIT_COMMIT
  .circleci/config.yml
  .circleci/triggers/__init__.py
  .circleci/triggers/deploy-sdk.py
  libs/scripts/release.sh
Labels: size/M

#3633 [PAY-401] Update Identity SDK to fix Solana Node Registration Job
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3641 INF-210 include v as VERSION prefix
  libs/scripts/release.sh
Labels: size/XS

#3631 CON-305 fixInconsistentUser() fixes + logging + tests
  creator-node/package-lock.json
  creator-node/src/components/replicaSet/exportComponentService.js
  creator-node/src/dbManager.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/test/dbManager.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/lib/app.js
  creator-node/test/lib/utils.js
Labels: size/L

#3640 Clear running migrations on server start
  creator-node/src/index.ts
  creator-node/src/migrationManager.js
Labels: size/S

#3642 INF-210 include change log in commit and tag
  libs/scripts/release.sh
Labels: size/S

#3638 Make syncs release locks when short circuiting
  creator-node/src/services/sync/secondarySyncFromPrimary.js
Labels: content-node, size/M

#3644 Fix legacy and sdk types, monitoringCallbacks, native exports
  libs/rollup.config.js
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/index.ts
  libs/src/legacy.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
  libs/src/services/types.ts
Labels: size/M

#3645 Add delegateOwnerWallet to CN register
  creator-node/scripts/register.js
Labels: size/XS

#3606 [PLAT-259] Upgrade EthereumTx version
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/relay/ethTxRelay.js
  identity-service/src/relay/txRelay.js
Labels: size/S

#3464 postgres triggers for discovery notifications
  discovery-provider/alembic/trigger_sql/handle_challenge_disbursements.sql
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_play.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_reaction.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/trigger_sql/handle_user_tip.sql
  discovery-provider/alembic/versions/58b26285cdcf_migrate_triggers_for_notifiations.py
  discovery-provider/alembic/versions/9931f7fd118f_migrate_miletones_to_notifications.py
  discovery-provider/alembic/versions/b0623220e904_create_notifications_table.py
  discovery-provider/integration_tests/notifications/test_challenge_disbursement.py
  discovery-provider/integration_tests/notifications/test_follow.py
  discovery-provider/integration_tests/notifications/test_play_milestone.py
  discovery-provider/integration_tests/notifications/test_playlist.py
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/integration_tests/notifications/test_repost.py
  discovery-provider/integration_tests/notifications/test_save.py
  discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
  discovery-provider/integration_tests/notifications/test_track.py
  discovery-provider/integration_tests/notifications/test_user_tip.py
  discovery-provider/integration_tests/tasks/test_generate_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/notifications/notification.py
Labels: size/XXL

#3647 INF add alerts for failed gcp bake jobs
  .circleci/config.yml
Labels: size/XS

#3643 [C-749] Support req pagination and ordering in hist/fav/tracks
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_save_tracks.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_user_listening_history.py
  discovery-provider/src/queries/query_helpers.py
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/L

#3650 Add remix cosign
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
Labels: size/M

#3651 available playlist ID endpoint
  discovery-provider/integration_tests/queries/test_get_playlist_id_occupied.py
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_playlist_is_occupied.py
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#3649 Fix Prometheus Metric Names for Bull Queue Durations
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
  creator-node/test/lib/genericBullQueueMock.js
  creator-node/test/prometheus.test.js
Labels: size/M

#3632 Rename processImmediateSync to processManualImmediateSync for clarity
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/components/replicaSet/syncQueueComponentService.js
  creator-node/src/services/sync/syncImmediateQueue.js
Labels: size/S

#3653 safer kill_running_queries_sql
  discovery-provider/alembic/env.py
Labels: size/S

#3655 Upgrade service-commands to latest sdk
  service-commands/package-lock.json
  service-commands/package.json
Labels: size/XS

#3656 Repair missing wallets
  discovery-provider/alembic/versions/3403e008e6c7_repair_missing_wallets.py
Labels: size/M

#3664 Change openresty location directive from exact match to regex
  creator-node/nginx_conf/nginx.conf
  creator-node/src/config.js
  creator-node/src/utils.js
Labels: size/XS

#3659 Revert "Repair missing wallets (#3656)"
  discovery-provider/alembic/versions/3403e008e6c7_repair_missing_wallets.py
Labels: size/M

#3666 Add slack-secrets to jobs that use Slack notifications
  .circleci/config.yml
Labels: size/XS

#3657 Add unique constraint to notification
  discovery-provider/alembic/trigger_sql/handle_challenge_disbursements.sql
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_play.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_reaction.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/trigger_sql/handle_user_tip.sql
  discovery-provider/alembic/versions/9931f7fd118f_migrate_miletones_to_notifications.py
  discovery-provider/alembic/versions/b0623220e904_create_notifications_table.py
  discovery-provider/integration_tests/notifications/test_challenge_disbursement.py
  discovery-provider/integration_tests/notifications/test_follow.py
  discovery-provider/integration_tests/notifications/test_play_milestone.py
  discovery-provider/integration_tests/notifications/test_playlist.py
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/integration_tests/notifications/test_repost.py
  discovery-provider/integration_tests/notifications/test_save.py
  discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
  discovery-provider/integration_tests/notifications/test_track.py
  discovery-provider/integration_tests/notifications/test_user_tip.py
  discovery-provider/src/models/notifications/notification.py
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/L

#3598 CON-297 Auth check the requester is the primary of the observed user
  creator-node/src/apiSigning.js
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/components/replicaSet/syncQueueComponentService.js
  creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
  creator-node/src/services/stateMachineManager/ContentNodeInfoManager.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/test/ContentNodeInfoManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/secondarySyncFromPrimaryUtils.test.js
  creator-node/test/sync.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/XXL

#3668 Fix TypeError for userSecondarySyncMetrics
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
Labels: content-node, size/S

#3661 Bump random replica select attempt count + filter out existing nodes from healthy replica set
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/S

#3669 Bump to version 0.3.64
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3660 [CON-222] Fix SequelizeUniqueConstraintError for blockchain track ID
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/tracks.js
  creator-node/test/audiusUsers.test.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/sync.test.js
Labels: content-node, size/L

#3673 Use correct configuration for full endpoints
  libs/src/sdk/sdk.ts
Labels: size/M

#3672 Add disable flag to logspout
  .circleci/config.yml
  creator-node/Dockerfile
  discovery-provider/Dockerfile
  logspout/Dockerfile
  logspout/README.md
  logspout/start.sh
Labels: size/S

#3667 Fix downgrades
  discovery-provider/alembic/versions/9931f7fd118f_migrate_miletones_to_notifications.py
  discovery-provider/alembic/versions/b0623220e904_create_notifications_table.py
  discovery-provider/integration_tests/notifications/test_reaction.py
Labels: size/M

#3671 Prevent extra unnecessary reconfig events
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/L

#3676 Filter out notifications from bad initiators
  identity-service/src/notifications/index.js
Labels: size/M

#3662 [PAY-506] Exposes AAO error code
  libs/src/api/Rewards.ts
  libs/src/services/solana/rewardsAttester.ts
Labels: size/M

#3677 Add a log before force resync happens
  creator-node/src/services/sync/secondarySyncFromPrimary.js
Labels: size/XS

#3674 [PAY-459] Add dethroned notifications on Identity
  identity-service/sequelize/migrations/20220809211742-add_supporter_dethroned.js
  identity-service/src/featureFlag.js
  identity-service/src/notifications/constants.js
  identity-service/src/notifications/fetchNotificationMetadata.js
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
  identity-service/src/notifications/sendNotifications/index.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
  identity-service/src/routes/notifications.js
Labels: size/L

#3610 [PAY-485][PAY-491] Handle premium content signature
  creator-node/.eslintrc.js
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  creator-node/src/apiSigning.js
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.test.ts
  creator-node/src/middlewares/premiumContent/premiumContentMiddleware.ts
  creator-node/src/premiumContent/helpers.ts
  creator-node/src/premiumContent/types.ts
  creator-node/src/utils/getRegisteredDiscoveryNodes.ts
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
Labels: size/XL

#3681 Fix bad notifs
  identity-service/src/notifications/index.js
Labels: size/S

#3682 Revert "[PLAT-259] Upgrade EthereumTx version (#3606)"
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/relay/ethTxRelay.js
  identity-service/src/relay/txRelay.js
Labels: size/S

#3684 populate save_count in feed endpoint
  discovery-provider/src/queries/get_feed_es.py
Labels: size/XS

#3683 Use abuse error codes in relay
  identity-service/sequelize/migrations/20220811205355-add-abusive-error-code.js
  identity-service/src/featureFlag.js
  identity-service/src/routes/relay.js
  identity-service/src/utils/antiAbuse.js
Labels: size/M

#3686 Handle zero error code
  identity-service/src/models/user.js
  identity-service/src/utils/antiAbuse.js
Labels: size/XS

#3680 [CON-324] Add orphaned data recovery queue
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/recoverOrphanedData.jobProcessor.test.js
Labels: content-node, size/L

#3678 CON-327 Miscellaneous secondarySyncFromPrimary() improvements to logic + metric tracking
  creator-node/src/dbManager.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/syncQueue.js
Labels: size/M

#3689 [Libs]: Update @solana/spl-token to 0.1.8
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3688 Add custom headers to all axios calls to health check in content node
  creator-node/src/components/replicaSet/URSMRegistrationComponentService.js
  creator-node/src/services/stateMachineManager/CNodeHealthManager.js
  creator-node/src/snapbackSM/peerSetManager.js
  libs/src/api/ServiceProvider.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/utils/network.ts
Labels: size/M

#3690 [PAY-530] Fix dethroned push notifs
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: size/XS

#3687 Allow abusive user redemption
  identity-service/src/routes/relay.js
Labels: size/XS

#3685 CON-328 Add manual mergePrimaryAndSecondary route for testing
  creator-node/.gitignore
  creator-node/package.json
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
Labels: size/M

#3400 Add entity manager for playlist actions
  contracts/scripts/migrate-contracts.js
  discovery-provider/alembic/versions/f1e86fba0357_add_playlist_metadata.py
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/queries/test_get_playlist_id_occupied.py
  discovery-provider/integration_tests/tasks/test_entity_manager.py
  discovery-provider/integration_tests/tasks/test_track_entity_manager.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/app.py
  discovery-provider/src/models/playlists/playlist.py
  discovery-provider/src/queries/get_playlist_is_occupied.py
  discovery-provider/src/queries/get_playlists.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/utils/cid_metadata_client.py
  discovery-provider/src/utils/constants.py
  discovery-provider/src/utils/redis_cache.py
  discovery-provider/src/utils/user_event_constants.py
  libs/data-contracts/ABIs/EntityManager.json
  libs/initScripts/configureLocalDiscProv.js
  libs/src/AudiusLibs.ts
  libs/src/api/Track.ts
  libs/src/api/entityManager.ts
  libs/src/data-contracts/ABIs/AudiusData.json
  libs/src/data-contracts/ABIs/EntityManager.json
  libs/src/data-contracts/signatureSchemas.ts
  libs/src/eth-contracts/ABIs/Wormhole.json
  libs/src/services/ABIDecoder/AudiusABIDecoder.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/services/schemaValidator/SchemaValidator.ts
  libs/src/services/schemaValidator/schemas/playlistSchema.json
  libs/src/utils/types.ts
  service-commands/src/commands/service-commands.json
Labels: size/XXL

#3665 [C-785] Add request sorters to hist/fav/tracks
  discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/models/tracks/track_with_aggregates.py
  discovery-provider/src/queries/get_save_tracks.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/get_user_listening_history.py
  discovery-provider/src/queries/query_helpers.py
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  service-commands/src/setup.js
Labels: size/XL

#3698 Add entity manager contract ABI
  discovery-provider/build/contracts/EntityManager.json
Labels: size/L

#3699 Add new feature flag for Dethroned push notifs
  identity-service/src/featureFlag.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: identity-service, size/XS

#3700 Remove playlist is occupied API
  discovery-provider/integration_tests/queries/test_get_playlist_id_occupied.py
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_playlist_is_occupied.py
Labels: size/M

#3701 Add playlist metadata timestamp type
  libs/src/sdk/api/generated/full/models/PlaylistAddedTimestamp.ts
Labels: size/XS

#3702 Log stack traces of update-replica-set errors
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: content-node, size/M

#3697 [PLAT-289] Add endpoint for playlist tracks
  discovery-provider/src/api/v1/playlists.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/full/models/FullPlaylistTracksResponse.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#3704 Update block error codes
  identity-service/src/routes/relay.js
Labels: size/XS

#3654 track trigger runs on update
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/versions/5d3f95470222_track_trigger_update.py
  discovery-provider/integration_tests/models/test_aggregate_counters.py
Labels: size/M

#3709 Track is available flag
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/versions/5d3f95470222_track_trigger_update.py
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/integration_tests/models/test_aggregate_counters.py
  discovery-provider/src/utils/alembic_helpers.py
Labels: size/M

#3710 INF-201 Enable local ELK and Grafana-related Sidecars by default for remote-dev
  service-commands/src/setup.js
Labels: size/XS

#3703 PrimarySyncFromSecondary() improvements to error handling and logging
  creator-node/src/middlewares.js
  creator-node/src/services/stateMachineManager/ContentNodeInfoManager.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/utils/decisionTree.ts
  creator-node/test/sync/assets/export.json
  creator-node/test/sync/assets/realExport.json
Labels: size/XL

#3627 INF-213 New Alchemy and SDK Prometheus Exporters
  monitoring/docker-compose.yml
  monitoring/exporters/.eslintrc.json
  monitoring/exporters/.gitignore
  monitoring/exporters/alchemy/Dockerfile
  monitoring/exporters/alchemy/main.js
  monitoring/exporters/alchemy/package.json
  monitoring/exporters/sdk/Dockerfile
  monitoring/exporters/sdk/main.js
  monitoring/exporters/sdk/package.json
  monitoring/grafana/alerts/alert.template.json
  monitoring/grafana/dashboards/audius-governance.json
  monitoring/grafana/dashboards/audius-token.json
  monitoring/prometheus/ymls/local.yml
Labels: size/XXL

#3708 INF-221 Automate Grafana Alert extraction from Grafana Panels
  monitoring/README.md
  monitoring/grafana/Dockerfile
  monitoring/grafana/alerts/alert.template.json
  monitoring/grafana/alerts/audius-governance_new-proposals.json
  monitoring/grafana/alerts/audius-governance_open-proposals.json
  monitoring/grafana/alerts/audius-governance_proposals-by-unknown-proposers.json
  monitoring/grafana/alerts/audius-token_contract-balances-staking.json
  monitoring/grafana/alerts/audius-token_contract-balances.json
  monitoring/grafana/alerts/audius-token_contract-movements.json
  monitoring/grafana/alerts/audius-token_token-transfers-amount-increase-over-5m.json
  monitoring/grafana/bin/delete-alerts.sh
  monitoring/grafana/bin/extract-alerts.py
  monitoring/grafana/bin/extract-alerts.sh
  monitoring/grafana/bin/save-dashboards.sh
  monitoring/grafana/bin/upload-alerts.sh
  monitoring/grafana/bin/upload-library-panels.sh
Labels: size/XXL

#3707 Pass cover art when creating a playlist from existing track
  libs/src/api/entityManager.ts
  libs/src/services/web3Manager/Web3Config.ts
Labels: size/S

#3711 [C-853] Add solanaWeb3Manager to NativeAudiusLibs
  creator-node/package-lock.json
  creator-node/package.json
  identity-service/package-lock.json
  identity-service/package.json
  libs/package-lock.json
  libs/package.json
  libs/src/NativeAudiusLibs.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/wormhole/Wormhole.ts
  service-commands/package-lock.json
  service-commands/package.json
Labels: size/L

#3712 Avoid sending recovery and welcome emails
  identity-service/src/routes/recovery.js
  identity-service/src/routes/welcomeEmail.js
Labels: size/XS

#3713 Fix get_tracks typo
  discovery-provider/src/queries/get_tracks.py
Labels: size/XS

#3714 Improve history query
  discovery-provider/src/queries/get_user_listening_history.py
Labels: size/M

#3717 Fix get_feed_es save_count, add test
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/queries/get_feed_es.py
Labels: size/S

#3715 INF-221 Further testing of Grafana Alerts on Clean Dev Environments
  monitoring/README.md
  monitoring/docker-compose.yml
  monitoring/grafana/Dockerfile
  monitoring/grafana/alerts/alert.template.json
  monitoring/grafana/alerts/audius-governance_new-proposals.json
  monitoring/grafana/alerts/audius-governance_open-proposals.json
  monitoring/grafana/alerts/audius-governance_proposals-by-unknown-proposers.json
  monitoring/grafana/alerts/audius-token_contract-balances-staking.json
  monitoring/grafana/alerts/audius-token_contract-balances.json
  monitoring/grafana/alerts/audius-token_contract-movements.json
  monitoring/grafana/alerts/audius-token_token-transfers-amount-increase-over-5m.json
  monitoring/grafana/bin/extract-alerts.py
  monitoring/grafana/bin/extract-alerts.sh
  monitoring/grafana/bin/save-dashboards.sh
  monitoring/grafana/bin/upload-dashboards.sh
  monitoring/grafana/bin/upload-library-panels.sh
  monitoring/grafana/dashboards/folders.json
  monitoring/scripts/deploy.sh
Labels: size/XL

#3705 Add track entity cid type
  discovery-provider/src/tasks/index.py
Labels: size/XS

#3724 Fix dethroned push notif copy
  identity-service/src/notifications/formatNotificationMetadata.js
Labels: size/XS

#3722 Revert @solana/web3.js version
  creator-node/package-lock.json
  creator-node/package.json
  identity-service/package-lock.json
  identity-service/package.json
  libs/package-lock.json
  libs/package.json
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/wormhole/Wormhole.ts
  service-commands/package-lock.json
  service-commands/package.json
Labels: size/S

#3725 Bump identity audius sdk version 0.0.35
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3726 Do not send bad download app emails
  identity-service/src/notifications/sendDownloadAppEmails.js
Labels: size/XS

#3727 Fix var
  identity-service/src/notifications/sendDownloadAppEmails.js
Labels: size/XS

#3723 Allow RS update when node is deregistered
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/M

#3729 Add is_streamable to api surface
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/tracks.py
  libs/src/sdk/api/generated/default/models/Track.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
Labels: size/S

#3694 Consolidate storage calculation
  creator-node/compose/env/base.env
  creator-node/scripts/run-tests.sh
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/CNodeHealthManager.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/test/CNodeHealthManager.test.js
  creator-node/test/peerSetManager.test.js
Labels: size/L

#3731 Skip entity manager txs that fail to process
  discovery-provider/integration_tests/tasks/test_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
Labels: size/L

#3719 Playlist updates from cached playlist state
  libs/src/api/entityManager.ts
Labels: size/L

#3718 CON-253 Add unavail content skipping to PrimarySyncFromSecondary()
  creator-node/src/fileManager.js
  creator-node/src/services/sync/UserSyncFailureCountManager.js
  creator-node/src/services/sync/UserSyncFailureCountService.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/skippedCIDsRetryService.js
  creator-node/src/utils/decisionTree.ts
  creator-node/test/sync.test.js
Labels: size/XL

#3648 Add some setup instructions
  dev-tools/README.md
Labels: size/S

#3728 [PLAT-294] Falsey flag in entity manager indexing
  discovery-provider/integration_tests/tasks/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/S

#3733 [CON-284] Distributed Tracing - auto instrumentation
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/index.ts
  creator-node/src/tracer.ts
  discovery-provider/requirements.txt
  discovery-provider/src/app.py
  discovery-provider/src/tracer.py
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/index.js
  identity-service/src/tracer.js
Labels: size/L

#3737 Update default config to dev env
  discovery-provider/default_config.ini
Labels: size/XS

#3736 Add first playlist challenge to entity manager
  discovery-provider/src/tasks/entity_manager/playlist.py
Labels: size/S

#3734 Add entity manager address param to configInternalWeb3 native
  libs/src/NativeAudiusLibs.ts
Labels: size/XS

#3738 Fix track upload challenge integration test
  discovery-provider/integration_tests/challenges/test_track_upload_challenge.py
Labels: size/XS

#3744 CN - Minor decision tree logging fixes
  creator-node/src/fileManager.js
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/utils/decisionTree.ts
Labels: size/S

#3741 Fix not returning result when secondarySyncFromPrimary sync is not required
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/sync/secondarySyncFromPrimary.js
Labels: content-node, size/XL

#3745 Avoid stalling entity manager with undefined params
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#3706 Track entity manager
  libs/src/api/Track.ts
  libs/src/api/entityManager.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
  libs/src/utils/utils.ts
Labels: feature, libs, size/L

#3747 remove lexeme dict + old search code
  discovery-provider/alembic/versions/551f5fc03862_drop_lexeme.py
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/search_config.py
  discovery-provider/src/queries/search_queries.py
  discovery-provider/src/tasks/index_materialized_views.py
  discovery-provider/src/utils/session_manager.py
Labels: size/XXL

#3748 [PAY-579] Checks associated account or SOL before transfer
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/S

#2609 Removing duplicate logs
  identity-service/src/routes/wormhole.js
Labels: size/XS

#3751 Bump to version 0.3.65
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3739 [CON-310] Redo issue_update_replica_set metric for granular statuses
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/processJob.ts
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: size/L

#3753 revert track entity upload
  libs/src/api/Track.ts
Labels: size/S

#3742 [PLAT-308] Fix wormhole on identity
  libs/src/AudiusLibs.ts
  libs/src/services/wormhole/Wormhole.ts
Labels: size/M

#3755 Fix playlist entity manager invalid tx logic and last_added_to
  discovery-provider/integration_tests/tasks/test_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/playlist.py
Labels: size/S

#3756 Fix entity manager playlist invalidation
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/S

#3749 CON-366 CN - Log on secondarySyncFromPrimary() success + logging cleanup
  creator-node/package-lock.json
  creator-node/src/logging.js
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
Labels: size/M

#3696 [CON-324] Implement orphaned data recovery
  creator-node/.gitignore
  creator-node/Dockerfile
  creator-node/compose/env/base.env
  creator-node/nodemon.json
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/config.js
  creator-node/src/middlewares.js
  creator-node/src/routes/playlists.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/src/utils/index.ts
  creator-node/src/utils/strToReplicaSet.ts
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/recoverOrphanedData.jobProcessor.test.js
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
  creator-node/test/sync.test.js
  creator-node/tsconfig.base.json
  creator-node/tsconfig.build.json
  creator-node/tsconfig.json
Labels: content-node, size/XXL

#3760 Make Content Node tsconfig include all src files
  creator-node/tsconfig.build.json
Labels: content-node, size/XS

#3754 [CON-363] Skip replica set updates for users w/o URSM data
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
Labels: content-node, size/M

#3761 Fix invalidate playlist's original record
  discovery-provider/integration_tests/tasks/test_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/M

#3757 Fix wormhole with upgraded libs
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3763 CON-368 Fix sync duration logging bug
  creator-node/src/services/sync/syncImmediateQueue.js
  creator-node/src/services/sync/syncQueue.js
Labels: size/S

#3764 Fix issueSyncRequest libs not having ethContracts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
Labels: content-node, size/XS

#3730 New "soft unhealthy" env var + actually set healthy status from content node
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/CNodeHealthManager.js
  creator-node/test/CNodeHealthManager.test.js
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
Labels: size/M
