Repository AudiusProject/apps, pull requests merged in 2022-05, with the labels that each got.

#3008 Cache latest timestamp from SOL and pass it into listen transactions
  identity-service/src/solana-client.js
Labels: size/S

#3007 Conditional on empty Plays insert
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/M

#3009 Eliminate batch resize, forcibly wipe cache to avoid intersect loop
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/S

#3013 Fix solana programs admin key naming
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
  solana-programs/start.sh
Labels: size/M

#2997 Change user_tips PKEY to signature and index slot column
  discovery-provider/alembic/env.py
  discovery-provider/alembic/versions/378ef6680606_user_tips_index_change.py
  discovery-provider/src/models/user_tip.py
Labels: size/L

#3016 [CON-122] Batch mad dog libs interactions
  mad-dog/README.md
  mad-dog/src/helpers.js
  mad-dog/src/index.js
Labels: size/XL

#2872 Initial commit of API client generator with template
  api-client-generator/.gitignore
  api-client-generator/README.md
  api-client-generator/gen.js
  api-client-generator/openapitools.json
  api-client-generator/package-lock.json
  api-client-generator/package.json
  api-client-generator/templates/typescript-fetch/ApiEntitiesRecord.mustache
  api-client-generator/templates/typescript-fetch/ApiEntitiesReducer.mustache
  api-client-generator/templates/typescript-fetch/ApiEntitiesSelectors.mustache
  api-client-generator/templates/typescript-fetch/README.mustache
  api-client-generator/templates/typescript-fetch/allSagas.mustache
  api-client-generator/templates/typescript-fetch/apis.index.mustache
  api-client-generator/templates/typescript-fetch/apis.mustache
  api-client-generator/templates/typescript-fetch/gitignore
  api-client-generator/templates/typescript-fetch/index.mustache
  api-client-generator/templates/typescript-fetch/licenseInfo.mustache
  api-client-generator/templates/typescript-fetch/modelEnum.mustache
  api-client-generator/templates/typescript-fetch/modelEnumInterfaces.mustache
  api-client-generator/templates/typescript-fetch/modelGeneric.mustache
  api-client-generator/templates/typescript-fetch/modelGenericInterfaces.mustache
  api-client-generator/templates/typescript-fetch/modelOneOf.mustache
  api-client-generator/templates/typescript-fetch/modelOneOfInterfaces.mustache
  api-client-generator/templates/typescript-fetch/models.index.mustache
  api-client-generator/templates/typescript-fetch/models.mustache
  api-client-generator/templates/typescript-fetch/npmignore.mustache
  api-client-generator/templates/typescript-fetch/package.mustache
  api-client-generator/templates/typescript-fetch/recordGeneric.mustache
  api-client-generator/templates/typescript-fetch/records.mustache
  api-client-generator/templates/typescript-fetch/runtime.mustache
  api-client-generator/templates/typescript-fetch/runtimeSagasAndRecords.mustache
  api-client-generator/templates/typescript-fetch/sagaApiManager.mustache
  api-client-generator/templates/typescript-fetch/sagas.mustache
  api-client-generator/templates/typescript-fetch/sourceLibraryIndex.mustache
  api-client-generator/templates/typescript-fetch/tsconfig.mustache
Labels: size/XXL

#2987 [CON-71] Parallelize aggregateReconfigAndPotentialSyncOps in chunks of 500 users
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: size/L

#2760 Override challenges to have starting block 0 for local dev
  discovery-provider/src/challenges/challenges.dev.json
  discovery-provider/src/challenges/create_new_challenges.py
Labels: size/M

#3012 v0.0.2
  solana-programs/anchor/audius-data/package.json
Labels: size/XS

#2944 [AUD-1919] Refactor DiscoveryProvider to typescript
  libs/.eslintrc
  libs/package-lock.json
  libs/package.json
  libs/src/index.js
  libs/src/service-selection/ServiceSelection.ts
  libs/src/services/comstock/Comstock.ts
  libs/src/services/comstock/index.js
  libs/src/services/comstock/index.ts
  libs/src/services/contracts/ContractClient.js
  libs/src/services/contracts/ContractClient.ts
  libs/src/services/contracts/GovernedContractClient.js
  libs/src/services/contracts/ProviderSelection.js
  libs/src/services/contracts/ProviderSelection.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/dataContracts/IPLDBlacklistFactoryClient.js
  libs/src/services/dataContracts/playlistFactoryClient.js
  libs/src/services/dataContracts/registryClient.js
  libs/src/services/dataContracts/socialFeatureFactoryClient.js
  libs/src/services/dataContracts/trackFactoryClient.js
  libs/src/services/dataContracts/userFactoryClient.js
  libs/src/services/dataContracts/userLibraryFactoryClient.js
  libs/src/services/dataContracts/userReplicaSetManagerClient.js
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
  libs/src/services/discoveryProvider/constants.js
  libs/src/services/discoveryProvider/constants.ts
  libs/src/services/discoveryProvider/index.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/services/ethContracts/claimDistributionClient.js
  libs/src/services/ethContracts/claimsManagerClient.js
  libs/src/services/ethContracts/ethRewardsManagerClient.js
  libs/src/services/ethContracts/governanceClient.js
  libs/src/services/ethContracts/index.d.ts
  libs/src/services/ethContracts/stakingProxyClient.js
  libs/src/services/web3Manager/index.d.ts
  libs/src/types.ts
  libs/src/userStateManager.ts
  libs/tests/providerSelectionTest.js
  libs/tsconfig.json
Labels: size/XXL

#2992 Update isAvailable() fn to accept more jobs + refactor asyncRetry fn to be more generic and customizable
  creator-node/src/TranscodingQueue.js
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/config.js
  creator-node/src/utils.js
  creator-node/test/TrackTranscodeHandoffManager.test.js
  creator-node/test/utils.test.js
Labels: size/L

#3018 Add auth-headers command to seed script
  service-commands/scripts/seed.js
  service-commands/src/commands/seed/SeedSession.js
Labels: service-commands, size/S

#2999 Use cached solana docker with programs baked in
  service-commands/scripts/bootstrap-solana-program-docker.js
  service-commands/scripts/setup.js
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
  solana-programs/Dockerfile.cacheLedger
Labels: size/L

#3023 Return the notifications after processing tierChange
  identity-service/src/notifications/processNotifications/tierChangeNotification.js
Labels: size/XS

#3021 Wait 10 seconds after trying health check instead of before
  service-commands/src/setup.js
Labels: service-commands, size/XS

#3025 Hold off track transcode load balancing
  creator-node/src/routes/tracks.js
Labels: size/S

#2989 [CON-70 & CON-74] Snapback `getNodeUsers` unreliability & slowness
  creator-node/src/snapbackSM/peerSetManager.js
  discovery-provider/src/queries/queries.py
Labels: javascript, content-node, size/L

#3030 Bump to v0.3.57
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2976 [CON-76] Add logger param to some libs functions that CN uses
  libs/src/api/base.js
  libs/src/api/serviceProvider.js
  libs/src/index.js
  libs/src/services/contracts/ContractClient.ts
  libs/src/services/contracts/GovernedContractClient.js
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/dataContracts/index.js
  libs/src/services/ethContracts/delegateManagerClient.js
  libs/src/services/ethContracts/governanceClient.js
  libs/src/services/ethContracts/index.js
  libs/src/services/ethContracts/serviceProviderFactoryClient.js
  libs/src/services/ethContracts/stakingProxyClient.js
  libs/src/utils/types.ts
Labels: javascript, libs, content-node, size/L

#3036 Fix max_slot_result None check
  discovery-provider/src/tasks/index_aggregate_tips.py
Labels: discovery-node, size/XS

#2993 [PAY-121] [PAY-150] Index Tipping Leaderboard Notifications
  discovery-provider/alembic/versions/5ea8fd4ae1fb_supporter_rank_ups.py
  discovery-provider/requirements.txt
  discovery-provider/scripts/seed.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/supporter_rank_up.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/tasks/aggregates/__init__.py
  discovery-provider/src/tasks/index_aggregate_tips.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/L

#3026 Find the sender/receiver indices
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/XS

#3037 [CON-70](bug fix): `asyncRetry()` signature update in `getNodeUsers()`
  creator-node/src/snapbackSM/peerSetManager.js
Labels: size/S

#3017 Support reactions in identity
  identity-service/sequelize/migrations/20220428223149-add_reactions.js
  identity-service/src/models/reaction.js
  identity-service/src/routes/reactions.js
Labels: size/L

#3035 Fix dev env python path and update version comments
  discovery-provider/Dockerfile
  service-commands/scripts/.env/.aliases/10.audius_aliases
  service-commands/scripts/provision-dev-env.sh
Labels: size/M

#3014 Add track updates to anchor program indexing
  discovery-provider/src/app.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/solana/solana_program_indexer.py
  solana-programs/anchor/audius-data/cli/main.ts
Labels: size/L

#3019 Allow specifying signer group keypair
  solana-programs/cli/src/main.rs
Labels: size/M

#3034 [CON-138] Lower retry attempts for issuing new replica set
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/XS

#2980 Fix loggly tag generation on discprov
  discovery-provider/scripts/start.sh
Labels: size/S

#3033 [CON-76] Bump libs to v1.2.113
  libs/package.json
Labels: javascript, libs, size/XS

#3024 [CON-131] Refactor state machine redis metrics to reduce calls
  creator-node/src/snapbackSM/secondarySyncHealthTracker.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/secondarySyncHealthTracker.test.js
  creator-node/test/snapbackSM.test.js
Labels: size/L

#3045 Libs v1.2.114
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3047 Fix missing fi
  discovery-provider/scripts/start.sh
Labels: size/XS

#3044 Handle exceptions from collectors
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/S

#3040 Tip Notifications
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/response_name_constants.py
Labels: discovery-node, size/M

#3027 [PAY-126] [PAY-114] Add supporters/supporting API
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/support.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_support_for_user.py
Labels: discovery-node, size/L

#2966 Add anchor programs lib to audius libs
  libs/.eslintrc
  libs/package-lock.json
  libs/package.json
  libs/src/index.js
  libs/src/services/solanaAudiusData/errors.ts
  libs/src/services/solanaAudiusData/index.ts
  libs/src/services/solanaWeb3Manager/index.d.ts
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/src/services/solanaWeb3Manager/utils.d.ts
  libs/src/services/web3Manager/index.d.ts
Labels: size/XXL

#3053 Bump libs version v1.2.115
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3050 prune with -f within CircleCI
  .circleci/config.yml
Labels: size/XS

#3049 [PAY-152] Discovery Node: Index Reactions
  discovery-provider/alembic/versions/35198266d709_index_reactions.py
  discovery-provider/src/app.py
  discovery-provider/src/models/models.py
  discovery-provider/src/models/reaction.py
  discovery-provider/src/tasks/index_reactions.py
Labels: size/L

#2965 Add identity relay with signature sol
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/config.js
  identity-service/src/routes/solana.js
  identity-service/src/utils/relayHelpers.js
Labels: size/S

#3043 Add Identity route to get user's email
  identity-service/src/routes/user.js
  libs/src/api/account.js
  libs/src/services/identity/IdentityService.ts
Labels: size/M

#3051 [INF-80] Add health check to Dockerfile
  creator-node/Dockerfile
  discovery-provider/Dockerfile
  identity-service/Dockerfile
Labels: size/S

#3056 Pass in anchorAudiusData
  libs/src/api/base.js
Labels: size/XS

#3058 Bump libs to v1.2.116
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3046 [CON-81] Fetch file from content node network if file size is 0
  creator-node/src/fileManager.js
  creator-node/src/routes/files.js
  creator-node/src/utils.js
Labels: content-node, size/M

#3061 Fix fetch notification metadata log
  identity-service/src/notifications/fetchNotificationMetadata.js
Labels: size/XS

#3048 Docker Data and Eth contracts baked in
  contracts/Dockerfile.cacheLedger
  contracts/contract-config.js
  contracts/migrations/4_user_replica_set_migration.js
  eth-contracts/Dockerfile.cacheLedger
  libs/initScripts/local.js
  service-commands/scripts/bootstrap-eth-contracts-docker.js
  service-commands/scripts/setup.js
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
Labels: size/L

#3062 Fix aggregate functions
  discovery-provider/src/tasks/aggregates/__init__.py
  discovery-provider/src/tasks/aggregates/index_aggregate_plays.py
  discovery-provider/src/tasks/aggregates/index_aggregate_track.py
  discovery-provider/src/tasks/index_aggregate_user.py
Labels: discovery-node, size/S

#3066 Batch track metadata notification fetches
  identity-service/src/notifications/fetchNotificationMetadata.js
  identity-service/test/sendNotifications/index.js
Labels: size/M

#3068 Remove IPFS from DP start.sh
  discovery-provider/scripts/start.sh
Labels: size/S

#2979 Run local setup, bake image and mad dog on GCP
  .circleci/GCP/Dockerfile.CircleCi-GCloud-Bake
  .circleci/config.yml
  service-commands/scripts/A
  service-commands/scripts/create-instance.sh
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/utils.sh
Labels: size/L

#3067 Provision dev with upgraded pip
  service-commands/scripts/provision-dev-env.sh
Labels: size/XS

#3055 (Content Node) Add dashboard for visualizing Bull queues + change cron to re-queuing on completion/failure
  creator-node/compose/env/base.env
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/app.js
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/serviceRegistry.js
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/L

#3002 [INF-97] README + ergonomic updates
  README.md
  service-commands/package-lock.json
  service-commands/scripts/init-repos.sh
  service-commands/scripts/setup.js
  solana-programs/anchor/audius-data/.gitignore
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
Labels: size/L

#3039 Speed up "all up" service command
  creator-node/scripts/start.sh
  identity-service/scripts/dev-server.sh
  service-commands/.gitignore
  service-commands/scripts/run-libs.sh
  service-commands/scripts/setup.js
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
Labels: service-commands, size/L

#3072 Fix mad-dog to GCP invalid name errors
  .circleci/config.yml
Labels: size/XS

#3074 Use loggly's recommended MaxMessageSize of 64k
  creator-node/scripts/start.sh
Labels: size/XS

#3063 [C-313] Refactor EthContracts to typescript
  libs/package-lock.json
  libs/package.json
  libs/src/index.js
  libs/src/services/ABIDecoder/AudiusABIDecoder.ts
  libs/src/services/ABIDecoder/index.ts
  libs/src/services/contracts/ContractClient.ts
  libs/src/services/contracts/GovernedContractClient.js
  libs/src/services/contracts/GovernedContractClient.ts
  libs/src/services/contracts/ProviderSelection.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/dataContracts/registryClient.js
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
  libs/src/services/ethContracts/AudiusTokenClient.ts
  libs/src/services/ethContracts/ClaimDistributionClient.ts
  libs/src/services/ethContracts/ClaimsManagerClient.ts
  libs/src/services/ethContracts/DelegateManagerClient.ts
  libs/src/services/ethContracts/EthContracts.ts
  libs/src/services/ethContracts/EthRewardsManagerClient.ts
  libs/src/services/ethContracts/GovernanceClient.ts
  libs/src/services/ethContracts/RegistryClient.ts
  libs/src/services/ethContracts/ServiceProviderFactoryClient.ts
  libs/src/services/ethContracts/ServiceTypeManagerClient.ts
  libs/src/services/ethContracts/StakingProxyClient.ts
  libs/src/services/ethContracts/TrustedNotifierManagerClient.ts
  libs/src/services/ethContracts/WormholeClient.ts
  libs/src/services/ethContracts/claimDistributionClient.js
  libs/src/services/ethContracts/claimsManagerClient.js
  libs/src/services/ethContracts/delegateManagerClient.js
  libs/src/services/ethContracts/index.d.ts
  libs/src/services/ethContracts/index.ts
  libs/src/services/ethContracts/registryClient.js
  libs/src/services/ethContracts/serviceProviderFactoryClient.js
  libs/src/services/ethContracts/serviceTypeManagerClient.js
  libs/src/services/ethContracts/stakingProxyClient.js
  libs/src/services/ethWeb3Manager/EthWeb3Manager.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/services/solanaAudiusData/index.ts
  libs/src/services/web3Manager/Web3Config.ts
  libs/src/services/web3Manager/Web3Manager.ts
  libs/src/services/web3Manager/XMLHttpRequest.ts
  libs/src/services/web3Manager/index.d.ts
  libs/src/services/web3Manager/index.js
  libs/src/services/web3Manager/index.ts
  libs/src/types.ts
  libs/src/utils/estimateGas.ts
  libs/src/utils/importContractABI.d.ts
  libs/src/utils/utils.ts
  libs/tests/governanceTest.js
  libs/tests/providerSelectionTest.js
  libs/types/@audius-hedgehog/index.d.ts
Labels: size/XXL

#3020 Use global slot for solana notifications
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/index_listen_count_milestones.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/utils/redis_constants.py
Labels: discovery-node, size/M

#3059 Add kibana contain + update ES dev env
  discovery-provider/compose/docker-compose.redis.yml
  discovery-provider/es-indexer/README.md
  discovery-provider/scripts/dev-server.sh
Labels: size/S

#3064 [CON-118] (Content Node) Paginate getNodeUsers in snapback
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/utils.js
Labels: size/M

#3077 Add supporter metadata to user
  discovery-provider/alembic/env.py
  discovery-provider/alembic/versions/f11f9e83b28b_add_supporter_and_supporting_to_.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/models.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/tasks/index_aggregate_tips.py
Labels: discovery-node, size/L

#3081 Forgot to checkout the right branch before running mad dog
  .circleci/config.yml
Labels: size/XS

#3075 es-indexer: retry + load following IDs in batches
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
  discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/logger.ts
Labels: size/L

#3079 use balanced ssds instead of spinning disks for remote-dev
  service-commands/scripts/create-instance.sh
  service-commands/scripts/utils.sh
Labels: size/S

#3065 [PAY-127] Tips API Endpoint
  discovery-provider/scripts/seed.py
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/tips.py
  discovery-provider/src/api/v1/tips.py
  discovery-provider/src/queries/get_tips.py
Labels: size/XL

#3084 Add debugging tools for remote-dev
  service-commands/scripts/provision-dev-env.sh
Labels: size/S

#3071 [CON-118] (Discovery Node) Paginate /v1/full/users/content_node route
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_users_cnode.py
Labels: size/M

#3087 Convert SPL to Wei for tip amounts
  discovery-provider/requirements.txt
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/queries/get_attestation.py
  discovery-provider/src/utils/spl_audio.py
Labels: discovery-node, size/S

#3090 Fix negative tips, aggregate_tips
  discovery-provider/scripts/seed.py
  discovery-provider/src/tasks/index_aggregate_tips.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/M

#3076 Make celery_tasks_check response more human readable
  discovery-provider/src/queries/get_celery_tasks.py
  discovery-provider/src/queries/health_check.py
Labels: size/S

#3091 Add supporter/supporting endpoints to full ns
  discovery-provider/src/api/v1/models/support.py
  discovery-provider/src/api/v1/users.py
Labels: discovery-node, size/M

#3083 Add tries to es indexer health check
  discovery-provider/src/queries/get_health.py
Labels: size/S

#3092 Declare last_tx
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/XS

#3082 Add ES indexer integration test
  .circleci/config.yml
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/main.ts
  discovery-provider/integration_tests/tasks/test_es_indexer.py
  discovery-provider/src/queries/get_health.py
Labels: size/L

#3078 [PAY-175][PAY-173][PAY-146] Discovery: Reaction Notifications
  discovery-provider/alembic/versions/0d2067242dd5_change_reaction_column_names.py
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/reactions.py
  discovery-provider/src/api/v1/reactions.py
  discovery-provider/src/models/reaction.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/reactions.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/tasks/index_reactions.py
  identity-service/sequelize/migrations/20220509223231-change_reaction_columns.js
  identity-service/src/models/reaction.js
  identity-service/src/routes/reactions.js
  service-commands/scripts/seed-audio.sh
Labels: size/L

#3094 [PAY-192] Add send first tip challenge
  discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  discovery-provider/src/challenges/challenge_event.py
  discovery-provider/src/challenges/challenge_event_bus.py
  discovery-provider/src/challenges/challenges.dev.json
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
  discovery-provider/src/challenges/send_first_tip_challenge.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#3095 Make full supporter/supporting response fuller
  discovery-provider/src/api/v1/users.py
Labels: discovery-node, size/XS

#3100 Discovery: Fix Solana Notifications
  discovery-provider/src/queries/notifications.py
Labels: size/XS

#3099 Add route to Discovery for verifying JWT C-445
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_user_with_wallet.py
Labels: size/L

#3103 Use correct sender/receiver account indexes
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/S

#3097 Fix various bugs with tips endpoint
  discovery-provider/alembic/versions/a83814aeb4a1_add_updated_at_to_usertip.py
  discovery-provider/src/api/v1/tips.py
  discovery-provider/src/models/aggregate_user_tips.py
  discovery-provider/src/models/user_tip.py
  discovery-provider/src/queries/get_tips.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: discovery-node, size/L

#3104 Use a default for updated_at column
  discovery-provider/alembic/versions/a83814aeb4a1_add_updated_at_to_usertip.py
Labels: discovery-node, size/S

#3102 Clean up state machine and add timing logs
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/utils.js
  creator-node/test/snapbackSM.test.js
Labels: size/L

#3101 Add location endpoint to discovery
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/health_check.py
Labels: size/M

#3106 get_feed_es: user metadata fn returns copy
  discovery-provider/src/queries/get_feed_es.py
Labels: size/XS

#3108 [INF-81] Add install of GCP monitoring agent to new box
  service-commands/scripts/provision-dev-env.sh
Labels: size/S

#3105 [PAY-172] Add monitoring for reactions
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/health_check.py
  discovery-provider/src/tasks/index_reactions.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/M

#3110 Wrap StateMachine:updateReplicaSet() call in try-catch [Content Node]
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/M

#3107 AUD-1172 Add Lo-Fi Genre
  discovery-provider/src/tasks/index_trending.py
Labels: size/XS

#3112 Uppercase reaction notification type
  discovery-provider/src/queries/response_name_constants.py
Labels: size/XS

#3114 replace empty file removal log with decision tree stage [Content Node]
  creator-node/src/routes/files.js
Labels: size/XS

#3113 Add default logger + log boolean to CN asyncretry wrapper + renaming [Content Node]
  creator-node/package-lock.json
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/utils.js
  creator-node/test/utils.test.js
Labels: size/M

#3117 Upgrade to v0.3.58
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3115 Fix Solana global slot logic
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/S

#3116 [CON-149] Test more of snapback
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/snapbackSM/StateMachineConstants.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: size/XL

#3118 Group snapback tests into describe blocks
  creator-node/test/snapbackSM.test.js
Labels: size/L

#3119 Break selecting replica set out of issuing update
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: size/L

#3123 [CON-150] Break apart determineNewReplicaSet + cleanup
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: size/L

#3121 Fix redis chunk add use
  creator-node/src/blacklistManager.js
Labels: size/XS

#3125 Print errors while creating GCP instances
  service-commands/scripts/create-instance.sh
Labels: size/XS

#3126 Make contracts docker containers build only on master
  .circleci/config.yml
Labels: size/XS

#3129 Return number type for ids
  creator-node/src/components/contentBlacklist/contentBlacklistComponentService.js
Labels: size/XS

#3130 Add additional field to tip notification
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/response_name_constants.py
Labels: size/XS

#3131 Move contract and solana build CI steps to nightly workflow
  .circleci/config.yml
Labels: size/S

#3132 [INF-104] Upgrade to node 16 to fix build errors
  .circleci/config.yml
  contracts/Dockerfile
  eth-contracts/Dockerfile
Labels: size/M

#3135 Fix aggregate tip indexing bug
  discovery-provider/src/tasks/index_aggregate_tips.py
Labels: size/XS

#3133 Increase materialized view timeout to 6 hours
  discovery-provider/src/tasks/index_materialized_views.py
Labels: size/XS

#3127 Expose infrastructure stack env var in health check
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/config.js
  discovery-provider/default_config.ini
  discovery-provider/src/queries/get_health.py
Labels: size/S

#3137 Fix types
  libs/src/services/solanaAudiusData/index.ts
  libs/src/services/solanaWeb3Manager/utils.d.ts
Labels: size/M

#3134 [CON-145] Add cancel token and test coverage to getNodeUsers
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/snapbackSM/StateMachineConstants.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/test/peerSetManager.test.js
Labels: size/L

#3138 [PLAT-129] Only init contract if there is an address
  libs/src/services/contracts/ContractClient.ts
Labels: size/XS

#3136 Add string-based `level` keys to Bunyan logger
  creator-node/compose/env/commonEnv.sh
  creator-node/src/config.js
  creator-node/src/logging.js
Labels: size/S

#3143 Return wei string for supporting amount
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#3140 [PAY-120] Consume tipping notifications in Identity
  identity-service/compose/.env
  identity-service/sequelize/migrations/20220512172226-add_notification_json_b.js
  identity-service/src/models/solanaNotification.js
  identity-service/src/notifications/constants.js
  identity-service/src/notifications/processNotifications/index.js
  identity-service/src/notifications/processNotifications/reactionNotification.js
  identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
  identity-service/src/notifications/processNotifications/tipNotification.js
  identity-service/src/routes/notifications.js
Labels: size/L

#3144 [INF-93] Follow up code cleanliness for Bunyan changes
  creator-node/src/logging.js
Labels: size/XS

#3145 [PLAT-149] Enforce wallet fetch ordering in discovery auth_middleware
  discovery-provider/src/utils/auth_middleware.py
Labels: size/XS

#3146 Simplify CN child logger pattern
  creator-node/package-lock.json
  creator-node/src/apiHelpers.js
  creator-node/src/logging.js
Labels: size/M

#3139 [PLAT-146] Make health check respond when web3 is unhealthy
  discovery-provider/src/queries/get_health.py
Labels: size/M

#3142 Refactor snapback into monitoring queue
  creator-node/compose/env/base.env
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/config.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/cNodeToSpIdMapManager.js
  creator-node/src/services/stateMachineManager/constants.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/monitoring/StateMonitoringQueue.js
  creator-node/src/services/stateMachineManager/monitoring/processStateMonitoringJob.js
  creator-node/src/services/stateMachineManager/monitoring/utils.js
  creator-node/src/services/stateMachineManager/nodeHealthManager.js
  creator-node/src/services/stateMachineManager/reconciliation/StateReconciliationQueue.js
  creator-node/src/services/stateMachineManager/utils.js
  creator-node/test/StateMonitoringQueue.test.js
Labels: size/XXL

#3149 [CON-174] Use GH .gitignore template
  .gitignore
Labels: size/L

#3150 Standardize state machine manager naming and test it
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/monitoring/utils.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/StateMonitoringQueue.js
  creator-node/src/services/stateMachineManager/stateMonitoring/processStateMonitoringJob.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/StateReconciliationQueue.js
  creator-node/test/StateMonitoringQueue.test.js
  creator-node/test/processStateMonitoringJob.test.js
Labels: content-node, size/XXL

#3147 Add OAuth to libs (to be moved to SDK) C-353
  libs/src/index.js
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/services/oauth/Oauth.ts
  libs/src/services/oauth/index.ts
Labels: size/L

#3148 Add retries to transaction handler
  identity-service/src/routes/solana.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  service-commands/scripts/seed.js
  service-commands/src/commands/seed/SeedSession.js
  service-commands/src/utils/seed.js
Labels: size/L

#3158 Libs 1.2.117
  libs/package-lock.json
  libs/package.json
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/XS

#3159 Consume libs 1.2.117 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3163 [CON-177] Add new column is_available to tracks table
  discovery-provider/alembic/versions/5e17e0480ca7_add_is_available_column_to_track_table.py
  discovery-provider/src/models/models.py
Labels: size/M

#3164 Remove pg_indexes queries from monitors celery task
  discovery-provider/src/monitors/database.py
  discovery-provider/src/monitors/monitor_names.py
  discovery-provider/src/monitors/monitors.py
  discovery-provider/src/queries/get_health.py
Labels: size/M

#3162 Test stateMachineUtils and CNodeToSpIdMapManager
  creator-node/src/services/stateMachineManager/CNodeHealthManager.js
  creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/processStateMonitoringJob.js
  creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
  creator-node/test/CNodeToSpIdMapManager.test.js
  creator-node/test/StateMonitoringQueue.test.js
  creator-node/test/peerSetManager.test.js
  creator-node/test/processStateMonitoringJob.test.js
  creator-node/test/snapbackSM.test.js
  creator-node/test/stateMachineUtils.test.js
  creator-node/test/stateMonitoringUtils.test.js
Labels: content-node, size/L

#3161 Add check if download is none
  discovery-provider/src/queries/get_tracks.py
Labels: size/XS

#3093 Search on es
  discovery-provider/.test.env
  discovery-provider/compose/docker-compose.backend.yml
  discovery-provider/es-indexer/README.md
  discovery-provider/es-indexer/package.json
  discovery-provider/es-indexer/src/conn.ts
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/indexers/sharedIndexSettings.ts
  discovery-provider/es-indexer/src/main.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/es-indexer/src/types/docs.ts
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/tasks/test_es_indexer.py
  discovery-provider/scripts/search_quality.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/search.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/queries/search_queries.py
  discovery-provider/src/tasks/index_materialized_views.py
  discovery-provider/src/utils/elasticdsl.py
Labels: size/XXL

#3167 Add coverage for CNodeHealthManager
  creator-node/src/services/stateMachineManager/stateMonitoring/StateMonitoringQueue.js
  creator-node/test/CNodeHealthManager.test.js
  creator-node/test/StateMonitoringQueue.test.js
Labels: content-node, size/XL

#3171 Fix Solana Retry Bugs
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/S

#3172 Libs 1.2.118
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3169 Leave tags mat view on with search flag enabled
  discovery-provider/src/tasks/index_materialized_views.py
Labels: size/S

#3173 Consume Libs 1.2.118 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#3168 CON-180 Add code coverage CI reporting to CN
  .circleci/config.yml
  creator-node/README.md
  creator-node/package-lock.json
  creator-node/package.json
Labels: size/S

#3080 [C-406] Refactor AudiusContracts to typescript
  libs/data-contracts/signatureSchemas.ts
  libs/package-lock.json
  libs/package.json
  libs/src/index.js
  libs/src/services/contracts/ProviderSelection.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/dataContracts/IPLDBlacklistFactoryClient.js
  libs/src/services/dataContracts/IPLDBlacklistFactoryClient.ts
  libs/src/services/dataContracts/PlaylistFactoryClient.ts
  libs/src/services/dataContracts/RegistryClient.ts
  libs/src/services/dataContracts/SocialFeatureFactoryClient.ts
  libs/src/services/dataContracts/TrackFactoryClient.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/dataContracts/UserLibraryFactoryClient.ts
  libs/src/services/dataContracts/UserReplicaSetManagerClient.ts
  libs/src/services/dataContracts/index.ts
  libs/src/services/dataContracts/playlistFactoryClient.js
  libs/src/services/dataContracts/userLibraryFactoryClient.js
Labels: size/XXL

#3177 CON-180 Remove CI coverage status from READMEs
  creator-node/README.md
  eth-contracts/README.md
Labels: size/XS

#3179 Fix last_tx bug in Discovery index_solana_plays.py
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/XS
