Repository AudiusProject/apps, pull requests merged in 2022-01, with the labels that each got.

#2201 Switch discovery selection err to console.warn
  libs/src/services/discoveryProvider/index.js
Labels: size/XS

#2205 Remove diff before building docker tags, reverting to original behavior
  .circleci/config.yml
Labels: size/XS

#2206 [AUD-1150] [AUD-1152] Add additional Solana libs config
  libs/package-lock.json
  libs/package.json
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/S

#2131 Add OpenResty cache proxy in front of Content Node
  creator-node/Dockerfile
  creator-node/compose/docker-compose.yml
  creator-node/compose/env/base.env
  creator-node/compose/env/shellEnv1.sh
  creator-node/nginx_conf/nginx.conf
  creator-node/scripts/prod-server.sh
  creator-node/scripts/run-tests.sh
  creator-node/scripts/start.sh
  creator-node/src/config.js
  creator-node/src/index.ts
Labels: size/L

#2207 Libs 1.2.41
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2210 [AUD-1184] Properly pad attestation signatures
  libs/src/services/solanaWeb3Manager/rewards.js
Labels: size/XS

#2211 Bump libs to 1.2.42
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2212 Consume libs 1.2.42 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2198 Bring back some configs for vs code in discovery
  discovery-provider/.vscode/settings.json
Labels: size/XS

#2214 Set client upload max size to 1000mb (1gb)
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#2213 [AUD-1110] Add rewards config overrides for staging DN
  discovery-provider/default_config.ini
  discovery-provider/src/challenges/challenges.stage.json
  discovery-provider/src/challenges/create_new_challenges.py
Labels: size/M

#2179 [ASI-756] PR #1 - Add optional md5 fileshash to `/clock_status` and `/batch_clock_status` routes
  creator-node/src/apiSigning.js
  creator-node/src/dbManager.js
  creator-node/src/routes/users.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/users.test.js
Labels: size/XL

#2216 Disable client max body limit
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#2208 Retry getting blocks if no transactions
  discovery-provider/src/tasks/index.py
Labels: size/M

#2220 [AUD-1186] Add 404 safety check to discovery node selection
  libs/src/services/discoveryProvider/index.js
Labels: size/M

#2221 Libs v1.2.43
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2183 [ASI-756] PR #2 - Add logic to force secondary to resync all user state
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/components/replicaSet/syncQueueComponentService.js
  creator-node/src/dbManager.js
  creator-node/src/services/sync/processSync.js
  creator-node/src/services/sync/syncQueue.js
  creator-node/test/dbManager.test.js
  creator-node/test/nodesync.test.js
  creator-node/test/pollingTracks.test.js
Labels: size/XXL

#2225 Incrementing trackID
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
Labels: size/M

#2222 Remove resumable upload
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/routes/tracks.js
  libs/package.json
  libs/src/index.js
  libs/src/services/creatorNode/index.js
Labels: libs, content-node, size/L

#2227 Fix play metrics indexing on empty plays case
  discovery-provider/integration_tests/test_index_hourly_play_counts.py
  discovery-provider/src/tasks/index_hourly_play_counts.py
Labels: size/S

#2151 Identity wormhole
  identity-service/package.json
  identity-service/src/app.js
  identity-service/src/audiusLibsInstance.js
  identity-service/src/config.js
  identity-service/src/relay/ethTxRelay.js
  identity-service/src/routes/wormhole.js
  identity-service/src/utils/rewardsReporter.js
  libs/package-lock.json
  libs/package.json
  libs/src/api/account.js
  libs/src/constants.js
  libs/src/index.js
  libs/src/services/ethWeb3Manager/index.js
  libs/src/services/identity/index.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/wormhole/index.js
Labels: size/XL

#2228 Libs version patch v1.2.44
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2229 Bump identity libs version
  identity-service/package-lock.json
  identity-service/package.json
Labels: bug, identity-service, size/XS

#2232 [AUD-1206] Fix SolanaWeb3Manager getBalance method
  libs/src/services/solanaWeb3Manager/index.js
Labels: size/XS

#2233 Libs 1.2.45
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2230 [AUD-1186] Resolve DN divergence issue
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/src/tasks/index.py
Labels: size/M

#2234 Consume libs 1.2.45 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2223 Remove legacy track upload route
  creator-node/src/components/tracks/tracksComponentService.js
  creator-node/src/routes/tracks.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/tracks.test.js
  libs/src/index.js
  libs/src/services/creatorNode/index.js
Labels: libs, content-node, size/XL

#2235 Libs get sol wrapped audio check associated token acct
  libs/src/services/solanaWeb3Manager/index.js
Labels: libs, size/S

#2237 Bump libs 1.2.46
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2236 Add alembic revision - connect verified challenge
  discovery-provider/alembic/versions/132955202f03_update_connect_verified_challenge_.py
Labels: size/M

#2240 Add misc rewards fixes
  discovery-provider/src/challenges/create_new_challenges.py
  discovery-provider/src/tasks/index.py
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2241 Libs 1.2.47
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2242 Consume libs 1.2.47 in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2243 [AUD-1213] Fix identity notification processing
  identity-service/src/notifications/constants.js
  identity-service/src/notifications/processNotifications/challengeRewardNotification.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
  identity-service/test/index.js
  identity-service/test/processNotifications/challengeRewardNotification.js
Labels: bug, identity-service, size/M

#2200 Add installation of pre-commit
  service-commands/scripts/init-repos.sh
Labels: size/XS

#2239 Bump service commands libs usage to 1.2.46
  service-commands/package-lock.json
  service-commands/package.json
  service-commands/src/libs.js
  service-commands/src/utils/seed.js
Labels: libs, service-commands, size/S

#2251 Re-enable Rewards Preflight Checks
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
Labels: size/M

#2252 Libs 1.2.48
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2253 Consume libs 1.2.48 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2255 Fix libs waudio transfer method
  libs/src/services/solanaWeb3Manager/index.js
Labels: size/XS

#2256 Libs 1.2.49
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2257 Configure prod challenges
  discovery-provider/src/challenges/challenges.json
Labels: size/M

#2260 Update challenge tests to set start block for testing
  discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  discovery-provider/integration_tests/challenges/test_referral_challenge.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/utils.py
Labels: size/L

#2258 [AUD-1208] Add challenge reward amount to response
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/get_challenges.py
Labels: discovery-node, size/XS

#2261 Up worker connections + delete unused file
  creator-node/scripts/prod-server.sh
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#2215 Update indexes for SolanaNotifications and SolanaNotificationActions to have names
  identity-service/sequelize/migrations/20211223183608-add-solana-notification-indexes.js
Labels: size/M

#2262 Fix retroactive profile completion start block
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
Labels: size/S

#2171 Remove dead code
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#2265 Remove disbursements FK
  discovery-provider/alembic/versions/85680793a611_remove_disbursement_fk.py
Labels: discovery-node, size/M

#2271 Vg add ip check back
  creator-node/src/routes/healthCheck.js
Labels: size/S

#2264 Cleanup discovery log
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XS

#2270 Fix bad log
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: identity-service, size/XS

#2274 Remove build requirements for CircleCI
  .circleci/config.yml
Labels: size/S

#2263 Fix notifications route solana
  identity-service/src/routes/notifications.js
Labels: bug, identity-service, size/S

#2275 Fix OpenResty Redirect
  .circleci/config.yml
  discovery-provider/nginx_conf/config.lua
  discovery-provider/nginx_conf/main.lua
  discovery-provider/nginx_conf/nginx.conf
Labels: size/M

#2278 Add track check to isServable
  creator-node/src/blacklistManager.js
Labels: size/XS

#2283 Fix push notifs for identity challenges
  identity-service/src/notifications/sendNotifications/publishNotifications.js
  identity-service/test/sendNotifications/index.js
Labels: bug, identity-service, size/S

#2273 Add ip check back to content node
  creator-node/nginx_conf/nginx.conf
  creator-node/src/routes/healthCheck.js
Labels: content-node, size/S

#2287 Revert "[AUD-1186] Resolve DN divergence issue (#2230)"
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/src/tasks/index.py
Labels: size/M

#2288 Move migrations back into server.sh
  discovery-provider/scripts/dev-server.sh
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
Labels: size/S

#2284 Get Shareable URL for Cognito Flow
  identity-service/compose/.env
  identity-service/src/config.js
  identity-service/src/routes/cognito.js
  identity-service/src/utils/cognitoHelpers.js
Labels: identity-service, size/L

#2289 [AUD-1089] Update public gateways list
  libs/src/api/file.js
Labels: size/XS

#2281 Add additional rewards fixes to libs
  libs/src/api/account.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: libs, size/M

#2291 Libs 1.2.50
  libs/package-lock.json
  libs/package.json
Labels: libs, size/XS

#2290 [AUD-1255] Add redis startblock override
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/app.js
Labels: size/S

#2279 Set production rewards config
  discovery-provider/default_config.ini
  discovery-provider/src/utils/config.py
Labels: discovery-node, size/S

#2276 Add alembic version endpoint
  discovery-provider/src/queries/get_alembic_version.py
  discovery-provider/src/queries/health_check.py
Labels: size/M

#2226 [AUD-1136] - TrackFactory + ID, CLI, Lib consolidation
  solana-programs/anchor/audius-data/Anchor.toml
  solana-programs/anchor/audius-data/README.md
  solana-programs/anchor/audius-data/cli/README.md
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/utils.ts
  solana-programs/anchor/audius-data/tsconfig.json
  solana-programs/anchor/audius-data/yarn.lock
Labels: size/XXL

#2296 Pipe skipPreflight out to relay
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/transactionHandler.js
  libs/src/services/solanaWeb3Manager/transfer.js
  libs/src/services/solanaWeb3Manager/userBank.js
Labels: size/S

#2297 Libs 1.2.51
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2302 Bump version to v0.3.50
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2304 [AUD-1271] Handle skipPreflight in identity Solana relay
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/routes/solana.js
Labels: size/XS

#2305 Set connect-verified challenge to retroactive
  discovery-provider/src/challenges/challenges.json
Labels: discovery-node, size/XS

#2306 Remove extra param passed in to log setting fn
  creator-node/src/apiHelpers.js
Labels: size/XS

#2307 Remove log from serving file
  creator-node/src/routes/files.js
Labels: size/XS

#2292 Removing Duplicate code | Updating account.js
  libs/src/api/account.js
Labels: size/XS

#2298 [AUD-1170] Support uniquely owned discovery node selection
  libs/src/api/rewards.js
  libs/src/api/serviceProvider.js
  libs/src/index.js
  libs/src/service-selection/ServiceSelection.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
Labels: size/M

#2293 [AUD-1265] Make createUserBank to fire & forget
  libs/src/api/account.js
Labels: size/S

#2308 Libs 1.2.52
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2299 Log level cleanup to ease logger load
  creator-node/src/app.js
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/ipfs_lib.py
  discovery-provider/src/utils/redis_cache.py
Labels: size/S

#2310 Identity Notifs - Add log after DB TX commit
  identity-service/src/notifications/index.js
Labels: size/XS

#2313 bugfix
  creator-node/src/blacklistManager.js
Labels: size/S

#2314 Fix aggregate_plays on empty plays case
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
  discovery-provider/src/tasks/index_aggregate_plays.py
Labels: size/S

#2295 [ASI-794] Skip tx not block when missing refs
  discovery-provider/alembic/versions/f775fb87f5ff_add_skipped_transaction_level_column.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/utils/model_nullable_validator_unit_test.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/models.py
  discovery-provider/src/queries/skipped_transactions.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/indexing_errors.py
  discovery-provider/src/utils/model_nullable_validator.py
  discovery-provider/src/utils/track_event_constants.py
Labels: size/XXL

#2315 [Identity] Add logging & timeout to notification queue processing
  identity-service/src/notifications/index.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/notifications/pushAnnouncementNotifications.js
  identity-service/src/utils/racePromiseWithTimeout.js
Labels: size/M

#2317 Add ref to newly baked image and fix bake script
  service-commands/scripts/bake-dev-image.sh
  service-commands/scripts/utils.sh
Labels: size/XS

#2316 Rename trending challenges
  discovery-provider/alembic/versions/7104383ac0fe_drop_old_trending_challenges.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
  discovery-provider/src/challenges/trending_challenge.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/M

#2319 Update trending challenge revision
  discovery-provider/alembic/versions/7104383ac0fe_drop_old_trending_challenges.py
Labels: size/XS

#2272 Add AAO_DIR setting to remote box .profile
  service-commands/scripts/provision-dev-env.sh
Labels: size/XS

#2323 Raise MissingRequired error when no handle is found for a track
  discovery-provider/src/tasks/tracks.py
Labels: size/S

#2321 Identity rewards notifications feature flag
  identity-service/src/featureFlag.js
  identity-service/src/notifications/index.js
  identity-service/src/notifications/sendNotifications/index.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
  identity-service/src/routes/notifications.js
Labels: identity-service, size/M

#2318 [ASI-803] Identity notifs - minor logging nits
  identity-service/src/awsSNS.js
  identity-service/src/notifications/index.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/notifications/pushAnnouncementNotifications.js
  identity-service/src/webPush.js
Labels: size/M

#2324 Fix host
  identity-service/src/config.js
  identity-service/src/routes/recovery.js
Labels: size/S

#2244 Add playlist create, update, delete, and their tests
  solana-programs/anchor/audius-data/cli/README.md
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/XXL

#2326 Add service-commands and mad-dog alias to zshrc
  service-commands/scripts/.zshrc
Labels: size/XS

#2267 Update trending strategy to use all time play count
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/trending_strategies/ML51L_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py
Labels: size/M

#2327 [AUD-1300] Build trending notif consensus
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/notifications/trendingTrackProcessing.js
  identity-service/test/processNotifications/trendingTrackNotification.js
Labels: size/L

#2331 Filter deactivated accounts from the undisbursed endpoint
  discovery-provider/src/queries/get_undisbursed_challenges.py
Labels: discovery-node, size/XS

#2330 Bypass indexing skipped transactions
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#2332 [AUD-1309][AUD-1291] Improve Identity challenge attestation
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/S

#2334 Libs 1.2.53
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2224 Automatically reconnect if content node returns invalid auth token error
  libs/src/services/creatorNode/index.js
Labels: size/M

#2337 Bump libs version to v0.1.2.54
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2335 Consume libs 1.2.53 in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2341 Libs 1.2.55
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2342 Fix libs lint error
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/XS

#2344 Libs 1.2.56
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2345 Consume latest libs in identity
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/app.js
  identity-service/src/remoteConfig.js
Labels: size/XS

#2343 [AUD-73] Add country field to discovery health-check
  discovery-provider/default_config.ini
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/utils/config.py
Labels: size/XS

#2336 Set proxy read timeout to 1 hour
  creator-node/nginx_conf/nginx.conf
Labels: content-node, size/XS

#2328 Change prod-server log level to info
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
Labels: size/M

#2329 [AUD-1214] Implement User Follows in Anchor
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/XL

#2338 better manual control over linting and testing
  discovery-provider/scripts/lint.sh
  discovery-provider/scripts/test.sh
  service-commands/scripts/provision-dev-env.sh
Labels: size/M

#2350 Revert "Update trending strategy to use all time play count (#2267)"
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/trending_strategies/ML51L_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py
Labels: size/M

#2333 Remove skipping of disbursement on foreign user address / user challenge
  discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  discovery-provider/src/exceptions.py
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: discovery-node, size/M

#2353 Improve startBlock override for attester
  libs/src/services/discoveryProvider/index.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: libs, size/XS

#2354 Libs 1.2.57
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2195 Update get play metrics query to use hourly_play_counts
  discovery-provider/integration_tests/queries/test_get_plays_metrics.py
  discovery-provider/src/api/v1/metrics.py
  discovery-provider/src/queries/get_plays_metrics.py
Labels: size/L

#2185 Update user listen history query to use new indexed table
  discovery-provider/integration_tests/queries/test_get_history_for_user.py
  discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_track_history.py
  discovery-provider/src/queries/get_user_listening_history.py
  discovery-provider/src/queries/response_name_constants.py
Labels: size/L

#2355 [AUD-1339] Clear out old trending experiments, update default to ML51L
  discovery-provider/alembic/versions/a6d2e50a8efa_remove_old_trending.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/src/trending_strategies/ML51L_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/ePWJD_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/ePWJD_underground_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/L

#2349 [AUD-1251] Add protocol check on service registration
  libs/src/services/ethContracts/serviceProviderFactoryClient.js
  libs/src/utils/utils.js
  libs/tests/helpers.js
Labels: size/S

#2362 Add new trending strategy for all time scores
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/trending_strategies/EJ57D_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/EJ57D_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/EJ57D_underground_trending_tracks_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/L

#2363 [AUD-1347] - Enable Confirmation Timeout Config
  identity-service/package.json
  identity-service/src/audiusLibsInstance.js
  identity-service/src/config.js
  identity-service/src/routes/healthCheck.js
  identity-service/src/routes/trackListens.js
  identity-service/src/solana-client.js
  libs/src/index.js
Labels: size/M

#2367 [AUD-1348] Add verified referral challenge
  discovery-provider/integration_tests/challenges/test_referral_challenge.py
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/src/challenges/challenge.py
  discovery-provider/src/challenges/challenge_event_bus.py
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/referral_challenge.py
  discovery-provider/src/queries/get_challenges.py
Labels: size/L

#2366 [AUD-1345] Fix favorite playlist profile completion challenge
  discovery-provider/alembic/versions/8e4dda8255fd_fix_profile_completion_challenge_.py
  discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  discovery-provider/src/tasks/user_library.py
Labels: size/L

#2368 Override stage startblock for verified referrals
  discovery-provider/src/challenges/challenges.stage.json
Labels: size/XS

#2369 Remove .only in CN test suite + fix test
  creator-node/test/ensureStorageMiddleware.test.js
  creator-node/test/nodesync.test.js
Labels: size/XS

#2356 Update slack reporter
  identity-service/src/app.js
  identity-service/src/config.js
  identity-service/src/routes/wormhole.js
  identity-service/src/utils/rewardsReporter.js
Labels: identity-service, size/M

#2371 Libs 1.2.58
  libs/package.json
Labels: size/XS

#2374 Libs 1.2.59
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2375 Identity Service - Consuming libs 1.2.59
  identity-service/package.json
  package-lock.json
Labels: size/XS

#2377 Identity retry tx log
  identity-service/src/routes/trackListens.js
Labels: size/XS

#2364 Update proxy access log file with cache status
  creator-node/nginx_conf/nginx.conf
Labels: size/XS

#2348 Reward Emails
  identity-service/src/notifications/components/Body.jsx
  identity-service/src/notifications/components/notifications/Icons.jsx
  identity-service/src/notifications/components/notifications/Notification.jsx
  identity-service/src/notifications/fetchNotificationMetadata.js
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/notifications/renderEmail/Body.js
  identity-service/src/notifications/renderEmail/BodyStyles.js
  identity-service/src/notifications/renderEmail/Comment.js
  identity-service/src/notifications/renderEmail/FontStyles.js
  identity-service/src/notifications/renderEmail/Footer.js
  identity-service/src/notifications/renderEmail/Head.js
  identity-service/src/notifications/renderEmail/index.js
  identity-service/src/notifications/renderEmail/notifications/Icons.js
  identity-service/src/notifications/renderEmail/notifications/MultiUserHeader.js
  identity-service/src/notifications/renderEmail/notifications/Notification.js
  identity-service/src/notifications/renderEmail/notifications/NotificationBody.js
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/routes/notifications.js
  identity-service/test/emailNotifications/renderEmail.js
  identity-service/test/emailNotifications/renderedEmails/additionalChallengeEmail.html
  identity-service/test/emailNotifications/renderedEmails/challengeEmail.html
  identity-service/test/emailNotifications/renderedEmails/testEmail.html
  identity-service/test/index.js
  identity-service/test/sendNotifications/index.js
  identity-service/test/sendNotifications/mockNotifications/challengeReward.json
Labels: size/XXL

#2376 Add check in auth middleware
  creator-node/src/middlewares.js
Labels: size/S

#2380 [ASI-800] PR 2.5 - `/users/clock_status` route bugfixes
  creator-node/src/dbManager.js
  creator-node/src/routes/users.js
  creator-node/test/pollingTracks.test.js
Labels: size/L

#2381 Tests pass
  discovery-provider/src/tasks/index.py
  discovery-provider/src/utils/constants.py
Labels: size/M

#2339 Add migration idempotency test
  discovery-provider/integration_tests/test_migration_idempotency.py
Labels: size/L

#2382 Fix unlisted tracks in track upload challenge
  discovery-provider/integration_tests/challenges/test_track_upload_challenge.py
  discovery-provider/src/challenges/track_upload_challenge.py
Labels: size/M

#2269 ASI-792 Move aggregate_users to use indexing_checkpoints from redis checkpoint
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/queries/test_get_related_artists.py
  discovery-provider/integration_tests/queries/test_get_user_signals.py
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_user.py
  discovery-provider/integration_tests/tasks/test_index_related_artists.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/scripts/test.sh
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_aggregate_plays.py
  discovery-provider/src/tasks/index_aggregate_user.py
  discovery-provider/src/tasks/index_hourly_play_counts.py
  discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
  discovery-provider/src/utils/update_indexing_checkpoints.py
Labels: size/XL

#2142 Count RPS in OpenResty for redirects
  discovery-provider/nginx_conf/config.lua
  discovery-provider/nginx_conf/main.lua
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_redirect_weights.py
Labels: size/L

#2388 Identity logging - fixing NaN value log
  identity-service/src/awsSNS.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/webPush.js
Labels: size/XS

#2383 [AUD-1340] - TrackListens % of success vs failure
  identity-service/src/routes/trackListens.js
Labels: size/M

#2390 Bump version to v0.3.51
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2389 Listen streak override step count
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/src/challenges/challenge.py
  discovery-provider/src/challenges/listen_streak_challenge.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/queries/get_challenges.py
Labels: bug, discovery-node, size/L

#2391 [AUD-1338] Consolidate batch size for indexing across sol tasks
  discovery-provider/src/solana/constants.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#2384 [ASI-813] - Update filesystem monitors check
  creator-node/src/monitors/filesystem.js
  discovery-provider/src/monitors/filesystem.py
Labels: size/M

#2393 [AUD-1340] Fix redisExpiryKey mismatch
  identity-service/src/routes/trackListens.js
Labels: size/XS

#2254 Add test coverage and refactoring for discovery node indexing flow
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/constants.py
  discovery-provider/src/utils/indexing_errors.py
Labels: size/XL
