Repository AudiusProject/apps, pull requests merged in 2022-03, with the labels that each got.

#2614 Improve rewards logging and other fixes
  identity-service/src/routes/rewards.js
  identity-service/src/utils/configureAttester.js
  identity-service/src/utils/rewardsReporter.js
  libs/src/api/rewards.js
  libs/src/services/identity/index.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/L

#2620 Fix attestation reselection logic
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/M

#2636 Libs 1.2.87
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2632 faster top_users query
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/src/queries/get_top_users.py
Labels: size/M

#2637 Consume libs 1.2.87 in Identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2602 [ASI-890] CN getCID bugfixes [v2]
  creator-node/src/diskManager.js
  creator-node/src/routes/files.js
Labels: size/L

#2611 [ASI-894] Add verify user
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: solana, size/L

#2638 Cleanup user handle
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/follows.ts
Labels: solana, size/M

#2640 Lint and consistency in solana anchor lib
  solana-programs/anchor/audius-data/lib/lib.ts
Labels: size/M

#2581 [ASI-870] Only redirect v1 route
  discovery-provider/nginx_conf/main.lua
  discovery-provider/nginx_conf/nginx.conf
Labels: size/M

#2641 [ASI-910] Validate SECP message
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
Labels: size/L

#2642 Remove reduce to speed up notif processing
  discovery-provider/src/queries/notifications.py
Labels: size/S

#2644 [ASI-913] Add ESLint to anchor workspace
  solana-programs/anchor/audius-data/.eslintignore
  solana-programs/anchor/audius-data/.eslintrc.js
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/migrations/deploy.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tsconfig.json
  solana-programs/anchor/audius-data/yarn.lock
Labels: size/XXL

#2645 Update libs to 1.2.88
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2651 Bump version to v0.3.53
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2648 TNM
  eth-contracts/.solcover.js
  eth-contracts/contract-config.js
  eth-contracts/contracts/TrustedNotifierManager.sol
  eth-contracts/migrations/12_trusted_notifier_manager_migration.js
  eth-contracts/migrations/13_delegate_manager_v2_migration.js
  eth-contracts/package-lock.json
  eth-contracts/scripts/static_analysis.md
  eth-contracts/test/serviceProvider.test.js
  eth-contracts/test/trustedNotifierManager.test.js
  eth-contracts/utils/lib.js
  libs/eth-contracts/ABIs/TrustedNotifierManager.json
  libs/src/services/ethContracts/index.js
  libs/src/services/ethContracts/trustedNotifierManagerClient.js
  service-commands/src/commands/service-commands.json
Labels: size/XXL

#2654 Expose metrics from #2606 into Grafana
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: requires-special-attention, size/M

#2537 [AUD-1310] Move explore endpoints to /v1
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_top_followee_saves.py
  discovery-provider/src/queries/get_top_followee_windowed.py
  discovery-provider/src/queries/queries.py
Labels: size/L

#2655 fix prometheus metric name
  discovery-provider/src/tasks/index.py
Labels: size/S

#2657 Reduce high-cardinality Prometheus metric labels from flask routes
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XS

#2649 [AUD-1477] Support for user authority delegation (UpdateUser)
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/L

#2652 TN Final integration
  creator-node/src/app.js
  creator-node/src/components/contentBlacklist/contentBlacklistController.js
  creator-node/src/config.js
  creator-node/src/index.ts
  creator-node/src/routes/contact.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/TrustedNotifierManager.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/app.js
  creator-node/test/snapbackSM.test.js
  libs/initScripts/local.js
  service-commands/scripts/hosts.js
  service-commands/scripts/provision-dev-env.sh
  service-commands/src/commands/service-commands.json
  service-commands/src/setup.js
Labels: size/L

#2659 Bump libs to v1.2.89
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2661 Bump libs to 1.2.90
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2660 Bump content node to libs v1.2.89
  creator-node/package-lock.json
  creator-node/package.json
Labels: size/XS

#2662 further limit the amount of metrics generated
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XS

#2639 Add repost and save social actions for tracks and playlists
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
Labels: solana, size/XL

#2666 Use lowercase identity name
  identity-service/src/routes/cognito.js
Labels: size/S

#2663 Index spl audio
  discovery-provider/alembic/versions/58c87cf2c7e6_create_spl_token_transaction.py
  discovery-provider/integration_tests/tasks/test_index_spl_token.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/app.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/spl_token_transaction.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/queries/get_sol_rewards_manager.py
  discovery-provider/src/queries/get_sol_user_bank.py
  discovery-provider/src/queries/get_spl_audio.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/solana/solana_transaction_types.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/utils/redis_constants.py
  discovery-provider/src/utils/solana_indexing_logger.py
Labels: discovery-node, size/XXL

#2668 Fix relay
  identity-service/src/routes/solana.js
  identity-service/src/utils/relayHelpers.js
  identity-service/test/lib/instructionMocks.js
  identity-service/test/routes/solanaTest.js
Labels: size/L

#2669 transfer with override
  libs/src/services/solanaWeb3Manager/transfer.js
Labels: size/XS

#2670 Libs 1.2.91
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2664 Add created_at indexes for faster get_feed.
  discovery-provider/alembic/versions/ac0c6f94dd8d_partial_created_at_idx.py
Labels: size/L

#2671 Revert "Add created_at indexes for faster get_feed."
  discovery-provider/alembic/versions/ac0c6f94dd8d_partial_created_at_idx.py
Labels: size/L

#2673 partial indexes migration
  discovery-provider/alembic/versions/d321f0a00721_partial_indexes.py
Labels: size/L

#2578 [ASI-886] [Libs] Add retries to contract client init
  libs/src/services/contracts/ContractClient.js
  libs/tests/providerSelectionTest.js
Labels: size/M

#2674 Remove reduce to speed up notif processing (#2642)
  discovery-provider/src/queries/notifications.py
Labels: size/S

#2677 allow skipping recovery link generation for test purposes
  libs/src/api/account.js
Labels: size/XS

#2678 skip vacuum after updating search tables
  discovery-provider/src/tasks/index_materialized_views.py
Labels: size/S

#2653 [ASI-902] Add index_block_stats route for indexing information
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/index_block_stats.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/utils/index_blocks_performance.py
Labels: size/L

#2658 Replace all pickle with json
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/queries/get_unpopulated_playlists.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/get_unpopulated_users.py
  discovery-provider/src/tasks/cache_trending_playlists.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/redis_cache.py
  discovery-provider/src/utils/redis_cache_unit_test.py
Labels: size/L

#2679 bump libs
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2680 [ASI-919] Split lib functionality into multiple files
  solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/error.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
Labels: size/M

#2682 Remove tk
  identity-service/src/utils/relayHelpers.js
Labels: size/XS

#2686 Make docs unique
  identity-service/src/routes/cognito.js
Labels: size/S

#2685 capture flask http response codes
  discovery-provider/src/utils/redis_metrics.py
  service-commands/scripts/provision-dev-env.sh
Labels: size/S

#2687 [AUD-1690] Properly parse unpopulated tracks, users, playlists
  discovery-provider/src/queries/get_unpopulated_playlists.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/get_unpopulated_users.py
Labels: size/M

#2690 Add endpoint to return id signals
  identity-service/src/authMiddleware.js
  identity-service/src/routes/idSignals.js
  identity-service/src/userHandleMiddleware.js
Labels: size/M

#2675 Export "transfer rewards to Solana" script to enable automatic transfer
  libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
Labels: size/XS

#2693 accept different result types for @record_metrics
  discovery-provider/src/utils/redis_metrics.py
  service-commands/scripts/provision-dev-env.sh
Labels: size/S

#2672 [AUD-1618] Replace counts with usage of Aggregate tables in get_remixes_of query
  discovery-provider/src/queries/get_remixes_of.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/L

#2692 [ASI-852] Fix duplicate parallel track upload bug 🤦‍♂️
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/tracks.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
Labels: size/L

#2694 Add fp
  identity-service/sequelize/migrations/20220310212727-fingerprint.js
  identity-service/src/models/fingerprint.js
  identity-service/src/routes/fp.js
Labels: size/L

#2697 Include device user count in signals
  identity-service/src/routes/fp.js
  identity-service/src/routes/idSignals.js
  identity-service/src/utils/fpHelpers.js
Labels: size/L

#2701 Fix folder model again
  discovery-provider/src/api/v1/models/playlist_library.py
Labels: size/XS

#2699 extract status codes from werkzeug Responses
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XS

#2700 Share celery metrics via the web server
  .circleci/config.yml
  discovery-provider/scripts/start.sh
  discovery-provider/src/queries/prometheus_metrics_exporter.py
Labels: size/S

#2704 [AUD-1725] Add base rollup config to libs
  libs/.gitignore
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
Labels: size/M

#2696 Record IP
  identity-service/sequelize/migrations/20220311221027-add-user-ips.js
  identity-service/src/models/userIPs.js
  identity-service/src/routes/idSignals.js
Labels: size/L

#2702 [ASI-935] Update storage layer in Anchor
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
Labels: size/XL

#2715 Revert json changes in release branch
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/queries/get_unpopulated_playlists.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/get_unpopulated_users.py
  discovery-provider/src/tasks/cache_trending_playlists.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/redis_cache.py
  discovery-provider/src/utils/redis_cache_unit_test.py
Labels: size/L

#2714 Fix datetime caching
  discovery-provider/src/queries/get_unpopulated_playlists.py
  discovery-provider/src/queries/get_unpopulated_tracks.py
  discovery-provider/src/queries/get_unpopulated_users.py
  discovery-provider/src/utils/redis_cache.py
  discovery-provider/src/utils/redis_cache_unit_test.py
Labels: size/M

#2717 Remove content-service remnants
  diff.sh
  service-commands/src/commands/service-commands.json
Labels: size/S

#2716 [ASI-936] Remove playlist account and refactor lib
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
Labels: size/XXL

#2723 Bump version to v0.3.54
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2719 [PAY-89] Map OTHER needs response from AAO in libs
  identity-service/src/utils/rewardsReporter.js
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/XS

#2718 [ASI-960] Refactor social action
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
Labels: size/L

#2724 Fix scoping of scoped_session.
  discovery-provider/src/tasks/index.py
Labels: size/S

#2733 Use CommonJS export so that node can call this script from the commandline
  libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
Labels: size/XS

#2722 [AUD-1737] Fix wormhole compilation issue
  .circleci/config.yml
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
  libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
  libs/src/index.js
  libs/src/services/wormhole/index.js
  service-commands/scripts/init-repos.sh
Labels: size/M

#2705 [AUD-1726] Add typescript to libs
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
  libs/scripts/circleci-test.sh
  libs/src/services/solanaWeb3Manager/padBNToUint8Array.ts
  libs/src/services/solanaWeb3Manager/utils.js
  libs/tsconfig.json
  service-commands/scripts/init-repos.sh
  service-commands/src/commands/service-commands.json
Labels: size/L

#2730 [AUD-1748] replace standard with ts-standard
  libs/data-contracts/signatureSchemas.js
  libs/initScripts/configureLocalDiscProv.js
  libs/initScripts/helpers/claim.js
  libs/initScripts/helpers/distributeTokens.js
  libs/initScripts/helpers/spRegistration.js
  libs/initScripts/helpers/utils.js
  libs/initScripts/helpers/version.js
  libs/initScripts/local.js
  libs/initScripts/mainnet.js
  libs/initScripts/manageProdRelayerWallets.js
  libs/package-lock.json
  libs/package.json
  libs/scripts/addCIDToIpldBlacklist.js
  libs/scripts/circleci-test.sh
  libs/src/api/account.js
  libs/src/api/base.js
  libs/src/api/playlist.js
  libs/src/api/serviceProvider.js
  libs/src/api/track.js
  libs/src/api/user.js
  libs/src/index.js
  libs/src/service-selection/ServiceSelection.js
  libs/src/services/contracts/ContractClient.js
  libs/src/services/creatorNode/CreatorNodeSelection.js
  libs/src/services/creatorNode/CreatorNodeSelection.test.js
  libs/src/services/creatorNode/index.js
  libs/src/services/dataContracts/index.js
  libs/src/services/dataContracts/registryClient.js
  libs/src/services/dataContracts/userReplicaSetManagerClient.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
  libs/src/services/discoveryProvider/index.js
  libs/src/services/discoveryProvider/requests.js
  libs/src/services/ethContracts/claimsManagerClient.js
  libs/src/services/ethContracts/delegateManagerClient.js
  libs/src/services/ethContracts/governanceClient.js
  libs/src/services/ethContracts/index.js
  libs/src/services/ethContracts/serviceProviderFactoryClient.js
  libs/src/services/ethContracts/serviceTypeManagerClient.js
  libs/src/services/ethContracts/stakingProxyClient.js
  libs/src/services/ethWeb3Manager/index.js
  libs/src/services/hedgehog/index.js
  libs/src/services/identity/index.js
  libs/src/services/identity/requests.js
  libs/src/services/schemaValidator/index.js
  libs/src/services/solanaWeb3Manager/padBNToUint8Array.ts
  libs/src/services/solanaWeb3Manager/rewards.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
  libs/src/services/solanaWeb3Manager/transfer.js
  libs/src/services/solanaWeb3Manager/utils.js
  libs/src/services/web3Manager/index.js
  libs/src/services/wormhole/index.js
  libs/src/utils/apiSigning.js
  libs/src/utils/network.js
  libs/src/utils/network.test.js
  libs/src/utils/promiseFight.js
  libs/src/utils/signatures.js
  libs/src/utils/utils.js
Labels: size/XL

#2725 [AUD-1743] convert network to typescript
  libs/.eslintrc
  libs/package-lock.json
  libs/package.json
  libs/src/index.js
  libs/src/services/creatorNode/index.js
  libs/src/services/ethWeb3Manager/index.js
  libs/src/services/identity/index.js
  libs/src/utils/index.js
  libs/src/utils/multiProvider.ts
  libs/src/utils/network.test.ts
  libs/src/utils/network.ts
  libs/src/utils/promiseFight.js
  libs/src/utils/promiseFight.test.ts
  libs/src/utils/promiseFight.ts
  libs/src/utils/utils.d.ts
  libs/src/utils/utils.js
  libs/src/utils/uuid.ts
  libs/src/web3.d.ts
  service-commands/src/libs.js
Labels: size/L

#2737 Bump libs to v1.2.93
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2735 Fix create sender public
  libs/src/api/rewards.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/solanaWeb3Manager/rewards.js
Labels: size/M

#2739 Consume libs 1.2.93 in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2742 [ASI-965] Increase handle size
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/S

#2743 [ASI-943] Make discovery node unhealthy block diff configurable
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/serviceRegistry.js
  libs/src/index.js
  libs/src/services/discoveryProvider/index.js
Labels: size/S

#2745 [AUD-1763] Fix dev-mode with linked @audius/libs
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/start.sh
  creator-node/src/snapbackSM/snapbackSM.js
  identity-service/scripts/dev-server.sh
  service-commands/scripts/init-repos.sh
Labels: size/S

#2748 Link libs in CN by default
  creator-node/scripts/start.sh
Labels: size/XS

#2747 [CN] Change batch_clock_status requests to batches
  creator-node/src/snapbackSM/snapbackSM.js
Labels: size/L

#2749 Update fast provision with new bake
  service-commands/scripts/utils.sh
Labels: size/XS

#2734 Add app delegation account to audius data program
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/error.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/utils.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
Labels: size/L

#2708 Add solana ursm
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/programs/audius-data/Cargo.toml
  solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
Labels: size/XXL

#2746 Fix SocialHandles Sequelize comment
  identity-service/sequelize/migrations/20200615162622-add-personal-website-and-donation-link.js
Labels: size/XS

#2753 Add bn id to user and entity
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
Labels: size/L

#2709 Solana tx parser, naming stg -> storage, local automation, docs
  discovery-provider/solana-tx-parser/README.md
  discovery-provider/solana-tx-parser/account_parser.py
  discovery-provider/solana-tx-parser/call_instruction.py
  discovery-provider/solana-tx-parser/constants.py
  discovery-provider/solana-tx-parser/requirements.txt
  discovery-provider/solana-tx-parser/tx_parser.py
  discovery-provider/solana-tx-parser/utils.py
  service-commands/scripts/provision-dev-env.sh
  solana-programs/anchor/audius-data/.gitignore
  solana-programs/anchor/audius-data/README.md
  solana-programs/anchor/audius-data/cli/README.md
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/package.json
  solana-programs/anchor/audius-data/scripts/build-dev.sh
  solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh
  solana-programs/anchor/audius-data/scripts/parse-tx.sh
  solana-programs/anchor/audius-data/scripts/seed-tx.sh
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
Labels: size/XXL

#2711 Add isAvailable() for TranscodingQueue
  creator-node/src/TranscodingQueue.js
  creator-node/src/config.js
Labels: size/S

#2710 Use async_processing_status
  libs/src/services/creatorNode/index.js
Labels: size/XS

#2755 Bump libs to v1.2.94
  libs/package-lock.json
  libs/package.json
Labels: libs, size/XS

#2754 [ASI-962] Convert Solana track listen from hash to sorted set
  identity-service/scripts/run-tests.sh
  identity-service/src/routes/trackListens.js
  identity-service/test/authenticationTest.js
  identity-service/test/expressAppTest.js
  identity-service/test/index.js
  identity-service/test/lib/app.js
  identity-service/test/relayTest.js
  identity-service/test/routes/solanaTest.js
  identity-service/test/routes/trackListensTest.js
Labels: size/L

#2758 set PROMETHEUS_MULTIPROC_DIR for local tests
  discovery-provider/scripts/test.sh
Labels: size/XS

#2726 lower error to warning
  discovery-provider/src/tasks/index.py
Labels: size/XS

#2761 Add phase to attester, improve healthcheck
  identity-service/src/routes/healthCheck.js
  identity-service/src/utils/configureAttester.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.js
Labels: size/L

#2763 Libs 1.2.95
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2764 Consume libs 1.2.95
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#2732 [PAY-86] Assert correct authority in relay
  identity-service/src/routes/solana.js
  identity-service/src/utils/relayHelpers.js
  identity-service/test/lib/instructionMocks.js
  identity-service/test/routes/solanaTest.js
Labels: size/XXL

#2728 remove disused index_plays job
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_plays.py
Labels: size/L

#2762 Don't error on zero Solana listen submissions
  identity-service/src/routes/trackListens.js
  identity-service/test/routes/trackListensTest.js
Labels: size/S

#2770 Add blockdiff and blocknumber gauges for Prometheus
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/prometheus_metrics_exporter.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/M

#2771 missing get_health() argument
  discovery-provider/src/queries/get_health.py
Labels: size/XS

#2775 [AUD-1796] Fix wormhole compilation issue
  identity-service/package.json
  identity-service/src/audiusLibsInstance.js
  libs/src/services/wormhole/index.js
Labels: size/XS

#2777 Libs 1.2.96
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2773 Fix how PrometheusMetrics sets Gauge metrics
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/S

#2781 pin werkzeug
  discovery-provider/requirements.txt
Labels: size/XS

#2767 [ASI-956] Propagate delegation authority to remaining write functions
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/anchor/audius-data/lib/lib.ts
  solana-programs/anchor/audius-data/lib/utils.ts
  solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
  solana-programs/anchor/audius-data/programs/audius-data/src/utils.rs
  solana-programs/anchor/audius-data/tests/audius-data.ts
  solana-programs/anchor/audius-data/tests/follows.ts
  solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
  solana-programs/anchor/audius-data/tests/playlist.ts
  solana-programs/anchor/audius-data/tests/test-helpers.ts
  solana-programs/anchor/audius-data/tests/track-social-actions.ts
  solana-programs/anchor/audius-data/tests/ursm.ts
Labels: size/XXL

#2769 Use different copy/run commands w/labels to minimize intermediate image pruning
  .circleci/config.yml
  solana-programs/Dockerfile
Labels: size/S

#2756 Remove deprecated route /track_content_status
  creator-node/src/routes/files.js
Labels: content-node, size/XS

#2759 Update comments for Solana program instructions
  solana-programs/claimable-tokens/program/src/instruction.rs
  solana-programs/reward-manager/program/src/instruction.rs
Labels: size/S

#2752 Fix issue where cache active user led to errors, pin service-commands dep vsns
  libs/package-lock.json
  libs/package.json
  service-commands/.prettierrc.js
  service-commands/package.json
  service-commands/src/commands/seed/SeedSession.js
  service-commands/src/commands/seed/UserCache.js
Labels: size/L

#2751 Upgrade solana.py to 0.21.0, web3.py to 6.0.0b1
  .circleci/config.yml
  discovery-provider/.gitignore
  discovery-provider/.python-version
  discovery-provider/Dockerfile
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_trending.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/requirements.txt
  discovery-provider/scripts/circle-ci.sh
  discovery-provider/src/eth_indexing/event_scanner.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/solana/solana_client_manager_unit_test.py
  discovery-provider/src/tasks/cache_user_balance.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_blacklist.py
  discovery-provider/src/tasks/index_trending.py
Labels: size/L

#2782 add local directory cleaning for discovery-provider on down|restart
  service-commands/src/commands/service-commands.json
Labels: size/S

#2791 Bump version to v0.3.55
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#2736 [AUD-1755] Convert utils and service-selection to typescript
  libs/.eslintrc
  libs/package-lock.json
  libs/package.json
  libs/scripts/circleci-test.sh
  libs/scripts/test.sh
  libs/src/api/account.js
  libs/src/api/playlist.js
  libs/src/api/track.js
  libs/src/api/user.js
  libs/src/index.js
  libs/src/sanityChecks/rolloverNodes.js
  libs/src/service-selection/ServiceSelection.test.ts
  libs/src/service-selection/ServiceSelection.ts
  libs/src/service-selection/constants.js
  libs/src/service-selection/constants.ts
  libs/src/service-selection/index.js
  libs/src/service-selection/index.ts
  libs/src/services/ABIDecoder/index.js
  libs/src/services/contracts/ProviderSelection.js
  libs/src/services/creatorNode/CreatorNodeSelection.js
  libs/src/services/dataContracts/index.js
  libs/src/services/dataContracts/registryClient.js
  libs/src/services/dataContracts/userFactoryClient.js
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
  libs/src/services/discoveryProvider/index.js
  libs/src/services/ethContracts/claimsManagerClient.js
  libs/src/services/ethContracts/delegateManagerClient.js
  libs/src/services/ethContracts/governanceClient.js
  libs/src/services/ethContracts/index.js
  libs/src/services/ethContracts/registryClient.js
  libs/src/services/ethContracts/serviceProviderFactoryClient.js
  libs/src/services/ethContracts/serviceTypeManagerClient.js
  libs/src/services/solanaWeb3Manager/index.js
  libs/src/services/wormhole/index.js
  libs/src/utils/apiSigning.ts
  libs/src/utils/captcha.ts
  libs/src/utils/estimateGas.ts
  libs/src/utils/importContractABI.d.ts
  libs/src/utils/importContractABI.js
  libs/src/utils/index.js
  libs/src/utils/index.ts
  libs/src/utils/network.ts
  libs/src/utils/promiseFight.ts
  libs/src/utils/signatures.ts
  libs/src/utils/utils.d.ts
  libs/src/utils/utils.test.ts
  libs/src/utils/utils.ts
  libs/src/web3.d.ts
  libs/tests/playlistClientTest.js
  libs/tests/socialFeatureClientTest.js
  libs/tests/trackClientTest.js
  libs/tests/userClientTest.js
  libs/tsconfig.json
Labels: size/XL

#2772 [ASI-945] Remove most IPFS functionality from /ipfs routes
  creator-node/compose/env/base.env
  creator-node/default-config.json
  creator-node/scripts/run-tests.sh
  creator-node/src/RehydrateIpfsQueue.js
  creator-node/src/components/tracks/trackContentUploadManager.js
  creator-node/src/config.js
  creator-node/src/fileManager.js
  creator-node/src/ipfsAdd.js
  creator-node/src/logging.js
  creator-node/src/monitors/ipfs.js
  creator-node/src/resizeImage.js
  creator-node/src/routes/audiusUsers.js
  creator-node/src/routes/files.js
  creator-node/src/routes/tracks.js
  creator-node/src/utils.js
  creator-node/test/audiusUsers.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/fileManager.test.js
  creator-node/test/ipfsAdd.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/resizeImage.test.js
  creator-node/test/utils.test.js
  discovery-provider/src/queries/get_ipfs_peer_info.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/utils/helpers.py
Labels: requires-special-attention, size/XXL

#2796 Bump service-commands libs to v1.2.96
  service-commands/package-lock.json
  service-commands/package.json
Labels: size/XS

#2788 Anchor local deploy integration + Validator version upgrade
  service-commands/src/commands/service-commands.json
  solana-programs/anchor/audius-data/cli/main.ts
  solana-programs/start.sh
Labels: size/M

#2800 Fix changed utils import in libs
  libs/src/services/creatorNode/index.js
Labels: size/XS

#2802 fix alembic indexes
  discovery-provider/alembic/versions/37a4458bb72c_fix_alembic_indexes.py
Labels: size/M

#2803 Bump libs to v1.2.97
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#2794 [AUD-1754] Publish libs types
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
  libs/src/types.ts
  libs/src/utils/signatures.ts
Labels: size/S

#2768 [ASI-860] Enforce max wallet size in content-node batch_clock_status
  creator-node/compose/env/base.env
  creator-node/src/config.js
  creator-node/src/routes/users.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/pollingTracks.test.js
Labels: size/M
