Repository AudiusProject/apps, pull requests merged in 2022-06, with the labels that each got.

#3174 [CON-151] Refactor reconciliation queue
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMonitoring/StateMonitoringQueue.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/StateReconciliationQueue.js
  creator-node/src/services/stateMachineManager/stateReconciliation/handleSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/CNodeHealthManager.test.js
  creator-node/test/StateMonitoringQueue.test.js
  creator-node/test/monitorState.jobProcessor.test.js
Labels: content-node, size/XL

#3181 Fix snapback init error
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: bug, content-node, size/L

#3124 [INF-93] Remove rsyslog implementation and build Logspout sidecar container
  .circleci/config.yml
  creator-node/scripts/start.sh
  discovery-provider/compose/env/commonEnv.sh
  discovery-provider/default_config.ini
  discovery-provider/scripts/start.sh
  discovery-provider/src/utils/helpers.py
  logspout/.gitignore
  logspout/Dockerfile
  logspout/README.md
  logspout/build.sh
  logspout/modules.go
  logspout/start.sh
Labels: size/L

#3183 Remove default value from discoveryProviderWhitelist in creator-node
  creator-node/default-config.json
Labels: size/XS

#3185 Use logglyTags for CN nodes (logspout)
  logspout/start.sh
Labels: size/XS

#3187 Set service key to k8s when not present
  discovery-provider/src/utils/helpers.py
Labels: size/XS

#3186 Flake8 Plugin: Fix multiple route parameter detection
  discovery-provider/flake8_plugins/flask_decorator_plugin/visitor_helpers.py
Labels: bug, discovery-node, size/XS

#3184 Notification Fixes
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/response_name_constants.py
  identity-service/src/routes/notifications.js
Labels: size/M

#3188 [PAY-272] Add API routes for individual user supporter/supporting
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_support_for_user.py
Labels: discovery-node, size/L

#3176 Bump version to v0.3.59
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3193 Fix reactions endpoint for multiple reactions
  discovery-provider/src/api/v1/reactions.py
  discovery-provider/src/queries/reactions.py
Labels: size/S

#3199 Move alembic migrations
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
Labels: size/S

#3201 Fix reactions endpoint 404 case
  discovery-provider/src/api/v1/reactions.py
  discovery-provider/src/queries/reactions.py
Labels: size/S

#3202 [PAY-297] Change reaction notification handling on Identity
  identity-service/src/notifications/processNotifications/reactionNotification.js
  identity-service/src/routes/notifications.js
Labels: size/S

#3204 Disable download app email
  identity-service/src/notifications/index.js
Labels: size/XS

#3205 Add unsubscribe link to welcomeDownload.html
  identity-service/src/notifications/emails/downloadMobileApp.html
  identity-service/src/notifications/emails/recovery.html
  identity-service/src/notifications/emails/welcome.html
  identity-service/src/notifications/emails/welcomeDownload.html
Labels: size/S

#3206 Comment out coveralls upload from content-node tests
  .circleci/config.yml
Labels: size/XS

#3203 Fix reaction lint
  discovery-provider/src/queries/reactions.py
Labels: size/XS

#3128 [CON-112] Add worker to check if track is available
  discovery-provider/integration_tests/tasks/test_update_track_is_available.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/utils/redis_constants.py
Labels: discovery-node, size/XL

#3209 Remove /etc/hosts modification
  service-commands/scripts/setup-instance.sh
  service-commands/scripts/utils.sh
Labels: size/S

#3212 Improve GH pull request template readability/usability
  .github/pull_request_template.md
Labels: size/S

#3219 Support notif for track added to playlist
  discovery-provider/src/models/models.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/response_name_constants.py
Labels: size/M

#3211 use duration, not runtime, keyword for Prometheus metrics
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/users.py
Labels: size/S

#3216 Add is_available field to tracks api resp
  discovery-provider/src/api/v1/models/tracks.py
Labels: discovery-node, size/XS

#3221 Extend ES indexer test
  discovery-provider/integration_tests/tasks/test_es_indexer.py
Labels: size/S

#3214 Set update track is available cadence to every 12 hours
  discovery-provider/src/app.py
  discovery-provider/src/tasks/update_track_is_available.py
Labels: discovery-node, size/XS

#3200 [CON-151] Refactor the rest of state machine
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/QueueInterfacer.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeCompletedJobEnqueueOtherJobs.js
  creator-node/src/services/stateMachineManager/processJob.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/StateMonitoringQueue.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/SecondarySyncHealthTracker.js
  creator-node/src/services/stateMachineManager/stateReconciliation/StateReconciliationQueue.js
  creator-node/src/services/stateMachineManager/stateReconciliation/SyncRequestDeDuplicator.js
  creator-node/src/services/stateMachineManager/stateReconciliation/handleSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/StateMonitoringQueue.test.js
  creator-node/test/monitorState.jobProcessor.test.js
Labels: content-node, size/XXL

#3224 Make exclusive try/except blocks for fetching ts
  discovery-provider/src/queries/get_health.py
Labels: discovery-node, size/S

#3215 migration to undo partial and temporary indexes
  discovery-provider/alembic/versions/88daa6a4f269_index_repair.py
Labels: size/L

#3226 update to new dashboards
  monitoring/grafana/dashboards/discovery-provider.json
  monitoring/grafana/dashboards/load-test.json
Labels: size/M

#3218 [INF-119] faster `Building web server` step for creator node
  creator-node/Dockerfile
  creator-node/scripts/up.sh
  creator-node/scripts/wait
  service-commands/src/commands/service-commands.json
Labels: size/L

#3217 [INF-87] faster `Building web server` step for discovery provider
  discovery-provider/.dockerignore
  discovery-provider/Dockerfile
  discovery-provider/scripts/init-db.sh
  discovery-provider/scripts/openresty_log_convertor.py
  discovery-provider/scripts/search_quality.py
  discovery-provider/scripts/seed.py
  discovery-provider/scripts/up.sh
  discovery-provider/scripts/wait
  service-commands/src/commands/service-commands.json
Labels: size/L

#3223 CON-200 Make snapbackMaxLastSuccessfulRunDelayMs configurable
  creator-node/compose/env/base.env
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/config.js
Labels: size/S

#3180 es-indexer cleanup
  discovery-provider/es-indexer/README.md
  discovery-provider/es-indexer/nuke.ts
  discovery-provider/es-indexer/package-lock.json
  discovery-provider/es-indexer/package.json
  discovery-provider/es-indexer/scripts/nuke.ts
  discovery-provider/es-indexer/scripts/sql-ts.ts
  discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
  discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/main.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/es-indexer/src/types/docs.ts
  discovery-provider/integration_tests/tasks/test_es_indexer.py
  discovery-provider/scripts/dev-server.sh
  discovery-provider/scripts/prod-server.sh
  discovery-provider/scripts/start.sh
Labels: size/XXL

#3190 Add location to plays
  discovery-provider/alembic/versions/cdf1f6197fc6_add_play_geolocation.py
  discovery-provider/src/models/models.py
  discovery-provider/src/tasks/index_solana_plays.py
  identity-service/compose/.env
  identity-service/default-config.json
  identity-service/src/config.js
  identity-service/src/routes/trackListens.js
  identity-service/src/solana-client.js
Labels: size/L

#3232 Fix geolocation play migration conflict
  discovery-provider/alembic/versions/cdf1f6197fc6_add_play_geolocation.py
Labels: size/XS

#3235 INF-128 Remove on-hold jobs from main ci workflow to get dat ✅
  .circleci/config.yml
Labels: size/M

#3229 update monitoring dir README
  monitoring/README.md
  monitoring/docker-compose.yml
Labels: size/M

#3228 [INF-122] Track metrics for dp4
  monitoring/README.md
  monitoring/deploy.sh
  monitoring/docker-compose.yml
  monitoring/prometheus/generate-prom.js
Labels: size/M

#3220 CON-180 Re-enable coveralls on content node
  .circleci/config.yml
Labels: size/XS

#3241 [CON-148] Test monitoring queue and processJob
  creator-node/src/services/stateMachineManager/makeCompletedJobEnqueueOtherJobs.js
  creator-node/src/services/stateMachineManager/processJob.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/StateMonitoringQueue.test.js
  creator-node/test/processJob.test.js
Labels: content-node, size/XL

#3239 [INF-122] Export search queries metrics to Prometheus
  discovery-provider/src/api/v1/search.py
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XS

#3240 Ci node modules fix
  discovery-provider/Dockerfile
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/scripts/start.sh
  discovery-provider/scripts/test.sh
  discovery-provider/scripts/up.sh
Labels: size/M

#3245 don't move node_modules pre-build
  .circleci/config.yml
  discovery-provider/scripts/start.sh
  discovery-provider/scripts/up.sh
Labels: size/M

#3166 CON-181 Add prometheus metrics to CN
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/monitors/filesystem.js
  creator-node/src/routes/prometheusMetricsRoutes.js
  creator-node/src/routes/tracks.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/README.md
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/prometheusMonitoring/prometheusRegistry.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/app.js
  creator-node/test/prometheus.test.js
Labels: size/L

#3250 Skip fetching all CIDs for all tracks
  creator-node/src/blacklistManager.js
  creator-node/test/contentBlacklist.test.js
Labels: size/M

#3253 [PAY-167][PAY-196] Add submitReaction function to libs and corresponding function in the identity service
  identity-service/src/routes/reactions.js
  libs/src/api/base.d.ts
  libs/src/api/reactions.ts
  libs/src/libs.js
  libs/src/services/identity/IdentityService.ts
Labels: size/M

#3255 [PAY-256] Fix back to back tip nonce error
  libs/src/services/solanaWeb3Manager/transfer.js
Labels: size/XS

#3258 Bump libs
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3259 Add xmlhttprequest dependency
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3262 Bump libs
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3244 Fix identity feature flag for location
  discovery-provider/src/tasks/index_solana_plays.py
  identity-service/src/solana-client.js
Labels: size/S

#3257 Test monitorState and findSyncRequests job processors
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/processJob.test.js
Labels: content-node, size/XL

#3263 Fix v1 search APIs on elasticsearch
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#3264 Bump to version 0.3.60
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3266 Get local CN working
  monitoring/prometheus/generate-prom.js
Labels: size/M

#3261 [CON-214] - Removing clearing BL on init
  creator-node/src/blacklistManager.js
  creator-node/src/redis.js
  creator-node/test/blacklistManager.test.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/blacklistManager.js
Labels: content-node, size/L

#3233 Is abusive column
  identity-service/sequelize/migrations/20220610002940-add-is-abusive.js
  identity-service/src/featureFlag.js
  identity-service/src/models/user.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
  identity-service/src/routes/relay.js
  identity-service/src/utils/antiAbuse.js
  service-commands/scripts/hosts.js
Labels: size/L

#3237 [CON-147] Create Network Monitoring project in protocol repo
  discovery-provider/plugins/network-monitoring/.dockerignore
  discovery-provider/plugins/network-monitoring/.gitignore
  discovery-provider/plugins/network-monitoring/Dockerfile
  discovery-provider/plugins/network-monitoring/README.md
  discovery-provider/plugins/network-monitoring/assets/NetworkMonitoring.png
  discovery-provider/plugins/network-monitoring/assets/network_monitoring_er_diagram.png
  discovery-provider/plugins/network-monitoring/docker-compose.yaml
  discovery-provider/plugins/network-monitoring/grafana/Dockerfile
  discovery-provider/plugins/network-monitoring/grafana/bin/create-data-sources.sh
  discovery-provider/plugins/network-monitoring/grafana/bin/save-dashboards.sh
  discovery-provider/plugins/network-monitoring/grafana/bin/upload-dashboards.sh
  discovery-provider/plugins/network-monitoring/network-monitoring-cron
  discovery-provider/plugins/network-monitoring/new_job.sh
  discovery-provider/plugins/network-monitoring/package-lock.json
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/prometheus/.env.prod
  discovery-provider/plugins/network-monitoring/prometheus/.env.stage
  discovery-provider/plugins/network-monitoring/prometheus/.gitignore
  discovery-provider/plugins/network-monitoring/prometheus/config/prometheus.yml
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/db/config/config.json
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_foreign_connection.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_tables.ts
  discovery-provider/plugins/network-monitoring/src/db/models/cid_from_cn.ts
  discovery-provider/plugins/network-monitoring/src/db/models/cid_from_dn.ts
  discovery-provider/plugins/network-monitoring/src/db/models/content_node.ts
  discovery-provider/plugins/network-monitoring/src/db/models/index_block.ts
  discovery-provider/plugins/network-monitoring/src/db/models/user.ts
  discovery-provider/plugins/network-monitoring/src/db/sql/README.md
  discovery-provider/plugins/network-monitoring/src/db/sql/create_tables.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/foreign_connection.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/import_schema.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/new_run.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/discovery/index.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
  discovery-provider/plugins/network-monitoring/tsconfig.json
Labels: discovery-node, size/XXL

#3265 fix test.sh and Dockerfile
  discovery-provider/Dockerfile
  discovery-provider/compose/.test.env
  discovery-provider/scripts/test.sh
  discovery-provider/scripts/up.sh
Labels: size/S

#3272 Move prometheus setup-node script into monitoring/ from load-test-tools
  monitoring/bin/setup-node
Labels: size/M

#3281 [CON-203] Test reconciliation manager + issueSyncRequest job processor
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: content-node, size/XL

#3234 Simple data layer contract
  contracts/contracts/AudiusData.sol
  contracts/signature_schemas/signatureSchemas.js
  contracts/test/_lib/artifacts.js
  contracts/test/audiusData.js
Labels: size/L

#3270 Remove watchtower
  creator-node/scripts/start.sh
Labels: size/XS

#3268 [CON-203] Test findReplicaSetUpdates job processor
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
Labels: content-node, size/L

#3273 Update aggregate play
  discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
  discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/app.py
  discovery-provider/src/models/__init__.py
  discovery-provider/src/models/milestone.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/aggregates/index_aggregate_plays.py
  discovery-provider/src/tasks/index_listen_count_milestones.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/utils/redis_constants.py
Labels: discovery-node, size/XL

#3284 [PLAT-181] Sort by transactionIndex instead of hash
  discovery-provider/default_config.ini
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/sort_block_transactions.py
  discovery-provider/src/tasks/sort_block_transactions_unit_test.py
Labels: size/M

#3286 Fix play trigger name
  discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py
Labels: size/XS

#3289 Fix aggregate play test for trigger
  discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
Labels: size/M

#3288 Fix caching of latest play when indexing plays
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/S

#3276 triggers: aggregate_user, aggregate_track, aggregate_playlist
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/trigger_sql/handle_user.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_playlist.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_playlist_down.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_track.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_user.sql
  discovery-provider/alembic/trigger_sql/migrate_album_playlist_lexeme_dict.sql
  discovery-provider/alembic/versions/d615bdcc0e56_agg_triggers.py
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/integration_tests/queries/test_get_related_artists.py
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/queries/test_get_user_signals.py
  discovery-provider/integration_tests/queries/test_populate_playlist_metadata.py
  discovery-provider/integration_tests/queries/test_populate_track_metadata.py
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_es_indexer.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_track.py
  discovery-provider/integration_tests/tasks/test_index_aggregate_user.py
  discovery-provider/integration_tests/tasks/test_index_related_artists.py
  discovery-provider/integration_tests/tasks/test_update_trending.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/aggregates/index_aggregate_track.py
  discovery-provider/src/tasks/index_aggregate_user.py
  discovery-provider/src/tasks/index_aggregate_views.py
Labels: size/XXL

#3283 Fix miscellaneous state machine bugs
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
Labels: content-node, size/L

#3231 [CON-215] - Make bl init asynchronous but exit if err
  creator-node/src/blacklistManager.js
  creator-node/src/index.ts
  creator-node/src/serviceRegistry.js
Labels: content-node, size/M

#3290 [CON-207] Add network monitoring as a prometheus target
  discovery-provider/plugins/network-monitoring/Dockerfile.test
  discovery-provider/plugins/network-monitoring/docker-compose.yaml
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
  monitoring/prometheus/ymls/local.yml
  monitoring/prometheus/ymls/prod.yml
  monitoring/prometheus/ymls/stage.yml
Labels: size/L

#3294 Fix updateReplicaSet, add a few tests, and improve dashboard truncation
  creator-node/src/serviceRegistry.js
  creator-node/src/services/stateMachineManager/makeCompletedJobEnqueueOtherJobs.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
  creator-node/test/StateReconciliationManager.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
Labels: content-node, size/XL

#3295 [PLAT-196] Simple data migration
  contracts/migrations/5_audius_data_migration.js
Labels: size/M

#3291 [PAY-299] Add Tipping Push Notifications
  identity-service/src/featureFlag.js
  identity-service/src/notifications/fetchNotificationMetadata.js
  identity-service/src/notifications/formatNotificationMetadata.js
  identity-service/src/notifications/processNotifications/utils.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
  identity-service/src/notifications/sendNotifications/index.js
  identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: size/L

#3298 Fix Solana Notification generation cutoff
  discovery-provider/src/queries/notifications.py
Labels: size/S

#3287 [CON-213] - Paginate delist adding and small refactor
  creator-node/src/blacklistManager.js
  creator-node/test/contentBlacklist.test.js
  creator-node/test/lib/blacklistManager.js
Labels: content-node, size/L

#3304 Network Monitoring Staging Refactor
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_foreign_connection.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
  monitoring/prometheus/ymls/stage.yml
Labels: size/M

#3306 [PAY-370] Dedupe reaction notifications
  identity-service/src/notifications/processNotifications/reactionNotification.js
Labels: size/M

#3292 [CON-224] - Re-enable nginx cache
  creator-node/compose/docker-compose.yml
  creator-node/compose/env/shellEnv1.sh
  creator-node/nginx_conf/nginx.conf
  creator-node/scripts/start.sh
  creator-node/src/config.js
  creator-node/src/index.ts
Labels: content-node, size/S

#3269 [PLAT-112] Add playlists metadata upload route and test
  creator-node/sequelize/migrations/20220427014326-create-playlist-table-and-clock-record-type.js
  creator-node/src/models/clockRecord.js
  creator-node/src/models/playlist.js
  creator-node/src/routes/playlists.js
  creator-node/src/utils/index.js
  creator-node/test/lib/libsMock.js
  creator-node/test/playlists.test.js
  service-commands/scripts/A
Labels: size/XL

#3300 Get milestones updated in discovery
  discovery-provider/integration_tests/queries/test_get_milestones.py
  discovery-provider/src/models/milestone.py
  discovery-provider/src/queries/notifications.py
Labels: size/L

#3307 INF-139 saving newest dashboards
  monitoring/grafana/dashboards/audius-boilerplate.json
  monitoring/grafana/dashboards/audius-internal-health.json
  monitoring/grafana/dashboards/discovery-provider.json
  monitoring/grafana/dashboards/general-alerting.json
  monitoring/grafana/dashboards/load-test.json
  monitoring/grafana/dashboards/network-monitoring.json
Labels: size/XL

#3303 Add bash to identity service
  identity-service/Dockerfile
Labels: size/XS

#3311 Network Monitoring DB Timeout Fix
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
Labels: javascript, size/M

#3312 Convert JSON secrets to env var
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
Labels: size/M

#3314 Revert "identity milestones update (#3301)"
  identity-service/src/notifications/index.js
  identity-service/src/notifications/milestoneProcessing.js
  identity-service/test/index.js
  identity-service/test/processNotifications/milestoneProcessing.js
Labels: size/L

#3309 [CON-152] Allow state machine jobs to record metrics
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/prometheus.constants.js
  creator-node/src/services/prometheusMonitoring/prometheusUtils.js
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeCompletedJobEnqueueOtherJobs.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
Labels: content-node, size/XL

#3318 @audius/sdk v0.0.5
  libs/README.md
  libs/package.json
Labels: size/XS

#3308 INF-139 Update README with additional information for panel creation
  monitoring/.gitignore
  monitoring/README.md
  monitoring/grafana/bin/create-data-sources.sh
  monitoring/grafana/bin/save-dashboards.sh
  monitoring/grafana/bin/upload-dashboards.sh
Labels: size/L

#3302 tag search on elasticsearch
  discovery-provider/es-indexer/src/helpers/splitTags.ts
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/indexers/sharedIndexSettings.ts
  discovery-provider/es-indexer/src/types/docs.ts
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/queries/search_queries.py
  discovery-provider/src/tasks/index_materialized_views.py
  discovery-provider/src/utils/elasticdsl.py
Labels: size/L

#3317 Disable snapback, enable refactored state machine
  creator-node/compose/env/base.env
  creator-node/default-config.json
  creator-node/src/config.js
  creator-node/test/StateMonitoringManager.test.js
Labels: content-node, size/S

#3319 update trending lock timeout to 24h
  discovery-provider/src/tasks/index_trending.py
Labels: size/XS

#3320 Dont need to .length a length
  creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
Labels: size/XS

#3321 [CON-195] Update health check for new queues
  creator-node/compose/env/base.env
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/config.js
  creator-node/src/monitors/monitors.js
  creator-node/src/monitors/stateMachine.js
  creator-node/src/services/stateMachineManager/processJob.js
  creator-node/test/processJob.test.js
Labels: content-node, size/L

#3325 Update timestamp for weekly email users and fix typo
  identity-service/src/notifications/sendNotificationEmails.js
Labels: size/XS

#3323 [CON-230] - Bump nginx cache ttl
  creator-node/nginx_conf/nginx.conf
Labels: size/S

#3322 [CON-229] - Fix content caching
  creator-node/src/routes/files.js
Labels: size/S

#3086 Start remote-dev with a clean `git status`
  .circleci/config.yml
Labels: size/XS

#3331 Bump libs and @types/async-retry
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3332 Disable recurring sync processing in snapback
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/test/snapbackSM.test.js
Labels: content-node, size/S

#3335 Change Network Monitoring prod prometheus target
  monitoring/prometheus/ymls/prod.yml
Labels: size/XS

#3336 Re-install `xmlhttprequest` dep in @audius/sdk
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3339 Bump to v0.3.61
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#3338 Update network monitoring prometheus targets to use DNS instead of IP
  monitoring/prometheus/ymls/prod.yml
  monitoring/prometheus/ymls/stage.yml
Labels: size/S

#3341 Kill running queries before migration
  discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py
Labels: size/XS

#3342 Increase discovery db conn pool for local env from 20 to 200
  discovery-provider/default_config.ini
Labels: size/XS

#3344 Revert "Increase discovery db conn pool for local env from 20 to 200 (3342)"
  discovery-provider/default_config.ini
Labels: size/XS

#3346 add sqlalchemy text call
  discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py
Labels: size/XS

#3347 SDK 0.0.9
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3348 Enable stateMonitoring by default on local env
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
Labels: size/XS

#3349 Fix streaming via /ipfs/<cid> and /content/<cid>
  creator-node/src/routes/files.js
Labels: size/M

#3350 Fetch CN spID config after it has been set
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
Labels: size/XS

#3353 top playlists endpoint
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_top_playlists.py
Labels: size/M

#3358 Remove redundant header setting/unsetting
  creator-node/src/routes/files.js
Labels: content-node, size/XS

#3360 [C-467] Return full service response
  libs/src/utils/network.ts
Labels: size/S

#3361 SDK 0.0.10
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#3362 [PAY-401] Fix Solana Node registration script
  identity-service/src/solanaNodeRegistration.js
  libs/src/api/rewards.js
  libs/src/api/serviceProvider.js
  libs/src/services/solanaWeb3Manager/rewardsAttester.ts
  libs/tests/rewardsAttesterTest.js
Labels: size/L
