Repository AudiusProject/apps, pull requests merged in 2022-12, with the labels that each got.

#4412 Add profile backfill job
  discovery-provider/integration_tests/tasks/test_index_profile_challenge_backfill.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/health_check.py
  discovery-provider/src/tasks/index_profile_challenge_backfill.py
Labels: size/L

#4413 Remove unused sync env vars
  creator-node/src/config.js
Labels: size/S

#4414 Fix audius compose test readme
  discovery-provider/README.md
Labels: size/XS

#4415 Upgrade CN ioredis and redis to v6.2.7
  .circleci/config.yml
  creator-node/Dockerfile
  creator-node/compose/docker-compose.yml
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/tracer.ts
Labels: content-node, size/M

#4404 [CON-506] Migrate files with custom storage paths
  creator-node/src/config.js
  creator-node/src/dbManager.js
  creator-node/src/diskManager.ts
  creator-node/src/index.ts
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
Labels: content-node, size/L

#4417 Update import for computing legacy CIDs
  creator-node/src/routes/files.js
  creator-node/src/utils/index.ts
Labels: content-node, size/S

#4418 Fix CN mkdir called on grandparent instead of parent
  creator-node/src/utils/fsUtils.ts
Labels: content-node, size/XS

#4419 Fix tiktok auth
  identity-service/src/routes/tiktok.js
Labels: size/XS

#4421 Update README.md
  mad-dog/README.md
Labels: size/XS

#4423 Update storagePaths for failed blacklisted CIDs
  creator-node/src/dbManager.js
  creator-node/src/diskManager.ts
Labels: content-node, size/M

#4422 Add notification seen table
  discovery-provider/alembic/versions/21e5635c83a9_create_notification_seen.py
  discovery-provider/integration_tests/notifications/test_challenge_disbursement.py
  discovery-provider/integration_tests/notifications/test_follow.py
  discovery-provider/integration_tests/notifications/test_play_milestone.py
  discovery-provider/integration_tests/notifications/test_playlist.py
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/integration_tests/notifications/test_repost.py
  discovery-provider/integration_tests/notifications/test_save.py
  discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
  discovery-provider/integration_tests/notifications/test_track.py
  discovery-provider/integration_tests/notifications/test_user_tip.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_notification.py
  discovery-provider/src/models/notifications/notification.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/notification_seen.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#4425 Narrow pagination windows for storagePath migrations
  creator-node/src/dbManager.js
  creator-node/src/diskManager.ts
Labels: content-node, size/L

#4428 Fix latest track default args
  discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#4426 Fix identity redis rate limit error and improve logging
  identity-service/src/app.js
  identity-service/src/rateLimiter.js
  identity-service/src/redis.js
Labels: size/S

#4430 Remove primary reconfig restrictions that we no longer need
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/S

#4431 CN improve "Error issuing request to recover orphaned data" log
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
Labels: size/XS

#4433 Manual reconfig route bug
  creator-node/src/components/replicaSet/replicaSetController.js
Labels: size/XS

#4406 INF-185 Local development on M1
  dev-tools/audius-compose
  docker-compose.m1.build.yml
  docker-compose.m1.yml
  solana-programs/.dockerignore
  solana-programs/.gitignore
  solana-programs/Dockerfile
  solana-programs/Dockerfile.dev
  solana-programs/Dockerfile.m1
  solana-programs/README.md
  solana-programs/scripts/build.sh
  solana-programs/scripts/setup-predeployed.sh
Labels: size/L

#4388 Replace remaining findOrCreates in identity notification system
  identity-service/src/notifications/milestoneProcessing.js
  identity-service/src/notifications/processNotifications/addTrackToPlaylistNotification.js
  identity-service/src/notifications/processNotifications/favoriteNotification.js
  identity-service/src/notifications/processNotifications/milestoneListenNotification.js
  identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
  identity-service/src/notifications/processNotifications/tierChangeNotification.js
  identity-service/src/notifications/processNotifications/tipNotification.js
  identity-service/src/notifications/utils.js
Labels: size/L

#4436 Fix manual reconfig route
  creator-node/src/components/replicaSet/replicaSetController.js
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/M

#4432 [PAY-745] Backfill audio_transactions_history from csv
  discovery-provider/alembic/versions/7b843f2d3a0d_load_audio_transactions_csv.py
  discovery-provider/integration_tests/tasks/test_index_spl_token.py
Labels: size/M

#4437 Better EM copying
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/src/models/playlists/playlist.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#4439 Add unclaimed user ID API
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_unclaimed_id.py
Labels: size/M

#4441 [PLAT-521] Add more table data to verbose health
  discovery-provider/src/monitors/database.py
Labels: size/XS

#4444 Wrap unclaimed API in proper response
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#4443 Update CN reconfig blacklist
  creator-node/src/config.js
Labels: size/XS

#4447 Fix notification send
  identity-service/src/notifications/notificationQueue.js
Labels: size/XS

#4448 Fix identity lint
  identity-service/src/notifications/notificationQueue.js
Labels: size/XS

#4410 Add ability to set-env with local compose
  .gitignore
  dev-tools/audius-compose
  dev-tools/startup/startup.sh
Labels: size/M

#4454 Add copy320 cid to header
  creator-node/src/routes/tracks.js
Labels: size/XS

#4457 Add ability to filter updateReplicaSet relays by sender address
  identity-service/src/config.js
  identity-service/src/relay/txRelay.js
Labels: size/S

#4459 Update compose permissions and add pyc to gitignore
  dev-tools/audius-compose
  discovery-provider/.gitignore
Labels: size/XS

#4326 Convert `transcodeHandoffManager` to typescript
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.ts
  creator-node/src/components/tracks/tracksComponentService.ts
  creator-node/test/TrackTranscodeHandoffManager.test.js
Labels: size/XXL

#4466 Make storagePath metrics work in cluster mode
  creator-node/src/app.ts
  creator-node/src/blacklistManager.js
  creator-node/src/components/tracks/TrackTranscodeHandoffManager.ts
  creator-node/src/diskManager.ts
  creator-node/src/index.ts
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/prometheusMonitoring/prometheusSetupUtils.ts
  creator-node/src/services/prometheusMonitoring/prometheusUsageUtils.ts
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/utils/cluster/clusterUtilsForPrimary.ts
  creator-node/src/utils/cluster/clusterUtilsForWorker.ts
Labels: content-node, size/XL

#4461 Skip txs with unsupported versions in spl token indexer
  discovery-provider/src/exceptions.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
Labels: requires-special-attention, size/S

#4451 Add DN endpoint for audio transactions count
  discovery-provider/src/api/v1/transactions.py
  discovery-provider/src/queries/get_audio_transactions_history.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/TransactionsApi.ts
  libs/src/sdk/api/generated/full/models/TransactionHistoryCountResponse.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#4464 Return favorite timestamp and sort by it
  discovery-provider/src/api/v1/models/common.py
  discovery-provider/src/queries/get_saves.py
  libs/src/sdk/api/generated/default/models/Favorite.ts
  libs/src/sdk/api/generated/full/models/Favorite.ts
Labels: size/S

#4468 Clean up storagePath metrics and expose failed paths in non-debug logs
  creator-node/scripts/run-tests.sh
  creator-node/src/diskManager.ts
  creator-node/src/index.ts
  creator-node/src/services/prometheusMonitoring/prometheusUsageUtils.ts
  creator-node/src/services/prometheusMonitoring/types.ts
  creator-node/src/utils/cluster/clusterUtilsForPrimary.ts
  docker-compose.test.yml
Labels: content-node, size/L

#4470 Fix typo in socialHandles.js
  identity-service/src/routes/socialHandles.js
Labels: size/XS

#4467 Expose EM users config via identity
  identity-service/src/routes/healthCheck.js
Labels: size/S

#4474 Lower number of subscribers for load test
  identity-service/test/processNotifications/createNotification.js
Labels: size/XS

#4465 [PAY-740] Add new location endpoint to Identity
  identity-service/src/config.js
  identity-service/src/routes/location.js
Labels: size/M

#4476 Fall back to network fetch when storagePath doesn't exist
  creator-node/src/dbManager.js
  creator-node/src/diskManager.ts
  creator-node/src/fileManager.js
Labels: content-node, size/L

#4472 Delete spl token indexer lock on startup
  discovery-provider/src/app.py
Labels: size/XS

#4477 Remove blocks FKs from subscriptions table
  discovery-provider/alembic/versions/3cdcb5e303f8_remove_subscriptions_fk_constraint.py
  discovery-provider/src/models/social/subscription.py
Labels: size/M

#4462 Backfill missing spl-token transactions
  discovery-provider/alembic/versions/7b843f2d3a0d_load_audio_transactions_csv.py
Labels: size/M

#4475 Network Monitoring: Use AudiusLibs to get content nodes
  discovery-provider/plugins/network-monitoring/package-lock.json
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/src/config.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
Labels: size/L

#4460 Fix spl token indexer parsing
  discovery-provider/integration_tests/tasks/test_index_spl_token.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#4469 Add libs is playlist upload to metadata
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/XS

#4483 Catch missing edge cases in storagePath pagination
  creator-node/src/diskManager.ts
Labels: content-node, size/S

#4484 Del trending task redis lock key on restart
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_trending.py
Labels: size/XS

#4485 Add is_current to query
  discovery-provider/src/queries/query_helpers.py
Labels: size/XS

#4486 Fix trending final poa
  discovery-provider/src/tasks/index_trending.py
Labels: size/XS

#4488 Set alembic head to backfill csv migration
  discovery-provider/alembic/versions/fe2c3daaa912_load_audio_transactions_csv_2.py
Labels: size/M

#4434 Show audius-docker-compose commit in health check
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  discovery-provider/src/queries/get_health.py
Labels: size/S

#4492 Eventlet py version
  discovery-provider/requirements.txt
Labels: size/XS

#4490 Async io fetch nodes
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/L

#4420 [PAY-742] Add backfill script and migration (possibly one of several)
  audius.code-workspace
  discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
  monitoring/scripts/track-cid-backfill/.gitignore
  monitoring/scripts/track-cid-backfill/Pipfile
  monitoring/scripts/track-cid-backfill/README.md
  monitoring/scripts/track-cid-backfill/package-lock.json
  monitoring/scripts/track-cid-backfill/package.json
  monitoring/scripts/track-cid-backfill/python/Pipfile
  monitoring/scripts/track-cid-backfill/python/Pipfile.lock
  monitoring/scripts/track-cid-backfill/python/main.py
  monitoring/scripts/track-cid-backfill/src/config.ts
  monitoring/scripts/track-cid-backfill/src/content.ts
  monitoring/scripts/track-cid-backfill/src/csv.ts
  monitoring/scripts/track-cid-backfill/src/db/index.ts
  monitoring/scripts/track-cid-backfill/src/index.ts
  monitoring/scripts/track-cid-backfill/src/queries.ts
  monitoring/scripts/track-cid-backfill/tsconfig.json
Labels: size/XXL

#4495 Fix lib types, add CI check
  libs/Dockerfile
  libs/src/AudiusLibs.ts
  libs/src/api/Account.ts
  libs/src/api/Users.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/wormhole/Wormhole.ts
  libs/tests/audiusTokenClientTest.js
  libs/tests/stakingTest.js
  libs/tsconfig.json
Labels: size/M

#4494 Network Monitoring: fix query to fetch content nodes
  discovery-provider/plugins/network-monitoring/package-lock.json
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
Labels: size/S

#4442 Add fetch notifs method
  discovery-provider/integration_tests/queries/test_notifications/test_follow_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_paginate_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_reaction_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_repost_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_save_notification.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/XL

#4435 Add libs write notif view
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/api/Notifications.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: libs, size/M

#4491 Rate limit EM replica set updates
  identity-service/src/relay/txRelay.js
Labels: size/M

#4496 [C-1644] Remove Recaptcha
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/api/base.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/utils/captcha.ts
  libs/src/utils/index.ts
Labels: size/L

#4500 Fix err logs
  discovery-provider/src/eth_indexing/event_scanner.py
  discovery-provider/src/utils/helpers.py
Labels: size/S

#4498 Fix track cid backfill alembic version
  discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
  discovery-provider/alembic/versions/f6f009132212_add_track_is_playlist_upload.py
Labels: size/XS

#4489 [PAY-765] Prevent redirecting stream to CN if no track_cid
  discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#4504 Remove mismatched CID check from storagePath migrations
  creator-node/src/diskManager.ts
Labels: content-node, size/S

#4505 Implement solana notifs safer min/max slot logic
  identity-service/src/config.js
  identity-service/src/notifications/index.js
Labels: size/S

#4499 [PAY-757] Prevent premium tracks remixability
  discovery-provider/src/queries/get_remix_track_parents.py
  discovery-provider/src/queries/get_remixable_tracks.py
  discovery-provider/src/queries/get_remixes_of.py
Labels: size/S

#4506 Avoid updating or publishing already seen notifications
  identity-service/sequelize/migrations/20221219201744-add-indices-to-slot-and-blocknum.js
  identity-service/src/notifications/index.js
Labels: size/M

#4502 Fix backfill track cid tmp removal
  discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
Labels: size/L

#4481 Write and relay nethermind txs
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/relay.js
Labels: size/L

#4408 Add handle check
  identity-service/src/routes/instagram.js
  identity-service/src/routes/twitter.js
Labels: size/S

#4487 Add release-scripts to protocol repo
  .circleci/config.yml
  .circleci/release-scripts/README.md
  .circleci/release-scripts/bump-hotfix.sh
  .circleci/release-scripts/cut-release.sh
  .circleci/release-scripts/dheeraj-test.sh
  .circleci/release-scripts/dockerfiles/bump-hotfix/Dockerfile
  .circleci/release-scripts/dockerfiles/bump-hotfix/bump.sh
  .circleci/release-scripts/dockerfiles/cut-release/Dockerfile
  .circleci/release-scripts/dockerfiles/cut-release/cut.sh
  .circleci/release-scripts/dockerfiles/evaluate-proposal/Dockerfile
  .circleci/release-scripts/dockerfiles/evaluate-proposal/evaluate.js
  .circleci/release-scripts/dockerfiles/evaluate-proposal/package.json
  .circleci/release-scripts/dockerfiles/release-to-service-providers/Dockerfile
  .circleci/release-scripts/dockerfiles/release-to-service-providers/package.json
  .circleci/release-scripts/dockerfiles/release-to-service-providers/release.js
  .circleci/release-scripts/dockerfiles/release-to-service-providers/release.sh
  .circleci/release-scripts/dockerfiles/slash-proposal/Dockerfile
  .circleci/release-scripts/dockerfiles/slash-proposal/package.json
  .circleci/release-scripts/dockerfiles/slash-proposal/slash.js
  .circleci/release-scripts/evaluate-proposal.sh
  .circleci/release-scripts/release-to-service-providers.sh
  .circleci/release-scripts/slash-proposal.sh
Labels: size/XL

#4493 Remove dependency on ursm_content_nodes in track availability
  discovery-provider/integration_tests/tasks/test_update_track_is_available.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/helpers.py
Labels: size/M

#4512 Minor fixes for cmd upload
  dev-tools/commands/src/upload-track.mjs
Labels: size/XS

#4511 Fix TikTok auth + improve association
  identity-service/src/routes/tiktok.js
Labels: size/S

#4510 Rename to full for clarity
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/cid_data.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/index.ts
Labels: size/S

#4507 Fix CN stack too deep error & probably CPU maxing out
  creator-node/package-lock.json
  creator-node/src/diskManager.ts
  creator-node/src/index.ts
Labels: size/L

#4513 [C-1697] Fix contract method check runtime error
  libs/src/services/contracts/ContractClient.ts
Labels: size/XS

#4517 disable backgroundDiskCleanupCheckEnabled
  creator-node/src/config.js
Labels: size/XS

#4518 disable storagePath migrations
  creator-node/src/config.js
Labels: size/XS

#4514 Fix dethrone notification
  identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
  identity-service/src/notifications/utils.js
  identity-service/test/index.js
  identity-service/test/processNotifications/supporterRankChangeNotification.js
Labels: size/L

#4519 [PAY-769] Optimize Solana RPC signature fetching
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#4520 Remove caching for unclaimed ID
  discovery-provider/nginx_conf/nginx.conf
Labels: size/M

#4521 Re-enable CN background tasks
  creator-node/src/config.js
Labels: size/XS

#4516 Cache CN SPFactory calls
  creator-node/src/apiSigning.ts
  creator-node/src/components/replicaSet/URSMRegistrationComponentService.js
  creator-node/src/middlewares.js
  creator-node/src/reqLimiter.js
  creator-node/test/apiSigning.test.js
  creator-node/test/lib/app.js
  creator-node/test/transcodeAndSegment.test.js
Labels: size/L

#4515 Add metrics for total unmigrated files
  creator-node/src/dbManager.js
  creator-node/src/diskManager.ts
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
Labels: content-node, size/L

#4509 [C-1522] Update instagram routes
  identity-service/src/config.js
  identity-service/src/routes/instagram.js
  identity-service/src/routes/twitter.js
Labels: size/M

#4523 Fix typo
  identity-service/src/config.js
Labels: size/XS

#4522 Content node /track/stream optimizations
  creator-node/src/routes/tracks.js
Labels: size/M

#4524 Update Replica set endpoint
  discovery-provider/integration_tests/queries/test_get_user_replica_set.py
  discovery-provider/src/queries/get_user_replica_set.py
Labels: size/M

#4527 Tracks stream optimizations pt 2
  creator-node/src/routes/tracks.js
Labels: size/S

#4480 [PAY-747] Handle solana-nft-gated premium content
  discovery-provider/src/queries/get_premium_track_signatures.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/solana/solana_helpers.py
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/L

#4528 [PAY-123] Fix flaky rewards test
  libs/tests/rewardsAttesterTest.js
Labels: size/S

#4529 Only process messages once per seq num
  comms/db/migrations/20221222050259_add_rpc_log_pk.sql
  comms/internal/rpcz/apply.go
  comms/server/server_test.go
Labels: size/M

#4416 [PAY-759] [PAY-758] Add ChatsApi to SDK
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
  libs/rollup.sdkbrowser.config.js
  libs/src/sdk/api/HealthCheckResponseData.ts
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
  libs/src/sdk/api/chats/serverTypes.ts
  libs/src/sdk/api/generated/default/runtime.ts
  libs/src/sdk/api/generated/full/runtime.ts
  libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache
  libs/src/sdk/index.ts
  libs/src/sdk/middleware/addAppNameMiddleware.ts
  libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
  libs/src/sdk/middleware/index.ts
  libs/src/sdk/middleware/jsonResponseMiddleware.ts
  libs/src/sdk/sdk.ts
Labels: size/XXL

#4533 Revert "[PAY-759] [PAY-758] Add ChatsApi to SDK"
  libs/package-lock.json
  libs/package.json
  libs/rollup.config.js
  libs/rollup.sdkbrowser.config.js
  libs/src/sdk/api/HealthCheckResponseData.ts
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
  libs/src/sdk/api/chats/serverTypes.ts
  libs/src/sdk/api/generated/default/runtime.ts
  libs/src/sdk/api/generated/full/runtime.ts
  libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache
  libs/src/sdk/index.ts
  libs/src/sdk/middleware/addAppNameMiddleware.ts
  libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
  libs/src/sdk/middleware/index.ts
  libs/src/sdk/middleware/jsonResponseMiddleware.ts
  libs/src/sdk/sdk.ts
Labels: size/XXL

#4535 Fix instagram request bug
  identity-service/src/routes/instagram.js
Labels: size/XS

#4536 Default EM users in content node
  creator-node/src/config.js
Labels: size/XS

#4537 Update CN reconfigSPIdBlacklistString
  creator-node/src/config.js
Labels: size/XS

#4538 Use username instead of display_name for tiktok
  identity-service/src/routes/tiktok.js
Labels: size/S

#4540 Validate user handle with lowercase
  discovery-provider/src/tasks/entity_manager/user.py
Labels: size/XS

#4548 Fix entity manager invalidation for user and tracks
  discovery-provider/alembic/versions/1b6e405ef358_fix_is_current_for_users_and_tracks_due_.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
Labels: size/L
