Repository AudiusProject/apps, pull requests merged in 2023-03, with the labels that each got.

#4854 Improve audius-compose reliability
  creator-node/Dockerfile
  creator-node/scripts/start.sh
  dev-tools/audius-compose
  discovery-provider/compose/docker-compose.notifications.yml
  discovery-provider/plugins/notifications/.nvmrc
  discovery-provider/plugins/notifications/Dockerfile
  discovery-provider/plugins/notifications/package-lock.json
  docker-compose.yml
  identity-service/scripts/dev-server.sh
Labels: size/L

#4856 Add additional 84 missing track cids
  discovery-provider/alembic/csvs/missing_track_cid_22823.csv
  discovery-provider/alembic/versions/abf8419b2dd5_22823_track_cids.py
Labels: size/L

#4820 [PLAT-712] Normalize unicode in *_routes tables
  discovery-provider/alembic/versions/e68928955812_nfc_unicode_routes.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/helpers_unit_test.py
Labels: size/L

#4857 Add tests for Content Access Middleware
  comms/natsd/nats_main.go
  comms/natsd/nats_manager.go
  comms/shared/peering/exchange_endpoint.go
  comms/shared/peering/info.go
  comms/shared/peering/nats_connection.go
  comms/shared/peering/peering.go
  comms/shared/peering/solicit.go
  comms/shared/peering/sps.go
  comms/shared/utils/utils.go
  comms/storage/contentaccess/content_access_checker.go
  comms/storage/contentaccess/content_access_checker_test.go
  comms/storage/contentaccess/content_access_middleware.go
  comms/storage/storageserver/storageserver.go
  comms/storage/tests/content_access_middleware_test.go
  comms/storage/tests/mock_peering.go
Labels: size/L

#4851 Update em and get_notifications for save_of_repost
  discovery-provider/integration_tests/queries/test_notifications/test_save_of_repost_notification.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/L

#4853 add migrations to update handle save and repost triggers
  discovery-provider/alembic/versions/4b3b96d8149b_update_handle_repost_trigger.py
  discovery-provider/alembic/versions/b9b7a1444783_update_handle_save_trigger.py
Labels: size/M

#4859 fix migration head on handle repost migration
  discovery-provider/alembic/versions/4b3b96d8149b_update_handle_repost_trigger.py
Labels: size/XS

#4860 disable auto deploy to stage discovery nodes
  .circleci/workflows/main.yml
Labels: size/M

#4850 [CON-625] Change logger to `slog`
  comms/cmd/audio.go
  comms/cmd/image.go
  comms/cmd/seed.go
  comms/discovery/discovery_main.go
  comms/discovery/em/chain_test.go
  comms/discovery/em/cid.go
  comms/discovery/em/nats_test.go
  comms/discovery/rpcz/main_test.go
  comms/discovery/server/main_test.go
  comms/go.mod
  comms/go.sum
  comms/natsd/nats_main.go
  comms/natsd/nats_manager.go
  comms/shared/config/config.go
  comms/shared/peering/info_test.go
  comms/shared/peering/nats_connection.go
  comms/shared/peering/peering.go
  comms/shared/peering/signed_request.go
  comms/shared/peering/solicit.go
  comms/shared/peering/sps.go
  comms/storage/persistence/persistence.go
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
  comms/storage/telemetry/README.md
  comms/storage/telemetry/logger.go
  comms/storage/telemetry/tracing_handler.go
  comms/storage/transcode/create_bucket.go
  comms/storage/transcode/img.go
  comms/storage/transcode/jobs.go
  comms/storage/transcode/jobs_test.go
Labels: size/XL

#4861 fix: Storage Server merge issue
  comms/storage/storageserver/storageserver.go
Labels: size/XS

#4864 house keeping
  comms/shared/peering/peering.go
  comms/storage/tests/mock_peering.go
Labels: size/M

#4862 Fix social actions on accessible gated tracks
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/queries/get_track_stream_signature.py
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/L

#4830 [CON-621] StorageV2: Add cli cmds for integration tests
  comms/cmd/discovery.go
  comms/cmd/getFile.go
  comms/cmd/job.go
  comms/cmd/jobs.go
  comms/cmd/nats.go
  comms/cmd/nodesToShards.go
  comms/cmd/results.go
  comms/storage/client/client.go
Labels: size/L

#4868 StorageV2: hex encode signature for content access middleware
  comms/storage/contentaccess/content_access_checker.go
  comms/storage/contentaccess/content_access_checker_test.go
  comms/storage/contentaccess/content_access_middleware.go
  comms/storage/tests/content_access_middleware_test.go
Labels: size/M

#4867 Fix notification seen at
  discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/XS

#4869 Rename leftover nodesToShards to nodeStatuses
  comms/cmd/nodesToShards.go
  comms/storage/client/client.go
Labels: size/S

#4870 Comment out indexer code that gates social actions
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/S

#4866 Add unread count
  discovery-provider/integration_tests/notifications/test_save_of_repost.py
  discovery-provider/integration_tests/queries/test_notifications/test_get_unread_notification_count.py
  discovery-provider/src/api/v1/models/notifications.py
  discovery-provider/src/api/v1/notifications.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#4871 [CON-625] Silence app logs for new cli cmds
  comms/cmd/getFile.go
  comms/cmd/job.go
  comms/cmd/jobs.go
  comms/cmd/nodesToShards.go
  comms/cmd/results.go
Labels: size/S

#4858 Add email mappings
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/types.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/XXL

#4874 Add logs to notifications health check
  identity-service/src/routes/healthCheck.js
Labels: size/S

#4876 Improve cleanup flow, and cleanup firewalls
  .circleci/commands/gcp-run.yml
  .circleci/jobs/gcp-cleanup.yml
Labels: size/M

#4877 Log and visualize core storage node events
  comms/docker-compose.v2.base.yml
  comms/shared/config/config.go
  comms/storage/client/client.go
  comms/storage/config/config.go
  comms/storage/decider/RendezvousDecider.go
  comms/storage/logstream/logstream.go
  comms/storage/monitor/monitor.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/weather-map/README.md
  comms/storage/storageserver/weather-map/dist/assets/index-08f8b381.css
  comms/storage/storageserver/weather-map/dist/assets/index-262be2b6.js
  comms/storage/storageserver/weather-map/dist/assets/index-7ca346ac.css
  comms/storage/storageserver/weather-map/dist/assets/index-b3310aad.js
  comms/storage/storageserver/weather-map/dist/index.html
  comms/storage/storageserver/weather-map/index.html
  comms/storage/storageserver/weather-map/package.json
  comms/storage/storageserver/weather-map/src/App.tsx
  comms/storage/storageserver/weather-map/src/api.ts
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/Buttons.tsx
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/DatePickerPopup.tsx
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/DatePickerProvider.tsx
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/DateTimePicker.tsx
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/views/Days.tsx
  comms/storage/storageserver/weather-map/src/components/dateTimePicker/views/Months.tsx
  comms/storage/storageserver/weather-map/src/components/nodes/Nodes.tsx
  comms/storage/storageserver/weather-map/src/components/search/SearchBar.tsx
  comms/storage/storageserver/weather-map/src/routes/History.tsx
  comms/storage/storageserver/weather-map/src/routes/Home.tsx
  comms/storage/storageserver/weather-map/src/routes/Search.tsx
  comms/storage/storageserver/weather-map/src/routes/Shard.tsx
  comms/storage/storageserver/weather-map/src/routes/Wrapper.tsx
  comms/storage/storageserver/weather-map/weather-map.code-workspace
  comms/storage/storageserver/weather-map/yarn.lock
  comms/storage/transcode/create_bucket.go
Labels: size/XXL

#4878 Fix flaky dm notifs tests
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
Labels: size/M

#4880 ignore processing 'create' notifications
  identity-service/src/notifications/processNotifications/createNotification.js
Labels: size/XS

#4881 Ignore push create track notif
  identity-service/src/notifications/sendNotifications/formatNotification.js
Labels: size/XS

#4882 Use last index instead of 0th for CN getUsers
  creator-node/src/services/ContentNodeInfoManager.ts
Labels: size/S

#4879 Is fix worker 2
  discovery-provider/src/app.py
Labels: size/XS

#4875 ACDC migration: only allow eth calls + tolerate final_poa_block reque…
  discovery-provider/nginx_conf/main.lua
  discovery-provider/src/utils/helpers.py
Labels: size/S

#4884 Remove newline char on cid
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
Labels: size/XS

#4888 Remove prod cn4 from deploy pipeline
  .circleci/workflows/main.yml
Labels: size/XS

#4890 Fix cid comparison
  creator-node/src/contentAccess/contentAccessChecker.ts
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
Labels: size/XS

#4852 Add ACDC relay timeout and fix metric
  identity-service/src/config.js
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/healthCheck.js
  identity-service/src/utils/relayReporter.js
Labels: size/L

#4873 Add CI Tests
  .circleci/workflows/main.yml
  discovery-provider/plugins/notifications/Dockerfile
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/emailRender.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  docker-compose.test.yml
  docker-compose.yml
Labels: size/XXL

#4892 Fix some release related errors in Circle CI
  .circleci/jobs/release-audius-docker-compose.yml
  .circleci/jobs/release-discord.yml
  .circleci/jobs/release-github-draft.yml
  .circleci/jobs/release-github.yml
  .circleci/jobs/release-governance.yml
Labels: size/S

#4893 [CON-635] Make remaining log types queryable and display them
  comms/storage/logstream/logstream.go
  comms/storage/monitor/monitor.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/weather-map/dist/assets/index-262be2b6.js
  comms/storage/storageserver/weather-map/dist/assets/index-29ee4f74.css
  comms/storage/storageserver/weather-map/dist/assets/index-7ca346ac.css
  comms/storage/storageserver/weather-map/dist/assets/index-efaab22c.js
  comms/storage/storageserver/weather-map/dist/index.html
  comms/storage/storageserver/weather-map/src/api.ts
  comms/storage/storageserver/weather-map/src/components/timeline/Timeline.tsx
  comms/storage/storageserver/weather-map/src/components/timeline/index.ts
  comms/storage/storageserver/weather-map/src/routes/History.tsx
Labels: size/XL

#4883 Add min followers to feeling lucky query
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_random_tracks.py
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
Labels: size/S

#4894 Add trending track
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
  discovery-provider/plugins/notifications/src/utils/format.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XL

#4899 [INF-364] Improve identity reload speed
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/scripts/dev-server.sh
  identity-service/src/index.ts
Labels: size/S

#4902 Revert "[INF-364] Improve identity reload speed (#4899)"
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/scripts/dev-server.sh
  identity-service/src/index.ts
Labels: size/S

#4904 reverse proxy route for mediorum
  creator-node/nginx_conf/nginx.conf
Labels: size/S

#4900 [C-2268] Add missing valid_types params to get-notifications endpoint
  discovery-provider/src/api/v1/notifications.py
  libs/src/api/Notifications.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/M

#4901 Disable linking libs by default, optimize CN hot reloading, fix bug
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/start.sh
  creator-node/src/apiSigning.ts
  creator-node/src/app.ts
  creator-node/src/components/tracks/trackContentUploadManager.ts
  creator-node/src/diskManager.ts
  creator-node/src/fileManager.js
  creator-node/src/index.ts
  creator-node/src/resizeImage.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/URSMRegistrationManager.js
  creator-node/src/services/initAudiusLibs.js
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/utils/cidUtils.ts
  creator-node/src/utils/fileHasher.js
  discovery-provider/src/api/v1/tracks.py
  identity-service/scripts/dev-server.sh
  identity-service/src/app.js
  identity-service/src/index.ts
Labels: size/L

#4905 Bump sdk to v2.0.2-alpha.4
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#4906 Revert track-create push notifs change on Identity
  identity-service/src/notifications/processNotifications/createNotification.js
  identity-service/src/notifications/sendNotifications/formatNotification.js
Labels: size/XS

#4903 Fix identity relay checks
  identity-service/src/routes/healthCheck.js
Labels: size/L

#4910 double money for docker
  docker-compose.test.yml
Labels: size/XS

#4911 Fix zrange args and clean up logs
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/healthCheck.js
Labels: size/S

#4908 Push comms through Circle CI
  .circleci/workflows/main.yml
  docker-compose.yml
Labels: size/S

#4913 Enable auto-deploy stage
  .circleci/workflows/main.yml
Labels: size/M

#4917 Allow net /nethermind requests
  discovery-provider/nginx_conf/main.lua
Labels: size/XS

#4916 Remove defaults for relay checks
  identity-service/src/routes/healthCheck.js
Labels: size/M

#4826 Comms: round timestamps to microseconds on read
  comms/discovery/rpcz/apply.go
Labels: size/XS

#4919 Fix celery worker startup by removing prometheus
  discovery-provider/src/app.py
Labels: size/XS

#4920 Fix discovery notifications endpoint for unread
  discovery-provider/src/api/v1/notifications.py
Labels: size/XS

#4922 Fix unread count
  discovery-provider/src/api/v1/notifications.py
Labels: size/XS

#4923 handle nonexistent user in relay
  identity-service/src/relay/txRelay.js
Labels: size/XS

#4823 Comms: unfurl urls server-side
  comms/discovery/discovery_main.go
  comms/discovery/server/server.go
  comms/go.mod
  comms/go.sum
Labels: size/M

#4907 add acdc specific check
  discovery-provider/src/queries/get_health.py
Labels: size/S

#4925 Improve identity and CN dev reload times
  creator-node/Dockerfile
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/patches/ts-node-dev+2.0.0.patch
  creator-node/scripts/start.sh
  dev-tools/setup-dev.sh
  identity-service/Dockerfile
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/patches/ts-node-dev+2.0.0.patch
  identity-service/scripts/dev-server.sh
Labels: size/M

#4895 fix mappers and add multi support
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/MultiUserHeader.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/NotificationBody.tsx
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/types.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipSend.ts
Labels: size/XXL

#4928 Fix CN tests
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/utils.test.js
Labels: size/M

#4927 Minor CI fixes
  .circleci/jobs/gcp-cleanup.yml
  .circleci/jobs/release-audius-docker-compose.yml
  .circleci/jobs/release-governance.yml
Labels: size/S

#4896 Add repost of repost and save of repost to notifications plugin
  discovery-provider/output.txt
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/types/dn.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XXL

#4773 SDK: Retry once with new selections on failed requests
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
Labels: size/M

#4933 Fix notification test type imports
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
Labels: size/S

#4931 Deploy notifications on ci
  .circleci/jobs/deploy.yml
  .circleci/workflows/main.yml
Labels: size/S

#4929 nats healthz
  monitoring/healthz/src/Nats.tsx
  monitoring/healthz/src/Router.tsx
  monitoring/healthz/src/query.ts
  monitoring/healthz/src/useServiceProviders.ts
Labels: size/L

#4924 Add play count to user listening history and allow sorting by play count
  discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  discovery-provider/integration_tests/tasks/test_index_user_listening_history.py
  discovery-provider/src/queries/get_user_listening_history.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
  discovery-provider/src/tasks/user_listening_history/listen_history.py
Labels: size/L

#4912 Use audius-compose to bring up comms
  .circleci/jobs/push-docker-image.yml
  comms/Dockerfile
  comms/docker-compose.base.yml
  comms/docker-compose.yml
  comms/nginx/ingress.conf
  dev-tools/audius-compose
  dev-tools/config.json
  dev-tools/startup/comms-ingress.sh
  dev-tools/startup/comms.sh
  dev-tools/startup/creator-node.sh
  dev-tools/startup/discovery-provider.sh
Labels: size/XL

#4935 rpc id is the timestamp + md5(rpc)
  comms/discovery/db/migrations/20230315135942_rpc_id.sql
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
Labels: size/M

#4941 Remove block hash constraints
  discovery-provider/alembic/versions/5b4e01eaebab_remove_revert_constraints.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#4946 Fix loop of block number adjustment
  discovery-provider/src/queries/notifications.py
Labels: size/S

#4944 Silence logs when running notification tests
  discovery-provider/plugins/notifications/src/logger.ts
Labels: size/XS

#4949 SDK 2.0.2
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#4932 Fix duplicate create EM validation failure on follow
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/M

#4954 Revert by number not hash
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#4955 Fix typo in users model
  discovery-provider/src/api/v1/models/users.py
Labels: size/XS

#4952 DMs: Allow multiple websocket connections, backfill pubkeys
  comms/discovery/db/migrations/20230316193251_pubkey_table.sql
  comms/discovery/discovery_main.go
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/pubkeystore/recover_test.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/websocket.go
  comms/discovery/server/server.go
Labels: size/L

#4950 ACDC migration relay reconcile with release-v0.3.78
  identity-service/src/relay/txRelay.js
Labels: size/S

#4957 Stop POA indexing
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index.py
Labels: size/L

#4945 Fix a single track availability post acdc
  discovery-provider/alembic/versions/e97a5ba523fc_fix_available_track.py
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
Labels: size/M

#4936 Remove wait in identity notifications
  identity-service/src/notifications/index.js
Labels: size/S

#4915 Plugin notifications add optimizely val
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
  discovery-provider/plugins/notifications/src/logger.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipSend.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  identity-service/src/notifications/index.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/remoteConfig.js
Labels: size/XL

#4948 Fix unread count
  discovery-provider/integration_tests/queries/test_notifications/test_get_unread_notification_count.py
  discovery-provider/src/api/v1/notifications.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/S

#4960 Increase timeout to fix DP tests
  discovery-provider/Dockerfile
Labels: size/XS

#4962 remove is_available true in base track selector
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
Labels: size/XS

#4958 [PLAT-694] Add underground-trending notification indexing
  discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/tasks/index_trending.py
Labels: size/L

#4845 PLAT-575: include nodes in health query
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/M

#4968 Revert "PLAT-575: include nodes in health query"
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/M

#4969 Bypass notification transactions
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#4970 Revert notification seen
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#4971 Add notification seen table again
  discovery-provider/alembic/versions/d43a7fd867f3_notification_seen_again.py
Labels: size/M

#4972 Add index on notification seen
  discovery-provider/alembic/versions/f008f6f2eee3_add_block_number_index_on_notification_.py
Labels: size/M

#4973 [INF-369] Add content node flakey test retries
  contracts/test/userReplicaSetManager.js
  creator-node/.mocharc.js
  creator-node/test/CNodeHealthManager.test.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/dbManager.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/prometheus.test.js
Labels: size/XXL

#4959 As/plat 787 verified user plugin
  discovery-provider/plugins/verified-uploads/Dockerfile
  discovery-provider/plugins/verified-uploads/docker-compose.yaml
  discovery-provider/plugins/verified-uploads/package-lock.json
  discovery-provider/plugins/verified-uploads/package.json
  discovery-provider/plugins/verified-uploads/src/db.js
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
  discovery-provider/plugins/verified-uploads/src/index.js
  discovery-provider/plugins/verified-uploads/src/slack.js
Labels: size/L

#4977 Shut off stage autodeploy
  .circleci/workflows/main.yml
Labels: size/L

#4963 [PAY-951] SDK: Allow chat messages to have externally specified IDs, gracefully fail decryption
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/M

#4961 Use nginx ingress instead of sshuttle
  comms/Dockerfile
  comms/Makefile
  comms/README.md
  comms/docker-compose.yml
  comms/nginx/ingress.conf
  comms/storage/README.md
  dev-tools/README.md
  dev-tools/audius-compose
  dev-tools/config.json
  dev-tools/startup/comms-ingress.sh
  dev-tools/startup/comms.sh
  dev-tools/startup/creator-node.sh
  dev-tools/startup/discovery-provider.sh
  dev-tools/startup/port-forwarder.sh
  dev-tools/startup/sshuttle-server.sh
  discovery-provider/default_config.ini
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/web3_provider.py
  docker-compose.blockchain.yml
  docker-compose.comms.yml
  docker-compose.creator.yml
  docker-compose.dev.yml
  docker-compose.discovery.yml
  docker-compose.identity.yml
  docker-compose.yml
  nginx_ingress.conf
  solana-programs/Dockerfile.dev
Labels: size/XXL

#4967 Remove dependency on identity for final_poa_block
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/L

#4983 Bump SDK to v2.0.3-beta.0
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#4974 [PLAT-791] Index trending_playlist notifications
  discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
  discovery-provider/integration_tests/tasks/test_trending_playlist_notifications.py
  discovery-provider/src/tasks/cache_trending_playlists.py
Labels: size/L

#3743 [PLAT-789] Remove anchor audius data
  libs/package-lock.json
  libs/package.json
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/api/Account.ts
  libs/src/api/base.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solanaAudiusData/SolanaAudiusData.ts
  libs/src/services/solanaAudiusData/errors.ts
  libs/src/services/solanaAudiusData/index.ts
  libs/src/services/wormhole/Wormhole.ts
Labels: size/XXL

#4984 Revert "Shut off stage autodeploy (#4977)"
  .circleci/workflows/main.yml
Labels: size/L

#4985 [Flare-167] Add no-cache to discovery unclaimed ids
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#4986 More retries for unclaimed ID
  discovery-provider/src/queries/get_unclaimed_id.py
Labels: size/XS

#4990 Remove prod dp4 from auto deploy
  .circleci/workflows/main.yml
Labels: size/XS

#4966 Comms user chat permissions endpoints
  comms/discovery/db/queries/get_chat_permissions.go
  comms/discovery/db/queries/get_follows.go
  comms/discovery/db/queries/get_user_tips.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/validator.go
  comms/discovery/schema/schema.go
  comms/discovery/schema/schema.ts
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/XL

#4940 safer self connection test
  comms/natsd/self_connection_probe.go
Labels: size/S

#4993 Change /etc/hosts update from auto to manual
  dev-tools/README.md
  dev-tools/audius-compose
Labels: size/S

#4995 Update /etc/hosts via audius-compose connect
  dev-tools/README.md
  dev-tools/audius-compose
Labels: size/M

#4996 Remove POA tests
  .circleci/workflows/main.yml
Labels: size/XS

#4982 PLAT-575: list discprov nodes
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/M

#4997 Fix discord ci curl
  .circleci/jobs/release-discord.yml
Labels: size/XS

#4976 Add flow to release sdk through circleci
  .circleci/@parameters.yml
  .circleci/config.yml
  .circleci/jobs/release-audius-sdk.yml
  .circleci/workflows/release-audius-sdk.yml
Labels: size/M

#5000 Isolate CI fixes
  .circleci/jobs/build-gcp-image.yml
  .circleci/jobs/push-docker-image.yml
  .circleci/jobs/test-audius-cmd.yml
  .circleci/jobs/test.yml
  dev-tools/audius-compose
Labels: size/S

#4994 Revert verified user reporter on identity
  identity-service/src/config.js
  identity-service/src/routes/instagram.js
  identity-service/src/routes/tiktok.js
  identity-service/src/routes/twitter.js
  identity-service/src/utils/verifiedUserReporter.js
Labels: size/M

#4987 Improve caching on dockerfiles
  creator-node/Dockerfile
  discovery-provider/Dockerfile
Labels: size/S

#4998 Use a single postgres db for local dev
  dev-tools/startup/creator-node.sh
  dev-tools/startup/discovery-provider.sh
  dev-tools/startup/init-db.sql
  docker-compose.comms.yml
  docker-compose.creator.yml
  docker-compose.discovery.yml
  docker-compose.identity.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: size/L

#5003 healthz: re-add compose sha
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/index.css
Labels: size/M

#5002 Fix unclaimed ID caching for safari
  libs/src/services/discoveryProvider/requests.ts
Labels: size/XS

#4980 add trending pages to healthz for trending underground and trending p…
  monitoring/healthz/src/DiscoveryTrending.tsx
  monitoring/healthz/src/Router.tsx
Labels: size/S

#4981 Add tastemaker notification type to get notifications query
  discovery-provider/integration_tests/queries/test_notifications/test_tastemaker_notification.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/L

#5005 [INF-371] Fix local indexing and add flags to skip libs and solana-test-validator
  creator-node/test/CNodeHealthManager.test.js
  dev-tools/audius-compose
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/web3_provider.py
  docker-compose.blockchain.yml
  docker-compose.discovery.yml
  docker-compose.test.yml
  docker-compose.yml
  nginx_ingress.conf
Labels: size/L

#5008 Fix sdk release
  .circleci/config.yml
Labels: size/XS

#5001 Add tastemaker notification to discovery notif plugin
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tastemaker.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tastemaker.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/XL

#5016 Dedupe byte range requests
  creator-node/src/routes/tracks.js
  creator-node/src/utils/requestRange.ts
Labels: size/S

#4999 Make es-indexer less aggressive about deleting red indexes
  discovery-provider/es-indexer/src/conn.ts
Labels: size/M

#5010 Update notifs feature flag
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/notifications/test_track.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py
  discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
  discovery-provider/plugins/notifications/README.md
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/scripts/create-announcement.ts
  discovery-provider/plugins/notifications/scripts/test-push-notification.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/listener.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/sns.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/tasks/cache_trending_playlists.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/entity_manager/utils.py
  identity-service/src/notifications/index.js
  identity-service/src/notifications/notificationQueue.js
  identity-service/src/remoteConfig.js
Labels: size/L

#5015 Use mediorum for storage v2 track upload
  dev-tools/audius-compose
  dev-tools/commands/src/utils.mjs
  docker-compose.storagev2.yml
  docker-compose.yml
  libs/initScripts/local.js
  libs/package-lock.json
  libs/src/api/Track.ts
  libs/src/services/creatorNode/CreatorNode.ts
  nginx_ingress.conf
Labels: size/L

#5011 [PLAT-800] Add trending integration tests
  discovery-provider/integration_tests/queries/test_notifications/test_trending_playlist_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_trending_underground_notification.py
Labels: size/L

#5018 add extra details to healthz readme
  monitoring/healthz/README.md
Labels: size/S

#5023 Fix extend announcement
  discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/XS

#5020 Fix local image upload and --no-notifs flag
  creator-node/src/ImageProcessingQueue.ts
  dev-tools/audius-compose
  discovery-provider/scripts/start.sh
  docker-compose.comms.yml
  docker-compose.discovery.yml
  docker-compose.storagev2.yml
  nginx_ingress.conf
Labels: size/M

#5022 Clean up permissions endpoints
  comms/discovery/db/queries/get_chat_permissions.go
  comms/discovery/db/queries/get_follows.go
  comms/discovery/db/queries/get_user_tips.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
Labels: size/L

#4978 PLAT-787: verified users and uploads plugin
  discovery-provider/.gitignore
  discovery-provider/plugins/verified-uploads/.dockerignore
  discovery-provider/plugins/verified-uploads/.nvmrc
  discovery-provider/plugins/verified-uploads/Dockerfile
  discovery-provider/plugins/verified-uploads/Makefile
  discovery-provider/plugins/verified-uploads/README.md
  discovery-provider/plugins/verified-uploads/docker-compose.yaml
  discovery-provider/plugins/verified-uploads/package-lock.json
  discovery-provider/plugins/verified-uploads/package.json
  discovery-provider/plugins/verified-uploads/src/db.js
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
  discovery-provider/plugins/verified-uploads/src/index.js
  discovery-provider/plugins/verified-uploads/src/slack.js
Labels: size/L

#5024 Es indexer enable triggers
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/setup.ts
Labels: size/XS

#5013 Improve listens: pass user ID, more accurate geolocation
  creator-node/src/contentAccess/contentAccessChecker.ts
  creator-node/src/contentAccess/types.ts
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
  creator-node/src/routes/tracks.js
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
  discovery-provider/src/queries/get_premium_track_signatures.py
  discovery-provider/src/queries/get_track_stream_signature.py
  identity-service/src/rateLimiter.js
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/trackListens.js
  identity-service/test/routes/trackListensTest.js
Labels: size/L

#4934 migrate notification last seen from identity to notification_seen on …
  discovery-provider/alembic/csvs/prod_user_last_notif_seen_results.csv
  discovery-provider/alembic/csvs/staging_user_last_notif_seen_results.csv
  discovery-provider/alembic/versions/02295bdb6bca_migrate_identity_last_seen_notification_.py
Labels: size/XXL

#5028 fix migration revision id
  discovery-provider/alembic/versions/02295bdb6bca_migrate_identity_last_seen_notification_.py
Labels: size/XS

#5017 Wait for libs
  docker-compose.dev.yml
Labels: size/XS

#5029 Add user delist indexing
  creator-node/src/components/contentBlacklist/contentBlacklistComponentService.ts
  creator-node/src/components/contentBlacklist/contentBlacklistController.js
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/alembic/versions/9f5539bdd5bc_user_is_available.py
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/tasks/test_update_track_is_available.py
  discovery-provider/integration_tests/tasks/test_update_user_is_available.py
  discovery-provider/plugins/notifications/src/types/dn.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/app.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/tasks/update_user_is_available.py
  discovery-provider/src/utils/prometheus_metric.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/XXL

#5030 Fix down migration
  discovery-provider/alembic/versions/9f5539bdd5bc_user_is_available.py
Labels: size/XS

#5012 Remove POA contract initializing
  docker-compose.creator.yml
  docker-compose.identity.yml
  libs/src/api/Account.ts
  libs/src/api/Playlist.ts
  libs/src/api/Track.ts
  libs/src/api/Users.test.js
  libs/src/api/Users.ts
  libs/src/data-contracts/signatureSchemas.js
  libs/src/eth-contracts/ABIs/Wormhole.json
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/services/ABIDecoder/AudiusABIDecoder.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/dataContracts/IPLDBlacklistFactoryClient.ts
  libs/src/services/dataContracts/PlaylistFactoryClient.ts
  libs/src/services/dataContracts/RegistryClient.ts
  libs/src/services/dataContracts/SocialFeatureFactoryClient.ts
  libs/src/services/dataContracts/TrackFactoryClient.ts
  libs/src/services/dataContracts/UserFactoryClient.ts
  libs/src/services/dataContracts/UserLibraryFactoryClient.ts
  libs/src/services/dataContracts/UserReplicaSetManagerClient.ts
Labels: size/XXL

#5027 Fix notification plugin image build
  discovery-provider/plugins/notifications/Dockerfile
Labels: size/XS

#5025 Fix push deep link
  discovery-provider/plugins/notifications/Dockerfile
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/tasks/appNotifications.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XL

#5014 [C-2385] Fix track sorting bug
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/src/queries/get_tracks.py
Labels: size/M

#5034 Comms chats/blocked endpoint + check blocks in /validate-can-chat
  comms/Makefile
  comms/discovery/db/queries/get_chat_blocked_users.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  comms/shared/utils/utils.go
  docker-compose.comms.yml
  docker-compose.yml
Labels: size/XL
