Repository AudiusProject/apps, pull requests merged in 2023-06, with the labels that each got.

#5338 Fix DM browser notifs
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/M

#5340 Fix discovery selector usage of latest_chain_block
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#5342 [PLAT-917] Add docker exporter endpoints
  creator-node/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#5314 [PLAT-892] Rename pushNotification fn
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipSend.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/M

#5345 [INF-420] Upgrade eth contracts node to 18
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.test.yml
  eth-contracts/Dockerfile
  eth-contracts/Dockerfile.cacheLedger
  eth-contracts/Dockerfile.dev
  eth-contracts/package-lock.json
  eth-contracts/package.json
Labels: size/M

#5308 [PLAT-1011] Log blocknumber when processing notifications
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
Labels: size/S

#5347 Include delegateOwnerWallet in content node health_check
  discovery-provider/src/tasks/cache_current_nodes.py
Labels: size/XS

#5350 Update add track to playlist notification to handle previous format
  discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/XS

#5285 replace alembic with pg_migrate.sh
  discovery-provider/Dockerfile
  discovery-provider/alembic/env.py
  discovery-provider/alembic/trigger_sql/migrate_agg_playlist.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_playlist_down.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_track.sql
  discovery-provider/alembic/trigger_sql/migrate_agg_user.sql
  discovery-provider/alembic/trigger_sql/migrate_album_playlist_lexeme_dict.sql
  discovery-provider/ddl/README.md
  discovery-provider/ddl/functions/handle_challenge_disbursements.sql
  discovery-provider/ddl/functions/handle_follow.sql
  discovery-provider/ddl/functions/handle_play.sql
  discovery-provider/ddl/functions/handle_playlist.sql
  discovery-provider/ddl/functions/handle_reaction.sql
  discovery-provider/ddl/functions/handle_repost.sql
  discovery-provider/ddl/functions/handle_save.sql
  discovery-provider/ddl/functions/handle_supporter_rank_ups.sql
  discovery-provider/ddl/functions/handle_track.sql
  discovery-provider/ddl/functions/handle_user.sql
  discovery-provider/ddl/functions/handle_user_balance_changes.sql
  discovery-provider/ddl/functions/handle_user_tip.sql
  discovery-provider/ddl/migrations/0000_schema_failable.sql
  discovery-provider/ddl/migrations/0001_old_ddl_file.sql
  discovery-provider/ddl/pg_migrate.sh
  discovery-provider/ddl/preflight/0001_initial_block.sql
  discovery-provider/es-indexer/package.json
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/test_migration_idempotency.py
  discovery-provider/scripts/run-migrations.sh
  discovery-provider/scripts/start.sh
Labels: size/XXL

#5353 Hotfix mediorum /contact, blacklist v2 tracks, and fix hanging on stream
  mediorum/server/delist_statuses.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_contact.go
  mediorum/server/serve_legacy.go
  mediorum/server/server.go
Labels: size/M

#5354 Nerf crudr sweep and pg_beam
  mediorum/crudr/client.go
  mediorum/server/cid_log_server.go
  mediorum/server/serve_crud.go
Labels: size/XS

#5355 Add timeout to mediorum sql, and make batch a queryparam
  mediorum/server/cid_log_client.go
  mediorum/server/cid_log_server.go
  mediorum/server/serve_blob.go
Labels: size/S

#5359 Fix urllib parse
  discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#5227 PLAT-958: paginate scheduled emails
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
Labels: size/L

#5362 Halt stage deploy manually
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
Labels: size/S

#5293 Clean up libs writeMetadataThroughChain flags
  libs/src/api/Account.ts
  libs/src/api/File.ts
  libs/src/api/Track.ts
  libs/src/api/Users.ts
  libs/src/api/entityManager.ts
  libs/src/sanityChecks/addSecondaries.ts
  libs/src/sanityChecks/assignReplicaSetIfNecessary.ts
  libs/src/sanityChecks/index.ts
  libs/src/sanityChecks/rolloverNodes.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/L

#5365 Revert "Halt stage deploy manually (#5362)"
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
Labels: size/S

#5361 [C-2696] Add StorageNodeSelector to sdk
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/Auth/AppAuth.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/constants.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/index.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/utils/network.test.ts
Labels: size/L

#5335 dms healthz matrix date selector for `since`
  comms/discovery/rpcz/apply.go
  monitoring/healthz/src/AudiusSurvivalKit.ts
  monitoring/healthz/src/DMMatrix.tsx
  monitoring/healthz/src/DMs.tsx
  monitoring/healthz/src/useServiceProviders.ts
Labels: size/M

#5352 [CON-734] Add discovery rendezvous and use it in /tracks/:encodedId/stream
  discovery-provider/requirements.txt
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/get_all_other_nodes.py
  discovery-provider/src/utils/rendezvous.py
  discovery-provider/src/utils/rendezvous_unit_test.py
Labels: size/L

#5351 Dedupe log messages in vector config
  monitoring/vector/vector.toml
Labels: size/XS

#5370 Revert comms health checks
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/L

#5364 mediorum cid beam does one peer at a time.
  mediorum/server/cid_log_client.go
  mediorum/server/server.go
Labels: size/M

#5369 [PLAT-997] Drop custom comms & notifs tags
  .circleci/src/jobs/deploy.yml
  comms/bash_scripts/deploy_discovery.sh
  comms/bash_scripts/deploy_stage.sh
Labels: size/S

#5363 [PLAT-1023] Hide announcements for a user before they were created
  discovery-provider/integration_tests/queries/test_notifications/test_announcement_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/M

#5346 [SDK] Rename delegates, grants [C-2616]
  libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  libs/src/sdk/api/grants/GrantsApi.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/EntityManager/types.ts
Labels: size/S

#5344 Rename app delegates, delegations; remove use of shared secret for delegated writes [C-2620] [C-2616]
  discovery-provider/ddl/migrations/0001_old_ddl_file.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/grants/__init__.py
  discovery-provider/src/models/grants/developer_app.py
  discovery-provider/src/models/grants/grant.py
  discovery-provider/src/tasks/entity_manager/app_delegate.py
  discovery-provider/src/tasks/entity_manager/delegation.py
  discovery-provider/src/tasks/entity_manager/developer_app.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/grant.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XXL

#5366 Add Discovery endpoints for developer apps + grants [C-2623]
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/developer_apps.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/developer_apps.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_developer_apps.py
Labels: size/L

#5368 [CON-727] Check Content Nodes for liveness in Discovery
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/utils/get_all_other_nodes.py
  mediorum/server/health.go
Labels: size/M

#5374 Remove storage path migration
  creator-node/src/config.js
  creator-node/src/diskManager.ts
  creator-node/src/index.ts
  creator-node/src/utils/index.ts
  creator-node/src/utils/utils.test.ts
  creator-node/src/utils/utils.ts
Labels: size/XL

#5327 re-enable top_playlists from es with dominant_mood
  discovery-provider/src/queries/get_top_playlists.py
  discovery-provider/src/queries/get_top_playlists_es.py
Labels: size/XS

#5381 [PAY-1395] DMs: Mark chats as read on delete
  comms/discovery/rpcz/chat.go
Labels: size/XS

#5383 Dedupe notifications grouped by action
  discovery-provider/src/queries/get_notifications.py
Labels: size/XS

#5377 mediorum can serve a unified health_check
  mediorum/Dockerfile
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/db.go
  mediorum/server/health.go
  mediorum/server/repair.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_health.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_status.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/transcode.go
  mediorum/server/version.go
Labels: size/L

#5367 DN pull-based trusted notifier
  discovery-provider/build/eth-contracts/TrustedNotifierManager.json
  discovery-provider/ddl/migrations/0001_old_ddl_file.sql
  discovery-provider/ddl/migrations/0002_create_delist_status_tables.sql
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/models/test_aggregate_counters.py
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/integration_tests/queries/test_get_tips.py
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/queries/test_notifications/test_announcement_notification.py
  discovery-provider/integration_tests/tasks/test_update_delist_statuses.py
  discovery-provider/integration_tests/tasks/test_update_track_is_available.py
  discovery-provider/integration_tests/tasks/test_update_user_is_available.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/models/delisting/__init__.py
  discovery-provider/src/models/delisting/delist_status_cursor.py
  discovery-provider/src/models/delisting/track_delist_status.py
  discovery-provider/src/models/delisting/user_delist_status.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_tastemaker_notifications.py
  discovery-provider/src/tasks/update_delist_statuses.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/tasks/update_user_is_available.py
  discovery-provider/src/utils/auth_helpers.py
  discovery-provider/src/utils/eth_contracts_helpers.py
Labels: size/XXL

#5380 [C-2529] Add confirmer to EntityManager in sdk
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/config/development.ts
  libs/src/sdk/config/production.ts
  libs/src/sdk/config/staging.ts
  libs/src/sdk/config/types.ts
  libs/src/sdk/scripts/generateServicesConfig.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/EntityManager/EntityManager.test.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/constants.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5387 [PLAT-1040] Add "Your IP" column
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/S

#5388 repair + replicate handle more edge cases
  mediorum/bash_scripts/deploy_mediorum.sh
  mediorum/server/repair.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#5386 Normalize milestone numbers
  discovery-provider/ddl/functions/handle_play.sql
  discovery-provider/ddl/functions/handle_repost.sql
  discovery-provider/ddl/functions/handle_save.sql
  discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py
Labels: size/S

#5390 Mediorum logs when cid blacklisted, redirected, or served properly
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
Labels: size/S

#5384 Use /health_check for CNs from Discovery and libs
  discovery-provider/integration_tests/tasks/test_update_delist_statuses.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/tasks/update_delist_statuses.py
  discovery-provider/src/utils/get_all_other_nodes.py
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/utils/getNStorageNodes.ts
Labels: size/L

#5392 [PAY-1409] DMs: Include chat_id in push notification
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/M

#5393 Update ChatsApi to use Zod for types and input validation
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
  libs/src/sdk/index.ts
  libs/src/sdk/sdkBrowserDist.ts
  libs/src/sdk/utils/parseRequestParameters.ts
Labels: size/L

#5395 Fix mediorum signature timestamp units
  mediorum/server/serve_blob.go
  mediorum/server/serve_blob_test.go
Labels: size/M

#5396 Switch acdc version to latest working
  discovery-provider/chain/Dockerfile.acdc
Labels: size/XS

#5397 [PLAT-659] Add /chain
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#5343 [PLAT-1026] Sort health check
  discovery-provider/Dockerfile
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/utils.lua
Labels: size/S

#5398 [PLAT-659] Fix metamask sign in
  libs/src/services/web3Manager/Web3Manager.ts
Labels: size/S

#5394 Mediorum pull repair
  mediorum/Makefile
  mediorum/server/health.go
  mediorum/server/peer_health.go
  mediorum/server/placement.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_health.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
Labels: size/XL

#5399 Refactor /contracts & node 18
  contracts/.eslintrc.js
  contracts/.prettierrc.js
  contracts/.soliumrc.json
  contracts/Dockerfile
  contracts/Dockerfile.cacheLedger
  contracts/Dockerfile.dev
  contracts/contract-config.js
  contracts/contracts/DiscoveryProviderFactory.sol
  contracts/contracts/PlaylistFactory.sol
  contracts/contracts/SocialFeatureFactory.sol
  contracts/contracts/TrackFactory.sol
  contracts/contracts/UserReplicaSetManager.sol
  contracts/contracts/interface/SocialFeatureStorageInterface.sol
  contracts/contracts/interface/UserStorageInterface.sol
  contracts/contracts/registry/Registry.sol
  contracts/contracts/registry/RegistryContract.sol
  contracts/contracts/storage/SocialFeatureStorage.sol
  contracts/migrations/3_contracts_migration.js
  contracts/migrations/4_user_replica_set_migration.js
  contracts/migrations/5_entity_manager_migration.js
  contracts/migrations/6_nethermind_entity_manager_migration.js
  contracts/package-lock.json
  contracts/package.json
  contracts/scripts/call-function.sh
  contracts/scripts/circleci-test.sh
  contracts/scripts/lint.sh
  contracts/scripts/nethermind_entity_manager_tx.js
  contracts/scripts/test.sh
  contracts/scripts/truffle-test.sh
  contracts/signature_schemas/signatureSchemas.js
  contracts/test/_lib/artifacts.js
  contracts/test/_lib/testContract.js
  contracts/test/_lib/testPlaylist.js
  contracts/test/_lib/testTrack.js
  contracts/test/_lib/testUser.js
  contracts/test/discoveryProviderFactory.js
  contracts/test/entityManager.js
  contracts/test/playlistFactory.js
  contracts/test/registry.js
  contracts/test/socialFeatureFactory.js
  contracts/test/storage/testStorage.js
  contracts/test/storage/trackStorage.js
  contracts/test/storage/userStorage.js
  contracts/test/trackFactory.js
  contracts/test/userFactory.js
  contracts/test/userLibrary.js
  contracts/test/userReplicaSetManager.js
  contracts/test/utils/constants.js
  contracts/test/utils/getters.js
  contracts/test/utils/parser.js
  contracts/test/utils/util.js
  contracts/test/utils/validator.js
  contracts/truffle-config.js
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/startup/poa-ganache.sh
  eth-contracts/migrations/11_eth_rewards_manager_migration.js
  eth-contracts/truffle-config.js
  libs/initScripts/local.js
  libs/scripts/addCIDToIpldBlacklist.js
Labels: size/XXL

#5404 Add developer app endpoints to swagger docs
  discovery-provider/src/api/v1/developer_apps.py
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5405 DMs: Fix health error output
  comms/discovery/rpcz/apply.go
Labels: size/XS

#5403 [C-2727] Add deleteTrack to sdk
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5341 PLAT-983 pedalboard turborepo
  .circleci/src/workflows/discovery.yml
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.pedalboard.yml
  dev-tools/compose/docker-compose.yml
  discovery-provider/plugins/pedalboard/.dockerignore
  discovery-provider/plugins/pedalboard/.eslintrc.js
  discovery-provider/plugins/pedalboard/.gitignore
  discovery-provider/plugins/pedalboard/README.md
  discovery-provider/plugins/pedalboard/apps/app-template/.eslintrc.js
  discovery-provider/plugins/pedalboard/apps/app-template/package.json
  discovery-provider/plugins/pedalboard/apps/app-template/src/index.ts
  discovery-provider/plugins/pedalboard/apps/app-template/tsconfig.json
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/.eslintrc.js
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/package.json
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/config.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/index.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/libs.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/server.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/utils.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/tsconfig.json
  discovery-provider/plugins/pedalboard/docker-compose.yml
  discovery-provider/plugins/pedalboard/docker/Dockerfile
  discovery-provider/plugins/pedalboard/package-lock.json
  discovery-provider/plugins/pedalboard/package.json
  discovery-provider/plugins/pedalboard/packages/basekit/.eslintrc.js
  discovery-provider/plugins/pedalboard/packages/basekit/package.json
  discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts
  discovery-provider/plugins/pedalboard/packages/basekit/src/index.ts
  discovery-provider/plugins/pedalboard/packages/basekit/tsconfig.json
  discovery-provider/plugins/pedalboard/packages/eslint-config-custom-server/index.js
  discovery-provider/plugins/pedalboard/packages/eslint-config-custom-server/package.json
  discovery-provider/plugins/pedalboard/packages/eslint-config-custom/index.js
  discovery-provider/plugins/pedalboard/packages/eslint-config-custom/package.json
  discovery-provider/plugins/pedalboard/packages/jest-presets/jest/node/jest-preset.js
  discovery-provider/plugins/pedalboard/packages/jest-presets/package.json
  discovery-provider/plugins/pedalboard/packages/logger/.eslintrc.js
  discovery-provider/plugins/pedalboard/packages/logger/package.json
  discovery-provider/plugins/pedalboard/packages/logger/src/index.ts
  discovery-provider/plugins/pedalboard/packages/logger/tsconfig.json
  discovery-provider/plugins/pedalboard/packages/storage/.eslintrc.js
  discovery-provider/plugins/pedalboard/packages/storage/package.json
  discovery-provider/plugins/pedalboard/packages/storage/src/gen.ts
  discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  discovery-provider/plugins/pedalboard/packages/storage/tsconfig.json
  discovery-provider/plugins/pedalboard/packages/tsconfig/README.md
  discovery-provider/plugins/pedalboard/packages/tsconfig/base.json
  discovery-provider/plugins/pedalboard/packages/tsconfig/nextjs.json
  discovery-provider/plugins/pedalboard/packages/tsconfig/package.json
  discovery-provider/plugins/pedalboard/packages/tsconfig/react-library.json
  discovery-provider/plugins/pedalboard/publish-tcr.sh
  discovery-provider/plugins/pedalboard/tsconfig.json
  discovery-provider/plugins/pedalboard/turbo.json
Labels: size/XXL

#5323 Remove fetch_cid_metadata in indexer
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/challenges/index_helpers.py
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_notification.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_ursm_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/tasks/backfill_cid_data.py
  discovery-provider/src/tasks/entity_manager/developer_app.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/grant.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/user_replica_set_unit_test.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/utils/cid_metadata_client.py
  discovery-provider/src/utils/prometheus_metric.py
  discovery-provider/src/utils/structured_logger.py
Labels: size/XXL

#5407 Gen API for developer apps
  libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  libs/src/sdk/api/generated/default/.openapi-generator/FILES
  libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  libs/src/sdk/api/generated/default/apis/DeveloperAppsApi.ts
  libs/src/sdk/api/generated/default/apis/TracksApi.ts
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/default/apis/index.ts
  libs/src/sdk/api/generated/default/models/AuthorizedApp.ts
  libs/src/sdk/api/generated/default/models/AuthorizedApps.ts
  libs/src/sdk/api/generated/default/models/DeveloperApp.ts
  libs/src/sdk/api/generated/default/models/DeveloperApps.ts
  libs/src/sdk/api/generated/default/models/User.ts
  libs/src/sdk/api/generated/default/models/index.ts
  libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/sdk/api/generated/full/models/UserFull.ts
Labels: size/XXL

#5409 Better notifications plugin logs
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/sns.ts
  discovery-provider/plugins/notifications/src/tasks/appNotifications.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/web.ts
Labels: size/L

#5413 Fix params reference before assignment follow on
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#5410 [CON-744] Update mediorum health_check and healthz
  dev-tools/compose/docker-compose.storagev2.yml
  mediorum/crudr/crudr.go
  mediorum/server/monitor.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
  monitoring/healthz/src/Mediorum.tsx
Labels: size/L

#5389 Fix is signer in healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XS

#5416 Improve DM logging
  comms/discovery/config/config.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/peer_client.go
  comms/discovery/server/server.go
  monitoring/healthz/src/DMMatrix.tsx
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/index.css
  monitoring/healthz/src/query.ts
  monitoring/healthz/src/useServiceProviders.ts
Labels: size/M

#5417 [Discovery API] Check if developer app was found before trying to format it
  discovery-provider/src/api/v1/developer_apps.py
Labels: size/XS

#5421 Fix name collision with developer_app schema
  discovery-provider/src/api/v1/developer_apps.py
Labels: size/XS

#5419 Add question mark
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#5423 Fix developer-app generated sdk types
  libs/src/sdk/api/generated/default/.openapi-generator/FILES
  libs/src/sdk/api/generated/default/apis/DeveloperAppsApi.ts
  libs/src/sdk/api/generated/default/models/DeveloperApp.ts
  libs/src/sdk/api/generated/default/models/DeveloperAppResponse.ts
  libs/src/sdk/api/generated/default/models/index.ts
Labels: size/L

#5425 Add rendezvous to healthz and use (lowercase) hosts
  discovery-provider/src/api/v1/tracks.py
  libs/src/api/ServiceProvider.ts
  libs/src/sdk/index.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/utils/getNStorageNodes.ts
  libs/src/utils/rendezvous.ts
  mediorum/crudr/client.go
  mediorum/crudr/crudr.go
  mediorum/ethcontracts/ethcontracts.go
  mediorum/httputil/httputil.go
  mediorum/main.go
  mediorum/registrar/the_graph.go
  mediorum/server/peer_health.go
  monitoring/healthz/index.html
  monitoring/healthz/package-lock.json
  monitoring/healthz/package.json
  monitoring/healthz/src/Rendezvous.tsx
  monitoring/healthz/src/Router.tsx
  monitoring/healthz/vite.config.ts
Labels: size/L

#5429 Bump libs version in healthz and deploy
  monitoring/healthz/package-lock.json
  monitoring/healthz/package.json
Labels: size/XS

#5391 Verify ownership of developer app wallet C-2528
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/requirements.txt
  discovery-provider/src/tasks/entity_manager/developer_app.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#5428 [INF-423] Fix sdk gen with audius-compose
  libs/src/sdk/api/generator/gen.js
Labels: size/XS

#5431 Show mediorum healthy nodes in the last 5min
  monitoring/healthz/src/Mediorum.tsx
Labels: size/S

#5415 [PAY-1341] Add optional currentUserId to every chats request
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/utils/parseRequestParameters.ts
Labels: size/L

#5426 [PLAT-1044] Trim down eth web3 usage in discovery
  discovery-provider/integration_tests/queries/test_get_attestation.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/confirm_indexing_transaction_error.py
  discovery-provider/src/queries/get_attestation.py
  discovery-provider/src/queries/get_authed_user.py
  discovery-provider/src/queries/get_redirect_weights.py
  discovery-provider/src/tasks/cache_user_balance.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  discovery-provider/src/utils/eth_manager.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/L

#5434 CurrentUserId should be optional for listen()
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/S

#5435 Fix file location
  discovery-provider/src/tasks/update_clique_signers.py
Labels: size/XS

#5436 Add celery test
  discovery-provider/integration_tests/test_celery.py
  discovery-provider/src/tasks/index_eth.py
Labels: size/S

#5433 [CON-746] Improve content node usage of eth rpc
  creator-node/src/services/ContentNodeInfoManager.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/snapbackSM.js
  libs/src/api/ServiceProvider.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
Labels: size/L

#5437 [PLAT-1044] Reduce identity eth rpc usage
  identity-service/src/notifications/index.js
  identity-service/src/notifications/trendingTrackProcessing.js
  identity-service/test/index.js
  identity-service/test/processNotifications/trendingTrackNotification.js
  identity-service/test/sendNotifications/getEmailNotifications.js
  identity-service/test/sendNotifications/index.js
Labels: size/XXL

#5432 Fix DN polling of TN
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/update_delist_statuses.py
  discovery-provider/src/utils/prometheus_metric.py
  discovery-provider/src/utils/redis_constants.py
Labels: size/L

#5438 Remove remaining entity mgr flags
  identity-service/src/config.js
  identity-service/src/routes/healthCheck.js
  identity-service/src/routes/relay.js
Labels: size/S

#5441 Revert "Revert comms health checks (#5370)"
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/L

#5440 DMs: handle delayed messages deterministically
  comms/Dockerfile
  comms/DockerfileFast
  comms/Makefile
  comms/README.md
  comms/discovery/db/migrations/20221128164712_create_rpc_log_table.sql
  comms/discovery/db/migrations/20221130042018_create_pubkey_table.sql
  comms/discovery/db/migrations/20221130171438_drop_pubkey_table.sql
  comms/discovery/db/migrations/20221202144236_create_chat.sql
  comms/discovery/db/migrations/20221210021301_create_chat_permissions.sql
  comms/discovery/db/migrations/20221212074228_create_chat_blocked_users.sql
  comms/discovery/db/migrations/20221212081249_create_chat_message_reactions.sql
  comms/discovery/db/migrations/20221222050259_add_rpc_log_pk.sql
  comms/discovery/db/migrations/20230117200411_add_chat_last_message.sql
  comms/discovery/db/migrations/20230224160015_chat_indexes.sql
  comms/discovery/db/migrations/20230316193251_pubkey_table.sql
  comms/discovery/db/migrations/20230328011841_rpc_relayed_by.sql
  comms/discovery/db/migrations/20230328185322_rpc_applied_at.sql
  comms/discovery/db/migrations/20230328193145_rpc_applied_at_not_null.sql
  comms/discovery/db/migrations/20230329192212_rpc_cursor.sql
  comms/discovery/db/migrations/20230605185932_chat_ban.sql
  comms/discovery/db/run_migrations.go
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_block_test.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/chat_test.go
  comms/discovery/server/server_test.go
  comms/docker-compose.test.yml
  dev-tools/compose/docker-compose.discovery.yml
  discovery-provider/ddl/migrations/0003_dm_migrations.sql
Labels: size/L

#5442 Revert "DMs: handle delayed messages deterministically (#5440)"
  comms/Dockerfile
  comms/DockerfileFast
  comms/Makefile
  comms/README.md
  comms/discovery/db/migrations/20221128164712_create_rpc_log_table.sql
  comms/discovery/db/migrations/20221130042018_create_pubkey_table.sql
  comms/discovery/db/migrations/20221130171438_drop_pubkey_table.sql
  comms/discovery/db/migrations/20221202144236_create_chat.sql
  comms/discovery/db/migrations/20221210021301_create_chat_permissions.sql
  comms/discovery/db/migrations/20221212074228_create_chat_blocked_users.sql
  comms/discovery/db/migrations/20221212081249_create_chat_message_reactions.sql
  comms/discovery/db/migrations/20221222050259_add_rpc_log_pk.sql
  comms/discovery/db/migrations/20230117200411_add_chat_last_message.sql
  comms/discovery/db/migrations/20230224160015_chat_indexes.sql
  comms/discovery/db/migrations/20230316193251_pubkey_table.sql
  comms/discovery/db/migrations/20230328011841_rpc_relayed_by.sql
  comms/discovery/db/migrations/20230328185322_rpc_applied_at.sql
  comms/discovery/db/migrations/20230328193145_rpc_applied_at_not_null.sql
  comms/discovery/db/migrations/20230329192212_rpc_cursor.sql
  comms/discovery/db/migrations/20230605185932_chat_ban.sql
  comms/discovery/db/run_migrations.go
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_block_test.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/chat_test.go
  comms/discovery/server/server_test.go
  comms/docker-compose.test.yml
  dev-tools/compose/docker-compose.discovery.yml
  discovery-provider/ddl/migrations/0003_dm_migrations.sql
Labels: size/L

#5424 Include actual emojis in message reaction push notifs
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
Labels: size/S

#5444 Make 1033 faster
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#5420 Add rate limiting to relays
  identity-service/relay-rate-limit.json
  identity-service/src/app.js
  identity-service/src/config.js
  identity-service/src/rateLimiter.js
  identity-service/src/routes/relay.js
  identity-service/test/relayTest.js
Labels: size/L

#5430 [SDK] Fix Create Dev App to match EM changes; use Zod for validation - Grants/Developer Apps
  libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  libs/src/sdk/api/developer-apps/constants.ts
  libs/src/sdk/api/developer-apps/types.ts
  libs/src/sdk/api/grants/GrantsApi.ts
  libs/src/sdk/api/grants/constants.ts
  libs/src/sdk/api/grants/types.ts
  libs/src/sdk/services/Auth/AppAuth.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/utils/file.ts
Labels: size/L

#5445 DMs: handle delayed messages deterministically (fix)
  comms/Dockerfile
  comms/DockerfileFast
  comms/Makefile
  comms/README.md
  comms/discovery/db/migrations/20221128164712_create_rpc_log_table.sql
  comms/discovery/db/migrations/20221130042018_create_pubkey_table.sql
  comms/discovery/db/migrations/20221130171438_drop_pubkey_table.sql
  comms/discovery/db/migrations/20221202144236_create_chat.sql
  comms/discovery/db/migrations/20221210021301_create_chat_permissions.sql
  comms/discovery/db/migrations/20221212074228_create_chat_blocked_users.sql
  comms/discovery/db/migrations/20221212081249_create_chat_message_reactions.sql
  comms/discovery/db/migrations/20221222050259_add_rpc_log_pk.sql
  comms/discovery/db/migrations/20230117200411_add_chat_last_message.sql
  comms/discovery/db/migrations/20230224160015_chat_indexes.sql
  comms/discovery/db/migrations/20230316193251_pubkey_table.sql
  comms/discovery/db/migrations/20230328011841_rpc_relayed_by.sql
  comms/discovery/db/migrations/20230328185322_rpc_applied_at.sql
  comms/discovery/db/migrations/20230328193145_rpc_applied_at_not_null.sql
  comms/discovery/db/migrations/20230329192212_rpc_cursor.sql
  comms/discovery/db/migrations/20230605185932_chat_ban.sql
  comms/discovery/db/run_migrations.go
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_block_test.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/chat_test.go
  comms/discovery/server/server_test.go
  comms/docker-compose.test.yml
  dev-tools/compose/docker-compose.discovery.yml
  discovery-provider/ddl/migrations/0003_dm_migrations.sql
Labels: size/L

#5446 comms derives wallet address from private key
  comms/discovery/config/config.go
  comms/discovery/config/constants.go
  comms/discovery/discovery_main.go
  comms/discovery/server/basic_auth.go
  comms/discovery/server/server.go
Labels: size/M

#5447 compute wallet address from private key
  mediorum/ethcontracts/compute_address.go
  mediorum/httputil/httputil.go
  mediorum/main.go
  mediorum/server/serve_health.go
  mediorum/server/server.go
  mediorum/server/server_basic_auth.go
Labels: size/L

#5448 audius-cmd v2 edit track
  dev-tools/commands/src/edit-track.mjs
  dev-tools/commands/src/index.mjs
Labels: size/M

#5443 PLAT-992: compose friday tweet
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/server.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts
  discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts
Labels: size/L

#5449 DN TN discrepancies endpoint
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_trusted_notifier_discrepancies.py
  discovery-provider/src/queries/health_check.py
Labels: size/L

#5451 populate relayed_by and relayed_at (if missing)
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat_test.go
Labels: size/S

#5408 Index single tx signup
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
Labels: size/M

#5454 retrun 506 from health_check if wallet not registered
  mediorum/server/serve_health.go
Labels: size/XS

#5439 [PLAT-932] Add exception logs to triggers
  discovery-provider/ddl/functions/handle_challenge_disbursements.sql
  discovery-provider/ddl/functions/handle_follow.sql
  discovery-provider/ddl/functions/handle_play.sql
  discovery-provider/ddl/functions/handle_playlist.sql
  discovery-provider/ddl/functions/handle_reaction.sql
  discovery-provider/ddl/functions/handle_repost.sql
  discovery-provider/ddl/functions/handle_save.sql
  discovery-provider/ddl/functions/handle_supporter_rank_ups.sql
  discovery-provider/ddl/functions/handle_track.sql
  discovery-provider/ddl/functions/handle_user.sql
  discovery-provider/ddl/functions/handle_user_balance_changes.sql
  discovery-provider/ddl/functions/handle_user_tip.sql
Labels: size/L

#5453 upgrade node version for notifications
  discovery-provider/plugins/notifications/Dockerfile
Labels: size/XS

#5458 Mediorum fix health panic
  mediorum/ddl/ddl.go
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/repair.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
Labels: size/M

#5456 Single transaction sign up
  discovery-provider/src/tasks/entity_manager/user.py
  libs/src/api/Account.ts
  libs/src/api/Users.ts
Labels: size/M

#5460 audius-cmd follow and unfollow
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/follow.mjs
  dev-tools/commands/src/unfollow.mjs
Labels: size/S

#5455 Add Write OAuth helpers to SDK C-2784
  libs/package.json
  libs/src/sdk/api/developer-apps/types.ts
  libs/src/sdk/api/grants/types.ts
  libs/src/sdk/oauth/OAuth.ts
  libs/src/sdk/oauth/index.ts
  libs/src/sdk/oauth/types.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/utils/apiKey.ts
  libs/src/sdk/utils/file.ts
  libs/src/sdk/utils/oauthScope.ts
Labels: size/L

#5452 creatorNodeVersionOverride env var
  creator-node/src/components/healthCheck/healthCheckComponentService.js
Labels: size/XS

#5461 audius-cmd create and update playlists
  dev-tools/commands/src/create-playlist.mjs
  dev-tools/commands/src/edit-playlist.mjs
  dev-tools/commands/src/edit-track.mjs
  dev-tools/commands/src/index.mjs
Labels: size/M

#5459 Use relay rate limit custom handler and send json
  identity-service/src/apiHelpers.js
  identity-service/src/rateLimiter.js
  identity-service/src/routes/relay.js
Labels: size/M

#5400 [PLAT-1033] Linear indexer
  discovery-provider/ddl/pg_migrate.sh
  discovery-provider/ddl/preflight/0001_initial_block.sql
  discovery-provider/integration_tests/challenges/index_helpers.py
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_notification.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_ursm_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/tasks/test_index_nethermind.py
  discovery-provider/integration_tests/test_celery.py
  discovery-provider/integration_tests/test_migration_idempotency.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/queries/index_block_stats.py
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  discovery-provider/src/tasks/entity_manager/entities/grant.py
  discovery-provider/src/tasks/entity_manager/entities/notification.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entities/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/entities/user_replica_set_unit_test.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user_unit_test.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_latest_block.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/sort_block_transactions.py
  discovery-provider/src/tasks/sort_block_transactions_unit_test.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/index_blocks_performance.py
  discovery-provider/src/utils/indexing_errors.py
  discovery-provider/src/utils/structured_logger.py
Labels: size/XXL

#5462 burst rate limit for chat messages
  comms/discovery/rpcz/rate_limit_test.go
  comms/discovery/rpcz/validator.go
  discovery-provider/ddl/migrations/0004_chat_message_index.sql
Labels: size/M

#5469 DM: validate host + wallet pair
  comms/discovery/discovery_main.go
Labels: size/M

#5471 Revert single tx signup in libs
  libs/src/api/Account.ts
  libs/src/api/Users.ts
Labels: size/M

#5472 SDK: Don't check comms API response health
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/S

#5467 Use album repost/save types and fix aggregate playlist counts
  discovery-provider/ddl/migrations/0004_fix_save_repost_album_type.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
  discovery-provider/src/tasks/update_aggregates.py
Labels: size/L

#5473 SDK: Temporarily disable comms api response test
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
Labels: size/M

#5475 Fix social feature test
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
Labels: size/XS

#5476 pull is_healthy logic into func
  comms/discovery/server/server.go
Labels: size/XS

#5474 [PLAT-861] allow empty string for user bios in em indexing
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/L

#5464 [PLAT-1078] Add sla-auditor plugin
  discovery-provider/plugins/pedalboard/README.md
  discovery-provider/plugins/pedalboard/apps/sla-auditor/.eslintrc.js
  discovery-provider/plugins/pedalboard/apps/sla-auditor/package.json
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/index.ts
  discovery-provider/plugins/pedalboard/apps/sla-auditor/tsconfig.json
  discovery-provider/plugins/pedalboard/docker-compose.yml
  discovery-provider/plugins/pedalboard/package-lock.json
Labels: size/M

#5485 Bump update_delist_statuses log level on error when updating DN db
  discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/XS

#5486 Fix cached node retrieval
  discovery-provider/integration_tests/queries/test_get_attestation.py
  discovery-provider/src/queries/confirm_indexing_transaction_error.py
  discovery-provider/src/queries/get_attestation.py
  discovery-provider/src/queries/get_redirect_weights.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/update_clique_signers.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/M

#5489 Backfill missing metrics
  discovery-provider/ddl/migrations/0005_backfill_unsynced_metrics.sql
Labels: size/M

#5490 [C-2765] Add is_image_autogenerated playlist column
  discovery-provider/ddl/migrations/0006_add_is_image_autogenerated.sql
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/playlists/playlist.py
  discovery-provider/src/schemas/playlist_schema.json
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/metadata.py
  libs/src/services/schemaValidator/schemas/playlistSchema.json
  libs/src/utils/types.ts
Labels: size/L

#5491 Upgrade sdk in js content node
  creator-node/package-lock.json
  creator-node/package.json
Labels: size/XS

#5463 Mediorum no health broadcast
  mediorum/crudr/crudr.go
  mediorum/ddl/ddl.go
  mediorum/server/db.go
  mediorum/server/health.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_health.go
  mediorum/server/server.go
Labels: size/M

#5465 repair under-replicated blobs in cleanup mode
  mediorum/server/repair.go
  mediorum/server/repair_test.go
Labels: size/M

#5494 fix bad merge
  mediorum/server/repair.go
  mediorum/server/repair_test.go
Labels: size/S

#5487 Change DM notifs back to default on
  identity-service/sequelize/migrations/20230626231334-default-messages-on-mobile-notification-settings.js
  identity-service/sequelize/migrations/20230626231346-default-messages-on-browser-notification-settings.js
  identity-service/src/models/userNotificationBrowserSettings.js
  identity-service/src/models/userNotificationMobileSettings.js
Labels: size/M

#5493 validate in mutate endpoint
  comms/discovery/rpcz/apply.go
  comms/discovery/server/main_test.go
Labels: size/S

#5470 Enforce limit 3 apps per user EM side C-2749
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
Labels: size/M

#5495 make wallet user_id lookup deterministic
  comms/discovery/db/queries/get_users.go
  comms/discovery/server/mutate_test.go
  comms/discovery/server/server_test.go
Labels: size/S

#5478 [plat-1085] do not persist save and favorites of hidden tracks and collections
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
Labels: size/M

#5484 Add reverts for grant and dev apps
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#5488 EntityManager event and app structured logs
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/utils/structured_logger.py
Labels: size/M

#5480 Handle indexing validation exception
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/exceptions.py
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  discovery-provider/src/tasks/entity_manager/entities/grant.py
  discovery-provider/src/tasks/entity_manager/entities/notification.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entities/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/entities/user_unit_test.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#5497 [PLAT-1087] Free up cycles when block not found for 500ms
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/XS

#5499 Send response when EM rate limited
  identity-service/src/rateLimiter.js
Labels: size/S

#5477 minor adjustments to trending plugin
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts
Labels: size/S

#5418 [C-2726] Add updateTrack to sdk
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/index.ts
  libs/src/sdk/utils/parseRequestParameters.ts
  sdk-consumer/index.ts
Labels: size/L

#5501 Fix discovery test conflict with validation error
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
Labels: size/XS

#5502 [C-2808] Add getNodes to StorageNodeSelector
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/WebAudiusLibs.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
  libs/src/sdk/services/index.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/L

#5500 [PLAT-1086] Log cleanup
  discovery-provider/scripts/start.sh
  discovery-provider/src/challenges/challenge_event_bus.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_solana_plays.py
Labels: size/S

#5503 [C-2808] Make getNodes not async
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/WebAudiusLibs.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
Labels: size/M

#5507 DMs: chat create ordering
  comms/Makefile
  comms/discovery/db/conn.go
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/rpcz/peer_client.go
  comms/discovery/rpcz/validator.go
  comms/discovery/server/server.go
  comms/go.mod
  comms/go.sum
  comms/main.go
  comms/shared/signing/signed_request.go
  monitoring/healthz/src/DMMatrix.tsx
Labels: size/L

#5506 0.4.0
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#5509 update DM health panel
  monitoring/healthz/package-lock.json
  monitoring/healthz/src/DMs.tsx
  monitoring/healthz/src/Mediorum.tsx
Labels: size/M

#5510 Fix linear indexer for local state
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#5511 [PAY-1554] Change to less scary error message on decryption failure
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/XS

#5512 Do not destroy mobile settings when deregistering device token
  identity-service/src/routes/push_notifications.js
Labels: size/S

#5492 PLAT-1096: use for loop instead of callbacks
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
Labels: size/L

#5508 PLAT-1063: docker caching issues
  creator-node/src/app.ts
  dev-tools/audius-compose
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/src/app.py
  identity-service/src/app.js
Labels: size/XS

#5514 Revert "0.4.0 (#5506)"
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#5517 DMs: better retry mechanism
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/rpcz/peer_client.go
  comms/discovery/rpcz/peer_client_test.go
  comms/discovery/rpcz/rate_limit_test.go
  comms/discovery/rpcz/test_utils.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  discovery-provider/ddl/migrations/0007_dm_chat_member_created_at.sql
  discovery-provider/ddl/migrations/0008_rpc_log_error.sql
Labels: size/L

#5498 Fix app limit check [EM] C-2805
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
Labels: size/L
