Repository AudiusProject/apps, pull requests merged in 2023-04, with the labels that each got.

#5037 Refactor permissions and blocks endpoints
  comms/discovery/db/queries/get_chat_blocked_users.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  comms/shared/utils/utils.go
Labels: size/XL

#5039 SDK: Snake case DN selector services key
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
Labels: size/S

#5041 SDK: Add getBlockers(), getBlockees(), unfurl(), and getPermissions()
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/M

#5043 Fix discover-node-selector response
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/XS

#5044 SDK: Chat unblocking
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#5031 PLAT-761: filter response by correct playlist visibilty
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/src/queries/get_playlist_tracks.py
Labels: size/L

#5050 Upgrade identity SDK 2.0.3-beta.4
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#5051 Add notifs proxy pass
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#5048 Add selectionCallback to sdk discovery-node-selector
  libs/src/api/Track.ts
  libs/src/api/Users.test.js
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/dataContracts/AudiusContracts.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/utils/fileHasher.ts
Labels: size/L

#5055 SDK: Type error on Chat Permits
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/XS

#5054 Fix /notifications proxy pass
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#5046 Send metadata blobs through chain
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/utils/cid_metadata_client.py
  identity-service/src/relay/txRelay.js
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/XL

#5052 Allow health check when no sp id
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts
Labels: size/XS

#5049 Remove blocks_copy table
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/XS

#5033 [PAY-1116] - Prevent ipfs route from streaming mp3
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/is-mp3.d.ts
  creator-node/src/routes/files.js
  creator-node/src/utils/fileUtils.ts
  creator-node/src/utils/index.ts
  creator-node/test/contentBlacklist.test.js
Labels: size/L

#5040 Update aggregates to increment + a job to recalculate
  discovery-provider/alembic/trigger_sql/handle_follow.sql
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/integration_tests/tasks/test_update_aggregates.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/update_aggregates.py
  libs/package-lock.json
Labels: size/XL

#5047 routes to serve a "legacy" CID
  mediorum/bash_scripts/deploy_mediorum.sh
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/beam_client.go
  mediorum/server/repair_test.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_pg_beam.go
  mediorum/server/server.go
Labels: size/L

#5063 Add lowercase check
  creator-node/src/contentAccess/helpers.ts
Labels: size/XS

#5059 Libs changes to read metadata from DNs
  discovery-provider/default_config.ini
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  libs/src/api/File.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/M

#5061 Fix user query filter
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/tasks/update_aggregates.py
Labels: size/S

#5068 Lower replica set updates 10x
  creator-node/src/config.js
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
Labels: size/XS

#5067 Revert playlist seen
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#5069 prod: only start on subset of hosts, tag docker image with git sha.
  mediorum/Makefile
  mediorum/main.go
Labels: size/S

#5066 Revert "[PAY-1116] - Prevent ipfs route from streaming mp3 (#5033)"
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/is-mp3.d.ts
  creator-node/src/routes/files.js
  creator-node/src/utils/fileUtils.ts
  creator-node/src/utils/index.ts
  creator-node/test/contentBlacklist.test.js
Labels: size/L

#5058 Skip track propagation
  creator-node/src/blacklistManager.js
Labels: size/S

#5065 [PLAT-828]: Refactor user notification settings notification plugin and check user is abusive
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/userNotificationSettings.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipSend.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  discovery-provider/plugins/notifications/src/sns.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XXL

#5073 Clean up CN nginx and don't serve stale /health_check
  creator-node/nginx_conf/nginx.conf
Labels: size/S

#5076 Add forwarded for to identity logs
  identity-service/src/logging.js
Labels: size/XS

#5077 Fix duplicate track create notifications
  identity-service/src/notifications/processNotifications/createNotification.js
Labels: size/XS

#5078 Add request-ip package
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/routes/healthCheck.js
Labels: size/XS

#5080 plat 831: return early on unlisted tracks
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
Labels: size/S

#5045 Add backfill for more track_cids
  discovery-provider/alembic/csvs/missing_track_cid_40323.csv
  discovery-provider/alembic/versions/97a9e89c802f_40323_track_cids.py
Labels: size/L

#5081 Integrate storage v2 metadata and /tracks/cidstream
  creator-node/nginx_conf/nginx.conf
  libs/src/api/Track.ts
  libs/src/services/creatorNode/CreatorNode.ts
  mediorum/server/server.go
  nginx_ingress.conf
Labels: size/M

#5084 Respect AAO rule #17
  identity-service/src/utils/antiAbuse.js
Labels: size/XS

#5062 Mediorum remove sqlite, use postgres
  comms/nginx/ingress.conf
  dev-tools/startup/initdb/02_dbs.sql
  docker-compose.comms.yml
  docker-compose.storagev2.yml
  docker-compose.yml
  mediorum/.initdb/init.sql
  mediorum/Makefile
  mediorum/Procfile
  mediorum/README.md
  mediorum/crudr/crudr.go
  mediorum/crudr/setup_test_db.go
  mediorum/docker-compose.yml
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/db.go
  mediorum/server/health.go
  mediorum/server/repair.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
  nginx_ingress.conf
Labels: size/XL

#5075 [PAY-827][PAY-1115] Always use cid streaming and include filename in redirect if exists
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_track_stream_signature.py
Labels: size/M

#5087 Add mocha type and pin deps in identity
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/L

#5086 [PLAT-868]: Swap supporter rank up vs supporting rank up notifications in trigger
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql
  discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/src/models/notifications/notification.py
Labels: size/M

#5090 update test push notification script to send android notifs
  discovery-provider/plugins/notifications/scripts/test-push-notification.ts
Labels: size/L

#5092 Fix android push notif message struct
  discovery-provider/plugins/notifications/src/sns.ts
Labels: size/XS

#5085 Add flag to disable logging
  monitoring/vector/start.sh
Labels: size/S

#5074 remove sse server
  mediorum/Makefile
  mediorum/crudr/broadcast.go
  mediorum/crudr/client.go
  mediorum/crudr/crudr.go
  mediorum/crudr/crudr_test.go
  mediorum/crudr/op.go
  mediorum/crudr/setup_test_db.go
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/db.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_sync.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
  mediorum/server/uis/upload.html
Labels: size/L

#5057 Update release-audius-docker-compose to respect `dev` and reconcile state
  .circleci/jobs/release-audius-docker-compose.yml
Labels: size/S

#5095 Mediorum hostname
  docker-compose.storagev2.yml
  mediorum/main.go
  nginx_ingress.conf
Labels: size/L

#5096 Fix clone command in ci
  .circleci/jobs/release-audius-docker-compose.yml
Labels: size/XS

#5098 remove log
  discovery-provider/plugins/verified-uploads/src/db.js
Labels: size/XS

#5088 Add storage v2 signup flow without replica sets
  dev-tools/audius-compose
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/schemas/user_schema.json
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/tasks/metadata.py
  discovery-provider/src/utils/helpers.py
  docker-compose.creator.yml
  docker-compose.storagev2.yml
  docker-compose.yml
  identity-service/src/authMiddleware.js
  libs/package-lock.json
  libs/package.json
  libs/src/api/Account.ts
  libs/src/api/Users.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
  libs/src/utils/fileHasher.ts
  libs/src/utils/types.ts
  nginx_ingress.conf
Labels: size/L

#5099 Fix trigger_sql missing commit
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/XS

#5100 Make notif migration use temp step
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/S

#5097 mediorum first with fallback reverse proxy to nodejs server.
  mediorum/bash_scripts/deploy_mediorum.sh
  mediorum/crudr/broadcast.go
  mediorum/crudr/client.go
  mediorum/crudr/crudr.go
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/db.go
  mediorum/server/helpers.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/signature/signature.go
  mediorum/server/signature/signature_test.go
  mediorum/server/start_crud_clients.go
  mediorum/server/uis/upload.html
Labels: size/XL

#5101 Misc DMs
  comms/discovery/db/queries/get_chat_permissions.go
  comms/discovery/db/queries/get_chats.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/validator.go
  comms/discovery/schema/schema.go
  comms/discovery/schema/schema.ts
  comms/discovery/server/response_mapper.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  identity-service/sequelize/migrations/20230127023810-add-messages-to-mobile-notification-settings.js
  identity-service/sequelize/migrations/20230415023159-change-default-messages-mobile-notification-settings.js
  identity-service/sequelize/migrations/20230415023208-change-default-messages-browser-notification-settings.js
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#5107 Add retries to instagram profile fetch
  identity-service/src/routes/instagram.js
Labels: size/M

#5093 Email notifs in notification plugin
  discovery-provider/plugins/notifications/jest.config.js
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/tasks/appNotifications.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  identity-service/src/notifications/sendNotificationEmails.js
  identity-service/src/remoteConfig.js
Labels: size/XXL

#5110 Show how long ws was connected.
  monitoring/healthz/src/DMs.tsx
Labels: size/M

#5114 Update README.md to include audius-compose examples
  dev-tools/README.md
Labels: size/S

#5113 Update discovery-provider README.md
  discovery-provider/README.md
Labels: size/XS

#5109 Set is_playlist_upload correctly in EM
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#5106 Remove join on userbank in undisbursed challenges endpoint
  discovery-provider/src/queries/get_undisbursed_challenges.py
Labels: size/XS

#5116 Temporarily enable client listen requests in identity
  identity-service/src/routes/trackListens.js
Labels: size/S

#5112 Es numbers
  discovery-provider/es-indexer/src/conn.ts
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/types/docs.ts
Labels: size/M

#5035 Add CI env to freeze staging deploys
  .circleci/jobs/deploy.yml
  .circleci/workflows/main.yml
Labels: size/M

#5108 [PAY-1161] Add human-readable balance to users API
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/utils/helpers.py
Labels: size/S

#5118 fix pubkey recover for acdc prod
  comms/discovery/pubkeystore/recover.go
  comms/discovery/pubkeystore/recover_add_user.go
  comms/discovery/pubkeystore/recover_test.go
Labels: size/M

#5111 [CON-642] Reindex unavailable users
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/integration_tests/tasks/test_update_user_is_available.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/tasks/update_user_is_available.py
Labels: size/M

#5125 Enable mediorum-first on staging.
  mediorum/Makefile
  mediorum/bash_scripts/deploy.sh
  mediorum/bash_scripts/deploy_mediorum.sh
  mediorum/bash_scripts/nodes.sh
  mediorum/server/beam_client.go
  mediorum/server/server.go
Labels: size/M

#5124 [PAY-1166] Make SDK respect DN override (sdk-side)
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/constants.ts
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
Labels: size/S

#5091 Stage cid metadata backfill url, validate cid metadata structure in EM txs
  discovery-provider/integration_tests/tasks/test_backfill_cid_data.py
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/backfill_cid_data.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5126 Filter out albums from trending playlists
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/src/queries/get_trending_playlists.py
Labels: size/XS

#5133 ddl
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/alembic/versions/10c4a52dace7_notifier_incident.py
Labels: size/M

#5115 PLAT-725: remove very expensive query
  discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py
  discovery-provider/src/tasks/entity_manager/notification.py
Labels: size/S

#5127 Fix follow push notif title copy
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
Labels: size/XS

#5104 Create userbanks lazily in Identity Auto-Attester
  libs/src/api/Rewards.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/solana/rewardsAttester.ts
Labels: size/L

#5141 Bump sdk to v2.0.3-beta.11
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#5138 [PAY-1173] Improve identity attester & consume libs
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/utils/configureAttester.js
Labels: size/S

#5140 ddl 2
  discovery-provider/alembic/versions/6b4e03423667_notifier_incident_2.py
Labels: size/M

#5134 Structured logs in discovery
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/structured_logger.py
Labels: size/M

#5130 Fix mobile notification settings endpoints
  identity-service/src/models/userNotificationBrowserSettings.js
  identity-service/src/models/userNotificationMobileSettings.js
  identity-service/src/routes/push_notifications.js
Labels: size/S

#5129 Fix session not in scope in update_user_is_available
  discovery-provider/integration_tests/tasks/test_update_user_is_available.py
  discovery-provider/src/tasks/update_user_is_available.py
Labels: size/S

#5137 [C-2504] Upload file via storageV2 in sdk
  libs/src/sdk/api/TracksApi.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/constants.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/index.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/StorageService/StorageService.ts
  libs/src/sdk/services/StorageService/constants.ts
  libs/src/sdk/services/StorageService/index.ts
  libs/src/sdk/services/StorageService/types.ts
  libs/src/sdk/services/index.ts
  libs/src/sdk/types/File.ts
  libs/src/sdk/types/types.ts
  libs/src/sdk/utils/file.ts
  libs/src/sdk/utils/object.ts
  libs/src/sdk/utils/wait.ts
  sdk-consumer/index.ts
  sdk-consumer/package-lock.json
  sdk-consumer/package.json
  sdk-consumer/tsconfig.json
Labels: size/XL

#5146 Revert "[PAY-1166] Make SDK respect DN override (sdk-side) (#5124)"
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/constants.ts
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
Labels: size/S

#5147 Fix follow copy test
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
Labels: size/XS

#5131 [PLAT-897] Fix tastemaker notif indexing to handle pre-existing dupli…
  discovery-provider/integration_tests/tasks/test_index_tastemaker_notification.py
  discovery-provider/src/tasks/index_tastemaker_notifications.py
Labels: size/L

#5149 add mediorum panel to healthz
  monitoring/healthz/src/DMs.tsx
  monitoring/healthz/src/Mediorum.tsx
  monitoring/healthz/src/Router.tsx
  monitoring/healthz/src/misc.tsx
Labels: size/L

#5152 comms logs go to vector, use slog, reduce log noise.
  comms/Makefile
  comms/bash_scripts/deploy_discovery.sh
  comms/bash_scripts/deploy_prod.sh
  comms/bash_scripts/nodes.sh
  comms/bash_scripts/nuke_prod.sh
  comms/discovery/db/conn.go
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/broadcast.go
  comms/discovery/rpcz/sync_client.go
  comms/discovery/rpcz/validator.go
  comms/discovery/rpcz/websocket.go
  comms/discovery/server/server.go
  comms/discovery/server/version.go
  comms/go.mod
  comms/go.sum
  comms/main.go
  monitoring/vector/vector.toml
Labels: size/L

#5139 Better v0 CID sync
  mediorum/Makefile
  mediorum/crudr/client.go
  mediorum/crudr/crudr.go
  mediorum/ddl/cid_lookup.sql
  mediorum/ddl/ddl.go
  mediorum/ddl/test/cid_lookup_test.sql
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/beam_client.go
  mediorum/server/cid_log_client.go
  mediorum/server/cid_log_server.go
  mediorum/server/cid_log_test.go
  mediorum/server/db.go
  mediorum/server/repair.go
  mediorum/server/replicate.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
  mediorum/server/transcode.go
Labels: size/XL

#5153 SDK: Update types in SDK for chats/permissions
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/S

#5154 SDK: Stringify fetch POST bodies in V2-land
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/XS

#5128 Add register script to mediorum
  dev-tools/startup/register.py
  dev-tools/startup/storagev2.sh
  docker-compose.creator.yml
  docker-compose.storagev2.yml
  docker-compose.test.yml
  docker-compose.yml
  mediorum/.initdb/init.sql
  mediorum/server/server.go
  nginx_ingress.conf
Labels: size/L

#5148 Dedupe live emails
  discovery-provider/plugins/notifications/src/__tests__/emailRender.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
Labels: size/M

#5157 Document audius-compose, and remove legacy compose folders
  creator-node/compose/default-config.json
  creator-node/compose/docker-compose.yml
  creator-node/compose/env/base.env
  creator-node/compose/env/commonEnv.sh
  creator-node/compose/env/shellEnv.userMetadata.sh
  creator-node/compose/env/shellEnv1.sh
  creator-node/compose/env/shellEnv10.sh
  creator-node/compose/env/shellEnv2.sh
  creator-node/compose/env/shellEnv3.sh
  creator-node/compose/env/shellEnv4.sh
  creator-node/compose/env/shellEnv5.sh
  creator-node/compose/env/shellEnv6.sh
  creator-node/compose/env/shellEnv7.sh
  creator-node/compose/env/shellEnv8.sh
  creator-node/compose/env/shellEnv9.sh
  creator-node/compose/env/unsetShellEnv.sh
  creator-node/scripts/up.sh
  dev-tools/README.md
  discovery-provider/compose/.env
  discovery-provider/compose/.test.env
  discovery-provider/compose/docker-compose.backend.yml
  discovery-provider/compose/docker-compose.db.yml
  discovery-provider/compose/docker-compose.elasticsearch.yml
  discovery-provider/compose/docker-compose.notifications.yml
  discovery-provider/compose/docker-compose.redis.yml
  discovery-provider/compose/docker-compose.web-server.yml
  discovery-provider/compose/env/commonEnv.sh
  discovery-provider/compose/env/shellEnv1.sh
  discovery-provider/compose/env/shellEnv2.sh
  discovery-provider/compose/env/shellEnv3.sh
  discovery-provider/compose/env/shellEnv4.sh
  discovery-provider/compose/env/shellEnv5.sh
  discovery-provider/compose/env/shellEnv6.sh
  discovery-provider/compose/env/shellEnv7.sh
  discovery-provider/compose/env/shellEnv8.sh
  discovery-provider/compose/env/shellEnv9.sh
  discovery-provider/compose/env/unsetShellEnv.sh
  identity-service/compose/.env
  identity-service/compose/docker-compose.full.yml
Labels: size/XL

#5156 [PAY-1120] Filter tips to Audius account from the /tips API
  discovery-provider/integration_tests/queries/test_get_tips.py
  discovery-provider/src/api/v1/tips.py
  discovery-provider/src/queries/get_tips.py
Labels: discovery-node, size/L, python

#5122 PLAT-725: browser notification push
  .circleci/jobs/test.yml
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  discovery-provider/plugins/notifications/src/web.ts
Labels: size/L

#5159 [PAY-1120] Apply recipient filtering to full tips api
  discovery-provider/src/api/v1/tips.py
Labels: discovery-node, size/XS, python

#5155 [PLAT-848] Expose plugins in healthz
  discovery-provider/nginx_conf/config.lua
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/plugins.lua
  discovery-provider/plugins/verified-uploads/docker-compose.yaml
  discovery-provider/plugins/verified-uploads/package-lock.json
  discovery-provider/plugins/verified-uploads/package.json
  discovery-provider/plugins/verified-uploads/src/index.js
  discovery-provider/plugins/verified-uploads/src/server/index.js
  discovery-provider/plugins/verified-uploads/src/server/routes/healthCheck.js
  monitoring/healthz/package-lock.json
  monitoring/healthz/package.json
  monitoring/healthz/src/DMs.tsx
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/DiscoveryPlugins.tsx
  monitoring/healthz/src/DiscoveryTrending.tsx
  monitoring/healthz/src/Mediorum.tsx
  monitoring/healthz/src/Router.tsx
  monitoring/healthz/src/components/EnvironmentSelector.tsx
Labels: size/L

#5160 Fix timestamp precision.
  comms/discovery/rpcz/sync_client.go
  comms/discovery/server/server.go
Labels: size/XS

#5162 Notifs plugin: reasonable defaults
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
Labels: size/XS

#5163 [C-2526] pass offset through to get_related_artists
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_related_artists.py
Labels: size/S

#5161 [CON-661] mediorum enforces signature on cidstream endpoint
  mediorum/crudr/client.go
  mediorum/main.go
  mediorum/server/db.go
  mediorum/server/helpers.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_status.go
  mediorum/server/server.go
  mediorum/server/uis/upload.html
  mediorum/server/version.go
Labels: size/L

#5165 [CON-660] Set duration metadata property on v2 track uploads
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/metadata.py
  libs/src/sdk/services/StorageService/StorageService.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/M

#5166 [CON-671] Add mediorum track streaming byte ranges and filename downloads
  discovery-provider/src/queries/get_related_artists.py
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/M

#5167 Move compose files, delete code
  .circleci/jobs/build-gcp-image.yml
  README.md
  audius.code-workspace
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  crytic-config.json
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.comms.yml
  dev-tools/compose/docker-compose.creator.yml
  dev-tools/compose/docker-compose.dev.yml
  dev-tools/compose/docker-compose.discovery.yml
  dev-tools/compose/docker-compose.identity.yml
  dev-tools/compose/docker-compose.storagev2.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/compose/nginx_ingress.conf
  diff.sh
  discovery-provider/.test.env
  discovery-provider/contract_config_example.ini
  discovery-provider/default_config.ini
  discovery-provider/integration_tests/models/test_aggregate_counters.py
  discovery-provider/scripts/circle-ci.sh
  discovery-provider/scripts/setup.sh
  discovery-provider/scripts/test_entrypoint.sh
  discovery-provider/scripts/up.sh
  mad-dog/.eslintrc.js
  mad-dog/.gitignore
  mad-dog/README.md
  mad-dog/assets/images/duck.jpg
  mad-dog/assets/images/profile-pic.jpg
  mad-dog/assets/images/sid.png
  mad-dog/config.js
  mad-dog/package-lock.json
  mad-dog/package.json
  mad-dog/src/emitter.js
  mad-dog/src/helpers.js
  mad-dog/src/index.js
  mad-dog/src/logger.js
  mad-dog/src/madDog.js
  mad-dog/src/operations.js
  mad-dog/src/tests/index.js
  mad-dog/src/tests/test_integration.js
  mad-dog/src/tests/test_ipldBlacklist.js
  mad-dog/src/tests/test_plays.js
  mad-dog/src/tests/test_snapbackSM.js
  mad-dog/src/tests/test_ursmBlockSaturation.js
  mad-dog/src/tests/test_userReplicaSetManager.js
  mad-dog/src/tests/test_userReplicaSetNodes/deregisterRandomCreatorNode.js
  mad-dog/src/tests/test_userReplicaSetNodes/index.js
  mad-dog/src/tests/test_userReplicaSetNodes/setNumCreatorNodes.js
  mad-dog/src/tests/test_userReplicaSetNodes/stopRandomCreatorNode.js
  mad-dog/src/tests/test_userReplicaSetNodes/verifyValidCN.js
  mad-dog/src/utils/uploadTracksForUsers.js
  package-lock.json
  package.json
Labels: size/XXL

#5142 Validate to show playlist library in non-v1 /users endpoint
  discovery-provider/src/queries/queries.py
Labels: size/XS

#5168 Fix pg notify
  discovery-provider/plugins/notifications/src/listener.ts
  discovery-provider/plugins/notifications/src/setup.ts
Labels: size/S

#5169 Lower interval to 10min for availability checks
  discovery-provider/src/app.py
  discovery-provider/src/tasks/update_track_is_available.py
  discovery-provider/src/tasks/update_user_is_available.py
Labels: size/XS

#5170 Only show storage v2 flag in users full route, and fix minor compose issues
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.dev.yml
  dev-tools/compose/docker-compose.storagev2.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  discovery-provider/src/api/v1/models/users.py
Labels: size/S

#5173 Cursor retry + debug endpoint.
  comms/bash_scripts/deploy_discovery.sh
  comms/discovery/rpcz/sync_client.go
  comms/discovery/server/server.go
  comms/go.mod
  comms/go.sum
Labels: size/M

#5172 Better error message for getPermissions endpoint
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#5151 Add delegates table, create delegate indexing C-2292
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_delegate_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/delegates/__init__.py
  discovery-provider/src/models/delegates/app_delegate.py
  discovery-provider/src/tasks/entity_manager/app_delegate.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#5176 Add AI attribution
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/integration_tests/queries/test_get_tracks.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/models/users/user.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  libs/src/api/Track.ts
  libs/src/api/Users.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/XL

#5179 [CON-674] Make track edit work for storage v2
  libs/src/api/Track.ts
Labels: size/M

#5175 Make storage v2 work without CNs in audius-compose
  creator-node/sequelize/migrations/20181122035259-create-file.js
  creator-node/sequelize/migrations/20190711143402-add_uuid_to_users.js
  creator-node/sequelize/migrations/20200623002237-add-parent-file-data.js
  creator-node/sequelize/migrations/20200918150546-add-clock.js
  dev-tools/audius-compose
  discovery-provider/src/api/v1/helpers.py
  libs/src/api/Track.ts
  libs/src/sdk/services/StorageService/StorageService.ts
  libs/src/services/creatorNode/CreatorNode.ts
  mediorum/.initdb/init.sql
  mediorum/cmd/loadtest/client.go
  mediorum/cmd/loadtest/metrics.go
  mediorum/cmd/loadtest/report.go
  mediorum/cmd/loadtest/upload.go
  mediorum/ddl/cid_lookup.sql
  mediorum/server/server.go
  monitoring/healthz/src/Mediorum.tsx
Labels: size/L

#5180 Add AI attribution fields to API
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/models/users.py
Labels: size/XS

#5177 Fix listen milestone email
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/S

#5136 [PLAT-843] Add scheduled emails to notifications plugin
  dev-tools/audius-compose
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/userNotificationSettings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XL

#5183 Disable auto deploy to stage
  .circleci/workflows/main.yml
  dev-tools/audius-compose
Labels: size/M

#5184 Maybe fix wrong CircleCI images being auto-deployed
  dev-tools/audius-compose
Labels: size/XS

#5186 Add metadata schema for fetching AI attributes
  discovery-provider/src/tasks/metadata.py
Labels: size/XS
