Repository AudiusProject/apps, pull requests merged in 2023-01, with the labels that each got.

#4530 [PAY-782] Add tip gate for premium content
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/premium_content/premium_content_types.py
  discovery-provider/src/schemas/track_schema.json
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/M

#4547 Add dynamic nethermind gas limit
  identity-service/src/relay/txRelay.js
Labels: size/S

#4554 [PAY-802] Add track id to premium content signature data
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
  discovery-provider/src/queries/get_premium_track_signatures.py
  discovery-provider/src/queries/get_track_stream_signature.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/M

#4550 [CON-534] add new required field to accessChecker `trackId`
  creator-node/src/contentAccess/types.ts
  creator-node/test/contentAccessChecker.test.ts
Labels: size/S

#4545 Content node typescript
  creator-node/src/components/contentBlacklist/contentBlacklistComponentService.ts
Labels: size/M

#4449 Remove legacy POA indexing code
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/test_flask_app.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_profile_challenge_backfill.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/constants.py
  discovery-provider/src/utils/playlist_event_constants.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/XXL

#4544 Add anncouncement notif
  discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py
  discovery-provider/src/models/notifications/__init__.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/entity_manager/notification_seen.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index.py
Labels: size/L

#4497 [CON-534] move track_cid to Track model
  discovery-provider/src/api/v1/models/tracks.py
  libs/src/sdk/api/generated/default/models/Track.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
Labels: size/S

#4555 Sp nethermind web3
  discovery-provider/nginx_conf/main.lua
Labels: size/XS

#4557 Fix release scripts
  .circleci/release-scripts/bump-hotfix.sh
  .circleci/release-scripts/cut-release.sh
  .circleci/release-scripts/dheeraj-test.sh
  .circleci/release-scripts/evaluate-proposal.sh
  .circleci/release-scripts/release-to-service-providers.sh
  .circleci/release-scripts/slash-proposal.sh
Labels: size/S

#4559 Fix spid key in availability indexing
  discovery-provider/src/utils/eth_contracts_helpers.py
Labels: size/XS

#4561 Remove default audiusDataIdl from native libs
  libs/src/AudiusLibs.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/XS

#4558 Remove registry contract and clean up log
  discovery-provider/src/app.py
  discovery-provider/src/utils/eth_contracts_helpers.py
Labels: size/S

#4542 Comms rate limits
  comms/README.md
  comms/config/config.go
  comms/config/constants.go
  comms/db/queries/get_chat_messages.go
  comms/db/queries/get_chats.go
  comms/internal/pubkeystore/recover.go
  comms/internal/rpcz/apply.go
  comms/internal/rpcz/chat_block_test.go
  comms/internal/rpcz/chat_delete_test.go
  comms/internal/rpcz/chat_permissions_test.go
  comms/internal/rpcz/chat_test.go
  comms/internal/rpcz/rate_limit_test.go
  comms/internal/rpcz/test_utils.go
  comms/internal/rpcz/validator.go
  comms/jetstream/jetstream_client.go
  comms/peering/nats.go
  comms/server/server.go
  comms/server/server_test.go
Labels: size/XL

#4551 Add notification playlist seen
  discovery-provider/alembic/versions/4efaecad96fc_playlist_seen_notification.py
  discovery-provider/integration_tests/queries/test_user_playlist_update.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/setup.py
  discovery-provider/src/models/notifications/notification.py
  discovery-provider/src/queries/get_user_playlist_update.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#4197 Backfill artist pick
  discovery-provider/alembic/csvs/prod_pinned_track_ids.csv
  discovery-provider/alembic/csvs/staging_pinned_track_ids.csv
  discovery-provider/alembic/versions/2fad3671bf9f_backfill_artist_pick.py
Labels: size/XXL

#4568 Change CN legacy URSM code to not first attempt URSM reconfig, and go straight to EM now that it is rolled out globally
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
Labels: size/M

#4567 Add back rolloverNodes
  libs/src/sanityChecks/index.ts
  libs/src/sanityChecks/rolloverNodes.ts
Labels: size/L

#4570 check for blacklist having primary before declaring healthy
  libs/src/sanityChecks/index.ts
  libs/src/sanityChecks/rolloverNodes.ts
Labels: size/S

#4571 Move patch-package to main deps
  libs/package.json
Labels: size/XS

#4572 Move patch-package to prepare
  libs/package.json
Labels: size/XS

#4574 Check clock values, not blocknumbers, when replacing primary in sanity check
  libs/src/sanityChecks/rolloverNodes.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/M

#4575 Use entity manager in rollover
  libs/src/sanityChecks/rolloverNodes.ts
Labels: size/XS

#4556 [PAY-805] Update premium conditions in track schema
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/src/schemas/track_schema.json
  libs/src/sdk/api/generated/full/models/PremiumConditions.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/M

#4577 Use EntityManager in libs user and track
  libs/src/api/Account.ts
  libs/src/api/Track.ts
  libs/src/api/Users.ts
  libs/src/sanityChecks/rolloverNodes.ts
Labels: size/L

#4581 Disable CI maddog jobs since it is broken and deprecation is imminent
  .circleci/config.yml
Labels: size/M

#4576 [PLAT-570] Migrate for start block
  discovery-provider/alembic/versions/2571ec7593c7_init_db_models.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#4580 Fix migration idempotency
  .circleci/config.yml
  discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
  discovery-provider/alembic/versions/f6f009132212_add_track_is_playlist_upload.py
Labels: size/M

#4582 [C-1787] Improve tokenAccount performance by caching randomKeyPair
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solana/tokenAccount.ts
  libs/src/services/solanaAudiusData/SolanaAudiusData.ts
  libs/src/utils/index.ts
  libs/src/utils/keyPair.ts
Labels: size/S

#4584 [PLAT-570] Fix tests broken in prior commit
  dev-tools/audius-compose
  discovery-provider/alembic/versions/2571ec7593c7_init_db_models.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/utils.py
  docker-compose.m1.test.yml
Labels: size/L

#4563 [PLAT-538] Remove custom redis disk persistence, upgrade redis
  .circleci/config.yml
  discovery-provider/compose/docker-compose.redis.yml
  discovery-provider/src/eth_indexing/event_scanner.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_oldest_unarchived_play.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/utils/cache_solana_program.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/redis_metrics.py
  discovery-provider/src/utils/test_get_cached_metrics.py
  docker-compose.test.yml
  docker-compose.yml
  identity-service/compose/docker-compose.full.yml
  identity-service/scripts/run-tests.sh
Labels: size/L

#4578 Use EntityManager only for verify user
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/instagram.js
  identity-service/src/routes/tiktok.js
  identity-service/src/routes/twitter.js
Labels: size/S

#4589 Update DMs schema
  audius.code-workspace
  comms/Makefile
  comms/schema/schema.go
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/M

#4591 Fixes for audius-compose test run
  docker-compose.test.yml
Labels: size/XS

#4587 fixes precommit hook
  comms/DockerfileFast
  comms/Makefile
  comms/storage/storage.go
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/M

#4565 Recreate playlist_routes table
  discovery-provider/alembic/versions/efafdb22df81_backfill_playlist_routes_table.py
Labels: size/L

#4579 Fix CN reconfig + enable entitymanager locally
  creator-node/compose/env/base.env
  creator-node/src/monitors/MonitoringQueue.js
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  dev-tools/commands/src/utils.mjs
  identity-service/src/config.js
Labels: size/S

#4541 Reduce CN state machine interval
  creator-node/compose/env/base.env
  creator-node/src/config.js
Labels: size/XS

#4595 Fix bad unicode chars
  discovery-provider/src/utils/cid_metadata_client.py
Labels: size/XS

#4598 Mbrier/plat 000/revert subscriptions
  discovery-provider/src/tasks/index.py
Labels: size/S

#4593 Use one dockerfile for M1 and Linux Solana builds
  dev-tools/audius-compose
  docker-compose.m1.build.yml
  docker-compose.m1.test.yml
  docker-compose.m1.yml
  solana-programs/Dockerfile.dev
  solana-programs/Dockerfile.m1
  solana-programs/scripts/build.sh
  solana-programs/scripts/install-solana.sh
  solana-programs/scripts/setup-predeployed.sh
  solana-programs/scripts/update-keys.sh
Labels: size/XL

#4597 remove logs
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#4600 Fix redis timestamp in health check
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_latest_play.py
  discovery-provider/src/queries/get_oldest_unarchived_play.py
Labels: size/S

#4603 Remove solana anchor tests in CI
  .circleci/config.yml
Labels: size/M

#4594 Fix notifications endpoint
  discovery-provider/integration_tests/queries/test_user_playlist_update.py
  discovery-provider/src/api/v1/api.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/notifications.py
  discovery-provider/src/api/v1/notifications.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/queries/get_user_playlist_update.py
Labels: size/XL

#4605 Increase CI timeout
  .circleci/config.yml
Labels: size/S

#4606 Allow nil reactions in comms react RPC to unreact
  comms/internal/rpcz/chat.go
  comms/internal/rpcz/chat_test.go
  comms/schema/schema.go
  comms/schema/schema.ts
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/M

#4607 Update SDK chats.react to allow null reactions
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#4596 Include imageUrl for nft collection premium conditions for track
  discovery-provider/integration_tests/premium_content/test_access.py
  discovery-provider/src/schemas/track_schema.json
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/S

#4608 [INF-336] Cache sdk release module install
  .circleci/config.yml
  libs/package-lock.json
  libs/package.json
  libs/scripts/release.sh
Labels: size/M

#4613 Remove unnecessary chatId param from chats.create()
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/XS

#4615 dev-tools README improvements for clarity
  dev-tools/README.md
Labels: size/M

#4614 Fix & consolidate CN envvars for local dev for audius-compose
  dev-tools/startup/creator-node.sh
  docker-compose.yml
Labels: size/L

#4599 Add indexing after chain reset
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#4612 Add script to reset stage chain
  contracts/migrations/6_nethermind_entity_manager_migration.js
  contracts/truffle-config.js
  discovery-provider/scripts/reset_chain.sh
Labels: size/L

#4610 Misc comms cleanup
  comms/Makefile
  comms/internal/rpcz/chat_block_test.go
  comms/internal/rpcz/chat_delete_test.go
  comms/internal/rpcz/chat_permissions_test.go
  comms/internal/rpcz/chat_test.go
  comms/internal/rpcz/rate_limit_test.go
  comms/internal/rpcz/test_utils.go
  comms/internal/rpcz/validator.go
  comms/server/server.go
  comms/server/server_test.go
Labels: size/L

#4617 Change track un-delist logs to info
  creator-node/src/blacklistManager.js
Labels: content-node, size/S

#4543 Add trending notif
  discovery-provider/integration_tests/tasks/test_index_trending.py
  discovery-provider/integration_tests/tasks/test_index_trending_notification.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/tasks/index_trending.py
Labels: size/L

#4619 Rt sdk fix
  libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
Labels: size/XS

#4618 Fix CN isReadOnlyMode health check
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
Labels: size/M

#4562 Add registered discovery nodes as signers
  discovery-provider/default_config.ini
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/M

#4622 Skip API response version check if empty string
  libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
Labels: size/XS

#4611 NATS connection test
  comms/DockerfileFast
  comms/config/config.go
  comms/config/constants.go
  comms/go.mod
  comms/go.sum
  comms/internal/rpcz/apply.go
  comms/internal/rpcz/validator.go
  comms/main.go
  comms/peering/info.go
  comms/peering/nats.go
  comms/peering/solicit.go
  comms/peering/sps.go
  comms/server/server.go
  comms/server/static/cool.html
  comms/server/static/hello.txt
Labels: size/L

#4569 Backfill null artist pick discrepancies in discprov
  discovery-provider/alembic/versions/36ed02ac38f7_backfill_null_artist_pick_discrepancies_.py
Labels: size/M

#4564 Artist pick backfill: only update records last updated before the csvs were pulled
  discovery-provider/alembic/versions/2fad3671bf9f_backfill_artist_pick.py
Labels: size/S

#4623 [PLAT-418] Improve audius-compose testing for discovery
  dev-tools/README.md
  dev-tools/audius-compose
  dev-tools/keys/README.md
  dev-tools/keys/dev
  dev-tools/keys/dev.pub
  discovery-provider/.devcontainer/devcontainer.json
  discovery-provider/.vscode/settings.json
  discovery-provider/Dockerfile
  discovery-provider/README.md
  docker-compose.test.yml
  docker-compose.yml
Labels: size/L

#4625 Add tier change notification via triggers
  discovery-provider/alembic/trigger_sql/handle_user_balance_changes.sql
  discovery-provider/alembic/versions/58b26285cdcf_migrate_triggers_for_notifiations.py
  discovery-provider/alembic/versions/6a9f01e775d5_update_triggers.py
  discovery-provider/integration_tests/notifications/test_tier_change.py
  discovery-provider/integration_tests/queries/test_notifications/test_user_tier_change_notification.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/L

#4629 Fix alembic version
  discovery-provider/alembic/versions/6a9f01e775d5_update_triggers.py
Labels: size/XS

#4628 Add chain health check
  discovery-provider/src/queries/get_health.py
Labels: size/S

#4616 Comms chats endpoint updates
  comms/db/migrations/20230117200411_add_chat_last_message.sql
  comms/db/queries/get_chats.go
  comms/db/queries/get_summaries.go
  comms/internal/rpcz/chat.go
  comms/schema/schema.go
  comms/schema/schema.ts
  comms/server/response_mapper.go
  comms/server/server.go
  comms/server/server_test.go
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#4601 [CON-543] Fix `track_cid` edit bug
  discovery-provider/alembic/versions/a62b4e92b733_fix_nullified_track_cid.py
Labels: size/M

#4632 Fix alembic head
  discovery-provider/alembic/versions/a62b4e92b733_fix_nullified_track_cid.py
Labels: size/XS

#4624 Handle nil body data in nethermind rpc request
  discovery-provider/nginx_conf/main.lua
Labels: size/S

#4585 Write entity manager notifications in libs
  libs/src/api/Notifications.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/M

#4635 Use track cid streaming and fallback track id streaming
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_track_stream_signature.py
Labels: size/S

#4631 CON-537 "poor-mans UUID" Ensure each track file gets a unique CID to avoid re-upload collisions
  creator-node/package.json
  creator-node/src/ffmpeg.ts
  creator-node/test/ffmpeg.test.js
  creator-node/test/lib/helpers.js
  creator-node/test/pollingTracks.test.js
Labels: size/L

#4621 update chain reset to include all DNs
  discovery-provider/scripts/reset_chain.sh
Labels: size/S

#4634 Fix nft ownership check
  discovery-provider/src/queries/get_premium_track_signatures.py
Labels: size/S

#4620 [PAY-839] Do not filter out premium tracks from feed, trending, search on DN
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/premium_content/premium_content_constants.py
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/queries/search.py
  discovery-provider/src/queries/search_es.py
  discovery-provider/src/queries/search_queries.py
Labels: size/M

#4636 [CON-546] Check blacklist and record track listen in stream route
  creator-node/src/contentAccess/contentAccessChecker.ts
  creator-node/src/contentAccess/types.ts
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
  creator-node/src/routes/tracks.js
  creator-node/test/contentAccessChecker.test.ts
Labels: size/M

#4644 SDK: Decrypt the last message in the getChats response
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/M

#4400 Update playlists full get endpoint to retrieve playlist by playlist id or permalink
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_playlists.py
  libs/src/sdk/api/generated/full/apis/PlaylistsApi.ts
Labels: size/L

#4645 CN Ensure certain POST routes still work in readOnlyMode
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.ts
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts
Labels: size/L

#4633 Remove legacy POA indexing code (again)
  discovery-provider/integration_tests/conftest.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/tasks/test_index_operations.py
  discovery-provider/integration_tests/tasks/test_index_playlists.py
  discovery-provider/integration_tests/tasks/test_index_tracks.py
  discovery-provider/integration_tests/tasks/test_index_user_replica_set.py
  discovery-provider/integration_tests/tasks/test_index_users.py
  discovery-provider/integration_tests/test_flask_app.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/track.py
  discovery-provider/src/tasks/entity_manager/user.py
  discovery-provider/src/tasks/entity_manager/user_replica_set.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_profile_challenge_backfill.py
  discovery-provider/src/tasks/playlists.py
  discovery-provider/src/tasks/social_features.py
  discovery-provider/src/tasks/tracks.py
  discovery-provider/src/tasks/user_library.py
  discovery-provider/src/tasks/user_replica_set.py
  discovery-provider/src/tasks/users.py
  discovery-provider/src/utils/constants.py
  discovery-provider/src/utils/playlist_event_constants.py
  discovery-provider/src/utils/prometheus_metric.py
Labels: size/XXL

#4627 audius-compose cleanup
  contracts/Dockerfile.dev
  creator-node/Dockerfile
  dev-tools/audius-compose
  docker-compose.test.yml
  docker-compose.yml
  eth-contracts/Dockerfile.dev
  eth-contracts/package-lock.json
  identity-service/Dockerfile
Labels: size/L

#4648 Update mocha and fix cn and id tests
  creator-node/.mocharc.js
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/scripts/run-tests.sh
  dev-tools/audius-compose
  docker-compose.test.yml
  identity-service/.mocharc.js
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/scripts/run-tests.sh
Labels: size/L

#4649 fix comms websocket config
  comms/storage/transcode/static/status.html
  creator-node/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#4638 Update discovery api to return permalink with playlist objects
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/models/playlists/playlist.py
  libs/src/sdk/api/generated/default/models/Playlist.ts
  libs/src/sdk/api/generated/full/models/PlaylistFull.ts
Labels: size/M

#4647 SDK: Paginate getChats
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/chats/clientTypes.ts
Labels: size/S

#4650 nginx config for nats container
  creator-node/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#4652 [PAY-715] Delete audio tx history backfillers
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/index_rewards_manager_backfill.py
  discovery-provider/src/tasks/index_spl_token_backfill.py
  discovery-provider/src/tasks/index_user_bank_backfill.py
Labels: size/XXL

#4651 Add chain health to healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XS

#4654 Fix audius-compose test identity-service
  docker-compose.yml
  identity-service/test/redis.js
Labels: size/S

#4656 Update playlists route in queries.py to handle arguments correctly
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/src/queries/get_playlists.py
  discovery-provider/src/queries/queries.py
Labels: size/S

#4657 Move exchange endpoint to nats container
  comms/Makefile
  comms/README.md
  comms/bash_scripts/deploy.sh
  comms/bash_scripts/deploy_content.sh
  comms/bash_scripts/deploy_discovery.sh
  comms/bash_scripts/nuke.sh
  comms/bash_scripts/nuke_server.sh
  comms/discovery/discovery_main.go
  comms/discovery/jetstream/jetstream_client.go
  comms/discovery/server/server.go
  comms/natsd/nats_main.go
  comms/natsd/nats_manager.go
  comms/shared/peering/exchange_endpoint.go
  comms/shared/peering/info.go
  comms/shared/peering/nats_connection.go
  comms/shared/peering/signed_request.go
  comms/shared/peering/solicit.go
  comms/shared/peering/sps.go
  comms/storage/server.go
  comms/storage/static/cool.html
  comms/storage/static/hello.txt
  comms/storage/static/status.html
  comms/storage/storage_main.go
Labels: size/XL

#4604 [CON-544] Add new route to fetch copy320 CIDs using a segment CID
  creator-node/package-lock.json
  creator-node/src/routes/files.js
Labels: size/M

#4659 Fix account signup return block and userID
  libs/src/api/Account.ts
  libs/src/api/Users.ts
Labels: size/S

#4658 Fix identity users/update 400s
  identity-service/src/routes/user.js
Labels: size/XS

#4655 (WIP) PLAT-339: add filter arg to top parser
  discovery-provider/src/api/v1/playlists.py
Labels: bug, discovery-node, size/XS

#4662 Clear beatfile
  discovery-provider/scripts/start.sh
Labels: size/XS

#4666 Bump max limit
  discovery-provider/src/queries/query_helpers.py
Labels: size/XS

#4664 [PAY-849] Use IPData instead of IPAPI in identity /location
  identity-service/src/routes/location.js
Labels: size/S

#4661 Allow linking to private playlists if direct route is passed in
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_playlists.py
Labels: size/M

#4668 Fix discovery playlist seen indexing
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XS

#4667 Add permalink to user collections in users/account
  discovery-provider/src/queries/get_users_account.py
Labels: size/XS

#4669 [PAY-877] Cleanup solana tx fetching errors
  discovery-provider/src/exceptions.py
  discovery-provider/src/solana/solana_client_manager.py
  discovery-provider/src/tasks/index_spl_token.py
Labels: size/S

#4660 Add storage v2 skeleton
  comms/README.md
  comms/storage/decider/StorageDecider.go
  comms/storage/glue/glue.go
  comms/storage/server.go
  comms/storage/storage_main.go
  comms/storage/web/static/cool.html
  comms/storage/web/static/hello.txt
  comms/storage/web/static/status.html
  comms/storage/web/test.mp3
  comms/storage/web/web.go
  comms/storage/web/web_test.go
Labels: size/XL

#4670 SDK: Don't fail healthcheck on 0 blockdiff
  libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
Labels: size/XS

#4673 Fix redis version for creator build
  .circleci/config.yml
  creator-node/Dockerfile
  creator-node/compose/docker-compose.yml
  creator-node/scripts/run-tests.sh
  docker-compose.test.yml
Labels: size/S

#4675 Append in_eu field to location response
  identity-service/src/routes/location.js
Labels: size/XS

#4674 Remove unused anchor program indexer
  discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
  discovery-provider/src/app.py
  discovery-provider/src/database_task.py
  discovery-provider/src/solana/anchor_program_indexer.py
  discovery-provider/src/solana/audius_data_transaction_handlers.py
  discovery-provider/src/solana/solana_program_indexer.py
  discovery-provider/src/tasks/index_solana_user_data.py
Labels: size/XXL

#4677 Fix social feature validations
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#4682 PLAT-623: death to the jdk
  libs/src/sdk/api/generator/gen.js
Labels: libs, size/M

#4678 Add message notification setting
  identity-service/sequelize/migrations/20230127022759-add-messages-to-browser-notification-settings.js
  identity-service/sequelize/migrations/20230127023810-add-messages-to-mobile-notification-settings.js
  identity-service/src/models/userNotificationBrowserSettings.js
  identity-service/src/models/userNotificationMobileSettings.js
Labels: size/M

#4592 Subscribe/unsubscribe on follow/unfollow in EM
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/notification.py
  discovery-provider/src/tasks/entity_manager/playlist.py
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/L

#4685 Playlist es indexer fix
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
Labels: size/XS

#4690 [CON-566] Add try/catch to all metrics sql queries
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
Labels: size/L

#4687 Fix social feature undefined
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/M

#4694 Add migration for handle repost fix
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/versions/72b030bb3dcb_handle_repost_fix.py
Labels: size/M

#4693 [CON-561] Add launch config to debug storage node
  .vscode/launch.json
Labels: size/XS

#4679 image resizing
  comms/go.mod
  comms/go.sum
  comms/storage/transcode/img.go
  comms/storage/transcode/jobs.go
  comms/storage/web/static/status.html
  comms/storage/web/web.go
Labels: size/XL

#4683 Refactor DMs validator to use kv watch
  comms/Makefile
  comms/discovery/discovery_main.go
  comms/discovery/jetstream/jetstream_client.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/pubkeystore/recover_test.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat_block_test.go
  comms/discovery/rpcz/chat_delete_test.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/chat_test.go
  comms/discovery/rpcz/main_test.go
  comms/discovery/rpcz/rate_limit.go
  comms/discovery/rpcz/rate_limit_test.go
  comms/discovery/rpcz/validator.go
  comms/discovery/server/main_test.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  comms/shared/peering/nats_connection.go
  comms/storage/storage_main.go
  comms/storage/transcode/jobs_test.go
Labels: size/XL
