Repository AudiusProject/apps, pull requests merged in 2023-12, with the labels that each got.

#6815 [C-3403] Fix sign-up e2e
  packages/common/src/hooks/useFeatureFlag.ts
  packages/harmony/src/components/button/FollowButton/FollowButton.mdx
  packages/harmony/src/components/button/FollowButton/FollowButton.stories.tsx
  packages/harmony/src/components/button/FollowButton/FollowButton.tsx
  packages/probers/cypress/e2e/flaky-test-jail.md
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/web/src/app/App.tsx
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/welcome-modal/WelcomeModal.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#6821 [PAY-2215] Play full purchased tracks from mobile library
  packages/web/src/common/store/queue/sagas.ts
Labels: size/XS

#6824 Auto-hide scheduled releases and index as utc
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/M

#6826 [PAY-2227] Set min-width for NavPopupMenu
  packages/mobile/src/components/audio-balance-pill/AUDIOBalancePill.tsx
  packages/web/src/components/audio-balance-pill/AUDIOBalancePill.module.css
  packages/web/src/components/audio-balance-pill/AUDIOBalancePill.tsx
  packages/web/src/components/nav/desktop/NavPopupMenu.module.css
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/usdc-balance-pill/USDCBalancePill.module.css
Labels: size/S

#6810 [PAY-2209] Use single modal for purchase and transfer
  packages/common/src/hooks/purchaseContent/constants.ts
  packages/common/src/hooks/purchaseContent/types.ts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/store/purchase-content/selectors.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/purchase-content/types.ts
  packages/common/src/store/ui/modals/usdc-manual-transfer-modal/index.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseContentFormState.ts
  packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/mobile/src/components/usdc-manual-transfer/index.ts
  packages/web/src/components/add-funds-modal/AddFundsModal.module.css
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseContentFormState.ts
  packages/web/src/components/usdc-manual-transfer-modal/USDCManualTransferModal.module.css
  packages/web/src/components/usdc-manual-transfer-modal/USDCManualTransferModal.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.module.css
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XL

#6827 Make mobile buy buttons stick to bottom
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Labels: size/L

#6829 [C-3453] Replace edit collection form with new fields
  packages/web/src/components/create-playlist/FormActions.tsx
  packages/web/src/components/create-playlist/PlaylistForm.module.css
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/form-fields/ArtworkField.module.css
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/components/upload/UploadArtwork.d.ts
  packages/web/src/components/upload/UploadArtwork.jsx
  packages/web/src/components/upload/UploadArtwork.module.css
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Labels: size/L

#6831 [C-2591] Fix Follow All button on mobile
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Labels: size/M

#6830 [PROTO-1458] Expose postgres upgrade logs in mediorum
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/XS

#6811 [C-3417] Cover photos default to blurred profile photo if unset
  packages/mobile/src/components/image/CoverPhoto.tsx
  packages/mobile/src/components/image/UserCoverImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/ProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/ProfileCoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/web/src/components/artist/ArtistCardCover.tsx
  packages/web/src/components/artist/ArtistCover.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/cover-photo/CoverPhoto.tsx
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/tipping/support/SupportingTile.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
  packages/web/src/hooks/useCoverPhoto.ts
  packages/web/src/hooks/useUserCoverPhoto.ts
  packages/web/src/pages/dashboard-page/components/ArtistCard.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/sign-up-page/components/FollowArtistTile.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/XL

#6834 Fix routing for legacy sign-on
  packages/web/src/app/App.tsx
Labels: size/S

#6839 Fix remixes for usdc purchase tracks
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Labels: size/M

#6840 Return remixes for premium tracks
  packages/discovery-provider/src/queries/get_remixes_of.py
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Labels: size/S

#6843 Fix mobile premium track remix visibility
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
Labels: size/S

#6837 [C-3385] Harmony icon component tweaks
  packages/harmony/src/components/icon/Icon.tsx
  packages/harmony/src/foundations/theme/theme.ts
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
Labels: size/M

#6835 Remove track_segments data, default to []
  packages/discovery-provider/ddl/migrations/0040_rm_track_segments.sql
Labels: size/S

#6832 Periodically check for and correct trusted notifier discrepancies in DN
  packages/discovery-provider/src/queries/get_trusted_notifier_discrepancies.py
  packages/discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/L

#6844 [C-3459] Improve sign-up responsiveness
  packages/web/src/app/App.tsx
  packages/web/src/hooks/useMedia.ts
  packages/web/src/pages/oauth-login-page/index.ts
  packages/web/src/pages/sign-on-page/AudiusValues.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenrePage.tsx
  packages/web/src/pages/sign-up-page/utils/RouteContext.tsx
Labels: size/XL

#6854 re-add docker copy
  packages/discovery-provider/Dockerfile.dev
  packages/discovery-provider/Dockerfile.prod
Labels: size/XS

#6850 [Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#6857 [C-3467] Fix python install in mobile ci
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/workflows/mobile.yml
Labels: size/M

#6848 Update solana-test-validator container build to allow deployment of payment router
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/config.json
  packages/discovery-provider/src/app.py
  solana-programs/.nvmrc
  solana-programs/Dockerfile
  solana-programs/Dockerfile.dev
  solana-programs/README.md
  solana-programs/payment-router/Anchor.toml
  solana-programs/payment-router/package.json
  solana-programs/payment-router/tests/constants.ts
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/payment-router/yarn.lock
  solana-programs/scripts/deploy.sh
  solana-programs/scripts/install-solana.sh
  solana-programs/scripts/update-keys.sh
Labels: size/XXL

#6838 [C-3408] Native Create Account Page
  packages/common/src/index.ts
  packages/common/src/messages/index.ts
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/messages/sign-on/socialMediaMessages.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/utils/email.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/components/layout/index.ts
  packages/mobile/src/harmony-native/foundations/color/semantic.ts
  packages/mobile/src/screens/sign-in-screen/SignInScreen.tsx
  packages/mobile/src/screens/sign-up-screen/SignUpRootScreen.tsx
  packages/mobile/src/screens/sign-up-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-up-screen/components/SocialMediaLoginOptions.tsx
  packages/mobile/src/screens/sign-up-screen/components/layout.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/AudiusLogoH.png
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/Divider.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/Hint.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/IconAudiusLogoHorizontalColor.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/IconExclamation.svg
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/SocialButton.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconCloudArrowUp.svg
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconHeadphones.svg
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconMessages.svg
  packages/mobile/src/screens/sign-up-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SignUpScreen.tsx
  packages/mobile/src/screens/sign-up-screen/types.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/utils/emailSchema.ts
  packages/web/src/pages/sign-up-page/utils/loginDetailsSchema.ts
Labels: size/XXL

#6852 [PROTO-1477] Free up mediorum db space and remove unused code
  mediorum/cmd/main.go
  mediorum/cmd/reaper/reaper.go
  mediorum/cmd/reaper/reaper_test.go
  mediorum/cmd/segments/segments.go
  mediorum/cmd/segments/segments_test.go
  mediorum/ddl/ddl.go
  mediorum/main.go
  mediorum/server/server.go
Labels: size/XL

#6860 Add payment router addresses
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
Labels: size/XS

#6863 Fix typo in libs solana decimals constants
  packages/libs/src/api/Rewards.ts
  packages/libs/src/constants.ts
  packages/libs/src/services/solana/SolanaUtils.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/S

#6865 Reindex corrupted discovery indexes
  packages/discovery-provider/ddl/migrations/0041_repair_indexes.sql
Labels: size/S

#6867 Fix discovery lint err
  packages/discovery-provider/integration_tests/queries/test_get_personal_route_metrics.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/root_path.py
  packages/discovery-provider/src/solana/solana_client_manager.py
  packages/discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/M

#6861 [PROTO-1478] Add finalPOABlock support to discovery relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
Labels: size/XS

#6853 PROTO-1474: Discovery uses db tempalte for integration tests
  packages/discovery-provider/integration_tests/conftest.py
Labels: size/M

#6855 [Mobile] [C-3413] Fix verified sign up on mobile via Twitter/IG
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/S

#6869 fix openresty version
  packages/discovery-provider/Dockerfile.dev
  packages/discovery-provider/Dockerfile.prod
Labels: size/XS

#6868 [C-2959] Fix creating playlist from track
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
Labels: size/S

#6873 [C-3332] Fix playlist edit after create
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/M

#6875 [C-3479] 404 on invalid collection url
  packages/web/src/common/store/pages/collection/sagas.js
Labels: size/S

#6851 [C-3458] Sign Up QA round 2
  packages/harmony/src/components/button/FollowButton/FollowButton.tsx
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/src/components/input/TextInput/TextInput.module.css
  packages/web/src/components/stepped-progress/SteppedProgress.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx
  packages/web/src/pages/sign-up-page/components/EnterPasswordSection.tsx
  packages/web/src/pages/sign-up-page/components/FollowArtistTile.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/AppCtaPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/MobileAppCtaPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/utils/determineAllowedRoutes.ts
  packages/web/src/utils/route.ts
Labels: size/XL

#6871 [PAY-2194] Update summary tables
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/summary-table/SummaryTable.tsx
Labels: size/XL

#6812 [PAY-2197] Check Redis cache for transactions
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/index_solana_plays.py
  packages/discovery-provider/src/tasks/index_user_bank.py
  packages/discovery-provider/src/utils/redis_cache.py
Labels: size/M

#6878 PROTO-1364: fix relay heavy load
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
Labels: size/S

#6884 [C-3423] Add Avatar component to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Avatar/Avatar.stories.tsx
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/L

#6885 Remove extraneous icon imports
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Labels: size/XS

#6883 relay: fix error on no metadata
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/abi.ts
Labels: size/XS

#6887 Polish social media flow, other QA [C-3418]
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowInstagramAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTwitterAuth.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoading.module.css
  packages/web/src/pages/sign-up-page/components/SocialMediaLoading.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/utils/determineAllowedRoutes.ts
  packages/web/src/pages/sign-up-page/utils/handleSchema.ts
Labels: size/L

#6893 Address mobile icon issues
  packages/harmony/.svgrrc.js
  packages/mobile/.svgrrc.js
  svgr-template.js
Labels: size/S

#6889 Re-remove copy . . from discovery dev dockerfile
  packages/discovery-provider/Dockerfile.dev
  packages/discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
Labels: size/XS

#6897 [PAY-2245] Fix purchase radio buttons on android
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
Labels: size/XS

#6898 Fix rewards + plays indexing
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/index_solana_plays.py
Labels: size/M

#6896 Improve mobile clean commands
  package.json
Labels: size/XS

#6901 Fix svgo viewBox defaults
  svgo.config.js
Labels: size/S

#6892 [PAY-2178] Initial implementation of payment router indexing
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  monitoring/uptime/main.go
  packages/discovery-provider/ddl/migrations/0042_add_payment_router_txs.sql
  packages/discovery-provider/default_config.ini
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/models/users/payment_router.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/utils/redis_constants.py
Labels: size/XL

#6902 [PAY-2132] Premium content explore page denylist
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/common/store/lineup/sagas.js
Labels: size/S

#6904 [C-3440] Add Hint component to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Hint/Hint.stories.tsx
  packages/mobile/src/harmony-native/components/Hint/Hint.tsx
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/M

#6907 Fix missing string format on payment router indexing
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/XS

#6890 [C-3444] Native Pick Handle Page
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/sign-on/pickHandleSchema.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/restrictedHandles.ts
  packages/mobile/src/screens/sign-up-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-up-screen/utils/restrictedHandles.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/hooks/socialMediaLogin.ts
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
  packages/web/src/pages/upload-page/fields/SelectMoodField.tsx
  packages/web/src/utils/Moods.tsx
  packages/web/src/utils/restrictedHandles.ts
Labels: size/L

#6846 Add memo for purchaser user id
  packages/commands/src/purchase-track.mjs
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/M

#6905 [C-3452 C-3448] Native sign-on screen
  packages/common/src/messages/sign-on/pages.ts
  packages/harmony/src/foundations/corner-radius/CornerRadius.stories.mdx
  packages/harmony/src/foundations/corner-radius/cornerRadius.ts
  packages/mobile/src/app/navigation/AudiusHomeLink.tsx
  packages/mobile/src/app/navigation/BackButton.tsx
  packages/mobile/src/app/navigation/index.ts
  packages/mobile/src/app/navigation/useScreenOptions.tsx
  packages/mobile/src/components/fields/TextField.tsx
  packages/mobile/src/harmony-native/components/layout/Box/Box.tsx
  packages/mobile/src/harmony-native/components/layout/Flex/Flex.tsx
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/sign-in-screen/SignInScreen.tsx
  packages/mobile/src/screens/sign-in-screen/index.ts
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/ArtistTile.tsx
  packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-on-screen/components/CoverPhotoField.tsx
  packages/mobile/src/screens/sign-on-screen/components/PasswordCompletionChecklist.tsx
  packages/mobile/src/screens/sign-on-screen/components/ProfilePictureField.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpPolicyText.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoginOptions.tsx
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/ArrowRight.svg
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/AudiusLogoH.png
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/Divider.tsx
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/Hint.tsx
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/IconExclamation.svg
  packages/mobile/src/screens/sign-on-screen/components/temp-harmony/SocialButton.tsx
  packages/mobile/src/screens/sign-on-screen/constants.ts
  packages/mobile/src/screens/sign-on-screen/index.ts
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/types.ts
  packages/mobile/src/screens/sign-on-screen/types.ts
  packages/mobile/src/screens/sign-on-screen/useRoute.ts
  packages/mobile/src/screens/sign-on-screen/utils/restrictedHandles.ts
  packages/mobile/src/screens/sign-on-screen/utils/socialMediaMessages.ts
  packages/mobile/src/screens/sign-up-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/IconAudiusLogoHorizontalColor.tsx
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconCloudArrowUp.svg
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconHeadphones.svg
  packages/mobile/src/screens/sign-up-screen/components/temp-harmony/iconMessages.svg
  packages/mobile/src/screens/sign-up-screen/index.ts
  packages/mobile/src/screens/sign-up-screen/screens/CreateEmailScreen.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
Labels: size/XL

#6906 Separate web / mobile trpc client
  packages/common/src/services/index.ts
  packages/mobile/src/app/TrpcProvider.tsx
  packages/mobile/src/components/user/FollowsYouChip.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/services/trpc-client-mobile.ts
  packages/trpc-server/src/trpc.ts
  packages/web/src/app/TrpcProvider.tsx
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
  packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx
  packages/web/src/utils/trpcClientWeb.ts
Labels: size/M

#6872 trpc test setup
  packages/trpc-server/.prettierrc
  packages/trpc-server/README.md
  packages/trpc-server/docker-compose.yml
  packages/trpc-server/package.json
  packages/trpc-server/src/index.ts
  packages/trpc-server/src/routers/search-router.ts
  packages/trpc-server/src/server.ts
  packages/trpc-server/test.sh
  packages/trpc-server/test/_fixtures.ts
  packages/trpc-server/test/_test_helpers.ts
  packages/trpc-server/test/router.test.ts
  packages/trpc-server/test/search.test.ts
Labels: size/XL

#6903 [C-3436] Add SelectablePill component to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.stories.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/types.ts
Labels: size/L

#6909 [C-3445] Add native finish-profile-screen
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/sign-on/finishProfileSchema.ts
  packages/harmony/src/components/avatar/Avatar.tsx
  packages/harmony/src/components/avatar/types.ts
  packages/mobile/src/harmony-native/components/Avatar/Avatar.stories.tsx
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-on-screen/components/CoverPhotoField.tsx
  packages/mobile/src/screens/sign-on-screen/components/ProfilePictureField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/utils/launchImageLibrary.e2e.ts
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Labels: size/XL

#6913 Fix timestamp comparison for sched releases
  packages/discovery-provider/src/tasks/publish_scheduled_releases.py
Labels: size/XS

#6912 Add sign in route aliases C-3503
  packages/web/src/app/App.tsx
  packages/web/src/utils/route.ts
Labels: size/S

#6914 [C-3504] Enable native animated icons
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/types/declarations.d.ts
  svgr-template.js
Labels: size/S

#6915 [PAY-2241][PAY-2259] Add Funds via Coinflow
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/M

#6917 [PAY-2263] Decode ABI for blocked users and relay if they're deactivation requests
  packages/identity-service/src/routes/relay.js
Labels: size/S

#6920 [PAY-2263] Always Allow Deactivations on DN Relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
Labels: size/S

#6921 Fix prices add types for purchases
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/M

#6908 [PROTO-1480] Expose hosted DBs in healthz
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/XS

#6925 Bump version to 0.6.0
  mediorum/.version.json
  packages/discovery-provider/.version.json
Labels: size/XS

#6918 [PROTO-1481] Hardcode mediorum dbUrl to localhost
  mediorum/main.go
  packages/discovery-provider/scripts/reset_chain.sh
Labels: size/XS

#6924 Remove CTA on withdrawals table empty state
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/M

#6926 Fix defaults when coinflow disabled + android purchase vendor drawer
  packages/mobile/src/components/payment-method/CardSelectionButton.tsx
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
Labels: size/S

#6836 rm does_follow_current_user from API response
  packages/common/src/models/User.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/queries/response_name_constants.py
  packages/discovery-provider/src/utils/elasticdsl.py
  packages/libs/src/utils/types.ts
Labels: size/M

#6928 [C-3429] Add FollowButton to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/types.ts
Labels: size/L

#6931 [PAY-2269] Fix mobile config
  packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/env.ts
Labels: size/S

#6930 [PAY-2271] Skip preflight in coinflow checkout
  packages/common/src/hooks/useCoinflowAdapter.ts
Labels: size/XS

#6933 Add dashboard wallet users table C-3497
  packages/discovery-provider/ddl/migrations/0043_add_dashboard_wallet_users.sql
Labels: size/S

#6937 Fix feature flag lint issue
  packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx
  packages/mobile/src/screens/feature-flag-override-screen/fuzzySearch.ts
Labels: size/XS

#6876 [C-3475] Allow editing album track order
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#6940 [C-3509] Fix sign-in legacy styles
  packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/M

#6932 [PAY-2249] Adds tests for payment router indexing
  packages/discovery-provider/integration_tests/tasks/payment_router_mock_transactions.py
  packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/XXL

#6942 Use 0.0.0.0 default host for vite app
  packages/web/vite.config.ts
Labels: size/XS

#6945 [PAY-2270] Show vendor button only if more than 1 vendor
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Labels: size/S

#6943 [PAY-2273] Fix payExtra for coinflow and stripe
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/XS

#6946 [PAY-2276] Selectable amounts for coinflow add funds web
  packages/common/src/hooks/purchaseContent/usePayExtraPresets.ts
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/add-funds-modal/constants.ts
  packages/web/src/components/add-funds-modal/types.ts
  packages/web/src/components/add-funds-modal/validation.ts
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts
  packages/web/src/components/summary-table/SummaryTable.tsx
Labels: size/L

#6947 [C-3435] Add CompletionCheck to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.stories.tsx
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.tsx
Labels: size/L

#6934 Fix primary key for DashboardWalletUsers
  packages/discovery-provider/ddl/migrations/0043_add_dashboard_wallet_users.sql
Labels: size/XS

#6949 Extra amount is in dollars
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/XS

#6951 Revert "Extra amount is in dollars (#6949)"
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/XS

#6952 Fix pay extra
  packages/common/src/services/audius-backend/solana.ts
Labels: size/XS

#6944 [PAY-2224] Add ExploreTransaction callout to sale/purchase details
  packages/web/src/components/link/Link.module.css
  packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Labels: size/M

#6953 fix: Fix native select genres pill performance issue
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenreScreen.tsx
Labels: size/M

#6936 [C-3485, C-3487, C-3486] Add Track to Album (web)
  packages/common/src/store/cache/collections/actions.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/add-to-collection/actions.ts
  packages/common/src/store/ui/add-to-collection/reducer.ts
  packages/common/src/store/ui/add-to-collection/selectors.ts
  packages/common/src/store/ui/add-to-playlist/actions.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/components/add-to-collection-drawer/index.ts
  packages/mobile/src/components/add-to-playlist-drawer/index.ts
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/add-to-collection/sagas.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/components/actions-tab/ActionsTab.jsx
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.module.css
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
  packages/web/src/components/add-to-collection/mobile/AddToCollection.module.css
  packages/web/src/components/add-to-collection/mobile/AddToCollection.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/nav/mobile/TopLevelPage.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#6954 Scheduled release mobile
  packages/common/src/models/Collection.ts
  packages/mobile/src/components/core/ContextualMenu.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateFieldLegacy.tsx
  packages/mobile/src/screens/edit-track-screen/fields/index.ts
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/index.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XL

#6939 [C-3449] Add native welcome modal & consolidate messages to common
  packages/common/src/messages/sign-on/pages.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/components/WelcomeDrawer.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistsScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/welcome-modal/WelcomeModal.tsx
Labels: size/L

#6956 [PAY-2286] Increase payment router indexer frequency
  packages/discovery-provider/src/app.py
Labels: size/XS

#6958 Bump mobile versions for full release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#6957 Use retry logic for coinflow
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/M

#6959 [PAY-2274] Update minWidths of pay extra pills to prevent clipping
  packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx
Labels: size/XS

#6960 [PAY-2283] Disable purchase button immediately after click
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/purchase-content/types.ts
  packages/common/src/store/purchase-content/utils.ts
  packages/common/src/store/ui/coinflow-modal/slice.ts
  packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
Labels: size/M

#6950 Make finding slow queries compatible with pg 13+
  packages/discovery-provider/src/monitors/database.py
Labels: size/S

#6922 Notify Slack when stage nodes aren't updating
  .circleci/config.yml
Labels: size/M

#6963 Default to Stripe
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
Labels: size/XS

#6962 [C-3511] Add Track to Album (mobile + mobile web)
  packages/common/src/store/cache/collections/actions.ts
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/components/collection-list/AddCollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/components/duplicate-add-confirmation-drawer/DuplicateAddConfirmationDrawer.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/saved-collections/actions.ts
  packages/web/src/common/store/saved-collections/sagas.ts
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
  packages/web/src/components/add-to-collection/mobile/AddToCollection.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#6970 Revert "[PAY-2276] Selectable amounts for coinflow add funds web (#69…
  packages/common/src/hooks/purchaseContent/usePayExtraPresets.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/add-funds-modal/constants.ts
  packages/web/src/components/add-funds-modal/types.ts
  packages/web/src/components/add-funds-modal/validation.ts
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts
  packages/web/src/components/summary-table/SummaryTable.tsx
Labels: size/L

#6967 [PAY-2293][PAY-2292] Add coinflow updates
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Labels: size/M

#6972 Quick fix to use release_date for feed ordering
  packages/es-indexer/package.json
  packages/es-indexer/src/indexNames.ts
  packages/es-indexer/src/indexers/TrackIndexer.ts
  packages/es-indexer/src/types/db.ts
  packages/sql-ts/package.json
  packages/sql-ts/src/index.ts
Labels: size/XXL

#6974 [C-3518] Fix user-list issues, sign-up navigation issue
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/screens/user-list-screen/UserListItemSkeleton.tsx
Labels: size/M

#6975 [PAY-2296] Adds additional metadata to Coinflow purchases
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/ui/modals/coinflow-onramp-modal/index.ts
  packages/web/src/app/App.tsx
  packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
Labels: size/L

#6973 Update ToS
  packages/web/public/documents/TermsOfUse.pdf
Labels: size/XS

#6978 Update key for tos banner version
  packages/web/src/components/banner/TermsOfServiceUpdateBanner.tsx
Labels: size/XS

#6979 [C-3535] Fix harmony icon types
  packages/harmony/src/icons/logos.ts
  packages/harmony/src/icons/specialIcons.ts
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/icons.ts
Labels: size/XL

#6976 [C-3519] Fix async absolute lottie imports
  packages/web/src/components/animated-button/AnimatedIconButton.tsx
  packages/web/src/components/bottom-bar/buttons/ExploreButton.tsx
  packages/web/src/components/bottom-bar/buttons/FeedButton.tsx
  packages/web/src/components/bottom-bar/buttons/LibraryButton.tsx
  packages/web/src/components/bottom-bar/buttons/ProfileButton.tsx
  packages/web/src/components/bottom-bar/buttons/TrendingButton.tsx
  packages/web/src/components/play-bar/repeat-button/RepeatButtonProvider.tsx
  packages/web/src/components/play-bar/shuffle-button/ShuffleButtonProvider.tsx
Labels: size/M

#6955 [C-3447] Add select-artist native screen
  packages/common/src/audius-query/index.ts
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/sign-on/selectArtistsSchema.ts
  packages/harmony/src/components/avatar/Avatar.tsx
  packages/harmony/src/components/avatar/types.ts
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/audio-rewards/index.ts
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/FlatList.tsx
  packages/mobile/src/components/core/IconAudioBadge.tsx
  packages/mobile/src/components/core/ProfilePicture.tsx
  packages/mobile/src/components/core/UserCoverPhoto.tsx
  packages/mobile/src/components/core/UserDisplayName.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/types.ts
  packages/mobile/src/harmony-native/components/CoverPhoto/CoverPhoto.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectedGenresTabBar.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/index.ts
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistsScreen.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/XL

#6980 [C-3494] Add shadow to icon
  packages/harmony/rollup.config.mjs
  packages/harmony/src/components/icon.ts
  packages/mobile/src/harmony-native/foundations/theme/shadows.ts
  packages/mobile/src/harmony-native/foundations/theme/theme.ts
  packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx
  svgr-template.js
Labels: size/L

#6981 [C-3528] Add harmony animated icons
  packages/harmony/src/assets/animations/Soundwave.json
  packages/harmony/src/assets/animations/SoundwaveCircle.json
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/components/layout/Box/types.ts
  packages/harmony/src/icons/animatedIcons.ts
  packages/harmony/src/icons/index.ts
  packages/web/src/pages/sign-up-page/components/FollowArtistTile.tsx
Labels: size/M

#6985 Schedule release follow ons
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/upload-screen/index.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
Labels: size/L

#6986 Fix sdk write w/ vite and fix npm publish
  packages/commands/package.json
  packages/embed/package.json
  packages/es-indexer/package.json
  packages/harmony/package.json
  packages/identity-service/package.json
  packages/libs/src/sdk/services/EntityManager/EntityManager.ts
  packages/probers/package.json
Labels: size/S

#6966 fix non responsive node attestation
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/libs.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
Labels: size/S

#6977 Lint fixes for edit album
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
Labels: size/S

#6991 Publish @audius/spl
  packages/spl/package.json
Labels: size/XS

#6968 [C-3427] Add BaseButton to mobile harmony
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/types.ts
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.stories.tsx
Labels: size/L

#6982 [PROTO-1500] Use created_at for release_date by default
  packages/discovery-provider/ddl/migrations/0044_set_release_to_created_where_null.sql
  packages/discovery-provider/src/models/model_utils.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#6998 Add lock to tracks table for migration
  packages/discovery-provider/ddl/migrations/0044_set_release_to_created_where_null.sql
Labels: size/XS

#6999 fix es-indexer for local dev
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/startup/discovery-provider.sh
  packages/discovery-provider/plugins/pedalboard/docker/startup.sh
  packages/es-indexer/README.md
Labels: size/XS

#6891 Add Solana Support to SDK with sdk.users.sendTip()
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/cache.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/cache/cache.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/feePayer.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/fixed-decimal/package.json
  packages/identity-service/src/typed-routes/solana/solanaRelayChecks.ts
  packages/identity-service/test/routes/solanaRelayTest.ts
  packages/libs/package.json
  packages/libs/src/sdk/api/users/UsersApi.test.ts
  packages/libs/src/sdk/api/users/UsersApi.ts
  packages/libs/src/sdk/api/users/types.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Auth/AppAuth.ts
  packages/libs/src/sdk/services/Auth/Auth.ts
  packages/libs/src/sdk/services/Auth/types.ts
  packages/libs/src/sdk/services/EntityManager/EntityManager.test.ts
  packages/libs/src/sdk/services/Solana/Solana.ts
  packages/libs/src/sdk/services/Solana/constants.ts
  packages/libs/src/sdk/services/Solana/index.ts
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokens.ts
  packages/libs/src/sdk/services/Solana/programs/types.ts
  packages/libs/src/sdk/services/Solana/types.ts
  packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  packages/libs/src/sdk/services/index.ts
  packages/libs/src/sdk/types.ts
  packages/libs/src/sdk/utils/prettify.ts
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/services/env.ts
  packages/mobile/src/services/sdk/audius-sdk.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/solana.ts
  packages/spl/src/claimable-tokens/ClaimableTokensProgram.ts
  packages/spl/src/claimable-tokens/constants.ts
  packages/spl/src/claimable-tokens/create.ts
  packages/spl/src/claimable-tokens/decode.ts
  packages/spl/src/claimable-tokens/index.ts
  packages/spl/src/claimable-tokens/transfer.ts
  packages/spl/src/claimable-tokens/types.ts
  packages/spl/src/index.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/audius-sdk/solana.ts
Labels: size/XXL

#7001 Disable triggers while migration runs
  packages/discovery-provider/ddl/migrations/0044_set_release_to_created_where_null.sql
Labels: size/XS

#7002 Revert "Add Solana Support to SDK with sdk.users.sendTip() (#6891)"
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/cache.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/cache/cache.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/feePayer.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/fixed-decimal/package.json
  packages/identity-service/src/typed-routes/solana/solanaRelayChecks.ts
  packages/identity-service/test/routes/solanaRelayTest.ts
  packages/libs/package.json
  packages/libs/src/sdk/api/users/UsersApi.test.ts
  packages/libs/src/sdk/api/users/UsersApi.ts
  packages/libs/src/sdk/api/users/types.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Auth/AppAuth.ts
  packages/libs/src/sdk/services/Auth/Auth.ts
  packages/libs/src/sdk/services/Auth/types.ts
  packages/libs/src/sdk/services/EntityManager/EntityManager.test.ts
  packages/libs/src/sdk/services/Solana/Solana.ts
  packages/libs/src/sdk/services/Solana/constants.ts
  packages/libs/src/sdk/services/Solana/index.ts
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokens.ts
  packages/libs/src/sdk/services/Solana/programs/types.ts
  packages/libs/src/sdk/services/Solana/types.ts
  packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  packages/libs/src/sdk/services/index.ts
  packages/libs/src/sdk/types.ts
  packages/libs/src/sdk/utils/prettify.ts
  packages/mobile/.env.dev
  packages/mobile/.env.prod
  packages/mobile/.env.stage
  packages/mobile/src/services/env.ts
  packages/mobile/src/services/sdk/audius-sdk.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/solana.ts
  packages/spl/src/claimable-tokens/ClaimableTokensProgram.ts
  packages/spl/src/claimable-tokens/constants.ts
  packages/spl/src/claimable-tokens/create.ts
  packages/spl/src/claimable-tokens/decode.ts
  packages/spl/src/claimable-tokens/index.ts
  packages/spl/src/claimable-tokens/transfer.ts
  packages/spl/src/claimable-tokens/types.ts
  packages/spl/src/index.ts
  packages/web/.env/.env.dev
  packages/web/.env/.env.prod
  packages/web/.env/.env.stage
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/audius-sdk/solana.ts
Labels: size/XXL

#7003 Ignore legacy images in indexing
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#6997 As/fix profiles not loading
  packages/discovery-provider/ddl/migrations/0044_correct_picture_sizes.sql
Labels: size/XS

#6996 [PROTO-1524] Invalidate cache on refresh
  packages/common/src/store/lineup/actions.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
  packages/web/src/common/store/lineup/sagas.js
Labels: size/M

#6989 [C-3527] Add native artist previews
  packages/mobile/src/app/App.tsx
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/core/UserCoverPhoto.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/types.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/sign-on-screen/components/ArtistTile.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/PreviewArtistHint.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/web/src/pages/sign-up-page/components/PreviewArtistHint.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#6995 Publish sdk and fix publish flow
  packages/discovery-provider/plugins/pedalboard/packages/eslint-config-custom/package.json
  packages/eslint-config-audius/package.json
  packages/libs/package.json
Labels: size/XS

#7006 Fix sdk Storage retry logic
  packages/libs/src/sdk/services/Storage/Storage.ts
Labels: size/XS

#7004 [C-3539] Add harmony IconButton
  packages/harmony/src/components/button/BaseButton/BaseButton.tsx
  packages/harmony/src/components/button/IconButton/IconButton.mdx
  packages/harmony/src/components/button/IconButton/IconButton.stories.tsx
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/harmony/src/components/button/index.ts
  packages/harmony/src/components/button/types.ts
  packages/harmony/src/components/input/PasswordInput/PasswordInput.modules.css
  packages/harmony/src/components/input/PasswordInput/PasswordInput.tsx
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/app/index.ts
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/Button/types.ts
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/foundations/color/Color.stories.tsx
  packages/mobile/src/harmony-native/foundations/color/color.ts
  packages/mobile/src/harmony-native/foundations/motion/motion.ts
  packages/mobile/src/harmony-native/foundations/shadows/shadows.ts
  packages/mobile/src/harmony-native/foundations/theme/theme.ts
Labels: size/XL

#7008 Temporarily remove ddex image as required for releases
  .circleci/src/workflows/release.yml
Labels: size/XS

#6969 Index EM transactions for dashboard wallet users C-3529
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/models/dashboard_wallet_user/__init__.py
  packages/discovery-provider/src/models/dashboard_wallet_user/dashboard_wallet_user.py
  packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py
  packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#7011 [PAY-2315] Explicitly cancel transaction when closing coinflow drawer
  packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
Labels: size/XS

#7009 [PAY-1872] Add tests for USDC user bank indexer
  packages/discovery-provider/integration_tests/tasks/payment_router_mock_transactions.py
  packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
  packages/discovery-provider/integration_tests/tasks/user_bank_mock_transactions.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/XXL

#7012 Lower thresholds for prune and full prune on self-hosted ci machines
  .circleci/scripts/periodic-cleanup
Labels: size/XS

#7013 Add ddex to audius-compose and improve its build
  .circleci/src/workflows/release.yml
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.ddex.yml
  dev-tools/compose/docker-compose.yml
  packages/ddex/.dockerignore
  packages/ddex/Dockerfile
  packages/ddex/Dockerfile.fast
  packages/ddex/scripts/docker-entrypoint.sh
Labels: size/L

#7014 Build protocol dashboard 84x smaller in CI instead of at runtime
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.protocol-dashboard.dev.yml
  dev-tools/compose/docker-compose.protocol-dashboard.prod.yml
  dev-tools/compose/docker-compose.protocol-dashboard.stage.yml
  dev-tools/compose/docker-compose.yml
  protocol-dashboard/Dockerfile.fast
  protocol-dashboard/Dockerfile.prod
  protocol-dashboard/Dockerfile.stage
  protocol-dashboard/scripts/docker-entrypoint.sh
Labels: size/L

#6984 [Discovery] Add bulk get dashboard wallet users to Discovery Api [C-3532]
  packages/discovery-provider/src/api/v1/api.py
  packages/discovery-provider/src/api/v1/dashboard_wallet_users.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/dashboard_wallet_user.py
  packages/discovery-provider/src/queries/get_dashboard_wallet_users.py
Labels: size/L

#6971 [SDK] Add dashboard wallet users API to SDK [C-3530]
  packages/libs/src/sdk/api/dashboard-wallet-users/DashboardWalletUsersApi.ts
  packages/libs/src/sdk/api/dashboard-wallet-users/types.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/libs/src/sdk/utils/ethAddress.ts
Labels: size/L

#7015 Hotfix adding missing scripts to Dockerfile
  dev-tools/compose/docker-compose.protocol-dashboard.dev.yml
  protocol-dashboard/Dockerfile
  protocol-dashboard/Dockerfile.dev
  protocol-dashboard/Dockerfile.fast
  protocol-dashboard/Dockerfile.prod
  protocol-dashboard/Dockerfile.stage
Labels: size/M

#7017 Revert protocol dashboard changes
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.protocol-dashboard.dev.yml
  dev-tools/compose/docker-compose.protocol-dashboard.stage.yml
  dev-tools/compose/docker-compose.protocol-dashboard.yml
  dev-tools/compose/docker-compose.yml
  protocol-dashboard/Dockerfile
  protocol-dashboard/Dockerfile.dev
  protocol-dashboard/Dockerfile.fast
  protocol-dashboard/Dockerfile.prod
  protocol-dashboard/Dockerfile.stage
  protocol-dashboard/scripts/docker-entrypoint.sh
Labels: size/L

#7019 [Discovery] Fix response marshalling - Dashboard Wallet Users API
  packages/discovery-provider/src/api/v1/dashboard_wallet_users.py
Labels: size/XS

#7020 [Discovery] Discovery lint fix
  packages/discovery-provider/src/api/v1/dashboard_wallet_users.py
Labels: size/XS

#7022 Add back protocol dashboard improvements
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.protocol-dashboard.dev.yml
  dev-tools/compose/docker-compose.protocol-dashboard.prod.yml
  dev-tools/compose/docker-compose.protocol-dashboard.stage.yml
  dev-tools/compose/docker-compose.yml
  protocol-dashboard/Dockerfile
  protocol-dashboard/Dockerfile.dev
  protocol-dashboard/Dockerfile.fast
  protocol-dashboard/Dockerfile.prod
  protocol-dashboard/Dockerfile.stage
  protocol-dashboard/scripts/docker-entrypoint.sh
Labels: size/L

#7024 Make CI sed more specific
  .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
Labels: size/XS
