Repository AudiusProject/apps, pull requests merged in 2023-05, with the labels that each got.

#5190 Remove auto start ES
  discovery-provider/scripts/start.sh
Labels: size/XS

#5182 Adds function to check for column before trying to add it.
  discovery-provider/alembic/env.py
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/L

#5187 Enable stage deploys
  .circleci/workflows/main.yml
  dev-tools/audius-compose
Labels: size/M

#5189 Fix broken test
  discovery-provider/integration_tests/tasks/test_index_helper.py
Labels: size/XS

#5192 Fix browser push when user doesn't have browsers
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
Labels: size/XS

#5185 [PLAT-947] Filter out disabled notifications from scheduled emails
  discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/multipleMappings.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tastemaker.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingPlaylist.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingUnderground.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
Labels: size/XXL

#5195 Add tracks_ai_attribution index
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/XS

#5197 Allow null ai attribution in tracks full route
  discovery-provider/src/api/v1/models/tracks.py
Labels: size/XS

#5178 Create notifs for newly unlisted tracks or newly public playlists
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
Labels: size/M

#5198 Resend recent websocket messages on reconnect.
  comms/discovery/rpcz/websocket.go
Labels: size/M

#5181 Fix handle_track trigger...
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/integration_tests/models/test_aggregate_counters.py
Labels: size/M

#5193 [C-2506] Sdk uploadTrack with EntityManager
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/index.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/services/EntityManager/index.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/constants.ts
  libs/src/sdk/services/Storage/index.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageService/StorageService.ts
  libs/src/sdk/services/StorageService/index.ts
  libs/src/sdk/services/StorageService/types.ts
  libs/src/sdk/services/WalletApi/WalletApi.ts
  libs/src/sdk/services/WalletApi/types.ts
  libs/src/sdk/services/index.ts
  libs/src/sdk/utils/cid.ts
  libs/src/sdk/utils/hashId.ts
  libs/src/sdk/utils/object.ts
  libs/src/sdk/utils/retry.ts
  sdk-consumer/index.ts
  sdk-consumer/package-lock.json
  sdk-consumer/package.json
Labels: size/XL

#5171 Send metadata directly through chain
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  libs/src/api/Account.ts
  libs/src/api/File.ts
  libs/src/api/Track.ts
  libs/src/api/Users.ts
  libs/src/api/entityManager.ts
  libs/src/sanityChecks/addSecondaries.ts
  libs/src/sanityChecks/assignReplicaSetIfNecessary.ts
  libs/src/sanityChecks/index.ts
  libs/src/sanityChecks/rolloverNodes.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/L

#5200 [PLAT-963] plugin should not send emails if no valid notifs available
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
Labels: size/M

#5206 Increase update aggregate frequency
  discovery-provider/src/app.py
Labels: size/XS

#5205 [PAY-1206] Remove documentation from DN endpoints not included in API
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/users.py
Labels: size/M

#5132 add new guard and test for old uploads
  discovery-provider/plugins/verified-uploads/README.md
  discovery-provider/plugins/verified-uploads/src/handlers/test.js
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
Labels: size/M

#5209 Add back doc for UserIdByAssociatedWallet endpoint
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5213 Strip cid newline for stream
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/src/api/v1/tracks.py
Labels: size/S

#5212 SDK: Prevent double endpoints
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
Labels: size/S

#5214 Remove whitespace in cid migration
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/XS

#5207 Dedupe reaction notifs
  discovery-provider/alembic/trigger_sql/handle_reaction.sql
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
Labels: size/L

#5203 [PLAT-767] Fix eth contracts tests
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.test.yml
  eth-contracts/.eslintrc.js
  eth-contracts/.prettierrc.js
  eth-contracts/Dockerfile.dev
  eth-contracts/contract-config.js
  eth-contracts/package-lock.json
  eth-contracts/package.json
  eth-contracts/scripts/circleci-test-no-coverage.sh
  eth-contracts/scripts/circleci-test.sh
  eth-contracts/scripts/lint.sh
  eth-contracts/scripts/static_analysis.md
  eth-contracts/scripts/truffle-test.sh
  eth-contracts/test/audiusToken.test.js
  eth-contracts/test/ethRewardsManager.test.js
  eth-contracts/test/governance.test.js
  eth-contracts/test/staking.test.js
  eth-contracts/test/wormholeClient.test.js
  eth-contracts/truffle-config.js
  eth-contracts/utils/lib.js
Labels: size/XXL

#5215 Get audius-cmd to run again
  .circleci/workflows/main.yml
  dev-tools/audius-cmd
Labels: size/XS

#5201 Revoke app delegate EM action C-2559
  discovery-provider/alembic/trigger_sql/ddl.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_delegate_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/delegates/app_delegate.py
  discovery-provider/src/tasks/entity_manager/app_delegate.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#5216 SDK: Update tests to match what context comes back with
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
Labels: size/S

#5194 [CON-681] Reconcile storage v2 ffmpeg differences
  mediorum/server/transcode.go
Labels: size/S

#5208 Add revoke delegation functionality to EM (Discovery) C-2562
  discovery-provider/integration_tests/tasks/entity_manager/test_delegation_entity_manager.py
  discovery-provider/src/tasks/entity_manager/delegation.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#5204 [CON-676] Support storage v2 playlists+albums, and clean up track upload
  discovery-provider/integration_tests/models/test_aggregate_counters.py
  discovery-provider/integration_tests/queries/test_notifications/test_repost_notification.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  libs/src/api/Playlist.ts
  libs/src/api/Track.ts
  libs/src/api/entityManager.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/solana/rewardsAttester.ts
Labels: size/L

#5219 Hot fix duration key error
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#5218 Use window web3 in sdk when available
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/utils/web3.ts
Labels: size/M

#5191 PLAT-945: browser push feature flag
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/web.ts
Labels: size/L

#5217 [PLAT-684] Fix audius-cmd tests
  .circleci/jobs/test-audius-cmd.yml
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/upload-track.mjs
  dev-tools/commands/test/create-user.bats
  dev-tools/commands/test/upload-track.bats
  libs/src/api/Users.ts
  libs/src/eth-contracts/ABIs/Wormhole.json
Labels: size/L

#5221 Use npm for tests
  dev-tools/commands/test/create-user.bats
  dev-tools/commands/test/upload-track.bats
Labels: size/XS

#5220 Fix flaky DMs tests
  discovery-provider/plugins/notifications/scripts/test-push-notification.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/main.ts
Labels: size/L

#5224 Test to fix
  .circleci/jobs/test-audius-cmd.yml
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/utils.mjs
Labels: size/S

#5211 Add prod metadata tsv to backfill
  discovery-provider/src/app.py
  discovery-provider/src/tasks/backfill_cid_data.py
Labels: size/XS

#5228 Undocument album and playlist favorites routes
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5223 Trim default audius-compose, make audius-cmd use storage v2, and fix server-side v2 upload
  .circleci/jobs/build-gcp-image.yml
  .circleci/jobs/push-docker-image.yml
  .circleci/jobs/test-audius-cmd.yml
  .circleci/jobs/test.yml
  dev-tools/README.md
  dev-tools/audius-compose
  dev-tools/commands/package-lock.json
  dev-tools/commands/package.json
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/upload-track.mjs
  dev-tools/commands/src/utils.mjs
  dev-tools/compose/docker-compose.storagev2.yml
  dev-tools/setup.sh
  libs/src/AudiusLibs.ts
  libs/src/services/creatorNode/CreatorNode.ts
  mediorum/Dockerfile
Labels: size/L

#5233 Fix CircleCI status badge
  README.md
Labels: size/XS

#5234 Remove documentation for supporter user route
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5235 [PAY-1238] Chats sdk unread messages count
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#5231 PLAT-781: nm healthz improvements
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/S

#5238 Fix libs startup race condition
  .circleci/jobs/test.yml
  dev-tools/compose/docker-compose.dev.yml
Labels: size/S

#5240 healthz DM mutual world view matrix
  monitoring/healthz/package-lock.json
  monitoring/healthz/src/DMMatrix.tsx
  monitoring/healthz/src/Router.tsx
Labels: size/M

#5229 sig recovery works
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/serve_blob.go
  mediorum/server/signature/signature.go
  mediorum/server/signature/signature_test.go
Labels: size/M

#5241 handle undefined string
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/S

#5230 PLAT-970: push latest nethermind image to dockerhub
  discovery-provider/chain/Dockerfile.acdc
  discovery-provider/chain/README.md
  discovery-provider/chain/publish.sh
Labels: size/S

#5237 DMs permissions updates
  comms/discovery/db/queries/get_chat_permissions.go
  comms/discovery/db/queries/get_chats.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/validator.go
  comms/discovery/schema/schema.go
  comms/discovery/schema/schema.ts
  comms/discovery/server/response_mapper.go
  comms/discovery/server/server_test.go
  dev-tools/compose/docker-compose.comms.yml
  libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#5210 [CON-683] Make client and discovery use CN v2 health checks
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/app.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/eth_contracts_helpers.py
  libs/src/utils/getNStorageNodes.test.ts
  libs/src/utils/getNStorageNodes.ts
Labels: size/L

#5239 PLAT-955: default to local RPC and fallback to gateway
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/S

#5242 dms: ordered queue to push messages to peers
  comms/.dockerignore
  comms/Dockerfile
  comms/DockerfileFast
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/broadcast.go
  comms/discovery/rpcz/peer_client.go
  comms/discovery/rpcz/sync_client.go
  comms/docker-compose.monitor.yml
  comms/shared/signing/basic.go
Labels: size/L

#5244 Add /internal nginx proxy rule. Enable cid beam in prod
  comms/discovery/rpcz/broadcast.go
  creator-node/nginx_conf/nginx.conf
  mediorum/server/cid_log_client.go
  mediorum/server/server.go
Labels: size/M

#5236 Allow delegated track writes in EM C-2294
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/tasks/entity_manager/delegation.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/track.py
Labels: size/L

#5247 Revert "Revert "PLAT-955: default to local RPC and fallback to gateway""
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/M

#5246 improve logging on stage identity
  identity-service/src/relay/txRelay.js
Labels: size/S

#5250 Break apart CI jobs, auto publish sdk
  .circleci/@orbs.yml
  .circleci/@parameters.yml
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/gcp-auth.yml
  .circleci/src/commands/gcp-checkout.yml
  .circleci/src/commands/gcp-run.yml
  .circleci/src/jobs/build-gcp-image.yml
  .circleci/src/jobs/deploy.yml
  .circleci/src/jobs/gcp-cleanup.yml
  .circleci/src/jobs/push-docker-image.yml
  .circleci/src/jobs/release-audius-docker-compose.yml
  .circleci/src/jobs/release-audius-sdk.yml
  .circleci/src/jobs/release-create-branch.yml
  .circleci/src/jobs/release-discord.yml
  .circleci/src/jobs/release-github-draft.yml
  .circleci/src/jobs/release-github.yml
  .circleci/src/jobs/release-governance.yml
  .circleci/src/jobs/test-audius-cmd.yml
  .circleci/src/jobs/test.yml
  .circleci/src/workflows/contracts.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/eth-contracts.yml
  .circleci/src/workflows/gcp-cleanup.yml
  .circleci/src/workflows/gcp.yml
  .circleci/src/workflows/identity.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/sdk.yml
  .circleci/workflows/gcp-cleanup.yml
  .circleci/workflows/main.yml
  .circleci/workflows/release-audius-sdk.yml
  .circleci/workflows/release-create-branch.yml
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.test.yml
  libs/scripts/release.sh
Labels: size/XL

#5257 Improve new CI workflows
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/release-audius-sdk.yml
  .circleci/src/workflows/sdk.yml
  contracts/test/userReplicaSetManager.js
  dev-tools/compose/docker-compose.test.yml
  libs/package.json
Labels: size/L

#5251 Clean up notifications tests
  .circleci/src/commands/gcp-run.yml
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/userNotificationSettings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/listener.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/L

#5232 Allow AuthService to accept apiKey and apiSecret
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/Auth/AppAuth.ts
  libs/src/sdk/services/Auth/Auth.ts
  libs/src/sdk/services/Auth/index.ts
  libs/src/sdk/services/Auth/types.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/WalletApi/WalletApi.ts
  libs/src/sdk/services/WalletApi/index.ts
  libs/src/sdk/services/WalletApi/types.ts
  libs/src/sdk/services/index.ts
  sdk-consumer/index.ts
Labels: size/L

#5260 Cid beam limit
  mediorum/ddl/ddl.go
  mediorum/server/cid_log_client.go
  mediorum/server/cid_log_server.go
  mediorum/server/cid_log_test.go
  mediorum/server/health.go
  mediorum/server/server.go
Labels: size/M

#5261 Add mediorum
  .circleci/src/workflows/creator.yml
Labels: size/XS

#5262 Add mediorum test
  .circleci/src/workflows/creator.yml
Labels: size/XS

#5258 Separate main and release CI flows
  .circleci/config.yml
  .circleci/src/jobs/build-gcp-image.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/identity.yml
  contracts/test/userReplicaSetManager.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/audiusUsers.test.js
  dev-tools/audius-compose
Labels: size/L

#5263 No release on main
  .circleci/config.yml
Labels: size/XS

#5264 Drop unused libs test script
  libs/package.json
  libs/scripts/circleci-test.sh
Labels: size/M

#5252 Validate blocks and permissions on chat react
  comms/discovery/rpcz/validator.go
Labels: size/M

#5249 PLAT-981: fix peer count in health z
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XS

#5269 [INF-379] Make pre-commit hook fast
  check_secrets.sh
Labels: size/XS

#5267 Sanitize cid metadata from chain
  discovery-provider/integration_tests/tasks/test_index_helper.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/utils/cid_metadata_client.py
Labels: size/S

#5273 [Flare-178] Add recurring sync queue null check
  creator-node/src/components/replicaSet/replicaSetController.js
Labels: size/XS

#5276 flare-178: disable cid beam, truncate cid_lookup table.
  mediorum/ddl/ddl.go
  mediorum/server/cid_log_client.go
  mediorum/server/health.go
  mediorum/server/server.go
Labels: size/S

#5271 Add skip_play_count flag
  creator-node/src/routes/tracks.js
  dev-tools/commands/src/upload-track.mjs
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_tracks.py
Labels: size/S

#5277 exit with error if truncate fails
  mediorum/ddl/ddl.go
Labels: size/XS

#5278 Add skreamizm
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/M

#5272 [PLAT-943] rm personal bcc on email notifications
  discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts
Labels: size/XS

#5279 [PLAT-990] add notifications logs to axiom
  monitoring/vector/vector.toml
Labels: size/XS

#5281 Fix release branch
  .circleci/config.yml
  .circleci/src/jobs/release-create-branch.yml
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/M

#5282 Fix migration idempotency
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/S

#5222 Clean up server logs
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/scripts/prod-server.sh
  discovery-provider/src/challenges/create_new_challenges.py
  discovery-provider/src/queries/block_confirmation.py
  discovery-provider/src/queries/get_trailing_metrics.py
  discovery-provider/src/queries/get_unclaimed_id.py
  discovery-provider/src/queries/get_users.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/queries/queries.py
Labels: size/M

#5255 [CON-688] Make mediorum poll for delisted statuses
  mediorum/ddl/ddl.go
  mediorum/ddl/delist_statuses.sql
  mediorum/ethcontracts/abis.go
  mediorum/ethcontracts/ethcontracts.go
  mediorum/main.go
  mediorum/server/delist_statuses.go
  mediorum/server/delist_statuses_test.go
  mediorum/server/serve_contact.go
  mediorum/server/serve_legacy.go
  mediorum/server/server.go
  mediorum/server/server_basic_auth.go
  mediorum/server/signature/basic_auth.go
Labels: size/XXL

#5284 Remove loggly code
  discovery-provider/scripts/start.sh
Labels: size/M

#5288 Tiebreak order_bys in get_tracks
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_tracks.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/M

#5290 Run delist migration separately from cid_lookup
  mediorum/ddl/ddl.go
Labels: size/S

#5283 Fix DN re-selection in SDK
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
Labels: size/L

#5296 fix indexing stall
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/XS

#5291 [CON-678] Add v2 edit-user to audius-cmd
  creator-node/test/CNodeHealthManager.test.js
  dev-tools/commands/src/edit-user.mjs
  dev-tools/commands/src/index.mjs
  libs/src/api/Users.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/schemaValidator/schemas/playlistSchema.json
  libs/src/services/schemaValidator/schemas/userSchema.json
  libs/src/utils/getNStorageNodes.test.ts
  libs/src/utils/getNStorageNodes.ts
  mediorum/server/transcode.go
Labels: size/L

#5083 PLAT-821: announcements
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
Labels: size/L

#5295 Bring back cid in responses
  discovery-provider/src/queries/queries.py
Labels: size/XS

#5300 Fix time in delist-status test to match postgres
  mediorum/server/delist_statuses.go
  mediorum/server/delist_statuses_test.go
Labels: size/L

#5298 Comms health
  comms/discovery/discovery_main.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/peer_client.go
  comms/discovery/server/server.go
Labels: size/M

#5287 [PLAT-821]: Fix announcement notification reads from discovery
  discovery-provider/integration_tests/queries/test_notifications/test_announcement_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/M

#5289 [PLAT-1005] Add track added to playlist notification to get_notificat…
  discovery-provider/integration_tests/queries/test_notifications/test_track_added_to_playlist_notification.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/M

#5301 Reenable CID beam, omit tracks (segments) this time.
  mediorum/.initdb/init.sql
  mediorum/bash_scripts/deploy_mediorum.sh
  mediorum/ddl/cid_lookup.sql
  mediorum/ddl/ddl.go
  mediorum/ddl/test/cid_lookup_test.sql
  mediorum/server/cid_log_test.go
  mediorum/server/db.go
  mediorum/server/server.go
Labels: size/L

#5304 Remove status check when fetching CNs
  discovery-provider/src/utils/eth_contracts_helpers.py
Labels: size/XS

#5297 Only apply skreamizm fix once
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/M

#5305 Invalidate old skreamizm records
  discovery-provider/alembic/trigger_sql/ddl.sql
Labels: size/S

#5292 [PLAT-951] Add port exposure check
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/nginx_conf/port.lua
Labels: size/M

#5306 [PLAT-1007] Fix sort by coelesce
  discovery-provider/src/queries/get_tracks.py
Labels: size/S

#5303 Reuse web3 instance
  discovery-provider/src/utils/web3_provider.py
Labels: size/XS

#5312 Simple PR template
  .github/pull_request_template.md
Labels: size/S

#5310 Remove duplicate content script
  creator-node/scripts/delistContent/apiSigning.js
  creator-node/scripts/delistContent/commanderHelper.js
  creator-node/scripts/delistContent/hashIds.js
  creator-node/scripts/delistContent/index.js
Labels: size/XL

#5311 Lint eth contracts js
  eth-contracts/.eslintrc.js
  eth-contracts/migrations/10_wormhole_client_migration.js
  eth-contracts/migrations/11_eth_rewards_manager_migration.js
  eth-contracts/migrations/12_trusted_notifier_manager_migration.js
  eth-contracts/migrations/13_delegate_manager_v2_migration.js
  eth-contracts/migrations/1_initial_migration.js
  eth-contracts/migrations/2_registry_migration.js
  eth-contracts/migrations/3_governance_migration.js
  eth-contracts/migrations/4_token_migration.js
  eth-contracts/migrations/5_staking_migration.js
  eth-contracts/migrations/6_claims_manager_migration.js
  eth-contracts/migrations/7_versioning_service_migration.js
  eth-contracts/migrations/8_delegate_manager_migration.js
  eth-contracts/package.json
  eth-contracts/scripts/get-address.js
  eth-contracts/scripts/migrate-contracts.js
  eth-contracts/scripts/release-governance.js
  eth-contracts/scripts/setup-dev.js
  eth-contracts/test/claimsManager.test.js
  eth-contracts/test/delegateManager.test.js
  eth-contracts/test/delegateManagerV2.test.js
  eth-contracts/test/random/random.test.js
  eth-contracts/test/registry.test.js
  eth-contracts/test/serviceProvider.test.js
  eth-contracts/test/trustedNotifierManager.test.js
  eth-contracts/test/upgradeability.test.js
  eth-contracts/utils/lib.js
  eth-contracts/utils/signatures.js
Labels: size/XXL

#5313 [PLAT-982] Join comms and server health checks
  discovery-provider/nginx_conf/nginx.conf
Labels: size/S

#5265 Add warnings in CN for disallowed mp3 streaming
  creator-node/package-lock.json
  creator-node/package.json
  creator-node/src/is-mp3.d.ts
  creator-node/src/routes/files.js
  creator-node/src/routes/tracks.js
  creator-node/src/utils/fileUtils.ts
  creator-node/src/utils/index.ts
  monitoring/healthz/src/AudiusSurvivalKit.ts
Labels: size/L

#5316 Fix health_check CORS
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#5150 SDK - add developer apps and grants APIs for corresponding EM actions C-2290 C-2291
  libs/src/sdk/api/developer-apps/DeveloperAppsAPI.ts
  libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  libs/src/sdk/api/developer-apps/constants.ts
  libs/src/sdk/api/developer-apps/types.ts
  libs/src/sdk/api/grants/GrantsAPI.ts
  libs/src/sdk/api/grants/constants.ts
  libs/src/sdk/api/grants/types.ts
  libs/src/sdk/index.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/EntityManager/types.ts
Labels: size/L

#5319 Delete DeveloperAppsAPI.ts
  libs/src/sdk/api/developer-apps/DeveloperAppsAPI.ts
Labels: size/L

#5270 Add Entity Manager bootstrap config C-2629
  libs/package.json
  libs/src/sdk/config/development.ts
  libs/src/sdk/config/index.ts
  libs/src/sdk/config/production.ts
  libs/src/sdk/config/staging.ts
  libs/src/sdk/config/types.ts
  libs/src/sdk/scripts/generateServicesConfig.ts
  libs/src/sdk/services/EntityManager/constants.ts
Labels: size/L

#5315 [PLAT-982] SDK: Select DNs with healthy comms
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/L

#5322 Fix skip ci on libs/*
  libs/scripts/release.sh
Labels: size/XS

#5324 [C-2695] Expose content-nodes in discovery-node health-check
  discovery-provider/src/queries/confirm_indexing_transaction_error.py
  discovery-provider/src/queries/get_attestation.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_redirect_weights.py
  discovery-provider/src/tasks/cache_current_nodes.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_network_peers.py
  discovery-provider/src/utils/get_all_other_nodes.py
Labels: size/L

#5325 [PLAT-1019] Add since to comms debug cursors
  comms/discovery/server/server.go
Labels: size/S

#5320 [C-2520] sdk trackUpload schema validation
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/types/Genre.ts
  libs/src/sdk/types/HashId.ts
  libs/src/sdk/types/Mood.ts
  libs/src/sdk/utils/parseRequestParameters.ts
  sdk-consumer/index.ts
Labels: size/L

#5329 Check tg_op for segments in Files trigger
  mediorum/ddl/cid_lookup.sql
Labels: size/S

#5318 [PLAT-1018] Add playlist owner id to add track to playlist notif metadata
  discovery-provider/alembic/trigger_sql/handle_playlist.sql
  discovery-provider/integration_tests/notifications/test_playlist.py
  discovery-provider/integration_tests/queries/test_notifications/test_track_added_to_playlist_notification.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/S

#5328 Fix test
  .circleci/src/jobs/deploy.yml
  discovery-provider/integration_tests/queries/test_get_attestation.py
Labels: size/XS

#5333 Shut off stage auto deploy
  .circleci/src/workflows/discovery.yml
Labels: size/S

#5331 Move block diff in healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
  package-lock.json
Labels: size/XS

#5326 [PAY-1298] DN4 can read from peers
  comms/discovery/server/basic_auth.go
Labels: size/XS

#5334 PLAT-1020: add better signer comparison
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XS

#5321 Remove code that depends on or enforces segments
  creator-node/src/logging.ts
  creator-node/src/routes/tracks.js
  libs/src/api/Track.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/L

#5330 Pipe chain logs
  monitoring/vector/vector.toml
Labels: size/XS

#5336 Revert "Shut off stage auto deploy (#5333)"
  .circleci/src/workflows/discovery.yml
Labels: size/S

#5337 SDK: Check comms at root
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/L
