Repository AudiusProject/apps, pull requests merged in 2023-02, with the labels that each got.

#4697 Cherry pick and reconcile repost fix migration
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/versions/72b030bb3dcb_handle_repost_fix.py
  discovery-provider/alembic/versions/a62b4e92b733_fix_nullified_track_cid.py
Labels: size/M

#4680 Remove anchor audius data from solana-programs build
  docker-compose.yml
  solana-programs/Dockerfile
  solana-programs/Dockerfile.dev
  solana-programs/scripts/build.sh
Labels: size/M

#4692 [CON-558] Add bucketing logic and e2e storer, and refactor
  comms/go.mod
  comms/go.sum
  comms/storage/bucketer/bucketer.go
  comms/storage/bucketer/bucketer_test.go
  comms/storage/decider/RendezvousDecider.go
  comms/storage/decider/StorageDecider.go
  comms/storage/glue/glue.go
  comms/storage/storage_main.go
  comms/storage/storageserver/static/cool.html
  comms/storage/storageserver/static/hello.txt
  comms/storage/storageserver/static/status.html
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
  comms/storage/storageserver/test.mp3
  comms/storage/transcode/jobs.go
  comms/storage/transcode/jobs_test.go
  comms/storage/web/web.go
Labels: size/XL

#4707 Fix autoflush arg in session
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/XS

#4706 Fix identity solana listen test
  identity-service/test/routes/trackListensTest.js
Labels: size/S

#4703 Update docker-compose.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: size/S

#4708 [C-2005] Remove filter deleted on individual discovery node tracks
  discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#4701 Fix top playlists with user_id
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/queries/get_top_playlists.py
  discovery-provider/src/queries/queries.py
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/S

#4712 Archive plays up to 2022
  discovery-provider/src/tasks/prune_plays.py
Labels: size/XS

#4715 [CON-576] Add prometheus middleware to echo server
  comms/go.mod
  comms/go.sum
  comms/storage/storageserver/storageserver.go
  comms/storage/telemetry/metrics.go
Labels: size/L

#4714 [CON-567] Add a simple load test
  comms/Makefile
Labels: size/XS

#4702 [CON-571] Add prometheus exporter to storage server API
  comms/go.mod
  comms/go.sum
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
Labels: size/XL

#4711 [CON-573] Add telemetry package with tracing methods
  comms/Makefile
  comms/discovery/schema/schema.go
  comms/docker-compose.monitor.yml
  comms/go.mod
  comms/go.sum
  comms/monitoring/README.md
  comms/monitoring/grafana-jetstream-dash-helm.json
  comms/monitoring/grafana-jetstream-dash.json
  comms/monitoring/grafana-nats-dash.json
  comms/monitoring/grafana-nss-dash.json
  comms/monitoring/prometheus.yml
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
  comms/storage/telemetry/README.md
  comms/storage/telemetry/logger.go
  comms/storage/telemetry/metrics.go
  comms/storage/telemetry/tracer.go
  comms/storage/transcode/jobs.go
Labels: size/XXL

#4709 [CON-562] Store files in sharded tmp buckets, download to abstract storage (default disk)
  .vscode/launch.json
  comms/Makefile
  comms/go.mod
  comms/go.sum
  comms/storage/bucketer/bucketer.go
  comms/storage/bucketer/bucketer_test.go
  comms/storage/decider/RendezvousDecider.go
  comms/storage/decider/StorageDecider.go
  comms/storage/longterm/longterm.go
  comms/storage/storageserver/static/status.html
  comms/storage/storageserver/storageserver.go
  comms/storage/transcode/create_bucket.go
  comms/storage/transcode/jobs.go
  comms/storage/transcode/jobs_test.go
Labels: size/XXL

#4718 NO-TICKET: fix link for template generation in SDK
  libs/src/sdk/api/generator/gen.js
Labels: size/XS

#4719 Remove user bank from sdk signup
  libs/src/api/Account.ts
Labels: size/M

#4691 Update playlist sitemap
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/src/queries/get_sitemap.py
Labels: size/M

#4720 Use dummy container for solana tests
  docker-compose.test.yml
Labels: size/S

#4727 Fix TikTok association
  identity-service/src/routes/tiktok.js
Labels: size/XS

#4710 Serve top playlists from ElasticSearch
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/src/queries/get_top_playlists.py
  discovery-provider/src/queries/get_top_playlists_es.py
Labels: size/L

#4725 Encode artist pick track id in API responses
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/users.py
Labels: size/XS

#4732 Is more pruning
  discovery-provider/src/app.py
Labels: size/XS

#4731 libs: Use proper types in identityService.getUserBankTransactionMetadata
  libs/src/services/identity/IdentityService.ts
Labels: size/XS

#4713 Add is_repost_repost column to reposts table
  discovery-provider/alembic/versions/988f095a1d43_add_is_repost_repost_column.py
  discovery-provider/src/models/social/repost.py
Labels: size/S

#4733 Fix is_available on three tracks
  discovery-provider/alembic/versions/6f98e9709e3e_fix_is_available.py
  discovery-provider/alembic/versions/988f095a1d43_add_is_repost_repost_column.py
Labels: size/M

#4700 PLAT-618: fix cache decorator
  discovery-provider/src/utils/redis_cache.py
Labels: size/XS

#4739 [Libs] Fix types for identityservice in libs
  libs/src/services/identity/IdentityService.ts
Labels: size/XS

#4729 Add weather map
  comms/Dockerfile.v2
  comms/Makefile
  comms/storage/bucketer/bucketer.go
  comms/storage/decider/RendezvousDecider.go
  comms/storage/decider/StorageDecider.go
  comms/storage/longterm/longterm.go
  comms/storage/monitor/monitor.go
  comms/storage/sharder/sharder.go
  comms/storage/sharder/sharder_test.go
  comms/storage/storageserver/static/status.html
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
  comms/storage/storageserver/weather-map/.eslintignore
  comms/storage/storageserver/weather-map/.eslintrc.cjs
  comms/storage/storageserver/weather-map/.gitignore
  comms/storage/storageserver/weather-map/.prettierignore
  comms/storage/storageserver/weather-map/.prettierrc.cjs
  comms/storage/storageserver/weather-map/README.md
  comms/storage/storageserver/weather-map/dist/assets/index-cd96c4e5.css
  comms/storage/storageserver/weather-map/dist/assets/index-e2841262.js
  comms/storage/storageserver/weather-map/dist/index.html
  comms/storage/storageserver/weather-map/index.html
  comms/storage/storageserver/weather-map/package.json
  comms/storage/storageserver/weather-map/postcss.config.cjs
  comms/storage/storageserver/weather-map/src/App.tsx
  comms/storage/storageserver/weather-map/src/api.ts
  comms/storage/storageserver/weather-map/src/components/filesTable/ErrorRow.tsx
  comms/storage/storageserver/weather-map/src/components/filesTable/FilesTable.tsx
  comms/storage/storageserver/weather-map/src/components/filesTable/FilesTableWrapper.tsx
  comms/storage/storageserver/weather-map/src/components/filesTable/HealthyRow.tsx
  comms/storage/storageserver/weather-map/src/components/nodes/Nodes.tsx
  comms/storage/storageserver/weather-map/src/components/search/Search.tsx
  comms/storage/storageserver/weather-map/src/index.css
  comms/storage/storageserver/weather-map/src/main.tsx
  comms/storage/storageserver/weather-map/src/routes/Home.tsx
  comms/storage/storageserver/weather-map/src/routes/Shard.tsx
  comms/storage/storageserver/weather-map/src/routes/Wrapper.tsx
  comms/storage/storageserver/weather-map/src/util.ts
  comms/storage/storageserver/weather-map/src/vite-env.d.ts
  comms/storage/storageserver/weather-map/tailwind.config.cjs
  comms/storage/storageserver/weather-map/tsconfig.json
  comms/storage/storageserver/weather-map/tsconfig.node.json
  comms/storage/storageserver/weather-map/vite.config.ts
  comms/storage/storageserver/weather-map/weather-map.code-workspace
  comms/storage/storageserver/weather-map/yarn.lock
  comms/storage/transcode/jobs.go
Labels: size/XXL

#4742 Remove unused packages in storage build
  comms/Dockerfile.v2
Labels: size/XS

#4737 add is_repost_repost comment for clarification
  discovery-provider/src/models/social/repost.py
Labels: size/XS

#4743 Read private key and host from stage+prod env vars
  comms/storage/storageserver/storageserver.go
Labels: size/S

#4746 middlewares for nats server
  comms/natsd/nats_main.go
Labels: size/XS

#4741 Remove docker m1 files
  docker-compose.m1.test.yml
  docker-compose.m1.yml
Labels: size/L

#4508 Update libs to relay EM to POA and ACDC
  libs/src/services/contracts/ContractClient.ts
  libs/src/services/dataContracts/EntityManagerClient.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/services/web3Manager/Web3Manager.ts
Labels: size/M

#4740 Index 1 block behind to avoid reverting
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/XS

#4748 Prepend https:// to creatorNodeEndpoint
  creator-node/src/serviceRegistry.js
Labels: size/XS

#4734 SDK: Allow updating DN selector config after initializing
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/constants.ts
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
  libs/src/sdk/utils/deepPartial.ts
Labels: size/M

#4750 SDK: Update CI to allow version, preid to be specified
  .circleci/config.yml
  libs/scripts/release.sh
Labels: size/S

#4686 [PAY-786][PAY-876] Filter out collectible gated tracks from feed and trending
  discovery-provider/src/premium_content/premium_content_constants.py
  discovery-provider/src/queries/get_feed.py
  discovery-provider/src/queries/get_feed_es.py
  discovery-provider/src/queries/get_remixes_of.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
Labels: size/L

#4482 [PLAT-518] Remove old metrics code
  discovery-provider/integration_tests/queries/test_get_aggregate_route_metrics.py
  discovery-provider/integration_tests/queries/test_get_app_name_metrics.py
  discovery-provider/integration_tests/queries/test_get_historical_route_metrics.py
  discovery-provider/integration_tests/queries/test_get_route_metrics.py
  discovery-provider/src/api/v1/metrics.py
  discovery-provider/src/api/v1/models/metrics.py
  discovery-provider/src/app.py
  discovery-provider/src/models/metrics/app_metrics_all_time.py
  discovery-provider/src/models/metrics/app_metrics_trailing_month.py
  discovery-provider/src/models/metrics/app_metrics_trailing_week.py
  discovery-provider/src/models/metrics/app_name_metrics.py
  discovery-provider/src/models/metrics/route_metrics.py
  discovery-provider/src/models/metrics/route_metrics_all_time.py
  discovery-provider/src/models/metrics/route_metrics_day_matview.py
  discovery-provider/src/models/metrics/route_metrics_month_matview.py
  discovery-provider/src/models/metrics/route_metrics_trailing_month.py
  discovery-provider/src/models/metrics/route_metrics_trailing_week.py
  discovery-provider/src/queries/get_aggregate_route_metrics.py
  discovery-provider/src/queries/get_app_name_metrics.py
  discovery-provider/src/queries/get_app_name_metrics_unit_test.py
  discovery-provider/src/queries/get_app_names.py
  discovery-provider/src/queries/get_app_names_unit_test.py
  discovery-provider/src/queries/get_historical_route_metrics.py
  discovery-provider/src/queries/get_trailing_metrics.py
  discovery-provider/src/tasks/index_metrics.py
  discovery-provider/src/tasks/index_metrics_unit_test.py
  discovery-provider/src/utils/redis_metrics.py
Labels: size/XXL

#4753 Fix crontab import lint error
  discovery-provider/src/app.py
Labels: size/XS

#4698 Local compose with comms
  comms/DockerfileM1
  dev-tools/audius-compose
  docker-compose.yml
Labels: size/M

#4756 SDK: Update template to allow raw string body
  libs/src/sdk/api/generated/default/models/User.ts
  libs/src/sdk/api/generated/default/runtime.ts
  libs/src/sdk/api/generated/full/models/UserFull.ts
  libs/src/sdk/api/generated/full/runtime.ts
  libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache
Labels: size/S

#4749 Improve storage v2 config
  comms/.air.toml
  comms/Makefile
  comms/discovery/discovery_main.go
  comms/docker-compose.v2.dev.yml
  comms/docker-compose.v2.yml
  comms/go.mod
  comms/go.sum
  comms/natsd/nats_main.go
  comms/shared/peering/nats_connection.go
  comms/shared/peering/sps.go
  comms/storage/config/config.go
  comms/storage/decider/RendezvousDecider.go
  comms/storage/longterm/longterm.go
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
  comms/storage/transcode/jobs.go
Labels: size/L

#4755 SDK: Succeed API response healthcheck if version field not on response
  libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/XS

#4752 SDK: Update bootstrap to be for each env
  libs/package.json
  libs/src/sdk/config/development.ts
  libs/src/sdk/config/index.ts
  libs/src/sdk/config/production.ts
  libs/src/sdk/config/staging.ts
  libs/src/sdk/config/types.ts
  libs/src/sdk/index.ts
  libs/src/sdk/scripts/generateBootstrapConfig.ts
  libs/src/sdk/services/DiscoveryNodeSelector/constants.ts
  libs/src/sdk/services/DiscoveryNodeSelector/generateBootstrapConfig.ts
Labels: size/L

#4758 Revert "Local compose with comms (#4698)"
  comms/DockerfileM1
  dev-tools/audius-compose
  docker-compose.yml
Labels: size/M

#4721 Remove pinnedTrackId from SocialHandles in identity
  identity-service/default-config.json
  identity-service/sequelize/migrations/20230206073741-drop-pinned-track-id.js
  identity-service/src/models/socialhandles.js
  identity-service/src/routes/artistPick.js
Labels: size/M

#4751 Custom DM email notification frequency
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  docker-compose.yml
Labels: size/L

#4768 Add blacklist check to content access middleware
  creator-node/src/contentAccess/contentAccessChecker.ts
  creator-node/src/contentAccess/types.ts
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
  creator-node/src/routes/tracks.js
Labels: size/M

#4762 Delete old plays instead of archiving
  discovery-provider/alembic/versions/64e82a907294_delete_plays_archive_table.py
  discovery-provider/integration_tests/tasks/test_prune_plays.py
  discovery-provider/src/tasks/prune_plays.py
Labels: size/L

#4766 SDK v2.0.2-alpha.1
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#4738 DMs improvements
  discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/emailRender.test.ts
  discovery-provider/plugins/notifications/src/__tests__/notification.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  discovery-provider/plugins/notifications/src/types/identity.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/XXL

#4774 Fix comms tests
  comms/Makefile
  comms/discovery/config/placement.go
  comms/discovery/db/conn.go
  comms/discovery/discovery_main.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/server/server_test.go
  comms/shared/peering/signed_request.go
  comms/storage/storageserver/storageserver_test.go
  comms/storage/transcode/jobs.go
Labels: size/L

#4771 Update entity manager libs social actions to accept metadata
  libs/src/api/entityManager.ts
Labels: size/XS

#4772 PLAT-676: base trending server
  comms/Makefile
  comms/go.mod
  comms/go.sum
  comms/main.go
  comms/trending/config/config.go
  comms/trending/trending_main.go
  comms/trending/trendingserver/trendingserver.go
  comms/trending/trendingserver/trendingserver_suite_test.go
  comms/trending/trendingserver/trendingserver_test.go
Labels: size/L

#4779 No fetching metadata for social features
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#4767 [PAY-915] Reduce number of db round trips in DN stream route
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_track_stream_info.py
Labels: size/M

#4782 Fix comms discovery tests and bump isort
  .pre-commit-config.yaml
  comms/discovery/rpcz/main_test.go
Labels: size/S

#4783 [CON-572] change mimetype on input
  comms/storage/storageserver/static/status.html
Labels: size/S

#4785 [CON-595] Improve comms/storage config (pt3)
  comms/Makefile
  comms/discovery/config/config.go
  comms/discovery/discovery_main.go
  comms/discovery/em/cid.go
  comms/discovery/rpcz/main_test.go
  comms/discovery/server/main_test.go
  comms/docker-compose.v2.base.yml
  comms/docker-compose.v2.dev.yml
  comms/docker-compose.v2.multi.yml
  comms/docker-compose.yml
  comms/natsd/config/config.go
  comms/natsd/nats_main.go
  comms/shared/config/config.go
  comms/shared/peering/exchange_endpoint.go
  comms/shared/peering/info_test.go
  comms/shared/peering/nats_connection.go
  comms/shared/peering/peering.go
  comms/shared/peering/solicit.go
  comms/shared/peering/sps.go
  comms/shared/peering/sps_test.go
  comms/storage/config/config.go
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
Labels: size/XL

#4791 Fix lint in contentAccessMiddleware
  creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
Labels: size/S

#4790 [CON-572] add content-type checking in server
  comms/storage/storageserver/storageserver.go
Labels: size/S

#4788 SDK: Create chat IDs deterministically
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
Labels: size/S

#4781 As/plat 677 clickhouse db driver
  comms/.gitignore
  comms/Makefile
  comms/docker-compose.trending.yml
  comms/go.mod
  comms/go.sum
  comms/trending/README.md
  comms/trending/config/config.go
  comms/trending/db/clickhouse.go
  comms/trending/db/db.go
  comms/trending/houseparty/config.d/config.xml
  comms/trending/houseparty/config.d/named_connections.xml
  comms/trending/trendingserver/trendingserver.go
  comms/trending/trendingserver/trendingserver_test.go
Labels: size/L

#4794 [CON-580] remove tracing from storage
  comms/storage/storage_main.go
  comms/storage/telemetry/README.md
  comms/storage/telemetry/tracer.go
Labels: size/M

#4793 As/plat 674 sql dump script
  comms/.gitignore
  comms/Makefile
  comms/docker-compose.trending.yml
  comms/go.mod
  comms/go.sum
  comms/trending/README.md
  comms/trending/houseparty/sql/agg_activity.sql
  comms/trending/houseparty/sql/agg_artist.sql
  comms/trending/houseparty/sql/agg_track.sql
  comms/trending/houseparty/sql/agg_user.sql
  comms/trending/houseparty/sql/all.sh
  comms/trending/houseparty/sql/etl_follows.sql
  comms/trending/houseparty/sql/etl_playlists.sql
  comms/trending/houseparty/sql/etl_plays.sql
  comms/trending/houseparty/sql/etl_reposts.sql
  comms/trending/houseparty/sql/etl_saves.sql
  comms/trending/houseparty/sql/etl_tracks.sql
  comms/trending/houseparty/sql/etl_users.sql
  comms/trending/houseparty/sql/nuke.sql
Labels: size/XL

#4786 [CON-544 CON-548] Add track_cid migration for 1781 tracks
  discovery-provider/alembic/csvs/missing_track_cid_21523.csv
  discovery-provider/alembic/versions/9b4e12c0c428_21523_track_cids.py
Labels: size/XXL

#4802 disable ES top playlists while fixing scoring
  discovery-provider/src/queries/get_top_playlists.py
Labels: size/XS

#4800 Change default selected option
  comms/storage/storageserver/static/status.html
Labels: size/XS

#4799 Mark blacklisted CIDs as unavailable
  discovery-provider/integration_tests/tasks/test_update_track_is_available.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/tasks/update_track_is_available.py
Labels: size/M

#4769 Fix notifications endpoint
  discovery-provider/alembic/trigger_sql/handle_reaction.sql
  discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql
  discovery-provider/alembic/trigger_sql/handle_track.sql
  discovery-provider/alembic/trigger_sql/handle_user_balance_changes.sql
  discovery-provider/alembic/trigger_sql/handle_user_tip.sql
  discovery-provider/alembic/versions/0f75bcb73b0a_update_triggers_for_notifications.py
  discovery-provider/integration_tests/notifications/test_reaction.py
  discovery-provider/integration_tests/notifications/test_tier_change.py
  discovery-provider/integration_tests/notifications/test_track.py
  discovery-provider/integration_tests/notifications/test_user_tip.py
  discovery-provider/integration_tests/queries/test_notifications/test_follow_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_paginate_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py
  discovery-provider/integration_tests/queries/test_notifications/test_user_tier_change_notification.py
  discovery-provider/src/api/v1/models/notifications.py
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/tasks/index_trending.py
  libs/src/api/Notifications.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/XL

#4795 [PAY-902] Support adhoc userbank creation
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/M

#4805 Update signature ttl to 48hours
  creator-node/src/contentAccess/contentAccessChecker.ts
Labels: size/XS

#4804 PLAT-680: codegen comms
  comms/Makefile
  comms/trending/codegen/.openapi-generator/FILES
  comms/trending/codegen/.openapi-generator/VERSION
  comms/trending/codegen/model_activity.go
  comms/trending/codegen/model_bulk_subscribers_response.go
  comms/trending/codegen/model_connected_wallets.go
  comms/trending/codegen/model_connected_wallets_response.go
  comms/trending/codegen/model_cover_photo.go
  comms/trending/codegen/model_decoded_user_token.go
  comms/trending/codegen/model_encoded_user_id.go
  comms/trending/codegen/model_favorite.go
  comms/trending/codegen/model_favorites_response.go
  comms/trending/codegen/model_followers_response.go
  comms/trending/codegen/model_following_response.go
  comms/trending/codegen/model_get_supporter.go
  comms/trending/codegen/model_get_supporters.go
  comms/trending/codegen/model_get_supporting.go
  comms/trending/codegen/model_get_tips_response.go
  comms/trending/codegen/model_history_response.go
  comms/trending/codegen/model_listen_count.go
  comms/trending/codegen/model_monthly_aggregate_play.go
  comms/trending/codegen/model_playlist.go
  comms/trending/codegen/model_playlist_artwork.go
  comms/trending/codegen/model_playlist_response.go
  comms/trending/codegen/model_playlist_search_result.go
  comms/trending/codegen/model_playlist_tracks_response.go
  comms/trending/codegen/model_profile_picture.go
  comms/trending/codegen/model_related_artist_response.go
  comms/trending/codegen/model_remix_parent.go
  comms/trending/codegen/model_reposts.go
  comms/trending/codegen/model_subscribers_response.go
  comms/trending/codegen/model_supporter.go
  comms/trending/codegen/model_supporting.go
  comms/trending/codegen/model_tags_response.go
  comms/trending/codegen/model_tip.go
  comms/trending/codegen/model_top_genre_users_response.go
  comms/trending/codegen/model_top_users_response.go
  comms/trending/codegen/model_track.go
  comms/trending/codegen/model_track_artwork.go
  comms/trending/codegen/model_track_element.go
  comms/trending/codegen/model_track_response.go
  comms/trending/codegen/model_track_search.go
  comms/trending/codegen/model_tracks_response.go
  comms/trending/codegen/model_trending_playlists_response.go
  comms/trending/codegen/model_user.go
  comms/trending/codegen/model_user_associated_wallet_response.go
  comms/trending/codegen/model_user_replica_set.go
  comms/trending/codegen/model_user_response.go
  comms/trending/codegen/model_user_search.go
  comms/trending/codegen/model_user_subscribers.go
  comms/trending/codegen/model_user_track_listen_counts_response.go
  comms/trending/codegen/model_users_by_content_node.go
  comms/trending/codegen/model_verify_token.go
  comms/trending/codegen/model_version_metadata.go
  comms/trending/codegen/utils.go
  comms/trending/trendingserver/trendingserver.go
  comms/trending/trendingserver/trendingserver_test.go
Labels: size/M

#4807 lint libs notifications
  libs/src/api/Notifications.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/discoveryProvider/requests.ts
Labels: size/M

#4724 Update handle_repost trigger to create repost of a repost notification
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/integration_tests/notifications/test_repost.py
  discovery-provider/integration_tests/notifications/test_repost_repost.py
  discovery-provider/integration_tests/utils.py
Labels: size/L

#4808 Bump SDK
  libs/package-lock.json
  libs/package.json
Labels: size/XS

#4809 Filter chats with no messages in /chats response
  comms/discovery/db/queries/get_chats.go
  comms/discovery/db/queries/get_summaries.go
  comms/discovery/server/server_test.go
Labels: size/M

#4735 Update entity manager repost indexing to handle is_repost_repost
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/L

#4780 Circle CI improvement followup
  .circleci/@parameters.yml
  .circleci/config.yml
  .circleci/jobs/build-gcp-image.yml
  .circleci/jobs/gcp-cleanup.yml
  .circleci/jobs/push-docker-image.yml
  .circleci/jobs/push-docker-images.yml
  .circleci/workflows/gcp-cleanup.yml
  .circleci/workflows/main.yml
  .circleci/workflows/release-create-branch.yml
  comms/storage/storageserver/static/status.html
  dev-tools/audius-compose
  dev-tools/commands/package.json
Labels: size/L

#4814 Remove build from test up
  dev-tools/audius-compose
Labels: size/XS

#4815 change order of alembic for patching to release
  discovery-provider/alembic/versions/0f75bcb73b0a_update_triggers_for_notifications.py
  discovery-provider/alembic/versions/9b4e12c0c428_21523_track_cids.py
Labels: size/S

#4806 [INF-354] Move to sendgrid for email validation
  identity-service/package.json
  identity-service/src/config.js
  identity-service/src/routes/user.js
Labels: size/M

#4816 fix failing repost reposts test and specify repost type in trigger
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/integration_tests/notifications/test_repost_repost.py
  discovery-provider/integration_tests/queries/test_notifications/test_repost_repost_notifications.py
  discovery-provider/src/queries/get_notifications.py
Labels: size/S

#4803 [CON-579] Add image and audio seed subcommands
  comms/Makefile
  comms/cmd/audio.go
  comms/cmd/discovery.go
  comms/cmd/image.go
  comms/cmd/nats.go
  comms/cmd/root.go
  comms/cmd/seed.go
  comms/cmd/storage.go
  comms/go.mod
  comms/go.sum
  comms/main.go
  comms/shared/utils/utils.go
  comms/storage/client/client.go
  comms/storage/persistence/persistence_test.go
  comms/storage/storageserver/static/status.html
  comms/storage/storageserver/storageserver.go
Labels: size/XL

#4811 Add network ID and latest block to chain health check
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/S

#4824 Update storage seed cmd to use new config
  comms/cmd/seed.go
  comms/storage/storageserver/storageserver.go
Labels: size/S

#4827 Remove service cmds and mad dog
  dev-tools/setup-dev.sh
Labels: size/S

#4829 Fix cn build
  creator-node/Dockerfile
Labels: size/XS

#4828 Keep peering pointer in lifetime struct
  comms/storage/storage_main.go
  comms/storage/storageserver/storageserver.go
  comms/storage/storageserver/storageserver_test.go
Labels: size/S

#4833 Fix libs tests
  docker-compose.test.yml
Labels: size/S

#4821 Run comms migrations for notifications plugin
  comms/Dockerfile
  comms/cmd/discovery.go
  comms/discovery/db/run_migrations.go
  comms/discovery/discovery_main.go
  dev-tools/audius-compose
  dev-tools/startup/startup.sh
  discovery-provider/scripts/run-migrations.sh
  docker-compose.test.yml
  docker-compose.yml
Labels: size/M

#4818 Add is_save_of_repost to saves table
  discovery-provider/alembic/versions/abdb338530cd_add_is_save_of_repost_to_saves_table.py
  discovery-provider/src/models/social/save.py
Labels: size/M

#4819 PLAT-686: identity relays
  identity-service/src/relay/txRelay.js
  identity-service/src/routes/healthCheck.js
Labels: size/M

#4832 DM indexes
  comms/README.md
  comms/discovery/db/migrations/20230224160015_chat_indexes.sql
  comms/discovery/rpcz/apply.go
  comms/shared/config/constants.go
Labels: size/L

#4831 NATS_ENABLE_JETSTREAM flag
  comms/docker-compose.v2.base.yml
  comms/natsd/nats_manager.go
Labels: size/XS

#4841 Fix remixes failure for gated tracks
  discovery-provider/src/queries/get_remixes_of.py
Labels: size/XS

#4839 [C-2116] Return errors from tiktok access_token endpoint
  identity-service/src/routes/tiktok.js
Labels: size/S

#4842 Remove unused TikTok share.sound.create scope
  identity-service/src/routes/tiktok.js
Labels: size/XS

#4840 [PAY-902] Process userbank transactions sequentially
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#4843 Use node_modules instead of npx for test
  docker-compose.test.yml
Labels: size/XS

#4838 Rename is_repost_repost to is_repost_of_repost
  discovery-provider/alembic/trigger_sql/handle_repost.sql
  discovery-provider/alembic/versions/198d03c95cac_rename_repost_repost.py
  discovery-provider/integration_tests/notifications/test_repost_repost.py
  discovery-provider/integration_tests/queries/test_notifications/test_repost_repost_notifications.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/output.txt
  discovery-provider/src/api/v1/utils/extend_notification.py
  discovery-provider/src/models/social/repost.py
  discovery-provider/src/queries/get_notifications.py
  discovery-provider/src/tasks/entity_manager/social_features.py
Labels: size/XL

#4846 Remove platform
  discovery-provider/plugins/notifications/Dockerfile
Labels: size/XS

#4835 ACDC migraiton: enable identity final_poa_block, improve web3 provider switch, indexing parity
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/index.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/index_trending.py
  discovery-provider/src/utils/helpers.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/L

#4817 [CON-555] StorageV2: Add content access middleware
  comms/shared/utils/discovery.go
  comms/storage/contentaccess/content_access_checker.go
  comms/storage/contentaccess/content_access_checker_test.go
  comms/storage/contentaccess/content_access_middleware.go
  comms/storage/storageserver/storageserver.go
Labels: size/L

#4849 Fix broken userbank indexing
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#4848 Update handle_save trigger to handle is_save_of_repost
  discovery-provider/alembic/trigger_sql/handle_save.sql
  discovery-provider/integration_tests/notifications/test_save_of_repost.py
  discovery-provider/integration_tests/utils.py
Labels: size/L
