Repository AudiusProject/apps, pull requests merged in 2023-07, with the labels that each got.

#5541 [SDK] Add env option to OAuth
  libs/src/sdk/oauth/OAuth.ts
Labels: size/S

#5515 [CON-769] Return delisted before bad sig
  mediorum/server/serve_blob.go
  mediorum/server/server.go
Labels: size/M

#5537 [C-2754] Add remaining social writes to sdk
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/api/users/UsersApi.ts
  libs/src/sdk/api/users/types.ts
  libs/src/sdk/index.ts
  libs/src/sdk/sdk.ts
  sdk-consumer/index.ts
Labels: size/XL

#5544 Make grant creation faster on EM indexing C-2803
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/grant.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#5543 [SDK] Don't swallow EM relay errors; log detailed message when rate limit hit C-2642
  libs/src/sdk/services/EntityManager/EntityManager.ts
Labels: size/M

#5539 [PAY-1547] Add USDC related tables to DB
  discovery-provider/ddl/migrations/0010_usdc_userbank_tables.sql
Labels: size/M

#5479 PLAT-1076: handle endpoint disabled errors gracefully
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/milestone.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supporterRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/supportingRankUp.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tastemaker.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingPlaylist.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/trendingUnderground.test.ts
  discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/sns.ts
  discovery-provider/plugins/notifications/src/utils/disableArnEndpoint.ts
Labels: size/L

#5545 prettier on notifications
  discovery-provider/plugins/notifications/.eslintrc.js
  discovery-provider/plugins/notifications/.prettierrc.js
  discovery-provider/plugins/notifications/README.md
  discovery-provider/plugins/notifications/jest.config.js
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/scripts/create-announcement.ts
  discovery-provider/plugins/notifications/scripts/sql-ts.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/email/templates/README.md
  discovery-provider/plugins/notifications/src/email/templates/downloadMobileApp.html
  discovery-provider/plugins/notifications/src/email/templates/welcome.html
  discovery-provider/plugins/notifications/src/email/templates/welcomeDownload.html
  discovery-provider/plugins/notifications/src/listener.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/cosign.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/remix.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repostOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/saveOfRepost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingPlaylist.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingUnderground.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  discovery-provider/plugins/notifications/src/web.ts
Labels: size/XXL

#5548 Raise rate limits for social features
  identity-service/relay-rate-limit.json
Labels: size/S

#5547 [CON-771] Short circuit when transcode fails
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/services/creatorNode/CreatorNode.ts
  mediorum/server/serve_upload.go
Labels: size/S

#5546 [CON-772] Log ffmpeg stdout and stderr
  mediorum/server/transcode.go
Labels: size/M

#5550 Make mediorum stop looking like it's erroring when it's not
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
Labels: size/S

#5551 DMs make internal rpcs idempotent
  comms/discovery/config/config.go
  comms/discovery/discovery_main.go
  comms/discovery/misc/trim.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat_test.go
  comms/discovery/rpcz/internal_rpc.go
  comms/discovery/rpcz/internal_rpc_test.go
  comms/discovery/rpcz/main_test.go
  comms/discovery/rpcz/validator.go
  discovery-provider/ddl/migrations/0011_chat_ban_timestamps.sql
  discovery-provider/ddl/migrations/0012_rpc_log_applied_at_idx.sql
Labels: size/L

#5557 [C-2828] Fix collection upload order
  libs/src/api/Track.ts
Labels: size/M

#5552 [C-2737] Add collection upload to write sdk
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/TrackUploadHelper.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/sdk.ts
  sdk-consumer/index.ts
Labels: size/XL

#5559 [C-2739] Add deletePlaylist to write sdk
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  sdk-consumer/index.ts
Labels: size/M

#5556 rm spammy log
  discovery-provider/plugins/notifications/src/main.ts
Labels: size/XS

#5561 [C-2732] Add createPlaylist to write sdk
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5560 retry failed transcode
  mediorum/main.go
  mediorum/server/db.go
  mediorum/server/transcode.go
Labels: size/S

#5555 Use rendezvous for all streams
  discovery-provider/src/api/v1/tracks.py
  mediorum/server/repair.go
  mediorum/server/serve_health.go
  mediorum/server/server.go
Labels: size/M

#5562 Fix playlist update em
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/XS

#5563 Fix custom indexing validation
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XS

#5566 Log mp3 streams that would be blocked
  mediorum/server/serve_blob.go
Labels: size/S

#5558 [plat-1109] Add db trigger to create usdc purchase notifications
  discovery-provider/ddl/functions/handle_usdc_purchase.sql
  discovery-provider/integration_tests/notifications/test_usdc_purchase.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/users/usdc_purchase.py
Labels: size/L

#5549 Set web3 primary host as env var
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/utils/web3_provider.py
Labels: size/S

#5568 clear upload error after retry success
  mediorum/server/transcode.go
Labels: size/XS

#5565 add trusted notifier discrepancies to health check + index and delist sequentially
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  discovery-provider/src/queries/get_trusted_notifier_discrepancies.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/L

#5571 Use hasattr instead of self. in cache user balance
  discovery-provider/src/tasks/cache_user_balance.py
Labels: size/XS

#5572 Rm undefined self attributes in cache user balance
  discovery-provider/src/tasks/cache_user_balance.py
Labels: size/XS

#5574 Filter users earlier in lazy balance refresh
  discovery-provider/src/tasks/cache_user_balance.py
Labels: size/XS

#5573 Revert "Revert single tx signup in libs (#5471)"
  libs/src/api/Account.ts
  libs/src/api/Users.ts
Labels: size/M

#5575 Comment out lazy refresh on cache user balance ids
  discovery-provider/src/queries/get_balances.py
  discovery-provider/src/tasks/cache_user_balance.py
Labels: size/S

#5577 Make mediorum only redirect if db is reachable
  mediorum/server/serve_blob.go
  mediorum/server/server.go
Labels: size/S

#5578 Only log listen for tracks, and log legacy mp3 stream
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
Labels: size/S

#5570 [C-2735] Add updatePlaylist and publishPlaylist to sdk
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/api/v1/playlists.py
  libs/src/sdk/api/generated/default/.openapi-generator/FILES
  libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/default/models/Playlist.ts
  libs/src/sdk/api/generated/default/models/PlaylistAddedTimestamp.ts
  libs/src/sdk/api/generated/default/models/index.ts
  libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5583 Add entity counts
  discovery-provider/src/queries/get_entities_count_check.py
  discovery-provider/src/queries/health_check.py
Labels: size/M

#5582 Disallow non-cidstream mp3s, and fix filename download
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
Labels: size/M

#5580 PLAT-1096: notifs heap fixes
  discovery-provider/plugins/notifications/Dockerfile
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/scripts/create-announcement.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/server/index.ts
  discovery-provider/plugins/notifications/src/server/routes/memStats.ts
  discovery-provider/plugins/notifications/src/utils/memStats.ts
Labels: size/M

#5585 Log commit on discovery server start
  discovery-provider/src/wsgi.py
Labels: size/S

#5589 Add web push notifications for announcements
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
Labels: size/M

#5586 Allow delegated user writes
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#5591 [C-2733] Add addTrackToPlaylist and removeTrackFromPlaylist to sdk
  discovery-provider/src/api/v1/models/playlists.py
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5590 Validate user has handle
  discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#5592 Fix libs and /playlist endpoint for is_image_autogenerated
  discovery-provider/src/api/v1/models/playlists.py
  libs/src/api/entityManager.ts
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/XS

#5593 Add new identity signal
  identity-service/src/routes/idSignals.js
  identity-service/src/utils/antiAbuse.js
Labels: size/S

#5598 Make redirect err more informative
  mediorum/server/serve_legacy.go
Labels: size/XS

#5516 Handle track preview in POST /uploads
  mediorum/ddl/add_fields_to_uploads.sql
  mediorum/server/db.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_blob_test.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/server_basic_auth.go
  mediorum/server/server_basic_auth_test.go
  mediorum/server/signature/signature.go
  mediorum/server/transcode.go
Labels: size/XL

#5595 Clean up v1 CN (part 1, leave manual syncs)
  creator-node/src/components/README.md
  creator-node/src/components/healthCheck/healthCheckComponentService.js
  creator-node/src/components/healthCheck/healthCheckComponentService.test.js
  creator-node/src/components/healthCheck/healthCheckController.js
  creator-node/src/components/healthCheck/syncHealthCheckComponentService.test.js
  creator-node/src/components/healthCheck/syncHealthCheckComponentService.ts
  creator-node/src/components/replicaSet/replicaSetController.js
  creator-node/src/config.js
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.ts
  creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts
  creator-node/src/monitors/monitors.js
  creator-node/src/monitors/stateMachine.js
  creator-node/src/reqLimiter.js
  creator-node/src/routes/users.js
  creator-node/src/serviceRegistry.js
  creator-node/src/services/prometheusMonitoring/README.md
  creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
  creator-node/src/services/stateMachineManager/index.js
  creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
  creator-node/src/services/stateMachineManager/stateMachineConstants.ts
  creator-node/src/services/stateMachineManager/stateMachineUtils.js
  creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateMonitoring/index.js
  creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/index.js
  creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
  creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
  creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
  creator-node/src/services/stateMachineManager/types.ts
  creator-node/src/services/sync/primarySyncFromSecondary.js
  creator-node/src/services/sync/secondarySyncFromPrimary.ts
  creator-node/src/snapbackSM/README.md
  creator-node/src/snapbackSM/StateMachineConstants.js
  creator-node/src/snapbackSM/peerSetManager.js
  creator-node/src/snapbackSM/secondarySyncHealthTracker.js
  creator-node/src/snapbackSM/snapbackDeDuplicator.js
  creator-node/src/snapbackSM/snapbackSM.js
  creator-node/src/snapbackSM/syncHistoryAggregator.js
  creator-node/test/StateMonitoringManager.test.js
  creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
  creator-node/test/findSyncRequests.jobProcessor.test.js
  creator-node/test/issueSyncRequest.jobProcessor.test.js
  creator-node/test/monitorState.jobProcessor.test.js
  creator-node/test/pollingTracks.test.js
  creator-node/test/recoverOrphanedData.jobProcessor.test.ts
  creator-node/test/snapbackSM.test.js
  creator-node/test/stateMachineUtils.test.js
  creator-node/test/stateMonitoringUtils.test.js
  creator-node/test/updateReplicaSet.jobProcessor.test.js
  dev-tools/startup/creator-node-container.sh
  discovery-provider/plugins/network-monitoring/src/content/index.ts
  discovery-provider/plugins/network-monitoring/src/content/queries.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
Labels: size/XXL

#5602 [PLAT-1125] Tolerate higher minor/major versions in selection
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.ts
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
  libs/src/services/ethContracts/EthContracts.ts
Labels: size/M

#5600 [C-2740, C-2741] Add update profile to usersApi in SDK and add test
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/api/users/UsersApi.ts
  libs/src/sdk/api/users/types.ts
  libs/src/sdk/sdk.ts
  sdk-consumer/index.ts
Labels: size/L

#5610 [C-2845] Update save to favorite for the tracks and playlists endpoints
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  sdk-consumer/index.ts
Labels: size/L

#5607 Update sdk exports
  libs/src/sdk/index.ts
Labels: size/XS

#5606 [CON-773] support new nodes better
  mediorum/crudr/client.go
  mediorum/crudr/crudr.go
  mediorum/main.go
  mediorum/server/peer_health.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
Labels: size/L

#5614 Try more legacy fallback paths when serving files
  mediorum/server/serve_legacy.go
Labels: size/L

#5613 add push body to announcement notification
  discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/XS

#5616 Fix cid_lookup schema and stay unhealthy while seeding
  mediorum/server/cid_log_client.go
  mediorum/server/monitor.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_legacy.go
  mediorum/server/server.go
Labels: size/L

#5617 Remove and fix 2 slow mediorum sql queries
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/S

#5609 Set bootstrap nodes default for StorageNodeSelector
  libs/src/sdk/config/development.ts
  libs/src/sdk/config/production.ts
  libs/src/sdk/config/staging.ts
  libs/src/sdk/config/types.ts
  libs/src/sdk/scripts/generateServicesConfig.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/constants.ts
Labels: size/L

#5618 Gate user-facing routes with health check so client knows to retry another node
  mediorum/server/monitor.go
  mediorum/server/serve_health.go
  mediorum/server/server.go
Labels: size/M

#5622 [CON-778] Mediorum: Check all healthy nodes on 404 and use GA
  mediorum/cmd/main.go
  mediorum/main.go
  mediorum/registrar/audius_api_gateway.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#5624 Re-seed cid_lookup instead of falling back to every node
  mediorum/ddl/ddl.go
  mediorum/server/cid_log_client.go
  mediorum/server/serve_legacy.go
  mediorum/server/server.go
  monitoring/vector/vector.toml
Labels: size/L

#5625 Make mediorum case insensitive again
  mediorum/registrar/audius_api_gateway.go
Labels: size/XS

#5627 PLAT-1115: discovery relay config
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/EntityManager/EntityManager.test.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/types.ts
Labels: size/M

#5604 Revert "Revert "0.4.0 (#5506)" (#5514)"
  creator-node/.version.json
  discovery-provider/.version.json
Labels: size/XS

#5633 Update maxContentLength for sdk uploads
  libs/src/sdk/services/Storage/Storage.ts
Labels: size/XS

#5579 Add track preview columns to tracks table and metadata, add preview streaming
  dev-tools/commands/src/upload-track.mjs
  discovery-provider/ddl/migrations/0013_add_track_preview_cols.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/premium_content/signature.py
  discovery-provider/src/premium_content/signature_unit_test.py
  discovery-provider/src/queries/get_track_stream_signature.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/metadata.py
  libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  libs/src/sdk/api/generated/default/apis/TracksApi.ts
  libs/src/sdk/api/generated/default/models/Playlist.ts
  libs/src/sdk/api/generated/default/models/Track.ts
  libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  libs/src/sdk/api/generated/full/models/TrackFull.ts
  libs/src/sdk/api/tracks/TrackUploadHelper.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/types/types.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/services/schemaValidator/schemas/trackSchema.json
  libs/src/utils/types.ts
Labels: size/L

#5611 Add mood and genre to browser dist
  libs/src/sdk/sdkBrowserDist.ts
Labels: size/XS

#5637 load ai_attribution_user_id in validation
  discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/XS

#5632 Ddl index cleanup
  discovery-provider/ddl/migrations/0013_index_cleanup.sql
  discovery-provider/ddl/pg_migrate.sh
  discovery-provider/ddl/tests/counting.sql
Labels: size/M

#5630 [C-2782] Update app name middleware to fetch app name if not provided
  libs/src/sdk/middleware/addAppNameMiddleware.ts
  libs/src/sdk/sdk.ts
Labels: size/M

#5496 [PAY-1429] current_user_id query param
  comms/discovery/db/queries/get_users.go
  comms/discovery/rpcz/apply.go
  comms/discovery/server/server.go
  comms/discovery/server/server_test.go
  comms/discovery/server/signed_request.go
  comms/shared/signing/constants.go
  comms/shared/signing/signed_request.go
Labels: size/L

#5615 Check current block timestamp in delist task
  discovery-provider/integration_tests/tasks/test_update_delist_statuses.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/L

#5641 Function to do disk check without following redirects.
  mediorum/server/serve_legacy.go
Labels: size/L

#5638 Fix AI attribute update
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/S

#5644 Use GET for mediorum redirect checks
  mediorum/server/serve_legacy.go
Labels: size/S

#5599 Support creating USDC userbanks in libs and DN
  dev-tools/commands/src/utils.mjs
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.dev.yml
  dev-tools/compose/docker-compose.discovery.yml
  dev-tools/compose/docker-compose.identity.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/config.json
  discovery-provider/default_config.ini
  discovery-provider/src/models/users/user_bank.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/tasks/index_user_bank.py
  identity-service/src/config.js
  identity-service/src/utils/relayHelpers.js
  libs/initScripts/configureLocalDiscProv.js
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/WebAudiusLibs.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/wormhole/Wormhole.ts
  solana-programs/Dockerfile.dev
  solana-programs/README.md
  solana-programs/scripts/deploy.sh
Labels: size/XL

#5643 Fix revert cursor blocknumber logic + misc
  discovery-provider/integration_tests/tasks/test_update_delist_statuses.py
  discovery-provider/src/tasks/index_nethermind.py
  discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/L

#5623 [PLAT-608][PLAT-1129] Add dual playlist route writes and fix private fetches
  dev-tools/compose/docker-compose.pedalboard.yml
  dev-tools/compose/docker-compose.yml
  discovery-provider/integration_tests/queries/test_get_playlists.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/src/queries/get_playlists.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/L

#5608 [plat-1112] add usdc purchase buy and sell notifications to plugin
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseBuyer.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts
  discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  discovery-provider/plugins/notifications/src/remoteConfig.ts
  discovery-provider/plugins/notifications/src/types/dn.ts
  discovery-provider/plugins/notifications/src/types/notifications.ts
  discovery-provider/plugins/notifications/src/utils/format.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/XXL

#5650 Mediorum health changes
  mediorum/server/peer_health.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#5635 Add duration log for user endpoints
  discovery-provider/src/api/v1/users.py
Labels: size/M

#5645 [CON-781] Allow running a v2-only Content Node
  .circleci/config.yml
  creator-node/src/routes/healthCheck.js
  libs/src/api/ServiceProvider.ts
  libs/src/services/creatorNode/CreatorNodeSelection.test.ts
  libs/src/services/creatorNode/CreatorNodeSelection.ts
  libs/src/services/creatorNode/index.ts
  mediorum/.version.json
  mediorum/main.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
Labels: size/XXL

#5646 Libs edit file upload (for editing track previews)
  dev-tools/commands/src/edit-track.mjs
  libs/src/api/Track.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/Auth/AppAuth.ts
  libs/src/sdk/services/Auth/Auth.ts
  libs/src/sdk/services/Auth/types.ts
  libs/src/sdk/services/Auth/utils.ts
  libs/src/sdk/services/EntityManager/EntityManager.test.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/utils/apiSigning.ts
  mediorum/server/serve_upload.go
  mediorum/server/server_basic_auth.go
Labels: size/L

#5654 Fix user followers call
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5648 Skip transaction when there's network consensus
  discovery-provider/integration_tests/tasks/entity_manager/test_index_skip_tx.py
  discovery-provider/src/queries/confirm_indexing_transaction_error.py
  discovery-provider/src/queries/get_skipped_transactions.py
  discovery-provider/src/queries/skipped_transactions.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5655 Fix migration route for playlists
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/XS

#5564 Decentralized Relay
  discovery-provider/plugins/pedalboard/apps/relay/.eslintrc.js
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/apps/relay/src/abi.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/logger.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/routes/health.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/routes/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/scripts/sandbox.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/types/entityManager.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/types/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/validate.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/walletManager.ts
  discovery-provider/plugins/pedalboard/apps/relay/tsconfig.json
  discovery-provider/plugins/pedalboard/package-lock.json
Labels: size/XL

#5657 Fix broken playlist_routes test
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
Labels: size/S

#5656 sv2 alternative storage backends
  mediorum/go.mod
  mediorum/go.sum
  mediorum/main.go
  mediorum/persistence/README.md
  mediorum/persistence/persistence.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
Labels: size/L

#5639 As/plat 1136 build relay plugin
  .circleci/src/workflows/discovery.yml
  dev-tools/compose/docker-compose.pedalboard.yml
  dev-tools/compose/docker-compose.yml
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/scripts/sandbox.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/docker-compose.yml
Labels: size/M

#5660 Make all track previews publicly streamable
  discovery-provider/src/queries/get_track_stream_signature.py
Labels: size/S

#5658 [CON-733] Implement "full" content node (STORE_ALL)
  mediorum/main.go
  mediorum/server/placement.go
  mediorum/server/repair.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
Labels: size/L

#5612 [C-2835] Support partial updates in EM and SDK
  discovery-provider/Dockerfile
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/requirements.txt
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/metadata.py
  libs/src/sdk/api/albums/AlbumsApi.test.ts
  libs/src/sdk/api/albums/AlbumsApi.ts
  libs/src/sdk/api/albums/types.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/TrackUploadHelper.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/services/Auth/Auth.ts
  sdk-consumer/index.ts
Labels: size/XL

#5664 boost max skipped tx
  discovery-provider/src/queries/get_skipped_transactions.py
Labels: size/XS

#5665 Fix user update merging cid data
  discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/XS

#5661 Log error when skipping tx
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#5667 [C-2882] parseParams for AlbumsApi in sdk
  libs/src/sdk/api/albums/AlbumsApi.test.ts
  libs/src/sdk/api/albums/AlbumsApi.ts
  libs/src/sdk/api/albums/types.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  sdk-consumer/index.ts
Labels: size/XL

#5669 [C-2867] Support node files with no filename in sdk
  libs/src/sdk/api/albums/types.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/api/users/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/types/File.ts
  libs/src/sdk/utils/file.ts
Labels: size/L

#5668 Fix noisy metadata deserialization error
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/M

#5672 Fix hidden tracks and playlists
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#5651 Move joined health check to python code
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/src/api_helpers.py
  discovery-provider/src/queries/health_check.py
Labels: size/M

#5674 [C-2865] Strip 0x from apikey
  libs/src/sdk/services/Auth/AppAuth.ts
Labels: size/XS

#5670 [C-2868] Restrict mime types of files in sdk
  libs/package-lock.json
  libs/package.json
  libs/src/sdk/api/albums/AlbumsApi.test.ts
  libs/src/sdk/api/albums/AlbumsApi.ts
  libs/src/sdk/api/albums/types.ts
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  libs/src/sdk/api/grants/GrantsApi.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/api/users/UsersApi.ts
  libs/src/sdk/api/users/types.ts
  libs/src/sdk/oauth/OAuth.ts
  libs/src/sdk/test/png-file.png
  libs/src/sdk/test/wav-file.wav
  libs/src/sdk/types/File.ts
  libs/src/sdk/utils/parseRequestParameters.ts
Labels: size/L

#5666 [PAY-1508] Library tracks endpoint
  discovery-provider/integration_tests/queries/test_get_track_library.py
  discovery-provider/solana-tx-parser/README.md
  discovery-provider/solana-tx-parser/account_parser.py
  discovery-provider/solana-tx-parser/call_instruction.py
  discovery-provider/solana-tx-parser/constants.py
  discovery-provider/solana-tx-parser/requirements.txt
  discovery-provider/solana-tx-parser/tx_parser.py
  discovery-provider/solana-tx-parser/utils.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_save_tracks.py
  discovery-provider/src/queries/get_track_library.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/XXL

#5677 Fix mediorum persistence readme
  mediorum/persistence/README.md
Labels: size/XS

#5676 Fix user merge in multi tx signup
  discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#5671 use custom DNS in go http client
  mediorum/httputil/custom_dns.go
  mediorum/main.go
Labels: size/M

#5681 [SDK] Re-generate API to get `getUserLibraryTracks`
  libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/PlaylistFull.ts
Labels: size/L

#5678 [CON-796] Shard CDK keys
  mediorum/.vscode/settings.json
  mediorum/cidutil/cidutil.go
  mediorum/cidutil/cidutil_test.go
  mediorum/ddl/ddl.go
  mediorum/server/db.go
  mediorum/server/helpers.go
  mediorum/server/placement.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/transcode.go
Labels: size/L

#5682 [C-2869] Add Logger to sdk
  libs/src/sdk/api/albums/AlbumsApi.test.ts
  libs/src/sdk/api/albums/AlbumsApi.ts
  libs/src/sdk/api/chats/ChatsApi.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/api/users/UsersApi.ts
  libs/src/sdk/oauth/OAuth.ts
  libs/src/sdk/sdk.ts
  libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  libs/src/sdk/services/DiscoveryNodeSelector/constants.ts
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
  libs/src/sdk/services/EntityManager/EntityManager.test.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/Logger/Logger.ts
  libs/src/sdk/services/Logger/index.ts
  libs/src/sdk/services/Logger/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/constants.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/constants.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
  libs/src/sdk/services/index.ts
  libs/src/sdk/types.ts
  libs/src/sdk/types/types.ts
  libs/src/sdk/utils/hashId.ts
  sdk-consumer/index.ts
Labels: size/XL

#5684 Ignore .tmp files when sharding
  mediorum/ddl/ddl.go
Labels: size/XS

#5686 [C-2894] Update ids to HashIds
  libs/src/sdk/api/tracks/types.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/api/users/types.ts
Labels: size/S

#5680 Fix fetchAndUpdatePlaylist in sdk
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/playlists/types.ts
Labels: size/M

#5685 Hide write methods and internal methods from autogenerated SDK docs C-2898
  libs/src/sdk/api/albums/AlbumsApi.ts
  libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  libs/src/sdk/api/generated/default/apis/DeveloperAppsApi.ts
  libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/default/apis/ResolveApi.ts
  libs/src/sdk/api/generated/default/apis/TipsApi.ts
  libs/src/sdk/api/generated/default/apis/TracksApi.ts
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/default/models/Playlist.ts
  libs/src/sdk/api/generated/default/runtime.ts
  libs/src/sdk/api/generated/full/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/full/apis/ReactionsApi.ts
  libs/src/sdk/api/generated/full/apis/SearchApi.ts
  libs/src/sdk/api/generated/full/apis/TipsApi.ts
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
  libs/src/sdk/api/generated/full/apis/TransactionsApi.ts
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/runtime.ts
  libs/src/sdk/api/generator/templates/typescript-fetch/apis.mustache
  libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/users/UsersApi.ts
Labels: size/L

#5688 Add album routes to playlist permalinks project
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/src/models/playlists/playlist.py
Labels: size/XS

#5687 Delete CDK .tmp files on startup
  mediorum/persistence/persistence.go
Labels: size/S

#5683 Enforce immutable metadata on updates
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/metadata.py
Labels: size/L

#5689 Enforce albums cannot change tracklist
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/M

#5690 Fix Web3 issue C-2900
  libs/src/utils/apiSigning.ts
Labels: size/S

#5692 Use tmp file key without slash
  mediorum/server/transcode.go
Labels: size/XS

#5693 sdk and discovery: Fix full bulk tracks endpoint
  discovery-provider/src/api/v1/tracks.py
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
Labels: size/XS

#5691 [CON-801] Fix v2 only user images from public api
  discovery-provider/src/api/v1/helpers.py
Labels: size/M

#5675 PLAT-1140: add decodeAbi and recoverSigner functions to decoder in libs
  libs/src/services/ABIDecoder/AudiusABIDecoder.ts
Labels: size/M

#5698 Add headers to parser for library route (Take Two) C-2906
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/transactions.py
Labels: size/M

#5699 Fix auth user for multi user wallet
  discovery-provider/src/queries/get_authed_user.py
Labels: size/XS

#5700 Fix: Don't break existing bulk get tracks endpoint for slug + handle
  discovery-provider/src/api/v1/tracks.py
Labels: size/S

#5679 Log when not attempting to push a DM notif
  discovery-provider/plugins/notifications/src/config.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/M

#5701 Run SDK gen for library auth headers
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/S

#5704 Fix cid_data json data
  discovery-provider/ddl/migrations/0014_correct_cid_data_json.sql
Labels: size/XS

#5619 Index USDC Transfer Transactions
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/tip-audio.mjs
  dev-tools/commands/src/upload-track.mjs
  dev-tools/commands/src/utils.mjs
  dev-tools/compose/docker-compose.discovery.yml
  discovery-provider/ddl/migrations/0014_track_price_history_table.sql
  discovery-provider/integration_tests/utils/test_helpers.py
  discovery-provider/src/models/tracks/track_price_history.py
  discovery-provider/src/models/users/usdc_transactions_history.py
  discovery-provider/src/solana/solana_helpers.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/index_rewards_manager.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/tasks/index_user_bank.py
  discovery-provider/src/utils/helpers.py
  identity-service/src/utils/relayHelpers.js
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solana/transfer.ts
  solana-programs/scripts/deploy.sh
Labels: size/XXL

#5703 Fix: Validate single tx signups and fix audius-cmd
  dev-tools/commands/test/create-user.bats
  dev-tools/commands/test/upload-track.bats
  discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#5705 Add documentation to StorageNodeSelector config, make logger optional
  libs/src/sdk/services/DiscoveryNodeSelector/types.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/constants.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/constants.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
Labels: size/M

#5707 Ignore non-CID Qm keys in repair.go
  mediorum/cidutil/cidutil.go
  mediorum/cidutil/cidutil_test.go
  mediorum/server/repair.go
Labels: size/M

#5702 [CON-788] Migrate legacy files (Qm CIDs) to v2 bucket (CDK)
  mediorum/main.go
  mediorum/server/migrate_qm.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/transcode.go
Labels: size/L

#5708 Return extremely old images even when they have extra .jpg
  mediorum/server/serve_blob.go
Labels: size/S

#5710 Update bootstrap nodes
  libs/src/sdk/config/production.ts
  monitoring/healthz/src/Rendezvous.tsx
Labels: size/XS

#5711 update playlist es indexer version
  discovery-provider/es-indexer/src/indexNames.ts
Labels: size/XS

#5713 Update all userbank functions to allow usdc mint
  dev-tools/commands/src/utils.mjs
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solana/rewardsAttester.ts
Labels: size/L

#5715 Add indexing validation for tracks in playlist
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/S
