Repository AudiusProject/apps, pull requests merged in 2023-09, with the labels that each got.

#5891 delay cn2 migration
  mediorum/ddl/ddl.go
Labels: size/XS

#5897 Relay: update sdk version
  discovery-provider/plugins/pedalboard/apps/relay/package.json
Labels: size/XS

#5896 [CON-846] Race discovery track streams v2 image fallbacks
  discovery-provider/src/api/v1/tracks.py
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#5898 Increase track stream redirect timeout to 5s and cache 30min
  discovery-provider/src/api/v1/tracks.py
Labels: size/M

#5899 Add checks for AMM and serum market addresses in staking-bridge
  solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/error.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
Labels: size/M

#5881 PROTO-1139: add discovery relay option to libs
  libs/.nvmrc
  libs/src/AudiusLibs.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/services/web3Manager/Web3Manager.ts
Labels: size/M

#5903 mediorum: redirect cache
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/cuckoo.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/L

#5901 Remove premium conditions for non-premium tracks
  discovery-provider/ddl/migrations/0028_fix_non_gated_track_premiun_conditions.sql
Labels: size/XS

#5904 [CON-828] Replicate Qm CIDs
  mediorum/server/placement.go
  mediorum/server/repair.go
Labels: size/S

#5902 Log cpu / mem on stage
  discovery-provider/src/utils/helpers.py
Labels: size/S

#5905 Rewards indexer skips solana transaction fetch fails
  discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/XS

#5908 Return 0 rps when undefined
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#5909 [PAY-1806] Update health checks
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/health_check.py
Labels: size/S

#5912 Update mediorum db status more often on startup with longer timeout
  mediorum/server/monitor.go
Labels: size/S

#5906 relay refactorings and tests
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/apps/relay/src/config/antiAbuseConfig.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config/rateLimitConfig.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/error.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/logger.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/routes/health.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/routes/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/types/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/walletManager.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
  discovery-provider/plugins/pedalboard/package-lock.json
Labels: size/XL

#5910 Surface image cid cache in feed endpoints
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/api_helpers.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/utils/elasticdsl.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#5915 delete disused code
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/cuckoo.go
  mediorum/server/delist_statuses.go
  mediorum/server/helpers.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/XL

#5745 [CON-806] Allow delisting on own node
  mediorum/server/delist_statuses.go
  mediorum/server/delist_statuses_test.go
  mediorum/server/server.go
  mediorum/server/server_basic_auth.go
  mediorum/server/signature/signature.go
Labels: size/L

#5918 Reland: USDC Transactions API
  dev-tools/commands/src/auth-headers.mjs
  dev-tools/commands/src/tip-audio.mjs
  discovery-provider/src/api/v1/transactions.py
Labels: size/S

#5919 Libs Discovery Relay: turn down to 0
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
Labels: size/XS

#5738 [CON-805] Update go-cloud dependency to fix temp files
  mediorum/go.mod
  mediorum/go.sum
  mediorum/persistence/persistence.go
  mediorum/server/server.go
Labels: size/XXL

#5917 Fix relay env var to run on correct network env
  discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
Labels: size/XS

#5920 Make repair.go replicate isMine in replicate mode
  mediorum/server/repair.go
Labels: size/XS

#5922 Drop blobs table, gossip upload crudr events
  mediorum/Makefile
  mediorum/crudr/client.go
  mediorum/ddl/ddl.go
  mediorum/ddl/drop_blobs.sql
  mediorum/server/db.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_upload.go
Labels: size/L

#5870 Delete historical records
  discovery-provider/ddl/migrations/0028_delete_historical_records_pt_3.sql
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5916 Transaction handler: Catch and return tx serialization errors
  libs/src/services/solana/transactionHandler.ts
Labels: size/S

#5927 Temporarily revert user manually
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#5930 [PAY-1813] Add metadata to USDC transaction history table
  discovery-provider/ddl/migrations/0029_usdc_transactions_metadata.sql
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/models/users/usdc_transactions_history.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/S

#5925 comms dev mode: no peers, always healthy
  comms/discovery/config/config.go
  comms/discovery/discovery_main.go
  comms/discovery/server/server.go
  dev-tools/compose/docker-compose.discovery.yml
Labels: size/S

#5932 [PAY-1796] Fix reposted/saved albums not showing in library
  dev-tools/commands/src/auth-headers.mjs
  discovery-provider/src/queries/get_collection_library.py
Labels: size/S

#5931 PROTO-1212: audius-cmd decent relay
  dev-tools/commands/src/create-user.mjs
  dev-tools/commands/src/utils.mjs
  dev-tools/compose/nginx_ingress.conf
  discovery-provider/Dockerfile
  discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/error.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/walletManager.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
  libs/src/services/identity/IdentityService.ts
  libs/src/services/web3Manager/Web3Manager.ts
Labels: size/L

#5914 [PAY-1801] Handle payment router nit comments
  solana-programs/payment-router/Cargo.lock
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/programs/payment-router/src/router.rs
  solana-programs/staking-bridge/Cargo.lock
  solana-programs/staking-bridge/programs/staking-bridge/Cargo.toml
  solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/wormhole.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/utils.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/wormhole_tests.rs
  solana-programs/staking-bridge/tests/staking-bridge.ts
  solana-programs/staking-bridge/tests/wormholeTestUtils.ts
Labels: size/XL

#5811 Modify users fkey constraint
  discovery-provider/ddl/migrations/0025_modify_usesr_fkey.sql
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#5937 Update sdk + solana on identity
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/audiusLibsInstance.js
Labels: size/XS

#5938 Add cache-control header for images
  mediorum/server/serve_blob.go
Labels: size/XS

#5939 dms: keep peer cursors across restarts
  comms/discovery/rpcz/peer_sweeper.go
Labels: size/XS

#5911 [PROTO-1232] Add observability into replication
  mediorum/go.mod
  mediorum/go.sum
  mediorum/httputil/custom_dns.go
  mediorum/main.go
  mediorum/radix/radix.go
  mediorum/radix/radix_test.go
  mediorum/radix/rserver/rserver.go
  mediorum/server/radix_bridge.go
  mediorum/server/repair.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
Labels: size/XXL

#5935 Add db conn timeout to mediorum + mutex to crud sweep
  mediorum/server/serve_crud.go
  mediorum/server/server.go
Labels: size/S

#5934 Add expected content size to healthz
  mediorum/server/repair.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/M

#5942 Add timeout and fix radix segfault
  mediorum/radix/radix.go
Labels: size/S

#5941 Add transcode progress to callback
  libs/src/services/creatorNode/CreatorNode.ts
Labels: size/M

#5945 sdk update
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/package-lock.json
  discovery-provider/plugins/pedalboard/package.json
  identity-service/package-lock.json
  identity-service/package.json
  monitoring/exporters/sdk/package-lock.json
  monitoring/exporters/sdk/package.json
  monitoring/healthz/package-lock.json
  monitoring/healthz/package.json
  package-lock.json
  packages/common/package.json
  packages/embed/package.json
  packages/mobile/package.json
  packages/web/package.json
  sdk-consumer/package-lock.json
  sdk-consumer/package.json
Labels: size/S

#5946 [PAY-1819] Allow transferring to existing USDC ATAs
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/M

#5951 [PAY-1827] Fix withdrawals indexing
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/XS

#5954 Add `run-probers-workflow` argument to CI
  .circleci/src/@continue_config.yml
Labels: size/XS

#5957 [C-3072] Update editTrackForm preview button to use the new styles
  packages/web/src/pages/upload-page/forms/EditTrackForm.module.css
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/S

#5956 Migrate client release versioning fix
  .circleci/config.yml
  package-lock.json
  package.json
  packages/common/package.json
  packages/embed/package.json
  packages/eslint-config-audius/package.json
  packages/mobile/package.json
  packages/probers/package.json
  packages/stems/package.json
  packages/web/package.json
Labels: size/S

#5959 Fix CI Workflow triggers
  .circleci/config.yml
Labels: size/M

#5962 [PAY-1641] Fix social overlap
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
Labels: size/XS

#5952 [C-3042, C-3046, C-3073] Update back button and min-width of edit forms in new upload flow
  packages/web/src/components/back-button/BackButton.js
  packages/web/src/components/back-button/BackButton.module.css
  packages/web/src/pages/upload-page/forms/EditCollectionForm.module.css
  packages/web/src/pages/upload-page/forms/EditTrackForm.module.css
Labels: size/M

#5964 [PAY-1825] Wait to render dashboard on listen data
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Labels: size/XS

#5961 Require init step before triggering workflows
  .circleci/config.yml
Labels: size/XS

#5960 [C-3078] Fix sdk web build
  libs/src/sdk/index.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/index.ts
Labels: size/XS

#5948 Delete remaining old fkeys on blocks table
  discovery-provider/ddl/migrations/0030_drop_old_block_key.sql
Labels: size/M

#5958 [C-3066] Update cursor on disabled modal radio items
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
Labels: size/S

#5926 Add caddy Dockerfile
  caddy/Dockerfile
  caddy/README.md
Labels: size/S

#5966 [PAY-1757] Adds details modals for purchases/sales tables
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/modals/usdc-purchase-details-modal/index.ts
  packages/web/src/components/track/DynamicTrackArtwork.module.css
  packages/web/src/components/track/DynamicTrackArtwork.tsx
  packages/web/src/components/usdc-purchase-details-modal/USDCPurchaseDetailsModal.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackLink.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/styles.module.css
  packages/web/src/components/usdc-purchase-details-modal/components/types.ts
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
Labels: size/XL

#5974 [C-3050] Update the text and icon for the ImageSelectionButton
  packages/web/src/components/image-selection/ImageSelectionButton.js
  packages/web/src/components/upload/UploadArtwork.js
Labels: size/S

#5975 [PROTO-1250] Move celery to eventlets
  discovery-provider/scripts/start.sh
Labels: size/XS

#5982 [C-3064] Update the hover and focus styles for the releaseDateField border
  packages/web/src/pages/upload-page/fields/ReleaseDateField.module.css
Labels: size/XS

#5983 [INF-471] Only run integration and gcp workflows on protocol
  .circleci/config.yml
Labels: size/S

#5980 Fix not all tracks being rendered on library tracks page PAY-1831
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/XS

#5977 [Library QA] Gate offline purchases toggle; add padding to filter pills PAY-1845 PAY-1830
  packages/mobile/src/components/drawers/OfflineListeningDrawer.tsx
  packages/web/src/components/header/desktop/Header.module.css
Labels: size/S

#5984 [C-3062] Update track preview item styles
  packages/web/src/components/upload/TrackPreview.module.css
  packages/web/src/components/upload/TrackPreviewNew.tsx
Labels: size/M

#5971 Refactor edit-playlist-modal
  packages/common/src/store/ui/modals/edit-playlist-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/mobile/TopLevelPage.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/editPlaylistModal/selectors.ts
  packages/web/src/store/application/ui/editPlaylistModal/slice.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/types.ts
Labels: size/L

#5953 [C-2786] Add upload-track prober test for upload redesign
  package-lock.json
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/probers/cypress/e2e/uploadTrackLegacy.cy.ts
  packages/probers/cypress/fixtures/aiAttribution.json
  packages/probers/cypress/support/commands.ts
  packages/probers/package.json
  packages/stems/src/components/RadioButtonGroup/RadioButtonGroup.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/types.ts
  packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/data-entry/TagInput.js
  packages/web/src/components/data-entry/TagInput.module.css
  packages/web/src/components/form-fields/SegmentedControlField.tsx
  packages/web/src/components/form-fields/TagField.tsx
  packages/web/src/components/help-callout/HelpCallout.tsx
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.module.css
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/AttributionField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.module.css
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/TrackInfo.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/types.ts
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.module.css
  packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
  packages/web/src/pages/upload-page/fields/TrackMetadataFields.tsx
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.module.css
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/XL

#5988 [C-3071] Fix collection upload validation
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XS

#5972 Add purchased track to library; fix favoriting purchased tracks PAY-1829 PAY-1788
  packages/web/src/common/store/pages/saved/lineups/sagas.js
Labels: size/L

#5990 [PAY-1774] Fix previewing in web chat track tiles
  packages/common/src/hooks/chats/useTrackPlayer.ts
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Labels: size/M

#5986 Always delete gcp disks after workflow completion and instance removal
  .circleci/src/commands/gcp-run.yml
  .circleci/src/jobs/gcp-cleanup.yml
Labels: size/S

#5991 Update Sdk scheme to create function to fix release date validation
  packages/web/src/pages/upload-page/validation.ts
Labels: size/L

#5992 [PAY-1842] Update usdc twitter shares to pass track URLs correctly
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
Labels: size/M

#5995 [PAY-1848] Update libs solana/web3 + spl-token packages
  libs/package-lock.json
  libs/package.json
  libs/src/services/solana/SolanaWeb3Manager.ts
  libs/src/services/solana/tokenAccount.ts
Labels: size/M

#5996 Revert "Surface image cid cache in feed endpoints (#5910)"
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/api_helpers.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/utils/elasticdsl.py
  discovery-provider/src/utils/helpers.py
Labels: size/L

#5997 [C-3080] Hide artwork for collection uploads
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
Labels: size/S

#5999 [C-3082] Fix track extension on select page
  packages/web/src/components/upload/TrackPreviewNew.tsx
  packages/web/src/pages/upload-page/components/TracksPreviewNew.tsx
Labels: size/XS

#6004 [C-3086] Add missing media android permission
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: size/XS

#6002 Fix iOS build-upload ci step
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#6005 Update sdk on identity (upgraded solana in libs)
  identity-service/package-lock.json
  identity-service/package.json
Labels: size/XS

#6006 [C-3087] Fix android drawer overflow
  packages/mobile/src/app/Drawers.tsx
Labels: size/XS

#6000 [C-3070, C-3074] Add correct visit CTAs to the finish page of the new upload flow
  packages/web/src/pages/upload-page/components/FinishPage.module.css
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/M

#6007 [PAY-1823][PAY-1782] Minor USDC ui fixes
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
Labels: size/XS

#5987 [C-3037] Improve client bundle size
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/package.json
  monitoring/exporters/sdk/package.json
  monitoring/healthz/package.json
  package-lock.json
  packages/common/package.json
  packages/common/src/api/purchases.ts
  packages/common/src/api/user.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/context/appContext.ts
  packages/common/src/models/Collectible.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/solana-client/SolanaClient.ts
  packages/common/src/store/collectibles/slice.ts
  packages/common/src/store/pages/audio-transactions/slice.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/ui/modals/edit-track-modal/index.ts
  packages/common/src/store/ui/modals/edit-track-modal/selectors.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/embed/package.json
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/package.json
  packages/web/craco.config.ts
  packages/web/package.json
  packages/web/src/assets/animations/cityWalking.json
  packages/web/src/components/data-entry/FormTile.js
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/share-modal/index.ts
  packages/web/src/components/stripe-on-ramp-modal/index.ts
  packages/web/src/index.css
  packages/web/src/index.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/modals/AppModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/visualizer/Visualizer.tsx
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
  packages/web/src/root.tsx
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/services/audius-backend/eagerLoadUtils.ts
  packages/web/src/services/audius-backend/getLibs.ts
  packages/web/src/store/application/ui/editTrackModal/actions.ts
  packages/web/src/store/application/ui/editTrackModal/reducer.ts
  packages/web/src/store/application/ui/editTrackModal/types.ts
  packages/web/src/store/reducers.ts
  packages/web/src/store/token-dashboard/disconnectWallet.ts
  packages/web/src/store/types.ts
  sdk-consumer/package.json
Labels: size/L

#6008 Check db size before disk size
  mediorum/server/monitor.go
Labels: size/S

#5973 [PROTO-1223] Add sla auditor build step
  .circleci/src/workflows/discovery.yml
  dev-tools/compose/docker-compose.pedalboard.yml
  dev-tools/compose/docker-compose.yml
Labels: size/S

#6012 [PAY-1841] Fix some issues with setting preview start times
  packages/common/src/schemas/index.ts
  packages/web/src/components/track/EditTrackModal.js
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/XS

#6018 Better asyncio event loop handling when caching images in discovery
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#5976 Consolidate errors in discovery health check
  discovery-provider/src/queries/get_health.py
Labels: size/S

#6019 Return status 422 if ffprobe fails
  mediorum/server/serve_upload.go
Labels: size/M

#6014 [C-3067] Update upload flow artwork popup position
  packages/web/src/components/image-selection/ImageSelectionPopup.js
Labels: size/XS

#6017 [C-3065] Update modal footer placement in contextual menu to make the save button sticky
  packages/web/src/components/data-entry/ContextualMenu.tsx
Labels: size/S

#6021 Add effect to re-set the price form value if missing
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
  packages/web/src/utils/tokenInput.ts
Labels: size/S

#6024 [PAY-1846] Make solana transaction external linking consistent
  packages/common/src/utils/linking.ts
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx
  packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Labels: size/S

#6023 [C-3034] Add scrollToTop on track upload form submit
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Labels: size/XS

#6022 Add remote var timeout for handle check
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/upload/sagas.js
Labels: size/M

#6003 [C-3061] Fix harmony button states
  packages/stems/src/components/HarmonyButton/BaseButton.module.css
  packages/stems/src/components/HarmonyButton/HarmonyButton.module.css
Labels: size/XS

#6025 Remove set -x
  .circleci/src/jobs/deploy.yml
Labels: size/XS

#5950 [C-2960][C-3069] Add transcode progress tracking for upload progress
  packages/common/src/store/upload/actions.ts
  packages/common/src/store/upload/reducer.ts
  packages/common/src/store/upload/selectors.ts
  packages/common/src/store/upload/types.ts
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
Labels: size/L

#6009 [C-3084] Add floating upload submit button
  packages/web/src/components/play-bar/desktop/PlayBar.module.css
  packages/web/src/pages/App.module.css
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.module.css
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
  packages/web/src/pages/upload-page/components/SelectPageNew.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/M

#6026 [C-3092] Add error on empty file upload
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
  packages/web/src/components/upload/InvalidFileType.js
  packages/web/src/components/upload/InvalidFileType.module.css
  packages/web/src/pages/upload-page/components/SelectPageNew.tsx
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
  packages/web/src/pages/upload-page/store/utils/processFiles.ts
Labels: size/M

#6020 Optimize pkeys and indices by dropping is_current
  discovery-provider/ddl/migrations/0031_drop_current_indices.sql
  discovery-provider/integration_tests/queries/test_undisbursed_challeges.py
  discovery-provider/integration_tests/queries/test_user_playlist_update.py
Labels: size/L

#6015 Filter users by followers in sitemaps
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/src/queries/get_sitemap.py
Labels: size/S

#6028 No range images
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
Labels: size/S

#6011 Make sure new (or deleted) collections created by user are added (or removed) in library PAY-1832
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/M

#6032 [PAY-1847] UX fixes for USDC mobile/chat track tiles
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#6031 Add central location for sql-ts
  discovery-provider/es-indexer/package-lock.json
  discovery-provider/es-indexer/package.json
  discovery-provider/es-indexer/scripts/sql-ts.ts
  discovery-provider/plugins/notifications/README.md
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/notifications/package.json
  discovery-provider/plugins/notifications/scripts/sql-ts.ts
  packages/sql-ts/.gitignore
  packages/sql-ts/README.md
  packages/sql-ts/package.json
  packages/sql-ts/res/content-node.ts
  packages/sql-ts/res/discovery-node.ts
  packages/sql-ts/src/index.ts
Labels: size/XXL

#6039 Fix tracks library bug PAY-1864
  packages/web/src/common/store/pages/saved/lineups/sagas.js
Labels: size/XS

#6029 fix app notifs sql
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/S

#6040 Add root name to allow release branch generation
  package-lock.json
  package.json
Labels: size/XS

#6044 PAY-1641 Fix socials overflow
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/stats/Stats.module.css
Labels: size/XS

#6038 [PROTO-1228] Persist and track repair.go
  mediorum/server/db.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/misc.tsx
Labels: size/XL

#6043 [PROTO-1264] Don't redirect to images
  mediorum/cidutil/cidutil.go
  mediorum/cidutil/cidutil_test.go
  mediorum/cmd/reaper/reaper_test.go
  mediorum/ddl/ddl.go
  mediorum/server/helpers.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_image_test.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/test_main_test.go
  mediorum/server/testdata/claudius.jpg
  mediorum/server/transcode.go
Labels: size/XL

#6047 [PAY-1854] Add feature flag check for search autocomplete
  packages/web/src/common/store/search-bar/sagas.ts
Labels: size/S

#6048 Update tag replacement command
  .circleci/src/jobs/release-audius-docker-compose.yml
Labels: size/XS

#6045 [PAY-1865] Fix colors on dashboard page
  docs/src/css/colors.css
  docs/src/theme/dark.js
  docs/src/theme/light.js
  packages/web/src/assets/styles/colors.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
  packages/web/src/pages/artist-dashboard-page/components/TotalPlaysChart.js
  packages/web/src/utils/theme/dark.ts
  packages/web/src/utils/theme/default.ts
  packages/web/src/utils/theme/matrix.ts
Labels: size/M

#6046 Dedupe reposts/saves from album bug
  discovery-provider/ddl/migrations/0031_dedupe_repost_saves.sql
Labels: size/M

#6050 skip API image cid resolution step
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#6054 [C-3094] Remove repost from smart collection
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#6057 Update mookme to 2.4.1
  package-lock.json
  package.json
Labels: size/XS

#6053 [C-3103] Fix share modal playlist description
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Labels: size/XS

#6059 [C-3099] Fix bad width calculation on segmented control
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/types.ts
  packages/web/src/pages/upload-page/components/TracksPreviewNew.tsx
Labels: size/S

#5998 Export CSV for sales, purchases, and withdrawals
  discovery-provider/src/api/v1/transactions.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/download_csv.py
  discovery-provider/src/utils/csv_writer.py
Labels: size/L

#6061 [C-3108, C-3111] Fix collection upload
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Labels: size/S

#6060 [C-3109] Fix null error in FinishPage
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
Labels: size/XS

#6063 Lock tables during pkey index migration
  discovery-provider/ddl/migrations/0031_drop_current_indices.sql
Labels: size/S

#6064 [C-3110] Remove artwork progress from upload progress bar
  packages/common/src/store/upload/selectors.ts
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
Labels: size/XS

#6062 don't 503 for isSeeding
  mediorum/server/serve_health.go
Labels: size/XS

#6052 [C-3088] Remove open telemetry
  package-lock.json
  packages/web/package.json
  packages/web/src/index.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/utils/tracer.ts
Labels: size/L

#6069 Get missing Upload from peer.
  mediorum/ddl/ddl.go
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/helpers.go
  mediorum/server/peer_req.go
  mediorum/server/repair_test.go
  mediorum/server/serve_image_test.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#6049 Fix tracks table loading one track at a time PAY-1868 PAY-1873
  packages/web/src/components/table/Table.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/L

#6070 Fix SLA auditor numeric values
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audit.ts
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audits/version.ts
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/proposal.ts
Labels: size/M

#6036 Implement new Library feature for mobile web + several bug fixes PAY-1863 C-2985 PAY-1263 C-2604 C-3100
  packages/web/src/components/header-button/HeaderButton.module.css
  packages/web/src/components/header/mobile/Header.module.css
  packages/web/src/components/lineup/InfiniteCardLineup.tsx
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
Labels: size/XL

#6071 [C-3113] Fix edit-track modal state
  packages/common/src/store/ui/modals/edit-track-modal/index.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
Labels: size/S

#6073 Fix staging build web
  packages/common/src/utils/allSettled.ts
  packages/web/src/pages/visualizer/Visualizer.tsx
Labels: size/XS

#6076 repair.go skip image variants
  mediorum/server/db.go
  mediorum/server/repair.go
  mediorum/server/server.go
Labels: size/M

#6058 [C-3105] Create Harmony package
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  package-lock.json
  package.json
  packages/harmony/.eslintrc.js
  packages/harmony/package.json
  packages/harmony/rollup.config.js
  packages/harmony/src/index.ts
  packages/harmony/tsconfig.json
  packages/stems/package.json
Labels: size/L

#6074 [C-3114] Fix complex upload patterns
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/stems/src/components/ProgressBar/ProgressBar.tsx
  packages/stems/src/components/ProgressBar/types.ts
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
  packages/web/src/pages/upload-page/components/FinishPageNew.tsx
  packages/web/src/pages/upload-page/components/ShareBannerNew.tsx
  packages/web/src/pages/upload-page/fields/AttributionField.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
  packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx
  packages/web/src/pages/upload-page/types.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/L

#6077 Revert "Bump version to 0.4.10"
  discovery-provider/.version.json
  mediorum/.version.json
Labels: size/XS

#6078 non blocking notifs
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/main.ts
  discovery-provider/plugins/notifications/src/tasks/appNotifications.ts
  discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/S

#6051 [PROTO-1189] Containerize healthz to run on nodes
  monitoring/healthz/Dockerfile
  monitoring/healthz/README.md
  monitoring/healthz/package-lock.json
  monitoring/healthz/package.json
  monitoring/healthz/src/main.tsx
  monitoring/healthz/vite.config.ts
Labels: size/M

#6056 [PAY-1856][PAY-1857] Adds discovery support for pay extra field
  dev-tools/commands/src/purchase-track.mjs
  dev-tools/commands/src/upload-track.mjs
  discovery-provider/ddl/migrations/0032_add_usdc_purchases_extra_amount.sql
  discovery-provider/integration_tests/queries/test_get_usdc_purchases.py
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/models/users/usdc_purchase.py
  discovery-provider/src/tasks/index_user_bank.py
  packages/libs/src/sdk/api/generated/default/apis/DeveloperAppsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/ResolveApi.ts
  packages/libs/src/sdk/api/generated/default/apis/TipsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/Purchase.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/L

#6037 [PAY-1835] Upgrade @solana/web3 and @solana/spl-token everywhere
  dev-tools/commands/package.json
  package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/ui/withdraw-usdc/slice.ts
  packages/common/src/utils/wallet.ts
  packages/libs/package-lock.json
  packages/libs/package.json
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/services/solana/tokenAccount.ts
  packages/web/package.json
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/XL

#6085 Fix iOS 17 build
  package-lock.json
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/XS

#6087 Replace new image picker with old version
  packages/common/src/store/cache/collections/types.ts
  packages/mobile/src/components/core/FormImageInput.tsx
  packages/mobile/src/components/core/FormTextInput.tsx
  packages/mobile/src/components/core/Screen/ScreenContent.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/components/form-screen/FormScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/signon/ProfileImage.tsx
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/utils/launchSelectImageActionSheet.ts
  packages/mobile/src/utils/theme.ts
Labels: size/L

#6088 Replace global react-native-crypto with @peculiar/webcrypto
  package-lock.json
  packages/mobile/index.js
  packages/mobile/package.json
Labels: size/XS

#6089 [C-3079] Fixes blocking mobile upload validation error
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
Labels: size/XS

#6055 Use root wallet for Stripe USDC purchase, relay transfer to userbank
  identity-service/src/audiusLibsInstance.js
  identity-service/src/routes/solana.js
  identity-service/src/utils/relayHelpers.js
  identity-service/src/utils/relayUtils.js
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
Labels: size/L

#6090 [C-3116] Pipe collection release_date through to tracks
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XS

#6075 Color unhealthy nodes red in healthz
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/index.css
Labels: size/M

#6068 Fix editing previews
  dev-tools/commands/src/edit-track.mjs
  dev-tools/commands/src/upload-track.mjs
  discovery-provider/src/tasks/metadata.py
  packages/common/src/schemas/index.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/M
