Repository AudiusProject/apps, pull requests merged in 2023-08, with the labels that each got.

#5716 Default init config objects for userbanks functions
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/XS

#5706 [PAY-1667] Check for access to UDSC gated content
  discovery-provider/src/premium_content/helpers.py
  discovery-provider/src/premium_content/premium_content_access_checker.py
  discovery-provider/src/premium_content/premium_content_constants.py
  discovery-provider/src/premium_content/premium_content_types.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/L

#5719 [PAY-1666] Update identity stripe endpoint to support usdc
  identity-service/src/routes/stripe.js
  libs/src/services/identity/IdentityService.ts
Labels: size/S

#5697 PLAT-1140: discovery relay anti abuse
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/apps/relay/src/abi.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/antiAbuse.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/error.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/routes/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/scripts/sandbox.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/types/relay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/validate.ts
  discovery-provider/plugins/pedalboard/package-lock.json
  identity-service/src/utils/antiAbuse.js
Labels: size/L

#5721 Change stripe supported currency to sol
  libs/src/services/identity/IdentityService.ts
Labels: size/XS

#5714 PLAT-1161: skip push on playlist update and if track already existed
  discovery-provider/ddl/functions/handle_playlist.sql
  discovery-provider/integration_tests/notifications/test_playlist.py
  discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/M

#5723 Cleanup subgenre db migration
  discovery-provider/ddl/migrations/0018_clean_up_subgenre.sql
Labels: size/S

#5725 Don't only check patch in version check
  libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
Labels: size/XS

#5709 [PAY-1645][PAY-1644] Library albums and playlist endpoints
  discovery-provider/integration_tests/queries/test_get_collections_library.py
  discovery-provider/integration_tests/queries/test_get_track_library.py
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_collection_library.py
  discovery-provider/src/queries/get_playlists.py
  discovery-provider/src/queries/get_track_library.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/XL

#5722 [PLAT-1159] Migrate sum(segments) to duration field
  discovery-provider/ddl/migrations/0019_backfill_track_duration.sql
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/types/db.ts
  discovery-provider/integration_tests/queries/test_get_track_library.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  discovery-provider/src/models/tracks/track.py
  discovery-provider/src/queries/get_track_library.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/schemas/track_schema.json
  discovery-provider/src/tasks/metadata.py
Labels: size/XL

#5728 [PAY-1659] Improve library endpoint swagger types
  discovery-provider/src/api/v1/models/activities.py
  discovery-provider/src/api/v1/users.py
Labels: size/M

#5730 revert ID const change
  identity-service/src/utils/antiAbuse.js
Labels: size/S

#5729 [CON-803] Support moving data between CDK drivers
  mediorum/README.md
  mediorum/main.go
  mediorum/persistence/persistence.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
Labels: size/L

#5732 Remove expensive cid_lookup backfill and slow down beaming
  mediorum/ddl/cid_lookup.sql
  mediorum/server/cid_log_client.go
Labels: size/M

#5731 Fix broken es tests and add logs
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/integration_tests/queries/test_search.py
  discovery-provider/integration_tests/queries/test_search_track_tags.py
  discovery-provider/integration_tests/queries/test_search_user_tags.py
  discovery-provider/integration_tests/tasks/test_get_feed_es.py
Labels: size/S

#5733 Fix file-type import
  libs/src/sdk/types/File.ts
Labels: size/XS

#5726 Fix email copy for favorited
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
Labels: size/S

#5735 Fix userbank lookup for USDC
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/XS

#5736 [C-2841] Fix offset for es feed
  discovery-provider/src/queries/get_feed_es.py
Labels: size/XS

#5739 [PAY-1693] SDK: Don't cache chat secrets on create, make client refetch them
  libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/XS

#5741 Separate health check for registration
  libs/src/services/ethContracts/ServiceProviderFactoryClient.ts
  libs/tests/governanceTest.js
  libs/tests/helpers.js
  libs/tests/stakingTest.js
  mediorum/server/serve_health.go
Labels: size/M

#5742 Fix gh draft
  .circleci/src/jobs/release-github-draft.yml
Labels: size/S

#5743 [C-2936] Update sdk docs colors
  docs/docusaurus.config.js
  docs/src/css/colors.css
  docs/src/css/custom.css
  docs/static/img/logo-white.png
Labels: size/XL

#5724 Skip v0 txs in user bank indexer
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/S

#5744 [C-2935] Log dev app details
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XS

#5746 Fix replicating Qm images
  mediorum/cidutil/cidutil.go
  mediorum/server/cid_log_test.go
  mediorum/server/replicate.go
  mediorum/server/server.go
Labels: size/L

#5734 [CON-804] Conslidate mediorum healthz and show storage driver
  mediorum/ddl/ddl.go
  monitoring/healthz/src/Content.tsx
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/Mediorum.tsx
  monitoring/healthz/src/Router.tsx
  monitoring/healthz/src/query.ts
Labels: size/L

#5662 Create em_logs table and index txs
  discovery-provider/ddl/migrations/0014_add_revert_blocks.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_revert_blocks.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_skip_tx.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/models/indexing/revert_block.py
  discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  discovery-provider/src/tasks/entity_manager/entities/grant.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entities/user_replica_set.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#5749 [CON-807] Remove legacy mediorum code including seeding cid_lookup
  mediorum/server/cid_log_client.go
  mediorum/server/cid_log_server.go
  mediorum/server/monitor.go
  mediorum/server/replicate.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#5750 Drop ursm_content_nodes, delegations, app_delegates
  discovery-provider/ddl/migrations/0020_drop_unused_tables.sql
  discovery-provider/integration_tests/utils.py
  discovery-provider/src/models/indexing/ursm_content_node.py
  discovery-provider/src/queries/get_ursm_cnodes.py
  discovery-provider/src/queries/queries.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5747 Adjust sdk docs alert colors
  docs/src/css/colors.css
  docs/src/css/custom.css
Labels: size/S

#5748 Add keywords to sdk package
  libs/package.json
Labels: size/S

#5755 Add stream fallback for rendezvous
  discovery-provider/src/api/v1/tracks.py
Labels: size/S

#5757 Fix user events to use existing records
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#5751 Delete network monitoring
  discovery-provider/plugins/network-monitoring/.dockerignore
  discovery-provider/plugins/network-monitoring/.gitignore
  discovery-provider/plugins/network-monitoring/Dockerfile
  discovery-provider/plugins/network-monitoring/Dockerfile.test
  discovery-provider/plugins/network-monitoring/README.md
  discovery-provider/plugins/network-monitoring/assets/NetworkMonitoring.png
  discovery-provider/plugins/network-monitoring/assets/network_monitoring_er_diagram.png
  discovery-provider/plugins/network-monitoring/docker-compose.yaml
  discovery-provider/plugins/network-monitoring/network-monitoring-cron
  discovery-provider/plugins/network-monitoring/new_job.sh
  discovery-provider/plugins/network-monitoring/package-lock.json
  discovery-provider/plugins/network-monitoring/package.json
  discovery-provider/plugins/network-monitoring/src/config.ts
  discovery-provider/plugins/network-monitoring/src/db/config/config.json
  discovery-provider/plugins/network-monitoring/src/db/index.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_foreign_connection.ts
  discovery-provider/plugins/network-monitoring/src/db/migrations/create_tables.ts
  discovery-provider/plugins/network-monitoring/src/db/sql/README.md
  discovery-provider/plugins/network-monitoring/src/db/sql/create_tables.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/foreign_connection.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/import_schema.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/new_run.sql
  discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
  discovery-provider/plugins/network-monitoring/src/discovery/index.ts
  discovery-provider/plugins/network-monitoring/src/discovery/queries.ts
  discovery-provider/plugins/network-monitoring/src/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/index.ts
  discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
  discovery-provider/plugins/network-monitoring/src/prometheus.ts
  discovery-provider/plugins/network-monitoring/src/tracer.ts
  discovery-provider/plugins/network-monitoring/src/utils.ts
  discovery-provider/plugins/network-monitoring/tsconfig.json
  monitoring/prometheus/ymls/local.yml
  monitoring/prometheus/ymls/prod.yml
  monitoring/prometheus/ymls/stage.yml
Labels: size/XXL

#5762 [CON-811] Self-mark unhealthy when unable to query upload count
  mediorum/server/monitor.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/M

#5763 Fix resolve to use slug/handle for collections
  discovery-provider/integration_tests/api/v1/utils/resolve_url_test.py
  discovery-provider/src/api/v1/playlists.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/api/v1/utils/resolve_url.py
Labels: size/M

#5760 Fix backfill of playlist routes to sanitize like client
  discovery-provider/ddl/migrations/0021_backfill_playlist_routes_fixed.sql
Labels: size/M

#5696 PLAT-1141: discovery relay rate limit
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/apps/relay/src/abi.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimitConfig.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/package-lock.json
  discovery-provider/plugins/plugins/apps/blog/next-env.d.ts
Labels: size/L

#5758 [C-2942] Improve logs around developer app rate limits and reads
  discovery-provider/src/utils/helpers.py
  identity-service/src/rateLimiter.js
Labels: size/S

#5764 [CON-817] Try cuckoo filter first for faster v2 lookup
  mediorum/server/cuckoo.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/server.go
Labels: size/S

#5768 [INF-434] Upgrade identity and libs to node.js 18.17
  identity-service/Dockerfile
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/index.ts
  libs/Dockerfile
  libs/package-lock.json
  libs/package.json
  libs/src/services/dataContracts/EntityManagerClient.ts
  libs/tsconfig.json
Labels: size/M

#5769 Add cascading deletes to revert_block fkey
  discovery-provider/ddl/migrations/0014_add_revert_blocks.sql
  discovery-provider/src/utils/helpers.py
Labels: size/S

#5770 [PAY-1699] Assert account key patch in rewards manager program
  solana-programs/reward-manager/program/src/processor.rs
Labels: size/S

#5772 Fix bug where duplicate slugs get written to db
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#5771 [CON-818] Race mediorum redirects 5 at a time
  mediorum/server/cuckoo.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
Labels: size/M

#5753 Update the upload track metadata schema for the new upload flow
  libs/src/sdk/api/tracks/types.ts
Labels: size/L

#5773 block keys with zero or less configured calls
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimitConfig.ts
Labels: size/XS

#5776 [INF-436] Upgrade dev-tools to node 18
  contracts/.nvmrc
  dev-tools/commands/Dockerfile
  dev-tools/commands/package-lock.json
  dev-tools/commands/package.json
  identity-service/.nvmrc
  libs/.nvmrc
Labels: size/S

#5777 [INF-437] Upgrade ci jobs to node 18.17
  .circleci/src/jobs/release-audius-sdk.yml
  .circleci/src/jobs/release-governance.yml
Labels: size/XS

#5778 Re backfill existing playlist routes to match clients formatting exactly
  discovery-provider/ddl/migrations/0022_backfill_playlist_routes_like_client.sql
  discovery-provider/es-indexer/src/indexNames.ts
Labels: size/M

#5761 cleanup unfindable CIDs
  mediorum/ddl/clean_up_unfindable_cids.sql
  mediorum/ddl/ddl.go
Labels: size/L

#5780 [C-2947] Don't default services (except logger)
  libs/src/sdk/api/albums/AlbumsApi.test.ts
  libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  libs/src/sdk/api/tracks/TracksApi.test.ts
  libs/src/sdk/api/users/UsersApi.test.ts
  libs/src/sdk/services/EntityManager/EntityManager.ts
  libs/src/sdk/services/EntityManager/constants.ts
  libs/src/sdk/services/EntityManager/types.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/services/Storage/constants.ts
  libs/src/sdk/services/Storage/types.ts
  libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  libs/src/sdk/services/StorageNodeSelector/constants.ts
  libs/src/sdk/services/StorageNodeSelector/types.ts
Labels: size/M

#5781 [C-2949] Fix creatorNodeSelection, getNStorageNodes
  libs/src/AudiusLibs.ts
  libs/src/NativeAudiusLibs.ts
  libs/src/WebAudiusLibs.ts
  libs/src/services/creatorNode/CreatorNode.ts
  libs/src/utils/getNStorageNodes.ts
Labels: size/M

#5766 Fix activity sub-types for library endpoints PAY-1679
  discovery-provider/src/api/v1/models/activities.py
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/api/v1/users.py
Labels: size/M

#5784 add reasonable default to chain id
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
Labels: size/XS

#5785 remove error if undefined
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
Labels: size/XS

#5786 handle nonconfigured aao
  discovery-provider/plugins/pedalboard/apps/relay/src/antiAbuse.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
Labels: size/XS

#5782 [CON-819] Cache image lookup and add timing headers
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  mediorum/server/transcode.go
Labels: size/L

#5788 Fix params usage in `get_records_to_save`
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/S

#5787 Add migration to fix broken cover arts
  discovery-provider/ddl/migrations/0023_fix_broken_cover_art_sizes.sql
Labels: size/S

#5774 PLAT-1173: move db initializers around
  discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts
  discovery-provider/plugins/pedalboard/packages/basekit/src/db.ts
  discovery-provider/plugins/pedalboard/packages/basekit/src/index.ts
Labels: size/M

#5789 Allow sdk to upload from browser
  libs/src/sdk/api/playlists/PlaylistsApi.ts
  libs/src/sdk/api/tracks/TracksApi.ts
  libs/src/sdk/api/users/UsersApi.ts
  libs/src/sdk/services/Storage/Storage.ts
  libs/src/sdk/types.ts
  libs/src/sdk/utils/cid.ts
Labels: size/M

#5792 [CON-823] Log when serving from non-CDK disk
  mediorum/server/serve_legacy.go
Labels: size/XS

#5791 PLAT-1176: cleanup relay
  dev-tools/audius-compose
  dev-tools/commands/src/utils.mjs
  dev-tools/compose/docker-compose.pedalboard.yml
  dev-tools/compose/nginx_ingress.conf
  discovery-provider/plugins/pedalboard/apps/relay/package.json
  discovery-provider/plugins/pedalboard/apps/relay/src/antiAbuse.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/config.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimitConfig.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/scripts/sandbox.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
  discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
  discovery-provider/plugins/pedalboard/docker/Dockerfile
  discovery-provider/plugins/pedalboard/package-lock.json
  discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts
Labels: size/L

#5790 Update playlist trending to only compute one variant
  discovery-provider/src/queries/get_trending_playlists.py
  discovery-provider/src/trending_strategies/EJ57D_trending_playlists_strategy.py
  discovery-provider/src/trending_strategies/trending_strategy_factory.py
  monitoring/healthz/src/Router.tsx
Labels: size/M

#5794 [CON-823] Deprecate serving from non-CDK disk
  mediorum/server/serve_blob.go
  mediorum/server/serve_health.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/M

#5796 Rm slashes from playlist routes backfill
  discovery-provider/ddl/migrations/0022_backfill_playlist_routes_like_client.sql
Labels: size/XS

#5783 Return direct links with cids for images + cache
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/playlists.py
  discovery-provider/src/api/v1/models/tracks.py
  discovery-provider/src/api/v1/models/users.py
Labels: size/L

#5793 Improve pedalboard dockerfile
  discovery-provider/plugins/pedalboard/docker/Dockerfile
Labels: size/S

#5801 Drop stage discovery 2 deploy steps
  .circleci/src/workflows/discovery.yml
Labels: size/S

#5800 [C-2957] Fix sitemap generation
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/src/queries/get_sitemap.py
Labels: size/L

#5802 Improve sitemap perf
  discovery-provider/ddl/migrations/0024_user_count_idx.sql
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_sitemap.py
  discovery-provider/src/tasks/cache_entity_counts.py
Labels: size/M

#5798 [PAY-1643] Re-add support for track library filter query
  discovery-provider/integration_tests/queries/test_get_track_library.py
  discovery-provider/src/queries/get_track_library.py
Labels: size/L

#5808 [CON-829] Add legacy paths counter & expose in healthz
  mediorum/server/serve_blob.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_metrics.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/M

#5809 Add RWMutex to legacy path counts, and block segments+metadata
  mediorum/server/serve_legacy.go
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/M

#5810 Fix description limit
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/playlist.py
  discovery-provider/src/tasks/entity_manager/entities/track.py
  discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/S

#5814 Fix date check in trending rewards
  discovery-provider/integration_tests/challenges/test_trending_challenge.py
  discovery-provider/src/challenges/trending_challenge.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#5812 [PAY-1719] Handle v0 tx in index_spl_token
  discovery-provider/integration_tests/tasks/test_index_spl_token.py
  discovery-provider/integration_tests/utils/test_helpers.py
  discovery-provider/src/solana/solana_client_manager_unit_test.py
  discovery-provider/src/tasks/index_spl_token.py
  discovery-provider/src/utils/helpers.py
Labels: size/XXL

#5805 [PAY-1674][PAY-1718] Staking Bridge Part 3 - Add Anchor tests and docs
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/staking-bridge/.nvmrc
  solana-programs/staking-bridge/.prettierignore
  solana-programs/staking-bridge/Anchor.toml
  solana-programs/staking-bridge/README.md
  solana-programs/staking-bridge/package.json
  solana-programs/staking-bridge/programs/staking-bridge/Cargo.toml
  solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/wormhole.rs
  solana-programs/staking-bridge/scripts/redeemWormholeTokens.ts
  solana-programs/staking-bridge/scripts/setupTestEnv.sh
  solana-programs/staking-bridge/scripts/testCreateStakingBridgeBalancePda.sh
  solana-programs/staking-bridge/scripts/testRaydiumSwap.sh
  solana-programs/staking-bridge/scripts/testWormholeTransfer.sh
  solana-programs/staking-bridge/tests/constants.ts
  solana-programs/staking-bridge/tests/raydiumTestUtils.ts
  solana-programs/staking-bridge/tests/staking-bridge.ts
  solana-programs/staking-bridge/tests/wormholeTestUtils.ts
  solana-programs/staking-bridge/yarn.lock
Labels: size/XXL

#5803 [PAY-1674] Staking Bridge Part 1 - Set up anchor programs
  solana-programs/payment-router/.gitignore
  solana-programs/payment-router/.prettierignore
  solana-programs/payment-router/Anchor.toml
  solana-programs/payment-router/Cargo.lock
  solana-programs/payment-router/Cargo.toml
  solana-programs/payment-router/migrations/deploy.ts
  solana-programs/payment-router/package.json
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/payment-router/programs/payment-router/Xargo.toml
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/payment-router/tsconfig.json
  solana-programs/payment-router/yarn.lock
  solana-programs/staking-bridge/.gitignore
  solana-programs/staking-bridge/.nvmrc
  solana-programs/staking-bridge/.prettierignore
  solana-programs/staking-bridge/.yarnrc.yml
  solana-programs/staking-bridge/Anchor.toml
  solana-programs/staking-bridge/Cargo.lock
  solana-programs/staking-bridge/Cargo.toml
  solana-programs/staking-bridge/README.md
  solana-programs/staking-bridge/migrations/deploy.ts
  solana-programs/staking-bridge/package.json
  solana-programs/staking-bridge/programs/staking-bridge/Cargo.toml
  solana-programs/staking-bridge/programs/staking-bridge/Xargo.toml
  solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/error.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/wormhole.rs
  solana-programs/staking-bridge/scripts/redeemWormholeTokens.ts
  solana-programs/staking-bridge/scripts/setupTestEnv.sh
  solana-programs/staking-bridge/scripts/testCreateStakingBridgeBalancePda.sh
  solana-programs/staking-bridge/scripts/testRaydiumSwap.sh
  solana-programs/staking-bridge/scripts/testWormholeTransfer.sh
  solana-programs/staking-bridge/tests/constants.ts
  solana-programs/staking-bridge/tests/raydiumTestUtils.ts
  solana-programs/staking-bridge/tests/staking-bridge.ts
  solana-programs/staking-bridge/tests/wormholeTestUtils.ts
  solana-programs/staking-bridge/tsconfig.json
  solana-programs/staking-bridge/yarn.lock
Labels: size/XXL

#5817 Add enough data check to sla auditor
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audits/version.ts
  discovery-provider/plugins/pedalboard/apps/sla-auditor/src/config.ts
  discovery-provider/plugins/pedalboard/docker-compose.yml
Labels: size/M

#5813 Add track_price_history fkey
  discovery-provider/ddl/migrations/0025_add_track_price_history_fkey.sql
Labels: size/XS

#5756 Revert blocks with revert_blocks table
  discovery-provider/ddl/functions/handle_repost.sql
  discovery-provider/ddl/functions/handle_save.sql
  discovery-provider/ddl/migrations/0020_cascade_delete.sql
  discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_ursm_entity_manager.py
  discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/entity_manager/utils.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5820 Add link to SLA
  docs/docs/token/running-a-node/sla.md
  docs/i18n-disabled/en/docusaurus-plugin-content-docs/current/token/running-a-node/sla.md
Labels: size/XS

#5821 [INF-448] Update node to 18 in docs/
  docs/.gitignore
  docs/README.md
  docs/package-lock.json
  docs/package.json
  docs/workers-site/package-lock.json
  docs/wrangler.toml
Labels: size/S

#5822 Fix SDK storage upload header
  libs/src/sdk/services/Storage/Storage.ts
Labels: size/XS

#5824 Follow on fix social feature type
  discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  discovery-provider/src/tasks/entity_manager/entities/social_features.py
Labels: size/S

#5826 Increase upload count timeout
  mediorum/server/monitor.go
Labels: size/XS

#5819 [PAY-1673] Add payment router program - Part 2
  solana-programs/payment-router/.nvmrc
  solana-programs/payment-router/.yarnrc.yml
  solana-programs/payment-router/Anchor.toml
  solana-programs/payment-router/README.md
  solana-programs/payment-router/package.json
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/payment-router/programs/payment-router/src/constant.rs
  solana-programs/payment-router/programs/payment-router/src/error.rs
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/programs/payment-router/src/router.rs
  solana-programs/payment-router/scripts/setupTestEnv.sh
  solana-programs/payment-router/scripts/testCreatePaymentRouterBalancePda.sh
  solana-programs/payment-router/scripts/testRoute.sh
  solana-programs/payment-router/tests/constants.ts
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/payment-router/yarn.lock
  solana-programs/staking-bridge/tests/staking-bridge.ts
Labels: size/XXL

#5818 [PAY-1673] Add payment router program - Part 1
  solana-programs/payment-router/.nvmrc
  solana-programs/payment-router/.yarnrc.yml
  solana-programs/payment-router/Anchor.toml
  solana-programs/payment-router/Cargo.lock
  solana-programs/payment-router/README.md
  solana-programs/payment-router/package.json
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/payment-router/programs/payment-router/src/error.rs
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/programs/payment-router/src/router.rs
  solana-programs/payment-router/scripts/setupTestEnv.sh
  solana-programs/payment-router/scripts/testCreatePaymentRouterBalancePda.sh
  solana-programs/payment-router/scripts/testRoute.sh
  solana-programs/payment-router/tests/constants.ts
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/payment-router/yarn.lock
  solana-programs/staking-bridge/tests/staking-bridge.ts
Labels: size/XXL

#5823 Add image cid caching to v0 api
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/queries/query_helpers.py
Labels: size/M

#5828 fix infinite loop possibility when fetching images in API response
  discovery-provider/src/api/v1/helpers.py
Labels: size/S

#5816 [PAY-1617] Add api and query for purchases/sales tables
  discovery-provider/integration_tests/queries/test_get_usdc_purchases.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_usdc_purchases.py
  discovery-provider/src/queries/query_helpers.py
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/XL

#5832 [CON-822] Expose peer reachability in health check
  mediorum/server/monitor.go
  mediorum/server/peer_health.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
  monitoring/healthz/src/DiscoveryHealth.css
  monitoring/healthz/src/DiscoveryHealth.tsx
  monitoring/healthz/src/index.css
Labels: size/L

#5834 Fix publish playlist notifs
  discovery-provider/ddl/functions/handle_playlist.sql
  discovery-provider/integration_tests/queries/test_populate_user_metadata.py
  discovery-provider/src/queries/notifications.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/M

#5827 [PAY-1696][PAY-1697] - Update implementation and add rust unit tests
  solana-programs/payment-router/README.md
  solana-programs/payment-router/programs/payment-router/Cargo.toml
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/programs/payment-router/src/router.rs
  solana-programs/payment-router/programs/payment-router/tests/tests.rs
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/staking-bridge/Anchor.toml
  solana-programs/staking-bridge/Cargo.lock
  solana-programs/staking-bridge/README.md
  solana-programs/staking-bridge/programs/staking-bridge/Cargo.toml
  solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/error.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs
  solana-programs/staking-bridge/programs/staking-bridge/src/wormhole.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/utils.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/wormhole_tests.rs
  solana-programs/staking-bridge/scripts/testCreateStakingBridgeBalanceAtas.sh
  solana-programs/staking-bridge/tests/staking-bridge.ts
Labels: size/XL

#5835 Delete old records after flush
  discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  discovery-provider/integration_tests/tasks/test_update_aggregates.py
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/M

#5836 Fix up misc issues in payment router
  solana-programs/payment-router/README.md
  solana-programs/payment-router/package.json
  solana-programs/payment-router/programs/payment-router/src/lib.rs
  solana-programs/payment-router/programs/payment-router/tests/tests.rs
  solana-programs/staking-bridge/README.md
  solana-programs/staking-bridge/package.json
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/utils.rs
  solana-programs/staking-bridge/programs/staking-bridge/tests/wormhole_tests.rs
  solana-programs/staking-bridge/tests/staking-bridge.ts
Labels: size/L

#5833 Fix asyncio errors when attempting to fetch image cids in API
  discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#5840 Add marshalling and auth headers to purchases and sales endpoints
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/api/v1/users.py
  libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/default/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/Purchase.ts
  libs/src/sdk/api/generated/full/models/PurchasesResponse.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#5839 PLAT-1126: mod CTE in app notifications so it doesnt query all users
  discovery-provider/plugins/notifications/scripts/test-push-notification.ts
  discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
  discovery-provider/plugins/notifications/src/email/notifications/index.ts
  discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/S

#5542 Add is_current_user_subscribed to API and es-indexer
  discovery-provider/es-indexer/src/indexNames.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/types/docs.ts
  discovery-provider/src/api/v1/models/users.py
  discovery-provider/src/queries/query_helpers.py
  discovery-provider/src/queries/response_name_constants.py
  discovery-provider/src/utils/elasticdsl.py
  identity-service/test/sendNotifications/mockLibs.js
  libs/src/api/Users.ts
  libs/src/sdk/api/generated/full/models/UserFull.ts
  libs/src/services/discoveryProvider/DiscoveryProvider.ts
  libs/src/utils/types.ts
Labels: size/M

#5837 Fix broken formats
  discovery-provider/ddl/migrations/0026_fix_broken_images.sql
Labels: size/L

#5842 Clean up READMEs and finish up payment router
  solana-programs/payment-router/README.md
  solana-programs/payment-router/tests/payment-router.ts
  solana-programs/staking-bridge/README.md
  solana-programs/staking-bridge/scripts/redeemWormholeTokens.ts
Labels: size/M

#5843 Fix subscriptions api query
  discovery-provider/src/queries/query_helpers.py
Labels: size/XS

#5846 [PAY-1747] Fix balance caching
  discovery-provider/src/tasks/cache_user_balance.py
Labels: size/S

#5841 [plat-1188] fix bug where delisted tracks cause internal server error
  discovery-provider/src/queries/get_track_stream_info.py
Labels: size/XS

#5844 [PAY-1744] Allow USDC swap tx on relay
  identity-service/package-lock.json
  identity-service/package.json
  identity-service/src/routes/solana.js
  identity-service/src/utils/relayHelpers.js
  identity-service/src/utils/relayUtils.js
  identity-service/src/utils/withdrawUSDCInstructionsHelpers.js
  identity-service/test/routes/solanaTest.js
Labels: size/L

#5845 [PAY-1735] USDC Transactions History API
  dev-tools/commands/src/create-user-bank.mjs
  dev-tools/commands/src/index.mjs
  dev-tools/commands/src/mint-audio.mjs
  dev-tools/commands/src/mint-tokens.mjs
  dev-tools/commands/src/purchase-track.mjs
  discovery-provider/src/api/v1/helpers.py
  discovery-provider/src/api/v1/models/transactions.py
  discovery-provider/src/api/v1/transactions.py
  discovery-provider/src/queries/get_usdc_transactions_history.py
  discovery-provider/src/tasks/index_user_bank.py
  libs/src/sdk/api/generated/full/apis/CidDataApi.ts
  libs/src/sdk/api/generated/full/apis/PlaylistsApi.ts
  libs/src/sdk/api/generated/full/apis/ReactionsApi.ts
  libs/src/sdk/api/generated/full/apis/SearchApi.ts
  libs/src/sdk/api/generated/full/apis/TipsApi.ts
  libs/src/sdk/api/generated/full/apis/TracksApi.ts
  libs/src/sdk/api/generated/full/apis/TransactionsApi.ts
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/FavoritesResponseFull.ts
  libs/src/sdk/api/generated/full/models/FollowersResponse.ts
  libs/src/sdk/api/generated/full/models/PremiumConditions.ts
  libs/src/sdk/api/generated/full/models/RelatedArtistResponse.ts
  libs/src/sdk/api/generated/full/models/TopGenreUsersResponse.ts
  libs/src/sdk/api/generated/full/models/TopUsersResponse.ts
  libs/src/sdk/api/generator/templates/typescript-fetch/apis.mustache
Labels: size/XXL

#5852 Fix datetime parsing in TN delister
  discovery-provider/src/tasks/update_delist_statuses.py
Labels: size/S

#5849 Fix album social feature migration and add fkey cascade
  discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql
  discovery-provider/src/tasks/index_nethermind.py
Labels: size/L

#5851 [PAY-1752] Backfill missing reward manager tx
  discovery-provider/ddl/migrations/0027_backfill_missing_reward_indexing.sql
Labels: size/XXL

#5856 [PAY-1750] Export MintName and DEFAULT_MINT from libs
  libs/src/AudiusLibs.ts
  libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/S

#5857 [PAY-1756] Create count endpoints for purchases, sales
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_usdc_purchases.py
  libs/src/sdk/api/generated/full/.openapi-generator/FILES
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
  libs/src/sdk/api/generated/full/models/Purchase.ts
  libs/src/sdk/api/generated/full/models/PurchasesCountResponse.ts
  libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#5858 quick fix: ensure my host is in healthy host list for rendezvous
  mediorum/server/placement.go
Labels: size/XS

#5860 Update healthz package-lock
  monitoring/healthz/package-lock.json
Labels: size/XS

#5861 Kill active queries when running repost/save migration
  discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql
Labels: size/S

#5863 [PAY-1759] Allow Sales endpoint to be sortable buy buyer name
  discovery-provider/integration_tests/queries/test_get_usdc_purchases.py
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_usdc_purchases.py
  discovery-provider/src/queries/query_helpers.py
  libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/M

#5855 [INF-438] Upgrade discovery plugins to node 18
  discovery-provider/plugins/notifications/package-lock.json
  discovery-provider/plugins/verified-uploads/Dockerfile
  discovery-provider/plugins/verified-uploads/package-lock.json
Labels: size/XS

#5859 [CON-837] Cleanup legacy and fix missing healthy hosts in redirect fallback
  mediorum/.initdb/init.sql
  mediorum/ddl/cid_lookup.sql
  mediorum/ddl/ddl.go
  mediorum/ddl/test/cid_lookup_test.sql
  mediorum/main.go
  mediorum/server/cuckoo.go
  mediorum/server/migrate_qm.go
  mediorum/server/monitor.go
  mediorum/server/repair.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/serve_legacy.go
  mediorum/server/serve_metrics.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
  monitoring/healthz/src/DiscoveryHealth.tsx
Labels: size/XL

#5866 Fix associated wallets indexing without is_current false
  discovery-provider/src/tasks/entity_manager/entities/user.py
  discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/M

#5867 [PAY-1760] Filter deleted collections from library endpoint
  discovery-provider/src/api/v1/users.py
  discovery-provider/src/queries/get_collection_library.py
Labels: size/M

#5869 Fix Purchases Endpoint
  dev-tools/commands/src/purchase-track.mjs
  discovery-provider/src/api/v1/users.py
Labels: size/XS

#5871 [proto-1145] add relay logs to vector container
  monitoring/vector/vector.toml
Labels: size/XS

#5862 [CON-839] When low on disk, delete over-replicated + don't accept blobs
  mediorum/server/monitor.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/M

#5872 Fix tastemaker mobile deep linking from push notif
  discovery-provider/plugins/notifications/src/__tests__/mappings/tastemaker.test.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
Labels: size/S

#5874 [CON-842] Makes repair.go more tolerant of temp issues
  mediorum/server/placement.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/serve_blob.go
Labels: size/M

#5853 Partition ops
  mediorum/crudr/crudr.go
  mediorum/crudr/op.go
  mediorum/ddl/ddl.go
  mediorum/server/db.go
  mediorum/server/serve_metrics.go
  mediorum/server/server.go
Labels: size/L

#5877 Explicitly lock tables before migration
  discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql
Labels: size/XS

#5884 Fix audius-compose comms setup
  dev-tools/compose/docker-compose.comms.yml
  dev-tools/compose/docker-compose.discovery.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/startup/initdb/00_schema.sql
  dev-tools/startup/initdb/01_changes.sql
  dev-tools/startup/initdb/02_dbs.sql
Labels: size/XXL

#5885 Add min time to partition scheduling
  mediorum/ddl/ddl.go
Labels: size/XS

#5886 Fix eth indexing log_index check
  discovery-provider/src/eth_indexing/event_scanner.py
Labels: size/XS

#5880 Pin @solana/spl-token version in identity
  identity-service/package.json
Labels: size/XS

#5887 Log celery worker pid
  discovery-provider/src/utils/helpers.py
Labels: size/XS
