Repository AudiusProject/apps, pull requests merged in 2023-10, with the labels that each got.

#6174 [PAY-1627] Fix stripe onramp layout on moweb
  packages/web/src/components/drawer/Drawer.module.css
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.module.css
  packages/web/src/components/track/LockedTrackDetailsTile.module.css
  packages/web/src/components/track/LockedTrackDetailsTile.tsx
Labels: size/S

#6180 PROTO-1299: scroll uploads for backfill
  mediorum/server/db.go
  mediorum/server/server.go
  mediorum/server/upload_client.go
Labels: size/M

#6192 multiple peer providers with fallback behavior
  mediorum/main.go
  mediorum/registrar/multi.go
Labels: size/M

#6186 [C-3139] Add create password page
  package-lock.json
  packages/mobile/e2e/signUp.test.ts
  packages/mobile/src/screens/sign-up-screen/SignUpRootScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-up-screen/types.ts
  packages/mobile/src/screens/sign-up-screen/useRoute.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/probers/cypress/support/commands.ts
  packages/web/src/common/utils/isMobileWeb.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/sign-up-page/SignUpRootPage.tsx
  packages/web/src/pages/sign-up-page/index.ts
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SignUpPage.tsx
  packages/web/src/utils/clientUtil.ts
Labels: size/L

#6194 [C-3168] Add missing submit type on button
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/fields/SelectGenreField.tsx
Labels: size/XS

#6195 FollowsYou badge uses trpc
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/trpc-server/src/loaders.ts
  packages/trpc-server/src/routers/me-router.ts
  packages/web/src/app.tsx
  packages/web/src/components/artist/ArtistCardCover.tsx
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistChipFollowers.tsx
  packages/web/src/components/artist/ArtistCover.tsx
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
  packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/services/trpc.ts
Labels: size/L

#6198 [PAY-1917] Add parens around seconds
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPreviewField.tsx
  packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
Labels: size/XS

#6199 Optimize trending requests
  discovery-provider/src/queries/get_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
Labels: size/S

#6193 [PROTO-1293] Reverse proxy to healthz from mediorum server
  mediorum/server/server.go
Labels: size/S

#6177 [PROTO-1297] Persist storage/db sizes in db + crudr
  mediorum/server/db.go
  mediorum/server/monitor.go
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
  monitoring/healthz/src/pages/Nodes.tsx
  monitoring/healthz/src/useServiceProviders.ts
Labels: size/L

#6205 [PAY-1939] Convert purchase content drawer to full screen variant
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Labels: size/L

#6204 tRPC build + push docker image
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/release.yml
  dev-tools/compose/docker-compose.discovery.yml
  dev-tools/compose/docker-compose.yml
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
Labels: size/M

#6200 [PAY-1936] Allow preview timestamps to be set for "unpreviewable" tracks
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
  packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx
  packages/web/src/pages/upload-page/components/PreviewButton.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/store/utils/processFiles.ts
Labels: size/L

#6207 Move notify triggers into ddl
  discovery-provider/ddl/functions/notify_on_row.sql
  discovery-provider/es-indexer/docker-compose.yml
  discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
  discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
  discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
  discovery-provider/es-indexer/src/indexers/UserIndexer.ts
  discovery-provider/es-indexer/src/listener.ts
  discovery-provider/es-indexer/src/main.ts
  discovery-provider/es-indexer/src/setup.ts
Labels: size/L

#6211 fix import order
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
Labels: size/XS

#6210 [PAY-1927] Cleanup redux state on purchase modal close
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/XS

#6209 [PAY-1861] Expose Pay Extra details in purchase/sales tables
  packages/common/src/api/purchases.ts
  packages/common/src/models/USDCTransactions.ts
  packages/common/src/utils/wallet.ts
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/summary-table/SummaryTable.module.css
  packages/web/src/components/summary-table/SummaryTable.tsx
  packages/web/src/components/summary-table/index.ts
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx
  packages/web/src/pages/purchases-and-sales/PurchasesTable.tsx
  packages/web/src/pages/purchases-and-sales/SalesTable.tsx
Labels: size/L

#6206 PROTO-1304: fix uploads bot
  discovery-provider/ddl/migrations/0000_schema_failable.sql
  discovery-provider/plugins/verified-uploads/src/db.js
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
  discovery-provider/plugins/verified-uploads/src/handlers/utils.js
Labels: size/L

#6191 Import harmony styles in web and embed
  packages/embed/src/index.css
  packages/harmony/.storybook/preview.ts
  packages/harmony/rollup.config.js
  packages/harmony/src/assets/fonts/avenir.css
  packages/harmony/src/assets/styles/fonts.css
  packages/harmony/src/assets/styles/main.css
  packages/harmony/src/index.ts
  packages/web/src/app.tsx
Labels: size/M

#6215 verified bot follow ons
  discovery-provider/ddl/functions/notify_on_row.sql
  discovery-provider/ddl/migrations/0000_schema_failable.sql
  discovery-provider/plugins/verified-uploads/publish-bot.sh
  discovery-provider/plugins/verified-uploads/src/db.js
  discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
Labels: size/M

#6216 Remove erroneous local-storage
  .gitignore
  identity-service/local-storage/%40audius%2Flibs%3Adiscovery-node-timestamp
Labels: size/XS

#6217 Revert "Import harmony styles in web and embed (#6191)"
  packages/embed/src/index.css
  packages/harmony/.storybook/preview.ts
  packages/harmony/rollup.config.js
  packages/harmony/src/assets/fonts/avenir.css
  packages/harmony/src/assets/styles/fonts.css
  packages/harmony/src/assets/styles/main.css
  packages/harmony/src/index.ts
  packages/web/src/app.tsx
Labels: size/M

#6219 Fix flaky follows on sign up, mobile C-2718
  packages/common/src/utils/sagaHelpers.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/utils/sagaHelpers.ts
Labels: size/XS

#6220 PAY-1507, PAY-1769: USDC Withdrawals: SOL Swapping for Uninitiated Accounts
  package-lock.json
  packages/common/src/services/audius-backend/solana.ts
  packages/identity-service/Dockerfile.dev
  packages/identity-service/package.json
  packages/identity-service/scripts/run-tests.sh
  packages/identity-service/src/app.js
  packages/identity-service/src/audiusLibsInstance.js
  packages/identity-service/src/index.ts
  packages/identity-service/src/routes/solana.js
  packages/identity-service/src/typed-routes/solana/InvalidRelayInstructionError.ts
  packages/identity-service/src/typed-routes/solana/layout-utils.ts
  packages/identity-service/src/typed-routes/solana/programs/associatedToken.ts
  packages/identity-service/src/typed-routes/solana/programs/claimable-tokens/constants.ts
  packages/identity-service/src/typed-routes/solana/programs/claimable-tokens/create.ts
  packages/identity-service/src/typed-routes/solana/programs/claimable-tokens/decode.ts
  packages/identity-service/src/typed-routes/solana/programs/claimable-tokens/index.ts
  packages/identity-service/src/typed-routes/solana/programs/claimable-tokens/transfer.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/constants.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/createSenderPublic.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/decode.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/deleteSenderPublic.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/evaluateAttestations.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/index.ts
  packages/identity-service/src/typed-routes/solana/programs/reward-manager/submitAttestation.ts
  packages/identity-service/src/typed-routes/solana/solanaRelay.ts
  packages/identity-service/src/typed-routes/solana/solanaRelayChecks.ts
  packages/identity-service/src/types/express/index.d.ts
  packages/identity-service/src/utils/relayHelpers.js
  packages/identity-service/src/utils/relayUtils.js
  packages/identity-service/src/utils/withdrawUSDCInstructionsHelpers.js
  packages/identity-service/test/index.ts
  packages/identity-service/test/lib/instructionMocks.js
  packages/identity-service/test/routes/solanaRelayTest.ts
  packages/identity-service/test/routes/solanaTest.js
  packages/libs/src/services/identity/IdentityService.ts
  packages/libs/src/services/solana/transactionHandler.ts
  packages/libs/src/services/solana/transfer.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/XXL

#6221 As/minor bot fixes
  discovery-provider/plugins/verified-uploads/package-lock.json
  discovery-provider/plugins/verified-uploads/package.json
  discovery-provider/plugins/verified-uploads/publish-bot.sh
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
Labels: size/S

#6140 PROTO-1287/1286: add relay reselection logic and relay to healthz
  discovery-provider/requirements.txt
  discovery-provider/src/conftest.py
  discovery-provider/src/queries/get_health.py
  discovery-provider/src/queries/get_health_unit_test.py
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/M

#6222 Fix several USDC purchase related bugs
  packages/common/src/store/purchase-content/slice.ts
  packages/mobile/src/components/core/ErrorText.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/BoxedTextField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPreviewField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPriceField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
Labels: size/L

#6223 Defer jimp.min.js
  packages/web/public/index.html
Labels: size/XS

#6229 [INF-501] Disable mobile prod builds on main
  .circleci/config.yml
  .circleci/src/workflows/mobile.yml
Labels: size/M

#6224 Fix coming soon tag
  packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/XS

#6227 FollowsYouChip uses trpc
  package-lock.json
  packages/common/package.json
  packages/common/src/services/index.ts
  packages/common/src/services/trpc-client.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/TrpcProvider.tsx
  packages/mobile/src/components/user/FollowsYouChip.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/trpc-server/package.json
  packages/trpc-server/src/db.ts
  packages/trpc-server/src/loaders.ts
  packages/trpc-server/src/routers/me-router.ts
  packages/web/package.json
  packages/web/src/app.tsx
  packages/web/src/components/user-badges/FollowsYouBadge.tsx
  packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx
Labels: size/L

#6203 [PAY-1875] Add Premium Tracks Explore Page - Part 2
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/premium-tracks/lineup/actions.ts
  packages/common/src/store/pages/premium-tracks/lineup/reducer.ts
  packages/common/src/store/pages/premium-tracks/lineup/selectors.ts
  packages/common/src/store/pages/premium-tracks/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/libs/src/sdk/api/generated/full/apis/SearchApi.ts
  packages/libs/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/PremiumTracksScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/lineup/sagas.d.ts
  packages/web/src/common/store/pages/premium-tracks/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/premium-tracks/sagas.ts
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/perspective-card/PerspectiveCard.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/explore-page/collections.ts
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/Section.module.css
  packages/web/src/pages/explore-page/components/desktop/Section.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/premium-tracks-page/PremiumTracksPage.tsx
  packages/web/src/pages/premium-tracks-page/desktop/PremiumTracksPageContent.tsx
  packages/web/src/pages/premium-tracks-page/mobile/PremiumTracksPageContent.module.css
  packages/web/src/pages/premium-tracks-page/mobile/PremiumTracksPageContent.tsx
  packages/web/src/store/sagas.ts
  packages/web/src/utils/route.ts
Labels: size/XL

#6230 Bump app version to trigger full app release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#6202 [PAY-1875] Add Premium Tracks Explore Page - Part 1
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_premium_tracks.py
  discovery-provider/src/queries/get_recommended_tracks.py
  discovery-provider/src/queries/get_trending.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_trending.py
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/premium-tracks/lineup/actions.ts
  packages/common/src/store/pages/premium-tracks/lineup/reducer.ts
  packages/common/src/store/pages/premium-tracks/lineup/selectors.ts
  packages/common/src/store/pages/premium-tracks/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/libs/src/sdk/api/generated/full/apis/SearchApi.ts
  packages/libs/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/ForYouTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/PremiumTracksScreen.tsx
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/index.ts
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/lineup/sagas.d.ts
  packages/web/src/common/store/pages/premium-tracks/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/premium-tracks/sagas.ts
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/perspective-card/PerspectiveCard.tsx
  packages/web/src/pages/App.js
  packages/web/src/pages/explore-page/collections.ts
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/Section.module.css
  packages/web/src/pages/explore-page/components/desktop/Section.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/premium-tracks-page/PremiumTracksPage.tsx
  packages/web/src/pages/premium-tracks-page/desktop/PremiumTracksPageContent.tsx
  packages/web/src/pages/premium-tracks-page/mobile/PremiumTracksPageContent.module.css
  packages/web/src/pages/premium-tracks-page/mobile/PremiumTracksPageContent.tsx
  packages/web/src/store/sagas.ts
  packages/web/src/utils/route.ts
Labels: size/XL

#6232 [PROTO-1239] Fix initting ClaimsManagerClient
  packages/libs/src/services/ethContracts/ClaimsManagerClient.ts
Labels: size/XS

#6196 [C-3165] Add finish-account sign-up page
  packages/mobile/e2e/fixtures/coverPhoto.json
  packages/mobile/e2e/fixtures/profilePicture.json
  packages/mobile/e2e/matchers.ts
  packages/mobile/e2e/signUp.test.ts
  packages/mobile/metro.config.js
  packages/mobile/package.json
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/fields/ImageField.tsx
  packages/mobile/src/components/fields/index.ts
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/sign-up-screen/SignUpRootScreen.tsx
  packages/mobile/src/screens/sign-up-screen/components/CoverPhotoField.tsx
  packages/mobile/src/screens/sign-up-screen/components/ProfilePictureField.tsx
  packages/mobile/src/screens/sign-up-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SignUpScreen.tsx
  packages/mobile/src/screens/sign-up-screen/types.ts
  packages/mobile/src/utils/launchImageLibrary.e2e.ts
  packages/mobile/src/utils/launchImageLibrary.ts
  packages/mobile/src/utils/launchSelectImageActionSheet.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/probers/cypress/fixtures/cover-photo.jpeg
  packages/probers/cypress/fixtures/profile-picture.jpeg
  packages/web/src/pages/App.js
  packages/web/src/pages/sign-up-page/SignUpRootPage.tsx
  packages/web/src/pages/sign-up-page/components/CoverPhotoField.module.css
  packages/web/src/pages/sign-up-page/components/CoverPhotoField.tsx
  packages/web/src/pages/sign-up-page/components/ImageField.module.css
  packages/web/src/pages/sign-up-page/components/ImageField.tsx
  packages/web/src/pages/sign-up-page/components/ProfilePictureField.module.css
  packages/web/src/pages/sign-up-page/components/ProfilePictureField.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenrePage.tsx
Labels: size/XL

#6236 Update harmony tsconfig to allow for css module classnames without errors
  package-lock.json
  packages/harmony/package.json
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/tsconfig.json
Labels: size/S

#6238 Always pass test-discovery-api
  .circleci/src/jobs/@discovery-jobs.yml
Labels: size/S

#6243 [PAY-1944] Bring back AudioBreakdown
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XS

#6244 [PROTO-1317] Fix sitemap counts
  discovery-provider/integration_tests/queries/test_get_sitemap.py
  discovery-provider/src/app.py
  discovery-provider/src/queries/get_sitemap.py
Labels: size/M

#6240 [C-3176] Update harmony css variables and import harmony styles into web and embed
  packages/embed/src/index.css
  packages/harmony/.storybook/preview.ts
  packages/harmony/rollup.config.js
  packages/harmony/src/assets/fonts/avenir.css
  packages/harmony/src/assets/styles/border-radius.css
  packages/harmony/src/assets/styles/colors.css
  packages/harmony/src/assets/styles/fonts.css
  packages/harmony/src/assets/styles/main.css
  packages/harmony/src/assets/styles/shadows.css
  packages/harmony/src/assets/styles/spacing.css
  packages/harmony/src/assets/styles/tokens.css
  packages/harmony/src/components/input/SelectablePill/SelectablePill.module.css
  packages/harmony/src/components/typography/Text/Text.tsx
  packages/harmony/src/components/typography/Text/typography.module.css
  packages/harmony/src/index.ts
  packages/harmony/tsconfig.json
  packages/web/src/app.tsx
Labels: size/XL

#6234 [PAY-1956] Add pay extra column to purchases and sales csv
  discovery-provider/src/queries/download_csv.py
Labels: size/XS

#6248 Remove broken ethgasstation.info usage, let default gas be set
  packages/identity-service/src/relay/ethTxRelay.js
  packages/identity-service/src/routes/ethRelay.js
  packages/libs/initScripts/manageProdRelayerWallets.js
Labels: size/L

#6235 Add request time in json to server logs
  discovery-provider/nginx_conf/log_json.lua
  discovery-provider/nginx_conf/nginx.conf
  discovery-provider/scripts/prod-server.sh
Labels: size/M

#6250 Remove anon v1 full trending tracks cache
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/get_trending.py
Labels: size/S

#6251 Remove dead code
  packages/libs/.dockerignore
  packages/libs/.gitignore
  packages/libs/initScripts/helpers/claim.js
  packages/libs/initScripts/helpers/distributeTokens.js
  packages/libs/initScripts/helpers/spRegistration.js
  packages/libs/initScripts/helpers/utils.js
  packages/libs/initScripts/helpers/version.js
  packages/libs/initScripts/local.js
  packages/libs/initScripts/mainnet.js
  packages/libs/initScripts/manageProdRelayerWallets.js
  packages/libs/package.json
  packages/libs/scripts/addCIDToIpldBlacklist.js
  packages/libs/scripts/test.sh
  packages/libs/tests/governanceTest.js
  packages/libs/tests/helpers.js
  packages/libs/tests/stakingTest.js
Labels: size/XXL

#6212 [PAY-1945] Add column for amount in user_challenges table + backfill
  discovery-provider/ddl/migrations/0034_add_challenge_amount.sql
  discovery-provider/integration_tests/challenges/test_audio_matching_challenges.py
  discovery-provider/integration_tests/challenges/test_challenges.py
  discovery-provider/integration_tests/challenges/test_create_new_challenges.py
  discovery-provider/integration_tests/queries/test_get_challenges.py
  discovery-provider/integration_tests/queries/test_undisbursed_challenges.py
  discovery-provider/src/challenges/challenge.py
  discovery-provider/src/challenges/challenges.dev.json
  discovery-provider/src/challenges/challenges.json
  discovery-provider/src/challenges/challenges.stage.json
  discovery-provider/src/models/rewards/user_challenge.py
  discovery-provider/src/queries/get_challenges.py
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#6252 rm unneeded error log
  packages/libs/src/services/web3Manager/Web3Manager.ts
Labels: size/XS

#6247 Fix identity push
  .circleci/src/jobs/push-docker-image.yml
  dev-tools/audius-compose
Labels: size/S

#6256 Rename access log file
  discovery-provider/nginx_conf/nginx.conf
Labels: size/XS

#6226 Remove partition migration again
  dev-tools/compose/docker-compose.storagev2.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  mediorum/crudr/crudr.go
  mediorum/crudr/setup_test_db.go
  mediorum/ddl/ddl.go
  mediorum/server/db.go
  mediorum/server/test_main_test.go
Labels: size/L

#6257 bump DN dockerfile python3 dependency to 3.11.6
  discovery-provider/Dockerfile
Labels: size/XS

#6259 Remove sdk autopublish
  .circleci/src/workflows/sdk.yml
Labels: size/S

#6242 [C-3133] Port HarmonyButton to harmony package
  packages/harmony/src/assets/styles/animations.css
  packages/harmony/src/assets/styles/colors.css
  packages/harmony/src/assets/styles/spacing.css
  packages/harmony/src/components/button/BaseButton.module.css
  packages/harmony/src/components/button/BaseButton.tsx
  packages/harmony/src/components/button/Button.module.css
  packages/harmony/src/components/button/Button.stories.tsx
  packages/harmony/src/components/button/Button.tsx
  packages/harmony/src/components/button/PlainButton.module.css
  packages/harmony/src/components/button/PlainButton.stories.tsx
  packages/harmony/src/components/button/PlainButton.tsx
  packages/harmony/src/components/button/index.ts
  packages/harmony/src/components/button/types.ts
  packages/harmony/src/components/input/SelectablePill/SelectablePill.module.css
  packages/harmony/src/hooks/useMediaQueryListener.ts
  packages/harmony/src/storybook/components/ColorPalette/ColorPalette.module.css
  packages/harmony/src/storybook/components/ColorSwatch/ColorSwatch.module.css
  packages/harmony/src/types/colors.ts
  packages/harmony/src/types/styles.ts
  packages/harmony/src/utils/styles.ts
Labels: size/XL

#6254 [C-3181, C-3182] Fix collection loading, drawer closing, feature flag perf
  packages/common/src/hooks/useFeatureFlag.ts
  packages/mobile/metro.config.js
  packages/mobile/package.json
  packages/mobile/src/components/drawer/NativeDrawer.tsx
Labels: size/M

#6241 [C-3174] Add select genre page to sign up
  package-lock.json
  packages/mobile/e2e/matchers.ts
  packages/mobile/e2e/signUp.test.ts
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/screens/sign-up-screen/SignUpRootScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SignUpScreen.tsx
  packages/mobile/src/screens/sign-up-screen/types.ts
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/store/store.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/selectors.js
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/pages/App.js
  packages/web/src/pages/App.module.css
  packages/web/src/pages/sign-on/SignOn.tsx
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-up-page/SignUpRootPage.tsx
  packages/web/src/pages/sign-up-page/components/GenrePill.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenrePage.tsx
  packages/web/src/store/types.ts
Labels: size/XL

#6255 Wire up UI for $AUDIO matching challenges
  packages/common/src/models/AudioRewards.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/utils/challenges.ts
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/hooks/useIsAudioMatchingChallengesEnabled.ts
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#6261 [PAY-1975] Fix withdrawal email decimals
  discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcWithdrawal.ts
Labels: size/S

#6260 [PAY-1960] Clean up withdrawals decimal places
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Labels: size/M

#6218 [PROTO-1320] Run CI jobs without GCP
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/gcp-checkout.yml
  .circleci/src/commands/gcp-run.yml
  .circleci/src/jobs/build-gcp-image.yml
  .circleci/src/jobs/push-docker-image.yml
  .circleci/src/jobs/test-audius-cmd.yml
  .circleci/src/jobs/test.yml
  .circleci/src/workflows/contracts.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/eth-contracts.yml
  .circleci/src/workflows/gcp.yml
  .circleci/src/workflows/identity.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/sdk.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/requirements.txt
  dev-tools/setup.sh
Labels: size/L

#6253 trpc: social modal shows list of users who did X
  package-lock.json
  packages/trpc-server/package.json
  packages/trpc-server/src/db.ts
  packages/trpc-server/src/index.ts
  packages/trpc-server/src/routers/me-router.ts
  packages/trpc-server/src/routers/user-router.ts
  packages/web/package.json
  packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx
Labels: size/L

#6262 Backfill challenges amount migration
  discovery-provider/ddl/migrations/0035_backfill_challenge_amount.sql
Labels: size/M

#6237 [PAY-1974] Fix explore premium tracks bugs
  discovery-provider/integration_tests/tasks/test_index_trending_notification.py
  discovery-provider/integration_tests/tasks/test_trending_playlist_notifications.py
  discovery-provider/src/api/v1/tracks.py
  discovery-provider/src/queries/generate_unpopulated_trending_tracks.py
  discovery-provider/src/queries/get_premium_tracks.py
  discovery-provider/src/queries/get_recommended_tracks.py
  discovery-provider/src/queries/get_trending.py
  discovery-provider/src/queries/get_trending_ids.py
  discovery-provider/src/queries/get_trending_playlists.py
  discovery-provider/src/queries/get_trending_tracks.py
  discovery-provider/src/queries/get_underground_trending.py
  discovery-provider/src/tasks/cache_trending_playlists.py
  discovery-provider/src/tasks/calculate_trending_challenges.py
  discovery-provider/src/tasks/index_trending.py
  packages/web/src/pages/premium-tracks-page/PremiumTracksPage.tsx
Labels: size/XL

#6246 [C-3175] Replace instances of HarmonySelectablePill in web with harmony component
  packages/harmony/package.json
  packages/harmony/tsconfig.json
  packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx
  packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Labels: size/M

#6265 More web+mobile UI for $AUDIO matching challenges
  packages/common/src/utils/challenges.ts
  packages/mobile/src/assets/images/emojis/cart.png
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/assets/fonts/emojis/cart.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.module.css
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/L

#6266 Make createAssociatedTokenAccount idempotent for root wallet
  packages/web/src/services/solana/WithdrawUSDC.ts
Labels: size/XS

#6245 Fix offline collections not loading if started offline C-3187
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
Labels: size/M

#6263 fix package-lock.json
  package-lock.json
  packages/web/package.json
Labels: size/XS

#6267 Add react-query to mobile
  package-lock.json
  packages/mobile/package.json
Labels: size/XS

#6269 Revert "Revert "[PLAT-259] Upgrade EthereumTx version (#3606)" (#3682)"
  package-lock.json
  packages/identity-service/package.json
  packages/identity-service/src/relay/ethTxRelay.js
  packages/identity-service/src/relay/txRelay.js
Labels: size/S

#6271 Fix gasPrice bug
  packages/identity-service/src/relay/ethTxRelay.js
Labels: size/XS

#6276 Dispatch $AUDIO matching challenges in non-prod envs
  discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#6258 [⚠️] Remove /error page, try again should just refresh
  packages/web/src/app.tsx
  packages/web/src/common/store/pages/signon/errorSagas.ts
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/something-wrong/SomethingWrong.module.css
  packages/web/src/pages/something-wrong/SomethingWrong.tsx
  packages/web/src/store/configureStore.ts
  packages/web/src/store/errors/actions.ts
  packages/web/src/store/errors/reducers.ts
  packages/web/src/store/errors/sagas.ts
  packages/web/src/store/errors/selectors.ts
  packages/web/src/utils/route.ts
  packages/web/src/utils/zIndex.ts
Labels: size/L

#6280 Fix lint
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/upload/sagas.js
Labels: size/S

#6249 [PAY-1837] Adds more robust error handling to purchase/sales/withdrawals pages
  packages/common/src/api/purchases.ts
  packages/common/src/api/user.ts
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useBooleanOnce.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/hooks/useErrorPageOnFailedStatus.ts
  packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
  packages/web/src/pages/purchases-and-sales/WithdrawalsPage.tsx
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
  packages/web/src/store/errors/actions.ts
Labels: size/L

#6274 [PAY-1951][PAY-1966] Improve the Stripe drawer experience on mobile
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/NativeDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampDrawer.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampEmbed.tsx
Labels: size/L

#6282 [C-3199] Fix Remix Settings Not Saving (Web)
  packages/web/src/pages/upload-page/fields/RemixSettingsField/types.ts
Labels: size/XS

#6264 [C-3184] Add select-artists page to sign-up
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/topArtists.ts
  packages/common/src/api/user.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/audius-query/utils.ts
  packages/mobile/e2e/matchers.ts
  packages/mobile/e2e/signUp.test.ts
  packages/mobile/package.json
  packages/mobile/src/app/App.tsx
  packages/mobile/src/screens/sign-up-screen/components/ArtistTile.tsx
  packages/mobile/src/screens/sign-up-screen/screens/SelectArtistsScreen.tsx
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/web/src/app.tsx
  packages/web/src/pages/sign-up-page/SignUpRootPage.tsx
  packages/web/src/pages/sign-up-page/pages/AppCtaPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#6283 [C-3197] Fixes being unable to reopen Upload modals on mobile
  packages/mobile/src/components/core/ContextualMenu.tsx
Labels: size/XS

#6279 [C-3189] Adding periods + cleanup unused message
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/XS

#6284 Fix verified plugin check to account for new users
  discovery-provider/plugins/verified-uploads/src/handlers/users.js
Labels: size/XS

#6285 Use user_challenges amount in undisbursed endpoint
  discovery-provider/src/queries/get_undisbursed_challenges.py
Labels: size/XS

#6275 Pin activesupport to fix ios deploy
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/ios/Gemfile
  packages/mobile/ios/Gemfile.lock
  packages/mobile/ios/Podfile.lock
Labels: size/L

#6288 Support better run protocol commands
  package.json
  packages/compose/package.json
  turbo.json
Labels: size/XS

#6273 Use neutral loading color in healthz
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/M

#6289 [PAY-1892] Implement weekly pool limit
  packages/discovery-provider/ddl/migrations/0036_add_challenge_disbursement_cap.sql
  packages/discovery-provider/integration_tests/queries/test_get_attestation.py
  packages/discovery-provider/integration_tests/queries/test_get_disbursed_challenges_amount.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/create_new_challenges.py
  packages/discovery-provider/src/models/rewards/challenge.py
  packages/discovery-provider/src/models/rewards/challenge_disbursement.py
  packages/discovery-provider/src/queries/get_attestation.py
  packages/discovery-provider/src/queries/get_disbursed_challenges_amount.py
Labels: size/L

#6290 Use user_challenge amount in DN attestation
  packages/discovery-provider/src/queries/get_attestation.py
Labels: size/XS

#6292 Make npm run protocol work without up
  packages/compose/package.json
  packages/compose/start.sh
Labels: size/XS

#6294 Update package-lock to update ethereumjs-tx
  package-lock.json
Labels: size/XS

#6295 Updates to make aao work with local stack
  dev-tools/audius-compose
  dev-tools/startup/initdb/02_dbs.sql
  packages/web/.env/.env.dev
Labels: size/XS

#6296 [PAY-1891] Add challenge info endpoint
  packages/discovery-provider/integration_tests/queries/test_get_attestation.py
  packages/discovery-provider/integration_tests/queries/test_get_disbursed_challenges_amount.py
  packages/discovery-provider/src/api/v1/challenges.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/challenges.py
  packages/discovery-provider/src/models/rewards/challenge_disbursement.py
  packages/discovery-provider/src/queries/get_attestation.py
  packages/discovery-provider/src/queries/get_disbursed_challenges_amount.py
Labels: size/L

#6297 Debug ganache flakiness with verbose logging
  eth-contracts/scripts/setup-predeployed-ganache.sh
Labels: size/XS

#6299 Improve local dev mediorum cpu use, enable hot reload
  dev-tools/compose/docker-compose.storagev2.yml
  dev-tools/startup/register.py
  dev-tools/startup/storagev2.sh
  mediorum/Dockerfile
  mediorum/Dockerfile.dev
  mediorum/server/repair.go
Labels: size/M

#6272 [PAY-1923] Navigate to track screen in the background on successful purchase
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
Labels: size/M

#6300 Disable usdc bank split in dev mode
  packages/web/src/common/store/upload/sagaHelpers.ts
Labels: size/S

#6293 [INF-498] Leverage turborepo cache in docker builds in CI
  .circleci/src/workflows/contracts.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/eth-contracts.yml
  .circleci/src/workflows/identity.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/sdk.yml
  dev-tools/compose/docker-compose.identity.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.test.yml
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/identity-service/Dockerfile.prod
  packages/libs/Dockerfile
Labels: size/M

#6268 Fix empty state for offline tracks C-3188
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
Labels: size/S

#6185 Add loading and error states for AUDIO balance; fix AudioBreakdown modal on web C-3164 C-3162
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/ui/transaction-details/types.ts
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/slice.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/components/nav/desktop/NavAudio.module.css
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/pages/audio-rewards-page/Tiles.module.css
  packages/web/src/pages/audio-rewards-page/Tiles.tsx
  packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletActionsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#6301 [INF-398] Improve identity typecheck and run with --transpile-only
  .circleci/config.yml
  .circleci/src/jobs/@identity-jobs.yml
  .circleci/src/workflows/identity.yml
  package-lock.json
  packages/identity-service/.hooks/pre-push.json
  packages/identity-service/package.json
  packages/identity-service/src/notifications/index.js
  packages/identity-service/src/rateLimiter.js
  packages/identity-service/src/routes/push_notifications.js
  packages/identity-service/src/utils/antiAbuse.js
  turbo.json
Labels: size/L

#6270 Protocol dashboard in audius-compose
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/@protocol-dashboard-jobs.yml
  .circleci/src/workflows/protocol-dashboard.yml
  dev-tools/compose/docker-compose.protocol-dashboard.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/compose/nginx_ingress.conf
  protocol-dashboard/.circleci/config.yml
  protocol-dashboard/.env.stage
  protocol-dashboard/.gitignore
  protocol-dashboard/Dockerfile
  protocol-dashboard/README.md
  protocol-dashboard/configure-envs/configureEnv.cjs
  protocol-dashboard/configure-envs/configureLocalEnv.js
  protocol-dashboard/index.html
  protocol-dashboard/package.json
  protocol-dashboard/scripts/advanceBlocks.js
  protocol-dashboard/src/App.tsx
  protocol-dashboard/src/components/Header/Header.tsx
  protocol-dashboard/src/hooks/useRerouteLegacy.ts
  protocol-dashboard/src/services/Audius/setup.ts
  protocol-dashboard/vite.config.ts
Labels: size/XL

#6308 Fix lint on main
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XS

#6307 Push dashboard image in CI
  .circleci/src/workflows/protocol-dashboard.yml
  protocol-dashboard/Dockerfile
  protocol-dashboard/configure-envs/configureEnv.cjs
  protocol-dashboard/configure-envs/configureLocalEnv.js
  protocol-dashboard/package.json
  protocol-dashboard/scripts/configureEnv.cjs
  protocol-dashboard/scripts/updateBuild.cjs
Labels: size/L

#6287 [PAY-1965] Use authenticated callback for premium purchases
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/track/PremiumTrackSection.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/hooks/useAuthenticatedCallback.ts
  packages/web/src/hooks/useRequiresAccount.ts
Labels: size/L

#6298 [C-3201] Audit harmony button styles
  packages/harmony/src/assets/styles/animations.css
  packages/harmony/src/assets/styles/spacing.css
  packages/harmony/src/components/button/BaseButton.module.css
  packages/harmony/src/components/button/Button.module.css
  packages/harmony/src/components/button/Button.stories.tsx
  packages/harmony/src/components/button/Button.tsx
  packages/harmony/src/components/button/types.ts
Labels: size/L

#6309 Move dashboard docker push job to discovery workflow
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/protocol-dashboard.yml
Labels: size/S

#6312 Actually fix follow artists step in sign up flow C-3206
  packages/mobile/src/screens/signon/FirstFollows.tsx
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-on/SignOnProvider.tsx
Labels: size/S

#6313 Register multiple DNs on local stack
  dev-tools/compose/nginx_ingress.conf
  packages/discovery-provider/scripts/register.py
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  solana-programs/scripts/deploy.sh
Labels: size/M

#6304 [C-3156] Add Box and Flex components to harmony
  package-lock.json
  packages/harmony/.babelrc.json
  packages/harmony/.storybook/main.ts
  packages/harmony/package.json
  packages/harmony/rollup.config.js
  packages/harmony/src/assets/styles/shadows.css
  packages/harmony/src/assets/styles/spacing.css
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/input/SelectablePill/SelectablePill.stories.tsx
  packages/harmony/src/components/layout/Box/Box.stories.tsx
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/components/layout/Box/index.ts
  packages/harmony/src/components/layout/Box/types.ts
  packages/harmony/src/components/layout/Divider/Divider.stories.tsx
  packages/harmony/src/components/layout/Divider/Divider.tsx
  packages/harmony/src/components/layout/Divider/index.ts
  packages/harmony/src/components/layout/Divider/types.ts
  packages/harmony/src/components/layout/Flex/Flex.stories.tsx
  packages/harmony/src/components/layout/Flex/Flex.tsx
  packages/harmony/src/components/layout/Flex/index.ts
  packages/harmony/src/components/layout/Flex/types.ts
  packages/harmony/src/components/layout/index.ts
  packages/harmony/src/components/typography/Text/Text.stories.tsx
  packages/harmony/src/storybook/colors.ts
  packages/harmony/src/storybook/components/ColorPalette/ColorPalette.module.css
  packages/harmony/src/storybook/components/ColorPalette/ColorPalette.tsx
  packages/harmony/src/storybook/components/ColorSwatch/ColorSwatch.module.css
  packages/harmony/src/storybook/components/ColorSwatch/ColorSwatch.tsx
  packages/harmony/src/styles/theme.ts
  packages/harmony/src/styles/types.ts
Labels: size/XL

#6320 Revert "[INF-498] Leverage turborepo cache in docker builds in CI (#6…
  .circleci/src/workflows/contracts.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/eth-contracts.yml
  .circleci/src/workflows/identity.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/sdk.yml
  dev-tools/compose/docker-compose.identity.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.test.yml
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/identity-service/Dockerfile.prod
  packages/libs/Dockerfile
Labels: size/M

#6316 [PAY-2003] Fix challenge disbursement with variable amounts
  packages/common/src/models/AudioRewards.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/challenges/selectors/optimistic-challenges.ts
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/store/pages/audio-rewards/types.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Labels: size/M

#6324 Wormhole: Receive SPL AUDIO in background process, respond early
  packages/identity-service/src/relay/ethTxRelay.js
  packages/identity-service/src/routes/wormhole.js
Labels: size/L

#6317 Fix audio balance error C-3207 C-3208
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/slice.ts
  packages/common/src/utils/typeUtils.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx
  packages/web/src/components/nav/desktop/NavAudio.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/pages/audio-rewards-page/Tiles.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletActionsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#6321 Make weekly cap migration idempotent
  packages/discovery-provider/ddl/migrations/0036_add_challenge_disbursement_cap.sql
Labels: size/XS

#6323 [C-3198] Improve ContextualMenu submit pattern
  packages/web/src/components/data-entry/ContextualMenu.tsx
Labels: size/XS

#6322 [C-3211] Remove legacy upload
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/ios/Podfile.lock
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/probers/cypress/e2e/uploadTrackLegacy.cy.ts
  packages/web/src/components/data-entry/InlineFormTile.js
  packages/web/src/components/data-entry/InlineFormTile.module.css
  packages/web/src/pages/App.js
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/UploadPageLegacy.js
  packages/web/src/pages/upload-page/UploadPageNew.module.css
  packages/web/src/pages/upload-page/UploadPageNew.tsx
  packages/web/src/pages/upload-page/components/AddTracksNotification.js
  packages/web/src/pages/upload-page/components/AddTracksNotification.module.css
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
  packages/web/src/pages/upload-page/components/EditPage.js
  packages/web/src/pages/upload-page/components/EditPage.module.css
  packages/web/src/pages/upload-page/components/FinishPage.js
  packages/web/src/pages/upload-page/components/FinishPage.module.css
  packages/web/src/pages/upload-page/components/PreviewButton.tsx
  packages/web/src/pages/upload-page/components/SelectPage.js
  packages/web/src/pages/upload-page/components/SelectPage.module.css
  packages/web/src/pages/upload-page/components/ShareBanner.module.css
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/pages/upload-page/components/ShareBannerNew.tsx
  packages/web/src/pages/upload-page/components/TracksPreview.js
  packages/web/src/pages/upload-page/components/TracksPreview.module.css
  packages/web/src/pages/upload-page/components/TracksPreview.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/index.ts
  packages/web/src/pages/upload-page/pages/FinishPage.module.css
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.module.css
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
Labels: size/XXL

#6332 Fix feature-flag override when signed-out
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
Labels: size/S

#6333 Remove redundant jimp fetches
  packages/web/craco.config.ts
  packages/web/public/index.html
  packages/web/src/services/WebWorker.js
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/workers/averageRgb.worker.js
  packages/web/src/workers/dominantColor.worker.js
  packages/web/src/workers/generatePlaylistArtwork.worker.js
  packages/web/src/workers/gifPreview.worker.js
  packages/web/src/workers/resizeImage.worker.js
  packages/web/src/workers/utils/jimp.min.workerscript
Labels: size/M

#6319 [PROTO-1326] Add more delist reasons
  mediorum/ddl/add_delist_reasons.sql
  mediorum/ddl/ddl.go
  packages/discovery-provider/ddl/migrations/0037_add_delist_reasons.sql
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/src/models/delisting/track_delist_status.py
  packages/sql-ts/res/content-node.ts
  packages/sql-ts/res/discovery-node.ts
  packages/trpc-server/src/db-tables.ts
Labels: size/L

#6330 [C-2887] Improve favorites track list ui
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/M

#6326 [PAY-1886] Challenge cooldown: created_at migration + backend updates
  packages/common/src/models/AudioRewards.ts
  packages/discovery-provider/ddl/migrations/0037_add_challenge_created_at_col.sql
  packages/discovery-provider/integration_tests/challenges/test_challenges.py
  packages/discovery-provider/src/challenges/challenge.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/create_new_challenges.py
  packages/discovery-provider/src/models/rewards/challenge.py
  packages/discovery-provider/src/models/rewards/user_challenge.py
  packages/discovery-provider/src/queries/get_attestation.py
  packages/libs/src/api/Rewards.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
Labels: size/M

#6337 Remove COOLDOWN_CHALLENGE_IDS in get_attestation.py
  packages/discovery-provider/src/queries/get_attestation.py
Labels: size/XS

#6338 Simplify claiming variable-amount challenges
  packages/common/src/models/AudioRewards.ts
  packages/common/src/store/challenges/selectors/optimistic-challenges.ts
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/store/pages/audio-rewards/types.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/M

#6334 Create @audius/spl package
  .circleci/config.yml
  package-lock.json
  package.json
  packages/compose/package.json
  packages/identity-service/package.json
  packages/identity-service/src/typed-routes/solana/solanaRelayChecks.ts
  packages/identity-service/test/routes/solanaRelayTest.ts
  packages/spl/.eslintrc
  packages/spl/README.md
  packages/spl/package.json
  packages/spl/src/claimable-tokens/constants.ts
  packages/spl/src/claimable-tokens/create.ts
  packages/spl/src/claimable-tokens/decode.ts
  packages/spl/src/claimable-tokens/index.ts
  packages/spl/src/claimable-tokens/transfer.ts
  packages/spl/src/index.ts
  packages/spl/src/layout-utils.ts
  packages/spl/src/reward-manager/constants.ts
  packages/spl/src/reward-manager/createSenderPublic.ts
  packages/spl/src/reward-manager/decode.ts
  packages/spl/src/reward-manager/deleteSenderPublic.ts
  packages/spl/src/reward-manager/evaluateAttestations.ts
  packages/spl/src/reward-manager/index.ts
  packages/spl/src/reward-manager/submitAttestation.ts
  packages/spl/tsconfig.all.json
  packages/spl/tsconfig.base.json
  packages/spl/tsconfig.cjs.json
  packages/spl/tsconfig.esm.json
  packages/spl/tsconfig.json
  packages/spl/tsconfig.root.json
Labels: size/L

#6339 Revert "Remove redundant jimp fetches (#6333)"
  packages/web/craco.config.ts
  packages/web/public/index.html
  packages/web/src/services/WebWorker.js
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/workers/averageRgb.worker.js
  packages/web/src/workers/dominantColor.worker.js
  packages/web/src/workers/generatePlaylistArtwork.worker.js
  packages/web/src/workers/gifPreview.worker.js
  packages/web/src/workers/resizeImage.worker.js
  packages/web/src/workers/utils/jimp.min.workerscript
Labels: size/M

#6341 [PAY-1996] Only attempt usdc recovery is user is logged in
  packages/common/src/store/buy-usdc/sagas.ts
Labels: size/XS

#6327 Restore missing track CIDs with cid_data
  packages/discovery-provider/ddl/migrations/0037_restore_missing_track_cid.sql
Labels: size/S

#6342 Use more supported migration for mediorum workaround
  mediorum/ddl/add_delist_reasons.sql
  packages/discovery-provider/ddl/migrations/0037_add_delist_reasons.sql
Labels: size/M

#6343 [PAY-2007] Ignore paid extra amount for matching challenges
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/XS

#6340 Add test for varying aggregate challenge amounts
  packages/discovery-provider/integration_tests/challenges/test_challenges.py
Labels: size/S

#6311 [C-3183] Replace instances of HarmonyButton with harmony/button in web
  package-lock.json
  packages/harmony/.storybook/preview.ts
  packages/harmony/package.json
  packages/harmony/rollup.config.js
  packages/harmony/src/assets/animations/loadingSpinner.json
  packages/harmony/src/components/button/BaseButton.tsx
  packages/harmony/src/components/button/Button.module.css
  packages/harmony/src/components/button/Button.stories.tsx
  packages/harmony/src/components/button/Button.tsx
  packages/harmony/src/components/button/PlainButton.tsx
  packages/harmony/src/components/button/types.ts
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/loading-spinner/LoadingSpinner.module.css
  packages/harmony/src/components/loading-spinner/LoadingSpinner.tsx
  packages/harmony/src/index.ts
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx
  packages/web/src/components/navigation-prompt/NavigationPrompt.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/PremiumConditionsPill.tsx
  packages/web/src/components/twitter-share-button/TwitterShareButton.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx
  packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx
  packages/web/src/pages/purchases-and-sales/SalesPage.tsx
  packages/web/src/pages/purchases-and-sales/WithdrawalsPage.tsx
  packages/web/src/pages/purchases-and-sales/components/NoTransactionsContent.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenrePage.tsx
  packages/web/src/pages/sign-up-page/pages/SignUpPage.tsx
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
  packages/web/src/pages/upload-page/components/TracksPreview.tsx
  packages/web/src/pages/upload-page/fields/ModalField.tsx
  packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx
Labels: size/XL

#6328 [C-3185] Fix web e2e tests
  packages/probers/cypress/e2e/signIn.cy.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/probers/cypress/e2e/smoke/upload.cy.ts
  packages/probers/cypress/e2e/uilts.ts
  packages/probers/cypress/e2e/uploadTrack.cy.ts
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-up-page/pages/SignUpPage.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
Labels: size/L

#6310 [C-1002] Add reset-password mobile screen
  packages/common/src/api/account.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/mobile/src/components/enter-password/EnterPassword.tsx
  packages/mobile/src/components/enter-password/index.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/change-password-screen/ChangePasswordScreen.tsx
  packages/mobile/src/screens/change-password-screen/ConfirmCredentials.tsx
  packages/mobile/src/screens/change-password-screen/index.ts
  packages/mobile/src/screens/reset-password-screen/ResetPasswordScreen.tsx
  packages/mobile/src/screens/reset-password-screen/index.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/settings-screen/index.ts
Labels: size/L

#6325 Poll for wormhole balance change
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/mobile/src/screens/tip-artist-screen/SendTipStatusText.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/pages/audio-rewards-page/components/MigrationModalBody.tsx
Labels: size/M

#6306 Fix verified check because of identity time drift
  packages/discovery-provider/plugins/verified-uploads/src/handlers/users.js
Labels: size/M

#6345 [C-3213] Add deprecated label to HarmonyButton
  packages/stems/src/components/Button/Button.tsx
  packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
Labels: size/XS

#6277 Dedicated queue for ACDC indexing
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_nethermind.py
Labels: size/S

#6349 [PROTO-1329] Disable DLC
  .circleci/src/jobs/push-docker-image.yml
  .circleci/src/jobs/test-audius-cmd.yml
  .circleci/src/jobs/test.yml
Labels: size/XS

#6352 Tune celery worker concurrency
  packages/discovery-provider/scripts/start.sh
Labels: size/XS

#6348 [PAY-1993] Order challenges by claimable amt
  packages/common/src/utils/challenges.ts
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/S

#6350 [PROTO-1349] Continuous deployment for healthz
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/workflows/healthz.yml
  .circleci/src/workflows/release.yml
Labels: size/S

#6356 Remove gcp-cleanup job
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/gcp-auth.yml
  .circleci/src/jobs/gcp-cleanup.yml
  .circleci/src/workflows/gcp-cleanup.yml
Labels: size/M

#6347 Delay foundation deploy by 1hr
  .circleci/config.yml
Labels: size/XS

#6281 PROTO-1335: relay upload delay
  packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  packages/web/src/common/store/upload/sagas.js
Labels: size/M

#6360 PROTO-1261: trending rewards plugin QOL improvements
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/server.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts
Labels: size/M

#6365 Revert "Revert "[INF-498] Leverage turborepo cache in docker builds i…
  .circleci/src/workflows/contracts.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/eth-contracts.yml
  .circleci/src/workflows/identity.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/sdk.yml
  dev-tools/compose/docker-compose.identity.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.test.yml
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/identity-service/Dockerfile.prod
  packages/libs/Dockerfile
Labels: size/M

#6364 [PAY-1982] Add AudioMatchSection in premium purchase modal/drawer
  packages/mobile/src/components/premium-track-purchase-drawer/AudioMatchSection.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.module.css
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.module.css
  packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.tsx
Labels: size/L

#6367 [PAY-1954] Fix display of $0 existing balance on web purchase form
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
Labels: size/XS

#6366 [PAY-1978] Read pay extra presets from remote config
  packages/common/src/hooks/purchaseContent/constants.ts
  packages/common/src/hooks/purchaseContent/index.ts
  packages/common/src/hooks/purchaseContent/usePayExtraPresets.ts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/purchaseContent/utils.ts
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/utils/stringUtils.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts
Labels: size/L

#6353 [C-3216] Add react-slot, implement asChild for drag/drop
  package-lock.json
  packages/web/package.json
  packages/web/src/components/dragndrop/Draggable.tsx
  packages/web/src/components/dragndrop/Droppable.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
Labels: size/S

#6359 [C-3101] Fix table action hover state
  packages/web/src/components/table/components/TableRepostButton.module.css
  packages/web/src/components/table/components/TableRepostButton.tsx
Labels: size/M
