Repository AudiusProject/apps, pull requests merged in 2024-04, with the labels that each got.

#7983 [C-4087] Fix library not loading
  packages/libs/src/sdk/middleware/addRequestSignatureMiddleware.ts
Labels: size/XS

#7981 [C-4224] Fix mobile audio match reward date and collectibles date
  packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/common/src/utils/dayjs.ts
  packages/common/src/utils/timeUtil.test.ts
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
Labels: size/M

#7985 [C-4225] Add alt text to new StaticImages
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.jsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/components/track/GiantArtwork.tsx
  packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#7980 Lint changes for discovery-provider
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/challenges/challenge_event_bus.py
  packages/discovery-provider/src/queries/get_collection_library.py
  packages/discovery-provider/src/queries/get_feed.py
  packages/discovery-provider/src/queries/get_undisbursed_challenges.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/generate_trending.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/utils/redis_metrics.py
  packages/discovery-provider/src/utils/varint.py
Labels: size/L

#7984 Add textTransform prop to harmony Text
  packages/harmony/src/components/text/Text/Text.tsx
  packages/harmony/src/components/text/Text/types.ts
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
Labels: size/XS

#7986 [PAY-2651] Fix nft video thumbnail
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
Labels: size/S

#7990 Revert "ONC-54: indexer concurrency (#7933)"
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/monitors/monitoring_queue.py
  packages/discovery-provider/src/tasks/aggregates/__init__.py
  packages/discovery-provider/src/tasks/cache_current_nodes.py
  packages/discovery-provider/src/tasks/cache_entity_counts.py
  packages/discovery-provider/src/tasks/cache_trending_playlists.py
  packages/discovery-provider/src/tasks/cache_user_balance.py
  packages/discovery-provider/src/tasks/index_aggregate_monthly_plays.py
  packages/discovery-provider/src/tasks/index_challenges.py
  packages/discovery-provider/src/tasks/index_eth.py
  packages/discovery-provider/src/tasks/index_hourly_play_counts.py
  packages/discovery-provider/src/tasks/index_latest_block.py
  packages/discovery-provider/src/tasks/index_metrics.py
  packages/discovery-provider/src/tasks/index_oracles.py
  packages/discovery-provider/src/tasks/index_profile_challenge_backfill.py
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/index_solana_plays.py
  packages/discovery-provider/src/tasks/index_spl_token.py
  packages/discovery-provider/src/tasks/index_trending.py
  packages/discovery-provider/src/tasks/prune_plays.py
  packages/discovery-provider/src/tasks/publish_scheduled_releases.py
  packages/discovery-provider/src/tasks/update_aggregates.py
  packages/discovery-provider/src/tasks/update_clique_signers.py
  packages/discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
  packages/discovery-provider/src/tasks/vacuum_db.py
Labels: size/XL

#7992 [ONC-68] Fix stream hex signature and delisting by downgrading hexbytes
  packages/discovery-provider/requirements.txt
Labels: size/XS

#7993 Add timezone back
  packages/common/src/utils/dayjs.ts
Labels: size/XS

#7996 Misc improvements to saliou's nft PR
  packages/common/src/models/Collectible.ts
  packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/mobile/src/components/collectible-details-drawer/CollectibleMedia.tsx
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/collectibles/ethCollectibleHelpers.ts
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/workers/gifPreview.worker.js
Labels: size/L

#7997 Lower default celery worker concurrency
  packages/discovery-provider/scripts/start.sh
Labels: size/XS

#7995 Fix miscellaneous nft issues
  packages/common/src/assets/img/Placeholder2x.png
  packages/common/src/assets/index.ts
  packages/common/src/models/Collectible.ts
  packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/SolanaCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts
  packages/common/src/utils/dayjs.ts
  packages/mobile/src/assets/images/Placeholder@2x.png
  packages/mobile/src/components/collectible-details-drawer/CollectibleMedia.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/collectibles/ethCollectibleHelpers.ts
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/workers/gifPreview.worker.js
Labels: size/XL

#7999 [C-4235] Fix robots.txt on ssr worker
  .circleci/src/commands/@web-commands.yml
Labels: size/XS

#8000 [C-4233] Turn off client side hydration for crawlers
  packages/web/src/ssr/+onRenderClient.tsx
  packages/web/src/ssr/+passToClient.tsx
  packages/web/src/ssr/index/+route.ts
  packages/web/src/ssr/util.ts
Labels: size/M

#8003 Block spam nfts
  packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts
  packages/common/src/utils/dayjs.ts
Labels: size/S

#7994 [ONC-67] Update aggregates counts with more straightforward logic
  packages/discovery-provider/ddl/functions/handle_track.sql
  packages/discovery-provider/integration_tests/models/test_aggregate_counters.py
  packages/discovery-provider/integration_tests/notifications/test_track.py
  packages/discovery-provider/integration_tests/utils.py
Labels: size/L

#8001 [PAY-2650] Add DetailsTileNoAccess section to collection screen
  packages/common/src/hooks/useGatedContent.ts
  packages/common/src/utils/contentTypeUtils.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#8002 Fix collectible animated webp and progressive loading
  packages/common/src/assets/img/Placeholder2x.png
  packages/common/src/assets/img/imageCollectiblePlaceholder2x.webp
  packages/common/src/assets/index.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/screens/NFTCollectionsScreen.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/collectibles/components/CollectibleRow.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedDescription.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx
Labels: size/L

#8007 Fix useHarmonyField hook dependencies
  packages/common/src/hooks/useHarmonyField.ts
Labels: size/S

#7998 [PROTO-1745] Refactor DDEX parsing: release profiles, Singles, Fuga
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/e2e_test/fixtures/batch/ern382/1_CPD1.zip
  packages/ddex/ingester/e2e_test/fixtures/batch/ern382/2_CPD2.zip
  packages/ddex/ingester/e2e_test/fixtures/batch/ern382/CPD2.zip
  packages/ddex/ingester/go.mod
  packages/ddex/ingester/go.sum
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
Labels: size/XXL

#8005 Add '--maxsockets 1' flag to make ddex build more reliable
  packages/ddex/publisher/Dockerfile
  packages/ddex/webapp/Dockerfile
Labels: size/XS

#8011 Fix batch metadata parsing bug and add Fuga test
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/e2e_test/fixtures/batch/fuga/20240305090206405/8718857546047/8718857546047.xml
  packages/ddex/ingester/e2e_test/fixtures/batch/fuga/20240305090206405/8718857546047/resources/8718857546047_T1_0_SoundRecording_001_001.flac
  packages/ddex/ingester/e2e_test/fixtures/batch/fuga/20240305090206405/8718857546047/resources/8718857546047_T2_Image.jpg
  packages/ddex/ingester/e2e_test/fixtures/batch/fuga/20240305090206405/BatchComplete_20240305090206405.xml
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
Labels: size/XXL

#8008 Fix mobile collectible svg+xml and video display
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
Labels: size/L

#7961 ⚠️ Fix and re-enable a subset of tests (PAY-2600, PAY-2601, PAY-2605, PAY-2606, PAY-2607, PAY-2608, PAY-2609, PAY-2610, PAY-2611)
  .circleci/src/jobs/@web-jobs.yml
  package-lock.json
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/queue/slice.ts
  packages/common/src/store/queue/types.ts
  packages/web/package.json
  packages/web/src/app/web-player/WebPlayer.test.tsx
  packages/web/src/common/store/cache/store.test.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/player/store.test.js
  packages/web/src/common/store/player/store.test.ts
  packages/web/src/common/store/queue/store.test.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/collections/store.test.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/tracks/store.test.js
  packages/web/src/common/store/social/tracks/store.test.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
  packages/web/src/hooks/useImageSize.test.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/services/audio-player/AudioPlayer.test.ts
  packages/web/src/services/remote-config/__mocks__/remote-config-instance.ts
  packages/web/src/utils/route/collectionRouteParser.test.js
  packages/web/src/utils/route/collectionRouteParser.test.ts
  packages/web/src/utils/route/collectionRouteParser.ts
  packages/web/vite.config.ts
Labels: size/XXL

#8012 Add scheduled release schema type
  packages/libs/src/api/Track.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
Labels: size/XS

#8013 Priority listens
  packages/identity-service/src/solana-client.js
Labels: size/XS

#8014 Correct unlisted scheduled releases
  packages/discovery-provider/ddl/migrations/0065_fix_unlisted_scheduled_releases.sql
Labels: size/M

#8015 Fix mobile AI-generated track header
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#7989 [INF-593] [INF-644] Clean up npm i output
  dev-tools/setup.sh
  package.json
  scripts/patch-package.sh
  scripts/postinstall.sh
  scripts/preinstall.sh
Labels: size/L

#7988 Bump mobile version to 1.1.93 for release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8023 Slow down solana tx retries
  packages/identity-service/src/solana-client.js
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#8006 [PAY-2569] Mobile premium album purchase flow
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/utils/contentTypeUtils.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/premium-content-purchase-drawer/AudioMatchSection.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PayExtraFormSection.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSummaryTable.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseUnavailable.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/hooks/usePurchaseContentFormState.ts
  packages/mobile/src/components/premium-content-purchase-drawer/hooks/usePurchaseSummaryValues.ts
  packages/mobile/src/components/premium-content-purchase-drawer/index.ts
  packages/mobile/src/components/premium-track-purchase-drawer/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/L

#8027 [C-4060] Remove Open in Audius App drawer on web mobile for crawlers
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/S

#8019 [C-4083] Fix native password perf
  packages/mobile/src/components/fields/HarmonyTextField.tsx
  packages/mobile/src/components/fields/PasswordField.tsx
Labels: size/XS

#8021 [C-4329] Fix ai-attribution-details styles
  packages/harmony/src/components/text/Text/Text.tsx
  packages/mobile/src/components/details-tile/DetailsTileAiAttribution.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
Labels: size/M

#8017 Convert DetailsTile mobile component to Harmony
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Labels: size/L

#8024 Use multiple solana rpc connections
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/identity-service/src/routes/healthCheck.js
  packages/identity-service/src/routes/trackListens.js
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/services/solana/transactionHandler.ts
  packages/libs/src/services/wormhole/Wormhole.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/M

#7991 [PAY-2654] Use @audius/fetch-nft for all nft fetching logic
  package-lock.json
  packages/common/package.json
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/models/Collectible.ts
  packages/common/src/services/collectibles-provider/CollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/SolanaCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/common/src/services/collectibles-provider/index.ts
  packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts
  packages/common/src/services/collectibles-provider/types.ts
  packages/common/src/services/index.ts
  packages/common/src/store/storeContext.ts
  packages/embed/.env.dev
  packages/embed/.env.prod
  packages/embed/.env.stage
  packages/embed/package.json
  packages/embed/src/util/BedtimeClient.js
  packages/embed/vite.config.js
  packages/mobile/package.json
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSummaryTable.tsx
  packages/mobile/src/store/storeContext.ts
  packages/web/package.json
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/polyfills.ts
  packages/web/src/store/storeContext.ts
Labels: size/XXL

#8028 [DVRL-23] Flesh out distributors page
  docs/docs/distributors/introduction/overview.mdx
  docs/docs/distributors/run-a-server/run-a-ddex-server.mdx
  docs/docs/distributors/self-serve/overview.mdx
  docs/docs/distributors/self-serve/run-a-ddex-server.mdx
  docs/docs/distributors/specification/ern3.mdx
  docs/docs/distributors/specification/ern4.mdx
  docs/docs/distributors/specification/overview.mdx
  docs/i18n/en/code.json
  docs/i18n/en/docusaurus-plugin-content-blog/options.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/sidebars.js
  docs/src/css/custom.css
Labels: size/XXL

#8031 Cache content nodes immediately at startup
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/cache_current_nodes.py
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
Labels: size/S

#8033 [DVRL-24] Keep top tab highlighted
  docs/docs/distributors/self-serve/run-a-ddex-server.mdx
  docs/docusaurus.config.js
Labels: size/S

#7970 [C-4058] Refactor InputV2 to harmony TextInput
  packages/web/src/components/data-entry/InputV2.module.css
  packages/web/src/components/data-entry/InputV2.tsx
  packages/web/src/components/form-fields/PriceField.tsx
  packages/web/src/components/form-fields/TextField.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.module.css
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/pages/upload-page/fields/download-availability/DownloadPriceField.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Labels: size/L

#8035 [C-4241] Upgrade dapp-store-cli to latest
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/S

#8037 [C-4038] Fix missing playlist image
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
Labels: size/M

#8030 RPC fallback on error
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#8042 RTL test setup + SSR store ref refactor
  packages/common/src/utils/typeUtils.ts
  packages/web/src/app/ReduxProvider.tsx
  packages/web/src/store/configureStore.ts
  packages/web/src/test/redux-state.ts
  packages/web/src/test/test-utils.tsx
  packages/web/src/test/vitest-setup.ts
Labels: size/L

#8032 [PAY-2675] New Purchase/Sale details modal UI
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/components/link/ExternalTextLink.tsx
  packages/web/src/components/link/index.ts
  packages/web/src/components/track/DynamicTrackArtwork.module.css
  packages/web/src/components/track/DynamicTrackArtwork.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackLink.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/styles.module.css
  packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/pages/profile-page/components/SocialLink.tsx
  packages/web/src/pages/profile-page/components/mobile/SocialLink.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedDescription.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/L

#8044 Fix sale modal link
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Labels: size/XS

#8043 Hotfix tracks not getting artwork
  packages/web/src/common/store/upload/sagas.ts
Labels: size/XS

#8047 Fix tracks uploaded without cover art
  packages/discovery-provider/ddl/migrations/0066_hotfix_blank_track_images.sql
Labels: size/S

#8038 [PROTO-1753] Make ddex publisher+web work with refactored parser
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/models/publishedReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
Labels: size/L

#8045 Use vite preview for playwright tests
  .circleci/src/commands/@web-commands.yml
  .circleci/src/workflows/web.yml
  packages/web/package.json
  packages/web/playwright.config.ts
Labels: size/S

#8050 [PROTO-1752] Delete backfill_cid_data celery task
  packages/discovery-provider/integration_tests/tasks/test_backfill_cid_data.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/backfill_cid_data.py
  packages/discovery-provider/src/tasks/cache_current_nodes.py
Labels: size/L

#8046 [C-4243] Fix theming on first render
  packages/harmony/src/foundations/theme/ThemeProvider.tsx
  packages/web/src/app/AppProviders.tsx
  packages/web/src/app/ReduxProvider.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/pages/requires-update/RequiresUpdate.tsx
  packages/web/src/store/application/ui/theme/sagas.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/test/test-utils.tsx
  packages/web/src/utils/theme/theme.ts
Labels: size/L

#8040 Notify author on CI success and failure of main branch
  .circleci/config.yml
  .circleci/scripts/generate-slack-template.sh
  .circleci/scripts/wait-for-pipeline.sh
  .circleci/slack-templates/pipeline-status-template.jq
  .circleci/src/workflows/web.yml
Labels: size/L

#8055 Fix failing E2E upload tests
  packages/web/e2e/test.ts
  packages/web/e2e/uploadCollection.test.ts
  packages/web/e2e/uploadTrack.test.ts
Labels: size/M

#8018 [DVRL-23] - DDEX documentation
  docs/.vscode/spellright.dict
  docs/README.md
  docs/docs/distributors/introduction/overview.mdx
  docs/docs/distributors/self-serve/overview.mdx
  docs/docs/distributors/self-serve/run-a-ddex-server.mdx
  docs/docs/distributors/specification/deal-types.mdx
  docs/docs/distributors/specification/metadata.mdx
  docs/docs/distributors/specification/overview.mdx
  docs/docusaurus.config.js
  docs/i18n/en/code.json
  docs/i18n/en/docusaurus-plugin-content-blog/options.json
  docs/i18n/en/docusaurus-plugin-content-docs/current.json
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/sidebars.js
  docs/src/css/custom.css
Labels: size/XXL

#8056 Skip Mac staging desktop build
  .circleci/src/workflows/web.yml
Labels: size/S

#8057 Revert fetch-nft changes to unblock CI
  package-lock.json
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/models/Collectible.ts
  packages/common/src/services/collectibles-provider/CollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/SolanaCollectiblesProvider.ts
  packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts
  packages/common/src/services/collectibles-provider/index.ts
  packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts
  packages/common/src/services/collectibles-provider/types.ts
  packages/common/src/services/index.ts
  packages/common/src/store/storeContext.ts
  packages/embed/.env.dev
  packages/embed/.env.prod
  packages/embed/.env.stage
  packages/embed/package.json
  packages/embed/src/util/BedtimeClient.js
  packages/embed/vite.config.js
  packages/mobile/package.json
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSummaryTable.tsx
  packages/mobile/src/store/storeContext.ts
  packages/web/package.json
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/polyfills.ts
  packages/web/src/store/storeContext.ts
Labels: size/XXL

#8052 [PROTO-1760] Ensure UPC and ISWC are persisted top-level
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/publisher/src/services/publisherService.ts
  packages/discovery-provider/src/api/v1/models/playlists.py
  packages/discovery-provider/src/schemas/playlist_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/S

#8058 [PAY-2680] Update audio page wallet tile
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/common/src/utils/typeUtils.ts
  packages/harmony/src/assets/icons/CoinbasePay.svg
  packages/harmony/src/icons/Logos.stories.mdx
  packages/harmony/src/icons/logos.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.module.css
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/mobile-connect-wallets-drawer/MobileConnectWalletsDrawer.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletsTable.tsx
Labels: size/L

#8060 [PAY-2579] Change tx handler logs back to warn
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#8061 [PAY-2343] Only dispatch audio matching challenges for valid purchases
  packages/discovery-provider/integration_tests/challenges/test_audio_matching_challenges.py
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/M

#8010 [Protocol Dashboard] Implement Wallet Connect on Protocol Dashboard [C-3951]
  package.json
  packages/libs/src/WebAudiusLibs.ts
  packages/libs/src/services/ethWeb3Manager/EthWeb3Manager.ts
  packages/web/src/pages/oauth-login-page/messages.ts
  protocol-dashboard/.env.prod
  protocol-dashboard/.env.stage
  protocol-dashboard/package.json
  protocol-dashboard/src/App.tsx
  protocol-dashboard/src/components/AppBar/AppBar.module.css
  protocol-dashboard/src/components/AppBar/AppBar.tsx
  protocol-dashboard/src/components/ConfirmTransactionModal/ConfirmTransactionModal.tsx
  protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.module.css
  protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.tsx
  protocol-dashboard/src/components/ConnectMetaMaskModal/MisconfiguredModal.module.css
  protocol-dashboard/src/components/ConnectMetaMaskModal/MisconfiguredModal.tsx
  protocol-dashboard/src/components/ConnectMetaMaskModal/index.tsx
  protocol-dashboard/src/components/ModifyServiceModal/ModifyServiceModal.module.css
  protocol-dashboard/src/components/ModifyServiceModal/ModifyServiceModal.tsx
  protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.tsx
  protocol-dashboard/src/services/Audius/AudiusClient.ts
  protocol-dashboard/src/services/Audius/helpers.ts
  protocol-dashboard/src/services/Audius/setup.ts
  protocol-dashboard/src/store/account/hooks.ts
  protocol-dashboard/src/store/cache/user/graph/hooks.ts
  protocol-dashboard/src/store/cache/user/hooks.ts
  protocol-dashboard/src/utils/eth.ts
  protocol-dashboard/src/utils/sharedMessages.ts
  protocol-dashboard/src/utils/switchNetwork.ts
Labels: size/XL

#8063 [C-4253] Fix stats test line-height
  packages/web/src/components/track/desktop/stats/Stats.module.css
  packages/web/src/components/track/desktop/stats/StatsText.module.css
Labels: size/XS

#8025 [PAY-2667] Add nft improvements
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/collectibles/selectors.ts
  packages/common/src/store/ui/buy-audio/slice.ts
  packages/common/src/utils/typeUtils.ts
  packages/harmony/src/assets/icons/CoinbasePay.svg
  packages/harmony/src/icons/Logos.stories.mdx
  packages/harmony/src/icons/logos.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ListSelectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/NFTCollectionsScreen.tsx
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.module.css
  packages/web/src/components/buy-audio-modal/components/AmountInputPage.tsx
  packages/web/src/components/mobile-connect-wallets-drawer/MobileConnectWalletsDrawer.tsx
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletsTable.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedFields.module.css
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx
Labels: size/XL

#8059 [C-4001] Add interacive paper variant
  packages/harmony/src/components/layout/Paper/Paper.mdx
  packages/harmony/src/components/layout/Paper/Paper.stories.tsx
  packages/harmony/src/components/layout/Paper/Paper.tsx
  packages/harmony/src/components/layout/Paper/types.ts
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.stories.tsx
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
  packages/mobile/src/harmony-native/components/layout/Paper/types.ts
  packages/mobile/src/harmony-native/foundations/shadows/shadows.ts
Labels: size/L

#8066 [C-4256] Fix misaligned artist badge in premium content unlock section
  packages/web/src/components/track/GiantTrackTile.module.css
Labels: size/XS

#8049 chore: Refactor useAccessAndRemixSettings & add unit test
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSummaryTable.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/L

#8068 [C-4258] Fix text input end adornment position
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/XS

#8069 [C-4257] Fix web-dist-win jobs
  .circleci/src/jobs/@web-jobs.yml
Labels: size/XS

#8070 increase solana RPC reselect freq
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#8065 [PAY-2682] Write new TrackAddedToPurchasedAlbum notification to table
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/ddl/functions/handle_playlist.sql
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/trackAddedToPurchasedAlbum.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/L

#8072 First pass of claim all modal
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#8048 [PAY-2668] Purchase/sale details modals album support
  packages/common/src/hooks/useImageSize.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/web/src/components/usdc-purchase-details-modal/USDCPurchaseDetailsModal.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumPurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumSaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/ContentLink.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackLink.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackPurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/styles.module.css
  packages/web/src/components/usdc-purchase-details-modal/components/types.ts
  packages/web/src/hooks/useCollectionCoverArt.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTable.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
Labels: size/L

#8079 Reduce border on playlist tile track list
  packages/web/src/components/track/desktop/PlaylistTile.tsx
Labels: size/XS

#8081 Remove ComputeBudget from Withdrawals
  packages/common/src/services/audius-backend/solana.ts
Labels: size/S

#8077 [PROTO-1754] Fix DDEX albums being editable, fields not persisting
  packages/discovery-provider/src/schemas/playlist_schema.json
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/L

#8078 Standardize ddex envs to work with audius-docker-compose better
  packages/ddex/.env.dev
  packages/ddex/.env.stage
  packages/ddex/publisher/Dockerfile
  packages/ddex/publisher/package.json
  packages/ddex/publisher/src/index.ts
  packages/ddex/publisher/src/services/sdkService.ts
  packages/ddex/webapp/Dockerfile
  packages/ddex/webapp/Dockerfile.fast
  packages/ddex/webapp/client/.env.dev
  packages/ddex/webapp/client/.env.stage.local
  packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx
  packages/ddex/webapp/server/package.json
  packages/ddex/webapp/server/src/index.ts
  packages/ddex/webapp/server/src/services/sdkService.ts
Labels: size/M

#8071 [PAY-2585] Premium album edit feature
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/L

#8084 [PAY-2685] Render TrackAddedToPurchasedAlbumNotification on mobile
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrackAddedToPurchasedAlbumNotification.tsx
Labels: size/M

#8073 [PAY-2684] Fix wrap on audio wallet actions
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Labels: size/M

#8087 [PAY-2677] Retries for Discovery Solana Relay
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/logging.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/tsconfig.json
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.dev
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
  packages/web/src/services/audius-sdk/solana.ts
Labels: size/L

#8083 [C-4226] Remove lossless toggle in upload flow and download section on track
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
Labels: size/M

#8026 PROTO-1711: acdc tip notification reactions
  packages/commands/src/index.mjs
  packages/commands/src/tip-reaction.mjs
  packages/commands/src/utils.mjs
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_tip_reactions.py
  packages/discovery-provider/src/queries/get_tips.py
  packages/discovery-provider/src/tasks/entity_manager/entities/tip_reactions.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/users/UsersApi.test.ts
  packages/libs/src/sdk/api/users/UsersApi.ts
  packages/libs/src/sdk/api/users/types.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/libs/src/sdk/utils/reactionsMap.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
Labels: size/XL

#8092 [C-4252] Update search screen navigation to clear search on mobile
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#8089 [DVRL-25] - Using Wallet Connect on the Protocol Dashboard
  docs/.vscode/spellright.dict
  docs/docs/node-operator/overview.mdx
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/registration/multi-sig-wallet.mdx
  docs/docs/node-operator/setup/registration/registration.mdx
  docs/docs/node-operator/staking/delegate.mdx
  docs/docs/node-operator/staking/stake.mdx
  docs/docs/reference/protocol-dashboard/link-profile.mdx
  docs/static/img/dashboard-account/audius-profile-linked.png
  docs/static/img/dashboard-account/authorize-app.png
  docs/static/img/dashboard-account/connect-audius-metamask.png
  docs/static/img/dashboard-account/connect-audius-profile-button.png
  docs/static/img/dashboard-account/connect-metamask-button.png
  docs/static/img/dashboard-account/connect-profile-modal.png
  docs/static/img/dashboard-account/metamask-account-picker.png
  docs/static/img/dashboard-account/metamask-linked.png
  docs/static/img/dashboard-account/not-linked.png
  docs/static/img/dashboard-account/wallet-connect-button.png
  docs/static/img/dashboard-account/wallet-connected.png
  docs/static/img/dashboard-account/wallet-selector.png
  docs/static/img/delegate/delegate-modal.png
  docs/static/img/delegate/node-operator-tab.png
  docs/static/img/delegate/wallet-connect-button.png
  docs/static/img/delegate/wallet-selector.png
  docs/static/img/register-node/register-node-modal.png
  docs/static/img/register-node/register-service-button.png
  docs/static/img/register-node/wallet-connect-button.png
  docs/static/img/register-node/wallet-selector.png
Labels: size/XL

#8095 Disable play e2e test
  packages/web/e2e/play.test.ts
Labels: size/XS

#8094 [C-4268] Fix player sagas prev functionality for premium track previews
  packages/web/src/common/store/player/sagas.ts
Labels: size/S

#8098 remove unused import
  packages/libs/src/sdk/api/users/UsersApi.ts
Labels: size/XS

#8062 ddex: limit publisher to 3 retries
  packages/ddex/publisher/src/services/publisherService.ts
Labels: size/XS

#8096 Fix missing isTrack dependency (lint change)
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
Labels: size/XS

#8082 [PAY-2687] E2E tests for premium album edits
  packages/web/e2e/editCollection.test.ts
  packages/web/src/components/usdc-purchase-details-modal/USDCPurchaseDetailsModal.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumSaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
Labels: size/M

#8102 require handle_lc in users query
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
Labels: size/XS

#8090 [PAY-2689] Send tips via SDK (behind feature flag)
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/libs/src/sdk/services/AntiAbuseOracle/AntiAbuseOracle.ts
  packages/spl/src/layout-utils.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/L

#8097 [PROTO-1515] Hide modification buttons for ddex tracks and albums
  packages/common/src/models/Collection.ts
  packages/common/src/models/Search.ts
  packages/ddex/README.md
  packages/ddex/ingester/README.md
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/actions-tab/ActionsTab.jsx
  packages/web/src/components/card/desktop/Card.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.jsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#8106 Fix preview start and end point parsing
  packages/ddex/ingester/parser/ern38x.go
Labels: size/S

#8101 ACDC tip notifs: encode hash id
  packages/discovery-provider/src/queries/reactions.py
  packages/web/src/common/store/ui/reactions/sagas.ts
Labels: size/S

#8103 Use docker image tags to control versioning
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/commands/@docker-prune.yml
  .circleci/src/jobs/deploy-foundation-nodes.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
  .circleci/src/jobs/push-docker-image.yml
  .circleci/src/jobs/release-audius-docker-compose.yml
Labels: size/L

#8053 Parse DDEX deals (redo after refactor)
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/workflows/ddex-e2e.yml
  .circleci/src/workflows/ddex-webapp.yml
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
Labels: size/L

#8109 Restore common deps in CI
  .circleci/src/jobs/@common-jobs.yml
Labels: size/XS

#8112 Add more instructions for external users
  docs/docs/distributors/specification/deal-types.mdx
  packages/ddex/README.md
Labels: size/M

#8114 Lint fixes for main
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
  packages/web/src/components/actions-tab/ActionsTab.jsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
Labels: size/M

#8115 Fix docs nit
  docs/docs/distributors/specification/deal-types.mdx
Labels: size/XS

#8117 [C-4278] Fix native search collections
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/S

#8009 Make collectibles grid virtualized
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/L

#8123 Fix metro support for @metaplex-foundation/umi
  packages/mobile/metro.config.js
Labels: size/XS

#8118 PROTO-1768: add trending challenges to index_nethermind queue for priority
  packages/discovery-provider/src/tasks/index_nethermind.py
Labels: size/XS

#8124 Fix collection screen types
  packages/common/src/models/Search.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/S

#8121 Fix nft undefined bug
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/XS

#8100 [PAY-2661] Add collection card
  packages/common/src/models/Collection.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/harmony/src/components/icon.ts
  packages/web/src/components/collection/CollectionCard.test.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/collection/CollectionImage.tsx
Labels: size/L

#8113 [PAY-2697] Add purchase button to album DM unfurl
  packages/web/src/components/track/GatedConditionsPill.module.css
  packages/web/src/components/track/GatedConditionsPill.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/stats/Stats.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#8127 Fix ddex webapp client lint
  packages/ddex/webapp/server/.eslintrc.cjs
  packages/ddex/webapp/server/src/app.ts
  packages/ddex/webapp/server/src/controllers/collectionController.ts
  packages/ddex/webapp/server/src/index.ts
  packages/ddex/webapp/server/src/routers/collectionRouters.ts
  packages/ddex/webapp/server/src/routers/index.ts
  packages/ddex/webapp/server/src/routers/uploadRouter.ts
  packages/ddex/webapp/server/src/services/dbService.ts
  packages/ddex/webapp/server/src/services/s3.ts
  packages/ddex/webapp/server/src/services/sdkService.ts
  packages/ddex/webapp/server/src/trpc.ts
  packages/ddex/webapp/server/src/userSchema.ts
Labels: size/L

#8129 Fix premium album uploads
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#8125 Make ddex run locally again with hot reloading
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.yml
  packages/ddex/.env.dev
  packages/ddex/package-lock.json
  packages/ddex/publisher/Dockerfile
  packages/ddex/publisher/package.json
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/webapp/Dockerfile
  packages/ddex/webapp/Dockerfile.fast
  packages/ddex/webapp/server/package.json
Labels: size/M

#8088 Support coinflow relay on client
  packages/common/src/services/audius-backend/solana.ts
  packages/identity-service/src/typed-routes/solana/solanaRelay.ts
  packages/libs/src/services/identity/IdentityService.ts
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#8132 [PROTO-1764] Pipe vector logs for ddex containers
  monitoring/vector/start.sh
  monitoring/vector/vector.toml
Labels: size/XS

#8105 Convert tier badges back to png from svg [C-1337]
  packages/harmony/src/assets/icons/Verified.svg
  packages/web/src/assets/img/tokenBadgeBronze128@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze16@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze24@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze32@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze48@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze64@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze8@2x.webp
  packages/web/src/assets/img/tokenBadgeBronze96@2x.webp
  packages/web/src/assets/img/tokenBadgeGold128@2x.webp
  packages/web/src/assets/img/tokenBadgeGold16@2x.webp
  packages/web/src/assets/img/tokenBadgeGold24@2x.webp
  packages/web/src/assets/img/tokenBadgeGold32@2x.webp
  packages/web/src/assets/img/tokenBadgeGold48@2x.webp
  packages/web/src/assets/img/tokenBadgeGold64@2x.webp
  packages/web/src/assets/img/tokenBadgeGold8@2x.webp
  packages/web/src/assets/img/tokenBadgeGold96@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum128@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum16@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum24@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum32@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum48@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum64@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum8@2x.webp
  packages/web/src/assets/img/tokenBadgePlatinum96@2x.webp
  packages/web/src/assets/img/tokenBadgePurple128@2x.webp
  packages/web/src/assets/img/tokenBadgePurple16@2x.webp
  packages/web/src/assets/img/tokenBadgePurple24@2x.webp
  packages/web/src/assets/img/tokenBadgePurple32@2x.webp
  packages/web/src/assets/img/tokenBadgePurple48@2x.webp
  packages/web/src/assets/img/tokenBadgePurple64@2x.webp
  packages/web/src/assets/img/tokenBadgePurple8@2x.webp
  packages/web/src/assets/img/tokenBadgePurple96@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver128@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver16@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver24@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver32@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver48@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver64@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver8@2x.webp
  packages/web/src/assets/img/tokenBadgeSilver96@2x.webp
  packages/web/src/components/audio-balance-pill/AUDIOBalancePill.tsx
  packages/web/src/components/buy-audio-modal/BuyAudioModal.module.css
  packages/web/src/components/buy-audio-modal/BuyAudioModal.tsx
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/user-badges/ProfilePageBadge.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/L

#8111 [PAY-2617] Buy button for tracklist in albums
  packages/common/src/store/ui/modals/premium-content-purchase-modal/index.ts
  packages/web/src/components/table/components/TablePlayButton.module.css
  packages/web/src/components/table/components/TablePlayButton.tsx
  packages/web/src/components/tracks-table/TracksTable.module.css
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#8131 [C-4279] Don't log not found errors to sentry
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/errors.ts
  packages/common/src/audius-query/index.ts
Labels: size/S

#8130 [INF-690] Delete sdk release job
  .circleci/src/jobs/release-audius-sdk.yml
  .circleci/src/workflows/sdk.yml
  packages/libs/scripts/release.sh
Labels: size/L

#8128 Only bump web and mobile versions on release branch
  .circleci/config.yml
Labels: size/XS

#8122 skip relay rate limit on dev
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
Labels: size/XS

#8120 PAY-2563: add solana relay health check
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/health/health.ts
Labels: size/S

#8137 Upgrade native version to 1.1.94
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8138 fix lint
  packages/discovery-provider/setup.py
Labels: size/S

#8134 [PAY-2698] Add purchase button do album DMs (mobile)
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/L

#8116 Filter out stems and unlisted tracks from verified uploads bot
  packages/discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
Labels: size/XS

#8104 [PROTO-1726] Start simple entrypoint for distro
  package-lock.json
  package.json
  packages/ddex/README.md
  packages/ddex/entrypoint/.eslintrc.cjs
  packages/ddex/entrypoint/.gitignore
  packages/ddex/entrypoint/README.md
  packages/ddex/entrypoint/gitignore
  packages/ddex/entrypoint/index.html
  packages/ddex/entrypoint/package.json
  packages/ddex/entrypoint/public/favicon.ico
  packages/ddex/entrypoint/src/App.css
  packages/ddex/entrypoint/src/App.tsx
  packages/ddex/entrypoint/src/emotion.d.ts
  packages/ddex/entrypoint/src/main.tsx
  packages/ddex/entrypoint/src/vite-env.d.ts
  packages/ddex/entrypoint/tsconfig.json
  packages/ddex/entrypoint/tsconfig.node.json
  packages/ddex/entrypoint/vite.config.ts
  packages/ddex/webapp/client/package.json
  packages/ddex/webapp/client/src/pages/Login/Login.tsx
  packages/libs/src/sdk/oauth/OAuth.ts
Labels: size/L

#8141 Allow audio/x-flac mime type
  packages/libs/src/sdk/types/File.ts
Labels: size/XS

#8139 Test figma code-connect
  package-lock.json
  packages/harmony/package.json
  packages/harmony/src/components/button/Button/Button.stories.tsx
  packages/harmony/src/components/input/TextInput/TextInput.stories.tsx
Labels: size/M

#8150 fix: Minor copy change in album upload flow
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Labels: size/XS

#8151 Revert "Test figma code-connect (#8139)"
  package-lock.json
  packages/harmony/package.json
  packages/harmony/src/components/button/Button/Button.stories.tsx
  packages/harmony/src/components/input/TextInput/TextInput.stories.tsx
Labels: size/M

#8155 Add target for iOS privacy manifest
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/XS

#8143 [C-4247] Add cumulative rewards UI to web
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/common/src/store/challenges/selectors/optimistic-challenges.ts
  packages/discovery-provider/src/queries/get_challenges.py
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/CooldownSummaryTable.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/CooldownRewardsModalContent.tsx
Labels: size/L

#8160 Update cooldown days in response
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/XS

#8165 Don't allow creating developer app with user wallet as address [C-4041
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/M

#8158 [PAY-2692] Purchase/sale push+email notification album support
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseBuyer.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts
Labels: size/L

#8162 [ONC-74] Fix social account association
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/identity-service/src/routes/instagram.js
  packages/identity-service/src/routes/tiktok.js
  packages/identity-service/src/routes/twitter.js
  packages/identity-service/src/utils/waitForUser.js
  packages/libs/src/api/Account.ts
  packages/libs/src/services/identity/IdentityService.ts
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/L

#8142 [PAY-2666] Only show withdrawals on withdrawals tab
  .changeset/lucky-otters-look.md
  packages/common/src/api/user.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/transactions.py
  packages/discovery-provider/src/queries/get_usdc_transactions_history.py
  packages/libs/src/sdk/api/generated/default/models/Playlist.ts
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/L

#8145 [PAY-2709, PAY-2710, PAY-2708] Various CollectionTile fixes
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileTrackList.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.module.css
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
Labels: size/L

#8146 DDEX separate release date and validity start date
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
Labels: size/L

#8154 [PAY-2688] Add prototype foundation for manager mode
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/libs/src/sdk/api/grants/GrantsApi.ts
  packages/libs/src/sdk/api/grants/types.ts
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ManagerModeSettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ManagerModeSettingsModal.module.css
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ManagerModeSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/L

#8159 [INF-388] Improve protocol GH releases
  .circleci/config.yml
  .circleci/src/jobs/@root-jobs.yml
  .circleci/src/workflows/root.yml
Labels: size/M

#8169 Fix storage progress bar
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/XS

#8172 Fix changeset github action
  .github/workflows/publish-packages.yml
  scripts/publish-packages.sh
  scripts/version-packages.sh
Labels: size/S

#8167 Improve DDEX/aws interaction
  package.json
  packages/ddex/README.md
  packages/ddex/publisher/Dockerfile
  packages/ddex/webapp/Dockerfile.fast
  scripts/check_secrets.sh
  scripts/install-git-secrets.sh
  scripts/postinstall.sh
Labels: size/L

#8175 Add ddex s3 sync script
  packages/ddex/ingester/README.md
  packages/ddex/ingester/cmd/sync.go
Labels: size/M

#8170 Upgrade sentry to fix iOS build errors
  package-lock.json
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
Labels: size/S

#8157 [PAY-2615] Add support for common LUT in versioned transactions
  packages/common/src/services/env.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/env/env.dev.ts
  packages/mobile/src/env/env.prod.ts
  packages/mobile/src/env/env.stage.ts
  packages/web/src/services/env/env.dev.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
Labels: size/S
