Repository AudiusProject/apps, pull requests merged in 2024-08, with the labels that each got.

#9331 Add actions.json for solana blink support
  packages/web/public/actions.json
Labels: size/XS

#9340 [C-4905] Fix app crash when navigating to let them dj when signed out
  packages/web/src/pages/explore-page/ExploreCollectionsPageProvider.tsx
Labels: size/S

#9342 [PAY-3283] Show high res artwork in edit
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/S

#9341 Add actions.json to cloudflare
  packages/web/scripts/workers-site/index.js
  packages/web/src/ssr/worker.js
Labels: size/XS

#9324 add bpm edit flag col
  packages/discovery-provider/ddl/migrations/0086_add_bpm_edit_flag.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/metadata.py
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
Labels: size/M

#9169 Suppress warning in caa install
  packages/create-audius-app/helpers/install.ts
Labels: size/XS

#9343 [C-3907] Add empty state for artist results in sign up flow
  packages/common/src/messages/sign-on/pages.ts
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/S

#9344 Fix show premium downloads message
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/stream-availability/SpecialAccessFields.tsx
  packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Labels: size/M

#9345 Allow null bpms and musical keys
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#9350 Remove null checks for metadata items in useXMetadata
  packages/common/src/hooks/useCollectionMetadata.ts
  packages/common/src/hooks/useTrackMetadata.ts
Labels: size/XS

#9349 [C-4896] [C-4893] [C-4913] BPM precision adjustments
  packages/common/src/api/search.ts
  packages/common/src/hooks/useTrackMetadata.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/utils/bpm.ts
  packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/hooks/useBpmMaskedInput.ts
  packages/web/src/hooks/useRegexMaskedInput.ts
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
Labels: size/L

#9351 [PAY-3311] Create one_to_many_dms flag
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#9354 Add IconTowerBroadcast to harmony
  .changeset/nasty-rice-judge.md
  packages/harmony/src/assets/icons/TowerBroadcast.svg
  packages/harmony/src/icons/Changelog.stories.mdx
  packages/harmony/src/icons/UtilityIcons.stories.mdx
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/icons.ts
Labels: size/S

#9355 Fix sign in
  packages/common/src/audius-query/createApi.ts
Labels: size/XS

#9352 [C-4899] Fix isrc and iswc validation
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/IsrcIswcScreen.tsx
Labels: size/M

#9356 [C-4895] Fix profile screen verified badge
  packages/mobile/src/components/user/FollowsYouBadge.tsx
  packages/mobile/src/components/user/FollowsYouChip.tsx
  packages/mobile/src/components/user/index.ts
  packages/mobile/src/harmony-native/components/MusicBadge/MusicBadge.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
Labels: size/L

#9357 [C-4915] Fix create collection card height
  packages/mobile/src/components/collection-list/AddCollectionCard.tsx
Labels: size/S

#9310 [PAY-3253] Fix confirmation drawer height
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/components/CancelEditTrackDrawer.tsx
Labels: size/S

#9358 Add core to audius-compose and circleci
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/jobs/deploy-stage-nodes-just-tag.yml
  .circleci/src/workflows/core.yml
  .circleci/src/workflows/release.yml
  core/Makefile
  core/README.md
  core/infra/Dockerfile.tests
  core/infra/dev_config/discovery-one.docker.env
  core/infra/docker-compose.yml
  core/test/integration/kv_store_test.go
  dev-tools/compose/docker-compose.core.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
Labels: size/L

#9353 [C-4798] Filter all categories by verified
  packages/discovery-provider/src/queries/search_es.py
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
Labels: size/M

#9360 Add cors headers for actions
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#9359 [C-4891] Add artist pick to mobile
  packages/common/src/api/account.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/drawers/ArtistPickConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/web/src/components/artist-pick-modal/ArtistPickModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/VisibilityLabel.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
Labels: size/L

#9361 Fix core in docker-compose file
  dev-tools/compose/docker-compose.yml
Labels: size/S

#9365 Multiple cores for local dev
  core/infra/dev_config/content-one.docker.env
  core/infra/dev_config/content-three.docker.env
  core/infra/dev_config/content-two.docker.env
  core/infra/dev_config/discovery-one.docker.env
  dev-tools/compose/docker-compose.yml
Labels: size/M

#9363 [C-4681] [C-4680] Add analytics for search v2
  packages/common/src/api/search.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/models/Analytics.ts
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
  packages/web/src/app/AudiusQueryProvider.tsx
  packages/web/src/common/store/cache/tracks/sagaHelpers.ts
  packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
Labels: size/L

#9367 Bump mobile versions to 110
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9366 [C-4918] Improve harmony web FilterButton
  .changeset/stale-bulldogs-attend.md
  packages/ddex/webapp/client/src/pages/Releases/Releases.tsx
  packages/harmony/src/components/button/FilterButton/FilterButton.stories.tsx
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/FilterButtonKeyHandler.tsx
  packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.mdx
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/harmony/src/components/button/index.ts
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/select/Select/Select.tsx
  packages/web/src/components/edit/fields/KeySelectField.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/upload/TrackPreview.tsx
  packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SortMethodFilterButton.tsx
  packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Labels: size/XXL

#9368 Prevent service restarts when installing apt packages
  dev-tools/setup.sh
Labels: size/XS

#9370 [C-4921] Fix search v2 navigating back from profile
  packages/web/src/utils/route.ts
Labels: size/S

#9364 [PAY-3313] Targeted DMs CTA and modal
  packages/common/src/store/ui/modals/create-targeted-message-modal/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/chat-page/components/TargetedMessageCTA.tsx
  packages/web/src/pages/chat-page/components/TargetedMessageModal.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#9371 [QA-1486] Fix sign up select artists screen
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/XS

#9374 Remove audius-cmd purchase-content
  packages/commands/src/purchase-content.mjs
Labels: size/L

#9348 PROTO-1888: core plays
  core/Makefile
  core/chain/abci.go
  core/common/logger.go
  core/db/reads.sql.go
  core/db/sql/reads.sql
  core/gen/proto/protocol.pb.go
  core/gen/proto/protocol_grpc.pb.go
  core/go.mod
  core/go.sum
  core/grpc/server.go
  core/grpc/tx.go
  core/infra/dev_config/content-one.docker.env
  core/infra/dev_config/content-three.docker.env
  core/infra/dev_config/content-two.docker.env
  core/infra/docker-compose.yml
  core/main.go
  core/protocol.proto
  core/scripts/generate_options.go
  core/scripts/sandbox.go
  core/sdk/logger.go
  core/sdk/overrides.go
  core/sdk/sdk.go
  core/sdk/sdk_options.go
  core/sdk/signer_middleware.go
  core/test/integration/kv_store_test.go
  core/test/integration/network_test.go
  core/test/integration/plays_test.go
  core/test/integration/sdk_test.go
  core/test/integration/utils/nodes.go
  dev-tools/compose/docker-compose.test.yml
Labels: size/XXL

#9380 [QA-875] Use size for es query to fix feed pagination bug
  packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
  packages/discovery-provider/src/queries/get_feed_es.py
Labels: size/S

#9381 [QA-1114] Include menu items even if buttons are present
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
Labels: size/S

#9378 Fix short trending bug
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/header/desktop/HeaderGutter.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.jsx
  packages/web/src/components/menu/Menu.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/pages/MainContentContext.tsx
  packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/L

#9375 [PAY-3330] Fix spacing on RepostsFavoritesStats
  packages/web/src/components/collection/components/RepostsFavoritesStats.tsx
Labels: size/S

#9379 cleanup audio analysis code
  mediorum/ddl/clean_uploads_audio_analyses.sql
  mediorum/ddl/ddl.go
  mediorum/ddl/drop_audio_analysis_ops.sql
  mediorum/ddl/drop_uploads_audio_analysis_ops.sql
  mediorum/server/audio_analysis.go
  mediorum/server/legacy_audio_analysis.go
  mediorum/server/server.go
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/L

#9376 [PAY-3331] Purchase/sale endpoint filtering by content id
  .changeset/thin-crabs-brake.md
  packages/discovery-provider/integration_tests/queries/test_get_usdc_purchases.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_usdc_purchases.py
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/M

#9382 [C-4676] Fix es search returning deactivated content
  packages/es-indexer/src/indexNames.ts
  packages/es-indexer/src/indexers/PlaylistIndexer.ts
  packages/es-indexer/src/indexers/TrackIndexer.ts
  packages/es-indexer/src/listener.ts
Labels: size/S

#9319 Comments Read/Create E2E - Changes to DB/Discovery/SDK/Desktop UI
  .changeset/afraid-berries-rush.md
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/ddl/migrations/0083_create_comments.sql
  packages/discovery-provider/src/api/v1/api.py
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/models/comments/comment.py
  packages/discovery-provider/src/models/comments/comment_thread.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/api/comments/types.ts
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/CommentsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/apis/index.ts
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/libs/src/sdk/api/generated/default/models/CommentResponse.ts
  packages/libs/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/libs/src/sdk/api/generated/default/models/TrackCommentsResponse.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/EntityManager/index.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentHeader.tsx
  packages/web/src/components/comments/CommentSectionContext.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/components/comments/mock-data.ts
  packages/web/src/components/comments/types.ts
  packages/web/src/components/lineup/Lineup.tsx
  packages/web/src/components/section-button/SectionButton.module.css
  packages/web/src/pages/track-page/components/desktop/TrackPage.module.css
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/XXL

#9386 [PAY-3314] Track select dropdown for purchase/remix targeting
  packages/web/src/pages/chat-page/components/TargetedMessageModal.tsx
Labels: size/L

#9392 Add priority fees to purchases
  packages/libs/src/sdk/api/albums/AlbumsApi.ts
  packages/libs/src/sdk/api/tracks/TracksApi.ts
Labels: size/S

#9389 [QA-1446] Fix popup alignment
  packages/harmony/src/components/popup/Popup.tsx
  packages/web/src/components/menu/Menu.tsx
Labels: size/S

#9387 [PAY-2267] Update stage payment router and program addresses
  packages/libs/src/sdk/config/staging.ts
  packages/libs/src/sdk/scripts/generateServicesConfig.ts
  packages/mobile/src/env/env.stage.ts
  packages/web/src/services/env/env.stage.ts
  solana-programs/payment-router/Anchor.toml
  solana-programs/staking-bridge/Anchor.toml
  solana-programs/staking-bridge/package.json
  solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
Labels: size/M

#9373 [QA-1485] Redir to signup/in on direct /feed link
  packages/web/src/pages/feed-page/components/EmptyFeed.module.css
  packages/web/src/pages/feed-page/components/EmptyFeed.tsx
Labels: size/L

#9383 Add Pin icon and Timestamp component to harmony and harmony-native
  packages/harmony/src/assets/icons/Pin.svg
  packages/harmony/src/components/comments/SendIcon/SendIcon.tsx
  packages/harmony/src/components/comments/Timestamp/Timestamp.stories.tsx
  packages/harmony/src/components/comments/Timestamp/Timestamp.tsx
  packages/harmony/src/components/comments/Timestamp/index.ts
  packages/harmony/src/components/comments/Timestamp/types.ts
  packages/harmony/src/components/comments/Timestamp/util.ts
  packages/harmony/src/components/index.ts
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/components/Comments/Timestamp/Timestamp.stories.tsx
  packages/mobile/src/harmony-native/components/Comments/Timestamp/Timestamp.tsx
  packages/mobile/src/harmony-native/components/Comments/Timestamp/index.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/icons.ts
Labels: size/L

#9396 [QA-1459] Fix broken slugs
  packages/discovery-provider/ddl/migrations/0087_fix_slugs_with_slash.sql
Labels: size/XS

#9388 Clean up old trending versions
  packages/discovery-provider/integration_tests/queries/test_get_trending_playlists.py
  packages/discovery-provider/src/trending_strategies/BDNxn_trending_playlists_strategy.py
  packages/discovery-provider/src/trending_strategies/EJ57D_trending_tracks_strategy.py
  packages/discovery-provider/src/trending_strategies/EJ57D_underground_trending_tracks_strategy.py
  packages/discovery-provider/src/trending_strategies/trending_strategy_factory.py
  packages/discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/L

#9384 [C-4923] Persist verified filter & general cleanup
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page-v2/SortMethodFilterButton.tsx
  packages/web/src/pages/search-page-v2/categories.ts
  packages/web/src/pages/search-page-v2/hooks.ts
  packages/web/src/pages/search-page-v2/moods.tsx
  packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page-v2/search-results/AllResults.tsx
  packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
  packages/web/src/pages/search-page-v2/types.ts
  packages/web/src/pages/search-page-v2/utils.tsx
Labels: size/XL

#9385 [C 4922] Update mobile filter button
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButtonScreen.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/types.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/SelectMoodScreen.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
  packages/mobile/src/screens/search-screen-v2/BpmFilter.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/SearchFilters.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/index.ts
  packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMusicalKeyScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/index.ts
Labels: size/XL

#9372 Add comment actions: edit, delete, react
  packages/discovery-provider/ddl/migrations/0086_comment_reactions.sql
  packages/discovery-provider/src/models/comments/comment_reaction.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/libs/src/services/dataContracts/EntityManagerClient.ts
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentSectionContext.tsx
Labels: size/L

#9395 [PAY-3336] fix isPlaying logic for details screens
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#9394 [C-4937] Adding some pagination buttons
  packages/web/src/components/comments/CommentSectionContext.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/M

#9398 [C-4920] Only show bpm decimals if necessary
  packages/common/src/hooks/useTrackMetadata.ts
Labels: size/XS

#9397 [C-4936] FilterButton fixes
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
Labels: size/S

#9333 [PAY-3294] Hide save/repost for locked albums on mobile
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#9400 [C-4930, C-4931] Add IconText, ArtistPick, and Identifier components to harmony and harmony native
  packages/harmony/src/components/comments/ArtistPick/ArtistPick.stories.tsx
  packages/harmony/src/components/comments/ArtistPick/ArtistPick.tsx
  packages/harmony/src/components/comments/ArtistPick/index.ts
  packages/harmony/src/components/comments/ArtistPick/types.ts
  packages/harmony/src/components/comments/IconText/IconText.stories.tsx
  packages/harmony/src/components/comments/IconText/IconText.tsx
  packages/harmony/src/components/comments/IconText/index.ts
  packages/harmony/src/components/comments/IconText/types.ts
  packages/harmony/src/components/comments/Identifier/Identifier.stories.tsx
  packages/harmony/src/components/comments/Identifier/Identifier.tsx
  packages/harmony/src/components/comments/Identifier/index.ts
  packages/harmony/src/components/comments/Identifier/types.ts
  packages/harmony/src/components/index.ts
  packages/mobile/src/harmony-native/components/Comments/ArtistPick/ArtistPick.stories.tsx
  packages/mobile/src/harmony-native/components/Comments/ArtistPick/ArtistPick.tsx
  packages/mobile/src/harmony-native/components/Comments/ArtistPick/index.ts
  packages/mobile/src/harmony-native/components/Comments/IconText/IconText.stories.tsx
  packages/mobile/src/harmony-native/components/Comments/IconText/IconText.tsx
  packages/mobile/src/harmony-native/components/Comments/IconText/index.ts
  packages/mobile/src/harmony-native/components/Comments/IconText/types.ts
  packages/mobile/src/harmony-native/components/Comments/Identifier/Identifier.stories.tsx
  packages/mobile/src/harmony-native/components/Comments/Identifier/Identifier.tsx
  packages/mobile/src/harmony-native/components/Comments/Identifier/index.ts
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/L

#9403 [C-4934] Search bar fixes
  packages/web/src/components/header/desktop/Header.tsx
  packages/web/src/components/search/SearchBar.module.css
  packages/web/src/components/search/SearchBarV2.jsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
Labels: size/L

#9404 Payment router exception for when no geo_data found in memo
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/XS

#9405 Small repairer clean up
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/S

#9406 [QA-1496] fix unsafe read of audio analysis field
  packages/libs/src/sdk/services/Storage/types.ts
  packages/libs/src/services/creatorNode/CreatorNode.ts
Labels: size/XS

#9391 [QA-1357] Remove excessive polling and amplitude events in unlock
  packages/common/src/store/gated-content/sagas.ts
Labels: size/XS

#9103 Record Track Downloads via Entity Manager
  .changeset/fresh-apricots-peel.md
  packages/discovery-provider/ddl/migrations/0080_track_downloads.sql
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/rateLimitConfig.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/walletManager.ts
  packages/discovery-provider/src/models/tracks/track_download.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/libs/src/services/dataContracts/EntityManagerClient.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/L

#9399 [PAY-3335] Add priority fees to SDK Solana usages
  .changeset/dull-seahorses-kick.md
  packages/libs/src/sdk/api/albums/AlbumsApi.ts
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/libs/src/sdk/services/Solana/programs/BaseSolanaProgramClient.ts
  packages/libs/src/sdk/services/Solana/programs/types.ts
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/M

#9369 Add better error messages for Claimable Tokens Program
  .changeset/unlucky-chicken-listen.md
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Solana/programs/BaseSolanaProgramClient.ts
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/getDefaultConfig.ts
  packages/libs/src/sdk/services/Solana/programs/CustomInstructionError.ts
  packages/libs/src/sdk/services/Solana/programs/PaymentRouterClient/getDefaultConfig.ts
  packages/libs/src/sdk/services/Solana/programs/RewardManagerClient/RewardManagerClient.ts
  packages/libs/src/sdk/services/Solana/programs/RewardManagerClient/getDefaultConfig.ts
  packages/libs/src/sdk/services/Solana/programs/types.ts
  packages/spl/src/claimable-tokens/constants.ts
  packages/spl/src/index.ts
  packages/spl/src/reward-manager/constants.ts
  packages/web/src/common/store/tipping/sagas.ts
Labels: size/L

#9409 Fix useClickOutside
  packages/harmony/src/components/modal/Modal.tsx
  packages/harmony/src/components/popup/Popup.tsx
  packages/harmony/src/hooks/useClickOutside.ts
Labels: size/XS

#9390 [QA-1356] Improve notification UI
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/NotificationsButton.tsx
  packages/web/src/components/notification-dot/NotificationDot.module.css
Labels: size/M

#9412 Fix lint
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/XS

#9402 [QA-1491] Fix balance polling bug
  packages/common/src/hooks/useUSDCBalance.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/services/solana/tokenAccount.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/usdc-balance-row/USDCBalanceRow.tsx
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/address-tile/AddressTile.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Labels: size/M

#9411 [QA-1459] Fix 0087_fix_slugs_with_slash.sql migration
  packages/discovery-provider/ddl/migrations/0087_fix_slugs_with_slash.sql
Labels: size/M

#9410 relay retries
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
Labels: size/S

#9413 clean up aa endpts and limit ffprobe fields
  mediorum/server/serve_audio_analysis.go
  mediorum/server/serve_blob.go
  mediorum/server/server.go
  mediorum/server/transcode.go
Labels: size/M

#9401 [PAY-3332] Remixers users endpoint
  .changeset/fluffy-tigers-run.md
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_remixers.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/default/models/RemixersResponse.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/FullRemixersResponse.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
Labels: size/XL

#9414 fix repairer eager loading
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/M

#9416 add is_custom_musical_key
  packages/discovery-provider/ddl/migrations/0088_add_musical_key_edit_flag.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/metadata.py
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
Labels: size/M

#9418 Set is_custom_musical_key
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
Labels: size/XS

#9417 check is_custom_musical_key before pulling in calculated key in repairer
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/XS

#9415 [C-4932] Add CommentBody component to harmony and harmony-native
  packages/harmony/src/components/comments/CommentText/CommentText.stories.tsx
  packages/harmony/src/components/comments/CommentText/CommentText.tsx
  packages/harmony/src/components/comments/CommentText/index.ts
  packages/harmony/src/components/comments/CommentText/types.ts
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/harmony/src/components/text/Text.tsx
  packages/harmony/src/components/text/types.ts
  packages/mobile/src/harmony-native/components/Comments/CommentText/CommentText.tsx
  packages/mobile/src/harmony-native/components/Comments/CommentText/index.ts
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/L

#9426 [QA-1501] Fix mobile search input
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/index.ts
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
Labels: size/L

#9425 Fix pagination args
  packages/discovery-provider/src/api/v1/tracks.py
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
Labels: size/S

#9421 Testnet configuration for cometbft core
  .circleci/src/workflows/core.yml
  core/Makefile
  core/chain/node.go
  core/config/comet.go
  core/config/config.go
  core/config/genesis/stage.json
  core/infra/Dockerfile
  core/infra/dev_config/content-one.docker.env
  core/infra/dev_config/content-one.env
  core/infra/dev_config/content-three.docker.env
  core/infra/dev_config/content-three.env
  core/infra/dev_config/content-two.docker.env
  core/infra/dev_config/content-two.env
  core/infra/dev_config/discovery-one.docker.env
  core/infra/dev_config/discovery-one.env
Labels: size/L

#9428 Add buy button metrics
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/track/GatedConditionsPill.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/M

#9429 Format Solana Relay listens endpoint
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/M

#9420 [QA-1434] Fix hanging uploads due to errors on mobile
  packages/common/src/store/upload/selectors.ts
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Labels: size/M

#9308 [PAY-2917][QA-1466] Migrate more users endpoints
  packages/common/src/adapters/index.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/api/topArtists.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/user-list/related-artists/sagas.ts
  packages/web/src/components/related-artists/RelatedArtists.tsx
Labels: size/L

#9433 Fix comment reactions pkey
  packages/discovery-provider/ddl/migrations/0089_fix_comment_reactions_pkey.sql
Labels: size/XS

#9423 [C-4910] Audius-query-ify comments state management
  packages/common/src/api/comments.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/audius-query/README.md
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/audius-query/utils.ts
  packages/discovery-provider/src/api/v1/comments.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentSectionContext.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/components/comments/NoComments.tsx
  packages/web/src/components/comments/mock-data.ts
  packages/web/src/components/comments/types.ts
Labels: size/XL

#9424 [PAY-3300] Chat blast: lazy create thread
  comms/discovery/db/queries/get_chat_messages.go
  comms/discovery/db/queries/get_chats.go
  comms/discovery/db/queries/get_new_blasts.go
  comms/discovery/misc/chat_id.go
  comms/discovery/misc/hashids_util.go
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_blast.go
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/schema/schema.go
  comms/discovery/server/server.go
  packages/discovery-provider/ddl/migrations/0086_chat_blast.sql
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/XL

#9430 Fix duplicate error name in sentry
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#9431 use comet repo and modd for hotreloading
  core/Makefile
  core/go.mod
  core/go.sum
  core/main.go
  core/modd.conf
Labels: size/M

#9439 Add social signup feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
Labels: size/M

#9437 [C-4910] Comments replys & deletes fixes
  packages/common/src/api/comments.ts
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentSectionContext.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/L

#9440 Move comments context to common
  packages/common/src/context/commentsContext.tsx
  packages/common/src/context/index.ts
  packages/common/tsconfig.json
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/S

#9436 [PAY-3310] Chat blast function in sdk
  .changeset/soft-games-flash.md
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/clientTypes.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
Labels: size/L

#9444 [C-4964] Comment header changes
  packages/common/src/context/commentsContext.tsx
  packages/web/src/components/comments/CommentHeader.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentSkeletons.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#9443 Rename Targeted Message to Chat Blast
  packages/common/src/store/ui/modals/create-chat-blast-modal/index.ts
  packages/common/src/store/ui/modals/create-targeted-message-modal/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/M

#9445 core default values
  core/chain/node.go
  core/config/config.go
  core/config/defaults.go
  core/config/utils.go
  core/infra/Dockerfile
Labels: size/M

#9446 use const for constants
  core/config/defaults.go
Labels: size/XS

#9442 [PAY-3341] Add is_plaintext field for chat message
  comms/Makefile
  comms/discovery/db/queries/get_chat_messages.go
  comms/discovery/db/queries/get_chats.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/rpcz/chat_create_test.go
  comms/discovery/schema/schema.go
  comms/discovery/server/response_mapper.go
  packages/discovery-provider/ddl/migrations/0090_chat_last_message_is_plaintext.sql
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#9447 Create ChatBlast from web
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
  packages/web/src/pages/chat-page/components/ChatList.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/L

#9434 [PAY-3227] Unfurl tracks in composer
  packages/common/src/utils/chatUtils.ts
  packages/harmony/src/assets/icons/Send.svg
  packages/libs/src/sdk/sdk.ts
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ComposeTrackInfo.tsx
Labels: size/L

#9451 [QA-1495] Fix 404 for users
  packages/common/src/utils/error.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/store/errors/reportToSentry.ts
Labels: size/S

#9448 Don't decrypt plaintext messages
  .changeset/few-numbers-march.md
  packages/libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#9452 wrong core defaults
  core/config/defaults.go
Labels: size/XS

#9456 Fix bug in profile page 404
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#9454 More explicit audience columns for chat blast.
  comms/discovery/db/queries/get_new_blasts.go
  comms/discovery/rpcz/chat_blast.go
  comms/discovery/schema/schema.go
  packages/discovery-provider/ddl/migrations/0091_chat_audience_updates.sql
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#9453 [PAY-3307] Upgrade chat blasts to chats in sdk (V2)
  .changeset/chatty-cameras-yawn.md
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/websocket.go
  comms/discovery/schema/schema.go
  packages/common/src/store/pages/chat/sagas.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/clientTypes.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#9457 bump web3 version for ci
  packages/discovery-provider/requirements.txt
Labels: size/XS

#9450 Auto-deploy to SPs, consolidate git configuration
  .circleci/config.yml
  .circleci/scripts/auto-approve-release.sh
  .circleci/src/commands/@git-commands.yml
  .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
  .circleci/src/jobs/deploy-foundation-nodes.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
  .circleci/src/jobs/release-audius-docker-compose.yml
Labels: size/L

#9432 [PAY-2917] Migrate user endpoints to SDK, round 3
  .changeset/warm-squids-occur.md
  packages/common/src/adapters/challenge.ts
  packages/common/src/adapters/index.ts
  packages/common/src/adapters/wallet.ts
  packages/common/src/api/favorites.ts
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/common/src/models/AudioRewards.ts
  packages/common/src/models/Wallet.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/challenges/selectors/optimistic-challenges.ts
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/store/pages/audio-rewards/types.ts
  packages/common/src/utils/challenges.ts
  packages/common/src/utils/sdkMigrationUtils.ts
  packages/discovery-provider/src/api/v1/challenges.py
  packages/discovery-provider/src/api/v1/users.py
  packages/libs/src/sdk/api/challenges/ChallengesApi.ts
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/ChallengesApi.ts
  packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/default/apis/index.ts
  packages/libs/src/sdk/api/generated/default/models/ChallengeResponse.ts
  packages/libs/src/sdk/api/generated/default/models/GetChallenges.ts
  packages/libs/src/sdk/api/generated/default/models/UndisbursedChallenge.ts
  packages/libs/src/sdk/api/generated/default/models/UndisbursedChallenges.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/services/wallet-client.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/token-dashboard/checkIsNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/profile/fetchTopTagsSaga.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/services/wallet-client.ts
Labels: size/XXL

#9459 Use quotes to escape job name for jq
  .circleci/scripts/auto-approve-release.sh
Labels: size/XS

#9460 Fix chat deadlock
  comms/discovery/rpcz/websocket.go
Labels: size/XS

#9462 Fix comment delete in audius-query
  packages/common/src/api/comments.ts
Labels: size/XS

#9461 Fix bad claimable challenge state due to nullable max_steps
  packages/common/src/adapters/challenge.ts
  packages/common/src/hooks/useAudioRewards.ts
  packages/common/src/models/AudioRewards.ts
  packages/common/src/store/challenges/selectors/optimistic-challenges.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/M

#9463 Optimistic add chat blasts
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/utils/chatUtils.ts
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/L

#9464 Fix malformed json in auto-approve script
  .circleci/scripts/auto-approve-release.sh
Labels: size/S

#9465 default connection strings
  core/config/config.go
  core/config/defaults.go
Labels: size/XS

#9468 fix TS error
  packages/common/src/context/commentsContext.tsx
Labels: size/XS

#9470 Don't decrypt plaintext chat.last_message
  .changeset/cold-bees-rest.md
  comms/discovery/server/response_mapper.go
  packages/libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/S

#9466 Hook up client blast params to sdk
  .changeset/funny-students-prove.md
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/utils/chatUtils.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/clientTypes.ts
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
Labels: size/L

#9422 [C-4929] Add SendIcon component to harmony and harmony native
  packages/harmony/src/assets/icons/PaperAirplane.svg
  packages/harmony/src/components/comments/CommentText/CommentText.tsx
  packages/harmony/src/components/comments/SendIcon/SendIcon.stories.tsx
  packages/harmony/src/components/comments/SendIcon/SendIcon.tsx
  packages/harmony/src/components/comments/SendIcon/index.ts
  packages/harmony/src/components/comments/SendIcon/types.ts
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/components/Comments/SendIcon/SendIcon.tsx
  packages/mobile/src/harmony-native/components/Comments/SendIcon/index.ts
  packages/mobile/src/harmony-native/components/Comments/SendIcon/types.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/icons.ts
Labels: size/L

#9471 change pg string for regex in content (core)
  core/config/defaults.go
Labels: size/XS

#9435 Add comment replies pagination
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/generated/default/apis/CommentsApi.ts
Labels: size/M

#9467 [QA-1504] Fix payout wallet set default
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/L

#9455 [C-4828] Add timestamp features to comments
  packages/common/src/api/comments.ts
  packages/common/src/context/commentsContext.tsx
  packages/common/src/utils/formatTrackTimestamp.ts
  packages/discovery-provider/ddl/migrations/0091_comments_ms_to_s.sql
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/models/comments/comment.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/harmony/src/components/scrubber/Scrubber.tsx
  packages/harmony/src/components/scrubber/Slider.tsx
  packages/harmony/src/index.ts
  packages/harmony/src/utils/formatTrackTimestamp.ts
  packages/harmony/src/utils/index.ts
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/libs/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/mock-data.ts
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/TimestampLink.tsx
  packages/web/src/components/comments/mock-data.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#9408 [PAY-3315][PAY-3316][PAY-3323] Staking bridge
  packages/common/src/store/purchase-content/sagas.ts
  packages/discovery-provider/default_config.ini
  packages/discovery-provider/integration_tests/queries/test_get_extended_purchase_gate.py
  packages/discovery-provider/src/api/v1/models/access_gate.py
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
  packages/libs/src/sdk/api/albums/AlbumsApi.ts
  packages/libs/src/sdk/api/albums/types.ts
  packages/libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/models/ExtendedPaymentSplit.ts
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/utils/preparePaymentSplits.ts
Labels: size/L

#9475 [C-4940] Add comment badges (desktop web)
  packages/common/src/context/commentsContext.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/mobile/src/components/comments/mock-data.ts
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/comments/CommentBadges.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/mock-data.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#9472 [C-4939] Add comment action menu popup
  packages/common/src/api/comments.ts
  packages/common/src/context/commentsContext.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBadges.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/mock-data.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#9473 [PAY-3299] Chat blast sender endpoints
  comms/Makefile
  comms/discovery/db/queries/get_chat_messages.go
  comms/discovery/db/queries/get_chats.go
  comms/discovery/rpcz/chat_blast_test.go
Labels: size/L

#9476 [PAY-3358] Fire chat message RPCs on blast write
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat_blast.go
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/schema/schema.go
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/M

#9481 Bump mobile apps to 111
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9480 live reloading with modd
  core/.dockerignore
  core/Makefile
  core/README.md
  core/chain/node.go
  core/config/config.go
  core/config/genesis/genesis.go
  core/config/genesis/sandbox.json
  core/db/db.go
  core/db/models.go
  core/db/reads.sql.go
  core/db/writes.sql.go
  core/infra/Dockerfile.dev
  core/infra/dev_config/content-one.env
  core/infra/dev_config/content-three.env
  core/infra/dev_config/content-two.env
  core/infra/dev_config/discovery-one.env
  core/infra/dev_config/sandbox-one.env
  core/infra/docker-compose.yml
  core/modd.conf
  core/protocol.proto
  core/scripts/sandbox.go
Labels: size/L

#9484 [QA-1514] Fix search filter typing
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
Labels: size/M

#9486 [QA-1511] Fix space & arrow hotkeys not working
  .changeset/forty-bags-refuse.md
  packages/harmony/src/hooks/useHotKeys.ts
Labels: size/XS

#9489 [C-4976] Refactor comment hooks
  packages/common/src/context/commentsContext.tsx
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
Labels: size/L

#9487 [PAY-3201] Fix chat blast reactions
  comms/discovery/db/queries/get_chat_messages.go
Labels: size/XS

#9488 [PAY-3345] Prevent artist reacting to their own blasts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/S

#9490 Remote config for chat blast tier requirement
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
Labels: size/S

#9458 Separate saga top level error handling
  packages/common/src/utils/sagaHelpers.ts
  packages/mobile/src/store/sagas.ts
  packages/mobile/src/utils/reportToSentry.ts
  packages/web/src/store/sagas.ts
Labels: size/M

#9482 Revamp local solana-test-validator
  .changeset/fast-cheetahs-dream.md
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.yml
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
  packages/libs/src/sdk/services/Solana/programs/RewardManagerClient/RewardManagerClient.ts
  solana-programs/Dockerfile
  solana-programs/Dockerfile.cacheLedger
  solana-programs/Dockerfile.dev
  solana-programs/README.md
  solana-programs/fixtures/eth-registry-signer-group.json
  solana-programs/fixtures/eth-registry-valid-signer.json
  solana-programs/fixtures/fee-payer.json
  solana-programs/fixtures/owner.json
  solana-programs/fixtures/reward-manager-state.json
  solana-programs/fixtures/reward-manager-tokens.json
  solana-programs/fixtures/usdc.json
  solana-programs/fixtures/waudio.json
  solana-programs/payment-router/rust-toolchain
  solana-programs/scripts/build.sh
  solana-programs/scripts/deploy.sh
  solana-programs/scripts/init-dev-fixtures.sh
  solana-programs/scripts/install-solana.sh
  solana-programs/scripts/setup-predeployed.sh
  solana-programs/scripts/update-keys.sh
Labels: size/XXL

#9427 [C- 4926] Add Menu/MenuItem and update Select
  packages/harmony/rollup.config.mjs
  packages/harmony/src/components/button/FilterButton/FilterButton.stories.tsx
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/input/TextInput/types.ts
  packages/harmony/src/components/internal/Menu.tsx
  packages/harmony/src/components/internal/MenuItem.tsx
  packages/harmony/src/components/internal/OptionKeyHandler.tsx
  packages/harmony/src/components/select/Select/Select.mdx
  packages/harmony/src/components/select/Select/Select.stories.tsx
  packages/harmony/src/components/select/Select/Select.tsx
  packages/harmony/src/components/select/Select/types.ts
  packages/harmony/src/components/select/SelectInput/SelectInput.tsx
  packages/harmony/src/components/select/SelectInput/index.ts
  packages/harmony/src/components/select/SelectInput/types.ts
  packages/harmony/src/components/select/index.ts
  packages/harmony/src/foundations/theme/types.ts
  packages/web/src/components/edit/fields/KeySelectField.tsx
  packages/web/src/components/edit/fields/visibility/ScheduledReleaseDateField.tsx
  packages/web/src/components/form-fields/SelectField.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/upload/TrackPreview.tsx
  packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
Labels: size/XXL

#9483 [PAY-3309] Add is_hidden column to chat_member
  comms/discovery/db/queries/get_chats.go
  comms/discovery/rpcz/chat.go
  comms/discovery/rpcz/chat_blast_test.go
  packages/discovery-provider/ddl/migrations/0092_chat_member_hidden.sql
Labels: size/M

#9485 Fix challenge claim notification amount
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
Labels: size/M

#9495 PROTO-1910: core console
  core/Makefile
  core/console/assets/Glyph_Black.svg
  core/console/assets/assets.go
  core/console/block_page.go
  core/console/components/base.templ
  core/console/components/base_templ.go
  core/console/components/block_page.templ
  core/console/components/block_page_templ.go
  core/console/components/header_bar.templ
  core/console/components/header_bar_templ.go
  core/console/components/home_page.templ
  core/console/components/home_page_templ.go
  core/console/components/tx_page.templ
  core/console/components/tx_page_templ.go
  core/console/console.go
  core/console/home_page.go
  core/console/middleware/error_middleware.go
  core/console/network_page.go
  core/console/node_page.go
  core/console/styles/styles.go
  core/console/tx_page.go
  core/console/utils/render.go
  core/db/reads.sql.go
  core/db/sql/migrations/00003_index_tx_hash_lower.sql
  core/db/sql/reads.sql
  core/go.mod
  core/go.sum
  core/infra/Dockerfile
  core/infra/docker-compose.yml
  core/main.go
  core/scripts/sandbox.go
  dev-tools/compose/docker-compose.yml
Labels: size/XL

#9479 Remove listenUserId from chat api
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/clientTypes.ts
Labels: size/S

#9497 [QA-1517] Include UserID in websocket metadata
  comms/discovery/rpcz/websocket.go
  comms/discovery/schema/schema.go
Labels: size/XS

#9496 Remove rule 13 from blocking relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/antiAbuseConfig.ts
Labels: size/XS

#9498 Fix CTA empty states reversed web/mobile
  packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx
  packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
Labels: size/L

#9499 [PAY-3366] Fix CTA hidden on small screens
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Labels: size/XS
