Repository AudiusProject/apps, pull requests merged in 2024-07, with the labels that each got.

#8980 [PAY-3133][PAY-3127] Better UX for accept/reject flows
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ArtistInfo.module.css
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ArtistInfo.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagedUserListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagerListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
Labels: size/XL

#9008 Improve mobile search state and navigation
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/index.ts
  packages/mobile/src/screens/search-screen-v2/searchState.ts
Labels: size/L

#9014 Migrate to private rpc for saga deployment
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#8991 [PROTO-1873] re-index playlists containing track when track changes.
  packages/es-indexer/src/listener.ts
Labels: size/L

#8996 move audio analysis retry logic to content
  mediorum/server/audio_analysis.go
  mediorum/server/legacy_audio_analysis.go
  mediorum/server/serve_audio_analysis.go
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/L

#9004 [C-4572] Advanced search UI polish
  packages/common/src/hooks/useTrackMetadata.ts
  packages/common/src/utils/musicalKeys.ts
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/harmony/src/components/select/Select/Select.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/L

#8998 [C-4624] Add FilterButton to Harmony Native
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/types.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
Labels: size/L

#8995 [PAY-3147] Allow unsave/unrepost hidden track/album
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/web/src/components/edit-collection/mobile/EditPlaylistPage.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/M

#9016 Make small label update to FilterButton
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
Labels: size/S

#9017 [QA-1412] Show play button and hide stats on smart collections
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#9009 [C-4585] Add mobile search musical key filter
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/layout/Box/Box.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/components/FormScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/index.ts
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/IsrcIswcScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/LicenseTypeScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/NFTCollectionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/SelectGenreScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/SelectMoodScreen.tsx
  packages/mobile/src/screens/form-screen/FormScreen.tsx
  packages/mobile/src/screens/form-screen/index.ts
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/list-selection-screen/index.ts
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/components/index.ts
  packages/mobile/src/screens/search-screen-v2/index.ts
  packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMusicalKeyScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/index.ts
  packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/SearchResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/L

#9010 PAY-2489 PAY-2507 Fix UI for Change Email, Change Password
  packages/common/src/hooks/useChangePasswordFormConfiguration.ts
  packages/mobile/src/screens/change-email-screen/ChangeEmailScreen.tsx
  packages/mobile/src/screens/change-email-screen/SubScreens.tsx
  packages/mobile/src/screens/change-password-screen/ChangePasswordScreen.tsx
  packages/mobile/src/screens/change-password-screen/SubScreens.tsx
  packages/web/src/components/change-password/ChangePasswordModal.tsx
  packages/web/src/pages/settings-page/components/mobile/ChangePasswordPage.tsx
Labels: size/L

#9018 [C-4555] Add release date to new track edit
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/components/edit/fields/DatePickerField.tsx
  packages/web/src/components/edit/fields/ReleaseDateField.module.css
  packages/web/src/components/edit/fields/ReleaseDateField.tsx
  packages/web/src/components/edit/fields/ReleaseDateFieldLegacy.tsx
  packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
Labels: size/L

#9015 [PAY-3145][PAY-3150] Do not show hidden track/album in feed/trending/explore
  packages/web/src/common/store/smart-collection/sagas.ts
Labels: size/XS

#9020 [QA-1414] Force fetch playlist on navigate from playlist tile
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
Labels: size/XS

#9019 [C-4621] Advanced search mobile web
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/nav/mobile/NavBar.module.css
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/pages/search-page-v2/NoResultsTile.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
  packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
  packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
  packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
  packages/web/src/pages/search-page-v2/ResultsTracksView.tsx
  packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/utils/route.ts
Labels: size/XL

#9025 [QA-1416] Fix top-artists and audius-query
  packages/common/src/api/topArtists.ts
  packages/common/src/audius-query/createApi.ts
Labels: size/S

#9026 Simplify legacy audio analysis queue code.
  mediorum/server/legacy_audio_analysis.go
  mediorum/server/serve_audio_analysis.go
  mediorum/server/server.go
Labels: size/L

#9027 Simplify audio analysis for ba cids
  mediorum/server/audio_analysis.go
  mediorum/server/serve_audio_analysis.go
  mediorum/server/transcode.go
Labels: size/L

#9030 [C-4687] Wire up mobile advanced search tracks lineup
  packages/common/src/api/search.ts
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
Labels: size/L

#9029 [C-4586] Add mobile FilterBpmScreen for new search screen
  packages/common/src/utils/musicalKeys.ts
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/index.ts
Labels: size/XL

#9032 Connect remaining mobile search filters
  packages/common/src/api/search.ts
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
Labels: size/M

#8904 [PAY-3125] Add SDK support for location in transaction
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/instruction/location.ts
  packages/libs/src/sdk/api/albums/AlbumsApi.test.ts
  packages/libs/src/sdk/api/albums/AlbumsApi.ts
  packages/libs/src/sdk/api/tracks/TracksApi.test.ts
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Solana/SolanaRelay.ts
Labels: size/M

#9035 [C-4652] Fix track update access conditions
  packages/web/src/common/store/cache/tracks/sagas.ts
Labels: size/XS

#9031 [C-4688] Add AlbumResults and PlaylistResults for advanced search
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/schema.ts
  packages/common/src/audius-query/types.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/SearchResults.tsx
  packages/mobile/src/screens/search-screen-v2/searchState.ts
Labels: size/M

#9036 Add tests for updating track access conditions
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
Labels: size/L

#9033 [C-4641 C-4654 C-4648] Edit track page fixes
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/edit/fields/DatePickerField.module.css
  packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
Labels: size/M

#9037 [C-4606] Mobile advanced search All Results screen
  packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
  packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/SearchResults.tsx
  packages/mobile/src/screens/search-screen-v2/searchState.ts
Labels: size/XL

#9038 [C-4649] fix jumping date picker popup
  packages/web/src/components/edit/fields/DatePickerField.module.css
Labels: size/XS

#9039 Fix preview times longer than track duration not erroring
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/price-and-audience/priceAndAudienceSchema.ts
Labels: size/XS

#9040 [C-4694] Add track_count to non-full playlist endpoint
  packages/discovery-provider/src/api/v1/models/playlists.py
Labels: size/XS

#9042 [C-4632] Show 'remove' artwork button on edit collection, otherwise 'change' button
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.jsx
  packages/web/src/components/upload/UploadArtwork.d.ts
  packages/web/src/components/upload/UploadArtwork.jsx
Labels: size/S

#9021 [C-4637] Edit Collection Page
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/common/src/store/cache/collections/types.ts
  packages/common/src/store/ui/modals/edit-playlist-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/upload/types.ts
  packages/harmony/src/components/button/BaseButton/BaseButton.tsx
  packages/harmony/src/components/button/BaseButton/types.ts
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/harmony/src/components/popup/Popup.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistModalScreen.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.tsx
  packages/web/src/components/edit-collection/DeleteCollectionConfirmationModal.tsx
  packages/web/src/components/edit-collection/EditCollectionForm.module.css
  packages/web/src/components/edit-collection/EditCollectionForm.tsx
  packages/web/src/components/edit-collection/ReleaseCollectionConfirmationModal.tsx
  packages/web/src/components/edit-collection/desktop/EditCollectionModal.module.css
  packages/web/src/components/edit-collection/desktop/EditCollectionModal.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit-track/types.ts
  packages/web/src/components/edit/AnchoredSubmitRow.module.css
  packages/web/src/components/edit/AnchoredSubmitRow.tsx
  packages/web/src/components/edit/AnchoredSubmitRowEdit.module.css
  packages/web/src/components/edit/AnchoredSubmitRowEdit.tsx
  packages/web/src/components/edit/fields/CollectionTrackField.tsx
  packages/web/src/components/edit/fields/CollectionTrackFieldArray.tsx
  packages/web/src/components/header/desktop/Header.jsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/DeleteFolderConfirmationModal.tsx
  packages/web/src/components/nav/mobile/TopLevelPage.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
  packages/web/src/pages/edit-collection-page/index.tsx
  packages/web/src/pages/edit-collection-page/mobile/EditCollectionPage.module.css
  packages/web/src/pages/edit-collection-page/mobile/EditCollectionPage.tsx
  packages/web/src/pages/edit-collection-page/mobile/RemoveCollectionTrackDrawer.module.css
  packages/web/src/pages/edit-collection-page/mobile/RemoveCollectionTrackDrawer.tsx
  packages/web/src/pages/edit-collection-page/utils.ts
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/upload-page/forms/UploadCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
  packages/web/src/utils/route.ts
Labels: size/XXL

#9045 Fix condition for adding hidden track to playlist
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
Labels: size/XS

#9046 Patch paginated query bug
  packages/common/src/audius-query/hooks/usePaginatedQuery.ts
Labels: size/XS

#9043 [C-4650] Fix visibility field when released scheduled release
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Labels: size/S

#9044 [C-46916] Fix Block API Streaming
  packages/web/src/components/edit/fields/AdvancedField.tsx
Labels: size/XS

#9028 PROTO-1866: merge change email and post auth into one route
  packages/common/src/hooks/useChangeEmailFormConfiguration.ts
  packages/identity-service/src/routes/authentication.js
  packages/identity-service/test/authenticationTest.js
Labels: size/L

#9051 Mediorum: skip image transcode
  mediorum/server/audio_analysis.go
  mediorum/server/serve_upload.go
Labels: size/XS

#9050 [C-4594] Fix user-generated-text links
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
Labels: size/S

#9048 [C-4647] Fix license type
  packages/common/src/utils/creativeCommons.ts
  packages/web/src/components/edit-track/types.ts
  packages/web/src/components/edit-track/utils/computeLicenseIcons.ts
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
Labels: size/L

#9049 [C-4695] Fix remix field visibility
  packages/libs/src/api/Track.ts
  packages/libs/src/utils/types.ts
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Labels: size/L

#9054 Hide 0 stats on mobile collection screens
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
Labels: size/S

#9056 Fix mobile single-OTP signup
  packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
Labels: size/XS

#9057 [QA-1419] Fix twitter/instagram oauth exiting early
  packages/mobile/src/components/oauth/OAuthWebView.tsx
Labels: size/XS

#9060 [QA-1426] Fix audius-query array normalization
  packages/common/src/audius-query/createApi.ts
Labels: size/XS

#9059 Fix libs track validation
  packages/libs/src/api/Track.ts
Labels: size/XS

#9053 [C-4684] Fix edit-collection width
  packages/web/src/components/edit-collection/EditCollectionForm.module.css
Labels: size/XS

#9055 [C-4651] Fix stems upload refetch bug
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/store/application/ui/stemsUpload/sagas.ts
Labels: size/M

#9041 [C-4630] Update Confirm Modal copy
  packages/web/src/components/upload-confirmation-modal/UploadConfirmationModal.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
Labels: size/S

#9024 [PAY-3156] Fix Rewards Claiming Analytics
  .changeset/soft-kiwis-swim.md
  packages/common/src/models/Analytics.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/Rewards.ts
  packages/common/src/services/audius-backend/index.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/libs/src/sdk/api/challenges/ChallengesApi.ts
  packages/libs/src/sdk/utils/errors.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/audio-rewards/store.test.ts
  packages/web/src/store/errors/reportToSentry.ts
Labels: size/XXL

#9064 Respect schema key arrays
  packages/common/src/audius-query/createApi.ts
Labels: size/S

#9034 [PAY-3150][PAY-3158] Exclude playlists with only hidden tracks from feed/explore/trending and update library
  packages/discovery-provider/integration_tests/queries/test_get_collections_library.py
  packages/discovery-provider/integration_tests/queries/test_get_track_library.py
  packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
  packages/discovery-provider/integration_tests/tasks/test_get_top_playlists_es.py
  packages/discovery-provider/src/queries/get_collection_library.py
  packages/discovery-provider/src/queries/get_feed.py
  packages/discovery-provider/src/queries/get_feed_es.py
  packages/discovery-provider/src/queries/get_top_playlists_es.py
  packages/discovery-provider/src/queries/get_track_library.py
  packages/discovery-provider/src/queries/get_trending_playlists.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/web/src/common/store/pages/history/lineups/sagas.ts
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/L

#9065 Update all emails: updated design, manage preferences
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcTransfer.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcWithdrawal.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/claimableReward.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/rewardInCooldown.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcWithdrawal.ts
  packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
  packages/identity-service/src/notifications/emails/downloadMobileApp.html
  packages/identity-service/src/notifications/emails/otp.js
  packages/identity-service/src/notifications/emails/welcome.js
  packages/identity-service/src/notifications/sendDownloadAppEmails.js
  packages/identity-service/src/routes/recovery.js
  packages/identity-service/src/routes/welcomeEmail.js
  packages/identity-service/src/utils/otp.js
Labels: size/XXL

#9061 [C-4702] Add empty states for mobile search results and fix track search request
  packages/common/src/api/search.ts
  packages/mobile/src/screens/search-screen-v2/NoResultsTile.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
  packages/mobile/src/screens/search-screen-v2/searchState.ts
Labels: size/L

#8718 [PAY-3090] Add priority fees to SDK transactions (opt in)
  packages/libs/src/sdk/services/Solana/programs/BaseSolanaProgramClient.ts
  packages/libs/src/sdk/services/Solana/programs/types.ts
Labels: size/M

#9070 Fix unlocked premium content label color
  packages/web/src/components/track/GatedContentLabel.tsx
Labels: size/XS

#9066 [PAY-3154] Fix accidental refresh on removing managers
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
Labels: size/S

#9071 [C-4589] Add links from track tile screen to search screen
  packages/mobile/src/components/details-tile/TrackMetadataList.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/utils/route.ts
Labels: size/M

#9073 [C-4703] Update FilterButton to remove controlled value
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Labels: size/M

#9074 [PAY-3132] Manager Mode Modal Movement Mending
  packages/harmony/src/components/modal/ModalContentPages.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagerListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/StopManagingConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/types.ts
Labels: size/L

#9062 [C-4591] Edit key/bpm on mobile
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/fields/KeyBpmField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/SelectKeyField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/KeyBpmScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/SelectKeyScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/index.ts
  packages/mobile/src/screens/edit-track-screen/types.ts
Labels: size/L

#9069 Fix web tag search for search v1 and v2
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/components/search/SearchTag.tsx
Labels: size/M

#9076 Make view content button large on mobile purchase success
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
Labels: size/XS

#9063 [C-4600] Update tile action buttons for owners
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/publish-content-modal.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/sagas.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/selectors.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/slice.ts
  packages/common/src/store/ui/publish-playlist-confirmation-modal/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/drawers/ReleaseNowConfirmationDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/publish-content-drawer/PublishContentDrawer.tsx
  packages/mobile/src/components/publish-content-drawer/index.ts
  packages/mobile/src/components/publish-playlist-drawer/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/components/alt-button/FavoriteButton.tsx
  packages/web/src/components/alt-button/ShareButton.tsx
  packages/web/src/components/track/OwnerActionButtons.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/track/desktop/BottomRow.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#9075 [C-4700] Mobile tag search
  packages/common/src/api/search.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
Labels: size/L

#9081 [C-4724] Fix signup/in with metamask
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/pages/sign-up-page/components/SignUpWithMetaMaskButton.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
Labels: size/L

#9072 Allow unlisting tracks and playlists in DN indexing
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#9083 [QA-1430] Fix duplicate trending playlist
  packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
Labels: size/XS

#9078 PROTO-1847: identity discprov plays
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/health/health.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
  packages/identity-service/src/config.js
  packages/identity-service/src/routes/trackListens.js
Labels: size/L

#9080 [C-4722] [C-4723] Mobile advanced search UI fixes
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/types.ts
  packages/mobile/src/screens/edit-track-screen/screens/KeyBpmScreen.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
Labels: size/M

#9085 Lint fixes
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
Labels: size/XS

#9086 Show hidden tracks in the library purchases/all tab, hide from all other tabs
  packages/discovery-provider/integration_tests/queries/test_get_track_library.py
  packages/discovery-provider/src/queries/get_track_library.py
Labels: size/M

#9067 Add MRI UDR export
  packages/discovery-provider/plugins/pedalboard/apps/mri/package.json
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/clm.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/csv.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/server.ts
Labels: size/L

#9088 [C-4697] Add loading states for the mobile search results
  packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
Labels: size/L

#9092 [C-4669] Update new search page to maintain common filters between categories
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
Labels: size/M

#9079 [PAY-3140] Allow freely editing track/album access gate
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
  packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.test.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Labels: size/XL

#9093 Fix TRPC server with local dev audius-compose
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/nginx_ingress.conf
Labels: size/S

#8508 [PROTO-1824] Add country to csv download for sales
  packages/discovery-provider/src/queries/download_csv.py
Labels: size/XS

#9095 Fix UDR query result
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Labels: size/L

#9096 [C-4751, C-4746, C-4663] Add better validation for bpm inputs
  packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
Labels: size/M

#9097 [C-4666] Update skeleton counts for new search results
  packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
  packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
  packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
Labels: size/M

#9098 [C-4694] Add track_count to playlists query endpoint
  packages/discovery-provider/src/queries/query_helpers.py
Labels: size/XS

#9100 [C-4735, C-4678] Add popover and fix close icon for recent searches
  packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
Labels: size/S

#9084 Fixes issue where audius-query force was not respected
  packages/common/src/audius-query/createApi.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useBooleanOnce.ts
Labels: size/M

#9101 [C-4595] Fix addEntries call in asCache reducers
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/types.ts
  packages/common/src/store/cache/users/reducer.ts
Labels: size/M

#9104 [C-4747] Update track edit form to only display key and bpm field in the edit flow
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
Labels: size/M

#9105 [C-4733, C-4738] Update mobile profile, album, and playlist search results to have consistent background and scroll padding
  packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx
Labels: size/M

#9099 [C-4743] Update recent searches to display contextual items on web and mobile
  packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
Labels: size/M

#9108 Correct reserved handle
  packages/discovery-provider/ddl/migrations/0080_correct_reserved_handle.sql
Labels: size/S

#9058 [PAY-3130] Update most of LeftNav styling to match current conventions
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/components/layout/Box/types.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/GroupHeader.module.css
  packages/web/src/components/nav/desktop/GroupHeader.tsx
  packages/web/src/components/nav/desktop/LeftNav.module.css
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavDroppable.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.module.css
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/NavHeader.module.css
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.module.css
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.module.css
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistUpdateDot.tsx
  packages/web/src/components/nav/desktop/RouteNav.module.css
  packages/web/src/components/nav/desktop/RouteNav.tsx
Labels: size/XXL

#9111 Truncate skipped transactions table
  packages/discovery-provider/ddl/migrations/0081_truncate_skipped_transactions.sql
Labels: size/XS

#9110 Fix needsRecoveryEmail flag and add emails to sendgrid contacts
  packages/identity-service/src/app.js
  packages/identity-service/src/routes/recovery.js
  packages/identity-service/src/routes/welcomeEmail.js
Labels: size/M

#9090 Small email fixes: icons, layout, removing unsubscribe group
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts
  packages/identity-service/src/notifications/emails/downloadMobileApp.html
  packages/identity-service/src/notifications/emails/otp.js
  packages/identity-service/src/routes/recovery.js
  packages/identity-service/src/utils/otp.js
Labels: size/M

#9102 [C-4711] Hide play/repost stats for hidden content
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/web/src/components/collection/components/RepostsFavoritesStats.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
Labels: size/M

#9112 [C-4658] Add filter-button clear
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.mdx
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
Labels: size/L

#9106 [C-4725] Edit Collection Page QA
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/edit-collection/CollectionNavigationPrompt.tsx
  packages/web/src/components/edit-collection/EditCollectionForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/AnchoredSubmitRowEdit.tsx
  packages/web/src/components/form-fields/ArtworkField.tsx
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
Labels: size/M

#9116 Fix broken user tx hash
  packages/discovery-provider/ddl/migrations/0082_fix_user_tx_hash.sql
Labels: size/S

#9114 Nav to edit page instead of edit modal from track tile
  packages/web/src/components/track/OwnerActionButtons.tsx
Labels: size/S

#9113 [C-4714] Disallow share/add to playlist for hidden tracks
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/web/src/components/table/components/OverflowMenuButton.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/S

#9117 Fix Track more results page in search v1
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
Labels: size/M

#9115 [C-4667] Update recent search to sort on created_at field
  packages/discovery-provider/src/queries/search_es.py
Labels: size/XS

#9119 [C-4646] Fix stream_conditions optimistic update on track edit
  packages/common/src/store/cache/reducer.ts
Labels: size/XS

#9120 Allow gated content to be added to playlist
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/M

#9118 Fix misc component issues on startup
  packages/harmony/src/components/popup/Popup.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibraryNavItem.tsx
  packages/web/src/components/track/OwnerActionButtons.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
Labels: size/L

#9122 Fix web lint and permalink passing
  packages/web/src/components/track/OwnerActionButtons.tsx
Labels: size/XS

#9107 [PAY-3149] Edit track confirmation modal when listeners may lose access
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/edit-access-confirmation-modal/sagas.ts
  packages/common/src/store/ui/edit-access-confirmation-modal/selectors.ts
  packages/common/src/store/ui/edit-access-confirmation-modal/slice.ts
  packages/common/src/store/ui/edit-access-confirmation-modal/types.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/edit-access-confirmation-modal/EditAccessConfirmationModal.tsx
  packages/web/src/components/edit-access-confirmation-modal/index.ts
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#9124 Bump mobile apps to 107
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9121 Fix slow startup
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/libs/src/userStateManager.ts
  packages/web/src/common/store/account/sagas.js
Labels: size/M

#9125 [C-4771] Hide stats in TracksTable for hidden tracks
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/S

#9126 [C-4776] Fix edit collection submit
  packages/web/src/components/edit-collection/CollectionNavigationPrompt.tsx
Labels: size/XS

#9022 Update es-indexer readme, fix tests.
  packages/discovery-provider/integration_tests/queries/test_search_track_tags.py
  packages/discovery-provider/integration_tests/queries/test_search_user_tags.py
  packages/es-indexer/README.md
Labels: size/M

#9127 Filter out searchv2 history items for search v1
  packages/common/src/store/search/selectors.ts
Labels: size/XS

#9123 [PAY-3160] Try other tables for txhash if users table doesn't work.
  comms/DockerfileFast
  comms/discovery/pubkeystore/recover.go
Labels: size/M

#9077 clean up key/bpm repairer
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/M

#9129 img cache: check for empty bytes and add skipCache query param
  mediorum/server/serve_image.go
Labels: size/S

#9128 Fix MRI clm / udr s3 configs
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
Labels: size/L

#9131 Fix account playlists entering cache and caching of currentWeb3User
  packages/common/src/api/account.ts
  packages/common/src/audius-query/schema.ts
Labels: size/S

#9133 fix log error in analysis repairer
  packages/discovery-provider/src/tasks/repair_audio_analyses.py
Labels: size/XS

#9135 [C-4778, C-4786] Update visibility change confirmation
  packages/common/src/store/ui/edit-access-confirmation-modal/types.ts
  packages/web/src/components/edit-access-confirmation-modal/EditAccessConfirmationModal.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Labels: size/L

#9136 [C-4709] Fix modals on mobile-web
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XS

#9137 Fix offline mode after fast load change
  packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/backend/sagas.ts
Labels: size/M

#9132 drop old audio analyses ops
  mediorum/ddl/ddl.go
  mediorum/ddl/drop_audio_analysis_ops.sql
Labels: size/S

#9089 PROTO-1879: rm PUT /user/email route
  packages/identity-service/src/routes/user.js
Labels: size/M

#9141 Fix misc UDR bugs
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/csv.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/date.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
Labels: size/M

#9142 [C-4772] Update mobile filter buttons to respect filter value
  packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
  packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
  packages/mobile/src/screens/search-screen-v2/searchState.ts
Labels: size/M

#9143 [PAY-3164] Allow editing access for download-only gated tracks
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Labels: size/S

#9145 [C-4719] Fix local collections selector
  packages/common/src/store/cache/collections/selectors.ts
Labels: size/XS

#9144 Final touches to UDR
  packages/discovery-provider/plugins/pedalboard/apps/mri/README.md
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/date.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Labels: size/M

#9139 [C-4777] Prevent public track with future release date
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/L

#9134 [C-4668] Improve web search v2 perf and structure
  packages/common/src/api/search.ts
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
  packages/web/src/pages/MainContentContext.tsx
  packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
  packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
  packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
  packages/web/src/pages/search-page-v2/ResultsTracksView.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page-v2/search-results/AllResults.tsx
  packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
  packages/web/src/pages/search-page-v2/types.ts
  packages/web/src/pages/search-page-v2/utils.tsx
  packages/web/src/utils/route.ts
Labels: size/XXL

#9147 Cycle solana RPC connections better
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/trackListenInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
Labels: size/S

#9148 Specifiers should be strings in challenge notifs
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/XS

#9150 [C-4794] Hide social actions on now playing drawer for hidden tracks
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
Labels: size/L

#9149 [QA-1443] Remove faulty download all logic
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/S

#9154 [QA-1429] Fix avatar sizing
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
Labels: size/XS

#9151 Fix type error
  packages/common/src/api/search.ts
Labels: size/XS

#9152 [C-4796] Mobile Visibility Field
  packages/common/src/messages/edit.ts
  packages/common/src/messages/index.ts
  packages/mobile/package.json
  packages/mobile/src/components/core/DateTimeInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/harmony-native/components/Radio/Radio.tsx
  packages/mobile/src/harmony-native/components/Radio/RadioGroup.tsx
  packages/mobile/src/harmony-native/components/Radio/RadioGroupContext.ts
  packages/mobile/src/harmony-native/components/Radio/index.ts
  packages/mobile/src/harmony-native/components/Radio/useRadioGroup.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/components/ConfirmPublishDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/components/ExpandableRadio.tsx
  packages/mobile/src/screens/edit-track-screen/components/ExpandableRadioGroup.tsx
  packages/mobile/src/screens/edit-track-screen/fields/VisibilityField/VisibilityField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/VisibilityField/VisibilityScreen.tsx
  packages/mobile/src/screens/edit-track-screen/fields/VisibilityField/index.ts
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/form-screen/FormScreen.tsx
  packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
  packages/web/src/components/edit/fields/visibility/ScheduledReleaseDateField.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Labels: size/XL

#9109 [PAY-2783] Add filters to manager endpoints
  .changeset/smooth-crews-rush.md
  packages/commands/README.md
  packages/commands/src/account-managers.mjs
  packages/commands/src/index.mjs
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/tasks/entity_manager/entities/grant.py
  packages/libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/default/models/Playlist.ts
  packages/libs/src/sdk/api/generated/full/apis/SearchApi.ts
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
  packages/libs/src/sdk/api/grants/GrantsApi.ts
  packages/libs/src/sdk/api/grants/types.ts
Labels: size/XL

#9153 Add UTM tracking in amplitude
  packages/web/src/services/analytics/amplitude.ts
Labels: size/XS

#9156 [PAY-3148] Add better support for gated tracks in library
  packages/common/src/models/Analytics.ts
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/table/components/TablePlayButton.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/L

#9155 Include all save types in library collections endpoints
  packages/discovery-provider/src/queries/get_collection_library.py
Labels: size/S

#9161 [C-4789] Update web key and bpm filter buttons to respect the filter value
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Labels: size/L

#9162 [C-4671] Add clear search button
  packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/components/search/SearchBarV2.jsx
Labels: size/M

#9163 Fix usage of missing SDK function for Manager Mode reject flow
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ManagerModeSettingsModal.tsx
Labels: size/XS

#9159 [C-4805] Fix track filters
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Labels: size/S

#9164 [C-4788] Update filter button to fix toggle filter button functionality
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Labels: size/S

#9167 [C-4672] [C-4745] [C-4807] Advanced search UI qa fixes
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/types.ts
  packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/stats/Stats.module.css
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Labels: size/L

#9140 PROTO-1881: custom date for rewards bot
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/utils.ts
Labels: size/M

#9170 [C-4675] [C-4665] [C-4736] [C-4732] [C-4737] [C-4734] [C-4742] Advanced search UI qa fixes part 2
  packages/common/src/store/search/selectors.ts
  packages/mobile/src/components/user-list/UserCard.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/mobile/src/screens/search-screen-v2/SearchCatalogTile.tsx
  packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
Labels: size/M
