Repository AudiusProject/apps, pull requests merged in 2024-02, with the labels that each got.

#7404 Deprecate all non-harmony Avatar in native
  packages/common/src/utils/typeUtils.ts
  packages/harmony/src/foundations/index.ts
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/ProfilePicture.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/CoverPhoto.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/profile-list/ProfileCard.tsx
  packages/mobile/src/components/user/ProfilePicture.tsx
  packages/mobile/src/components/user/index.ts
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/FastImage/FastImage.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/utils/styleProps.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePicture.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePictureList.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePictureListSkeleton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/index.ts
  packages/mobile/src/screens/notifications-screen/Notifications/AddTrackToPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterAndSupportingNotificationContent.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/UserSubscriptionNotification.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/ReceiverDetails.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/XL

#7413 Fix native "MultiselectRemove" icons
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.tsx
  packages/mobile/src/screens/signon/CreatePassword.tsx
  packages/mobile/src/screens/signon/ProfileManual.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/M

#7405 User sagas to typescript
  packages/common/src/store/cache/actions.ts
  packages/common/src/utils/uid.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/sagas.ts
  packages/web/src/common/store/cache/users/sagas.d.ts
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/lineup/sagas.d.ts
  packages/web/src/common/store/pages/ai/sagas.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/L

#7415 Convert signon page sagas to ts
  packages/common/src/models/Analytics.ts
  packages/common/src/models/User.ts
  packages/common/src/models/UserEvent.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/XL

#7406 Fix duplicate unregistered SPs on healthz overview
  monitoring/healthz/src/useServiceProviders.ts
Labels: size/XS

#7418 track page sagas to typescript
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/pages/track/reducer.ts
  packages/common/src/store/pages/track/types.ts
  packages/web/src/common/store/pages/track/lineups/sagas.ts
  packages/web/src/common/store/pages/track/sagas.js
  packages/web/src/common/store/pages/track/sagas.ts
Labels: size/XL

#7426 Add orig_filename to track/stems endpoint
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#7427 Change index_user_bank log to info instead of error
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/XS

#7422 ONC-1: add metrics backfill
  packages/discovery-provider/ddl/migrations/0050_backfill_dashboard_metrics.sql
Labels: size/M

#7421 [PAY-2373][PAY-2406][PAY-2374] Support file sizes for stems / downloads
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/models/BlobInfo.ts
  packages/libs/src/sdk/api/generated/default/models/DecodedUserToken.ts
  packages/libs/src/sdk/api/generated/default/models/TopListener.ts
  packages/libs/src/sdk/api/generated/default/models/Track.ts
  packages/libs/src/sdk/api/generated/default/models/TrackInspect.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/XL

#7433 Convert trending page sagas to ts
  packages/common/src/store/pages/trending/types.ts
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.ts
  packages/web/src/common/store/pages/trending/sagas.ts
Labels: size/M

#7431 Convert history page sagas to ts
  packages/web/src/common/store/pages/history/lineups/sagas.ts
  packages/web/src/common/store/pages/history/sagas.ts
Labels: size/M

#7388 [PAY-2407][PAY-2441] Route withdraw transactions through user bank
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawModal.module.css
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawModal.tsx
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#7435 DDEX local dev
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.ddex.yml
  packages/ddex/.gitignore
  packages/ddex/README.md
  packages/ddex/ingester/.air.toml
  packages/ddex/ingester/.gitignore
  packages/ddex/ingester/README.md
  packages/ddex/ingester/go.mod
  packages/ddex/ingester/go.sum
  packages/ddex/publisher/README.md
  packages/ddex/publisher/src/index.ts
  packages/ddex/webapp/README.md
  packages/ddex/webapp/server/src/index.ts
Labels: size/L

#7436 [PROTO-1644] Healthz displays audius-d managed status and icon
  mediorum/server/serve_health.go
  mediorum/server/serve_health_test.go
  mediorum/server/server.go
  monitoring/healthz/src/images/audius_d.svg
  monitoring/healthz/src/pages/Nodes.tsx
  packages/discovery-provider/src/queries/get_health.py
  packages/trpc-server/Dockerfile
Labels: size/M

#7429 [PAY-2448] Exclude system USDC transactions by default
  packages/discovery-provider/integration_tests/queries/test_get_usdc_transactions_history.py
  packages/discovery-provider/src/api/v1/transactions.py
  packages/discovery-provider/src/queries/get_usdc_transactions_history.py
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/L

#7437 Fix mobile styles for pkey export
  packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterPage.tsx
Labels: size/S

#7417 Fix drawer icon sizing issue
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/DrawerHeader.tsx
Labels: size/S

#7423 Openresty cleanup
  packages/discovery-provider/nginx_conf/main.lua
  packages/discovery-provider/nginx_conf/nginx.conf
  packages/discovery-provider/nginx_conf/nginx_container.conf
  packages/discovery-provider/scripts/prod-server.sh
Labels: size/L

#7438 [PAY-2425] Fix DownloadRow text styles
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/S

#7428 Add stem orig_filename to tracks/<id>/stems
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
Labels: size/XS

#7439 Remove old cache track sagas js file
  packages/web/src/common/store/cache/tracks/sagas.js
Labels: size/L

#7445 Remove common command from root package.json
  package.json
Labels: size/XS

#7441 Fix copy icon color
  packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterPage.module.css
Labels: size/XS

#7420 Upgrade dapp-store cli
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/M

#7449 [ONC-7] Move to opensea api v2
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/models/OpenSea.ts
  packages/common/src/services/opensea-client/OpenSeaClient.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/mobile/src/env/env.dev.ts
  packages/mobile/src/env/env.prod.ts
  packages/mobile/src/env/env.stage.ts
  packages/web/src/common/store/pages/token-dashboard/getWalletInfo.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx
  packages/web/src/services/env/env.dev.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/XL

#7367 [Native] Fix OTP paste on mobile [C-3692]
  packages/mobile/src/screens/signon/SignOn.tsx
Labels: size/S

#7448 Fix cosign SVG fill color not using fill prop
  packages/harmony/src/assets/icons/Cosign.svg
Labels: size/XS

#7440 [C-3741] Fix sign up blocker when having no artists due to local stack
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/M

#7454 [PAY-2436] Add isOwner purchaseable downloads copy
  packages/common/src/hooks/useGatedContent.ts
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/M

#7446 [PAY-2404] Display correct file extensions when selecting download quality
  packages/common/src/utils/fileUtils.ts
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/M

#7452 DDEX indexer -> publisher talking
  packages/ddex/README.md
  packages/ddex/ingester/constants/constants.go
  packages/ddex/ingester/indexer/indexer.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/index.ts
  packages/ddex/publisher/src/models/parsed.ts
  packages/ddex/publisher/src/models/published.ts
  packages/ddex/publisher/src/services/publisherService.ts
Labels: size/L

#7456 Fix race condition when initting sdk in ddex
  packages/ddex/webapp/README.md
  packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx
Labels: size/L

#7385 [PAY-2329] Use download_conditions in purchase flow
  packages/common/src/hooks/purchaseContent/types.ts
  packages/common/src/hooks/purchaseContent/utils.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/L

#7455 [C-3607] Store & restore profile image and cover photo between new sign up pages
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
Labels: size/M

#7416 Migrate selectable pills to harmony
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/src/components/input/SelectablePill/types.ts
  packages/mobile/src/components/core/HarmonySelectablePill.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/types.ts
  packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectedGenresTabBar.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.module.css
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.stories.tsx
  packages/stems/src/components/SelectablePill/HarmonySelectablePill.tsx
  packages/stems/src/components/SelectablePill/index.ts
  packages/stems/src/components/SelectablePill/types.ts
  packages/stems/src/index.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedFilters.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingGenreFilters.module.css
  packages/web/src/pages/trending-page/components/desktop/TrendingGenreFilters.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
Labels: size/XL

#7327 Fix electric subgenre select-artist requests
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/XS

#7451 [C-3746] & [C-3745] Fix CoverPhoto and ProfileImage not showing correctly in native sign up
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/CoverPhoto/CoverPhoto.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/components/ImageField.tsx
Labels: size/M

#7447 [C-3665] - Prevent back on select genres page
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
Labels: size/XS

#7463 [INF-654] Fix mobile SSR render
  packages/web/src/components/search-bar/SearchBar.tsx
Labels: size/S

#7461 [C-3762] Unblock stage deploy by uploading sourcemaps to s3
  .circleci/src/commands/@web-commands.yml
  .circleci/src/jobs/@web-jobs.yml
  packages/web/vite.config.ts
Labels: size/S

#7465 [C-3764] Use history in handleClickRoute
  packages/web/src/components/search-bar/SearchBar.tsx
  packages/web/src/public-site/components/Footer.tsx
  packages/web/src/public-site/components/NavOverlay.tsx
  packages/web/src/public-site/components/handleClickRoute.ts
  packages/web/src/public-site/pages/landing-page/components/CTAGetStarted.tsx
  packages/web/src/public-site/pages/landing-page/components/CTAStartListening.tsx
  packages/web/src/public-site/pages/landing-page/components/CaseStudies.tsx
  packages/web/src/public-site/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/public-site/pages/landing-page/components/Hero.tsx
Labels: size/L

#7467 [C-3764] Use history in handleClickRoute pt 2
  packages/web/src/public-site/pages/landing-page/components/CTAGetStarted.tsx
Labels: size/XS

#7464 [C-3763] Restrict harmony imports in mobile
  packages/harmony/src/components/icon.ts
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/components/layout/Box/index.ts
  packages/harmony/src/components/layout/Box/types.ts
  packages/harmony/src/components/layout/Flex/index.ts
  packages/harmony/src/components/layout/Flex/types.ts
  packages/harmony/src/components/layout/Paper/types.ts
  packages/harmony/src/components/text/Text/Text.tsx
  packages/harmony/src/components/text/Text/types.ts
  packages/mobile/.eslintrc.js
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/drawer/DrawerHeader.tsx
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/types.ts
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/Button/types.ts
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.stories.tsx
  packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.tsx
  packages/mobile/src/harmony-native/components/CoverPhoto/CoverPhoto.tsx
  packages/mobile/src/harmony-native/components/Hint/Hint.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/types.ts
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/types.ts
  packages/mobile/src/harmony-native/components/layout/Box/types.ts
  packages/mobile/src/harmony-native/components/layout/Flex/types.ts
  packages/mobile/src/harmony-native/components/layout/Paper/types.ts
  packages/mobile/src/harmony-native/foundations/color/color.ts
  packages/mobile/src/harmony-native/foundations/index.ts
  packages/mobile/src/harmony-native/foundations/theme/ThemeProvider.tsx
  packages/mobile/src/harmony-native/foundations/theme/theme.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/harmony-native/utils/styleProps.ts
  packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
  packages/mobile/tsconfig.json
Labels: size/L

#7468 [Harmony] [Web] Fix red icons and playback icons [C-3765]
  packages/harmony/src/assets/icons/PlaybackPause.svg
  packages/harmony/src/assets/icons/PlaybackPlay.svg
  packages/harmony/src/icons/UtilityIcons.stories.mdx
  packages/web/src/components/image-selection/ImageSelectionPopup.jsx
  packages/web/src/components/image-selection/ImageSelectionPopup.module.css
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.module.css
  packages/web/src/components/notification/Notification/components/icons.tsx
  packages/web/src/components/upload/PreviewButton.jsx
  packages/web/src/pages/dashboard-page/components/TracksTableContainer.tsx
  packages/web/src/pages/profile-page/components/EditableName.jsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
  packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
  packages/web/src/pages/visualizer/VisualizerProvider.module.css
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
Labels: size/L

#7470 DDEX crawler
  dev-tools/compose/docker-compose.ddex.yml
  packages/ddex/.env.dev
  packages/ddex/.env.stage
  packages/ddex/README.md
  packages/ddex/ingester/.air.toml
  packages/ddex/ingester/README.md
  packages/ddex/ingester/cmd/main.go
  packages/ddex/ingester/common/common.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/go.mod
  packages/ddex/ingester/go.sum
  packages/ddex/ingester/indexer/indexer.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/.env.stage
  packages/ddex/publisher/README.md
  packages/ddex/publisher/package.json
  packages/ddex/publisher/src/index.ts
  packages/ddex/webapp/README.md
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
  packages/ddex/webapp/server/.env.dev
  packages/ddex/webapp/server/package.json
  packages/ddex/webapp/server/src/app.ts
  packages/ddex/webapp/server/src/index.ts
  packages/ddex/webapp/server/src/services/dbService.ts
  packages/ddex/webapp/server/src/services/s3.ts
Labels: size/XL

#7469 [PAY-2408][PAY-2443][PAY-2397] Bring web purchase up to lossless spec
  packages/common/src/hooks/purchaseContent/types.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
  packages/web/src/components/summary-table/SummaryTable.tsx
  packages/web/src/components/track/LockedTrackDetailsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Labels: size/L

#7462 fix audius-cmd && replicate relay locally
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/nginx_ingress.conf
  dev-tools/startup/discovery-provider.sh
  packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.dev
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/discovery-provider/plugins/pedalboard/docker/startup.sh
  packages/discovery-provider/src/queries/get_health.py
Labels: size/M

#7474 Fix SSR deploy cache
  .circleci/src/jobs/@web-jobs.yml
  packages/web/turbo.json
Labels: size/S

#7473 Enable SSR
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#7479 fix ddex ingester CI
  dev-tools/compose/docker-compose.ddex.yml
Labels: size/S

#7482 Delete broken or unused release/publish workflows
  .circleci/src/jobs/@root-jobs.yml
  .circleci/src/jobs/release-github-draft.yml
  .circleci/src/jobs/release-github.yml
  .circleci/src/workflows/release.yml
  .circleci/src/workflows/root.yml
  monitoring/healthz/README.md
Labels: size/L

#7485 Update crawler regex to include all crawlers
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#7476 Improve user search on exact matches
  packages/discovery-provider/src/queries/search_es.py
Labels: size/S

#7486 [PROTO-1621] Implement ddex indexer
  packages/ddex/README.md
  packages/ddex/ingester/cmd/main.go
  packages/ddex/ingester/common/common.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/go.mod
  packages/ddex/ingester/go.sum
  packages/ddex/ingester/indexer/indexer.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/webapp/client/.env.dev
  packages/ddex/webapp/client/src/pages/Upload/Upload.tsx
  packages/ddex/webapp/client/src/providers/EnvVarsProvider.tsx
  packages/ddex/webapp/server/src/app.ts
Labels: size/L

#7478 [PAY-2444] Title case stems
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/web/src/components/track/DownloadRow.tsx
Labels: size/S

#7480 [PAY-2353] Adds offramp analytics
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/models/Analytics.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#7492 [PAY-2457] Fix bad conditional for showing transaction link
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Labels: size/XS

#7471 [PAY-2365] Update logic to access nft gated tracks
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/gated-content/slice.ts
  packages/discovery-provider/integration_tests/queries/test_get_usdc_transactions_history.py
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
  packages/discovery-provider/src/queries/get_nft_gated_track_signatures.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/L

#7495 Fix search personalization in client
  packages/common/src/services/audius-api-client/helper.ts
Labels: size/M

#7477 [DVRL-7] - update frontmatter and switch to manual sidebars
  docs/docs/developers/_category_.json
  docs/docs/developers/advanced-options.mdx
  docs/docs/developers/hedgehog.mdx
  docs/docs/developers/log-in-with-audius.mdx
  docs/docs/developers/rest-api.mdx
  docs/docs/developers/sdk-oauth-methods.mdx
  docs/docs/developers/sdk/_category_.yml
  docs/docs/developers/sdk/albums.mdx
  docs/docs/developers/sdk/playlists.mdx
  docs/docs/developers/sdk/resolve.mdx
  docs/docs/developers/sdk/sdk.mdx
  docs/docs/developers/sdk/tracks.mdx
  docs/docs/developers/sdk/users.mdx
  docs/docs/developers/subgraph/data.mdx
  docs/docs/developers/subgraph/entities.mdx
  docs/docs/developers/subgraph/queries.mdx
  docs/docs/developers/upload-track-metadata.mdx
  docs/docs/protocol/_category_.json
  docs/docs/protocol/content-node/_category_.json
  docs/docs/protocol/content-node/architecture.mdx
  docs/docs/protocol/content-node/overview.mdx
  docs/docs/protocol/discovery-node/_category_.json
  docs/docs/protocol/discovery-node/architecture.mdx
  docs/docs/protocol/discovery-node/overview.mdx
  docs/docs/protocol/protocol.mdx
  docs/docs/protocol/whitepaper.mdx
  docs/docs/token/_category_.json
  docs/docs/token/governance.mdx
  docs/docs/token/running-a-node/_category_.json
  docs/docs/token/running-a-node/hardware-requirements.mdx
  docs/docs/token/running-a-node/introduction.mdx
  docs/docs/token/running-a-node/setup/_category_.json
  docs/docs/token/running-a-node/setup/advanced.mdx
  docs/docs/token/running-a-node/setup/claiming.mdx
  docs/docs/token/running-a-node/setup/installation.mdx
  docs/docs/token/running-a-node/setup/registration.mdx
  docs/docs/token/running-a-node/setup/wallet-management.mdx
  docs/docs/token/running-a-node/sla.mdx
  docs/docs/token/staking.mdx
  docs/docs/token/token.mdx
  docs/docs/welcome.mdx
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/pages/index.js
  docs/src/pages/index.module.css
Labels: size/XL

#7491 Add correct type to manual transfer confirmation switch field
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
Labels: size/XS

#7493 Miscellaneous data fetching fixes for Pay and Earn page
  packages/common/src/api/purchases.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/S

#7483 [PAY-2415][PAY-2417][PAY-2419][PAY-2420][PAY-2437] Fix lossless issues
  packages/common/src/models/Stems.ts
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/upload/TrackPreviewNew.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.module.css
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/types.ts
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/store/utils/stems.ts
  packages/web/src/pages/upload-page/validation.ts
  packages/web/src/store/application/ui/stemsUpload/sagas.ts
Labels: size/L

#7497 Fix tag search navigating on web
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Labels: size/S

#7496 Integrate ddex into CI auto-upgrade
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
  .circleci/src/workflows/ddex-stage.yml
Labels: size/M

#7499 Remove stems segmented-conrol, fix description
  packages/harmony/src/components/segmented-control/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.module.css
  packages/stems/src/components/SegmentedControl/SegmentedControl.stories.tsx
  packages/stems/src/components/SegmentedControl/SegmentedControl.tsx
  packages/stems/src/components/SegmentedControl/index.ts
  packages/stems/src/components/SegmentedControl/types.ts
Labels: size/L

#7484 [Web] Fix upload button icon color and dropdown input caret size [C-3771]
  packages/web/src/components/artist-recommendations/ArtistRecommendations.module.css
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/data-entry/DropdownInput.jsx
  packages/web/src/components/data-entry/DropdownInput.module.css
  packages/web/src/components/nav/desktop/NavButton.module.css
Labels: size/S

#7501 Revert "Disable usdc bank split in dev mode (#6300)"
  packages/web/src/common/store/upload/sagaHelpers.ts
Labels: size/S

#7502 [PAY-2461] Create track_price_history row for download-gated-only tracks
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#7503 [ONC-10] Fix styles for ArtistRecommendations pictures
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
Labels: size/XS

#7487 [C-3773] Migrate radio from stems to harmony
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/src/components/input/SelectablePill/types.ts
  packages/harmony/src/components/radio-group/RadioGroup.tsx
  packages/harmony/src/components/radio-group/RadioGroupContext.ts
  packages/harmony/src/components/radio-group/index.ts
  packages/harmony/src/components/radio-group/useRadioGroup.ts
  packages/harmony/src/components/radio/Radio.stories.tsx
  packages/harmony/src/components/radio/Radio.tsx
  packages/harmony/src/components/radio/index.ts
  packages/stems/src/components/PillButton/PillButton.tsx
  packages/stems/src/components/RadioButton/RadioButton.module.css
  packages/stems/src/components/RadioButton/RadioButton.stories.tsx
  packages/stems/src/components/RadioButton/RadioButton.tsx
  packages/stems/src/components/RadioButton/index.ts
  packages/stems/src/components/RadioButtonGroup/RadioButtonGroup.stories.tsx
  packages/stems/src/components/RadioPillButton/RadioPillButton.module.css
  packages/stems/src/components/RadioPillButton/RadioPillButton.stories.tsx
  packages/stems/src/components/RadioPillButton/RadioPillButton.tsx
  packages/stems/src/components/RadioPillButton/index.ts
  packages/stems/src/index.ts
  packages/stems/tsconfig.json
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.module.css
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/SpecialAccessFields.tsx
Labels: size/XL

#7500 Migrate token-amount-input to harmony
  packages/harmony/src/components/input/TokenAmountInput/TokenAmountInput.stories.tsx
  packages/harmony/src/components/input/TokenAmountInput/TokenAmountInput.tsx
  packages/harmony/src/components/input/TokenAmountInput/index.ts
  packages/harmony/src/components/input/TokenAmountInput/types.ts
  packages/harmony/src/components/input/index.ts
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.module.css
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.stories.tsx
  packages/stems/src/components/TokenAmountInput/TokenAmountInput.tsx
  packages/stems/src/components/TokenAmountInput/types.ts
  packages/stems/src/components/TokenValueInput/TokenValueInput.module.css
  packages/stems/src/components/TokenValueInput/TokenValueInput.tsx
  packages/stems/src/components/TokenValueInput/index.ts
  packages/stems/src/components/TokenValueInput/types.ts
  packages/stems/src/index.ts
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.module.css
  packages/web/src/pages/audio-rewards-page/components/SendInputBody.tsx
Labels: size/XL

#7498 [DVRL-9] - upgrade docusaurus to v3.1.1 and add mermaid diagrams
  docs/docs/developers/log-in-with-audius.mdx
  docs/docs/developers/sdk/playlists.mdx
  docs/docs/protocol/protocol.mdx
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
  docs/static/img/architecture.png
Labels: size/L

#7509 Update DN README.md for testing
  packages/discovery-provider/README.md
Labels: size/XS

#7511 [C-3780] Fix track history api call
  packages/web/src/common/store/pages/history/lineups/sagas.ts
Labels: size/XS

#7506 Misc DDEX cleanup + publisher sets delivery status
  dev-tools/compose/docker-compose.ddex.yml
  packages/ddex/README.md
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/constants/constants.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/indexer/indexer.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/index.ts
  packages/ddex/publisher/src/models/indexed.ts
  packages/ddex/publisher/src/models/parsed.ts
  packages/ddex/publisher/src/models/published.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/ddex/webapp/client/src/components/Collection/Collection.module.css
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
  packages/ddex/webapp/client/src/pages/Upload/Upload.tsx
  packages/ddex/webapp/server/src/controllers/collectionController.ts
  packages/ddex/webapp/server/src/routers/collectionRouters.ts
Labels: size/L

#7512 [PAY-2432][PAY-2462] Cancellable downloads
  packages/common/src/services/track-download/TrackDownload.ts
  packages/common/src/store/social/tracks/actions.ts
  packages/common/src/store/ui/modals/wait-for-download-modal/index.ts
  packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/services/track-download.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
  packages/web/src/services/track-download.ts
Labels: size/L

#7507 [PAY-2423] Render download options in equal-sized tabs
  packages/harmony/src/components/segmented-control/SegmentedControl.mdx
  packages/harmony/src/components/segmented-control/SegmentedControl.module.css
  packages/harmony/src/components/segmented-control/SegmentedControl.stories.tsx
  packages/harmony/src/components/segmented-control/SegmentedControl.tsx
  packages/harmony/src/components/segmented-control/types.ts
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/M

#7481 [DVRL-8] - adding code workspace file and plugin configs
  docs/.prettierrc
  docs/.vscode/extensions.json
  docs/.vscode/settings.json
  docs/.vscode/spellright.dict
  docs/docs.code-workspace
Labels: size/M

#7508 [PAY-2434][PAY-2427] Fix miscellaneous lossless issues
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/store/stems-upload/selectors.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/stem-files-modal/StemFilesModal.module.css
  packages/web/src/components/stem-files-modal/StemFilesModal.tsx
  packages/web/src/components/track/DownloadRow.module.css
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
Labels: size/L

#7518 Fix parser
  packages/discovery-provider/src/api/v1/tracks.py
Labels: size/XS

#7517 openresty config
  packages/discovery-provider/nginx_conf/main.lua
Labels: size/XS

#7519 [ONC-15] Fix artist dashboard plays bucketing
  packages/web/.gitignore
  packages/web/src/pages/dashboard-page/store/sagas.ts
Labels: size/XS

#7393 [PAY-2405] Add missing orig file cid and file name migration
  packages/discovery-provider/ddl/migrations/0052_update_non_existing_orig_filenames.sql
Labels: size/M

#7516 More DDEX cleanup
  packages/ddex/README.md
  packages/ddex/ingester/cmd/main.go
  packages/ddex/ingester/common/common.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/indexer/indexer.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/README.md
  packages/ddex/publisher/src/models/deliveries.ts
  packages/ddex/publisher/src/models/parsed.ts
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/models/published.ts
  packages/ddex/publisher/src/models/publishedReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/ddex/webapp/README.md
  packages/ddex/webapp/client/src/components/App.tsx
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
  packages/ddex/webapp/client/src/components/Sidebar.tsx
  packages/ddex/webapp/client/src/pages/Deliveries.tsx
  packages/ddex/webapp/client/src/pages/PendingReleases.tsx
  packages/ddex/webapp/client/src/pages/PublishedReleases.tsx
  packages/ddex/webapp/server/src/controllers/collectionController.ts
  packages/ddex/webapp/server/src/index.ts
  packages/ddex/webapp/server/src/routers/index.ts
Labels: size/L

#7282 [C-3644] Fix sign-up tests
  package.json
  packages/harmony/src/components/input/PasswordInput/PasswordInput.tsx
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/src/components/input/TextInput/TextInput.module.css
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/probers/cypress/e2e/signIn.cy.ts
  packages/probers/cypress/e2e/signInLegacy.cy.ts
  packages/probers/cypress/e2e/signUp.cy.ts
  packages/probers/cypress/e2e/signUpLegacy.ts
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/L

#7525 Fix Withdrawal flow errors due to slippage calculations
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/index.ts
  packages/common/src/services/remote-config/types.ts
  packages/common/src/store/ui/withdraw-usdc/slice.ts
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawModal.tsx
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/L

#7527 Skip jupiter tx in user bank withdrawal indexing
  packages/discovery-provider/src/solana/solana_helpers.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/XS

#7515 [Web] Fix more icon issues after Harmony migration C-3789
  packages/web/src/components/actions-tab/ActionsTab.module.css
  packages/web/src/components/banner/Banner.module.css
  packages/web/src/components/banner/CallToActionBanner.module.css
  packages/web/src/components/card/desktop/Card.module.css
  packages/web/src/components/create-playlist/CreatePlaylistButton.module.css
  packages/web/src/components/delineator/Delineator.module.css
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/more/More.module.css
  packages/web/src/components/nav/desktop/RouteNav.module.css
  packages/web/src/components/navigation/Dropdown.module.css
  packages/web/src/components/notification/Notification/components/icons.module.css
  packages/web/src/components/notification/NotificationModal.module.css
  packages/web/src/components/pill/Pill.module.css
  packages/web/src/components/search/SearchBar.jsx
  packages/web/src/components/search/SearchBar.module.css
  packages/web/src/components/share-modal/components/ShareDrawer.module.css
  packages/web/src/components/table/components/OverflowMenuButton.module.css
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/track/TrackInfo.module.css
  packages/web/src/components/track/mobile/TrackListItem.module.css
  packages/web/src/components/upload/PreviewButton.jsx
  packages/web/src/pages/audio-rewards-page/components/ExplainerTile.module.css
  packages/web/src/pages/dashboard-page/components/AchievementTile.module.css
  packages/web/src/pages/history-page/components/desktop/HistoryPage.module.css
  packages/web/src/pages/profile-page/components/EditableName.module.css
  packages/web/src/pages/sign-on/components/desktop/FollowPage.module.css
  packages/web/src/pages/sign-on/components/mobile/FollowPage.module.css
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
Labels: size/L

#7528 [PAY-2426] Fix native harmony text and buttons
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Labels: size/S

#7522 [PAY-2477] Remove blue background from purchased in download section
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
Labels: size/XS

#7523 [PAY-2466] Update banner copy in purchase flow
  packages/mobile/src/components/premium-track-purchase-drawer/AudioMatchSection.tsx
  packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.tsx
Labels: size/XS

#7524 [PAY-2473] Change 'original' copy to 'lossless' in download section
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/XS

#7532 Fix red icons + badge hover color in popup menu [C-3799] [C-3798]
  packages/web/src/components/nav/desktop/NavPopupMenu.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.module.css
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
Labels: size/S

#7533 [Web] Fix some weird arrow sizes [C-3801]
  packages/web/src/pages/audio-rewards-page/components/modals/TrendingRewards.tsx
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/S

#7531 [C-3783, C-3778] Fix collection screen messages
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
Labels: size/M

#7534 [C-3748] Address harmony callouts
  packages/stems/src/components/Modal/ModalHeader.module.css
  svgr-template.js
Labels: size/S

#7535 [C-3775] Fix co-sign placement
  packages/mobile/src/components/co-sign/CoSign.tsx
Labels: size/XS

#7475 run pg_migrate.sh test in CI
  dev-tools/compose/docker-compose.test.yml
  packages/discovery-provider/ddl/README.md
  packages/discovery-provider/ddl/docker-compose.yml
  packages/discovery-provider/ddl/local-test.sh
  packages/discovery-provider/ddl/migrations/0024_user_count_idx.sql
  packages/discovery-provider/ddl/migrations/0031_drop_current_indices_failable.sql
  packages/discovery-provider/ddl/migrations/0039_migrate_date_failable.sql
  packages/discovery-provider/ddl/migrations/0047_ix_plays_user_item_date.sql
  packages/discovery-provider/ddl/migrations/0047_update_track_metadata_columns_failable.sql
  packages/discovery-provider/ddl/pg_migrate.sh
  packages/discovery-provider/scripts/test-migrations.sh
Labels: size/M

#7529 force reselection on relay 500s
  packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  packages/libs/src/services/web3Manager/Web3Manager.ts
Labels: size/S

#7536 [C-3786, C-3787] Fix album link casing; Fix required artwork
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
  packages/web/src/pages/upload-page/validation.ts
Labels: size/M

#7541 [DVRL-14] - Integrate Google Analytics in Docs
  docs/docusaurus.config.js
  docs/package-lock.json
  docs/package.json
Labels: size/XS

#7542 update timings and set dryrun to false on cron
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
Labels: size/XS

#7526 [PAY-2464] Add access to purchases + sales endpoints
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/models/Purchase.ts
  packages/libs/src/sdk/api/generated/full/models/StemFull.ts
Labels: size/S

#7544 Fix lint
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/M

#7538 [PROTO-1622] Implement core parsing for DDEX ERN v3 releases
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/go.mod
  packages/ddex/ingester/go.sum
  packages/ddex/ingester/parser/parser.go
  packages/ddex/ingester/parser/sony_parser.go
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
Labels: size/XXL

#7546 [C-3802] Match Avatar styles more closely to prod
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
Labels: size/S

#7547 [PAY-2430][PAY-2433] Fix android download logic
  packages/mobile/src/services/track-download.ts
Labels: size/M

#7555 Patch trpc batching
  package.json
  packages/web/src/app/TrpcProvider.tsx
  patches/@trpc+client+10.38.4.patch
Labels: size/M

#7554 [PAY-2484] Ensure temporary download files are always deleted
  packages/mobile/src/services/track-download.ts
Labels: size/M

#7548 [PAY-2482] Purchase details modal downloadable content UI
  packages/common/src/api/purchases.ts
  packages/common/src/models/USDCTransactions.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx
Labels: size/M

#7559 [PAY-2469] Always show file size for downloadable files
  packages/web/src/components/track/DownloadRow.tsx
Labels: size/S

#7537 Improve Connect MetaMask UX, esp. when both MetaMask and Phantom are installed [C-3750]
  protocol-dashboard/src/components/AppBar/AppBar.module.css
  protocol-dashboard/src/components/AppBar/AppBar.tsx
  protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.module.css
  protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.tsx
  protocol-dashboard/src/services/Audius/AudiusClient.ts
  protocol-dashboard/src/services/Audius/helpers.ts
  protocol-dashboard/src/services/Audius/setup.ts
Labels: size/L

#7561 [PAY-2414] Remove manual mime type specification for Android downloads
  packages/mobile/src/services/track-download.ts
Labels: size/XS

#7564 [PAY-2486] Change Email: Copy changes and current email screen on mobile
  packages/mobile/src/screens/change-email-screen/SubScreens.tsx
  packages/web/src/components/change-email/ChangeEmailModal.tsx
Labels: size/S

#7560 [C-3804 C-3794] Fix native icon colors and size
  packages/harmony/src/foundations/color/semantic.ts
  packages/mobile/src/components/core/IconButton.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/mobile/src/components/now-playing-drawer/PlaybackRateButton.tsx
  packages/mobile/src/components/suggested-tracks/components/SuggestedTracks.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/types.ts
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
  packages/mobile/src/screens/app-screen/TopBarIconButton.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/search-screen/SearchBar.tsx
  packages/mobile/src/screens/search-screen/SearchHistory/SearchHistoryListItem.tsx
  packages/mobile/src/screens/signon/SignupHeader.tsx
  packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallet.tsx
Labels: size/XL

#7521 Upgrade native for full release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7565 Fix native handle field floating on the wrong side
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Labels: size/XS

#7267 [C-3561] Improve playback delay when playing track on mobile
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/L

#7566 [C-3659] Float continue button above keyboard on native OTP
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
Labels: size/M

#7567 [C-3666] Add autocomplete fields to new sign up/sign in fields
  packages/mobile/src/screens/sign-on-screen/components/EmailField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/mobile/src/screens/signon/CreatePassword.tsx
Labels: size/S

#7568 Don't render InputAccessoryView on non-iOS platforms
  packages/mobile/src/harmony-native/components/input/TextInput/TextInputAccessoryView.tsx
Labels: size/XS

#7571 [PAY-2472] Make USDCManualTransfer modal buy button actually buy
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Labels: size/S

#7574 Remove extra horizontal padding from SegmentedControl tabs
  packages/harmony/src/components/segmented-control/SegmentedControl.module.css
Labels: size/XS

#7453 Convert saved lineup sagas to ts
  packages/web/src/common/store/pages/saved/lineups/sagas.ts
Labels: size/L

#7575 [C-3769] Fix where condition for aggregate_user query.
  packages/discovery-provider/src/tasks/update_aggregates.py
Labels: size/XS

#7563 [PAY-2468] Dedup filenames during download
  packages/common/src/utils/fileUtils.ts
  packages/mobile/src/services/track-download.ts
  packages/web/src/services/track-download.ts
Labels: size/S

#7573 [PAY-2478] Add overshoot clamping to drawer close
  packages/mobile/src/components/drawer/Drawer.tsx
Labels: size/XS

#7570 [PAY-2465] Fix contextual menu stems
  packages/mobile/src/components/core/ContextualMenu.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx
Labels: size/S

#7577 Rewrite USDCCard in harmony-native to fix android text
  packages/mobile/src/components/core/AddressTile.tsx
  packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx
  packages/web/src/common/store/lineup/sagas.ts
Labels: size/L

#7549 [DVRL-15] - Connect Audius Account To Protocol Dashboard With MetaMask Guide
  docs/docs/protocol/link-audius-account-to-protocol-dashboard.mdx
  docs/sidebars.js
  docs/static/img/dashboard-account/audius-profile-linked.png
  docs/static/img/dashboard-account/authorize-app.png
  docs/static/img/dashboard-account/connect-audius-metamask.png
  docs/static/img/dashboard-account/connect-audius-profile-button.png
  docs/static/img/dashboard-account/connect-metamask-button.png
  docs/static/img/dashboard-account/connect-profile-modal.png
  docs/static/img/dashboard-account/metamask-account-picker.png
  docs/static/img/dashboard-account/metamask-linked.png
  docs/static/img/dashboard-account/not-linked.png
Labels: size/M

#7578 Fix action-button alignment
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Labels: size/XS

#7584 Fix spacing in Token docs
  docs/docs/token/token.mdx
Labels: size/XS

#7586 [ONC-20] Fix sign on page saga for fetching suggested artists
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/XS

#7587 Add time limit for payment router
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/XS

#7588 Fix edit/delete track sagas
  packages/web/src/common/store/cache/tracks/sagas.ts
Labels: size/S

#7589 Patch decimal return type serialization
  packages/discovery-provider/src/queries/get_remixable_tracks.py
  packages/discovery-provider/src/queries/get_top_playlists.py
Labels: size/XS

#7572 Fix ddex indexer excluding nested resources
  packages/ddex/ingester/indexer/indexer.go
Labels: size/M

#7581 Relax timeout for re-doing transcode
  mediorum/server/transcode.go
  mediorum/server/upload_client.go
Labels: size/S

#7585 [C-3732] Update tiktok oauth calls in identity-service to v2
  packages/identity-service/src/routes/tiktok.js
Labels: size/M

#7530 [DVRL-5.1] - multisig node registration walkthrough
  docs/.vscode/spellright.dict
  docs/docs/token/running-a-node/setup/multi-sig-registration.mdx
  docs/sidebars.js
  docs/src/css/custom.css
  docs/static/img/multisig-wallet/register-node/create/create-new-safe.png
  docs/static/img/multisig-wallet/register-node/create/create-signers.png
  docs/static/img/multisig-wallet/register-node/create/create-threshold.png
  docs/static/img/multisig-wallet/register-node/sign/last-signer-confirm.png
  docs/static/img/multisig-wallet/register-node/sign/pending-transactions.png
  docs/static/img/multisig-wallet/register-node/sign/sign-first.png
  docs/static/img/multisig-wallet/register-node/sign/successful-transaction.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-batch-send.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-builder-approve.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-builder-create-batch.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-builder-register.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-builder-simulate.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-builder.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-new.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-safe-address.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-safe-balance.png
  docs/static/img/multisig-wallet/register-node/transaction-builder/transact-unit-converter.png
  docs/static/img/protocol-dashboard/protocol-dashboard.png
  docs/static/img/protocol-dashboard/tikilabs-dashboard.png
Labels: size/XXL

#7583 [PAY-2485][PAY-2483] Adds download Retry behavior for mobile
  packages/common/src/store/downloads/index.ts
  packages/common/src/store/downloads/selectors.ts
  packages/common/src/store/downloads/slice.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx
  packages/mobile/src/harmony-native/components/Hint/Hint.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/download/selectors.ts
  packages/mobile/src/store/store.ts
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.module.css
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
  packages/web/src/services/track-download.ts
Labels: size/L

#7592 Fix follow-gated download row on web
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
Labels: size/S

#7594 [Web] Fix red icon kebab horizontal icon [C-3829]
  packages/web/src/components/track/desktop/TrackListItem.module.css
  packages/web/src/components/track/desktop/TrackListItem.tsx
Labels: size/XS

#7582 Bypass errors on health check for autoheal
  packages/discovery-provider/Dockerfile.prod
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/queries/health_check.py
Labels: size/XS

#7539 rework relay selection
  packages/libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  packages/libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/libs/src/services/web3Manager/Web3Manager.ts
Labels: size/L

#7576 [C-3811] Migrate popup to harmony
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/layout/Popup/Popup.module.css
  packages/harmony/src/components/layout/Popup/Popup.tsx
  packages/harmony/src/components/layout/Popup/index.ts
  packages/harmony/src/components/layout/Popup/types.ts
  packages/harmony/src/components/popup-menu/PopupMenu.module.css
  packages/harmony/src/components/popup-menu/PopupMenu.tsx
  packages/harmony/src/components/popup-menu/index.ts
  packages/harmony/src/components/popup-menu/types.tsx
  packages/stems/src/components/Popup/Popup.module.css
  packages/stems/src/components/Popup/Popup.stories.tsx
  packages/stems/src/components/Popup/Popup.tsx
  packages/stems/src/components/Popup/index.ts
  packages/stems/src/components/Popup/types.ts
  packages/stems/src/components/PopupMenu/PopupMenu.module.css
  packages/stems/src/components/PopupMenu/PopupMenu.stories.tsx
  packages/stems/src/index.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.module.css
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/image-selection/ImageSelectionPopup.jsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/menu/Menu.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/nav-banner/NavBanner.jsx
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/notification/NotificationPanel.module.css
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/play-bar/playback-rate-button/PlaybackRateButton.tsx
  packages/web/src/components/popup-menu-icon-button/PopupMenuIconButton.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/upload/UploadChip.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.module.css
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/public-site/PublicSite.tsx
  packages/web/src/public-site/components/NavBanner.module.css
  packages/web/src/public-site/components/NavBanner.tsx
Labels: size/XXL

#7569 ⚠️ [ONC-19] Error on failed gas estimation
  packages/discovery-provider/src/utils/multi_provider.py
  packages/libs/src/services/ethWeb3Manager/EthWeb3Manager.ts
  packages/libs/src/utils/estimateGas.ts
  packages/libs/src/utils/multiProvider.ts
  protocol-dashboard/src/components/ConfirmTransactionModal/ConfirmTransactionModal.tsx
  protocol-dashboard/src/components/TransactionStatus/TransactionStatus.tsx
  protocol-dashboard/src/store/actions/cancelTransaction.ts
  protocol-dashboard/src/store/actions/submitTransaction.ts
Labels: size/M

#7593 [PROTO-1664] Replicate transcode result in parallel
  mediorum/Dockerfile.unittests
  mediorum/server/replicate.go
  mediorum/server/serve_crud.go
  mediorum/server/serve_upload_test.go
  mediorum/server/test_main_test.go
  mediorum/server/testdata/beep.wav
  mediorum/server/transcode.go
  mediorum/server/upload_client.go
Labels: size/L
