Repository AudiusProject/apps, pull requests merged in 2024-03, with the labels that each got.

#7514 useHarmonyField
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useChangePasswordFormConfiguration.ts
  packages/common/src/hooks/useHarmonyField.ts
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/web/src/components/change-password/ChangePasswordModal.tsx
Labels: size/L

#7756 Add verifier checks to discovery relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
Labels: size/S

#7724 [C-2928] Add auth request signing middleware to sdk
  packages/common/src/api/library.ts
  packages/common/src/api/purchases.ts
  packages/common/src/api/user.ts
  packages/common/src/services/explore/Explore.ts
  packages/common/src/services/sdk/storageNodeSelector.ts
  packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx
  packages/libs/src/sdk/api/albums/AlbumsApi.test.ts
  packages/libs/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/libs/src/sdk/api/tracks/TracksApi.test.ts
  packages/libs/src/sdk/api/users/UsersApi.test.ts
  packages/libs/src/sdk/examples/README.md
  packages/libs/src/sdk/examples/signed-request/index.ts
  packages/libs/src/sdk/examples/signed-request/package-lock.json
  packages/libs/src/sdk/examples/signed-request/package.json
  packages/libs/src/sdk/examples/signed-request/tsconfig.json
  packages/libs/src/sdk/index.ts
  packages/libs/src/sdk/middleware/addAppNameMiddleware.ts
  packages/libs/src/sdk/middleware/addRequestSignatureMiddleware.test.ts
  packages/libs/src/sdk/middleware/addRequestSignatureMiddleware.ts
  packages/libs/src/sdk/middleware/index.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/Auth/AppAuth.ts
  packages/libs/src/sdk/services/Auth/Auth.ts
  packages/libs/src/sdk/services/Auth/DefaultAuth.ts
  packages/libs/src/sdk/services/Auth/UserAuth.ts
  packages/libs/src/sdk/services/Auth/constants.ts
  packages/libs/src/sdk/services/Auth/index.ts
  packages/libs/src/sdk/services/Auth/types.ts
  packages/libs/src/sdk/services/StorageNodeSelector/types.ts
  packages/libs/src/sdk/types.ts
  packages/libs/src/sdk/utils/errors.ts
  packages/libs/src/sdk/utils/localStorage.ts
  packages/libs/tsconfig.json
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/common/store/pages/history/lineups/sagas.ts
  packages/web/src/common/store/pages/saved/sagas.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/XL

#7755 [PAY-2488] Remove stripe option from purchase flow
  packages/common/src/services/remote-config/defaults.ts
  packages/mobile/src/components/add-funds-drawer/AddFundsDrawer.tsx
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Labels: size/S

#7759 [C-3923] Remove double badges on purchase flow
  packages/web/src/components/track/LockedTrackDetailsTile.tsx
Labels: size/XS

#7760 [C-3924] Fix misc font/type issues on purchase flow
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/harmony/src/components/text-link/types.ts
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx
  packages/web/src/components/track/LockedTrackDetailsTile.module.css
Labels: size/S

#7746 [C-3885] Migrate to harmony text-link
  packages/harmony/src/components/icon.ts
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/harmony/src/components/text-link/index.ts
  packages/harmony/src/components/text-link/types.ts
  packages/harmony/src/components/text/Text/Text.tsx
  packages/harmony/src/components/text/Text/types.ts
  packages/harmony/src/foundations/spacing/spacing.ts
  packages/harmony/src/foundations/theme/ThemeProvider.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.module.css
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/link/ExternalLink.tsx
  packages/web/src/components/link/Link.module.css
  packages/web/src/components/link/Link.tsx
  packages/web/src/components/link/TextLink.tsx
  packages/web/src/components/link/UserLink.module.css
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/link/index.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
Labels: size/XXL

#7761 [C-3926] Add error helper text to new sign in password field
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
Labels: size/XS

#7753 [PAY-2531] Grant access to stream track if user has purchased album
  packages/discovery-provider/integration_tests/gated_content/test_access.py
  packages/discovery-provider/src/gated_content/content_access_checker.py
  packages/discovery-provider/src/gated_content/helpers.py
  packages/discovery-provider/src/gated_content/types.py
Labels: size/XL

#7763 Fix download buttons erroneously displaying
  packages/web/src/components/track/DownloadRow.tsx
Labels: size/XS

#7764 [PAY-2527] Return `playlists_containing_track` from track apis
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/S

#7766 Add an isNativeMobile prop to amplitude
  packages/mobile/src/services/analytics.ts
Labels: size/XS

#7762 [C-3708] Fix wallet text clipping issue in withdrawals table
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTable.module.css
Labels: size/XS

#7767 Fix reset password
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#7765 [C-3929] Fix select-artist genres
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
Labels: size/M

#7770 Bump mobile app version for full-app release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7752 Disable play button if all collection tracks deleted on web
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.jsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
Labels: size/M

#7772 Format artist tracks and followers count
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
Labels: size/XS

#7757 [PAY-2530] Add repost buttons to purchase success
  packages/common/src/models/Analytics.ts
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/types.ts
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
Labels: size/L

#7740 [Protocol Dashboard] Batch of Protodash updates - mostly node related
  protocol-dashboard/src/App.module.css
  protocol-dashboard/src/App.tsx
  protocol-dashboard/src/components/ConfirmTransactionModal/ConfirmTransactionModal.module.css
  protocol-dashboard/src/components/ConfirmTransactionModal/ConfirmTransactionModal.tsx
  protocol-dashboard/src/components/Delegate/Delegate.tsx
  protocol-dashboard/src/components/DelegateStakeModal/DelegateStakeModal.tsx
  protocol-dashboard/src/components/DelegatorsModal/DelegatorsModal.tsx
  protocol-dashboard/src/components/DeregisterServiceModal/DeregisterServiceModal.tsx
  protocol-dashboard/src/components/DisplayAudio/DisplayAudio.tsx
  protocol-dashboard/src/components/ErrorModal/ErrorModal.tsx
  protocol-dashboard/src/components/Header/Header.module.css
  protocol-dashboard/src/components/InfoBox/InfoBox.tsx
  protocol-dashboard/src/components/LineChart/LineChart.tsx
  protocol-dashboard/src/components/ManageAccountCard/ManageAccountCard.tsx
  protocol-dashboard/src/components/ManageService/ManageService.module.css
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/components/ManageService/RegisterNewServiceBtn.tsx
  protocol-dashboard/src/components/MinimumDelegationAmountModal/MinimumDelegationAmountModal.module.css
  protocol-dashboard/src/components/MinimumDelegationAmountModal/MinimumDelegationAmountModal.tsx
  protocol-dashboard/src/components/ModalTable/ModalTable.tsx
  protocol-dashboard/src/components/ModifyServiceModal/ModifyServiceModal.tsx
  protocol-dashboard/src/components/MyEstimatedRewards/MyEstimatedRewards.module.css
  protocol-dashboard/src/components/MyEstimatedRewards/MyEstimatedRewards.tsx
  protocol-dashboard/src/components/NodeOverview/NodeOverview.module.css
  protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx
  protocol-dashboard/src/components/OperatorCutModal/OperatorCutModal.module.css
  protocol-dashboard/src/components/OperatorCutModal/OperatorCutModal.tsx
  protocol-dashboard/src/components/Page/Page.module.css
  protocol-dashboard/src/components/PlainLink/PlainLink.module.css
  protocol-dashboard/src/components/PlainLink/PlainLink.tsx
  protocol-dashboard/src/components/RegisterNodeCard/RegisterNodeCard.tsx
  protocol-dashboard/src/components/RegisterServiceModal/RegisterServiceModal.module.css
  protocol-dashboard/src/components/RegisterServiceModal/RegisterServiceModal.tsx
  protocol-dashboard/src/components/Tooltip/Tooltip.tsx
  protocol-dashboard/src/components/TransactionStatus/TransactionStatus.tsx
  protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.module.css
  protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.tsx
  protocol-dashboard/src/components/UpdateStakeModal/UpdateStakeModal.tsx
  protocol-dashboard/src/containers/API/API.module.css
  protocol-dashboard/src/containers/Node/Node.tsx
  protocol-dashboard/src/containers/Services/Services.tsx
  protocol-dashboard/src/containers/User/User.tsx
  protocol-dashboard/src/index.tsx
  protocol-dashboard/src/store/cache/analytics/hooks.ts
  protocol-dashboard/src/utils/routes.ts
Labels: size/XXL

#7758 Fix DDEX local dev + local dev uses localstack s3
  dev-tools/compose/docker-compose.ddex.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/config.json
Labels: size/S

#7777 Catch exceptions to finish rendezvous fallbacks
  packages/discovery-provider/src/api/v1/tracks.py
Labels: size/M

#7778 Fix rated limiter call in relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
Labels: size/XS

#7779 Add fb redirect
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/nav/desktop/LeftNav.tsx
Labels: size/S

#7782 [Protocol Dashboard] Fix mobile web styling [C-3809] [C-3845]
  protocol-dashboard/src/components/AppBar/AppBar.tsx
  protocol-dashboard/src/components/CallToActionBanner/CallToActionBanner.tsx
  protocol-dashboard/src/components/Header/HeaderMobile.module.css
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/components/MobileNav/MobileNav.module.css
  protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx
  protocol-dashboard/src/components/Page/Page.tsx
  protocol-dashboard/src/components/Page/PageMobile.module.css
  protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx
  protocol-dashboard/src/components/RegisterNodeCard/RegisterNodeCard.tsx
  protocol-dashboard/src/components/RewardsTimingCard/RewardsTimingCard.tsx
  protocol-dashboard/src/components/Timeline/TimelineEvent.module.css
  protocol-dashboard/src/components/Timeline/TimelineEventMobile.module.css
  protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx
  protocol-dashboard/src/containers/Home/Home.tsx
  protocol-dashboard/src/containers/Node/NodeMobile.module.css
  protocol-dashboard/src/containers/Services/Services.tsx
Labels: size/L

#7780 [Protocol Dashboard] Disable start + complete undelegation under certain conditions [C-3849] [C-3940]
  protocol-dashboard/src/components/AppBar/AppBar.tsx
  protocol-dashboard/src/components/CallToActionBanner/CallToActionBanner.tsx
  protocol-dashboard/src/components/Header/HeaderMobile.module.css
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/components/MobileNav/MobileNav.module.css
  protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx
  protocol-dashboard/src/components/Page/Page.tsx
  protocol-dashboard/src/components/Page/PageMobile.module.css
  protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx
  protocol-dashboard/src/components/RegisterNodeCard/RegisterNodeCard.tsx
  protocol-dashboard/src/components/RewardsTimingCard/RewardsTimingCard.tsx
  protocol-dashboard/src/components/Timeline/TimelineEvent.module.css
  protocol-dashboard/src/components/Timeline/TimelineEventMobile.module.css
  protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx
  protocol-dashboard/src/components/TransactionStatus/TransactionStatus.tsx
  protocol-dashboard/src/containers/Home/Home.tsx
  protocol-dashboard/src/containers/Node/NodeMobile.module.css
  protocol-dashboard/src/containers/Services/Services.tsx
Labels: size/L

#7781 Hotfix: Serve static .gitsha in cloudflare worker
  packages/web/src/ssr/worker.js
Labels: size/S

#7785 [C-3887] Update suggested tracks logic to better handle deleted tracks and the race condition
  packages/common/src/api/suggestedTracks.ts
Labels: size/M

#7788 Add user.info.profile scope to tiktok redirect
  packages/identity-service/src/routes/tiktok.js
Labels: size/XS

#7789 [C-3938] Fix harmony cache for SPA
  packages/web/src/HarmonyCacheProvider.tsx
  packages/web/src/index.tsx
  packages/web/src/pages/something-wrong/SomethingWrong.module.css
  packages/web/src/ssr/+onRenderClient.tsx
  packages/web/src/ssr/+onRenderHtml.tsx
  packages/web/src/ssr/index/+onRenderClient.tsx
  packages/web/src/ssr/worker.js
  packages/web/src/store/reload/sagas.ts
Labels: size/L

#7792 [C-3937] Fix new-playlist icon
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.module.css
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
Labels: size/S

#7786 Bump mediorum play logging timeout to 60s
  mediorum/server/serve_blob.go
Labels: size/XS

#7791 Move to 1k gold 10k platinum
  packages/common/src/store/wallet/utils.ts
  packages/discovery-provider/ddl/functions/handle_user_balance_changes.sql
  packages/discovery-provider/integration_tests/notifications/test_tier_change.py
  packages/discovery-provider/src/queries/notifications.py
  packages/embed/src/components/collectibles/CollectiblesHeader.jsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
Labels: size/M

#7795 [Discovery] Fix metrics APIs for year time range [C-3956]
  packages/discovery-provider/src/api/v1/metrics.py
Labels: size/XS

#7798 Add .gitsha to .gitignore
  packages/web/.gitignore
Labels: size/XS

#7796 Add connect instagram ui
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
  packages/web/src/components/nav/desktop/ConnectInstagram.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
Labels: size/M

#7787 Remove min delegation from identity, update subgraph
  protocol-dashboard/.env.prod
  protocol-dashboard/src/services/Audius/AudiusClient.ts
  protocol-dashboard/src/services/Audius/identity/index.ts
  protocol-dashboard/src/store/cache/user/graph/formatter.ts
  protocol-dashboard/src/store/cache/user/hooks.ts
  protocol-dashboard/src/types.ts
Labels: size/M

#7803 [Web] Fix Send Tip modal header icon and Download Page cloud icons [C-3952]
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/public-site/pages/download-page/DownloadPage.module.css
Labels: size/S

#7802 [ONC-45] Fix small kebab
  packages/web/src/components/card/desktop/Card.module.css
  packages/web/src/components/card/desktop/Card.tsx
Labels: size/S

#7804 [C-2459] Remove share sound to tiktok
  packages/common/src/models/Analytics.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/share-sound-to-tiktok-modal/selectors.ts
  packages/common/src/store/ui/share-sound-to-tiktok-modal/slice.ts
  packages/common/src/store/ui/share-sound-to-tiktok-modal/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-to-tiktok-drawer/ShareToTikTokDrawer.tsx
  packages/mobile/src/components/share-to-tiktok-drawer/index.ts
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/IconTikTok.tsx
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/components/ShareDrawer.module.css
  packages/web/src/components/share-modal/components/ShareDrawer.tsx
  packages/web/src/components/share-modal/messages.ts
  packages/web/src/components/share-modal/types.ts
  packages/web/src/components/share-sound-to-tiktok-modal/ShareSoundToTikTokModal.module.css
  packages/web/src/components/share-sound-to-tiktok-modal/ShareSoundToTikTokModal.tsx
  packages/web/src/components/share-sound-to-tiktok-modal/store/sagas.ts
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#7808 Remove idle status in dashboard
  protocol-dashboard/src/types.ts
Labels: size/XS

#7811 [ONC-47] Fix playlist/album upload stream gating check
  packages/web/src/common/store/upload/sagas.js
Labels: size/XS

#7800 Fix harmony icon stories
  packages/harmony/src/icons/SpecialIcons.stories.mdx
  packages/harmony/src/icons/UtilityIcons.stories.mdx
  packages/harmony/src/icons/specialIcons.ts
  packages/harmony/src/icons/utilityIcons.ts
Labels: size/S

#7814 [C-3965] Fix explore tiles
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/web/src/components/perspective-card/PerspectiveCard.module.css
  packages/web/src/pages/explore-page/components/mobile/ColorTile.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Labels: size/S

#7813 [ONC-46] Fix buy audio slippage
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/solana/WithdrawUSDC.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#7661 [Mobile] ⚠️ Install pending CodePush update upon foregrounding after 1hr [C-3791]
  packages/mobile/src/screens/root-screen/useSyncCodePush.ts
Labels: size/S

#7819 [PAY-2518] Fix android bug for combined downloads file in same folder
  packages/mobile/src/services/track-download.ts
Labels: size/XS

#7810 [PAY-2546] Fix stems and downloads text variant
  packages/web/src/components/stem-files-modal/StemFilesModal.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
Labels: size/S

#7809 [ONC-30] Fix playlist trending filters
  packages/discovery-provider/integration_tests/queries/test_get_trending_playlists.py
  packages/discovery-provider/src/queries/get_trending_playlists.py
Labels: size/L

#7812 [ONC-39] Check that signed in user matches wallet
  packages/web/src/common/store/account/sagas.js
Labels: size/S

#7801 Add country column to aggregate_monthly_plays
  packages/discovery-provider/ddl/migrations/0060_aggregate_monthly_plays_country.sql
  packages/discovery-provider/src/models/social/aggregate_monthly_plays.py
  packages/discovery-provider/src/queries/get_user_listen_counts_monthly.py
  packages/discovery-provider/src/tasks/index_aggregate_monthly_plays.py
Labels: size/M

#7806 push solana relay in ci
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/release.yml
Labels: size/M

#7821 .gitsha: update the correct worker this time
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#7816 Fix react-native-datepicker on xcode 15.3
  packages/mobile/patches/@react-native-community+datetimepicker+7.6.2.patch
  packages/mobile/patches/README.md
Labels: size/S

#7825 [C-3966] Don't require premium album fields
  packages/libs/src/services/schemaValidator/schemas/playlistSchema.json
Labels: size/XS

#7826 Bump mobile app versions for full release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7823 [DVRL-18] - formatting and port warnings
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/hardware-requirements.mdx
  docs/docs/node-operator/setup/installation.mdx
Labels: size/M

#7829 Fix wallet check
  packages/web/src/common/store/account/sagas.js
Labels: size/S

#7827 .gitsha => gitsha.json
  packages/web/.gitignore
  packages/web/scripts/workers-site/index.js
  packages/web/scripts/writeSHA.sh
  packages/web/src/ssr/worker.js
  packages/web/src/store/reload/sagas.ts
Labels: size/S

#7824 [C-3743] Fix avatar styles on local
  packages/web/src/components/dynamic-image/DynamicImage.tsx
Labels: size/XS

#7831 Add more priority fees across all solana transactions
  packages/identity-service/src/solana-client.js
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/services/solana/rewards.ts
  packages/libs/src/services/solana/transfer.ts
  packages/libs/src/services/solana/userBank.ts
  packages/web/public/.gitsha
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/Jupiter.ts
Labels: size/M

#7818 Parse and store all DDEX standard identitiers
  packages/common/src/models/Collection.ts
  packages/common/src/schemas/metadata.ts
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/discovery-provider/ddl/migrations/0060_add_ddex_release_ids.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/types/db.ts
  packages/libs/src/sdk/api/albums/types.ts
  packages/libs/src/sdk/api/playlists/types.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/sql-ts/res/discovery-node.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/L

#7834 PROTO-1720: relay logging
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/error.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
Labels: size/L

#7807 [INF-593] Add react + ts + @audius/sdk example app
  docs/docs/developers/sdk/oauth.mdx
  packages/harmony/README.md
  packages/harmony/src/components/input/TextInput/index.ts
  packages/harmony/src/components/input/TextInput/types.ts
  packages/libs/src/sdk/examples/react/.eslintrc.cjs
  packages/libs/src/sdk/examples/react/.gitignore
  packages/libs/src/sdk/examples/react/README.md
  packages/libs/src/sdk/examples/react/index.html
  packages/libs/src/sdk/examples/react/package-lock.json
  packages/libs/src/sdk/examples/react/package.json
  packages/libs/src/sdk/examples/react/public/vite.svg
  packages/libs/src/sdk/examples/react/src/App.css
  packages/libs/src/sdk/examples/react/src/App.tsx
  packages/libs/src/sdk/examples/react/src/assets/react.svg
  packages/libs/src/sdk/examples/react/src/emotion.d.ts
  packages/libs/src/sdk/examples/react/src/main.tsx
  packages/libs/src/sdk/examples/react/src/vite-env.d.ts
  packages/libs/src/sdk/examples/react/tsconfig.json
  packages/libs/src/sdk/examples/react/tsconfig.node.json
  packages/libs/src/sdk/examples/react/vite.config.ts
  packages/libs/src/sdk/oauth/OAuth.ts
Labels: size/L

#7836 Fix embed build and use turbo
  packages/embed/package.json
  packages/embed/src/components/collectibles/CollectibleDetailsView.jsx
Labels: size/S

#7833 Remove custom Sentry fingerprint
  packages/web/src/services/sentry.ts
Labels: size/S

#7839 fix circular dep
  .circleci/src/workflows/release.yml
Labels: size/XS

#7837 Bump harmony and consume in examples/react
  packages/harmony/package.json
  packages/libs/src/sdk/examples/react/package-lock.json
  packages/libs/src/sdk/examples/react/package.json
Labels: size/XS

#7838 [Protocol Dashboard] QA pass for Protocol Dashboard UX Improvements
  protocol-dashboard/src/assets/img/iconChart.svg
  protocol-dashboard/src/assets/img/iconGavel.svg
  protocol-dashboard/src/assets/img/iconHouse.svg
  protocol-dashboard/src/assets/img/iconNodes.svg
  protocol-dashboard/src/components/DelegatorsModal/DelegatorsModal.tsx
  protocol-dashboard/src/components/DeregisterServiceModal/DeregisterServiceModal.tsx
  protocol-dashboard/src/components/InfoTooltip/InfoTooltips.tsx
  protocol-dashboard/src/components/LineChart/LineChart.tsx
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/components/Page/Page.tsx
  protocol-dashboard/src/components/PlaysChart/PlaysChart.tsx
  protocol-dashboard/src/components/RegisterServiceModal/RegisterServiceModal.tsx
  protocol-dashboard/src/components/RewardsTimingCard/RewardsTimingCard.tsx
  protocol-dashboard/src/components/Tooltip/Tooltip.tsx
  protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx
  protocol-dashboard/src/components/TotalStakedChart/TotalStakedChart.tsx
  protocol-dashboard/src/components/UniqueUsersChart/UniqueUsersChart.tsx
  protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.tsx
  protocol-dashboard/src/components/UpdateStakeModal/UpdateStakeModal.tsx
  protocol-dashboard/src/containers/Analytics/Analytics.tsx
  protocol-dashboard/src/containers/Governance/Governance.tsx
  protocol-dashboard/src/containers/Home/Home.tsx
  protocol-dashboard/src/containers/Services/Services.tsx
Labels: size/L

#7840 [PAY-2557] Add PREMIUM_ALBUMS_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#7843 [Protocol Dashboard] Disable Manage delegation button when claim is pending [C-4000]
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.tsx
Labels: size/M

#7844 Add amplitude event for account creation
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/XS

#7849 Fix jupiter instruction
  packages/web/src/services/audius-backend/Jupiter.ts
Labels: size/S

#7851 Fix micro lamports in jupiter
  packages/web/src/services/audius-backend/Jupiter.ts
Labels: size/XS

#7852 Fix lint
  packages/web/src/services/audius-backend/Jupiter.ts
Labels: size/XS

#7850 fix aao error log
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
Labels: size/XS

#7835 Add aggregate_monthly_plays_country_backfill
  packages/discovery-provider/ddl/migrations/0061_aggregate_monthly_plays_country_backfill.sql
Labels: size/M

#7830 [C-3954] Expand sentry use in sign up
  packages/common/src/models/Analytics.ts
  packages/common/src/models/ErrorReporting.ts
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
  packages/mobile/src/utils/reportToSentry.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/tiktok-auth/TikTokAuthButton.tsx
  packages/web/src/components/twitter-auth/TwitterAuth.tsx
  packages/web/src/store/errors/reportToSentry.ts
Labels: size/L

#7842 [ONC-52] Self-re-enqueue user_bank and payment_router indexing tasks
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/S

#7854 Parse more ddex fields
  packages/ddex/ingester/artistutils/artistutils.go
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
Labels: size/XL

#7856 Move some tasks to new standalone index_sol worker
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/S

#7858 Allow querying for unlisted tracks by ID
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/gated_content/content_access_checker.py
  packages/discovery-provider/src/queries/get_tracks.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#7860 Mjp unlisted tracks
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/tasks/index_user_bank.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/default/models/Playlist.ts
  packages/libs/src/sdk/api/generated/default/models/Track.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
Labels: size/M

#7832 [C-3967] Migrate common buttons to harmony
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.module.css
  packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/FormTile.module.css
  packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.module.css
  packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.tsx
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.module.css
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.module.css
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/suggested-tracks/components/SuggestedTracks.tsx
  packages/web/src/components/track/EditTrackModal.jsx
  packages/web/src/components/track/EditTrackModal.module.css
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
  packages/web/src/pages/audio-rewards-page/TrendingRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/RemoveWalletBody.module.css
  packages/web/src/pages/audio-rewards-page/components/RemoveWalletBody.tsx
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.module.css
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.module.css
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.module.css
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.module.css
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-up-page/components/MetaMaskModal.jsx
  packages/web/src/pages/sign-up-page/components/MetaMaskModal.module.css
  packages/web/src/pages/sign-up-page/components/SignUpWithMetaMaskButton.tsx
Labels: size/XXL

#7784 [PAY-2348][PAY-2317] Remove download json field from track metadata
  packages/commands/src/upload-track.mjs
  packages/common/src/hooks/useStems.ts
  packages/common/src/models/Search.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/ddl/migrations/0061_delete_track_download_json_column.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/discovery-provider/src/queries/get_tracks.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/queries/response_name_constants.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/indexers/TrackIndexer.ts
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/models/Track.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/libs/src/sdk/api/tracks/TrackUploadHelper.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/creatorNode/CreatorNode.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/web/src/common/store/upload/sagas.js
  packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.tsx
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/stem-files-modal/StemFilesModal.tsx
  packages/web/src/pages/track-page/utils.ts
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/types.ts
  packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
  packages/web/src/pages/upload-page/store/utils/stems.ts
Labels: size/XXL

#7862 Persist unused DDEX fields in discovery
  packages/common/src/models/Collection.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/ddex/ingester/artistutils/artistutils.go
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/discovery-provider/ddl/migrations/0062_add_ddex_unsupported_fields.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/types/db.ts
  packages/libs/src/sdk/api/albums/types.ts
  packages/libs/src/sdk/api/playlists/types.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/types/DDEX.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/sql-ts/res/discovery-node.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XL

#7865 Document local audius-compose DDEX steps
  dev-tools/config.json
  packages/ddex/README.md
Labels: size/M

#7873 Revert "Persist unused DDEX fields in discovery (#7862)"
  packages/common/src/models/Collection.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/ddex/ingester/artistutils/artistutils.go
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/discovery-provider/ddl/migrations/0062_add_ddex_unsupported_fields.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/types/db.ts
  packages/libs/src/sdk/api/albums/types.ts
  packages/libs/src/sdk/api/playlists/types.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/types/DDEX.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/sql-ts/res/discovery-node.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XL

#7874 Fix audius-cmd test
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
Labels: size/XS

#7869 Misc Sign Up QA fixes
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/FollowArtistCard.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
Labels: size/XS

#7868 [C-4003] Fix sign up overflow issues on small devices
  packages/mobile/package.json
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
Labels: size/L

#7847 [C-3958] Add StaticImage component and update track artwork rendering on web and mobile-web track pages for ssr
  packages/web/src/components/static-image/StaticImage.tsx
  packages/web/src/components/track/GiantArtwork.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/ssr/track/+route.tsx
Labels: size/L

#7877 [PROTO-1700] Update DDEX UI for batches and improved schema
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.ddex.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  packages/ddex/.env.dev
  packages/ddex/README.md
  packages/ddex/webapp/README.md
  packages/ddex/webapp/client/.env.dev
  packages/ddex/webapp/client/src/components/AdminNavSidebar.tsx
  packages/ddex/webapp/client/src/components/App.tsx
  packages/ddex/webapp/client/src/components/Collection/Collection.module.css
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
  packages/ddex/webapp/client/src/pages/Upload/Upload.tsx
  packages/ddex/webapp/client/src/providers/EnvVarsProvider.tsx
  packages/ddex/webapp/server/src/app.ts
  packages/ddex/webapp/server/src/controllers/collectionController.ts
  packages/ddex/webapp/server/src/index.ts
  packages/ddex/webapp/server/src/services/sdkService.ts
Labels: size/L

#7878 Change loglevel to error in TransactionHandler _locallyConfirmTransaction
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/S

#7870 Ignore sentry errors for probers
  packages/web/src/services/sentry.ts
Labels: size/XS

#7882 [C-4014] Fix red chat icons
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.module.css
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/S

#7879 Bump mobile version for full-app-release
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7886 [C-4034] Fix feed tip tile
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
Labels: size/XS

#7885 Fix discovery ddex fields
  packages/common/src/models/Collection.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/ddex/ingester/artistutils/artistutils.go
  packages/ddex/ingester/common/sdk_types.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/discovery-provider/ddl/migrations/0062_add_ddex_unsupported_fields.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/types/db.ts
  packages/libs/src/sdk/api/albums/types.ts
  packages/libs/src/sdk/api/playlists/types.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/types/DDEX.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/sql-ts/res/discovery-node.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XL

#7888 [C-4040, C-4032] Fix play cls, Fix pause on track screen
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#7891 Add missing containers for DDEX Docker build
  dev-tools/compose/docker-compose.yml
Labels: size/M

#7890 [Discovery] Enable user to user grants ("delegated writes") aka manager mode [PAY-2544]
  packages/discovery-provider/ddl/migrations/0061_index_lowercase_user_wallets.sql
  packages/discovery-provider/ddl/migrations/0062_nullable_grant_is_approved.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/models/grants/grant.py
  packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  packages/discovery-provider/src/tasks/entity_manager/entities/grant.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XL

#7864 [Mediorum] [Discovery] Change `/services` protodash routes to `/nodes`
  mediorum/server/server.go
  packages/discovery-provider/src/api/v1/root_path.py
Labels: size/XS

#7893 [C-3561] Remove playback delay on native
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/L

#7855 Fix collection search ranking in common
  packages/common/src/store/pages/search-results/selectors.ts
Labels: size/S

#7896 Remove is_downloadable from trending query
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#7899 Add markdown-to-jsx to web
  package-lock.json
  packages/web/package.json
Labels: size/XS

#7898 Add undefined check to sentry navigator and remove profile page route
  packages/web/src/pages/profile-page/ProfilePage.tsx
  packages/web/src/services/sentry.ts
  packages/web/src/ssr/profile/route.tsx
Labels: size/S

#7900 Fix EM parsing of ddex fields
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/M

#7894 [PAY-2568] Add access field to playlists
  packages/discovery-provider/src/api/v1/models/playlists.py
  packages/discovery-provider/src/api/v1/notifications.py
  packages/discovery-provider/src/gated_content/content_access_checker.py
  packages/discovery-provider/src/queries/get_feed_es.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/queries/search_es.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/models/Access.ts
  packages/libs/src/sdk/api/generated/default/models/Playlist.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
Labels: size/XL

#7903 fix nullable new fields in collection schema
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XS

#7884 [PAY-2577] Fix nft issues
  packages/common/src/models/OpenSea.ts
  packages/common/src/services/opensea-client/ethCollectibleHelpers.ts
  packages/common/src/services/solana-client/solCollectibleHelpers.ts
  packages/libs/src/sdk/api/tracks/types.ts
Labels: size/M

#7905 Pin docker to older version to fix regression
  dev-tools/setup.sh
Labels: size/XS

#7895 Log retryTxId in TransactionHandler
  packages/libs/src/services/solana/transactionHandler.ts
Labels: size/XS

#7892 [C-4024] Update SSR to dynamically import Root based on HYDRATE_CLIENT
  packages/web/src/index.tsx
  packages/web/src/ssr/+onRenderClient.tsx
  packages/web/src/ssr/+onRenderHtml.tsx
  packages/web/src/ssr/RootWithProviders.tsx
  packages/web/src/ssr/index/+onRenderClient.tsx
Labels: size/L

#7883 Improve search quality: genre, mood, tag, fuzziness, exact matches
  packages/discovery-provider/src/queries/search_es.py
Labels: size/L

#7906 Re-add download to track api response for old clients
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#7904 Fix ddex indexing
  packages/discovery-provider/ddl/migrations/0063_ddex_jsonb_columns.sql
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/L

#7908 Fix search autocomplete race condition
  packages/web/src/components/search/SearchBar.jsx
Labels: size/XS

#7907 [C-4027] Harmony migration fixes
  packages/harmony/src/components/button/Button/Button.tsx
  packages/harmony/src/components/button/Button/types.ts
  packages/harmony/src/components/button/FollowButton/FollowButton.tsx
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/app-redirect-popover/components/AppRedirectPopover.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.tsx
  packages/web/src/components/profile-page-nav-section-title/ProfilePageNavSectionTitle.tsx
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/subscribe-button/SubscribeButton.module.css
  packages/web/src/components/subscribe-button/SubscribeButton.tsx
  packages/web/src/components/tipping/support/SupportingList.module.css
  packages/web/src/components/tipping/support/SupportingList.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/TrendingRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/VipDiscordModal.tsx
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.module.css
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx
  packages/web/src/pages/profile-page/components/EditableName.jsx
  packages/web/src/pages/profile-page/components/EditableName.module.css
  packages/web/src/pages/profile-page/components/EditableName.tsx
  packages/web/src/pages/profile-page/components/SocialLink.module.css
  packages/web/src/pages/profile-page/components/SocialLink.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/public-site/pages/landing-page/components/CTAGetStarted.tsx
Labels: size/XL

#7909 [C-4055] Improve modal and popover performance
  packages/harmony/src/components/layout/Popup/Popup.tsx
  packages/harmony/src/components/modal/Modal.tsx
  packages/harmony/src/utils/modalState.ts
Labels: size/L

#7911 Fix remix uploads and AI attributed uploads
  packages/libs/src/api/Track.ts
  packages/libs/src/utils/types.ts
Labels: size/L

#7880 [C-3962] Fix sign up referrals
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
Labels: size/S

#7912 Misc accessibility improvements + mobile drawer fix
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/web/src/components/bottom-bar/BottomBar.tsx
  packages/web/src/components/bottom-bar/buttons/ExploreButton.tsx
  packages/web/src/components/bottom-bar/buttons/FeedButton.tsx
  packages/web/src/components/bottom-bar/buttons/LibraryButton.tsx
  packages/web/src/components/bottom-bar/buttons/ProfileButton.tsx
  packages/web/src/components/bottom-bar/buttons/TrendingButton.tsx
  packages/web/src/components/drawer/Drawer.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/NavPopupMenu.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
Labels: size/M

#7914 boost relay retries and address in logging
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
Labels: size/S

#7920 ⚠️ [C-4064] Fix empty feed/trending pages
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/client-only/ClientOnly.tsx
Labels: size/S

#7902 [PROTO-1700] Make DDEX publisher support batched and local S3
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.ddex.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  packages/ddex/.env.dev
  packages/ddex/.env.stage
  packages/ddex/README.md
  packages/ddex/ingester/README.md
  packages/ddex/ingester/artistutils/artistutils.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/e2e_test/e2e_test.go
  packages/ddex/ingester/e2e_test/fixtures/release_by_release/ern381/sony1.zip
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/README.md
  packages/ddex/publisher/src/models/deliveries.ts
  packages/ddex/publisher/src/models/pendingReleases.ts
  packages/ddex/publisher/src/models/publishedReleases.ts
  packages/ddex/publisher/src/services/publisherService.ts
  packages/ddex/publisher/src/services/s3Service.ts
  packages/ddex/webapp/README.md
  packages/ddex/webapp/client/src/components/Collection/Collection.tsx
  packages/ddex/webapp/server/src/app.ts
Labels: size/XL

#7918 [C-4063] Add Sign on routes and aliases to static routes
  packages/web/src/utils/route.ts
Labels: size/S

#7921 [PROTO-1718] Parse DDEX subgenre and handle multiple genre elements
  packages/ddex/ingester/parser/ern38x.go
Labels: size/M

#7919 [C-4028] Harmony QA
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/harmony/src/components/popup-menu/PopupMenu.module.css
  packages/harmony/src/components/popup-menu/PopupMenu.tsx
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.module.css
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.module.css
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.jsx
  packages/web/src/components/nav-banner/NavBanner.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavCTA.tsx
  packages/web/src/components/nav/desktop/NavHeader.module.css
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/NavHeaderButton.tsx
  packages/web/src/components/nav/desktop/NavMenuButton.module.css
  packages/web/src/components/nav/desktop/NavMenuButton.tsx
  packages/web/src/components/nav/desktop/NotificationsButton.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/on-ramp-button/OnRampButton.module.css
  packages/web/src/components/on-ramp-button/OnRampButton.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/upload/AudioQuality.tsx
  packages/web/src/components/upload/Dropzone.tsx
  packages/web/src/components/upload/UploadArtwork.module.css
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/XL

#7913 [PROTO-1693] Fix tag search triggering autocomplete
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
Labels: size/XS

#7916 [C-3961] Fix sign up modal toast triggers
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/components/toast/ToastContext.module.css
  packages/web/src/components/toast/ToastContext.tsx
  packages/web/src/components/toast/mobile/Toast.module.css
Labels: size/M

#7924 Log error when retry on new node fails
  packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
Labels: size/XS

#7915 [C-4026, C-4059] Update profile page to render basic info and pictures on the server side
  packages/web/src/components/cover-photo/CoverPhoto.module.css
  packages/web/src/components/cover-photo/CoverPhoto.tsx
  packages/web/src/components/nav-banner/NavBanner.module.css
  packages/web/src/components/nav-banner/NavBanner.tsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/components/profile-picture/ProfilePicture.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/static-image/StaticImage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/ssr/profile/+route.tsx
Labels: size/L

#7928 Change internal sdk deps back to wildcard version
  package-lock.json
  packages/libs/package.json
Labels: size/XS

#7926 Expire cached Solana transactions
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
Labels: size/XS

#7929 Fix prepare transfer copy
  packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.tsx
Labels: size/XS

#7931 Update mobile app versions for release .73
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7927 add child logger to relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
Labels: size/M

#7925 [C-4066] Fix edit-collectibles modal spacing
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/S

#7934 [C-4019] Fix web track menu options
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/M

#7917 [INF-594] Add e2e tests for sdk example app
  .circleci/config.yml
  .circleci/src/jobs/@create-audius-app-jobs.yml
  .circleci/src/workflows/create-audius-app.yml
  .gitignore
  package-lock.json
  packages/create-audius-app/examples/react/index.html
  packages/create-audius-app/examples/react/src/App.tsx
  packages/create-audius-app/helpers/copy.ts
  packages/create-audius-app/package.json
  packages/create-audius-app/playwright.config.ts
  packages/create-audius-app/tests/e2e/react.test.ts
  packages/create-audius-app/tests/e2e/setup-test-env.sh
  packages/create-audius-app/tests/integration/create-audius-app.test.ts
  packages/create-audius-app/tests/integration/use-temp-dir.ts
  packages/create-audius-app/tests/integration/utils.ts
  packages/create-audius-app/tsconfig.json
Labels: size/L

#7936 [ONC-58] Add next param to opensea requests
  packages/common/src/services/opensea-client/OpenSeaClient.ts
Labels: size/XS

#7938 [C-4070] Improve sign-up page for various screen sizes
  package-lock.json
  packages/common/src/messages/sign-on/pages.ts
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/web/package.json
  packages/web/src/components/background-animations/BackgroundWaves.jsx
  packages/web/src/components/profile-picture/ProfilePicture.module.css
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-on-page/AudiusValues.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/utils/animations/background-waves.js
Labels: size/L

#7930 [C-4065, C-4067] Update sdk instances in ssr files to avoid http provider errors
  packages/web/src/ssr/profile/+onBeforeRender.tsx
  packages/web/src/ssr/sdk.ts
  packages/web/src/ssr/track/+onBeforeRender.tsx
  packages/web/src/ssr/util.ts
Labels: size/M

#7944 Fix sign up toasts not going away
  packages/web/src/common/store/pages/signon/actions.ts
Labels: size/XS

#7935 [PROTO-1717] Clean up DDEX e2e with table tests
  packages/ddex/ingester/e2e_test/e2e_test.go
Labels: size/XXL

#7946 Add playwright report task
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/@create-audius-app-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/web.yml
Labels: size/M

#7942 [PAY-2564] Remove old track download code
  packages/common/src/store/downloads/selectors.ts
  packages/common/src/store/downloads/slice.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
  packages/mobile/src/components/download-track-progress-drawer/index.ts
  packages/mobile/src/services/track-download.ts
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/L

#7943 [C-2938] Fix robots.txt
  packages/web/scripts/workers-site/index.js
  packages/web/src/ssr/worker.js
Labels: size/XS
