Repository AudiusProject/apps, pull requests merged in 2024-05, with the labels that each got.

#8251 DDEX update/delete
  packages/ddex/ingester/common/types.go
  packages/ddex/ingester/constants/constants.go
  packages/ddex/ingester/crawler/crawler.go
  packages/ddex/ingester/parser/ern38x.go
  packages/ddex/ingester/parser/parser.go
  packages/ddex/publisher/src/index.ts
  packages/ddex/publisher/src/models/releases.ts
  packages/ddex/publisher/src/services/publisherService.ts
Labels: size/XXL

#8284 [C-4327] Fix track ordering within playlist/album
  packages/web/src/common/store/upload/sagas.ts
Labels: size/XS

#8286 Bump android build number for release-client-v1.5.78
  packages/mobile/android/app/build.gradle
Labels: size/XS

#8255 [PAY-2703] Redesign mobile collection and track screen tiles
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/components/details-tile/DetailsProgressInfo.tsx
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/details-tile/DetailsTileAiAttribution.tsx
  packages/mobile/src/components/details-tile/DetailsTileBadge.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/details-tile/SecondaryStats.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/offline-downloads/OfflineStatusRow.tsx
  packages/mobile/src/components/offline-downloads/index.ts
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
  packages/mobile/src/screens/collection-screen/CollectionDownloadStatusRow.tsx
  packages/mobile/src/screens/collection-screen/CollectionHeader.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/DownloadStatusRowDisplay.tsx
  packages/mobile/src/screens/collection-screen/TrackDownloadStatusRow.tsx
  packages/mobile/src/screens/favorites-screen/DownloadFavoritesSwitch.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XXL

#8285 Fix lint items
  packages/ddex/processor/src/publishRelease.ts
  packages/embed/src/components/app.jsx
  packages/web/src/components/user-card/UserCard.test.tsx
Labels: size/M

#8272 [PAY-2817] Web collections show reposts, remove artist column
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XS

#8262 [PAY-2766] Analytics events for premium albums
  packages/common/src/models/Analytics.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx
  packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/L

#8289 Jail broken test
  packages/web/src/components/user-card/UserCard.test.tsx
Labels: size/XS

#8263 [C-4080] Mobile cooldown and claim all
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeDescription.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/styles.ts
  packages/mobile/src/components/drawer/DrawerHeader.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/mobile/src/utils/challenges.tsx
Labels: size/XL

#8282 [PAY-2796] Fix extra notifications on track removal from purchased album
  packages/discovery-provider/ddl/functions/handle_playlist.sql
  packages/discovery-provider/ddl/functions/handle_playlist_track.sql
Labels: size/M

#8288 [PAY-2775] Remove suggested tracks for albums
  packages/common/src/api/suggestedTracks.ts
  packages/mobile/src/components/suggested-tracks/SuggestedCollectionTracks.tsx
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/suggested-tracks/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/web/src/components/suggested-tracks/SuggestedCollectionTracks.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/suggested-tracks/index.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#8291 [C-4284] Fix rewards in mobile web
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/L

#8294 [PAY-2802] Auto-favorite tracks in purchased album
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/S

#8267 ddex: parse contributors
  package-lock.json
  package.json
  packages/ddex/processor/.vscode/launch.json
  packages/ddex/processor/Dockerfile
  packages/ddex/processor/cli.ts
  packages/ddex/processor/fixtures/01_delivery.xml
  packages/ddex/processor/fixtures/02_update.xml
  packages/ddex/processor/fixtures/03_delete.xml
  packages/ddex/processor/package.json
  packages/ddex/processor/src/db.ts
  packages/ddex/processor/src/parseDelivery.ts
  packages/ddex/processor/src/parseTakedown.test.ts
  packages/ddex/processor/src/publishRelease.ts
  packages/ddex/processor/src/s3poller.ts
  packages/ddex/processor/src/server.ts
  packages/ddex/processor/src/util.ts
Labels: size/XXL

#8295 [PAY-2800] Fix mobile navigate to album on purchase success
  packages/common/src/hooks/purchaseContent/types.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
Labels: size/M

#8297 [PAY-2791] Show only own albums in artist dashboard
  packages/common/src/store/account/selectors.ts
  packages/web/src/pages/dashboard-page/components/hooks.ts
Labels: size/S

#8299 [QA-971] Fix smart collections
  packages/common/src/store/playlist-library/helpers.ts
  packages/web/src/components/collection/components/AlbumDetailsText.tsx
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
Labels: size/M

#8298 [PAY-2823] Edit Album access control fixes
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
  packages/web/src/pages/upload-page/fields/types.ts
Labels: size/L

#8304 Fix EditCollection playwright test
  packages/web/e2e/editCollection.test.ts
Labels: size/XS

#8302 [PAY-2779] Fix validation for albumTrackPrice
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Labels: size/M

#8303 [PAY-2815] Show unlocked icon if dm content is purchased
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/S

#8305 Retrigger logic for android notification permissions post-manifest fix
  packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
  packages/mobile/src/notifications.ts
  packages/mobile/src/store/settings/sagas.ts
Labels: size/M

#8274 Convert swagger.json to OAS 3.0 before generating SDK types
  packages/discovery-provider/src/api/v1/models/access_gate.py
  packages/discovery-provider/src/api/v1/models/extensions/__init__.py
  packages/discovery-provider/src/api/v1/models/extensions/fields.py
  packages/discovery-provider/src/api/v1/models/extensions/models.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/models/wildcard_model.py
  packages/discovery-provider/src/api/v1/users.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/models/AccessGate.ts
  packages/libs/src/sdk/api/generated/full/models/FollowGate.ts
  packages/libs/src/sdk/api/generated/full/models/NftCollection.ts
  packages/libs/src/sdk/api/generated/full/models/NftGate.ts
  packages/libs/src/sdk/api/generated/full/models/PremiumContentSignature.ts
  packages/libs/src/sdk/api/generated/full/models/PurchaseGate.ts
  packages/libs/src/sdk/api/generated/full/models/StreamSignature.ts
  packages/libs/src/sdk/api/generated/full/models/TipGate.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/UsdcGate.ts
  packages/libs/src/sdk/api/generated/full/models/UserReplicaSet.ts
  packages/libs/src/sdk/api/generated/full/models/UsersByContentNode.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/libs/src/sdk/api/generator/.gitignore
  packages/libs/src/sdk/api/generator/gen.js
Labels: size/XXL

#8296 [PAY-2781] Poll for track access on album purchase
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/M

#8308 [PAY-2822] Convert LockedContentDetailsTile to Harmony
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/LockedContentDetailsTile.module.css
  packages/web/src/components/track/LockedContentDetailsTile.tsx
Labels: size/L

#8309 [PAY-2772] Fix collection description text size
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
Labels: size/XS

#8254 [PAY-2764] Implement DeveloperApp Update entity manager action
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#8310 [PAY-2810] Purchase/Sale email fix text for albums
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
Labels: size/M

#8306 [PAY-2794] Use UserLink for purchases/sales tables
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTable.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
Labels: size/XS

#8311 Upgrade dapp-store to 0.8.1
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/S

#8292 [C-4285] Add claim all rewards button functionality
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/store/pages/audio-rewards/types.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Labels: size/L

#8314 Remove root .env
  .gitignore
Labels: size/S

#8318 [PAY-2801] Purchased selectable filter in library albums
  packages/discovery-provider/src/queries/get_collection_library.py
  packages/discovery-provider/src/queries/get_track_library.py
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Labels: size/S

#8315 Content-Length header for images
  mediorum/server/serve_image.go
  mediorum/server/server.go
Labels: size/S

#8320 [PAY-2859] Fix bugs in edit app flow
  packages/common/src/api/developerApps.ts
  packages/web/src/components/preload-image/PreloadImage.tsx
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/AuthorizedAppListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/EditAppPage.tsx
Labels: size/M

#8319 Modify /etc/hosts on CI machines before api test
  .circleci/src/jobs/test-audius-cmd.yml
  dev-tools/audius-compose
  packages/libs/scripts/check-generated-types.sh
Labels: size/S

#8271 [PAY-2799] Show preview button for collections
  packages/common/src/api/collection.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/screens/collection-screen/CollectionDownloadStatusRow.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/TrackDownloadStatusRow.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/collection/types.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
Labels: size/L

#8312 [C-4333] Migrate follow-users to new sign-up flow
  packages/common/src/store/pages/feed/actions.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/feed/selectors.ts
  packages/web/src/common/store/pages/feed/sagas.ts
  packages/web/src/components/follow-artist-card/FollowArtistCard.tsx
  packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
  packages/web/src/pages/feed-page/FeedPageProvider.jsx
  packages/web/src/pages/feed-page/components/EmptyFeed.tsx
  packages/web/src/pages/feed-page/components/FollowUsers.jsx
  packages/web/src/pages/feed-page/components/FollowUsers.module.css
  packages/web/src/pages/feed-page/components/FollowUsers.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/feed-page/types.ts
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#8321 [PAY-2738] Public album with prem track always shows buy button
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/S

#8322 [QA-1215] Fix history
  packages/discovery-provider/src/api/v1/users.py
Labels: size/XS

#8323 [QA-1212] Fix chromecast
  package-lock.json
  package.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/patches/react-native-google-cast+4.6.2.patch
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/GoogleCast.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
Labels: size/M

#8324 Revert "Convert swagger.json to OAS 3.0 before generating SDK types (#8274)"
  packages/discovery-provider/src/api/v1/models/access_gate.py
  packages/discovery-provider/src/api/v1/models/extensions/__init__.py
  packages/discovery-provider/src/api/v1/models/extensions/fields.py
  packages/discovery-provider/src/api/v1/models/extensions/models.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/models/wildcard_model.py
  packages/discovery-provider/src/api/v1/users.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/models/AccessGate.ts
  packages/libs/src/sdk/api/generated/full/models/FollowGate.ts
  packages/libs/src/sdk/api/generated/full/models/NftCollection.ts
  packages/libs/src/sdk/api/generated/full/models/NftGate.ts
  packages/libs/src/sdk/api/generated/full/models/PremiumContentSignature.ts
  packages/libs/src/sdk/api/generated/full/models/PurchaseGate.ts
  packages/libs/src/sdk/api/generated/full/models/StreamSignature.ts
  packages/libs/src/sdk/api/generated/full/models/TipGate.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/UsdcGate.ts
  packages/libs/src/sdk/api/generated/full/models/UserReplicaSet.ts
  packages/libs/src/sdk/api/generated/full/models/UsersByContentNode.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/libs/src/sdk/api/generator/.gitignore
  packages/libs/src/sdk/api/generator/gen.js
Labels: size/XXL

#8330 [PAY-2861] CollectionCard fixes
  packages/web/src/components/card/Card.tsx
  packages/web/src/components/collection/CollectionCard.test.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/notification/Notification/components/UserNameLink.module.css
  packages/web/src/components/notification/Notification/components/UserNameLink.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/M

#8331 Close modal on done
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Labels: size/XS

#8332 [PAY-2812] Change spend to earn challenge copy
  packages/common/src/utils/challenges.ts
Labels: size/XS

#8313 [QA-957] Fix android overflowing text on access & sale modal
  packages/mobile/src/components/help-callout/HelpCallout.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx
Labels: size/M

#8325 [PROTO-1706] - Audius-d Node Documentation
  docs/.vscode/spellright.dict
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/architecture.mdx
  docs/docs/node-operator/setup/hardware-requirements.mdx
  docs/docs/node-operator/setup/installation.mdx
  docs/docs/node-operator/setup/overview.mdx
  docs/sidebars.js
Labels: size/XL

#8337 [PROTO-1706] fixups
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/architecture.mdx
  docs/docs/node-operator/setup/installation.mdx
  docs/docs/node-operator/setup/overview.mdx
Labels: size/S

#8334 Add error message to upload flow
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
Labels: size/M

#8333 [QA-956] Add deleted tile for tracks/albums/playlists
  packages/mobile/src/components/details-tile/DeletedTile.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
Labels: size/M

#8340 [QA-1241] Fix hidden track add to playlist allowing non hidden items
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/XS

#8335 Add CI for crm plugin
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/release.yml
Labels: size/M

#8342 Fix crm CI
  dev-tools/compose/docker-compose.yml
  packages/compose/package.json
Labels: size/XS

#8338 [C-4335] Migrate all user and collection cards
  packages/common/src/store/pages/explore/exploreCollections/selectors.ts
  packages/web/src/components/add-to-collection/mobile/AddToCollection.tsx
  packages/web/src/components/card-legacy/UserCard.jsx
  packages/web/src/components/card-legacy/UserCard.module.css
  packages/web/src/components/card-legacy/desktop/Card.module.css
  packages/web/src/components/card-legacy/desktop/Card.tsx
  packages/web/src/components/card-legacy/mobile/Card.module.css
  packages/web/src/components/card-legacy/mobile/Card.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/lineup/CardLineup.tsx
  packages/web/src/pages/explore-page/ExploreCollectionsPage.tsx
  packages/web/src/pages/explore-page/ExploreCollectionsPageProvider.tsx
  packages/web/src/pages/explore-page/ExplorePageProvider.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/saved-page/components/desktop/CollectionCard.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Labels: size/XXL

#8336 Disable add to playlist for prem tracks if not purchased
  packages/common/src/hooks/purchaseContent/utils.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#8343 Fix issues with text-link variant
  packages/harmony/src/components/text-link/types.ts
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/collections-table/CollectionsTable.tsx
  packages/web/src/components/link/TextLink.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/LockedContentDetailsTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/server-track-page/mobile/ServerTrackPageHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#8344 Reapply "Convert swagger.json to OAS 3.0 before generating SDK types (#8274)" (#8324)
  packages/discovery-provider/src/api/v1/models/access_gate.py
  packages/discovery-provider/src/api/v1/models/extensions/__init__.py
  packages/discovery-provider/src/api/v1/models/extensions/fields.py
  packages/discovery-provider/src/api/v1/models/extensions/models.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/models/wildcard_model.py
  packages/discovery-provider/src/api/v1/users.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/models/AccessGate.ts
  packages/libs/src/sdk/api/generated/full/models/FollowGate.ts
  packages/libs/src/sdk/api/generated/full/models/NftCollection.ts
  packages/libs/src/sdk/api/generated/full/models/NftGate.ts
  packages/libs/src/sdk/api/generated/full/models/PremiumContentSignature.ts
  packages/libs/src/sdk/api/generated/full/models/PurchaseGate.ts
  packages/libs/src/sdk/api/generated/full/models/StreamSignature.ts
  packages/libs/src/sdk/api/generated/full/models/TipGate.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/UsdcGate.ts
  packages/libs/src/sdk/api/generated/full/models/UserReplicaSet.ts
  packages/libs/src/sdk/api/generated/full/models/UsersByContentNode.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/libs/src/sdk/api/generator/.gitignore
  packages/libs/src/sdk/api/generator/gen.js
Labels: size/XXL

#8327 ddex: handle updates and deletes
  packages/ddex/processor/PROD.md
  packages/ddex/processor/README.md
  packages/ddex/processor/SCHEMA.md
  packages/ddex/processor/fixtures/01_delivery.xml
  packages/ddex/processor/fixtures/02_update.xml
  packages/ddex/processor/fixtures/03_delete.xml
  packages/ddex/processor/src/db.ts
  packages/ddex/processor/src/parseDelivery.test.ts
  packages/ddex/processor/src/parseDelivery.ts
  packages/ddex/processor/src/parseTakedown.test.ts
  packages/ddex/processor/src/publishRelease.ts
  packages/ddex/processor/src/server.ts
Labels: size/XL

#8347 Fix profile page artist vs user
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/XS

#8346 Fix pedalboard apps template import
  packages/discovery-provider/plugins/pedalboard/apps/app-template/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/crm/src/index.ts
Labels: size/XS

#8348 [PAY-2864] Fix progress label for reward on native
  packages/mobile/src/screens/audio-screen/Panel.tsx
Labels: size/S

#8355 [PAY-2866] Fix duration showing 0m 0s
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/XS

#8356 [PAY-2888] Fix dog ear positioning
  packages/web/src/components/tile/Tile.tsx
Labels: size/M

#8354 [C-4339] Fix rewards progress label formatting
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/S

#8357 [PAY-2814] Omit favorite and repost buttons for unowned albums
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/components/card-legacy/desktop/CollectionArtCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
Labels: size/M

#8349 [C-4077] Migrate HelpCallout to Hint
  packages/harmony/src/components/hint/Hint.tsx
  packages/mobile/src/components/help-callout/HelpCallout.tsx
  packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
  packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx
  packages/mobile/src/harmony-native/components/Hint/Hint.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/components/EmailInUseHint.tsx
  packages/web/src/components/help-callout/HelpCallout.module.css
  packages/web/src/components/help-callout/HelpCallout.tsx
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.module.css
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx
  packages/web/src/components/modal-radio/ModalRadioItem.tsx
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.module.css
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
  packages/web/src/pages/upload-page/fields/download-availability/DownloadAvailability.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/SpecialAccessFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedDescription.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/XL

#8352 [PAY-2881] Fix access & sale showing hidden by default
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/schemas/upload/uploadFormSchema.ts
Labels: size/XS

#8360 Fix wallet matches check
  packages/web/src/common/store/account/sagas.js
Labels: size/XS

#8353 [PAY-2763] Remove dividers on mobile collection screens
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/components/track-list/TrackListItemSkeleton.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenSkeleton.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
Labels: size/L

#8350 [C-4338] Fix $AUDIO available to claim
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/S

#8361 Change 'creator' to 'content' where applicable for audius-ctl docs
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/architecture.mdx
  docs/docs/node-operator/setup/installation.mdx
Labels: size/S

#8359 QA-1093: fix upload button dark mode
  packages/harmony/src/components/button/Button/Button.tsx
  packages/web/src/assets/styles/ant-overrides.css
Labels: size/S

#8362 [PAY-2806] Fix offline downloads legacy content node selection
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Labels: size/XS

#8363 [PAY-2879] Add purchased pill to mobile albums library
  packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
Labels: size/XS

#8351 [PAY-2809] Mobile premium album tracklist UI updates
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/M

#8364 [PAY-2887] Fix purchase notification twitter share copy
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
Labels: size/S

#8366 [PAY-2885] Remove require statements on encoded params
  packages/libs/src/sdk/api/users/UsersApi.ts
Labels: size/M

#8370 Add log for ws check
  comms/discovery/server/server.go
Labels: size/XS

#8016 [DVRL-19] - add 'create-audius-app' docs
  docs/.markdownlint.json
  docs/.vscode/spellright.dict
  docs/docs/developers/guides/create-audius-app.mdx
  docs/docs/developers/introduction/overview.mdx
  docs/docs/learn/introduction/getting-started.mdx
  docs/sidebars.js
  docs/static/img/create-audius-app/create-audius-app-terminal.svg
  docs/static/img/create-audius-app/run-app-terminal.svg
Labels: size/L

#8372 Bump versions
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8269 [PAY-2722] Add account switcher
  packages/common/src/api/account.ts
  packages/common/src/audius-query/schema.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/common/src/models/Grant.ts
  packages/common/src/models/User.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/libs/src/api/Account.ts
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/libs/src/services/discoveryProvider/constants.ts
  packages/libs/src/userStateManager.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountListContent.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcherRow.module.css
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcherRow.tsx
Labels: size/XL

#8371 [QA-1239] Fix collection loading state
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#8379 [QA-1214] Fix slider border radius
  packages/web/src/components/play-bar/slider/Slider.module.css
Labels: size/XS

#8375 [QA-955] Dismiss keyboard when clicking external link
  packages/mobile/src/components/core/Hyperlink.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/types.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Labels: size/S

#8368 misc ddex cleanup
  dev-tools/config.json
  packages/ddex/ingester/README.md
  packages/ddex/ingester/parser/ern38x.go
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/M

#8383 [PAY-2886] Fix artist dashboard border radii
  packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx
  packages/web/src/pages/dashboard-page/components/TotalPlaysChart.module.css
Labels: size/XS

#8384 [PAY-2824] Make Collection play button large
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
Labels: size/XS

#8385 [PAY-2899] Fix collection header title becoming centered
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
Labels: size/XS

#8376 [PAY-2896][PAY-2908][PAY-2907] Update claim all button text logic
  packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Labels: size/M

#8358 [PAY-2889] Fix edit collection unlisted value
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Labels: size/M

#8389 [PAY-2893] Fix FilterButton dark mode selection text color
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Labels: size/XS

#8382 [Docs] - Node Operator install guide updates
  docs/docs/node-operator/setup/installation.mdx
Labels: size/S

#8377 [PAY-2637] Update audio balance on successful rewards claim
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
Labels: size/S

#8390 [PAY-2900] Fix collection upload/edit layout
  packages/web/src/components/create-playlist/PlaylistForm.tsx
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/pages/upload-page/fields/StemsAndDownloadsCollectionsField.tsx
  packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Labels: size/S

#8391 [PAY-2773] Remove embed option for premium albums
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/web/src/components/card-legacy/desktop/CollectionArtCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
Labels: size/S

#8386 Disable failing audius-sdk test
  packages/libs/src/sdk/api/users/UsersApi.test.ts
  packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  packages/libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/M

#8394 [PAY-2871] Track table link to track even when it's gated
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/XS

#8396 [PAY-2868] Hide count stats if all zeros
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/details-tile/SecondaryStats.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#8328 Play with RNTP buffer settings
  packages/mobile/src/app/App.tsx
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/M

#8387 Add image url to response for developer app request
  packages/discovery-provider/src/queries/get_developer_apps.py
Labels: size/XS

#8400 Index all memos (v1 and v2) and use cache in index_payment_router
  packages/discovery-provider/src/solana/solana_helpers.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/utils/helpers.py
Labels: size/M

#8380 DDEX users poller
  packages/ddex/processor/cli.ts
  packages/ddex/processor/src/publishRelease.ts
  packages/ddex/processor/src/server.ts
  packages/ddex/processor/src/usersPoller.ts
Labels: size/M

#8381 [QA-1248] Fix search header width
  packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
Labels: size/XS

#8398 [PAY-2865] Mobile web collection page fixes
  packages/web/src/components/collection/mobile/CollectionHeader.module.css
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#8388 [PAY-2883] Disable links in purchase modal during purchase
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/track/LockedContentDetailsTile.tsx
Labels: size/S

#8392 [PAY-2867] Fix native DMs allowing purchase button to show after purchase
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
Labels: size/L

#8403 [C-4344][C-4352] Fix empty rewards mobile crashing
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/S

#8316 Run SDK gen script as user to allow deletes
  .circleci/src/jobs/test-audius-cmd.yml
  packages/libs/scripts/check-generated-types.sh
  packages/libs/src/sdk/api/generated/default/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/default/models/BulkSubscribersResponse.ts
  packages/libs/src/sdk/api/generated/default/models/GetSupporter.ts
  packages/libs/src/sdk/api/generated/default/models/Grant.ts
  packages/libs/src/sdk/api/generated/default/models/HistoryResponse.ts
  packages/libs/src/sdk/api/generated/default/models/ListenCount.ts
  packages/libs/src/sdk/api/generated/default/models/ManagedUser.ts
  packages/libs/src/sdk/api/generated/default/models/ManagedUsers.ts
  packages/libs/src/sdk/api/generated/default/models/MonthlyAggregatePlay.ts
  packages/libs/src/sdk/api/generated/default/models/TopGenreUsersResponse.ts
  packages/libs/src/sdk/api/generated/default/models/TopUsersResponse.ts
  packages/libs/src/sdk/api/generated/default/models/TxSignature.ts
  packages/libs/src/sdk/api/generated/default/models/UserReplicaSet.ts
  packages/libs/src/sdk/api/generated/default/models/UserSubscribers.ts
  packages/libs/src/sdk/api/generated/default/models/UserTrackListenCountsResponse.ts
  packages/libs/src/sdk/api/generated/default/models/UsersByContentNode.ts
  packages/libs/src/sdk/api/generated/default/models/VersionMetadata.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generator/gen.js
Labels: size/XXL

#8397 Make indexer properly resort to using gateway if chain isn't caught up
  packages/discovery-provider/src/utils/web3_provider.py
Labels: size/S

#8399 [QA-844] Fix misaligned bio links
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/harmony-native/components/TextLink/ExternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/types.ts
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
Labels: size/L

#8411 Cleanup user auth config
  packages/libs/src/sdk/services/Auth/UserAuth.ts
  packages/libs/src/sdk/services/Auth/constants.ts
  packages/libs/src/sdk/services/Auth/getDefaultConfig.ts
  packages/libs/src/sdk/services/Auth/types.ts
Labels: size/M

#8405 [PAY-2890] Fix hover state on CollectionCard title
  packages/web/src/components/collection/CollectionCard.tsx
Labels: size/S

#8412 [PAY-2878] Fix tracks tables right icons
  packages/web/src/components/collections-table/CollectionsTable.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx
Labels: size/M

#8407 [INF-694] Run playwright against local stack
  .circleci/src/jobs/@integration-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/jobs/test-audius-cmd.yml
  .circleci/src/workflows/integration.yml
  .circleci/src/workflows/web.yml
  dev-tools/compose/docker-compose.dev-tools.prod.yml
  dev-tools/setup.sh
  packages/commands/src/create-playlist.mjs
  packages/commands/src/create-user.mjs
  packages/commands/src/upload-track.mjs
  packages/web/.gitignore
  packages/web/e2e/auth.setup.ts
  packages/web/e2e/data.seed.ts
  packages/web/e2e/data.ts
  packages/web/e2e/editCollection.test.ts
  packages/web/e2e/page-object-models/socialActions.ts
  packages/web/e2e/play.test.ts
  packages/web/e2e/signIn.test.ts
  packages/web/e2e/signUp.test.ts
  packages/web/e2e/smoke.test.ts
  packages/web/e2e/socials.test.ts
  packages/web/e2e/test.ts
  packages/web/e2e/uploadCollection.test.ts
  packages/web/e2e/uploadTrack.test.ts
  packages/web/e2e/utils.ts
  packages/web/package.json
  packages/web/playwright.config.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
  scripts/get-release-dirs.sh
Labels: size/XL

#8369 [PAY-2869] Fix play button on mobile collections default state
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Labels: size/XS

#8410 [PAY-2892] Omit albumTrackPrice from data going to backend
  packages/web/src/common/store/upload/sagaHelpers.ts
Labels: size/XS

#8406 Fix dog ear on track page
  packages/web/src/components/tile/Tile.module.css
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Labels: size/M

#8393 Misc $album fixes
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/S

#8416 Revert "Fix dog ear on track page"
  packages/web/src/components/tile/Tile.module.css
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Labels: size/M

#8418 Fix web-test by resolving circular import
  packages/common/src/store/effects.ts
Labels: size/XS

#8421 fix ddex playlist release_date parsing
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/XS

#8422 [PAY-2960] Change library filter title to Premium
  packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Labels: size/XS

#8423 [PAY-2985] Fix squished art in purchase modal
  packages/web/src/components/track/LockedContentDetailsTile.module.css
  packages/web/src/components/track/LockedContentDetailsTile.tsx
Labels: size/XS

#8426 [QA-1259] Restrict OTP spam
  dev-tools/compose/docker-compose.test.yml
  packages/identity-service/src/routes/authentication.js
  packages/identity-service/src/utils/otp.js
  packages/identity-service/test/authenticationTest.js
  packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
  packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
Labels: size/L

#8430 [QA-1267] Fix blank android tip screen
  packages/mobile/src/screens/app-screen/AppScreen.tsx
Labels: size/S

#8301 [Web] [Common] Accounts You Manage flows; hook up Accounts Managing You to API
  packages/common/src/api/account.ts
  packages/common/src/models/Grant.ts
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/chat-page/components/useComposeChat.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/XL

#8413 [Web] Implement Remove Manager flows [Manager Mode ] [PAY-2827]
  packages/common/src/api/account.ts
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/StopManagingConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/types.ts
Labels: size/XL

#8436 QA-1260: change content title to not say track
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
Labels: size/XS

#8420 Fix dog ear pt 3
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Labels: size/M

#8427 [PAY-2786] Clean up skeletons for collection page
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#8428 [PAY-2965, PAY-2968, PAY-2963] Album upload copy fixes; remove 'hidden' option
  packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/M

#8435 fix ddex playlists UI
  packages/discovery-provider/src/tasks/metadata.py
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/M

#8402 [QA-1251] Fix short lineup playback issues.
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/web/src/common/store/pages/ai/lineups/tracks/sagas.ts
Labels: size/XS

#8433 [QA-1253] Improve details tile layout
  packages/mobile/src/components/core/Tag.tsx
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileMetadata.tsx
  packages/mobile/src/components/details-tile/SecondaryStats.tsx
  packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
Labels: size/L

#8438 re-do placement_hosts field
  packages/libs/src/services/creatorNode/CreatorNode.ts
  packages/libs/src/utils/types.ts
Labels: size/XS

#8429 [PAY-2966] Add purchase track to mobile collection tracklist overflow
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/M

#8440 [C-4384][C-4383] Small web mobile UI fixes
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Labels: size/S

#8441 [PAY-2975] Fix mobile-web premium album overflow options
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
Labels: size/S

#8419 [C-4349] Fix challenge cooldown with completed_at
  packages/discovery-provider/.gitignore
  packages/discovery-provider/ddl/migrations/0069_user_challenges_completed_at.sql
  packages/discovery-provider/integration_tests/challenges/test_audio_matching_challenges.py
  packages/discovery-provider/integration_tests/challenges/test_challenges.py
  packages/discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_referral_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_track_upload_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_trending_challenge.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py
  packages/discovery-provider/integration_tests/tasks/test_index_profile_challenge_backfill.py
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
  packages/discovery-provider/src/challenges/challenge.py
  packages/discovery-provider/src/challenges/challenge_event_bus.py
  packages/discovery-provider/src/models/rewards/user_challenge.py
  packages/discovery-provider/src/queries/get_attestation.py
  packages/discovery-provider/src/tasks/calculate_trending_challenges.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_profile_challenge_backfill.py
  packages/discovery-provider/src/tasks/index_solana_plays.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#8443 Fix coinflow default
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
Labels: size/XS

#8442 [PAY-2995] Fix stream_conditions in saved and library fetch
  packages/common/src/services/audius-api-client/makeActivity.ts
Labels: size/S

#8414 [PAY-2932][PAY-2933] Remove unused exports from apiClient and audiusBackend
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/L

#8425 [PAY-2794] Fix several album track price issues
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/helpers.ts
  packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Labels: size/M

#8437 Filter yourself and current managers out of search results list in Accounts Managing You search [PAY-2833]
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
Labels: size/S

#8445 [PAY-2945] Add claimable progress bar
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Labels: size/M

#8434 QA-1247: poa network removal
  dev-tools/compose/nginx_ingress.conf
  packages/libs/src/AudiusLibs.ts
  packages/libs/src/NativeAudiusLibs.ts
  packages/libs/src/WebAudiusLibs.ts
  packages/libs/src/services/web3Manager/Web3Manager.ts
Labels: size/M

#8448 No math.abs function in python
  packages/discovery-provider/src/utils/web3_provider.py
Labels: size/XS

#8452 [QA-1277] Fix missing artist names on playlist tables
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/M

#8451 [PAY-2980] Improve collection card touch response
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
Labels: size/M

#8446 [QA-1274] Fix icon-tipping
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/XS
