Repository AudiusProject/apps, pull requests merged in 2024-09, with the labels that each got.

#9564 PROTO-1904: eth validator bridge
  core/Makefile
  core/common/web3.go
  core/config/config.go
  core/contracts/contracts.go
  core/contracts/gen/audius_token.go
  core/contracts/gen/claims_manager.go
  core/contracts/gen/delegate_manager.go
  core/contracts/gen/entity_manager.go
  core/contracts/gen/eth_rewards_manager.go
  core/contracts/gen/governance.go
  core/contracts/gen/registry.go
  core/contracts/gen/service_provider_factory.go
  core/contracts/gen/service_type_manager.go
  core/contracts/gen/staking.go
  core/contracts/generate_contract.sh
  core/go.mod
  core/go.sum
  core/main.go
  core/registry_bridge/bridge.go
  core/registry_bridge/query.go
  core/registry_bridge/registry.go
  core/registry_bridge/state.go
  dev-tools/compose/docker-compose.test.yml
Labels: size/XL

#9594 [C-5001] Add comment disabling for tracks
  packages/common/src/messages/comments.ts
  packages/common/src/messages/edit.ts
  packages/common/src/models/Search.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/discovery-provider/ddl/migrations/0093_add_comments_disabled.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/metadata.py
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/generated/full/models/SearchTrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/mobile/src/components/fields/SwitchRowField.tsx
  packages/mobile/src/components/fields/index.ts
  packages/mobile/src/screens/edit-track-screen/fields/SwitchField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/index.ts
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/components/edit/fields/SwitchRowField.module.css
  packages/web/src/components/edit/fields/SwitchRowField.tsx
  packages/web/src/pages/track-page/TrackCommentsPage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#9613 [QA-1537] Remove unnecessary short circuit logic for gated tracks in get_remixes_of
  packages/discovery-provider/src/queries/get_remixes_of.py
Labels: size/XS

#9608 [PAY-3324] Add copy notice around network take rate
  packages/web/src/components/table/Table.tsx
  packages/web/src/pages/pay-and-earn-page/PayAndEarnPage.module.css
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
Labels: size/M

#9609 Fix web external-text-link style propagation
  packages/web/src/components/link/ExternalTextLink.tsx
Labels: size/XS

#9606 Add support for expand rounding mode to FixedDecimal
  .changeset/warm-spies-shake.md
  packages/fixed-decimal/src/FixedDecimal.test.ts
  packages/fixed-decimal/src/FixedDecimal.ts
Labels: size/L

#9601 [PAY-3206] Populate content targeting dropdowns for blast modal (web)
  .changeset/clever-comics-think.md
  packages/common/src/api/collection.ts
  packages/common/src/api/user.ts
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/default/models/SalesAggregate.ts
  packages/libs/src/sdk/api/generated/default/models/SalesAggregateResponse.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/L

#9615 Remove ToUserId in blast ws fan-out
  comms/discovery/rpcz/chat_blast.go
Labels: size/XS

#9616 [PAY-3387] Chat ws respects chat_member.is_hidden
  comms/discovery/rpcz/apply.go
Labels: size/XS

#9617 Only add blasts to store for sender
  .changeset/spotty-ads-share.md
  packages/common/src/store/pages/chat/middleware.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
Labels: size/M

#9618 Blast getMessages supports all audiences
  comms/discovery/db/queries/get_chat_messages.go
Labels: size/XS

#9610 [C-5008] Add single and multi lineHeight options to Text
  .changeset/rare-panthers-accept.md
  packages/harmony/src/components/text/Text.tsx
  packages/harmony/src/components/text/constants.ts
  packages/harmony/src/components/text/types.ts
  packages/harmony/src/foundations/typography/typography.ts
  packages/mobile/src/harmony-native/components/Comments/CommentText/CommentText.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/user-generated-text/UserGeneratedText.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/M

#9621 [PAY-3389] Fix duplicate blast messages in 1:1 threads
  comms/discovery/rpcz/chat_blast.go
Labels: size/XS

#9620 [QA-1439] Don't block gated tracks from being remixes
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Labels: size/M

#9626 [PAY-3412] Include network splits in CSV downloads of sales/purchases
  packages/discovery-provider/src/queries/download_csv.py
Labels: size/M

#9625 [PAY-3410][PAY-3406] Update Sales Table help link and "Value" => "Total"
  packages/common/src/utils/linking.ts
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
Labels: size/S

#9607 Pin Rust version for 'prod' DN dockerfile
  packages/discovery-provider/Dockerfile.prod
Labels: size/XS

#9629 Fix purchasing without network split
  .changeset/good-planets-give.md
  packages/libs/src/sdk/utils/preparePaymentSplits.ts
Labels: size/S

#9623 [PAY-3404] Fix floor() for negative numbers that are already floored
  .changeset/hot-dolphins-complain.md
  packages/fixed-decimal/src/FixedDecimal.test.ts
  packages/fixed-decimal/src/FixedDecimal.ts
Labels: size/S

#9624 [PAY-3408][PAY-3409][PAY-3408][PAY-3405][PAY-3413] Update Sales/Purchase Modal
  packages/web/src/components/summary-table/SummaryTable.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx
Labels: size/L

#9622 [C-4952] Mobile comment overflow action confirmations
  packages/mobile/src/components/action-drawer/ActionDrawerWithoutRedux.tsx
  packages/mobile/src/components/comments/CommentBadge.tsx
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/ConfirmationDrawerWithoutRedux.tsx
  packages/mobile/src/components/drawers/index.ts
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBadge.tsx
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/L

#9631 [QA-1512] Mediorum transcode fixes
  mediorum/ddl/ddl.go
  mediorum/server/audio_analysis.go
  mediorum/server/repair.go
  mediorum/server/transcode.go
Labels: size/L

#9612 [C-4752] Reduce border width for small Avatar
  .changeset/unlucky-bananas-impress.md
  packages/harmony/src/components/avatar/Avatar.tsx
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
Labels: size/S

#9632 Revert change to create-audius-app until new SDK version is published
  packages/create-audius-app/examples/react/src/App.tsx
Labels: size/XS

#9628 getChatMessages respects audience content type and id
  comms/discovery/db/queries/get_chat_messages.go
Labels: size/S

#9593 [PAY-3388] Migrate feed to SDK
  packages/common/src/adapters/feed.ts
  packages/common/src/adapters/index.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/explore/Explore.ts
  packages/mobile/src/services/explore.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/services/explore.ts
Labels: size/L

#9599 core misc changes
  core/Makefile
  core/accounts/serde.go
  core/accounts/signature.go
  core/accounts/signature_test.go
  core/accounts/wallet.go
  core/accounts/wallet_test.go
  core/chain/abci.go
  core/chain/db.go
  core/chain/finalize.go
  core/chain/node.go
  core/chain/register_node.go
  core/chain/state.go
  core/common/logger.go
  core/config/comet.go
  core/config/config.go
  core/console/components/base_templ.go
  core/console/components/block_page_templ.go
  core/console/components/header_bar_templ.go
  core/console/components/home_page_templ.go
  core/console/components/tx_page_templ.go
  core/console/console.go
  core/contracts/contracts.go
  core/contracts/utils.go
  core/db/models.go
  core/db/reads.sql.go
  core/db/sql/migrations/00004_latest_block_state.sql
  core/db/sql/migrations/00005_registered_nodes.sql
  core/db/sql/reads.sql
  core/db/sql/writes.sql
  core/db/writes.sql.go
  core/gen/proto/protocol.pb.go
  core/gen/proto/protocol_grpc.pb.go
  core/go.mod
  core/go.sum
  core/grpc/server.go
  core/infra/dev_config/content-one.docker.env
  core/infra/dev_config/content-three.docker.env
  core/infra/dev_config/content-two.docker.env
  core/infra/dev_config/discovery-one.docker.env
  core/infra/dev_config/sandbox-one.env
  core/infra/docker-compose.yml
  core/main.go
  core/protocol.proto
  core/registry_bridge/bridge.go
  core/registry_bridge/query.go
  core/registry_bridge/register.go
  core/registry_bridge/registry.go
  core/registry_bridge/state.go
  core/run.go
  core/server/genesis.go
  core/server/nodes.go
  core/server/server.go
  core/setup.go
Labels: size/XXL

#9636 [PAY-3370] Always use encoded content IDs in chats
  comms/discovery/db/queries/get_chat_messages.go
  comms/discovery/db/queries/get_chats.go
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/M

#9639 Fix purchasers count in chat blast modal
  packages/common/src/api/user.ts
Labels: size/XS

#9637 [C-4956] Add mobile comments sort ui
  packages/mobile/src/components/comments/CommentDrawerHeader.tsx
  packages/mobile/src/components/comments/CommentSortBar.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/M

#9642 core follow-ons: use main dir and correct registry address
  core/config/config.go
  core/setup.go
Labels: size/M

#9635 Revert "Cycle solana RPC connections better (#9147)"
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/trackListenInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
Labels: size/S

#9634 Add createUserBankIfNeeded call to trending rewards bug
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
Labels: size/S

#9643 fix core stage registry addr
  core/config/config.go
Labels: size/S

#9513 Add stems api for v1
  .changeset/curvy-olives-roll.md
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/models/Stem.ts
  packages/libs/src/sdk/api/generated/default/models/StemsResponse.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
Labels: size/L

#9644 [PAY-3411] Enable monetization for everyone when network cut is enabled
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/S

#9641 [PAY-3365] Chat reaction sets chat is_hidden to false
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
Labels: size/S

#9640 Display audience counts in chat blast items
  packages/common/src/api/user.ts
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/M

#9648 core: retry registration faster and always persist app state
  core/chain/abci.go
  core/chain/register_node.go
  core/registry_bridge/bridge.go
  core/registry_bridge/register.go
  core/registry_bridge/registry.go
  core/run.go
  core/sdk/sdk.go
Labels: size/L

#9633 [C-4975] Comments pagination
  .changeset/sweet-houses-type.md
  packages/common/src/api/comments.ts
  packages/common/src/api/track.ts
  packages/common/src/audius-query/createApi.ts
  packages/common/src/audius-query/types.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/common/src/context/comments/commentsHooks.ts
  packages/common/src/context/commentsContext.tsx
  packages/common/src/context/index.ts
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/api/generated/default/apis/CommentsApi.ts
  packages/libs/src/sdk/api/generated/default/models/CommentResponse.ts
  packages/libs/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
Labels: size/XL

#9652 Fix chat blast tests
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/rpcz/chat_test.go
Labels: size/S

#9655 Set audienceContentType=track for remix chat blasts
  .changeset/strong-emus-exist.md
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/M

#9654 [QA-1545] Fix cover art size on album search results
  packages/web/src/components/collection/CollectionCard.test.tsx
  packages/web/src/components/collection/CollectionCard.tsx
Labels: size/XS

#9649 [PAY-3420] Update styles on checkout UI
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/AudioMatchSection.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PayExtraFormSection.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/harmony-native/icons.ts
  packages/web/src/components/summary-table/SummaryTable.tsx
Labels: size/L

#9638 [C-4872, C-4993, QA-1538] Add ComposerInput component and update comments and DMs to user the input
  packages/common/src/hooks/chats/useAudiusLinkResolver.ts
  packages/harmony/src/components/comments/SendIcon/SendIcon.tsx
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/input/TextInput/TextInput.mdx
  packages/harmony/src/components/input/TextInput/TextInput.stories.tsx
  packages/harmony/src/components/popup/Popup.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/components/AutocompleteText.tsx
  packages/web/src/components/composer-input/index.ts
  packages/web/src/components/composer-input/types.ts
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/discovery-node-selection/DiscoveryNodeSelection.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.module.css
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
  packages/web/src/ssr/util.ts
Labels: size/XXL

#9662 fix staging sync bug
  core/chain/abci.go
  core/chain/finalize.go
  core/config/genesis/stage.json
  core/infra/Dockerfile.dev
  core/registry_bridge/register.go
Labels: size/M

#9630 [C-5005] Add comment counts
  packages/common/src/adapters/track.ts
  packages/common/src/models/Search.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/isLongFormContent.ts
  packages/discovery-provider/ddl/functions/handle_comment.sql
  packages/discovery-provider/ddl/migrations/0094_add_comment_count.sql
  packages/discovery-provider/integration_tests/models/test_aggregate_counters.py
  packages/discovery-provider/integration_tests/tasks/test_update_aggregates.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/aggregate_track.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/queries/response_name_constants.py
  packages/discovery-provider/src/tasks/update_aggregates.py
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/generated/default/models/Track.ts
  packages/libs/src/sdk/api/generated/full/models/SearchTrackFull.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/utils/types.ts
  packages/mobile/src/components/audio/useSavePodcastProgress.ts
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/TrackStats.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/stats/Stats.tsx
  packages/web/src/components/track/desktop/stats/StatsText.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/track-page/utils.ts
Labels: size/XL

#9653 [PAY-3395] Chat sort order prefers blasts
  comms/discovery/db/queries/get_chats.go
Labels: size/XS

#9651 [PAY-3416] Adds v1 account endpoint
  packages/discovery-provider/integration_tests/queries/test_get_users_account.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/playlist_library.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/exceptions.py
  packages/discovery-provider/src/queries/get_users_account.py
  packages/libs/src/sdk/api/generated/default/models/User.ts
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/libs/src/sdk/api/generated/full/models/AccountFull.ts
  packages/libs/src/sdk/api/generated/full/models/UserAccountResponseFull.ts
  packages/libs/src/sdk/api/generated/full/models/UserFull.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
Labels: size/XL

#9646 [QA-1542] Fix mobile top supporters crashing profile page
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
Labels: size/S

#9647 [QA-1529] Add guard for -1 ids to audius-query api hooks
  packages/common/src/api/collection.ts
  packages/common/src/api/track.ts
  packages/common/src/api/user.ts
Labels: size/S

#9658 [QA-1513] Remove validation on payout wallet
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#9668 fix typecheck in ChatBlastSelectAudienceFields
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
Labels: size/XS

#9661 [QA-1528] Move audius-query force ref tracking to useState
  packages/common/src/api/account.ts
  packages/common/src/api/comments.ts
  packages/common/src/audius-query/createApi.ts
Labels: size/M

#9667 fix type for spl_usdc_payout_wallet on user adapter
  packages/common/src/adapters/user.ts
Labels: size/XS

#9669 fix typecheck on main
  packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/S

#9566 Periodic SLA rollups for block proposals
  core/Makefile
  core/chain/abci.go
  core/chain/auditor.go
  core/chain/finalize.go
  core/chain/node.go
  core/config/config.go
  core/console/components/sla_page.templ
  core/console/components/sla_page_templ.go
  core/console/console.go
  core/console/sla_page.go
  core/db/models.go
  core/db/reads.sql.go
  core/db/sql/migrations/00006_sla_rollups.sql
  core/db/sql/reads.sql
  core/db/sql/writes.sql
  core/db/writes.sql.go
  core/gen/proto/protocol.pb.go
  core/protocol.proto
  core/run.go
  core/scripts/sandbox.go
  dev-tools/compose/docker-compose.yml
Labels: size/XL

#9671 add web3manager to trending rewards bot
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/libs.ts
Labels: size/S

#9656 [PAY-3213] ChatListBlastItem mobile UI
  packages/common/src/hooks/chats/index.ts
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/screens/chat-screen/ChatListBlastItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/L

#9579 [DOCS] - API doc examples with "real" data samples
  docs/docs/developers/api/get-authorized-apps.api.mdx
  docs/docs/developers/api/get-bulk-playlists.api.mdx
  docs/docs/developers/api/get-bulk-tracks.api.mdx
  docs/docs/developers/api/get-bulk-users.api.mdx
  docs/docs/developers/api/get-connected-wallets.api.mdx
  docs/docs/developers/api/get-developer-app.api.mdx
  docs/docs/developers/api/get-developer-apps.api.mdx
  docs/docs/developers/api/get-favorites.api.mdx
  docs/docs/developers/api/get-followers.api.mdx
  docs/docs/developers/api/get-following.api.mdx
  docs/docs/developers/api/get-playlist-access-info.api.mdx
  docs/docs/developers/api/get-playlist-by-handle-and-slug.api.mdx
  docs/docs/developers/api/get-playlist-tracks.api.mdx
  docs/docs/developers/api/get-playlist.api.mdx
  docs/docs/developers/api/get-related-users.api.mdx
  docs/docs/developers/api/get-reposts.api.mdx
  docs/docs/developers/api/get-subscribers.api.mdx
  docs/docs/developers/api/get-supported-users.api.mdx
  docs/docs/developers/api/get-supporters.api.mdx
  docs/docs/developers/api/get-tips.api.mdx
  docs/docs/developers/api/get-top-track-tags.api.mdx
  docs/docs/developers/api/get-track-access-info.api.mdx
  docs/docs/developers/api/get-track-top-listeners.api.mdx
  docs/docs/developers/api/get-track.api.mdx
  docs/docs/developers/api/get-tracks-by-user.api.mdx
  docs/docs/developers/api/get-trending-playlists.api.mdx
  docs/docs/developers/api/get-trending-tracks.api.mdx
  docs/docs/developers/api/get-underground-trending-tracks.api.mdx
  docs/docs/developers/api/get-user-by-handle.api.mdx
  docs/docs/developers/api/get-user-id-from-wallet.api.mdx
  docs/docs/developers/api/get-user.api.mdx
  docs/docs/developers/api/inspect-track.api.mdx
  docs/docs/developers/api/search-playlists.api.mdx
  docs/docs/developers/api/search-tracks.api.mdx
  docs/docs/developers/api/search-users.api.mdx
  docs/sidebars.js
Labels: size/M

#9675 remove max skipped tx check
  packages/discovery-provider/src/queries/get_skipped_transactions.py
Labels: size/XS

#9676 lower % for skip threshold
  packages/discovery-provider/src/queries/confirm_indexing_transaction_error.py
Labels: size/XS

#9664 [C-5010] Add comment reply counts
  packages/common/src/api/comments.ts
  packages/common/src/messages/comments.ts
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/mobile/src/components/comments/mock-data.ts
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/M

#9674 [PAY-3386] Implement mobile pay with anything
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/payment-method/TokenPicker.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/wallet-connect/ConnectNewWalletButton.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectModalScreen.tsx
  packages/mobile/src/screens/wallet-connect/types.ts
  packages/mobile/src/screens/wallet-connect/usePhantomConnect.ts
  packages/mobile/src/store/storeContext.ts
  packages/mobile/src/store/utils/phantomWalletConnect.ts
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/mobile/src/store/wallet-connect/sagas/index.ts
  packages/mobile/src/store/wallet-connect/slice.ts
  packages/mobile/src/store/wallet-connect/types.ts
Labels: size/L

#9670 [C-4966|C-4967] E2E working comment reactions
  packages/common/src/api/comments.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/common/src/context/comments/commentsHooks.ts
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/libs/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBadge.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentSectionMobile.tsx
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/L

#9659 [C-4954] mobile comments pagination
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/M

#9684 Fix pay with anything
  packages/common/src/store/purchase-content/sagas.ts
  packages/libs/src/sdk/api/albums/AlbumsApi.ts
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectModalScreen.tsx
  packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
  packages/mobile/src/screens/wallet-connect/types.ts
  packages/mobile/src/screens/wallet-connect/usePhantomConnect.ts
  packages/mobile/src/utils/navigation.ts
Labels: size/M

#9685 [QA-1711] Fix remix field not editable
  packages/web/src/components/data-entry/ContextualMenu.module.css
Labels: size/XS

#9698 [QA-1712] Fix trending header
  packages/web/src/components/header/desktop/Header.tsx
  packages/web/src/components/header/desktop/HeaderGutter.tsx
  packages/web/src/components/page/Page.module.css
  packages/web/src/components/page/Page.tsx
Labels: size/L

#9690 [QA-1587] Fix empty Jupiter quote on page load
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#9688 QA-1624: allow all view notifs through relay
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
Labels: size/S

#9689 [qa-1255] Fix bg color on premium giant track tiles
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/XS

#9701 [QA-990] Persist mobile theme on sign-out
  packages/mobile/src/store/sign-out/sagas.ts
Labels: size/XS

#9691 Remove trending tracks from underground trending
  packages/discovery-provider/src/queries/get_underground_trending.py
Labels: size/XS

#9692 [QA-1563] Close locked content drawer on CTA click
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
Labels: size/XS

#9696 [QA-1586] Rewards Page: 1px boder, 1px divider
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Labels: size/XS

#9699 QA-1378: fix withdrawal history extra grey space
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/XS

#9700 Remove deleted tracks from top tags
  packages/discovery-provider/src/queries/get_top_user_track_tags.py
Labels: size/XS

#9687 [QA-1552] Fix incorrect settings card order on web
  packages/common/src/api/comments.ts
  packages/common/src/models/USDCTransactions.ts
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/api/comments/types.ts
  packages/libs/src/sdk/index.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/M

#9697 [QA-1143] Update settings page download section
  packages/common/src/messages/settings.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/ssr/util.ts
Labels: size/S

#9703 [QA-1107] Fix TrackTile title lengths for podcasts
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/XS

#9705 QA-1715 Fix horizontal scrollbar in scheduled release
  packages/web/src/components/modal-radio/ModalRadioItem.module.css
Labels: size/XS

#9704 [QA-1546] Special access embed player
  packages/embed/src/components/artwork/Artwork.jsx
  packages/embed/src/components/collection/CollectionPlayerCard.jsx
  packages/embed/src/components/dog-ear/DogEar.jsx
  packages/embed/src/components/dog-ear/DogEar.module.css
  packages/embed/src/components/playbutton/PlayButton.jsx
  packages/embed/src/components/playbutton/PlayButton.module.css
  packages/embed/src/components/track/TrackPlayerCard.jsx
  packages/embed/src/components/track/TrackPlayerCompact.jsx
  packages/embed/src/components/track/TrackPlayerCompact.module.css
  packages/embed/src/components/track/TrackPlayerTiny.jsx
Labels: size/L

#9702 [QA-808] Clip long artist names on mobile signup
  packages/mobile/src/components/core/UserDisplayName.tsx
Labels: size/S

#9693 [QA-1564] Redirect to feed if user is already authed
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
Labels: size/S

#9706 [QA-874] Fix shadow spacing on mobile profile artist badge
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
Labels: size/XS

#9709 [QA-1548] Fix create playlist
  packages/common/src/utils/route.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
  packages/web/src/components/card-legacy/desktop/CollectionArtCard.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
  packages/web/src/public-site/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#9710 [QA-1502] Fix Add Funds modal hint spacing
  packages/web/src/components/withdraw-usdc-modal/components/Hint.module.css
  packages/web/src/components/withdraw-usdc-modal/components/Hint.tsx
Labels: size/S

#9707 QA-1028: disable artist preview on signup for users with no tracks
  packages/web/src/components/follow-artist-card/FollowArtistCard.tsx
  packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
Labels: size/S

#9715 [QA-1714] Fix mobile web track-page loading
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/trackTileMessages.ts
Labels: size/S

#9722 Remove dashboard from crane docker image tagging ci
  .circleci/src/commands/@docker-commands.yml
Labels: size/S

#9725 [QA-291] Fix explore page perspective card sensitivity
  packages/web/src/pages/explore-page/collections.ts
Labels: size/S

#9712 [QA-1588] Update reload anyway button styling
  packages/web/src/components/unload-dialog/UnloadDialog.tsx
Labels: size/XS

#9718 [QA-1483] Remove artist-pick in feed
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
Labels: size/XS

#9726 Stop music on signout
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/XS

#9728 [QA-1716] Fix removing songs from playlists
  packages/web/src/common/store/pages/collection/lineups/sagas.js
Labels: size/XS

#9713 [QA-1350] Remove links for deleted tracks in tracks table
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/M

#9732 Fix crane script again
  .circleci/src/commands/@docker-commands.yml
Labels: size/XS

#9731 [QA-1516] Hide share button on hidden milestones
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/isEntityHidden.ts
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/web/src/components/notification/Notification/MilestoneNotification.tsx
Labels: size/M

#9724 Inline transcode
  mediorum/server/serve_upload.go
  mediorum/server/serve_upload_test.go
  mediorum/server/transcode.go
Labels: size/L

#9694 [QA-1692] Fix inconsistent font weight in upload text
  packages/web/src/components/upload/Dropzone.tsx
Labels: size/XS

#9708 [QA-1134] Fix styles for date picker on scheduled release modal
  packages/web/src/components/edit/fields/DatePickerField.module.css
Labels: size/S

#9734 [QA-1472] Fix GiantTrackTile spacing
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/TrackStats.tsx
Labels: size/L

#9716 [QA-1553] Remove extra space below mobile profile socials
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
Labels: size/XS

#9727 [QA-1652] Add loading state to connected wallets
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx
Labels: size/L

#9738 [QA-1610] Fix mobile collection edit validatation
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionForm.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
Labels: size/M

#9729 [QA-1487] Fix camera icon in avatar
  packages/harmony/src/components/artwork/Artwork.tsx
Labels: size/XS

#9733 [QA-1719] Increase user bio cap in indexing
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XS

#9730 [QA-1589] Improve track search for titles without spaces
  packages/discovery-provider/src/queries/search_es.py
Labels: size/XS

#9721 [QA-1462] Fix delete account button spacing
  packages/web/src/pages/deactivate-account-page/DeactivateAccountPage.tsx
Labels: size/XS

#9737 [QA-1590] Remove private filter on album backlink
  packages/trpc-server/src/routers/track-router.ts
Labels: size/XS

#9717 [QA-1596] Fix timestamp for adding track to playlist
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
Labels: size/XS

#9741 [QA-1340] Fix page header grossness
  packages/web/src/components/page/Page.module.css
  packages/web/src/components/page/Page.tsx
Labels: size/M

#9746 [DOCS] - amplify hackathon announcement bar
  docs/docusaurus.config.js
  docs/src/css/custom.css
Labels: size/M

#9747 Fix null query in search
  packages/web/src/pages/search-page-v2/hooks.ts
Labels: size/XS

#9536 [DOCS] Update logo styling
  docs/docusaurus.config.js
  docs/i18n/en/docusaurus-theme-classic/navbar.json
  docs/static/img/logo-white.png
  docs/static/img/logo.png
Labels: size/XS

#9739 Reduce log output, add flag to retranscode.
  mediorum/crudr/client.go
  mediorum/server/audio_analysis.go
  mediorum/server/serve_upload.go
  mediorum/server/serve_upload_test.go
  mediorum/server/server.go
  mediorum/server/transcode.go
Labels: size/M

#9748 Bump android build number
  packages/mobile/android/app/build.gradle
Labels: size/XS

#9749 App Delight POC
  packages/mobile/src/hooks/useIsScreenReady.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
Labels: size/XL

#9750 Bump mobile app to 114
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9751 Revert "App Delight POC (#9749)"
  packages/mobile/src/hooks/useIsScreenReady.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
Labels: size/XL

#9752 [QA-1723] Fix filter options button helper text
  packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
Labels: size/S

#9742 [QA-1646] Fix saga for watching uploaded tracks and refreshing profile
  packages/common/src/store/upload/actions.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/watchUploadTracksSaga.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#9740 [QA-1713] Add filter input to feature flag modal
  packages/common/src/utils/fuzzySearch.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/L

#9755 Fix challenge summary table
  packages/web/src/components/summary-table/SummaryTable.tsx
Labels: size/XS

#9763 [C-5020] Search filter fixes for FilterButton
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/internal/Menu.tsx
  packages/harmony/src/components/select/Select/Select.tsx
  packages/harmony/src/components/select/Select/types.ts
Labels: size/L

#9682 Add tab completion for compose UI autocomplete
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/components/AutocompleteText.tsx
Labels: size/L

#9761 [C-4871] Add timestamp highlighting for composer input
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/types.ts
Labels: size/M

#9744 [DOCS] Running audius-ctl on same Node setup documentation
  docs/docs/node-operator/migration-guide.mdx
  docs/docs/node-operator/setup/advanced.mdx
  docs/docs/node-operator/setup/installation.mdx
Labels: size/L

#9743 [QA-1326] Update challenge button labels to match spec
  packages/common/src/utils/challenges.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChecks.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ReferralRewardContents.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/audio-rewards-page/config.tsx
Labels: size/M

#9764 Fixing lint from bad merge
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/XS

#9672 [C-4943] Add comment sort
  packages/common/src/api/comments.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/mobile/src/components/comments/CommentSortBar.tsx
  packages/web/src/components/comments/CommentHeader.tsx
  packages/web/src/components/comments/CommentSortBar.tsx
Labels: size/L

#9657 [C-4988] Update mobile TrackScreen layout for remixes + comments
  packages/mobile/src/components/co-sign/CoSign.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/explore-screen/tabs/ForYouTab/PremiumTracksScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Labels: size/L

#9677 [C-4968] Sort pinned comments to top
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_comments.py
Labels: size/M

#9678 [C-4971] Add comment pin e2e
  packages/common/src/api/comments.ts
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
Labels: size/L

#9745 Update issue templates
  .github/ISSUE_TEMPLATE/api-sdk-bug-report.md
  .github/ISSUE_TEMPLATE/api-sdk-feature-request.md
Labels: size/M

#9765 Fix composer input error and styling for DMs
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/types.ts
  packages/web/src/pages/chat-page/ChatPage.module.css
Labels: size/S

#9762 Harmonize web challenge UI
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ProgressDescription.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ProgressReward.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
Labels: size/L

#9679 [C-4973] Add edit comment e2e
  packages/common/src/api/comments.ts
  packages/common/src/messages/comments.ts
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/libs/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/mock-data.ts
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
Labels: size/L

#9756 [C-5014] Remove search input auto-correct
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/XS

#9757 [C-1601] Fix verified badge, Improve text-link
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx
  packages/mobile/src/components/user-link/UserLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/types.ts
Labels: size/L

#9753 core: remove kv store
  core/chain/abci.go
  core/console/tx_page.go
  core/db/models.go
  core/db/reads.sql.go
  core/db/sql/migrations/00007_drop_kv_store.sql
  core/db/sql/reads.sql
  core/db/sql/writes.sql
  core/db/writes.sql.go
  core/gen/proto/protocol.pb.go
  core/gen/proto/protocol_grpc.pb.go
  core/grpc/server.go
  core/protocol.proto
  core/scripts/sandbox.go
  core/test/integration/kv_store_test.go
Labels: size/L

#9768 Fix typecheck
  packages/libs/src/services/dataContracts/EntityManagerClient.ts
Labels: size/XS

#9759 core: rename "events" to "transactions"
  core/accounts/signature_test.go
  core/chain/abci.go
  core/chain/auditor.go
  core/chain/finalize.go
  core/chain/register_node.go
  core/config/genesis/stage.json
  core/console/tx_page.go
  core/gen/proto/protocol.pb.go
  core/gen/proto/protocol_grpc.pb.go
  core/grpc/server.go
  core/protocol.proto
  core/registry_bridge/register.go
  core/scripts/sandbox.go
  core/sdk/overrides.go
  core/test/integration/plays_test.go
Labels: size/L

#9680 [C-4970, C-4825] Add comment reports
  packages/common/src/api/comments.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/common/src/context/comments/commentsHooks.ts
  packages/common/src/messages/comments.ts
  packages/discovery-provider/ddl/migrations/0095_add_comment_reports.sql
  packages/discovery-provider/src/models/comments/comment_report.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/services/EntityManager/types.ts
  packages/libs/src/services/dataContracts/EntityManagerClient.ts
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/confirmation-modal/ConfirmationModal.tsx
  packages/web/src/components/confirmation-modal/index.ts
Labels: size/L

#9769 [C-5011] Add comment_count to es-indexer
  packages/discovery-provider/integration_tests/queries/test_search_track_tags.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/queries/search_es.py
  packages/es-indexer/src/indexers/TrackIndexer.ts
  packages/es-indexer/src/listener.ts
  packages/es-indexer/src/setup.ts
  packages/es-indexer/src/types/docs.ts
Labels: size/S

#9771 clm report: artist name falls back to handle
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
Labels: size/L

#9767 [PAY-3208] Web chat blast header
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/utils/chatUtils.ts
  packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/chat-page/components/UserChatHeader.tsx
  packages/web/src/utils/hashIds.ts
Labels: size/L

#9683 [PAY-3367] Mobile chat blast audience/content selection
  packages/common/src/hooks/chats/index.ts
  packages/common/src/hooks/chats/usePurchasersAudience.ts
  packages/common/src/hooks/chats/useRemixersAudience.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectContentScreen.tsx
  packages/mobile/src/screens/create-chat-blast-screen/CreateChatBlastNavigator.tsx
  packages/mobile/src/screens/form-screen/FormScreen.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/XL

#9775 Fix harmony tests
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/internal/Menu.tsx
  packages/harmony/src/components/select/Select/Select.tsx
Labels: size/S
