Repository AudiusProject/apps, pull requests merged in 2024-11, with the labels that each got.

#10296 Fix fastlane version number check
  packages/mobile/android/app/build.gradle
  packages/mobile/android/settings.gradle
  packages/mobile/ios/fastlane/Fastfile
Labels: size/XS

#10306 Add react-native patch to fix animation error
  packages/mobile/patches/react-native+0.74.6.patch
Labels: size/S

#10308 [QA-1807] Fix Profile Page: Add entry to totalTileHeight map of 140 for grid lineup variant
  packages/web/src/components/lineup/LineupProvider.tsx
Labels: size/XS

#10282 Harmony build to jail
  .circleci/src/workflows/harmony.yml
Labels: size/M

#10309 Fix react-native patch
  packages/mobile/patches/react-native+0.74.6.patch
Labels: size/XS

#10100 Support usdc in album zod schema
  packages/sdk/src/sdk/api/albums/types.ts
Labels: size/S

#10310 Use skeletons for track and collection screens
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/XS

#10301 [C-5342] Upgrade react-native to 0.75
  package-lock.json
  packages/common/package.json
  packages/ddex/entrypoint/package.json
  packages/ddex/webapp/client/package.json
  packages/discovery-provider/plugins/notifications/package.json
  packages/embed/package.json
  packages/harmony/package.json
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.kt
  packages/mobile/android/build.gradle
  packages/mobile/android/gradle/wrapper/gradle-wrapper.properties
  packages/mobile/android/gradlew
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/PrivacyInfo.xcprivacy
  packages/mobile/ios/Gemfile
  packages/mobile/ios/Gemfile.lock
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/patches/react-native-pager-view+6.2.3.patch
  packages/mobile/patches/react-native-screens+3.29.0.patch
  packages/mobile/src/components/video/AutoSizeVideo.tsx
  packages/mobile/src/services/createPrivateKey.ts
  packages/web/package.json
  patches/react-native-inset-shadow+1.0.3.patch
  protocol-dashboard/package.json
Labels: size/XXL

#10313 Add fast crypto patch
  packages/mobile/patches/react-native-fast-crypto+2.2.0.patch
Labels: size/S

#10314 Remove harmony workflow
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/workflows/harmony.yml
Labels: size/M

#10307 [PAY-3564][PAY-3567][PAY-3566] Rights attribution enhancements
  packages/common/src/messages/edit.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/edit/PriceAndAudienceField/PremiumRadioField/TrackPriceField.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedScreen.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/RightsDeclaration.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Labels: size/L

#10315 Upgrade react to 18.3.1
  docs/package.json
  monitoring/healthz/package.json
  package-lock.json
  package.json
  packages/common/package.json
  packages/create-audius-app/examples/react-hono/package.json
  packages/create-audius-app/examples/react/package.json
  packages/ddex/entrypoint/package.json
  packages/ddex/webapp/client/package.json
  packages/harmony/package.json
  packages/mobile/package.json
  packages/web/package.json
  packages/web/src/common/utils/isMobileWeb.ts
  packages/web/src/utils/clientUtil.ts
  protocol-dashboard/package.json
Labels: size/M

#10317 Upgrade mobile apps to 1.1.122
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/patches/react-native+0.75.4.patch
Labels: size/S

#10319 Remove primary/secondary loading for feed screen
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
Labels: size/M

#10321 Upgrade xcode to 16.1
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
Labels: size/S

#10323 Upgrade ruby version to 3.3.5
  .ruby-version
  packages/mobile/ios/Gemfile.lock
  packages/mobile/ios/Podfile.lock
Labels: size/XS

#10322 [C-5367] Fix harmony-native button initial color
  package-lock.json
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
  packages/mobile/patches/react-native+0.74.6.patch
  packages/mobile/patches/react-native-radial-gradient+1.1.4.patch
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextPressable.tsx
Labels: size/M

#10324 Fix android build
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .ruby-version
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: size/S

#10325 Fix ios and android builds
  packages/mobile/android/settings.gradle
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/XS

#10318 Update mobile app versions during client release
  .circleci/config.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/workflows/mobile.yml
Labels: size/S

#10274 [C-5348] Add premium-extras UI
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useCollectionDogEar.tsx
  packages/common/src/hooks/useTrackDogEar.tsx
  packages/common/src/models/DogEar.ts
  packages/common/src/models/Track.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/common/src/utils/index.ts
  packages/embed/src/components/dog-ear/DogEar.jsx
  packages/embed/src/components/dog-ear/DogEar.module.css
  packages/embed/src/components/track/TrackPlayerCard.jsx
  packages/embed/src/components/track/TrackPlayerCompact.jsx
  packages/embed/src/components/track/TrackPlayerContainer.jsx
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/CollectionDogEar.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/core/TrackDogEar.tsx
  packages/mobile/src/components/lineup-tile/GatedTrackLabel.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/collection/CollectionDogEar.tsx
  packages/web/src/components/collection/index.ts
  packages/web/src/components/collection/mobile/CollectionHeader.module.css
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/now-playing/NowPlaying.module.css
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/tile/Tile.tsx
  packages/web/src/components/track/GatedTrackLabel.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/LockedContentDetailsTile.tsx
  packages/web/src/components/track/TrackDogEar.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/trackTileMessages.ts
  packages/web/src/components/track/types.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XXL

#10328 [QA-1798] Close keyboard on submit for comments and DMs on mobile
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/S

#10320 [PAY-3559] Add direct publishing payments to Stems
  packages/common/src/schemas/metadata.ts
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/components/edit/fields/download-availability/DownloadPriceField.tsx
  packages/web/src/components/edit/fields/types.ts
Labels: size/M

#10329 SDK: album upload populates mediorum upload options.
  packages/sdk/src/sdk/api/albums/types.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
  packages/sdk/src/sdk/api/playlists/types.ts
  packages/sdk/src/sdk/api/tracks/TrackUploadHelper.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
Labels: size/M

#10331 Fix connect-verified indexing
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/S

#10330 Update ios icons
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/Icon-Dark-1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/Icon-Dark-1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/Icon-Tinted-1024x1024.png
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/M

#10332 Add changeset for SDK premium album support
  .changeset/thick-maps-design.md
Labels: size/XS

#10335 Fix ios build
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/M

#10333 Fix test for verify user and dispatching challenge
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
Labels: size/M

#10336 [C-5220] Add comment reply animations on mobile
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentThread.tsx
Labels: size/M

#10338 Fix FilterButtonOptionsList label prop
  packages/harmony/src/components/button/FilterButton/FilterButtonOptionsList.tsx
Labels: size/XS

#10339 Fix ddex ownership perms
  packages/discovery-provider/ddl/migrations/0105_fix_durante.sql
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/M

#10337 Minor icon updates
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/AppIcon1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/AppIcon1024x1024~dark.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/AppIcon1024x1024~tinted.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.appiconset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/Icon-Dark-40x40.imageset/Contents.json
Labels: size/M

#10340 Update app icon names to ensure light mode first
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/AppIcon1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/AppIcon1024x1024~dark.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/AppIcon1024x1024~tinted.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.ReleaseCandidate.appiconset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/AppIcon1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/AppIcon1024x1024~dark.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/AppIcon1024x1024~tinted.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.Staging.ReleaseCandidate.appiconset/Contents.json
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.appiconset/AppIcon1024x1024.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.appiconset/AppIcon1024x1024~dark.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.appiconset/AppIcon1024x1024~tinted.png
  packages/mobile/ios/AudiusReactNative/Images.xcassets/AppIcon.appiconset/Contents.json
Labels: size/S

#10311 [PAY-3578] Migrate sign-in out of AudiusBackend
  packages/commands/src/utils.mjs
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/auth/authService.ts
  packages/common/src/services/auth/getWalletAddresses.ts
  packages/common/src/services/auth/hedgehog.ts
  packages/common/src/services/auth/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/hedgehog.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/utils.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/audius-sdk/hedgehog.ts
  packages/web/src/services/audius-sdk/index.ts
  packages/web/src/services/audius-sdk/storageNodeSelector.ts
  packages/web/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/signOut.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#10341 new config restrictions and networks
  pkg/core/config/genesis/prod.json
  pkg/core/config/genesis/stage.json
  pkg/core/core.go
Labels: size/L

#10343 Fix null error
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedScreen.tsx
Labels: size/S

#10346 Make @audius/eth public
  .changeset/twelve-wolves-leave.md
  packages/eth/package.json
Labels: size/XS

#10347 Include @audius/eth in paths filter
  .github/workflows/publish-packages.yml
Labels: size/XS

#10342 [C-5372] Improve access type labels
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useCollectionAccessTypeLabel.ts
  packages/common/src/hooks/useTrackAccessTypeLabel.ts
  packages/common/src/models/AccessType.ts
  packages/common/src/models/index.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/collection/CollectionAccessTypeLabel.tsx
  packages/mobile/src/components/collection/CollectionDogEar.tsx
  packages/mobile/src/components/core/AccessTypeLabel.tsx
  packages/mobile/src/components/lineup-tile/GatedTrackLabel.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileGatedContentLabel.tsx
  packages/mobile/src/components/lineup-tile/LineupTileLabel.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/components/track/TrackAccessTypeLabel.tsx
  packages/mobile/src/components/track/TrackDogEar.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/access-type-label/AccessTypeLabel.tsx
  packages/web/src/components/access-type-label/index.ts
  packages/web/src/components/collection/CollectionAccessTypeLabel.tsx
  packages/web/src/components/lineup/EntityRank.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/track/GatedContentLabel.tsx
  packages/web/src/components/track/GatedTrackLabel.tsx
  packages/web/src/components/track/LineupTileLabel.tsx
  packages/web/src/components/track/TrackAccessTypeLabel.tsx
  packages/web/src/components/track/VisibilityLabel.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/XXL

#10312 [PAY-3573] Add 30s delay to blast websocket and notifs
  comms/discovery/rpcz/apply.go
  packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  packages/discovery-provider/plugins/notifications/src/config.ts
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/L

#10350 Remove scheduled release timezone on access-type-labels
  packages/mobile/src/components/core/AccessTypeLabel.tsx
  packages/web/src/components/access-type-label/AccessTypeLabel.tsx
Labels: size/S

#10351 [C-5375, C-5376] Improve chats & rewards screen loading perf
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
Labels: size/M

#10349 [C-5320] Improve profile screen loading performance
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePicture.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
Labels: size/L

#10358 Fix sign up issue related to formik version issues
  package-lock.json
  packages/common/package.json
  packages/mobile/package.json
Labels: size/XS

#10344 [PAY-3569] Get direct URLs to content node in API response
  .changeset/spotty-emus-pull.md
  packages/commands/src/purchase-content.mjs
  packages/common/src/models/Track.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/tracks/selectors.ts
  packages/common/src/store/cache/tracks/types.ts
  packages/common/src/store/player/selectors.ts
  packages/common/src/store/player/slice.ts
  packages/discovery-provider/src/api/v1/authorization_helpers.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/api/v1/transactions.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_authorization.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/discovery-provider/src/queries/get_underground_trending.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/queries/response_name_constants.py
  packages/discovery-provider/src/utils/auth_middleware.py
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/models/SearchTrackFull.ts
  packages/sdk/src/sdk/api/generated/full/models/TrackFull.ts
  packages/sdk/src/sdk/api/generated/full/models/UrlWithMirrors.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/comments/CommentForm.tsx
Labels: size/XL

#10355 [C- 5357] Fix sign-up redirect
  packages/mobile/src/components/edit/PriceAndAudienceField/PremiumRadioField/TrackPriceField.tsx
  packages/mobile/src/components/fields/SwitchRowField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/CoverAttributionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/utils/ensureLoggedIn.ts
  packages/web/src/common/utils/requiresAccount.ts
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/useCommentActionCallback.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/hooks/useAuthenticatedCallback.ts
  packages/web/src/hooks/useRequiresAccount.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
Labels: size/XL

#10291 Clean up Solana indexing health on discovery
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_tip_reactions.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/queries/get_health_unit_test.py
  packages/discovery-provider/src/queries/get_sol_plays.py
  packages/discovery-provider/src/queries/get_sol_rewards_manager.py
  packages/discovery-provider/src/queries/get_sol_user_bank.py
  packages/discovery-provider/src/queries/get_spl_audio.py
  packages/discovery-provider/src/queries/health_check.py
  packages/discovery-provider/src/queries/notifications.py
  packages/discovery-provider/src/tasks/index_aggregate_tips.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_reactions.py
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/index_solana_plays.py
  packages/discovery-provider/src/tasks/index_spl_token.py
  packages/discovery-provider/src/tasks/index_user_bank.py
  packages/discovery-provider/src/utils/cache_solana_program.py
  packages/discovery-provider/src/utils/redis_constants.py
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/XXL

#10360 Add undefined check for managers before mapping
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
Labels: size/XS

#10345 [PAY-3580] Make user bank logic for first time buyers more robust
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/buy-usdc/utils.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/web/src/common/store/upload/sagaHelpers.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/L

#10353 [PAY-3582][PAY-3583][PAY-3584] Fix bugbash comments for rights declaration
  packages/mobile/src/screens/edit-track-screen/screens/CoverAttributionScreen.tsx
  packages/web/src/components/edit/fields/AdvancedField.tsx
Labels: size/M

#10363 Fix mobile profile header sticky
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
Labels: size/L

#10364 Fix 30s preview generation
  pkg/mediorum/server/replicate.go
  pkg/mediorum/server/transcode.go
Labels: size/S

#10356 [C-5333, C-5334] Fix animated button perf; fix useFeatureFlag perf
  packages/common/src/hooks/helpers.ts
  packages/common/src/hooks/useGatedContent.ts
  packages/mobile/src/components/core/AnimatedButton.tsx
  packages/mobile/src/hooks/useRemoteConfig.ts
Labels: size/M

#10367 fix mobile lint
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
Labels: size/XS

#10365 Implements AppAuth.hashAndSign
  packages/sdk/src/sdk/services/Auth/AppAuth.ts
Labels: size/S

#10368 fix core tests
  Makefile
  pkg/core/core.go
  pkg/core/gen/proto/protocol.pb.go
  pkg/core/gen/proto/protocol_grpc.pb.go
Labels: size/XS

#10362 Revert moving plays health to solana_indexers key
  .changeset/brown-poems-learn.md
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/queries/get_health_unit_test.py
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
Labels: size/M

#10354 [C-5363] Open comment drawer from feed
  packages/common/src/context/comments/commentsContext.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentPreview.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/comments/CommentPreview.tsx
  packages/web/src/components/comments/CommentSection.tsx
Labels: size/L

#10366 [QA-1802] Fix add to playlist on web
  packages/web/src/components/table/Table.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/S

#10369 [C-5378] Fade in mobile screen content on load
  packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx
  packages/mobile/src/components/core/Screen/ScreenSecondaryContent.tsx
Labels: size/S

#10371 fix genesis
  pkg/core/config/genesis/prod.json
  pkg/core/config/genesis/stage.json
Labels: size/S

#10373 increase timeouts to stabilize block production
  pkg/core/core.go
Labels: size/S

#10375 Add copius logs to change email flow
  packages/common/src/hooks/useChangeEmailFormConfiguration.ts
  packages/identity-service/src/routes/authentication.js
Labels: size/M

#10376 Remove unnecessary identity authentication test
  packages/identity-service/test/authenticationTest.js
Labels: size/L

#10316 ⚠️ [PAY-3570] Refactor track image to use artwork directly
  packages/common/src/adapters/track.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useImageSize2.ts
  packages/common/src/models/Stems.ts
  packages/common/src/models/Track.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/upload/reducer.ts
  packages/common/src/store/upload/types.ts
  packages/mobile/src/screens/upload-screen/components/UploadingTrackTile.tsx
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/upload/sagaHelpers.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/TrackInfo.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/notification/Notification/components/TrackContent.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/components/remix-card/ConnectedRemixCard.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/track/Artwork.tsx
  packages/web/src/components/track/DynamicTrackArtwork.tsx
  packages/web/src/components/track/GiantArtwork.tsx
  packages/web/src/components/track/LockedContentDetailsTile.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/track/mobile/TrackTileArt.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackPurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
  packages/web/src/hooks/useTrackCoverArt.ts
  packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/chat-page/components/ComposePreviewInfo.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
  packages/web/src/pages/visualizer/VisualizerProvider.tsx
Labels: size/XL

#10377 [PAY-3544] Fix flashing empty state on mobile chat screen
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/S

#10380 [QA-1753] Fix Suggested Artists Popup lag
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
Labels: size/XS

#10379 [C-5364] Track and Collection Tile Stat updates
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/harmony/src/components/text-link/types.ts
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/avatar/AvatarList.tsx
  packages/web/src/components/avatar/index.ts
  packages/web/src/components/collection/CollectionLockedStatusPill.tsx
  packages/web/src/components/collection/CollectionTileMetrics.tsx
  packages/web/src/components/collection/CollectionTileStats.tsx
  packages/web/src/components/entity/VanityMetrics.tsx
  packages/web/src/components/lineup/EntityRank.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/link/TextLink.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/TrackLockedStatusPill.tsx
  packages/web/src/components/track/TrackTileMetrics.tsx
  packages/web/src/components/track/TrackTileStats.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/desktop/stats/Stats.module.css
  packages/web/src/components/track/desktop/stats/Stats.tsx
  packages/web/src/components/track/desktop/stats/StatsText.module.css
  packages/web/src/components/track/desktop/stats/StatsText.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx
  packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx
Labels: size/XXL

#10384 Fix profile screen content not rendering
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Labels: size/XS

#10385 Set is_downloadable when download_conditions are present
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/XS

#10378 Add make targets to force release core image
  Makefile
  scripts/release-core.sh
Labels: size/M

#10390 [C-5368] Default @handles list for comments
  packages/common/src/api/user.ts
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
Labels: size/M

#10395 [C-5336] Load more items on mobile feed/trending
  packages/mobile/src/components/lineup/Lineup.tsx
Labels: size/XS

#10399 [QA-1790] Fix boolean logic error in profile page reducers
  packages/common/src/store/pages/profile/reducer.ts
Labels: size/XS

#10400 [QA-1811] Fix tier change notif capitalization
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
Labels: size/XS

#10388 [QA-1812] Update referred reward progress label
  packages/common/src/utils/challenges.ts
Labels: size/XS

#10401 Fix off-by-one error in fetching mirrors
  packages/discovery-provider/src/queries/query_helpers.py
Labels: size/XS

#10389 Fix concurrent user bank creations at the SDK level
  .changeset/stupid-pens-happen.md
  packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
Labels: size/L

#10397 [PAY-3592] Always mark chat as read (temp fix)
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/S

#10404 Fix trending playlists
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
  packages/discovery-provider/src/queries/get_trending_playlists.py
Labels: size/XS

#10403 [PAY-3585] Prevent async account fetch from delaying left nav if account is cached
  packages/mobile/ios/Podfile.lock
  packages/web/src/common/store/account/sagas.js
Labels: size/S

#10407 Fix mobile profile skeleton background color
  packages/mobile/src/components/skeleton/Skeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
Labels: size/M

#10406 Fix mobile Track/Collection skeleton margins
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
Labels: size/L

#10408 sleep in core indexing
  Makefile
  packages/discovery-provider/src/tasks/index_core.py
  pkg/core/core.go
Labels: size/XS

#10405 [C-5335] Mobile follow button snappy
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx
Labels: size/M

#10410 Add discovery API + sdk support for for user playlists and albums
  .changeset/hot-socks-leave.md
  packages/discovery-provider/integration_tests/queries/test_get_playlists.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_playlists.py
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/AlbumsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/PlaylistsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
Labels: size/XL

#10413 Fix is_downloadable being set erroneously
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/XS

#10414 Fix free tracks not being allowed to be set as downloadable
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/XS

#10393 Fix download file names for ddex
  packages/common/src/utils/fileUtil.test.ts
  packages/common/src/utils/fileUtil.ts
  packages/common/src/utils/fileUtils.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
Labels: size/L

#10416 Revert cocoaods back to 1.13
  packages/mobile/ios/Podfile.lock
Labels: size/XS

#10419 Fix user state issues with signUp breaking follows
  package-lock.json
  packages/libs/src/NativeAudiusLibs.ts
  packages/libs/src/WebAudiusLibs.ts
  packages/sdk/package.json
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.ts
Labels: size/M

#10409 [QA-1815] Render track actions for deleted tracks in tables
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/XS

#10418 Use rf instead of ref for sign up
  packages/mobile/src/components/challenge-rewards-drawer/ReferralRewardContents.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
Labels: size/S

#10424 Fix client release creation
  .circleci/config.yml
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#10422 [QA-1742][QA-1818] Fix UPC persisting and add ean-13 compatibility
  packages/common/src/messages/edit.ts
  packages/libs/src/api/entityManager.ts
  packages/libs/src/services/creatorNode/CreatorNode.ts
  packages/libs/src/services/schemaValidator/schemas/playlistSchema.json
  packages/mobile/src/screens/edit-collection-screen/AdvancedAlbumScreen.tsx
  packages/web/src/components/edit/fields/AdvancedAlbumField.tsx
Labels: size/S

#10425 Make email check case insensitive
  packages/identity-service/src/routes/authentication.js
Labels: size/XS

#10427 [QA-1819] Fix missing userId in backend calls
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/common/store/social/tracks/store.test.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#10429 [QA-1822] Only extend playlists at the api level
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/queries/get_top_playlists_es.py
  packages/discovery-provider/src/queries/get_trending_playlists.py
Labels: size/S

#10381 SDK adds signature query param to uploads
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/services/Auth/UserAuth.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManager.ts
  packages/sdk/src/sdk/services/Storage/Storage.ts
  packages/sdk/src/sdk/services/Storage/types.ts
  pkg/mediorum/server/serve_upload.go
  pkg/mediorum/server/server_basic_auth.go
Labels: size/M

#10417 Do not require tracks in full playlist response type
  .changeset/quick-eels-pay.md
  packages/discovery-provider/src/api/v1/models/playlists.py
  packages/discovery-provider/src/api/v1/users.py
  packages/sdk/src/sdk/api/generated/full/models/PlaylistFull.ts
Labels: size/S

#10421 audiusd + audius-docker-compose compatibility
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/jobs/@audiusd-jobs.yml
  .circleci/src/workflows/audiusd.yml
  Makefile
  cmd/audiusd/Dockerfile
  cmd/audiusd/entrypoint.sh
  cmd/audiusd/env/dev.env
  cmd/audiusd/env/prod.env
  cmd/audiusd/env/stage.env
  cmd/audiusd/main.go
  pkg/core/config/config.go
  pkg/mediorum/mediorum.go
Labels: size/L

#10352 Safer splits
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
  packages/es-indexer/src/indexNames.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
Labels: size/S

#10433 Fix track edit preview transcode missing wallet
  packages/libs/src/NativeAudiusLibs.ts
  packages/libs/src/WebAudiusLibs.ts
Labels: size/XS

#10434 [C-5391] Add session replay to sentry
  packages/web/src/services/sentry.ts
Labels: size/S

#10432 postUpload actually reads signature from querystring
  pkg/mediorum/server/serve_upload.go
Labels: size/XS

#10439 Fix Profile page crash
  packages/common/src/store/pages/profile/reducer.ts
Labels: size/XS

#10440 [C-5381] Fast sign-up for referrals
  packages/common/src/schemas/sign-on/finishProfileSchema.ts
  packages/common/src/utils/route.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/track/TrackTileStats.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/welcome-modal/WelcomeModal.tsx
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/components/SkipButton.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/LoadingAccountPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/L

#10436 Update DiscoverProvider to handle replacing track audio
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/M

#10442 Allow user lookup for guest accounts
  packages/discovery-provider/src/queries/get_users_account.py
Labels: size/XS

#10437 [C-5399] Add saga and basic setup for track audio replace
  packages/common/src/schemas/metadata.ts
  packages/common/src/store/upload/actions.ts
  packages/discovery-provider/src/tasks/metadata.py
  packages/web/src/common/store/cache/tracks/sagaHelpers.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/L

#10443 [C-5401] Add preview updates for track audio replace
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#10435 [PAY-2943] Migrate track-related AudiusBackend logic to sdk (including track edit)
  .changeset/famous-cherries-trade.md
  packages/common/src/adapters/access.ts
  packages/common/src/adapters/track.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/types/File.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/social/tracks/store.test.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/services/audius-sdk/auth.ts
Labels: size/L

#10444 [QA-1824] Don't filter own playlists in collection library queries
  packages/discovery-provider/integration_tests/queries/test_get_collections_library.py
  packages/discovery-provider/src/queries/get_collection_library.py
Labels: size/L

#10445 Fix USDC user bank creation
  .changeset/twelve-cycles-grow.md
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-usdc/utils.ts
  packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
Labels: size/L

#10446 Fix usages of getTokenAccountInfo to conform to new arg type
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-crypto/sagas.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/buy-usdc/utils.ts
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/S

#10453 [DOCS] - TheGraph URL update
  docs/docs/developers/subgraph/entities.mdx
  docs/docs/developers/subgraph/overview.mdx
Labels: size/XL

#10454 Fix bad useEffects calls in PremiumContentPurchaseDrawer
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/S

#10451 [QA-1827] Fix queuing short profile lineups issue
  packages/web/src/common/store/queue/sagas.ts
Labels: size/S

#10450 Fix track edit sdk issues
  .changeset/polite-seahorses-sit.md
  packages/common/src/adapters/access.ts
  packages/common/src/adapters/track.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
Labels: size/M

#10456 Remove SOLANA_LISTEN_ENABLED feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/identity-service/src/featureFlag.js
Labels: size/XS

#10457 Remove TIPPING_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/identity-service/src/featureFlag.js
  packages/identity-service/src/notifications/sendNotifications/publishNotifications.js
Labels: size/XS

#10449 [PROTO-1979] Endpoint to generate an audio preview for a CID.
  pkg/mediorum/server/db.go
  pkg/mediorum/server/repair.go
  pkg/mediorum/server/serve_upload.go
  pkg/mediorum/server/serve_upload_test.go
  pkg/mediorum/server/server.go
  pkg/mediorum/server/transcode.go
  pkg/mediorum/server/transcode_preview.go
Labels: size/L

#10458 [C-5417] Update track audio replace for sdk change
  packages/common/src/adapters/track.ts
  packages/sdk/src/sdk/api/tracks/types.ts
Labels: size/XS

#10447 [C-5416] Basic guest checkout behind feature flag
  packages/common/src/audius-query/createApi.ts
  packages/common/src/hooks/purchaseContent/constants.ts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/RecordIP.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/account/index.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/cache/users/selectors.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/common/src/store/purchase-content/types.ts
  packages/common/src/store/ui/modals/coinflow-onramp-modal/index.ts
  packages/libs/src/api/Account.ts
  packages/libs/src/api/Users.ts
  packages/libs/src/utils/types.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/XL

#10460 [QA-1840] Fix Offline Mode errors
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/queue/sagas.ts
Labels: size/XS

#10461 Correct reserved handle
  packages/discovery-provider/ddl/migrations/0106_correct_reserved_handle.sql
Labels: size/S

#10467 Remove RATE_CTA_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/rate-cta-drawer/RateCtaReminder.tsx
Labels: size/S

#10469 Remove EARLY_ACCESS feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
Labels: size/M

#10471 Remove PODCAST_CONTROL_UPDATES_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/playback-position/sagas.ts
  packages/common/src/store/player/sagas.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/now-playing-drawer/AudioControls.tsx
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.jsx
  packages/web/src/components/track/PlayPauseButton.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
Labels: size/L

#10475 Remove RELATED_ARTISTS_ON_PROFILE_ENABLED feature flag
  packages/web/src/components/related-artists/RelatedArtists.tsx
Labels: size/S

#10478 Remove misc feature flags
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#10473 Remove LAZY_USERBANK_CREATION_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/account/sagas.js
Labels: size/S

#10474 Remove SDK_DISCOVERY_NODE_SELECTOR feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/M

#10477 Remove DEVELOPER_APPS_PAGE feature flag
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/XS

#10479 Remove DISCOVERY_TIP_REACTIONS feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/ui/reactions/sagas.ts
Labels: size/M

#10465 Fix libpq version dependency
  packages/discovery-provider/Dockerfile.prod
Labels: size/S

#10462 [C-5404] Add FileReplaceContainer component to web
  packages/web/src/components/file-replace-container/FileReplaceContainer.tsx
Labels: size/M

#10476 Remove AI_ATTRIBUTION feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/M

#10482 [C-5430] Add feature flag for track audio replace
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/related-artists/RelatedArtists.tsx
Labels: size/S

#10455 As/core custom mempool
  cmd/core/infra/Dockerfile.tests
  go.mod
  pkg/core/chain/abci.go
  pkg/core/chain/auditor.go
  pkg/core/chain/node.go
  pkg/core/common/converters.go
  pkg/core/common/proto.go
  pkg/core/config/config.go
  pkg/core/config/genesis/dev.json
  pkg/core/core.go
  pkg/core/grpc/server.go
  pkg/core/grpc/tx.go
  pkg/core/mempool/mempool.go
  pkg/core/pubsub/pubsub.go
  pkg/core/registry_bridge/bridge.go
  pkg/core/registry_bridge/register.go
  pkg/core/registry_bridge/registry.go
  pkg/core/test/integration/manage_entity_test.go
  pkg/core/test/integration/openapi_test.go
  pkg/core/test/integration/plays_test.go
  pkg/core/test/integration/utils/nodes.go
Labels: size/XL

#10487 [C-5408] Move delete track action to overflow menu
  packages/common/src/store/ui/modals/delete-track-confirmation-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/harmony/src/components/popup-menu/PopupMenu.module.css
  packages/harmony/src/components/popup-menu/PopupMenu.tsx
  packages/harmony/src/components/popup-menu/types.tsx
  packages/web/src/components/delete-track-confirmation-modal/DeleteTrackConfirmationModal.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#10489 [C-5410] Add ReplaceTrackConfirmation modal
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/replace-track-confirmation-modal/index.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/replace-track-confirmation-modal/ReplaceTrackConfirmationModal.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#10490 Fix aggregate tip indexing and improve Solana indexer health check
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/tasks/index_aggregate_tips.py
Labels: size/XS

#10468 [PROTO-1874] Remove get_feed_sql
  packages/discovery-provider/src/queries/get_feed.py
Labels: size/L

#10480 Remove PREFER_HIGHER_PATCH_FOR_PRIMARY/SECONDARIES feature flags
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
Labels: size/S

#10492 Fix update upload endpoint
  pkg/mediorum/server/serve_upload.go
Labels: size/XS

#10493 [PROTO-1983] rm expired txs from mempool
  pkg/core/chain/abci.go
  pkg/core/mempool/mempool.go
Labels: size/S

#10491 [QA-1842] Fix web date picker time default
  packages/mobile/src/components/core/DateTimeInput.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/web/src/components/edit/fields/DatePickerField.tsx
Labels: size/XS

#10485 [PAY-3605] Fix audius-cmd after account/UserStateManager updates
  .changeset/heavy-moles-speak.md
  package-lock.json
  packages/commands/src/account-managers.mjs
  packages/commands/src/auth-headers.mjs
  packages/commands/src/claim-reward.mjs
  packages/commands/src/create-user-bank.mjs
  packages/commands/src/edit-user.mjs
  packages/commands/src/mint-tokens.mjs
  packages/commands/src/purchase-content.mjs
  packages/commands/src/tip-audio.mjs
  packages/commands/src/tip-reaction.mjs
  packages/commands/src/unfollow.mjs
  packages/commands/src/upload-track.mjs
  packages/commands/src/utils.mjs
  packages/sdk/rollup.config.ts
  packages/sdk/src/sdk/services/Auth/UserAuth.ts
Labels: size/XL
