Repository AudiusProject/apps, pull requests merged in 2024-06, with the labels that each got.

#8682 Fix purchasing albums w/ SDK
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/queries/queries.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
Labels: size/XS

#8685 Flip email deliverable boolean
  packages/identity-service/src/routes/user.js
Labels: size/XS

#8683 [QA-1341] Fix track-tile skeleton
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
Labels: size/M

#8688 Fix SSR trying to load something when going to search route
  packages/web/src/ssr/util.ts
  packages/web/src/utils/route.ts
Labels: size/XS

#8684 Upgrade vector
  monitoring/vector/Dockerfile
Labels: size/XS

#8686 Update mobile app versions
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8690 Add legacy splits formatter to playlists
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#8692 Fix access-info for albums
  packages/commands/src/purchase-content.mjs
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/queries/get_playlists.py
Labels: size/S

#8691 [PAY-3058] Show owner accounts for payout wallet, stub creation of ATA via relay
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
  packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx
  packages/web/src/services/solana/solana.ts
Labels: size/M

#8694 Fix coinflow purchasing with SDK
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/S

#8695 QA-1347: filter query result response formatter on only users that were found
  packages/discovery-provider/src/queries/get_support_for_user.py
Labels: size/S

#8699 Add rate limit for ATA creation
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
Labels: size/M

#8700 Use signer middleware in solana-relay
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
  packages/libs/src/sdk/sdk.ts
Labels: size/S

#8697 Relay to create payout wallet token account
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/M

#8702 Fix assertAllowedRelayInstructions, fix tests, rewrite payout wallet logic
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/M

#8701 Finish payout wallet relay support
  mediorum/Dockerfile.dev
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/signerRecovery.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/libs/src/sdk/sdk.ts
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/L

#8687 [PAY-3070][PAY-3075] Fix a few endpoints incorrectly using current user id
  .changeset/witty-donuts-sit.md
  packages/discovery-provider/integration_tests/queries/test_get_managed_users.py
  packages/discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_managed_users.py
  packages/discovery-provider/src/queries/get_user_listening_history.py
  packages/discovery-provider/src/utils/auth_middleware.py
  packages/libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/pages/history/lineups/sagas.ts
Labels: size/L

#8698 [QA-1343] Update collection page publish button
  packages/harmony/src/components/button/BaseButton/types.ts
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
Labels: size/M

#8689 ONC: add check for old uploads
  packages/discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
Labels: size/XS

#8707 [PAY-3080] Misc. payout wallet UI cleanup
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
  packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx
Labels: size/S

#8704 [PAY-3071][PAY-3072] Fix track listing in manager mode
  packages/discovery-provider/integration_tests/queries/test_get_tracks.py
  packages/discovery-provider/src/api/v1/access_helpers.py
  packages/discovery-provider/src/queries/get_managed_users.py
  packages/discovery-provider/src/queries/get_tracks.py
Labels: size/L

#8710 Add compute budget
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/XS

#8711 Hotfix: Fix non-purchase access gates
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
Labels: size/XS

#8713 Pin turbo in docker files
  packages/commands/Dockerfile.prod
  packages/ddex/processor/Dockerfile
  packages/ddex/publisher/Dockerfile
  packages/ddex/webapp/Dockerfile
  packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
  packages/identity-service/Dockerfile.prod
  packages/libs/Dockerfile
  protocol-dashboard/Dockerfile.dev
  protocol-dashboard/Dockerfile.prod
  protocol-dashboard/Dockerfile.stage
Labels: size/S

#8696 [C-4421] Add mobile UserCard and skeletons
  packages/mobile/src/components/collection-list/CollectionCardSkeleton.tsx
  packages/mobile/src/components/profile-list/ProfileCardSkeleton.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/user-list/ProfileCard.tsx
  packages/mobile/src/components/user-list/UserCard.tsx
  packages/mobile/src/components/user-list/UserCardSkeleton.tsx
  packages/mobile/src/components/user-list/UserList.tsx
  packages/mobile/src/components/user-list/index.ts
  packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx
  packages/mobile/src/harmony-native/utils/styleProps.ts
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/search-results-screen/tabs/ProfilesTab.tsx
  packages/mobile/tsconfig.json
Labels: size/L

#8715 Add optional chaining to ssr render files for images
  packages/web/src/ssr/collection/+onBeforeRender.ts
  packages/web/src/ssr/profile/+onBeforeRender.tsx
  packages/web/src/ssr/track/+onBeforeRender.tsx
Labels: size/S

#8724 correct default discovery listens behavior
  mediorum/main.go
Labels: size/XS

#8706 [PAY-3083] Add user socials in DN
  packages/discovery-provider/ddl/migrations/0073_add_user_socials.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/models/users/user.py
  packages/discovery-provider/src/schemas/user_schema.json
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/discovery-provider/src/utils/user_event_constants.py
  packages/libs/src/sdk/api/generated/default/models/User.ts
  packages/libs/src/sdk/api/generated/full/models/UserFull.ts
Labels: size/L

#8712 [C-4358] Add basic search results to search v2
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/search.ts
  packages/common/src/store/pages/search-results/actions.ts
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/pages/search-page-v2/RecentSearches.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/L

#8723 [PAY-3084] Fix wAUDIO balance fetching
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
Labels: size/M

#8717 Wait for the payout wallet token account creation
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/S

#8726 [C-4360] Update SearchBarV2 to search on input
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/components/search/SearchBarV2.jsx
Labels: size/S

#8722 [QA-1346] Fix select-page dropdown text alignment
  packages/web/src/components/upload/Dropzone.module.css
  packages/web/src/components/upload/Dropzone.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
Labels: size/L

#8721 [QA-1287] Fix multiple popovers on tracks table
  packages/web/src/components/menu/Menu.tsx
  packages/web/src/components/table/components/OverflowMenuButton.tsx
Labels: size/S

#8709 [C-4463] POC add a 'skip check' param to /stream
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_health.py
Labels: size/S

#8734 Fix lint
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/XS

#8667 [C-4443][C-4444] Scheduled album releases
  packages/commands/src/create-playlist.mjs
  packages/discovery-provider/ddl/migrations/0076_playlist_scheduled_release.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/models/playlists/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/discovery-provider/src/tasks/publish_scheduled_releases.py
  packages/libs/src/api/entityManager.ts
  packages/libs/src/services/creatorNode/CreatorNode.ts
  packages/libs/src/utils/types.ts
Labels: size/L

#8731 [QA-865] Fix track mood alignment
  packages/web/src/components/track/GiantTrackTile.module.css
Labels: size/XS

#8735 [C-4466] Update new search results page track preview number
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/M

#8732 [QA-1338] Fix headers for small screens
  packages/web/src/components/header/desktop/Header.jsx
Labels: size/S

#8736 Add test to ensure updating playlist_id fails
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
Labels: size/S

#8730 [PAY-3085] Move payout wallet radio input to labeled
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Labels: size/S

#8729 [PAY-3086] Add verified user rate limit
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
Labels: size/S

#8716 [PAY-2835] Add account switcher to oauth popup
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountListContent.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/oauth-login-page/components/ContentWrapper.tsx
  packages/web/src/pages/oauth-login-page/components/PermissionsSection.tsx
  packages/web/src/pages/oauth-login-page/messages.ts
Labels: size/XL

#8743 on call: fix search on stage
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
Labels: size/S

#8737 [C-4263] Add OptionsFilterButton and implement more search filters
  .changeset/clever-elephants-act.md
  packages/ddex/webapp/client/src/pages/Releases/Releases.tsx
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.mdx
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.stories.tsx
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/harmony/src/components/button/index.ts
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/upload/TrackPreview.tsx
  packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
Labels: size/XL

#8739 [C-4467] Fix path reset on search
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Labels: size/M

#8727 [C-4455] Update otp email
  packages/identity-service/src/notifications/emails/otp.js
  packages/identity-service/src/utils/otp.js
Labels: size/XXL

#8748 Fix small player bugs
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
Labels: size/XS

#8752 Small fix for search results filter button
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/XS

#8750 Fix icon cloud container on drop zone
  packages/web/src/components/upload/Dropzone.tsx
Labels: size/S

#8755 Improve share to twitter copy
  packages/mobile/src/components/challenge-rewards-drawer/TwitterShareButton.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingUndergroundNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
  packages/web/src/components/notification/Notification/AddTrackToPlaylistNotification.tsx
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notification/MilestoneNotification.tsx
  packages/web/src/components/notification/Notification/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/TastemakerNotification.tsx
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/notification/Notification/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notification/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notification/TrendingPlaylistNotification.tsx
  packages/web/src/components/notification/Notification/TrendingTrackNotification.tsx
  packages/web/src/components/notification/Notification/TrendingUndergroundNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/share-modal/messages.ts
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/L

#8728 [PAY-3091] Move social handles out of identity into dn via entity manager
  .changeset/calm-ducks-tan.md
  packages/identity-service/src/routes/instagram.js
  packages/identity-service/src/routes/tiktok.js
  packages/identity-service/src/routes/twitter.js
  packages/libs/src/api/Users.ts
Labels: size/L

#8740 [C-4470, C-4428] Move track edit form to its own page
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/common/src/store/upload/types.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/confirmer-preview/ConfirmerPreview.module.css
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/edit-track/EditTrackModalLegacy.tsx
  packages/web/src/components/edit-track/EditTrackModalNew.tsx
  packages/web/src/components/edit-track/components/PreviewButton.tsx
  packages/web/src/components/edit-track/types.ts
  packages/web/src/components/edit/fields/CollectionTrackFieldArray.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/edit-page/components/AnchoredSubmitRowEdit.module.css
  packages/web/src/pages/edit-page/components/AnchoredSubmitRowEdit.tsx
  packages/web/src/pages/edit-page/index.ts
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/utils/route.ts
  packages/web/src/utils/zIndex.ts
Labels: size/XL

#8738 Normalize solana connections
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/connections.ts
  packages/discovery-provider/src/solana/solana_client_manager.py
Labels: size/S

#8624 [Web][Mobile] Display manager mode notifications [C-4426]
  .env
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ApproveManagerRequestNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RequestManagerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/components/notification/Notification/ApproveManagerRequestNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/RequestManagerNotification.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#8742 [PAY-3093] Update clients to use socials from DN
  packages/common/src/adapters/user.ts
  packages/common/src/hooks/useTwitterButtonStatus.ts
  packages/common/src/messages/sign-on/socialMediaMessages.ts
  packages/common/src/models/User.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/libs/src/api/Users.ts
  packages/libs/src/services/schemaValidator/schemas/userSchema.json
  packages/libs/src/utils/types.ts
  packages/mobile/src/components/share-drawer/utils.ts
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialsAndSites.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/utils/socialMediaMessages.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/EditProfile.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowInstagramAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTwitterAuth.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
  packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
Labels: size/L

#8754 [C-4368] Add mood options filter button to track search filters
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page-v2/utils.tsx
Labels: size/L

#8759 QA-1355: add exit button to web rewards modal
  packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Labels: size/S

#8762 Add trendingBlue and aiGreen harmony colors
  packages/harmony/src/foundations/color/primitive.ts
Labels: size/XS

#8749 [QA-1264] Fix mobile notification ui issues
  packages/web/src/components/notification/NotificationPage.module.css
  packages/web/src/components/notification/NotificationPage.tsx
Labels: size/L

#8760 [C-4365] Add key filter to new search page
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/index.ts
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
Labels: size/L

#8766 [C-4472] Connect EditTrackForm to submit changes
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/MultiTrackSidebar.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/edit-page/components/AnchoredSubmitRowEdit.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
Labels: size/M

#8761 Add mobile storybook instructions
  packages/mobile/README.md
Labels: size/XS

#8751 [QA-1353] Fix cover art blur
  packages/web/src/components/dynamic-image/DynamicImage.tsx
Labels: size/XS

#8753 [QA-1358] Fix long track title in upload
  packages/web/src/components/edit/fields/MultiTrackSidebar.module.css
  packages/web/src/components/edit/fields/MultiTrackSidebar.tsx
Labels: size/M

#8764 [QA-1361] Fix audio-nfts playlist
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/useAddAudioNftPlaylistToLibrary.ts
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
Labels: size/M

#8765 [C-4476] HarmonyNative MusicBadge component
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/MusicBadge/MusicBadge.stories.tsx
  packages/mobile/src/harmony-native/components/MusicBadge/MusicBadge.tsx
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/L

#8771 Add small variant to web Harmony MusicBage
  packages/harmony/src/components/music-badge/MusicBadge.tsx
Labels: size/S

#8773 [QA-1288] Fix tip reactions on mobile
  packages/mobile/src/services/sdk/auth.ts
Labels: size/S

#8776 [Notifications] Update bad snapshot
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/approveManagerRequest.test.ts.snap
Labels: size/XS

#8775 Revert "Display manager mode notifications" [C-4426]
  .env
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ApproveManagerRequestNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RequestManagerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/components/notification/Notification/ApproveManagerRequestNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/RequestManagerNotification.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#8777 Upgrade mobile apps to .101
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8778 [Web][Mobile] Reapply "Display manager mode notifications" [C-4426] without rogue .env
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ApproveManagerRequestNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RequestManagerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/components/notification/Notification/ApproveManagerRequestNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/RequestManagerNotification.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#8779 [C-4475] Consume MusicBadge on track/collection pages
  packages/common/src/models/DogEar.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/card/CollectionDogEar.tsx
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileAiAttribution.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx
  packages/web/src/components/track/Badge.module.css
  packages/web/src/components/track/Badge.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/track-page/utils.ts
Labels: size/L

#8781 Fix monorepo verify
  packages/ddex/webapp/client/src/pages/Releases/Releases.tsx
Labels: size/XS

#8774 [QA-973] Fix top playlists
  packages/discovery-provider/integration_tests/tasks/test_get_top_playlists_es.py
  packages/discovery-provider/src/queries/get_top_playlists_es.py
Labels: size/M

#8763 [C-4512] Implement purchase vendor tracking
  packages/discovery-provider/ddl/functions/handle_usdc_purchase.sql
  packages/discovery-provider/ddl/migrations/0077_purchase_vendor.sql
  packages/discovery-provider/default_config.ini
  packages/discovery-provider/integration_tests/notifications/test_usdc_purchase.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_usdc_purchase_notification.py
  packages/discovery-provider/src/models/users/usdc_purchase.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/M

#8784 Improve listen count checking
  packages/identity-service/default-config.json
  packages/identity-service/src/app.js
  packages/identity-service/src/config.js
  packages/identity-service/src/routes/trackListens.js
Labels: size/M

#8782 [DOCS] - audius-ctl status command
  docs/docs/node-operator/setup/installation.mdx
Labels: size/M

#8787 Add vendor to buyer notification
  packages/discovery-provider/ddl/functions/handle_usdc_purchase.sql
  packages/discovery-provider/integration_tests/notifications/test_usdc_purchase.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_usdc_purchase_notification.py
Labels: size/XS

#8744 [C-4465] Update usdc transactional emails
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcWithdrawal.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
  packages/discovery-provider/plugins/notifications/src/utils/format.ts
Labels: size/XXL

#8769 [C-4366] Add bpm filter for new search page tracks category
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
Labels: size/L

#8746 [PAY-2849] Support gated content in Manager Mode
  .changeset/mean-hairs-jam.md
  packages/common/src/utils/streaming.ts
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_authed_user.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/L

#8783 Temporarily remove mobile account verification
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
Labels: size/S

#8767 [QA-1041] Fix disabled tooltips
  packages/web/src/components/tooltip/Tooltip.tsx
Labels: size/XS

#8790 Add release_date, is_scheduled_release to playlist api
  packages/discovery-provider/src/api/v1/models/playlists.py
  packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
  packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
Labels: size/M

#8791 [C-4371] Add sort buttons to search category views
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/types.ts
  packages/web/src/pages/search-page-v2/BpmFilter.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page-v2/utils.tsx
Labels: size/L

#8792 [C-4441][C-4503] Release date formatting + add date to CollectionCard
  packages/common/src/models/Collection.ts
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#8780 [QA-1094] Fix track info labels
  packages/harmony/src/components/text/Text.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/InfoLabel.module.css
  packages/web/src/components/track/InfoLabel.tsx
  packages/web/src/utils/Moods.tsx
Labels: size/L

#8795 add new graph urls
  comms/discovery/the_graph/discovery_nodes.go
  mediorum/registrar/the_graph.go
  monitoring/uptime/registrar/the_graph.go
  protocol-dashboard/.env.prod
  protocol-dashboard/.env.stage
Labels: size/S

#8786 add listens rate limiter with tests
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.discovery.prod.yml
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/assertRateLimiter.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/rateLimiter.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/assertListenRateLimiter.test.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/L

#8796 [C-4488] Hide actions + play count for hidden content
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#8757 add key + bpm fields to discovery track metadata
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/discovery-provider/ddl/migrations/0077_add_audio_analysis_columns.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/schemas/track_schema.json
  packages/discovery-provider/src/tasks/metadata.py
  packages/es-indexer/src/types/db.ts
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/services/schemaValidator/schemas/trackSchema.json
  packages/libs/src/utils/types.ts
  packages/sql-ts/res/discovery-node.ts
Labels: size/L

#8801 Fix Coinflow purchases via SDK
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
  packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
  scripts/preinstall.sh
Labels: size/L

#8799 [C-4473] Enable edit rules in new edit form
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/AccessAndSaleField.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Labels: size/M

#8798 Clean up transactional email logs
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
Labels: size/XS

#8800 Fix mediorum audio analysis bugs, add better logs
  mediorum/server/audio_analysis.go
  mediorum/server/db.go
Labels: size/M

#8802 [C-4531] Add genre param to search api
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/search.py
  packages/discovery-provider/src/queries/search_es.py
Labels: size/S

#8803 [C-4521] Update search route format and add redirect for legacy route format
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page/SearchPageProvider.jsx
  packages/web/src/pages/search-page/helpers.ts
  packages/web/src/ssr/util.ts
  packages/web/src/store/lineup/lineupForRoute.js
  packages/web/src/utils/route.ts
Labels: size/L

#8804 Poll for Payout Wallet Owner
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
  packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx
  packages/web/src/services/solana/solana.ts
Labels: size/M

#8797 [C-4498] Prefetch stream logic - rework to saga cache listener
  packages/common/src/api/track.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/tracks/selectors.ts
  packages/common/src/store/cache/tracks/types.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#8808 initialize topNumber var
  protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx
Labels: size/XS

#8814 [C-4544] Remove artist pick dog ear variant
  packages/common/src/models/DogEar.ts
  packages/common/src/utils/dogEarUtils.ts
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/M

#8811 Add text link for track tile genre and mood info
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#8807 Add small search page routing fixes
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Labels: size/S

#8812 [C-4532] Add mood and is_verified params to search, wire up UI
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/store/pages/search-results/actions.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/search.py
  packages/discovery-provider/src/queries/search_es.py
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
  packages/es-indexer/README.md
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
  packages/mobile/src/screens/search-results-screen/tabs/useFetchTabResultsEffect.tsx
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.ts
  packages/web/src/pages/search-page-v2/SearchHeader.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
  packages/web/src/pages/search-page/SearchPageProvider.jsx
Labels: size/L

#8816 Add "es2022.error" to react native tsconfig
  packages/mobile/tsconfig.json
Labels: size/XS

#8806 [C-4497] Remove /stream-url in favor of /stream query param
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/discovery-provider/src/api/v1/tracks.py
  packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/full/apis/SearchApi.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
  packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
Labels: size/L

#8818 Fix double import
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
Labels: size/XS

#8819 [QA-864] Use the correct field for calculating followers suffix
  packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
Labels: size/XS

#8817 Remove RN Video POC
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
  packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Labels: size/XL

#8822 add host to logs of listens for analytics
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/XS

#8824 [C-4538] Add genre search param for profiles
  packages/discovery-provider/src/queries/search_es.py
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/M

#8826 Add small fix for legacy search page provider
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/pages/search-page/SearchPageProvider.jsx
Labels: size/S

#8829 Remove dethroned notification feature flag
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/S

#8827 Remove challenge feature flags
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
  packages/web/src/hooks/useIsAudioMatchingChallengesEnabled.ts
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Labels: size/M

#8825 Remove gated content feature flags
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/edit/fields/AccessAndSaleMenuFields.tsx
Labels: size/M

#8823 Remove CHAT_ENABLED feature flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/nav/desktop/NavMenuButton.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/chat-page/ChatPage.tsx
  packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
Labels: size/L

#8833 trailing comma
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/XS

#8832 [C-4539] Add collections search filters
  packages/discovery-provider/src/queries/search_es.py
  packages/web/src/pages/search-page-v2/SearchPageV2.tsx
  packages/web/src/pages/search-page-v2/SearchResults.tsx
Labels: size/L

#8830 Remove scheduled releases feature flag
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/M

#8821 [C-4495] Fix hidden track albums
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/collection/sagas.js
Labels: size/M

#8831 Remove offline mode feature flag
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/offline-downloads/CollectionDownloadStatusIndicator.tsx
  packages/mobile/src/components/offline-downloads/TrackDownloadStatusIndicator.tsx
  packages/mobile/src/hooks/useIsOfflineModeEnabled.ts
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/OfflineContentBanner.tsx
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/screens/settings-screen/DownloadAllFavoritesRow.tsx
  packages/mobile/src/screens/settings-screen/DownloadNetworkPreferenceRow.tsx
  packages/mobile/src/screens/settings-screen/RemoveAllDownloadsRow.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/L

#8768 [PAY-3073] Add socials backfill for staging
  packages/discovery-provider/ddl/data/0077_backfill_user_socials/stage_user_socials.csv
  packages/discovery-provider/ddl/data/0077_backfill_user_socials/stage_verified_instagram_users.csv
  packages/discovery-provider/ddl/data/0077_backfill_user_socials/stage_verified_tiktok_users.csv
  packages/discovery-provider/ddl/data/0077_backfill_user_socials/stage_verified_twitter_users.csv
  packages/discovery-provider/ddl/migrations/0077_backfill_user_socials.sql
  packages/discovery-provider/ddl/pg_migrate.sh
Labels: size/L

#8838 Fix discovery test
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/XS

#8408 [DOCS] - Community Built Utilites & Projects
  docs/docs/developers/community-projects/go-sdk.mdx
  docs/docs/developers/community-projects/unreal-engine-plugin.mdx
  docs/sidebars.js
  docs/src/css/custom.css
  docs/static/img/community-apps/unreal-engine-plugin/actor.png
Labels: size/L

#8834 Fix empty search in new search flow
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Labels: size/S

#8841 [PAY-3057][PAY-3099][PAY-3065] Fix misc account switcher UI issues
  packages/libs/src/api/Account.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcherRow.tsx
Labels: size/S

#8820 [C-4529] Remove extra live email when sending transactional email
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
Labels: size/M

#8840 Bump mobile versions
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#8837 [PAY-2837] Handle disallowed actions when acting as managed user
  packages/web/src/components/nav/desktop/NavMenuButton.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
  packages/web/src/hooks/useGoToRoute.ts
  packages/web/src/hooks/useManagedAccountNotAllowedRedirect.ts
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/chat-page/ChatPageProvider.tsx
  packages/web/src/pages/chat-page/components/ChatUser.tsx
  packages/web/src/pages/dashboard-page/components/ArtistDashboardAlbumsTab.tsx
  packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx
  packages/web/src/pages/edit-page/components/AnchoredSubmitRowEdit.tsx
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/L

#8835 Fix TrackTile scheduled release text size
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.module.css
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx
  packages/web/src/components/track/GatedContentLabel.module.css
  packages/web/src/components/track/GatedContentLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
Labels: size/L

#8813 [C-4490] Update Track/Collection Metadata UI
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useCollectionMetadata.ts
  packages/common/src/hooks/useTrackMetadata.ts
  packages/common/src/store/cache/collections/selectors.ts
  packages/mobile/src/components/details-tile/CollectionMetadataList.tsx
  packages/mobile/src/components/details-tile/DetailsStat.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileMetadata.tsx
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/details-tile/MetadataItem.tsx
  packages/mobile/src/components/details-tile/SecondaryStats.tsx
  packages/mobile/src/components/details-tile/TrackMetadataList.tsx
  packages/web/src/components/collection/CollectionMetadataList.tsx
  packages/web/src/components/collection/components/AlbumDetailsText.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/entity-page/EntityActionButton.tsx
  packages/web/src/components/entity/MetadataItem.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/InfoLabel.tsx
  packages/web/src/components/track/TrackMetadataList.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/collection-page/DesktopServerCollectionPage.tsx
  packages/web/src/pages/collection-page/MobileServerCollectionPage.tsx
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.module.css
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XXL

#8725 Use essentia for mediorum BPM analysis
  mediorum/Dockerfile
  mediorum/Dockerfile.dev
  mediorum/cpp/bpm-analyzer.cpp
  mediorum/ddl/ddl.go
  mediorum/ddl/drop_old_audio_analyses.sql
  mediorum/server/audio_analysis.go
  mediorum/server/db.go
  mediorum/server/transcode.go
Labels: size/L

#8848 push uptime, dashboard, and healthz for creator stage deploys
  .circleci/src/workflows/creator.yml
Labels: size/M

#8793 [Web] Fix red icons in manager mode notifs [PAY-3103]
  packages/web/src/components/notification/Notification/ApproveManagerRequestNotification.tsx
  packages/web/src/components/notification/Notification/RequestManagerNotification.tsx
Labels: size/XS

#8794 [Web] Get rid of "Learn More" link in manager mode modals [C-4346]
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/sharedMessages.ts
Labels: size/M

#8789 [Web] Handle invalid manager mode invitation link + fix grant-related settings routes [PAY-2832]
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/utils/route.ts
Labels: size/M

#8851 Fix album search
  packages/discovery-provider/src/queries/search_es.py
Labels: size/XS

#8854 Make content node metric recording non-blocking
  mediorum/server/serve_blob.go
Labels: size/XS

#8847 Mediorum audio analysis for Qm cids
  mediorum/server/audio_analysis.go
  mediorum/server/db.go
  mediorum/server/legacy_audio_analysis.go
  mediorum/server/serve_audio_analysis.go
  mediorum/server/serve_upload.go
  mediorum/server/server.go
Labels: size/L

#8857 fix gorm automigrate typo
  mediorum/ddl/ddl.go
  mediorum/ddl/fix-qm-audio-analyses-typo.sql
  mediorum/server/db.go
Labels: size/S

#8859 fix cid colname
  mediorum/server/db.go
Labels: size/XS

#8856 [C-4517] Visibility Section Changes
  packages/common/src/services/remote-config/feature-flags.ts
  packages/harmony/src/components/index.ts
  packages/harmony/src/components/modal/Modal.tsx
  packages/web/src/components/data-entry/ContextualMenu.tsx
  packages/web/src/components/edit-collection/desktop/EditCollectionForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/DatePickerField.module.css
  packages/web/src/components/edit/fields/DatePickerField.tsx
  packages/web/src/components/edit/fields/ReleaseDateField.tsx
  packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.test.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
  packages/web/src/components/edit/fields/visibility/mergeReleaseDateValues.ts
  packages/web/src/components/form-fields/DropdownField.tsx
Labels: size/XL

#8852 Hash migration
  mediorum/go.sum
  mediorum/main.go
  mediorum/server/placement.go
  mediorum/server/placement_test.go
  mediorum/server/repair.go
  mediorum/server/repair_test.go
  mediorum/server/replicate.go
  mediorum/server/server.go
Labels: size/L

#8846 [C-4542] OptionsFilterButton improvements
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
  packages/harmony/src/components/button/OptionsFilterButton/SelectPopupKeyHandler.tsx
  packages/harmony/src/components/popup/Popup.tsx
  packages/web/src/pages/search-page-v2/SearchFilters.tsx
Labels: size/L

#8845 [C-4504] Add playback logic to fall back to old /stream endpoint (vs prefetch)
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/cache/tracks/types.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/web/src/common/store/player/sagas.ts
Labels: size/M

#8858 [C-4564] Add logic for previews & skipped tracks
  packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
Labels: size/S

#8863 Mediorum timing header
  mediorum/server/repair_test.go
  mediorum/server/serve_blob.go
  mediorum/server/serve_image.go
  mediorum/server/serve_image_test.go
  mediorum/server/server.go
Labels: size/S
