Repository AudiusProject/apps, pull requests merged in 2024-10, with the labels that each got.

#9902 [QA-1750] Fix race cond in cc flow with token account creation
  packages/common/src/store/purchase-content/sagas.ts
Labels: size/XS

#9895 [C-5070] Add comment count to artist dashboard
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx
  packages/web/src/pages/dashboard-page/components/hooks.ts
  packages/web/src/pages/dashboard-page/components/types.ts
Labels: size/M

#9896 [C-5028] Hide sort buttons with 1 or fewer comments
  packages/mobile/src/components/comments/CommentDrawerHeader.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
Labels: size/XS

#9897 [C-5058] Close reply input on submit
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/XS

#9898 [C-5022] Fix cached-image artwork and avatar
  packages/harmony/src/components/artwork/Artwork.tsx
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/M

#9894 [QA-1522] Update web scrubber to track audio player directly
  packages/harmony/src/components/scrubber/Scrubber.tsx
  packages/harmony/src/components/scrubber/Slider.tsx
  packages/harmony/src/components/scrubber/hooks.ts
  packages/harmony/src/components/scrubber/types.ts
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.jsx
  packages/web/src/services/audio-player/AudioPlayer.ts
Labels: size/L

#9907 Bump harmony by minor version
  .changeset/dirty-terms-teach.md
Labels: size/S

#9904 [PAY-3455] Update unread element scroll function and fix chat page styling again
  packages/web/src/pages/chat-page/ChatPage.module.css
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/S

#9900 Migrate to new user/tracks/remixed endpoint
  .changeset/smooth-rats-retire.md
  packages/common/src/api/user.ts
  packages/common/src/hooks/chats/useRemixersAudience.ts
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/queries/get_user_tracks_remixed.py
  packages/libs/src/sdk/api/generated/default/models/RemixedTrackAggregate.ts
Labels: size/S

#9912 Fix get playlist API playlist contents
  packages/discovery-provider/src/api/v1/playlists.py
Labels: size/XS

#9915 Unblock CI
  packages/libs/rollup.config.ts
Labels: size/XS

#9913 [PAY-3329] Remove monetization beta waitlist
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Labels: size/L

#9927 Upgrade mobile apps to 116
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9917 Move debug to externals
  packages/libs/rollup.config.ts
Labels: size/XS

#9909 [PAY-3477] Initialize Hedgehog directly in client
  packages/common/src/services/auth/hedgehog.ts
  packages/common/src/services/auth/identity.ts
  packages/common/src/services/auth/index.ts
  packages/common/src/services/auth/types.ts
  packages/common/src/services/index.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/hedgehog.ts
  packages/mobile/src/services/sdk/identity.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/audius-sdk/hedgehog.ts
  packages/web/src/services/audius-sdk/identity.ts
  packages/web/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/signOut.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#9920 [C-5057] Make comment overflow actions consistent with designs
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
Labels: size/L

#9928 [C-5002] Empty comments state for track owner
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/web/src/components/comments/NoComments.tsx
Labels: size/M

#9916 Only send blast notifs when no existing chat
  packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/M

#9919 [PAY-3463] Chat is_hidden respects cleared_history_at
  comms/discovery/rpcz/chat.go
Labels: size/S

#9908 Add distro sources
  packages/ddex/entrypoint/public/logos/audiosalad.png
  packages/ddex/entrypoint/public/logos/fuga.png
  packages/ddex/entrypoint/src/distributors/prod.json
  packages/ddex/entrypoint/vite.config.ts
  packages/ddex/entrypoint/wrangler.toml
Labels: size/M

#9922 [PAY-3199] Inbox Settings UI (mobile)
  packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenLegacy.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
Labels: size/XL

#9926 Re-enable payment router tests after network cut
  packages/discovery-provider/integration_tests/tasks/payment_router_mock_transactions.py
  packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py
Labels: size/XXL

#9923 [QA-1749] Fix help alignment
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Labels: size/S

#9933 console with em and some reactivity
  core/console/analytics.go
  core/console/console.go
  core/console/nav.go
  core/console/overview.go
  core/console/routes.go
  core/console/state.go
  core/console/views/layout/site_frame.templ
  core/console/views/layout/site_frame_templ.go
  core/console/views/pages/analytics_page.templ
  core/console/views/pages/analytics_page_templ.go
  core/console/views/pages/overview_page.templ
  core/console/views/pages/overview_page_templ.go
  core/console/views/views.go
  core/core_pkg/run.go
  core/grpc/constants.go
  core/infra/dev_config/sandbox-one.env
Labels: size/L

#9936 Tag mri plugin container in discprov release
  .circleci/src/commands/@docker-commands.yml
Labels: size/XS

#9930 [C-4998] Add timestamp highlighting to mobile composer input
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
Labels: size/L

#9937 Fix composer position for comments
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/composer-input/types.ts
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/M

#9943 [QA-875] Fix short feed on web sign in
  packages/web/src/components/lineup/LineupProvider.tsx
Labels: size/XS

#9924 [PAY-3453] Fix @ mentions in Dms with UserGeneratedTextV2
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/M

#9934 Honor existing chat
  comms/discovery/rpcz/chat.go
  packages/discovery-provider/ddl/functions/chat_allowed.sql
  packages/discovery-provider/ddl/tests/chat_allowed_test.sql
Labels: size/M

#9939 [PAY-3489] Update web ComposerInput autocomplete range tracking
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/L

#9932 [PAY-3488] Blast websockets respect permissions
  comms/discovery/rpcz/chat_blast.go
Labels: size/XS

#9929 Fix CAA tests
  packages/create-audius-app/examples/react-hono/package-lock.json
  packages/create-audius-app/examples/react-hono/package.json
  packages/create-audius-app/examples/react/package-lock.json
  packages/create-audius-app/examples/react/package.json
  packages/create-audius-app/examples/react/src/App.tsx
  packages/create-audius-app/examples/react/vite.config.ts
  packages/create-audius-app/tests/e2e/react/react.test.ts
Labels: size/M

#9947 [C-5071] Scroll to top for new comments on mobile
  packages/common/src/context/comments/commentsContext.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
Labels: size/M

#9951 Revert "[C-4493] Don't show deleted track rows in collections (#9209)"
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/dashboard-page/components/TracksTableContainer.module.css
  packages/web/src/pages/dashboard-page/components/TracksTableContainer.tsx
Labels: size/L

#9954 [C-5082] Comments desktop replies tweaks
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/M

#9955 [C-5025] Add compose ui helper text
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/composer-input/types.ts
Labels: size/L

#9945 [PAY-3493] Fix download gating on usdc feature flag
  packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
Labels: size/S

#9946 core: cleanup sandboxes
  core/Makefile
  core/console/nav.go
  core/console/state.go
  core/console/views/layout/site_frame.templ
  core/console/views/layout/site_frame_templ.go
  core/console/views/views.go
  core/db/setup.sql.go
  core/db/sql/setup.sql
  core/db/sqlc.yaml
  core/gen/proto/protocol.pb.go
  core/gen/proto/protocol_grpc.pb.go
  core/infra/Caddyfile
  core/infra/add-sandbox-hosts.sh
  core/infra/dev_config/dev-sandbox.env
  core/infra/dev_config/prod-sandbox.env
  core/infra/dev_config/sandbox-one.env
  core/infra/dev_config/stage-sandbox.env
  core/infra/docker-compose.yml
  core/infra/initdb/create_databases.sql
  core/modd.conf
Labels: size/L

#9957 [QA-1748] Fix misc sign up issues
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
Labels: size/S

#9949 Batch chat blast notifications by blastId and userId
  packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  packages/discovery-provider/plugins/notifications/src/config.ts
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts
  packages/discovery-provider/plugins/notifications/src/utils/redisConnection.ts
Labels: size/XL

#9952 [C-4994] Add user autocomplete and tagging to mobile ComposerInput
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/comments/CommentDrawerHeader.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/composer-input/types.ts
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/L

#9962 [C-5097] Add backspace handling back to mobile ComposerInput
  packages/mobile/src/components/composer-input/ComposerInput.tsx
Labels: size/M

#9964 Fix bottom sheet keyboard avoiding + compose ui
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/composer-input/types.ts
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/S

#9967 Upgrade mobile apps to 117
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#9968 Fix mobile lint
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
Labels: size/XS

#9969 Fix comment lint
  packages/common/src/context/comments/commentsHooks.ts
Labels: size/XS

#9965 [C-5094] Press comment stat to navigate to comments
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/comments/CommentSectionMobile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/M

#9971 update default inbound and outbound peer conns
  pkg/core/config/config.go
  pkg/core/core.go
Labels: size/M

#9977 Fix discovery lint
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/XS

#9966 Remove ddex from ci
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/jobs/@ddex-jobs.yml
  .circleci/src/jobs/deploy-stage-nodes-just-tag.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
  .circleci/src/workflows/ddex.yml
Labels: size/M

#9978 [C-5069] Fix mobile ComposerInput border color on focus
  packages/mobile/src/components/core/TextInput.tsx
Labels: size/M

#9979 Finish TextLink refactor on mobile
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/TimestampLink.tsx
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/harmony-native/components/TextLink/ExternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextPressable.tsx
  packages/mobile/src/harmony-native/components/TextLink/hooks.ts
  packages/mobile/src/harmony-native/components/TextLink/types.ts
  packages/web/src/components/comments/CommentText.tsx
Labels: size/XL

#9982 [C-5076] Fix issue with unpin message
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
Labels: size/XS

#9981 [C-5073] Fix issue with edit state persisting
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
Labels: size/XS

#9975 [PAY-3496] Blast notifs fixes
  packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/L

#9942 [PAY-3484] Format audience counts
  packages/mobile/src/screens/chat-screen/ChatBlastHeader.tsx
  packages/mobile/src/screens/chat-screen/ChatListBlastItem.tsx
  packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/M

#9941 [PAY-3491] Don't allow chat blast create with empty audience
  packages/common/src/hooks/chats/useFirstAvailableBlastAudience.ts
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx
  packages/mobile/src/screens/create-chat-blast-screen/CreateChatBlastNavigator.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/S

#9980 [PAY-3497] chat_blast_audience SQL UDF
  comms/discovery/rpcz/chat_blast.go
  packages/discovery-provider/ddl/functions/chat_blast_audience.sql
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/L

#9974 [C-5012] Refactor web track remixes UI
  packages/harmony/src/components/button/Button/Button.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/pages/track-page/components/TrackRemixes.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/track-page/utils.ts
Labels: size/L

#9948 [C-4986] Add comment report karma threshold
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/queries/get_comments.py
Labels: size/M

#9986 Return error when remote config not found
  pkg/conf/override.go
  pkg/orchestration/docker.go
Labels: size/S

#9992 [PAY-3498] Fix remix track audience targeting
  packages/common/src/api/user.ts
Labels: size/XS

#9993 [C-5107] Fix replying to a reply on mobile
  packages/common/src/context/comments/commentsContext.tsx
  packages/mobile/src/components/comments/CommentActionBar.tsx
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
Labels: size/L

#9988 Batch chat notifs to fix max connection limit reached
  packages/discovery-provider/plugins/notifications/src/config.ts
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/S

#9994 [PAY-3471] ChatBlastCTA should stick to the bottom
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Labels: size/XS

#9953 [C-5066 C-5023] Refactor pinned comment, fix unpin
  packages/common/src/api/comments.ts
  packages/common/src/api/tan-query/comments.ts
  packages/common/src/context/comments/commentsHooks.ts
  packages/common/src/models/Track.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/discovery-provider/ddl/migrations/0099_fix_pinned_comment_model.sql
  packages/discovery-provider/integration_tests/queries/test_get_comments.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/models/comments.py
  packages/discovery-provider/src/models/comments/comment.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/api/generated/default/models/Comment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/components/comments/mock-data.ts
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/XL

#9995 [PAY-3465] Fix text overflow on mobile ChatList
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatListItemSkeleton.tsx
Labels: size/L

#9997 Clearing chat history forces permission re-check.
  packages/discovery-provider/ddl/functions/chat_allowed.sql
  packages/discovery-provider/ddl/tests/chat_allowed_test.sql
Labels: size/XS

#10002 Fix chat blast notif batching async/await
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Labels: size/XS

#10003 [C-5114] [C-5115] Comment stat display improvements
  packages/mobile/src/components/details-tile/DetailsTileStats.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/comments/CommentSection.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/TrackStats.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#10001 [C-5105] Fix issue with remixes lineup empty on track screen
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
Labels: size/XS

#9996 [PAY-3203] Chat permissions write updates for multi-select
  .changeset/shiny-pugs-attend.md
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/chat.go
  comms/discovery/schema/schema.go
  packages/common/src/hooks/chats/index.ts
  packages/common/src/hooks/chats/useSetInboxPermissions.ts
  packages/common/src/hooks/chats/useSetInboxPermissionsLegacy.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/common/src/store/pages/chat/types.ts
  packages/common/src/utils/chatUtils.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/clientTypes.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
  packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenLegacy.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalLegacy.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
Labels: size/XL

#10011 [PAY-3446] Fix back button in ChatBlastCTA
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/S

#10010 [PAY-3499, PAY-3500] Fix truncation on blasts with content audience
  packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Labels: size/S

#10006 [C-5132] Add artist popover UserGeneratedTextV2
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/XS

#9999 [C-5030] Get new comment ID from api
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/queries/get_unclaimed_id.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/sdk/api/comments/CommentsAPI.ts
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/apis/CommentsApi.ts
  packages/libs/src/sdk/api/generated/default/models/UnclaimedIdResponse.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts
  packages/libs/src/services/discoveryProvider/requests.ts
Labels: size/L

#10005 [C-4958] Improve web comment disabled state
  packages/web/src/pages/track-page/components/TrackRemixes.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/M

#10008 Fix track comment notification setting
  packages/common/src/api/tan-query/comments.ts
  packages/discovery-provider/src/api/v1/tracks.py
Labels: size/S

#10004 [C-5186] Add autoFocus to ComposerInput
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/types.ts
Labels: size/S

#9998 [C-5129, C-5130] Add reply/mention push/email notifications
  packages/common/src/store/pages/settings/reducer.ts
  packages/common/src/store/pages/settings/types.ts
  packages/discovery-provider/plugins/notifications/scripts/test-push-notification.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/commentMention.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/commentThread.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentMention.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentThread.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/types.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentMention.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentThread.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
  packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
  packages/discovery-provider/plugins/notifications/src/types/dn.ts
  packages/discovery-provider/plugins/notifications/src/types/identity.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
  packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts
  packages/identity-service/scripts/run-tests.sh
  packages/identity-service/sequelize/migrations/20241009143933-add-mentions-to-browser-notification-settings.js
  packages/identity-service/sequelize/migrations/20241009144010-add-mentions-to-mobile-notification-settings.js
  packages/identity-service/src/models/userNotificationBrowserSettings.js
  packages/identity-service/src/models/userNotificationMobileSettings.js
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
  packages/web/src/pages/settings-page/store/sagas.ts
Labels: size/XXL

#10012 [PAY-3220] Inbox unavailable UI for new chat permissions
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/common/src/store/pages/chat/types.ts
  packages/common/src/store/social/users/actions.ts
  packages/harmony/src/assets/icons/MessageSlash.svg
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/chat-page/components/UserChatHeader.tsx
Labels: size/L

#10014 Fix comment pin track update
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Labels: size/S

#10015 Fix mobile web comments not displaying
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/XS

#10013 Don't orchestrate releases through git sha tags
  .circleci/config.yml
  .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
  .circleci/src/jobs/deploy-stage-nodes.yml
  .circleci/src/workflows/creator.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/identity.yml
Labels: size/M

#9989 [C-5080] Fix comment pagination limit
  packages/discovery-provider/src/queries/get_comments.py
Labels: size/XS

#10009 [C-5079] Mute comments from user profile
  packages/common/src/messages/comments.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/drawers/MuteCommentsConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/index.ts
  packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/L

#10017 Remove duplicate turn off notifs
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
Labels: size/XS

#10016 add check for no chain status at all in discprov
  packages/discovery-provider/src/queries/get_health.py
Labels: size/XS

#10019 [C-5099] Pluralize the word replies correctly
  packages/common/src/messages/comments.ts
Labels: size/XS

#10020 [C-5125, C-5147, C-5148] Web and Mobile Comment QA 1
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/M

#10018 [C-5145] Add comment count increment logic
  packages/common/src/api/tan-query/comments.ts
Labels: size/S

#10021 Add New Comments button
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentDrawerHeader.tsx
  packages/web/src/components/comments/CommentHeader.tsx
  packages/web/src/components/comments/CommentSectionDesktop.tsx
Labels: size/M

#10023 [C-5140] Fix too big comment container
  packages/web/src/components/comments/CommentText.tsx
Labels: size/XS

#10022 [C-5143, C-5146] Comments QA 2
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/S

#10026 Fix comment mention entity type to table mapping
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/XS

#10032 [C-5170 C-5175] Fix web pin action, update mute thread
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
Labels: size/M

#10028 [PAY-3502] Toggle all boxes on when allowing all chats
  packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
Labels: size/M

#10029 [PAY-3481, PAY-3512] ChatBlastCTA float above mobile keyboard
  packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/hooks/useKeyboardAvoidingPlaybarStyle.ts
Labels: size/L

#10025 [PAY-3501] Improvements to blast upgrade flow
  .changeset/proud-kids-jog.md
  comms/discovery/schema/schema.go
  packages/common/src/store/pages/chat/slice.ts
  packages/libs/src/sdk/api/chats/ChatsApi.ts
  packages/libs/src/sdk/api/chats/serverTypes.ts
Labels: size/M

#10034 Fix Text component font and CAA API key
  .changeset/moody-squids-thank.md
  packages/create-audius-app/examples/react-hono/src/index.tsx
  packages/harmony/src/components/text/Text.tsx
Labels: size/S

#10033 Cleanup from sdk/libs split
  package-lock.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/sla-auditor/package.json
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/package.json
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/identity-service/package.json
  packages/sdk/src/sdk/api/chats/ChatsApi.ts
  packages/sdk/src/sdk/api/chats/clientTypes.ts
  packages/sdk/src/sdk/api/chats/serverTypes.ts
  packages/sdk/src/sdk/api/comments/CommentsAPI.ts
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/CommentsApi.ts
  packages/sdk/src/sdk/api/generated/default/models/Comment.ts
  packages/sdk/src/sdk/api/generated/default/models/UnclaimedIdResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
Labels: size/L

#10042 [C-5153] Update ComposerInput to not render the display layer unless there is highlighted text
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/M

#10036 turn off registry bridge and start new chain
  pkg/core/config/genesis/prod.json
  pkg/core/registry_bridge/register.go
Labels: size/M

#10044 [C-5164] Add max height to mobile ComposerInput
  packages/mobile/src/components/composer-input/ComposerInput.tsx
Labels: size/XS

#10037 [C-5040] Enable animated mobile icons
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/icons.ts
  svgr-template.js
Labels: size/L

#10038 [QA-1761] Fix mobile profile page username spacing
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/XS

#10048 [PAY-3458] ChatsApi.getAll blast query respects timestamp cursors
  comms/discovery/db/queries/get_chats.go
Labels: size/XS

#10024 Remove follows you badge from comment settings
  packages/mobile/src/screens/settings-screen/CommentSettingsScreen.tsx
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/artist/ArtistChipFollowers.tsx
  packages/web/src/components/comment-settings-modal/CommentSettingsModal.tsx
Labels: size/M

#10051 Fix withdrawals not showing coinflow modal
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Labels: size/XS

#10046 [C-5144] Fix dupe comments by ensuring deterministic order
  packages/discovery-provider/src/queries/get_comments.py
Labels: size/XS

#10054 FIx CI for feature-remove-libs
  .circleci/config.yml
  .circleci/src/jobs/@common-jobs.yml
  .circleci/src/jobs/@embed-jobs.yml
  .circleci/src/jobs/@identity-jobs.yml
  .circleci/src/jobs/@integration-jobs.yml
  .circleci/src/jobs/@mobile-jobs.yml
  .circleci/src/jobs/@protocol-dashboard-jobs.yml
  .circleci/src/jobs/@sdk-jobs.yml
  .circleci/src/jobs/@web-jobs.yml
  .circleci/src/workflows/sdk.yml
  .github/workflows/publish-packages.yml
  dev-tools/compose/docker-compose.test.yml
  package-lock.json
  packages/commands/package.json
  packages/commands/src/claim-reward.mjs
  packages/commands/src/purchase-content.mjs
  packages/commands/src/tip-audio.mjs
  packages/commands/src/upload-track.mjs
  packages/commands/src/utils.mjs
  packages/common/package.json
  packages/identity-service/package.json
  packages/libs/package.json
  packages/libs/scripts/check-generated-types.sh
  packages/libs/scripts/verify-types.sh
  packages/mobile/android/app/build.gradle
  packages/mobile/metro.config.js
  packages/sdk/package.json
  packages/sdk/scripts/check-generated-types.sh
  packages/sdk/scripts/verify-types.sh
  packages/sdk/src/sdk/api/albums/AlbumsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.test.ts
  packages/sdk/src/sdk/services/AntiAbuseOracleSelector/AntiAbuseOracleSelector.test.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManager.test.ts
  packages/sdk/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  packages/sdk/src/sdk/utils/mergeConfigs.test.ts
Labels: size/L

#10040 [C-5161 C-5151] Improve desktop track page responsiveness
  packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx
  packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
  packages/web/src/components/lineup/Lineup.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/lineup/types.ts
  packages/web/src/components/track/mobile/BottomButtons.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/ai-attributed-tracks-page/components/desktop/AiPage.tsx
  packages/web/src/pages/ai-attributed-tracks-page/components/mobile/AiPage.tsx
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx
  packages/web/src/pages/remixes-page/components/desktop/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/RemixesPage.tsx
  packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
  packages/web/src/pages/track-page/components/TrackRemixes.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/useTrackPageSize.ts
Labels: size/L

#10030 Chat create from blast validator
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/rpcz/chat_permissions_test.go
  comms/discovery/rpcz/validator.go
Labels: size/L

#10050 [C-5184] Add border to Harmony PopoverMenu
  packages/harmony/src/components/popup-menu/PopupMenu.module.css
Labels: size/XS

#10055 [C-5173] Fix sort by top comments out of date
  packages/common/src/context/comments/commentsContext.tsx
Labels: size/S

#10058 [C-5155] Add cancel accessory to mobile ComposerInput for comments
  packages/mobile/src/components/comments/CommentForm.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/composer-input/types.ts
Labels: size/M

#10052 [C-5172] Fix comments timezone
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/XS

#10057 [PAY-3483] Update 'ChatListBlastItem' UI on smaller screens
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
Labels: size/S

#10053 [PAY-3347] Analytics for create chat blast funnel
  packages/common/src/models/Analytics.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx
  packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
Labels: size/M

#10060 fix relay core error ref
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
Labels: size/XS

#10049 [PAY-3437] Add names to chats sentry reports
  packages/common/src/hooks/chats/useSetInboxPermissions.ts
  packages/common/src/store/pages/chat/sagas.ts
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
Labels: size/M

#10047 [C-5166] [C-5108] [C-5156] Address comment QA issues
  packages/common/src/audius-query/createRequestBatcher.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/common/src/utils/handle.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentDrawerForm.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/mobile/src/components/comments/CommentText.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/sdk/src/sdk/index.ts
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  packages/sdk/src/sdk/types/Timeout.ts
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/L

#10062 Fix comment report indexing errors in staging
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Labels: size/XS

#10064 Fix lint
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/XS

#10061 Fix comment unauthed state
  packages/common/src/api/tan-query/comments.ts
Labels: size/XS

#10068 Remove reported comment conflict
  packages/discovery-provider/src/models/moderation/reported_comment.py
  packages/discovery-provider/src/tasks/entity_manager/entities/reported_comment.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/L

#10065 [C-5178] Show newlines in comments
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/XS

#10067 [C-5167] Improve mobile comments perf
  packages/mobile/src/components/comments/CommentActionBar.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/components/comments/CommentSection.tsx
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/L

#10059 [QA-1762] Fix desktop app support on MacOS Sequoia
  package-lock.json
  packages/web/package.json
Labels: size/XS

#10066 [PAY-3466] Improve composer input responsiveness on mobile
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Labels: size/M

#10071 Fix mobile lint
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/XS

#10070 [PAY-3523] Fix bug where share to DM persists in input
  packages/web/src/pages/chat-page/ChatPageProvider.tsx
Labels: size/S

#10043 [PAY-3424] Restrict imports from SDK 'dist' folder in client code
  packages/common/.eslintrc.js
  packages/mobile/.eslintrc.js
  packages/web/.eslintrc.js
Labels: size/S

#10073 decouple console from rpc
  cmd/core/Makefile
  pkg/core/console/block.go
  pkg/core/console/console.go
  pkg/core/console/state.go
  pkg/core/console/views/layout/base.templ
  pkg/core/console/views/layout/site_frame.templ
  pkg/core/console/views/pages/block_page.templ
  pkg/core/console/views/pages/block_page_templ.go
  pkg/core/console/views/pages/nodes_page.templ
  pkg/core/console/views/pages/overview_page.templ
  pkg/core/console/views/pages/overview_page_templ.go
  pkg/core/console/views/pages/tx_page.templ
  pkg/core/console/views/pages/uptime_page.templ
  pkg/core/core.go
  pkg/core/db/reads.sql.go
  pkg/core/db/sql/reads.sql
Labels: size/L

#10056 [PROTO-1951] Add localhost node configuration
  .circleci/src/jobs/@audiusd-jobs.yml
  cmd/audius-ctl/jump.go
  cmd/audius-ctl/up.go
  dev-tools/templates/test-localhost.yaml
  pkg/conf/model.go
  pkg/orchestration/docker.go
  pkg/orchestration/run.go
Labels: size/L

#10077 Highlight user mentions when editing comments on web
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentForm.tsx
  packages/web/src/components/comments/CommentText.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/composer-input/types.ts
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/L

#10076 [PAY-3521] Fix offset calculation for Blast CTA
  packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx
Labels: size/XS

#10074 [PAY-3518] Get new blasts after inbox settings change
  comms/discovery/db/queries/get_new_blasts.go
  comms/discovery/rpcz/chat_blast_test.go
Labels: size/M

#10081 [PAY-3509] Show InboxUnavailableModal instead of disabled button
  packages/web/src/components/stat-banner/StatBanner.tsx
Labels: size/XS

#10083 [PAY-3526] Hide scroll on message inbox
  packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
Labels: size/XS

#10079 [PAY-3519] Fix mobile ChatBlastSubHeader opacity
  packages/mobile/src/screens/chat-screen/ChatBlastSubHeader.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/S

#10084 [PAY-3456] Fix chat last message sometimes wrong
  packages/common/src/store/pages/chat/slice.ts
Labels: size/S

#10075 [C-5189] Fix react and reply comment count
  packages/discovery-provider/src/queries/get_comments.py
Labels: size/L

#10078 [C-5191] Add background color to comment cancel accessory view
  packages/mobile/src/components/composer-input/ComposerInput.tsx
Labels: size/XS

#10080 [C-5193] Add cancel button to comment replies and edits
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/M

#9803 Update DN to use shortened rewards challenge IDs and specifiers
  packages/discovery-provider/ddl/migrations/0095_shorten_challenge_ids.sql
  packages/discovery-provider/ddl/pg_migrate.sh
  packages/discovery-provider/ddl/utils/hashids.sql
  packages/discovery-provider/integration_tests/challenges/test_challenges.py
  packages/discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_referral_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_track_upload_challenge.py
  packages/discovery-provider/integration_tests/queries/test_get_challenges.py
  packages/discovery-provider/integration_tests/queries/test_get_disbursed_challenges_amount.py
  packages/discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/email/notifications/types.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts
  packages/discovery-provider/src/challenges/audio_matching_challenge.py
  packages/discovery-provider/src/challenges/challenge.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/connect_verified_challenge.py
  packages/discovery-provider/src/challenges/first_playlist_challenge.py
  packages/discovery-provider/src/challenges/listen_streak_challenge.py
  packages/discovery-provider/src/challenges/mobile_install_challenge.py
  packages/discovery-provider/src/challenges/profile_challenge.py
  packages/discovery-provider/src/challenges/referral_challenge.py
  packages/discovery-provider/src/challenges/send_first_tip_challenge.py
  packages/discovery-provider/src/challenges/track_upload_challenge.py
  packages/identity-service/src/notifications/components/notifications/Notification.jsx
  packages/identity-service/src/notifications/formatNotificationMetadata.js
  packages/identity-service/src/notifications/renderEmail/notifications/Notification.js
  packages/identity-service/test/emailNotifications/renderEmail.js
  packages/identity-service/test/processNotifications/challengeRewardNotification.js
  packages/identity-service/test/sendNotifications/mockNotifications/challengeReward.json
  packages/libs/tests/rewardsAttesterTest.js
Labels: size/XXL

#10088 Validate comment mentions
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Labels: size/XS

#10089 Fix chat header too long on mobile
  packages/mobile/src/screens/chat-screen/UserChatHeader.tsx
Labels: size/M

#10072 [PAY-3525] Fix text overflow
  packages/harmony/src/components/text/Text.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S
