Repository AudiusProject/apps, pull requests merged in 2024-01, with the labels that each got.

#7007 Improve sdk track upload logs
  packages/libs/src/sdk/api/tracks/TracksApi.ts
  packages/libs/src/sdk/services/EntityManager/EntityManager.ts
  packages/libs/src/sdk/services/Storage/Storage.ts
  sdk-consumer/index.ts
Labels: size/XL

#7047 Fix button color darkening
  packages/mobile/src/components/core/Button.tsx
Labels: size/XS

#7051 Fix schedule release gating
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/M

#7056 [C-3566] UploadChip - fix text wrapping
  packages/web/src/components/upload/UploadChip.tsx
Labels: size/XS

#7057 [PAY-2320] Fix explore tx link callouts
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/harmony/src/components/text-link/types.ts
  packages/harmony/src/foundations/color/semantic.ts
  packages/web/src/components/link/Link.module.css
  packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Labels: size/M

#7055 [C-3513] Private albums + show PublishButton for albums
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
Labels: size/M

#7059 [PAY-2281] Fix mobile web purchase modal footer placement
  packages/stems/src/components/Modal/ModalContentPages.module.css
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.module.css
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/XS

#7063 Fix payment method existing balance
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Labels: size/XS

#7049 Clamp upload percentage
  packages/common/src/store/upload/selectors.ts
Labels: size/XS

#7058 [C-3565] Reduce saga apk size
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/dapp-store/README.md
Labels: size/XS

#7054 [C-3492] Fix podcast popup position
  packages/web/.svgrrc.js
Labels: size/XS

#7053 [C-3490] Improve profile touch targets
  packages/mobile/src/components/profile-list/ProfileCardSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileCoverPhoto.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
Labels: size/M

#7065 [PAY-2321] Prevent crash if nsure RN module isn't available
  packages/mobile/src/services/coinflow.ts
Labels: size/XS

#7067 [EM] Allow dashboard wallet to sign EM CreateDashboardWalletUser tx and user to sign `user_signature` in the metadata C-3568
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py
Labels: size/L

#7068 Fix native storybook
  package-lock.json
  packages/mobile/metro.config.js
  packages/mobile/package.json
Labels: size/S

#7060 [PAY-2289] Fix premium/usdc modal close issues
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/S

#7061 Add is_scheduled_release field
  packages/discovery-provider/ddl/migrations/0046_add_is_scheduled_release.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/discovery-provider/src/models/tracks/track.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/metadata.py
Labels: size/M

#7000 [C-3450] Native Social SignUp
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/sign-on/createLoginDetailsSchema.ts
  packages/common/src/services/oauth/formatSocialProfile.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/components/oauth/OAuthWebView.tsx
  packages/mobile/src/components/tiktok-auth/TikTokAuthButton.tsx
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignupFlowTikTokAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoading.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoginOptions.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/components/useSocialMediaLoader.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
  packages/mobile/src/screens/sign-on-screen/types.ts
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/store/oauth/reducer.ts
  packages/mobile/src/store/oauth/sagas.ts
  packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
Labels: size/XXL

#7073 Sanitize h1
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#7070 Scheduled release UI fixes from QA
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/components/core/Button.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/types.ts
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/utils/dateUtils.ts
Labels: size/L

#7075 [Discovery API] Add transaction signature to OAuth JWT payload type
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
Labels: size/S

#7076 Fix svgr template when no theme
  svgr-template.js
Labels: size/XS

#7038 [C-3425] Add Button component to native harmony
  packages/harmony/src/foundations/color/semantic.ts
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/components/loading-spinner/LoadingSpinner.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.stories.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/types.ts
  packages/mobile/src/harmony-native/components/Text/Text.tsx
Labels: size/XL

#7045 [Web] Enable connecting wallet to user via new OAuth `write_once` scope [C-3499]
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/oauth-login-page/components/CTAButton.tsx
  packages/web/src/pages/oauth-login-page/components/ContentWrapper.tsx
  packages/web/src/pages/oauth-login-page/components/PermissionsSection.tsx
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/messages.ts
  packages/web/src/pages/oauth-login-page/utils.ts
Labels: size/XXL

#7071 [C-3546] Upgrade electron
  package-lock.json
  packages/web/package.json
Labels: size/S

#7072 [C-3462] Disable native font scaling
  packages/mobile/index.js
Labels: size/XS

#7069 [C-3524] Mobile sign-up QA
  packages/common/src/schemas/index.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/schemas/sign-on/selectGenresSchema.ts
  packages/common/src/schemas/sign-on/signInSchema.ts
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/components/core/ErrorText.tsx
  packages/mobile/src/components/core/InputErrorMessage.tsx
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/fields/PasswordField.tsx
  packages/mobile/src/components/fields/TextField.tsx
  packages/mobile/src/components/fields/index.ts
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/components/EmailField.tsx
  packages/mobile/src/screens/sign-on-screen/components/EmailInUseHint.tsx
  packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx
  packages/mobile/src/screens/sign-on-screen/components/PasswordCompletionChecklist.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/web/src/components/form-fields/HarmonyTextField.tsx
  packages/web/src/pages/sign-up-page/components/EmailField.tsx
  packages/web/src/pages/sign-up-page/components/EnterPasswordSection.tsx
  packages/web/src/pages/sign-up-page/components/PasswordCompletionChecklist.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Labels: size/XL

#7081 Bust turbo web cache
  package-lock.json
Labels: size/XS

#7083 Fix uptime optimizely env
  monitoring/uptime/main.go
Labels: size/XS

#7086 Add DDEX MVC + DB scaffolding
  package-lock.json
  packages/ddex/package.json
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
  packages/ddex/src/index.ts
  packages/ddex/src/services/dbService.ts
  packages/ddex/src/services/scheduledReleaseService.ts
  packages/ddex/src/services/sdkService.ts
Labels: size/L

#7088 Perform full disk cleanup hourly for self-hosted runners
  .circleci/scripts/circleci-startup-script.sh
Labels: size/XS

#7089 Fix esbuild on intel
  package-lock.json
Labels: size/XS

#7090 Try again to bust cache
  packages/harmony/src/assets/icons/deprecated/UserFollow.svg
Labels: size/XS

#7082 fix: Fix horizontal color logo clipping & resize img
  packages/harmony/src/assets/icons/AudiusLogoHorizontalColor.svg
Labels: size/S

#7093 Fix harmony build
  package-lock.json
Labels: size/XS

#7080 [C-3560 C-3564] Improve mobile playlist image generation perf.
  packages/common/src/utils/updatePlaylistArtwork.ts
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/edit-playlist-screen/EditPlaylistModalScreen.tsx
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
Labels: size/L

#7085 Make Stripe the default PurchaseVendor for AddFunds on mobile
  packages/mobile/src/components/add-funds-drawer/AddFundsDrawer.tsx
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx
  packages/mobile/src/store/purchase-vendor/slice.ts
Labels: size/S

#7094 Add 8cpu resource class to circleci runners
  .circleci/scripts/circleci-startup-script.sh
  .circleci/scripts/periodic-cleanup
Labels: size/S

#7096 Add ddex upload logic to backend
  package-lock.json
  packages/ddex/package.json
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
  packages/ddex/src/examples/clipper.jpg
  packages/ddex/src/examples/snare.wav
  packages/ddex/src/services/sdkService.ts
Labels: size/L

#7097 Increment mobile versions ahead of 1.5.59
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7079 Fix copyright year for notif test
  packages/discovery-provider/plugins/notifications/package-lock.json
  packages/discovery-provider/plugins/notifications/package.json
  packages/discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/multipleMappings.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseBuyer.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts
  packages/discovery-provider/plugins/notifications/src/main.ts
Labels: size/M

#7098 Add default ddex stage keys and enforce prettier
  packages/ddex/.env.stage
  packages/ddex/.eslintrc.cjs
  packages/ddex/.prettierrc
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
  packages/ddex/src/index.ts
  packages/ddex/src/services/dbService.ts
  packages/ddex/src/services/scheduledReleaseService.ts
  packages/ddex/src/services/sdkService.ts
Labels: size/L

#7099 [Web] Fix OAuth sig timestamp
  packages/web/src/pages/oauth-login-page/hooks.ts
Labels: size/XS

#7084 [C-3515] Fix desktop sign up page transitions
  packages/web/src/components/form-fields/HarmonyTextField.tsx
  packages/web/src/components/form-fields/PasswordField.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-up-page/components/EnterPasswordSection.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
Labels: size/L

#7091 [C-3571] Fix modal header styles
  packages/web/src/components/collection/desktop/PublishConfirmationModal.module.css
  packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.module.css
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.module.css
  packages/web/src/components/inbox-unavailable-modal/InboxUnavailableModal.tsx
  packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx
  packages/web/src/components/locked-content-modal/LockedContentModal.module.css
  packages/web/src/components/remix-settings-modal/RemixSettingsModal.module.css
  packages/web/src/components/search-users-modal/SearchUsersModal.module.css
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.module.css
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/BlockUserConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/DeleteChatConfirmationModal.tsx
  packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.module.css
  packages/web/src/pages/chat-page/components/UnblockUserConfirmationModal.tsx
Labels: size/M

#7100 Move uploads out of DDEX client
  package-lock.json
  packages/ddex-frontend/.eslintrc.cjs
  packages/ddex-frontend/.prettierrc
  packages/ddex-frontend/public/ddex-examples/clipper.jpg
  packages/ddex-frontend/public/ddex-examples/snare.wav
  packages/ddex-frontend/src/components/App.tsx
  packages/ddex-frontend/src/components/AppWithProviders.tsx
  packages/ddex-frontend/src/components/Layout.tsx
  packages/ddex-frontend/src/main.tsx
  packages/ddex-frontend/src/pages/DDEX.tsx
  packages/ddex-frontend/src/providers/AudiusLibsProvider.tsx
  packages/ddex-frontend/src/providers/AudiusSdkProvider.tsx
  packages/ddex-frontend/src/providers/EnvVarsProvider.tsx
  packages/ddex-frontend/src/providers/RemoteConfigProvider.tsx
  packages/ddex-frontend/src/utils/constants.ts
  packages/ddex/.gitignore
  packages/ddex/package.json
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
Labels: size/XXL

#7101 Actually fix discovery notif tests
  packages/discovery-provider/plugins/notifications/jest.config.js
  packages/discovery-provider/plugins/notifications/package.json
Labels: size/XS

#7103 DDEX NODE_ENV production -> prod
  package-lock.json
  packages/Dockerfile.ddex
  packages/Dockerfile.ddex.fast
  packages/ddex-frontend/package.json
  packages/ddex-frontend/src/pages/DDEX.tsx
  packages/ddex-frontend/vite.config.ts
  packages/ddex/package.json
  packages/ddex/src/app.ts
  packages/ddex/src/services/sdkService.ts
Labels: size/M

#7074 [C-3478] Backlink to album from track page
  package-lock.json
  package.json
  packages/trpc-server/package.json
  packages/trpc-server/src/routers/playlist-router.ts
  packages/trpc-server/src/routers/track-router.ts
  packages/trpc-server/test/search.test.ts
  packages/web/package.json
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/tsconfig.json
Labels: size/L

#7108 Enable schedule release job
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/publish_scheduled_releases.py
Labels: size/M

#7102 [PROTO-1489] [PROTO-1512] Add ddex queue flows with db persistence
  package-lock.json
  packages/ddex/README.md
  packages/ddex/package.json
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
  packages/ddex/src/index.ts
  packages/ddex/src/initServices.ts
  packages/ddex/src/models/dbTypes.ts
  packages/ddex/src/services/dbService.ts
  packages/ddex/src/services/scheduledReleaseService.ts
  packages/ddex/src/services/sdkService.ts
  packages/ddex/src/services/xmlProcessorService.ts
  packages/ddex/src/utils/xmlUtils.ts
Labels: size/XL

#7109 Track ddex frontend changes and install uuid
  .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
  package-lock.json
  packages/ddex/package.json
Labels: size/XS

#7112 Remove DDEX .gitignore
  packages/ddex/.gitignore
Labels: size/XS

#7078 Schedule release disables hidden + editable release date on web
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/common/src/models/Search.ts
  packages/common/src/models/Track.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/details-tile/types.ts
  packages/mobile/src/components/drawers/ReleaseNowConfirmationDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/AccessAndSaleField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.module.css
  packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.tsx
  packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/helpers.ts
  packages/web/src/components/track/types.ts
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/dashboard-page/store/sagas.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/utils.ts
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/validation.ts
  packages/web/src/utils/dateUtils.ts
Labels: size/XL

#7111 Fix trpc-server ci cache
  .circleci/config.yml
  package-lock.json
  package.json
Labels: size/XS

#7110 DDEX uses sdk oauth
  monitoring/uptime/main.go
  monitoring/uptime/uptime.go
  package-lock.json
  packages/ddex-frontend/.env.stage.local
  packages/ddex-frontend/package.json
  packages/ddex-frontend/src/pages/DDEX.tsx
  packages/ddex-frontend/src/providers/AudiusSdkProvider.tsx
  packages/ddex-frontend/src/providers/EnvVarsProvider.tsx
Labels: size/L

#7114 Fix ios build by patching boost
  package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/patches/react-native+0.73.1.patch
Labels: size/S

#7118 Fix issues found in 1.5.59 release
  packages/mobile/android/app/build.gradle
  packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.kt
  packages/mobile/patches/react-native+0.73.1.patch
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
Labels: size/M

#7115 Scheduled release publishing confirmation
  packages/common/src/store/reducers.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/ui/publish-track-confirmation-modal/sagas.ts
  packages/common/src/store/ui/publish-track-confirmation-modal/selectors.ts
  packages/common/src/store/ui/publish-track-confirmation-modal/slice.ts
  packages/common/src/store/ui/publish-track-confirmation-modal/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/drawers/ReleaseNowConfirmationDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.tsx
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/publish-track-confirmation-modal/PublishTrackConfirmationModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#7119 [PAY-2340] Fix dms playlist unfurl
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
Labels: size/M

#7105 [C-3573] Persist email across all 3 sign up pages
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/screens/sign-on-screen/components/EmailField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/types.ts
  packages/web/src/components/form-fields/HarmonyTextField.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-up-page/components/EmailField.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/hooks/socialMediaLogin.ts
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
Labels: size/L

#7092 Revert adding extra icon
  packages/harmony/src/assets/icons/deprecated/UserFollow.svg
Labels: size/XS

#7107 [C-3407] Error messages for invalid profile image uploads
  packages/common/src/messages/sign-on/pages.ts
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx
  packages/web/src/pages/sign-up-page/components/ImageField.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Labels: size/M

#7106 Support creating dashboard wallet user in SDK
  packages/libs/src/sdk/api/dashboard-wallet-users/DashboardWalletUsersApi.ts
  packages/libs/src/sdk/api/dashboard-wallet-users/types.ts
  packages/libs/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/default/models/DecodedUserToken.ts
  packages/libs/src/sdk/api/generated/default/models/TxSignature.ts
  packages/libs/src/sdk/api/generated/default/models/index.ts
  packages/libs/src/sdk/api/generated/full/models/TrackFull.ts
  packages/libs/src/sdk/oauth/OAuth.ts
  packages/libs/src/sdk/oauth/types.ts
  packages/libs/src/sdk/utils/oauthScope.ts
Labels: size/L

#7121 [C-3426] Add PlainButton to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/Button/types.ts
Labels: size/L

#7122 Fix track-availability hook dependencies
  packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
Labels: size/M

#7117 [PROTO-1489] [PROTO-1512] Add endpoints + UI for paginating ddex uploads and releases
  packages/ddex-frontend/src/components/App.tsx
  packages/ddex-frontend/src/components/Releases.tsx
  packages/ddex-frontend/src/components/Uploads.tsx
  packages/ddex-frontend/src/pages/DDEX.tsx
  packages/ddex-frontend/src/providers/useReleases.tsx
  packages/ddex-frontend/src/providers/useUploads.tsx
  packages/ddex/src/app.ts
  packages/ddex/src/controllers/uploadController.ts
  packages/ddex/src/controllers/uploadsController.ts
  packages/ddex/src/services/dbService.ts
  packages/ddex/src/services/xmlProcessorService.ts
Labels: size/XL

#7128 [C-3593] signUp straight to jail
  packages/probers/cypress/e2e/flaky-test-jail.md
  packages/probers/cypress/e2e/signUp.cy.ts
Labels: size/S

#7129 [C-3523] Add create album card to mobile
  packages/mobile/src/components/collection-list/AddCollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
Labels: size/M

#7130 Allow placeholder postgres urls through secrets check
  scripts/check_secrets.sh
Labels: size/XS

#7127 [C-3439] Add LoadingSpinner to native harmony
  packages/mobile/src/harmony-native/assets/animations/loadingSpinner.json
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/LoadingSpinner/LoadingSpinner.tsx
Labels: size/M

#7124 [C-3430] Add SocialButton to native harmony
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
  packages/mobile/src/harmony-native/components/Button/SocialButton/types.ts
Labels: size/L

#7125 [C-3433] Add harmony-native password input
  packages/harmony/src/hooks/useControlled.ts
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/input/PasswordInput/PasswordInput.stories.tsx
  packages/mobile/src/harmony-native/components/input/PasswordInput/PasswordInput.tsx
  packages/mobile/src/harmony-native/components/input/PasswordInput/types.ts
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/harmony-native/hooks/useControlled.ts
Labels: size/L

#7131 Remove konami, segment, clean up Collectible3D
  package-lock.json
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/embed/package.json
  packages/embed/src/components/collectibles/CollectibleDetailsView.jsx
  packages/web/package.json
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/collectibles/components/Collectible3D.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
  packages/web/src/components/dragndrop/Draggable.tsx
  packages/web/src/components/konami/Konami.module.css
  packages/web/src/components/konami/Konami.tsx
  packages/web/src/hooks/useKonami.ts
  packages/web/src/services/analytics/amplitude.ts
  packages/web/src/services/analytics/index.ts
  packages/web/src/services/analytics/segment.ts
Labels: size/L

#7066 [PAY-2304][PAY-2306][PAY-2308] Add old client gated backwards compatibilty and more fixes
  packages/commands/src/upload-track.mjs
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/src/queries/get_feed.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/libs/src/api/Track.ts
  packages/libs/src/sdk/api/tracks/TrackUploadHelper.ts
  packages/libs/src/sdk/api/tracks/types.ts
  packages/libs/src/sdk/sdk.ts
  packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
  packages/libs/src/sdk/services/Logger/Logger.ts
  packages/libs/src/sdk/services/Storage/Storage.ts
  packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  packages/libs/src/services/solana/SolanaWeb3Manager.ts
  packages/libs/src/utils/types.ts
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/web/src/common/store/cache/tracks/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/store/utils/stems.ts
  packages/web/src/pages/upload-page/validation.ts
Labels: size/XXL

#7077 Add ix_plays_user_item_date index
  packages/discovery-provider/ddl/migrations/0047_ix_plays_user_item_date.sql
  packages/trpc-server/.env
  packages/trpc-server/.gitignore
  packages/trpc-server/README.md
  packages/trpc-server/docker-compose.yml
  packages/trpc-server/src/db-tables.ts
  packages/trpc-server/src/db.ts
  packages/trpc-server/src/loaders.ts
  packages/trpc-server/src/routers/me-router.ts
  packages/trpc-server/src/routers/search-router.ts
  packages/trpc-server/src/routers/track-router.ts
  packages/trpc-server/test.sh
  packages/trpc-server/test/_fixtures.ts
  packages/trpc-server/test/me-router.test.ts
  packages/trpc-server/test/search.test.ts
  packages/web/src/app/App.tsx
  packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx
  packages/web/src/pages/demo-trpc/TrpcHistory.module.css
  packages/web/src/pages/demo-trpc/TrpcHistory.tsx
Labels: size/XXL

#7137 [C-3567] Add harmony-native text-link
  packages/mobile/.storybook/storybook.requires.ts
  packages/mobile/src/harmony-native/components/TextLink/TextLink.stories.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/darkBackgroundSpace.jpg
  packages/mobile/src/harmony-native/components/TextLink/types.ts
Labels: size/L

#7136 [C-3595 C-3574] Fix Upload share-banner share options
  packages/common/src/store/ui/share-modal/types.ts
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/components/share-drawer/utils.ts
  packages/stems/src/components/ProgressBar/ProgressBar.module.css
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
Labels: size/L

#7116 [C-3576] Create account logic for web
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/LoadingAccountPage.tsx
  packages/web/src/pages/sign-up-page/pages/MobileAppCtaPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/utils/determineAllowedRoutes.ts
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
  packages/web/src/utils/route.ts
Labels: size/L

#7140 Revert unintended trpc changes
  packages/trpc-server/src/db.ts
Labels: size/M

#7141 [Protocol Dashboard] Add Connect Audius Profile modal before opening OAuth popup [C-3602]
  protocol-dashboard/src/components/AppBar/AppBar.tsx
  protocol-dashboard/src/components/ConnectAudiusProfileModal/ConnectAudiusProfileModal.module.css
  protocol-dashboard/src/components/ConnectAudiusProfileModal/ConnectAudiusProfileModal.tsx
  protocol-dashboard/src/components/ManageService/ManageService.module.css
  protocol-dashboard/src/components/ManageService/ManageService.tsx
  protocol-dashboard/src/hooks/useConnectAudiusProfile.ts
Labels: size/XL

#7135 Scheduled release follow ons: usdc to special access, persist selected date, etc
  packages/common/src/store/cache/reducer.ts
  packages/discovery-provider/src/tasks/metadata.py
  packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx
  packages/mobile/src/screens/edit-track-screen/components/types.ts
  packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/components/data-entry/FormTile.jsx
  packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/types.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
  packages/web/src/pages/upload-page/fields/DatePickerField.tsx
  packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
Labels: size/L

#7143 Fix disabled hidden hint for create schedule release
  packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Labels: size/XS

#7144 Pin @types/react to 18.2.0
  package-lock.json
  package.json
  packages/common/package.json
  packages/ddex-frontend/package.json
  packages/harmony/package.json
  packages/mobile/package.json
  packages/stems/package.json
  packages/web/package.json
Labels: size/S

#7126 DDEX tailwind -> harmony
  package-lock.json
  packages/ddex-frontend/package-lock.json
  packages/ddex-frontend/package.json
  packages/ddex-frontend/postcss.config.js
  packages/ddex-frontend/src/components/App.tsx
  packages/ddex-frontend/src/components/AppWithProviders.tsx
  packages/ddex-frontend/src/components/Releases.tsx
  packages/ddex-frontend/src/components/Uploads.tsx
  packages/ddex-frontend/src/index.css
  packages/ddex-frontend/src/main.tsx
  packages/ddex-frontend/src/pages/DDEX/DDEX.module.css
  packages/ddex-frontend/src/pages/DDEX/DDEX.tsx
  packages/ddex-frontend/src/providers/ThemeProvider.tsx
  packages/ddex-frontend/src/types/emotion.d.ts
  packages/ddex-frontend/tailwind.config.js
  packages/ddex-frontend/tsconfig.json
Labels: size/XL

#7147 [C-3588] Show twitter popup on staging
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
Labels: size/S

#7138 [PAY-2299][PAY-2342][PAY-2344] More backend download gated logic changes
  packages/ddex-frontend/src/providers/useReleases.tsx
  packages/ddex/src/models/dbTypes.ts
  packages/ddex/src/services/scheduledReleaseService.ts
  packages/ddex/src/utils/xmlUtils.ts
  packages/discovery-provider/ddl/migrations/0046_add_track_metadata_columns.sql
  packages/discovery-provider/ddl/migrations/0047_update_track_metadata_columns.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/src/queries/get_track_signature.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/web/src/components/edit-track/EditTrackModal.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
Labels: size/L

#7139 rest endpoint for track top_listeners
  packages/discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_top_listeners_for_track.py
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/full/models/FullTopListener.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#7151 DDEX admin UI
  packages/ddex-frontend/.eslintrc.cjs
  packages/ddex-frontend/src/components/App.tsx
  packages/ddex-frontend/src/components/AppWithProviders.tsx
  packages/ddex-frontend/src/components/Layout.tsx
  packages/ddex-frontend/src/components/Releases.tsx
  packages/ddex-frontend/src/components/Uploads.tsx
  packages/ddex-frontend/src/components/admin/Releases.tsx
  packages/ddex-frontend/src/components/admin/Table.module.css
  packages/ddex-frontend/src/components/admin/Uploads.tsx
  packages/ddex-frontend/src/main.tsx
  packages/ddex-frontend/src/pages/DDEX/DDEX.module.css
  packages/ddex-frontend/src/pages/DDEX/DDEX.tsx
  packages/ddex-frontend/src/providers/AudiusLibsProvider.tsx
  packages/ddex-frontend/src/providers/AudiusSdkProvider.tsx
  packages/ddex-frontend/src/providers/EnvVarsProvider.tsx
  packages/ddex-frontend/src/providers/RemoteConfigProvider.tsx
  packages/ddex-frontend/src/providers/useReleases.tsx
  packages/ddex-frontend/src/providers/useUploads.tsx
  packages/ddex-frontend/src/utils/constants.ts
  packages/ddex/README.md
Labels: size/XXL

#7152 Fix lossless fields zod validation
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/src/api/v1/models/tracks.py
  packages/web/src/pages/upload-page/validation.ts
Labels: size/S

#7148 [C-3610] Positive validation for sign up handles on web
  package-lock.json
  packages/common/package.json
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useIsWaitingForValidation.ts
  packages/web/src/components/form-fields/HarmonyTextField.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
Labels: size/M

#7155 Merge main
  mediorum/.version.json
  package-lock.json
  packages/common/package.json
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useIsWaitingForValidation.ts
  packages/ddex-frontend/.eslintrc.cjs
  packages/ddex-frontend/src/components/App.tsx
  packages/ddex-frontend/src/components/AppWithProviders.tsx
  packages/ddex-frontend/src/components/Layout.tsx
  packages/ddex-frontend/src/components/Releases.tsx
  packages/ddex-frontend/src/components/Uploads.tsx
  packages/ddex-frontend/src/components/admin/Releases.tsx
  packages/ddex-frontend/src/components/admin/Table.module.css
  packages/ddex-frontend/src/components/admin/Uploads.tsx
  packages/ddex-frontend/src/main.tsx
  packages/ddex-frontend/src/pages/DDEX/DDEX.module.css
  packages/ddex-frontend/src/pages/DDEX/DDEX.tsx
  packages/ddex-frontend/src/providers/AudiusLibsProvider.tsx
  packages/ddex-frontend/src/providers/AudiusSdkProvider.tsx
  packages/ddex-frontend/src/providers/EnvVarsProvider.tsx
  packages/ddex-frontend/src/providers/RemoteConfigProvider.tsx
  packages/ddex-frontend/src/providers/useReleases.tsx
  packages/ddex-frontend/src/providers/useUploads.tsx
  packages/ddex-frontend/src/utils/constants.ts
  packages/ddex/README.md
  packages/discovery-provider/.version.json
  packages/discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_top_listeners_for_track.py
  packages/libs/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/libs/src/sdk/api/generated/full/.openapi-generator/VERSION
  packages/libs/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/libs/src/sdk/api/generated/full/models/FullTopListener.ts
  packages/libs/src/sdk/api/generated/full/models/index.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoading.tsx
  packages/mobile/src/screens/sign-on-screen/screens/AccountLoadingScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/types.ts
  packages/web/src/components/form-fields/HarmonyTextField.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
Labels: size/XXL

#7154 [C-3613] Add error feedback for new sign up flow handle input
  packages/harmony/src/components/button/BaseButton/BaseButton.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
Labels: size/XS

#7156 [PAY-2328] Track page stems & downloads section
  packages/common/src/hooks/useDownloadTrackButtons.ts
  packages/common/src/models/DownloadQuality.ts
  packages/common/src/models/index.ts
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
  packages/web/src/components/download-buttons/DownloadButtons.tsx
  packages/web/src/components/expandable/Expandable.tsx
  packages/web/src/components/summary-table/SummaryTable.module.css
  packages/web/src/components/summary-table/SummaryTable.tsx
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#7160 [C-3590] Add handle field positive validation to native
  packages/common/src/messages/sign-on/pages.ts
  packages/mobile/src/screens/sign-on-screen/components/HandleField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
Labels: size/M

#7159 Update native harmony BaseButton to not scale when full width
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
Labels: size/XS

#7146 Revert "[C-3523] Add create album card to mobile (#7129)"
  packages/mobile/src/components/collection-list/AddCollectionCard.tsx
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
Labels: size/M

#7161 Fix audio matching buyer challenge broken for verified users
  packages/discovery-provider/src/challenges/audio_matching_challenge.py
Labels: size/XS

#7164 DDEX dockerfile uses turbo
  dev-tools/compose/docker-compose.ddex.yml
  packages/Dockerfile.ddex
  packages/Dockerfile.ddex.fast
Labels: size/M

#7163 [C-3612] Update FinishProfilePage to preserve changes if the user goes back to the handle page
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Labels: size/M

#7162 [C-3618] Fix callback on upload chip
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
  packages/web/src/components/upload/UploadChip.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/S

#7167 Upgrade react-native-track-player
  package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/audio/RepeatListener.tsx
  packages/mobile/src/components/scrubber/usePosition.ts
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
Labels: size/M

#7133 Add uploadedBy and improve pagination ends
  packages/ddex-frontend/src/components/admin/Releases.tsx
  packages/ddex-frontend/src/components/admin/Uploads.tsx
  packages/ddex-frontend/src/pages/DDEX/DDEX.tsx
  packages/ddex-frontend/src/providers/useReleases.tsx
  packages/ddex-frontend/src/providers/useUploads.tsx
  packages/ddex/src/controllers/uploadsController.ts
  packages/ddex/src/services/scheduledReleaseService.ts
  packages/ddex/src/utils/xmlUtils.ts
Labels: size/L

#7169 Increment mobile versions
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7170 [C-3522] Add track suggestions to albums
  packages/common/src/api/account.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/user.ts
  packages/mobile/src/components/suggested-tracks/SuggestedCollectionTracks.tsx
  packages/mobile/src/components/suggested-tracks/components/SuggestedTracks.tsx
  packages/mobile/src/components/suggested-tracks/index.ts
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/web/src/components/suggested-tracks/SuggestedCollectionTracks.tsx
  packages/web/src/components/suggested-tracks/components/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/components/SuggestedTracks.tsx
  packages/web/src/components/suggested-tracks/index.ts
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/L

#7173 [Discovery] Allow `wallet_signature` message in CreateDashboardWalletUser tx metadata to contain user handle
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py
  packages/libs/src/sdk/api/dashboard-wallet-users/types.ts
Labels: size/L

#7171 [C-3520] Add Visit Album links to track menus
  packages/common/src/store/pages/chat/selectors.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#7174 Fix payment method bug on native mobile
  packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Labels: size/XS

#7175 Fix mobile upload download gated fields
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
Labels: size/S

#7166 [C-3572] Update WelcomeModal to prevent blur flashing when button is hovered
  packages/web/src/components/welcome-modal/WelcomeModal.tsx
Labels: size/XS

#7178 [C-3626, C-3624, C-3628] Fix add to album toast message; Album info to end of track details
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#7180 Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#7182 [C-3627] Add toasts to removeTrackFromPlaylist
  packages/common/src/store/ui/toast/slice.ts
  packages/web/src/common/store/cache/collections/commonSagas.js
Labels: size/S

#7168 Send EM transaction from Audius client for connect wallet feature [C-3604] [C-3605]
  protocol-dashboard/src/components/ManageService/ManageService.module.css
  protocol-dashboard/src/hooks/useConnectAudiusProfile.ts
  protocol-dashboard/src/hooks/useDashboardWalletUsers.ts
  protocol-dashboard/src/services/Audius/sdk.ts
  protocol-dashboard/src/services/Audius/setup.ts
  protocol-dashboard/src/store/account/hooks.ts
  protocol-dashboard/src/store/account/slice.ts
  protocol-dashboard/src/store/cache/user/hooks.ts
  protocol-dashboard/src/utils/switchNetwork.ts
Labels: size/L

#7185 Add checks for tips/purchases/audio/usdc tx history
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
  packages/discovery-provider/src/queries/health_check.py
Labels: size/M

#7186 [Web][SDK] Send EM transaction from Audius client for connect wallet feature (previously reviewed)
  packages/libs/src/sdk/index.ts
  packages/libs/src/sdk/oauth/OAuth.ts
  packages/libs/src/sdk/oauth/types.ts
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/messages.ts
  packages/web/src/pages/oauth-login-page/utils.ts
Labels: size/L

#7183 [C-3631] Fix social image uploads by reformatting the types
  packages/common/src/store/account/types.ts
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/signon/ProfileAuto.tsx
  packages/mobile/src/store/oauth/actions.ts
  packages/mobile/src/store/oauth/reducer.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/ProfilePage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
Labels: size/L

#7188 Revert "Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]"
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#7187 v1.5.60
  package-lock.json
  package.json
  packages/commands/package.json
  packages/common/package.json
  packages/compose/package.json
  packages/ddex-frontend/package.json
  packages/ddex/package-lock.json
  packages/ddex/package.json
  packages/discovery-provider/plugins/pedalboard/apps/app-template/package.json
  packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/sla-auditor/package.json
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/package.json
  packages/discovery-provider/plugins/pedalboard/packages/basekit/package.json
  packages/discovery-provider/plugins/pedalboard/packages/eslint-config-custom-server/package.json
  packages/discovery-provider/plugins/pedalboard/packages/eslint-config-custom/package.json
  packages/discovery-provider/plugins/pedalboard/packages/jest-presets/package.json
  packages/discovery-provider/plugins/pedalboard/packages/logger/package.json
  packages/discovery-provider/plugins/pedalboard/packages/storage/package.json
  packages/discovery-provider/plugins/pedalboard/packages/tsconfig/package.json
  packages/embed/package.json
  packages/es-indexer/package.json
  packages/eslint-config-audius/package.json
  packages/fixed-decimal/package.json
  packages/harmony/package.json
  packages/identity-service/package.json
  packages/libs/package.json
  packages/mobile/package.json
  packages/probers/package.json
  packages/spl/package.json
  packages/sql-ts/package.json
  packages/stems/package.json
  packages/trpc-server/package.json
  packages/web/package.json
Labels: size/M

#7190 Revert "Revert "Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]""
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/XS

#7189 repairEntityManagerUserV2
  packages/libs/src/api/Users.ts
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/M

#7191 Prepare for full app release 1.1.81
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7176 [C-3583] Improve radial-gradient, update social-button
  package-lock.json
  packages/harmony/src/components/button/SocialButton/SocialButton.tsx
  packages/mobile/package.json
  packages/mobile/src/harmony-native/components/Button/BaseButton/types.ts
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/Button/types.ts
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
  packages/mobile/src/harmony-native/components/RadialGradient/RadialGradient.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
Labels: size/L

#7179 [C-3622] Exclude 'Visit Album' from menus when already on album page
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/M

#7193 [PROTO-1599] Add OTP support
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/identity-service/src/notifications/emails/otp.js
  packages/identity-service/src/routes/authentication.js
  packages/identity-service/src/utils/otp.js
  packages/identity-service/test/authenticationTest.js
  packages/libs/src/api/Account.ts
  packages/libs/src/services/hedgehog/Hedgehog.ts
  packages/libs/src/services/identity/IdentityService.ts
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/signon/SignOn.tsx
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/pages/oauth-login-page/utils.ts
  packages/web/src/pages/sign-on/SignOnProvider.tsx
  packages/web/src/pages/sign-on/components/desktop/SignInPage.module.css
  packages/web/src/pages/sign-on/components/desktop/SignInPage.tsx
  packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx
  packages/web/src/pages/sign-on/components/mobile/InitialPage.module.css
  packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx
  packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
Labels: size/XL

#7194 Bump app builds
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#7195 Add sendgrid param
  packages/identity-service/src/routes/authentication.js
Labels: size/XS

#7197 Fix repair signup
  packages/common/src/models/Analytics.ts
  packages/web/src/common/store/pages/signon/sagas.js
Labels: size/L

#7184 [C-3632] Return null instead of NOT_FOUND in trpc-server
  packages/trpc-server/src/routers/playlist-router.ts
  packages/trpc-server/src/routers/track-router.ts
  packages/trpc-server/src/routers/user-router.ts
  packages/trpc-server/test/router.test.ts
Labels: size/S

#7198 [C-2190] Fix track player interruptions
  packages/mobile/src/app/App.tsx
Labels: size/XS

#7196 Bypass OTP for testflight account
  packages/identity-service/src/routes/authentication.js
  packages/identity-service/src/utils/otp.js
Labels: size/M

#7208 Fix audius-cmd test
  packages/commands/src/upload-track.mjs
Labels: size/M

#7201 Gitignore snippets
  .gitignore
Labels: size/XS

#7199 use slog-gorm package
  mediorum/crudr/client.go
  mediorum/go.mod
  mediorum/go.sum
  mediorum/server/db.go
Labels: size/M

#7200 [C-3614, C-3615] Update image storage for new sign up flow to conform with old structure
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/components/welcome-modal/WelcomeModal.tsx
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
Labels: size/M

#7172 [PAY-2351] Fix height on add funds
  packages/web/src/components/add-funds/AddFunds.tsx
Labels: size/XS

#7202 Fix stems & downloads appearing erroneously web
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/XS

#7211 [C-3638] Fix saga ci
  packages/mobile/dapp-store/package.json
Labels: size/XS

#7215 Fix otp after #7196
  packages/identity-service/src/routes/authentication.js
Labels: size/XS

#7216 CircleCI self-hosted runners: lower cleanup thresholds
  .circleci/scripts/periodic-cleanup
Labels: size/XS

#7217 Export plain button from harmony native
  packages/mobile/src/harmony-native/components/index.ts
Labels: size/XS

#7212 [Web] Add OTP to OAuth login flow [C-3643]
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/oauth-login-page/messages.ts
Labels: size/M

#7207 [PAY-2356] Mobile track screen stems & download section
  packages/mobile/src/components/details-tile/DetailsTile.tsx
  packages/mobile/src/components/expandable/Expandable.tsx
  packages/mobile/src/components/expandable/ExpandableArrowIcon.tsx
  packages/mobile/src/components/expandable/index.ts
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
Labels: size/XL

#6993 Make FilterButton a controlled component
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/harmony/src/components/button/FilterButton/FilterButton.stories.tsx
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/button/FilterButton/types.ts
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/mobile-filter-button/MobileFilterButton.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Labels: size/L

#7134 Remove yield* in JS file
  packages/web/src/common/store/upload/sagas.js
Labels: size/XS

#7210 [C-3583 C-3634 C-3404] Add harmony-native to native sign up
  package-lock.json
  packages/common/src/schemas/sign-on/passwordSchema.ts
  packages/common/src/utils/commonPasswordCheck.ts
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/input/TextInput/types.ts
  packages/harmony/src/components/text/Text/Text.tsx
  packages/harmony/src/foundations/typography/typography.ts
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/RadialGradient/RadialGradient.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/harmony-native/components/TextLink/ExternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
  packages/mobile/src/harmony-native/components/TextLink/types.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/types.ts
  packages/mobile/src/harmony-native/foundations/theme/theme.ts
  packages/mobile/src/screens/root-screen/RootScreen.tsx
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
  packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx
  packages/mobile/src/screens/sign-on-screen/components/HandleField.tsx
  packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx
  packages/mobile/src/screens/sign-on-screen/components/PasswordCompletionChecklist.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpPolicyText.tsx
  packages/mobile/src/screens/sign-on-screen/components/WelcomeDrawer.tsx
  packages/mobile/src/screens/sign-on-screen/components/layout.tsx
  packages/mobile/src/screens/sign-on-screen/constants.ts
  packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
  packages/web/src/common/store/pages/signon/sagas.js
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XL

#7221 [C-3149 C-3122 C-3051 C-3625 C-3481] Fix add track to playlist
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/S

#7223 Get public IP in nginx
  packages/discovery-provider/nginx_conf/nginx.conf
  packages/discovery-provider/nginx_conf/port.lua
Labels: size/M

#7204 [C-3621] Fix scrolling issues on new sign up Password & Handle pages (web)
  packages/common/src/schemas/sign-on/pickHandleSchema.ts
  packages/web/src/components/nav/desktop/NavHeader.module.css
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
Labels: size/M

#7222 [C-3639] Fix empty album tab state
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/XS
