Repository AudiusProject/apps, pull requests merged in 2024-12, with the labels that each got.

#10554 [C-5450] Add theme v2 compat for legacy mobile theme
  packages/mobile/src/utils/theme.ts
  packages/mobile/src/utils/themeV2.ts
Labels: size/L

#10559 Remove hidden-paid-scheduled flag
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/edit-collection/EditCollectionForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/edit/fields/ReleaseDateField.module.css
  packages/web/src/components/edit/fields/ReleaseDateField.tsx
  packages/web/src/components/edit/fields/ReleaseDateFieldLegacy.module.css
  packages/web/src/components/edit/fields/ReleaseDateFieldLegacy.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
  packages/web/src/components/edit/fields/stream-availability/HiddenAvailabilityFields.module.css
  packages/web/src/components/edit/fields/stream-availability/HiddenAvailabilityFields.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
  packages/web/src/hooks/useMessages.ts
  packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
Labels: size/XXL

#10560 Remove editable-access feature flag
  packages/common/src/hooks/useAccessAndRemixSettings.ts
  packages/common/src/messages/edit.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
  packages/mobile/src/components/edit/VisibilityField/VisibilityScreen.tsx
  packages/web/src/components/edit-collection/EditCollectionForm.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
  packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
  packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
  packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx
  packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
  packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Labels: size/L

#10561 Remove simple feature flags
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/L

#10555 Convert UserList to functional component
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/components/user-list/UserList.module.css
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/components/UserList.tsx
  packages/web/src/pages/favorites-page/FavoritesPage.tsx
  packages/web/src/pages/followers-page/FollowersPage.tsx
  packages/web/src/pages/following-page/FollowingPage.tsx
  packages/web/src/pages/notification-users-page/NotificationUsersPage.tsx
  packages/web/src/pages/reposts-page/RepostsPage.tsx
  packages/web/src/pages/supporting-page/SupportingPage.tsx
  packages/web/src/pages/top-supporters-page/TopSupportersPage.tsx
Labels: size/L

#10553 [C-5449] Fix track tile performance
  packages/common/src/hooks/useCollectionAccessTypeLabel.ts
  packages/common/src/hooks/useCollectionDogEar.tsx
  packages/common/src/hooks/useGatedContent.ts
  packages/common/src/hooks/useTrackAccessTypeLabel.ts
  packages/common/src/hooks/useTrackDogEar.tsx
  packages/mobile/src/components/collection/CollectionLockedStatusBadge.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileMetrics.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx
  packages/mobile/src/components/lineup-tile/TrackTileStats.tsx
  packages/mobile/src/components/track/TrackLockedStatusBadge.tsx
  packages/web/src/components/collection/CollectionCard.test.tsx
Labels: size/L

#10556 [C-5451] Harmony theme v2 QA
  packages/harmony/src/components/button/PlainButton/PlainButton.tsx
  packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx
  packages/harmony/src/foundations/color/primitive-v2.css
  packages/harmony/src/foundations/color/primitive.ts
  packages/harmony/src/foundations/color/primitiveV2.ts
  packages/harmony/src/foundations/color/semantic.ts
  packages/harmony/src/foundations/color/semanticV2.ts
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
  packages/mobile/src/styles/makeStyles.ts
  packages/mobile/src/utils/theme.ts
  packages/mobile/src/utils/themeV2.ts
  packages/web/src/components/nav/desktop/NavMenuButton.module.css
  packages/web/src/components/nav/desktop/NavMenuButton.tsx
  packages/web/src/components/notification/NotificationPanel.module.css
  packages/web/src/components/notification/NotificationPanel.tsx
  packages/web/src/components/perspective-card/PerspectiveCard.module.css
  packages/web/src/components/track/Artwork.module.css
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.module.css
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
Labels: size/L

#10563 Fix common tests due to feature flag removals
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
Labels: size/XL

#10549 [QA-1856] Fix mobile uploads hanging infinitely
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#10565 Navigate to trending after signout
  packages/web/src/store/sign-out/sagas.ts
Labels: size/XS

#10562 Convert SettingsPageProvider to functional component
  packages/web/src/pages/settings-page/SettingsPage.tsx
  packages/web/src/pages/settings-page/SettingsPageProvider.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/AccountSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/ChangeEmailPage.tsx
  packages/web/src/pages/settings-page/components/mobile/ChangePasswordPage.tsx
  packages/web/src/pages/settings-page/components/mobile/NotificationsSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/settings-page/store/errorSagas.ts
Labels: size/XL

#10567 [PAY-3625] Add feature flag to use csv function conditionally
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/src/api/v1/models/users.py
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
Labels: size/L

#10564 Retry any missin pubkeys on interval.
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/server/server.go
Labels: size/S

#10569 Add remote config value for sentry replay recording
  packages/common/src/services/remote-config/defaults.ts
  packages/common/src/services/remote-config/types.ts
  packages/web/src/services/sentry.ts
Labels: size/S

#10568 Jail demo build
  .circleci/src/workflows/web.yml
Labels: size/M

#10552 [C-5448] Add isGuest column to identity users
  packages/identity-service/sequelize/migrations/20241127191843-guest-user-state.js
  packages/identity-service/src/models/user.js
  packages/identity-service/src/routes/user.js
  packages/libs/src/api/Account.ts
Labels: size/M

#10571 Add stream/download URLs for anon track fetches on free content
  packages/discovery-provider/src/queries/query_helpers.py
Labels: size/S

#10572 Unblock identity image building
  packages/identity-service/package.json
Labels: size/XS

#10574 Convert follow/unfollow to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
Labels: size/M

#10558 Simplify cache feature flags
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/types.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/sagas.ts
  packages/web/src/common/store/cache/store.test.ts
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/queue/store.test.ts
  packages/web/src/common/store/social/collections/sagas.ts
Labels: size/XXL

#10575 Convert get mutuals to sdk
  .changeset/shiny-ads-leave.md
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_follow_intersection_users.py
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/MutualFollowersResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/models/FullMutualFollowersResponse.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/user-list/mutuals/sagas.ts
Labels: size/L

#10580 Bumb stage chain version
  pkg/core/config/genesis/stage.json
Labels: size/XS

#10576 [C-5412, C-5414] Add file replace functionality to mobile upload flow
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackFormOverflowMenuDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackFormPreviewContext.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadFileContext.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadModalScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/XL

#10579 [C-5462] Fix EditTrackForm download function
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/XS

#10582 Remove unneeded waitForLibsInit
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#10573 Fix splits issue for old usdc_purchases
  packages/discovery-provider/src/queries/get_extended_purchase_gate.py
Labels: size/XS

#10585 [PAY-3631] Migrate sub/unsubscribe to user to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/social/users/sagas.ts
Labels: size/M

#10588 Improve desktop track tile perf
  packages/common/src/hooks/content/useCollectionLockedStatusVariant.ts
  packages/common/src/hooks/content/useIsCollectionUnlockable.ts
  packages/common/src/hooks/content/useIsTrackUnlockable.ts
  packages/common/src/hooks/content/useTrackLockedStatusVariant.ts
  packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx
  packages/web/src/components/collection/CollectionLockedStatusBadge.tsx
  packages/web/src/components/collection/CollectionTileMetrics.tsx
  packages/web/src/components/collection/CollectionTileStats.tsx
  packages/web/src/components/track/TrackLockedStatusBadge.tsx
  packages/web/src/components/track/TrackTileMetrics.tsx
  packages/web/src/components/track/TrackTileStats.tsx
Labels: size/L

#10592 Adds guards to bulk fetching hooks
  packages/common/src/api/collection.ts
  packages/common/src/api/track.ts
Labels: size/S

#10566 [C-5387] Complete sign up for guest accounts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/auth/authService.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/utils/constants.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/redis.ts
  packages/identity-service/src/routes/user.js
  packages/libs/src/api/Account.ts
  packages/sdk/src/sdk/api/users/types.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/components/guest-checkout/GuestCheckout.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
  packages/web/src/pages/sign-in-page/SignInRootPage.tsx
  packages/web/src/pages/sign-up-page/components/EmailField.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/XL

#10594 Fix src imports leading to web type errors
  packages/common/src/services/auth/authService.ts
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
Labels: size/S

#10593 Shorter rollup intervals for stage and prod core
  pkg/core/chain/auditor.go
  pkg/core/config/config.go
Labels: size/XS

#10596 [C-5413, C-5415] Add FileReplace to the mobile edit track flow
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackConfirmationDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/components/index.ts
  packages/mobile/src/screens/edit-track-screen/types.ts
  packages/mobile/src/screens/edit-track-screen/util.ts
  packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
Labels: size/L

#10581 [PAY-3571] Use new image components in mobile
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useImageSize.ts
  packages/common/src/hooks/useImageSize2.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/ProfilePicture.tsx
  packages/mobile/src/components/core/UserCoverPhoto.tsx
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/image/CollectionImageV2.tsx
  packages/mobile/src/components/image/CoverPhoto.tsx
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/image/TrackImageV2.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/Artwork.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/components/track-list/TrackArtwork.tsx
  packages/mobile/src/components/user-list/UserCard.tsx
  packages/mobile/src/harmony-native/components/FastImage/FastImage.tsx
  packages/mobile/src/hooks/useContentNodeImage.ts
  packages/mobile/src/hooks/useImageSize.ts
  packages/mobile/src/screens/chat-screen/ChatBlastSubHeader.tsx
  packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/store/account/sagas.ts
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/components/ai-attribution-modal/SearchBarResult.jsx
  packages/web/src/components/search/SearchBarResult.jsx
  packages/web/src/hooks/useCollectionCoverArt.ts
  packages/web/src/hooks/useCoverPhoto.ts
  packages/web/src/hooks/useImageSize.test.tsx
  packages/web/src/hooks/useProfilePicture.ts
  packages/web/src/hooks/useTrackCoverArt.ts
Labels: size/XXL

#10598 add analyze flag to individual tracks
  pkg/mediorum/server/audio_analysis.go
  pkg/mediorum/server/serve_upload.go
Labels: size/S

#10601 [PAY-3636] Migrate getSignature to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/ui/vip-discord-modal/sagas.ts
  packages/common/src/utils/streaming.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/player/store.test.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/M

#10602 Fix artist dashboard page
  packages/web/src/pages/dashboard-page/store/sagas.ts
Labels: size/S

#10595 [C-5454] Add mobile web guest checkout flow
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/web/src/components/guest-checkout/GuestCheckout.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/GuestCheckoutPage.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/PurchaseContentPage.tsx
Labels: size/L

#10605 [C-5469] Fix repost avatar-list spacing
  packages/web/src/components/collection/CollectionTileMetrics.tsx
  packages/web/src/components/track/TrackTileMetrics.tsx
Labels: size/S

#10583 [PAY-3629] Migrate get/changeUserEmail to identity service
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/auth/authService.ts
  packages/common/src/services/auth/identity.ts
  packages/libs/src/services/identity/IdentityService.ts
  packages/mobile/src/screens/change-email-screen/SubScreens.tsx
  packages/mobile/src/screens/change-password-screen/ResendCodeLink.tsx
  packages/web/src/components/change-email/ChangeEmailModal.tsx
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/utils.ts
Labels: size/L

#10604 [PAY-3633] Migrate getUserListenCountsMonthly to sdk
  .changeset/brave-hounds-smash.md
  packages/discovery-provider/src/api/v1/users.py
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/ListenCount.ts
  packages/sdk/src/sdk/api/generated/default/models/MonthlyAggregatePlay.ts
  packages/sdk/src/sdk/api/generated/default/models/UserTrackListenCountsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/web/src/pages/dashboard-page/store/sagas.ts
Labels: size/L

#10570 Sign Up Hardening Collection 1
  packages/common/src/messages/sign-on/socialMediaMessages.ts
  packages/common/src/models/ErrorReporting.ts
  packages/common/src/utils/sagaHelpers.ts
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/components/useSocialMediaLoader.tsx
  packages/mobile/src/store/oauth/sagas.ts
  packages/mobile/src/utils/reportToSentry.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/tiktok-auth/TikTokAuthButton.tsx
  packages/web/src/components/twitter-auth/TwitterAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
Labels: size/XL

#10541 ⚠️ [PAY-3586] Migrate upload to sdk
  .changeset/dirty-turkeys-punch.md
  .changeset/eighty-worms-retire.md
  .changeset/strong-eyes-buy.md
  packages/common/src/adapters/track.ts
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/common/src/store/confirmer/index.ts
  packages/common/src/store/upload/actions.ts
  packages/common/src/store/upload/types.ts
  packages/sdk/src/sdk/api/albums/types.ts
  packages/sdk/src/sdk/api/playlists/types.ts
  packages/sdk/src/sdk/api/tracks/TrackUploadHelper.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
  packages/sdk/src/sdk/api/users/types.ts
  packages/sdk/src/sdk/services/Storage/Storage.ts
  packages/sdk/src/sdk/services/Storage/index.ts
  packages/sdk/src/sdk/services/Storage/types.ts
  packages/sdk/src/sdk/types/File.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/tracks/store.test.ts
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/XXL

#10611 Fix sdk typecheck
  packages/sdk/src/sdk/api/users/types.ts
Labels: size/XS

#10613 add new proto dirs to release notification
  scripts/get-release-dirs.sh
Labels: size/XS

#10612 [QA-1852] Fix case sensitivity issues in login GET route
  packages/identity-service/src/routes/authentication.js
  packages/identity-service/test/authenticationTest.js
Labels: size/S

#10603 [PAY-3619] Remove libs dependency for collectibles/assoc wallets
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/discovery-provider/default_config.ini
  packages/discovery-provider/src/api/v1/cid_data.py
  packages/discovery-provider/src/api/v1/users.py
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/CidDataApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/index.ts
  packages/sdk/src/sdk/api/generated/full/models/CidData.ts
  packages/sdk/src/sdk/api/generated/full/models/CidDataResponse.ts
  packages/sdk/src/sdk/api/generated/full/models/DataAndType.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/sdk/src/sdk/sdk.ts
  packages/web/src/__mocks__/fetchCID.js
  packages/web/src/common/store/pages/deactivate-account/sagas.ts
  packages/web/src/common/store/pages/settings/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/XL

#10615 Fix typo
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/discovery-provider/src/api/v1/cid_data.py
  packages/sdk/src/sdk/api/generated/full/apis/CidDataApi.ts
  packages/web/src/common/store/profile/sagas.js
Labels: size/S

#10614 [C-5468, C-5470] Update downloads for file-replace
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/M

#10591 [C-5463] Tags and name updates for upload errors
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
  packages/web/src/store/errors/reportToSentry.ts
Labels: size/M

#10617 Fix signup error due to missing yield statement
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/XS

#10620 update a missed updateCreator call with new signature
  packages/web/src/common/store/profile/sagas.js
Labels: size/XS

#10623 Fix invalid playlist fetching
  packages/discovery-provider/src/api/v1/users.py
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts
  packages/web/src/pages/dashboard-page/store/sagas.ts
Labels: size/M

#10622 Fix track audio replace edits
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#10624 Fix mobile upload image input missing
  packages/mobile/src/components/fields/PickArtworkField.tsx
  packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
Labels: size/XS

#10628 Reduce code dupe, add spinner, fix performance on profile collections
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#10626 Setup backend on sdk signup
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/S

#10608 Two small cleanups
  packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
  packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
Labels: size/S

#10629 [PAY-2936] Move notification writes to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/playlist-updates/playlistUpdatesSagas.ts
  packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
  packages/sdk/src/sdk/api/notifications/NotificationsApi.ts
  packages/sdk/src/sdk/api/notifications/types.ts
  packages/sdk/src/sdk/sdk.ts
  packages/web/src/common/store/notifications/sagas.ts
Labels: size/L

#10632 Remove getUserEmail from libs Account
  packages/libs/src/api/Account.ts
Labels: size/XS

#10633 Fix NotificationsApi to not require authService dep
  packages/sdk/src/sdk/api/notifications/NotificationsApi.ts
  packages/sdk/src/sdk/sdk.ts
Labels: size/S

#10631 [PAY-3634] Move updateCreator to sdk
  packages/common/src/adapters/user.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
Labels: size/L

#10610 [C-5472] Refactor message drawers to use common drawers
  packages/mobile/src/components/action-drawer/ActionDrawer.tsx
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
  packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
  packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
  packages/mobile/src/components/drawer/NativeDrawer.tsx
Labels: size/L

#10625 Improve mobile entity collection screen loading
  packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/M

#10636 Remove getRandomFeePayer
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/solana/sagas.ts
Labels: size/M

#10639 Fix audius-cmd purchase gated content
  packages/commands/src/album/purchase-album.ts
  packages/commands/src/misc/auth-headers.ts
  packages/commands/src/misc/claim-reward.ts
  packages/commands/src/misc/mint.ts
  packages/commands/src/misc/withdraw-tokens.ts
  packages/commands/src/track/purchase-track.ts
  packages/commands/src/track/upload-track.ts
  packages/commands/src/user/tip-user.ts
Labels: size/M

#10627 [C-5477] Guard against empty response from storage node
  .changeset/polite-bikes-appear.md
  packages/libs/src/services/creatorNode/CreatorNode.ts
  packages/sdk/src/sdk/services/Storage/Storage.ts
Labels: size/S

#10640 Fix NotificationsApiTest
  packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
Labels: size/S

#10600 Correct rewards page collectibles gating
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
Labels: size/S

#10642 Upgrade mobile apps to v1.1.128
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#10644 Finalize harmony theme v2
  packages/harmony/src/foundations/color/primitive-v2.css
  packages/harmony/src/foundations/color/primitiveV2.ts
Labels: size/L

#10646 [QA-1873] Add back cache subscribe so UIDs get set correctly for playlists
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/types.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/sagas.ts
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
Labels: size/L

#10647 Upgrade something went wrong page error level
  packages/mobile/src/app/ErrorBoundary.tsx
  packages/web/src/app/AppErrorBoundary.tsx
Labels: size/S

#10635 Migrate getWaudioBalance to sdk + remove getSolanaConnection
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/buy-crypto/sagas.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
Labels: size/L

#10648 Up weekly pool for trending challenges
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
Labels: size/S

#10634 Misc libs cleanup
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/confirmer/sagas.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/common/store/social/tracks/store.test.ts
  packages/web/src/services/audius-api-client/apiClient.ts
  packages/web/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/signOut.ts
Labels: size/L

#10607 [C-5455] Add mobile guest checkout sign up
  packages/common/src/store/account/selectors.ts
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/mobile/src/screens/sign-on-screen/components/EmailInUseHint.tsx
  packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/types.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/pages/sign-up-page/components/EmailField.tsx
  packages/web/src/pages/sign-up-page/components/NewEmailField.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetailsPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
Labels: size/L

#10637 Update harmony v2 colors
  packages/harmony/src/foundations/color/primitive-v2.css
  packages/harmony/src/foundations/color/primitiveV2.ts
  packages/harmony/src/foundations/color/semanticV2.ts
Labels: size/L

#10653 [C-5481] Mobile harmony-theme-v2 QA
  packages/harmony/src/foundations/color/primitiveV2.ts
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/TextLink/TextPressable.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
  packages/mobile/src/harmony-native/constants.ts
  packages/mobile/src/styles/makeAnimations.ts
  packages/mobile/src/utils/themeV2.ts
Labels: size/L

#10655 Validate upload template + placement_hosts
  pkg/mediorum/server/db.go
  pkg/mediorum/server/serve_upload.go
  pkg/mediorum/server/serve_upload_test.go
Labels: size/M

#10658 Fix audius-cmd identity service functionality
  packages/commands/src/utils.ts
Labels: size/S

#10643 Sign up hardening round 2
  packages/mobile/src/hooks/useTikTokAuth.ts
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
  packages/web/src/components/instagram-auth/InstagramAuth.tsx
  packages/web/src/components/instagram-auth/InstagramAuthButton.tsx
  packages/web/src/components/social-button/index.ts
  packages/web/src/components/social-button/instagram-button/InstagramButton.module.css
  packages/web/src/components/social-button/instagram-button/InstagramButton.tsx
  packages/web/src/components/social-button/tiktok-button/TikTokButton.tsx
  packages/web/src/components/social-button/twitter-button/TwitterButton.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/components/tiktok-auth/TikTokAuthButton.tsx
  packages/web/src/components/twitter-auth/TwitterAuth.tsx
  packages/web/src/components/twitter-auth/TwitterAuthButton.tsx
  packages/web/src/pages/audio-rewards-page/components/modals/VerifiedUpload.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowInstagramAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowTwitterAuth.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
Labels: size/XL

#10660 Improve uptime console page
  pkg/core/console/uptime.go
  pkg/core/console/views/pages/uptime_page.templ
  pkg/core/console/views/pages/uptime_page_templ.go
  pkg/core/db/reads.sql.go
  pkg/core/db/sql/reads.sql
Labels: size/L

#10657 [PAY-3632] Migrate socials code off of libs
  packages/common/src/api/signUp.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/auth/identity.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/screens/change-email-screen/SubScreens.tsx
  packages/mobile/src/screens/change-password-screen/ResendCodeLink.tsx
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/identity.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/app/AudiusQueryProvider.tsx
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/change-email/ChangeEmailModal.tsx
  packages/web/src/pages/oauth-login-page/hooks.ts
  packages/web/src/pages/oauth-login-page/utils.ts
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/audius-sdk/identity.ts
  packages/web/src/services/audius-sdk/index.ts
  packages/web/src/store/storeContext.ts
Labels: size/XL

#10651 [PAY-3640] Convert getAssociatedTokenAccountInfo to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
Labels: size/L

#10663 C 5473 guest mode UI
  packages/common/src/store/account/selectors.ts
  packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavCTA.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.jsx
  packages/web/src/components/profile-progress/hooks/index.js
  packages/web/src/hooks/useRequiresAccount.ts
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/XL

#10659 Sign Up Hardening 2.5
  packages/mobile/src/hooks/useTikTokAuth.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/twitter-auth/TwitterAuthButton.tsx
Labels: size/M

#10661 [PAY-3643] Improve feed performance
  packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/tmp.txt
  packages/discovery-provider/src/queries/get_feed_es.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/utils/elasticdsl.py
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
Labels: size/L

#10652 [PAY-3641] Migrate sendWAudioTokens to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
Labels: size/L

#10654 Migrate `getAddressWAudioBalance` to sdk
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
Labels: size/M

#10630 [C-5456] Migrate guest checkout user creation to SDK
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/purchase-content/slice.ts
  packages/sdk/src/sdk/api/albums/AlbumsApi.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/GuestCheckoutPage.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/PurchaseContentPage.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/account/sagas.ts
Labels: size/L

#10667 Revert "[PAY-3643] Improve feed performance (#10661)"
  packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/tmp.txt
  packages/discovery-provider/src/queries/get_feed_es.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/utils/elasticdsl.py
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
Labels: size/L

#10656 [C-5479] Add error states for track replace progress
  packages/common/src/store/ui/modals/replace-track-progress-modal/index.ts
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
Labels: size/L

#10666 Migrate native TextButton to PlainButton and Divider to harmony
  packages/mobile/src/components/core/ContextualMenu.tsx
  packages/mobile/src/components/core/Divider.tsx
  packages/mobile/src/components/core/Pill.tsx
  packages/mobile/src/components/core/TextButton.tsx
  packages/mobile/src/components/core/TextInput.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/user-list/UserCardSkeleton.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/TextInputAccessoryView.tsx
  packages/mobile/src/harmony-native/foundations/color/Color.stories.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/VanityMetrics.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionForm.tsx
  packages/mobile/src/screens/edit-collection-screen/RandomImageButton.tsx
  packages/mobile/src/screens/edit-collection-screen/TrackListFieldArray.tsx
  packages/mobile/src/screens/edit-profile-screen/FormScreen.tsx
  packages/mobile/src/screens/edit-track-screen/fields/LicenseTypeField.tsx
  packages/mobile/src/screens/edit-track-screen/fields/SelectMoodField.tsx
  packages/mobile/src/screens/edit-track-screen/screens/LicenseTypeScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandedSection.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/screens/settings-screen/Divider.tsx
  packages/mobile/src/screens/settings-screen/DownloadSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/SettingsDivider.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
  packages/mobile/src/screens/tip-artist-screen/ConfirmSendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
Labels: size/XL

#10668 [C-5464] Track Replace QA 1
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
Labels: size/S

#10669 Update theme-v2 matrix colors
  packages/harmony/src/foundations/color/primitive-v2.css
  packages/harmony/src/foundations/color/primitiveV2.ts
Labels: size/L

#10672 Fix sentry mobile scope issue
  packages/common/src/store/storeContext.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/store/storeContext.ts
Labels: size/S

#10674 Fix buy button width
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
Labels: size/XS

#10679 [PAY-3649] Fix something went wrong on transactions page
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
Labels: size/XS

#10678 [PAY-3679] Fix legacy images without sizes
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/M

#10675 Fix connected wallet wAUDIO balance fetching
  packages/common/src/services/audius-backend/AudiusBackend.ts
Labels: size/XS

#10676 Pass in ethWallet to decorateCoinflowWithdrawalTransaction
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/services/audius-backend/solana.ts
Labels: size/S

#10671 Remove one-to-many-dms feature flag
  packages/common/src/hooks/chats/index.ts
  packages/common/src/hooks/chats/useSetInboxPermissionsLegacy.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreen.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenLegacy.tsx
  packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModal.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalLegacy.module.css
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalLegacy.tsx
  packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
  packages/web/src/components/user-list-modal/components/UserListModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/XXL

#10673 Fix syncing of guest accounts upon profile completion
  packages/common/src/store/account/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/S

#10687 Fix mobile lint
  packages/mobile/src/services/buyCrypto.ts
Labels: size/XS

#10684 [PAY-2937] Migrate remaining Identity off libs
  packages/common/src/hooks/useChangeEmailFormConfiguration.ts
  packages/common/src/hooks/useChangePasswordFormConfiguration.ts
  packages/common/src/services/auth/authService.ts
  packages/common/src/services/auth/hedgehog.ts
  packages/common/src/services/auth/identity.ts
  packages/web/src/common/store/change-password/sagas.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#10686 Fix discovery tests
  packages/discovery-provider/src/api/v1/helpers.py
Labels: size/XS

#10685 [PAY-3689] Migrate getRootSolanaAccount to an injected common service
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/index.ts
  packages/common/src/services/solana/createHedgehogSolanaWalletService.ts
  packages/common/src/services/solana/index.ts
  packages/common/src/services/solana/types.ts
  packages/common/src/store/buy-crypto/sagas.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/store/storeContext.ts
  packages/web/src/app/AudiusQueryProvider.tsx
  packages/web/src/common/store/account/sagas.js
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
  packages/web/src/services/audius-sdk/auth.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
  packages/web/src/store/storeContext.ts
Labels: size/L

#10688 [QA-1875] Clear badge count on `notification_seen` row add
  packages/discovery-provider/plugins/notifications/src/listener.ts
  packages/discovery-provider/plugins/notifications/src/main.ts
  packages/discovery-provider/plugins/notifications/src/notificationSeenListener.ts
  packages/discovery-provider/plugins/notifications/src/setup.ts
Labels: size/L

#10683 [C-5441] Handle sign on redirects
  packages/web/src/components/RestrictedLink.tsx
  packages/web/src/components/SignOnLink.tsx
  packages/web/src/components/link/TextLink.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavCTA.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/hooks/useRequiresAccount.ts
Labels: size/L

#10689 add redis volume to audius-d
  pkg/orchestration/docker.go
Labels: size/XS

#10682 [C-5492] Guest sign-up copy and improvements
  packages/common/src/messages/sign-on/pages.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/schemas/sign-on/signInSchema.ts
  packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx
  packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-on-page/GuestEmailHint.tsx
  packages/web/src/pages/sign-up-page/components/NewEmailField.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
Labels: size/L

#10664 Refactor profile progress to ts
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/profile-progress/ConnectedProfileCompletionHeroCard.jsx
  packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.jsx
  packages/web/src/components/profile-progress/ProfileCompletionPanel.module.css
  packages/web/src/components/profile-progress/ProfileCompletionPanel.tsx
  packages/web/src/components/profile-progress/components/ProfileCompletionHeroCard.jsx
  packages/web/src/components/profile-progress/components/ProfileCompletionHeroCard.tsx
  packages/web/src/components/profile-progress/components/ProfileCompletionPanel.jsx
  packages/web/src/components/profile-progress/components/ProfileCompletionTooltip.tsx
  packages/web/src/components/profile-progress/components/PropTypes.js
  packages/web/src/components/profile-progress/components/TaskCompletionItem.tsx
  packages/web/src/components/profile-progress/components/TaskCompletionList.tsx
  packages/web/src/components/profile-progress/components/types.ts
  packages/web/src/components/profile-progress/hooks.ts
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/XL

#10694 Fix premium modal footer for signed in users
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Labels: size/XS

#10691 fix go linter
  pkg/orchestration/docker.go
Labels: size/XS

#10698 Make getKeypair async since hedgehog init is async
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/services/solana/createHedgehogSolanaWalletService.ts
  packages/common/src/services/solana/types.ts
  packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx
  packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
Labels: size/S

#10692 [PAY-3687] Fix updateCreator wallets issue
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/account/sagas.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
Labels: size/M

#10699 [PAY-3676] Expand audio mime types accepted by sdk
  .changeset/dirty-berries-mix.md
  packages/sdk/src/sdk/types/File.ts
Labels: size/S

#10695 [C-5466] Enable pay with anything and changing guest email
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/GuestCheckoutPage.tsx
Labels: size/M

#10701 Feature flag fast referral signup
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/sign-up-page/hooks/useFastReferral.ts
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/LoadingAccountPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/M

#10702 [C-5505] Fix default track field visibility
  packages/web/src/common/store/cache/tracks/utils/reformat.ts
Labels: size/XS

#10703 [PAY-3692] [PAY-3650] Use generate_preview endpoint to improve editing of track previews
  .changeset/modern-geckos-enjoy.md
  .changeset/spicy-kiwis-argue.md
  packages/sdk/src/sdk/api/albums/AlbumsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/tracks/TrackUploadHelper.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/services/Storage/Storage.ts
  packages/sdk/src/sdk/services/Storage/types.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
Labels: size/L

#10696 [C-5520] Add guest checkout UI in purchase and sale emails
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
Labels: size/L

#10697 [C-5519, C-5521] Add guest mode UI in claim rewards email
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/claimableReward.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/claimableReward.ts
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
Labels: size/L

#10690 [PAY-3622] Update encryption patterns and add manager delegation
  packages/common/src/store/purchase-content/sagas.ts
  packages/discovery-provider/ddl/migrations/0108_update_email_tables.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_email_entity_manager.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/models/users/email.py
  packages/discovery-provider/src/queries/download_csv.py
  packages/discovery-provider/src/tasks/entity_manager/entities/email.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/SaleJson.ts
  packages/sdk/src/sdk/api/generated/default/models/SalesJsonContent.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
  packages/sdk/src/sdk/services/Encryption/EmailEncryptionService.ts
  packages/sdk/src/sdk/services/Encryption/types.ts
  packages/sdk/src/sdk/services/EntityManager/types.ts
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
Labels: size/XXL

#10693 Add non-genesis validators to comet consensus
  .hooks/pre-commit.json
  cmd/core/infra/dev_config/dev-sandbox.env
  cmd/core/infra/dev_config/prod-sandbox.env
  cmd/core/infra/dev_config/stage-sandbox.env
  cmd/core/infra/docker-compose.yml
  pkg/core/chain/abci.go
  pkg/core/chain/register_node.go
  pkg/core/common/converters.go
  pkg/core/config/config.go
  pkg/core/core.go
  pkg/core/gen/models/protocol_validator_registration.go
  pkg/core/gen/proto/protocol.pb.go
  pkg/core/gen/proto/protocol.swagger.json
  pkg/core/mempool/mempool.go
  pkg/core/proto/protocol.proto
  pkg/core/registry_bridge/register.go
Labels: size/L

#10704 Misc client analytics tweaks
  packages/common/src/models/Analytics.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/store/analytics/sagas.ts
  packages/web/src/store/errors/sagas.ts
Labels: size/M

#10707 [PAY-3691] Sanitize upload filename for react-native
  packages/sdk/src/sdk/services/Storage/Storage.ts
Labels: size/S

#10708 [C-5509] Fix track title reset on replace track edit
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
Labels: size/S

#10705 Add searchTags SDK support
  packages/discovery-provider/src/api/v1/search.py
  packages/discovery-provider/src/queries/search_es.py
  packages/discovery-provider/src/queries/search_queries.py
  packages/sdk/src/sdk/api/generated/full/apis/SearchApi.ts
Labels: size/L

#10711 [PAY-3675] Fix issues with scheduled releases
  .changeset/fresh-crabs-end.md
  packages/common/src/adapters/track.ts
  packages/mobile/src/components/core/DateTimeInput.tsx
  packages/mobile/src/components/edit/VisibilityField/ScheduledReleaseDateField.tsx
  packages/sdk/src/sdk/api/albums/AlbumsApi.ts
  packages/sdk/src/sdk/api/albums/types.ts
  packages/sdk/src/sdk/api/playlists/types.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
Labels: size/XL

#10706 [QA-1864][PAY-3690] Migrate searchTags to SDK
  packages/common/src/api/search.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/screens/search-screen/search-results/AllResults.tsx
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.ts
Labels: size/L

#10714 Fix audiusd ci
  .circleci/src/jobs/@audiusd-jobs.yml
  .circleci/src/workflows/audiusd.yml
  .circleci/src/workflows/core.yml
  pkg/conf/override.go
Labels: size/S

#10715 Remove a few miscellaneous libs references
  packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/solana/solana.ts
Labels: size/M

#10716 More CI fixes for audiusd
  .circleci/src/workflows/audiusd.yml
  pkg/conf/override.go
Labels: size/XS

#10717 rm long migration
  packages/discovery-provider/ddl/migrations/0109_backfill_prod_audio_analysis.sql
Labels: size/XXL

#10721 Make audiusd ci build faster
  .circleci/src/jobs/@audiusd-jobs.yml
  .circleci/src/workflows/audiusd.yml
  Makefile
  cmd/audiusd/Dockerfile
  cmd/audiusd/Dockerfile.cpp
Labels: size/L

#10722 Bump stage core version
  pkg/core/config/genesis/stage.json
Labels: size/XS

#10723 Bump stage to testnet-10
  pkg/core/config/genesis/stage.json
Labels: size/XS

#10725 Remove duplicate validator updates
  pkg/core/chain/abci.go
  pkg/core/chain/register_node.go
Labels: size/M

#10720 [PAY-3646] Remove audius api client
  packages/common/src/adapters/activity.ts
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/services/audius-api-client/AudiusAPIClient.ts
  packages/common/src/services/audius-api-client/ResponseAdapter.ts
  packages/common/src/services/audius-api-client/helper.ts
  packages/common/src/services/audius-api-client/index.ts
  packages/common/src/services/audius-api-client/makeActivity.ts
  packages/common/src/services/audius-api-client/types.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/explore/Explore.ts
  packages/common/src/services/index.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/reachability/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/preview.ts
  packages/common/src/utils/streaming.ts
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/mobile/src/services/audius-api-client/apiClient.ts
  packages/mobile/src/services/audius-api-client/index.ts
  packages/mobile/src/services/wallet-client.ts
  packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
  packages/mobile/src/store/storeContext.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/web/src/app/AudiusQueryProvider.tsx
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/pages/history/lineups/sagas.ts
  packages/web/src/common/store/pages/saved/sagas.ts
  packages/web/src/common/store/player/sagas.ts
  packages/web/src/common/store/player/store.test.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/services/audius-api-client/apiClient.ts
  packages/web/src/services/audius-api-client/index.ts
  packages/web/src/services/wallet-client.ts
  packages/web/src/ssr/collection/+onBeforeRender.ts
  packages/web/src/ssr/profile/+onBeforeRender.tsx
  packages/web/src/ssr/track/+onBeforeRender.tsx
  packages/web/src/store/storeContext.ts
Labels: size/XXL

#10729 Clean up some other lingering libs usage
  packages/common/src/api/signUp.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/auth/authService.ts
  packages/common/src/services/auth/identity.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/recovery-email/sagas.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/AccountSettingsPage.tsx
Labels: size/L

#10713 [C-5386] Guest checkout sale notifications and UI
  packages/common/src/store/cache/users/selectors.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumSaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
  packages/web/src/pages/pay-and-earn-page/components/BuyerUserLink.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.module.css
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
Labels: size/L

#10733 Add back notification settings
  packages/identity-service/src/routes/notificationSettings.js
Labels: size/M

#10736 Undo added fatal sentry logs (keep them only on "crashes")
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/recovery-email/sagas.ts
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#10737 [C-5540] Stop logging console & network errors to sentry
  packages/web/src/services/sentry.ts
Labels: size/XS

#10734 prod audio analysis backfill
  packages/discovery-provider/ddl/migrations/0109_backfill_prod_audio_analysis.sql
Labels: size/XXL

#10742 Fix guestEmail account slice
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/slice.ts
Labels: size/M

#10731 Improve sdk bundle size for SSR purposes
  packages/common/src/adapters/access.ts
  packages/common/src/adapters/accessConditionsFromSDK.ts
  packages/common/src/adapters/accessConditionsToSDK.ts
  packages/common/src/adapters/collection.ts
  packages/common/src/adapters/imageSize.ts
  packages/common/src/adapters/index.ts
  packages/common/src/adapters/playlistLibrary.ts
  packages/common/src/adapters/track.ts
  packages/sdk/package.json
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/utils/web3.ts
Labels: size/L

#10741 [PAY-3653] Re-land feed performance improvements
  packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/tmp.txt
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/models/feed.py
  packages/discovery-provider/src/queries/get_feed_es.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/discovery-provider/src/utils/elasticdsl.py
  packages/sdk/src/sdk/api/generated/full/models/PlaylistFeedItem.ts
  packages/web/src/common/store/lineup/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
Labels: size/L
