Repository AudiusProject/apps, pull requests merged in 2025-09, with the labels that each got.

#12830 [PE-6757] Mobile receive tokens drawer
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/core/TokenIcon.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/leaving-audius-drawer/LeavingAudiusDrawer.tsx
  packages/mobile/src/components/receive-tokens-drawer/ReceiveTokensDrawer.tsx
  packages/mobile/src/components/receive-tokens-drawer/index.ts
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
  packages/mobile/src/utils/zIndex.ts
Labels: size/L

#12831 Disable coin hooks in UserBadges when ff disabled
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/M

#12822 Fix mobile follow button flickering
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
Labels: size/XS

#12833 Fix disabled user link
  packages/mobile/src/components/user-link/UserLink.tsx
Labels: size/S

#12832 Mobile explore improvements
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/ForYouTracks.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Labels: size/M

#12834 [PE-6784] Scaffold UI for launchpad
  packages/common/src/utils/route.ts
  packages/harmony/src/assets/icons/ArtistCoin.svg
  packages/harmony/src/components/input/TokenAmountInput/TokenAmountInput.tsx
  packages/harmony/src/components/input/TokenAmountInput/types.ts
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/icons.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/assets/fonts/emojis/gift.png
  packages/web/src/assets/fonts/emojis/globe.png
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/nav-items/ArtistCoinsNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/index.ts
  packages/web/src/hooks/useFormImageUrl.ts
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsSubmitRow.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/BuyCoinPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/CoinFormFields.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ImageUploadArea.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchPanel.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ReviewPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/SetupPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/SplashScreen.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/StepHeader.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/WalletSetupCard.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/WhyCreateCard.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/index.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/types.ts
  packages/web/src/pages/artist-coins-launchpad-page/constants.ts
  packages/web/src/pages/artist-coins-launchpad-page/index.ts
  packages/web/src/pages/artist-coins-launchpad-page/validation.ts
Labels: size/XXL

#12826 Update trending rewards plugin to utilize new rewards api
  .changeset/big-hats-sneeze.md
  .changeset/smart-houses-film.md
  packages/common/src/utils/coinMetrics.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/sdk.ts
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/CoinsApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/RewardsApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/index.ts
  packages/sdk/src/sdk/api/generated/default/models/ClaimRewardsRequest.ts
  packages/sdk/src/sdk/api/generated/default/models/ClaimRewardsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/ClaimRewardsResponseDataInner.ts
  packages/sdk/src/sdk/api/generated/default/models/Coin.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinInsights.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinInsightsDynamicBondingCurve.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/sdk/src/sdk/api/generated/full/models/CosignNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/RemixNotificationActionData.ts
  packages/sdk/src/sdk/api/generator/templates/typescript-fetch/apis.mustache
  packages/sdk/src/sdk/index.ts
  packages/sdk/src/sdk/sdk.ts
Labels: size/XL

#12838 Upgrade android sdk target to 35
  packages/mobile/android/build.gradle
Labels: size/XS

#12842 Update SDK with /coins/ticker/:ticker change
  packages/sdk/src/sdk/api/generated/default/apis/CoinsApi.ts
Labels: size/M

#12843 [PE-6613] Make asset detail pages use ticker instead of mint
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useArtistCoinByTicker.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/utils/route.ts
  packages/web/src/pages/all-coins-page/AllCoinsPage.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/M

#12836 [PE-6753] Send any token
  packages/common/src/api/tan-query/wallets/useSendTokens.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/mobile/src/services/wallet-client.ts
  packages/sdk/src/sdk/services/Solana/programs/types.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/services/wallet-client.ts
Labels: size/L

#12855 [PE-6759] Update error stages in swap hook
  packages/common/src/api/tan-query/jupiter/directSwap.ts
  packages/common/src/api/tan-query/jupiter/indirectSwapViaAudio.ts
  packages/common/src/api/tan-query/jupiter/types.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
Labels: size/XL

#12850 [PE-6771] Add hover states to user token badge component
  packages/web/src/components/user-token-badge/UserTokenBadge.tsx
Labels: size/M

#12862 Update api Go module import
  packages/discovery-provider/ddl/run_migrations.go
Labels: size/XS

#12868 Fix download all when track download not available
  packages/common/src/api/tan-query/tracks/useDownloadTrackStems.ts
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/track-page/components/mobile/DownloadSection.tsx
Labels: size/M

#12869 [PE-6799] Web artist coin explore page
  .changeset/nasty-candles-add.md
  packages/common/src/store/ui/modals/buy-sell-modal/index.ts
  packages/common/src/utils/route.ts
  packages/harmony/src/foundations/color/primitive.css
  packages/harmony/src/foundations/color/primitive.ts
  packages/harmony/src/utils/formatCount.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/nav/desktop/nav-items/ArtistCoinsNavItem.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/pages/all-coins-page/AllCoinsPage.tsx
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.module.css
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchPanel.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/index.ts
Labels: size/XL

#12878 Only show audio card when feature flag is disabled
  packages/common/src/store/ui/buy-sell/useGroupCoinPairs.ts
Labels: size/S

#12880 Fix tooltip positioning in buy/sell modal
  packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
Labels: size/XS

#12883 Use price from BE in formatter and deprecate `useTokenPrice`
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/wallets/useTokenPrice.ts
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/common/src/hooks/useFormattedTokenBalance.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/mobile/src/screens/buy-sell-screen/components/BuyScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SellScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/ConvertTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
Labels: size/L

#12875 [API-100] Integrate new Rewards endpoint with client
  packages/commands/src/misc/claim-reward.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
Labels: size/S

#12894 [QA-2325] Fix audio balance user badges
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/hooks/useFormattedTokenBalance.ts
Labels: size/M

#12895 Fix token-info-row tooltip mount
  packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
Labels: size/XS

#12893 Refactor Token Filtering and Display Logic for Artist Coins
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useFormattedTokenBalance.ts
  packages/common/src/hooks/useOwnedTokens.ts
  packages/common/src/store/ui/buy-sell/index.ts
  packages/common/src/store/ui/buy-sell/useGroupCoinPairs.ts
  packages/common/src/utils/coinUtils.ts
  packages/common/src/utils/decimal.ts
  packages/common/src/utils/index.ts
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SellScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/CoinCard.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
  packages/web/src/components/buy-sell-modal/ConvertTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/L

#12896 Fix coin blasts sending to all chats
  packages/discovery-provider/ddl/functions/chat_blast_audience.sql
Labels: size/M

#12870 Cursor rules file for Audius style guide
  .cursor/rules/audius-style-guide.mdc
Labels: size/M

#12900 Make swaps work for new artist coins
  packages/common/src/api/tan-query/jupiter/indirectSwapViaAudio.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
Labels: size/M

#12901 Use correct route on artist coin hover card
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
Labels: size/XS

#12827 Drop legacy wallet modal
  packages/common/src/store/pages/token-dashboard/selectors.ts
  packages/common/src/store/pages/token-dashboard/slice.ts
  packages/common/src/store/pages/token-dashboard/types.ts
  packages/harmony/src/foundations/color/primitive.css
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/social-proof/SocialProof.module.css
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/audio-page/AudioPage.tsx
  packages/web/src/pages/audio-page/WalletModal.module.css
  packages/web/src/pages/audio-page/WalletModal.tsx
  packages/web/src/pages/audio-page/components/ErrorBody.module.css
  packages/web/src/pages/audio-page/components/ErrorBody.tsx
  packages/web/src/pages/audio-page/components/MigrationModalBody.module.css
  packages/web/src/pages/audio-page/components/MigrationModalBody.tsx
  packages/web/src/pages/audio-page/components/SendInputBody.module.css
  packages/web/src/pages/audio-page/components/SendInputBody.tsx
  packages/web/src/pages/audio-page/components/SendInputConfirmation.module.css
  packages/web/src/pages/audio-page/components/SendInputConfirmation.tsx
  packages/web/src/pages/audio-page/components/SendInputSuccess.module.css
  packages/web/src/pages/audio-page/components/SendInputSuccess.tsx
  packages/web/src/pages/audio-page/components/SendingModalBody.module.css
  packages/web/src/pages/audio-page/components/SendingModalBody.tsx
  packages/web/src/store/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/XXL

#12888 Reduce coin calls in user-badges
  packages/common/src/adapters/user.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/models/User.ts
  packages/harmony/src/components/hover-card/HoverCard.tsx
  packages/harmony/src/components/hover-card/types.ts
  packages/sdk/src/sdk/api/generated/full/models/UserFullArtistCoinBadge.ts
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/hover-card/HoverCardBody.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/L

#12905 [PE-6825] Add coin batching and cleanup
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/batchers/getArtistCoinsBatcher.ts
  packages/common/src/api/tan-query/coins/useArtistCoin.ts
  packages/common/src/api/tan-query/coins/useArtistCoinByTicker.ts
  packages/common/src/api/tan-query/coins/useArtistCoinInsights.ts
  packages/common/src/api/tan-query/coins/useArtistCoinMembers.ts
  packages/common/src/api/tan-query/coins/useArtistCoins.ts
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/common/src/hooks/useFormattedTokenBalance.ts
  packages/common/src/hooks/useGatedContent.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/common/src/utils/coinMetrics.ts
  packages/mobile/src/components/core/BalanceSection.tsx
  packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceField.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensConfirmation.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensFailure.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensInput.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensSuccess.tsx
  packages/mobile/src/screens/buy-sell-screen/components/BuyScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SellScreen.tsx
  packages/mobile/src/screens/coin-details-screen/CoinDetailsScreen.tsx
  packages/mobile/src/screens/coin-details-screen/components/AssetInsightsOverflowMenu.tsx
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinInsightsCard.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/user-list-screen/CoinLeaderboardScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/CoinCard.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/ConvertTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/receive-tokens-modal/ReceiveTokensModal.tsx
  packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
  packages/web/src/components/send-tokens-modal/SendTokensFailure.tsx
  packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
  packages/web/src/components/send-tokens-modal/SendTokensModal.tsx
  packages/web/src/components/send-tokens-modal/SendTokensSuccess.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/pages/asset-detail-page/components/AssetLeaderboardCard.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/L

#12903 Artist coin row clickable
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/S

#12915 Update buy artist coin button to open buy sell modal on web
  packages/web/src/components/track/GatedConditionsPill.tsx
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/M

#12916 Filter $AUDIO from artist coins tables
  packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
  packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/S

#12918 small mobile lint fix for useArtistCoin hook
  packages/mobile/src/components/details-tile/DetailsTileGatedAccess.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/S

#12919 Fix bug in asset details navigation
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
Labels: size/S

#12912 [PE-6850] Redo launchpad first buy with audio instead of sol
  packages/common/src/api/tan-query/coins/useFirstBuyQuote.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/first_buy_quote.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/launch_coin.ts
  packages/sdk/src/sdk/services/Solana/SolanaRelay.ts
  packages/sdk/src/sdk/services/Solana/types.ts
  packages/web/src/hooks/useLaunchCoin.ts
  packages/web/src/hooks/useLaunchpadConfig.ts
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/utils.ts
  packages/web/src/pages/artist-coins-launchpad-page/validation.ts
Labels: size/XXL

#12907 [PE-6791, PE-6838] Launchpad QA and updates
  packages/harmony/src/components/pill/Pill.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ConnectedWalletHeader.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ImageUploadArea.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/WhyCreateCard.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/ReviewPage.tsx
Labels: size/L

#12910 [PE-6856] Add check to see if the coin has a discord before rendering
  packages/sdk/src/sdk/api/generated/default/models/Coin.ts
  packages/sdk/src/sdk/api/generated/default/models/UserCoin.ts
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
Labels: size/M

#12920 Invalidate token owner tracks on token swap
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/web/src/components/track/GatedConditionsPill.tsx
Labels: size/M

#12924 Don't highlight coin pages
  packages/web/src/components/nav/desktop/nav-items/ArtistCoinsNavItem.tsx
Labels: size/XS

#12925 [PE-6849] Launchpad Buy Audio Modal
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/common/src/api/tan-query/wallets/useExternalWalletBalance.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/messages/buySell.ts
  packages/common/src/store/ui/buy-sell/hooks/useSwapCalculations.ts
  packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
  packages/common/src/store/ui/buy-sell/swapFormSchema.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/common/src/store/ui/buy-sell/utils/tokenLimits.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/launch_coin.ts
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/SwapBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/TransactionSuccessScreen.tsx
  packages/web/src/components/buy-sell-modal/USDCBalanceSection.tsx
  packages/web/src/hooks/useExternalWalletSwap.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/WalletSetupCard.tsx
  packages/web/src/pages/artist-coins-launchpad-page/constants.ts
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/validation.ts
  packages/web/src/pages/asset-detail-page/components/ExternalWallets.tsx
Labels: size/XL

#12930 [PE-6870] Add artist coin details modal
  packages/common/src/messages/coinDetailsMessages.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
  packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
Labels: size/L

#12933 Add artist coin badge to profile picture
  packages/harmony/src/components/artwork/Artwork.tsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
Labels: size/M

#12935 Fix profile picture lint
  packages/web/src/components/profile-picture/ProfilePicture.jsx
Labels: size/XS

#12932 [PE-6854] Use bonding curve price before graduation
  packages/common/src/utils/coinMetrics.ts
Labels: size/XS

#12938 Fix token data fixed decimal display decimals bug
  packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
Labels: size/XS

#12942 Upstream args to solana-relay
  packages/discovery-provider/nginx_conf/nginx_container.conf
Labels: size/XS

#12939 [PE-6872] Make the balance refresh + clean up modal
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
Labels: size/S

#12945 sync ddl from api
  packages/discovery-provider/ddl/functions/chat_blast_audience.sql
  packages/discovery-provider/ddl/migrations/0163_remove_pool.sql
Labels: size/S

#12943 [PE-6873] Add file validation to launchpad
  packages/web/src/pages/artist-coins-launchpad-page/pages/SetupPage.tsx
  packages/web/src/utils/imageProcessingUtil.ts
Labels: size/M

#12974 [PE-6908] Show buy coins for own profile
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
Labels: size/S

#12975 [PE-6933] Border for buy buttons section on profile
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/XS

#12980 Update mobile web pages and overflow menus for asset details page
  packages/common/src/utils/route.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/asset-detail-page/components/ExternalWallets.tsx
  packages/web/src/pages/asset-detail-page/components/mobile/ArtistCoinDetailsPage.tsx
  packages/web/src/utils/clipboardUtil.ts
Labels: size/L

#12966 [PE-6890] Improve nested modal styling
  packages/harmony/src/components/modal/Modal.module.css
Labels: size/XS

#12970 [PE-6894] Drop help CTA during coin purchase
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
Labels: size/XS

#12971 [PE-6935] Hide launch token banner if user has coin
  packages/web/src/pages/artist-coins-launchpad-page/pages/SplashPage.tsx
Labels: size/S

#12972 [PE-6904] External Wallets section
  packages/common/src/api/tan-query/wallets/useConnectedWallets.ts
  packages/common/src/messages/walletMessages.ts
  packages/common/src/utils/wallet.ts
  packages/harmony/src/components/text/Text.tsx
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/screens/wallet-screen/WalletScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/LinkedWallets.tsx
  packages/mobile/src/store/drawers/slice.ts
  packages/web/src/pages/asset-detail-page/components/ExternalWallets.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
  packages/web/src/pages/wallet-page/components/LinkedWallets.tsx
Labels: size/XL

#12984 Improve ATA check
  packages/common/src/services/audius-backend/solana.ts
Labels: size/XS

#12985 [PE-6878] Remove dollar sign from /coins/:ticker routes
  packages/common/src/utils/formatUtil.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/asset-detail-page/components/mobile/ArtistCoinDetailsPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/L

#12987 [PE-6929] Update buy coin card to pass the coin ticker
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/XS

#12997 s/Built-In/Built-In Wallet
  packages/common/src/messages/coinDetailsMessages.ts
Labels: size/XS

#12988 [PE-6931] Fix coin name
  packages/common/src/adapters/coin.ts
  packages/common/src/api/tan-query/coins/tokenUtils.ts
  packages/web/src/components/buy-sell-modal/DropdownSection.tsx
Labels: size/L

#12989 [PE-6922] Shorten SPL address if necessary
  packages/mobile/src/components/core/AddressTile.tsx
  packages/web/src/components/address-tile/AddressTile.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
Labels: size/S

#12998 Borders for artist coin explore page
  packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/S

#13002 Fix broken nginx code
  packages/discovery-provider/nginx_conf/nginx_container.conf
Labels: size/S

#12996 [PE-6921] Polish up some launchpad form error states
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsSubmitRow.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/ReviewPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/SetupPage.tsx
Labels: size/M

#13018 [PE-6942] Add copy address button to asset page
  packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
Labels: size/M

#13016 Add market cap to insights section
  packages/common/src/messages/coinDetailsMessages.ts
  packages/common/src/utils/coinMetrics.ts
Labels: size/XS

#13015 Add top border to last element in "Your Coins" on odd number of coins
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/XS

#13008 [PE-6607] Skip usdc transfer email for internal tranfers
  packages/common/src/api/tan-query/jupiter/utils.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/discovery-provider/plugins/notifications/package-lock.json
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcTransfer.test.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/.gitignore
  packages/discovery-provider/src/models/users/usdc_transactions_history.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#13017 [PE-6950], [PE-6949] Fix mobile balance formatting
  packages/common/src/hooks/useFormattedTokenBalance.ts
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
Labels: size/S

#13027 [PE-6961] Artist coins table sizing
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/S

#13029 [PE-6963] Artist coin table text body variant subscripts
  packages/harmony/src/components/text/Text.tsx
Labels: size/M

#13030 [PE-6912] Update coin gated dog ears to respect theme
  packages/harmony/src/icons/SVGDefs.tsx
  packages/mobile/src/assets/images/coinGateDogEarRectangle.svg
  packages/mobile/src/components/core/CoinGradientDogEarSvg.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/web/src/assets/img/dogEarRectangle.svg
  packages/web/src/components/dog-ear/DogEar.tsx
Labels: size/L

#13036 [PE-6974] Fix infinite spinning on artist coin details
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
Labels: size/XS

#13035 [PE-6964] Calculate 24h vol change manually
  packages/common/src/utils/coinMetrics.ts
Labels: size/XS

#13033 Fix swap due to invalid optimistic update
  packages/common/src/adapters/coin.ts
  packages/common/src/api/tan-query/coins/useUserCoins.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
Labels: size/M

#13032 [PE-6913] Small launchpad fixes
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/constants.ts
Labels: size/XS

#13041 Update coin gated label to respect theme on web and mobile
  packages/harmony/src/assets/icons/CoinGatedLabel.svg
  packages/harmony/src/icons/SVGDefs.tsx
  packages/mobile/src/components/core/AccessTypeLabel.tsx
  packages/mobile/src/components/core/CoinGatedLabelSvg.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
Labels: size/L

#13034 [PE-6866] Artist coin blast UI on sender side
  packages/common/src/store/pages/chat/sagas.ts
  packages/common/src/store/pages/chat/slice.ts
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/web/src/pages/chat-page/components/ChatComposer.tsx
Labels: size/S

#13037 [PE-6095][PE-6909][PE-6913][PE-6975] Fix misc layout issues
  packages/web/src/components/page/Page.module.css
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/M

#13046 [PE-6978] Fix scroll top issue
  packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Labels: size/XS

#13045 [PE-7001] Include staked AUDIO in the coin hover, exclude connected wallets from send modal
  packages/common/src/api/tan-query/wallets/useSendTokens.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
  packages/web/src/components/send-tokens-modal/SendTokensFailure.tsx
  packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
  packages/web/src/components/send-tokens-modal/SendTokensSuccess.tsx
Labels: size/M

#13047 [PE-6988] Update mobile buy coins button to open the swap modal
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
Labels: size/M

#13048 [PE-6747] Update retry logic in useSwapTokens hook
  packages/common/src/api/tan-query/jupiter/directSwap.ts
  packages/common/src/api/tan-query/jupiter/executors.ts
  packages/common/src/api/tan-query/jupiter/indirectSwapViaAudio.ts
  packages/common/src/api/tan-query/jupiter/orchestrator.ts
  packages/common/src/api/tan-query/jupiter/retryPolicy.ts
  packages/common/src/api/tan-query/jupiter/types.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
Labels: size/XXL

#13049 [PE-6984] Hide artist coin badge on coin explore
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/components/user-link/UserLink.tsx
  packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/M

#13052 [PE-6986] Mobile userbadges pressable
  packages/mobile/src/components/user-link/UserLink.tsx
Labels: size/XS

#13054 [PE-6976 PE-6980] Share coin to X
  packages/common/src/adapters/coin.ts
  packages/common/src/api/tan-query/coins/useArtistCoinByTicker.ts
  packages/common/src/messages/coinDetailsMessages.ts
  packages/mobile/src/screens/coin-details-screen/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/components/CoinSuccessModal.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
Labels: size/L

#13057 [PE-7003] Add discover artist coins CTA to your coins section
  packages/common/src/messages/buySell.ts
  packages/common/src/messages/walletMessages.ts
  packages/mobile/src/screens/wallet-screen/components/LinkedWallets.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/L

#13038 [PROTO-2029] Unified validators page
  packages/protocol-dashboard/src/App.tsx
  packages/protocol-dashboard/src/components/NodeTable/NodeTable.tsx
  packages/protocol-dashboard/src/containers/Validators/Validators.module.css
  packages/protocol-dashboard/src/containers/Validators/Validators.tsx
  packages/protocol-dashboard/src/containers/Validators/index.tsx
  packages/protocol-dashboard/src/utils/routes.ts
Labels: size/M

#13060 [PE-7005] Fix send tokens confirmation balance
  packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
  packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
Labels: size/S

#13062 Fix build params for embed deploy
  .circleci/src/commands/@embed-commands.yml
  .circleci/src/jobs/@embed-jobs.yml
Labels: size/XS

#13053 [PROTO-2031] Consolildate node types on dashboard user page
  packages/protocol-dashboard/src/components/InfoTooltip/InfoTooltips.tsx
  packages/protocol-dashboard/src/components/ManageService/ManageService.tsx
  packages/protocol-dashboard/src/containers/User/User.tsx
Labels: size/M

#13064 Remove information icons that don't have tooltip assigned
  packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
  packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
Labels: size/M

#13071 [QA-2285] Update sign in flow to handle deactivated accounts
  packages/common/src/models/Analytics.ts
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/S

#13074 [PE-7014] Fix dust bug
  packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
  packages/common/src/store/ui/buy-sell/types/swap.types.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
Labels: size/S
