Repository AudiusProject/apps, pull requests merged in 2025-10, with the labels that each got.

#13075 [QA-2352] Increase size of dropdown to avoid wrapping
  packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Labels: size/XS

#13083 allow /indexing routes to hit DN
  packages/discovery-provider/nginx_conf/nginx_container.conf
Labels: size/XS

#13056 [PE-6971] Swipe back on artist coin explore screen
  packages/mobile/src/components/core/Screen/Screen.tsx
Labels: size/XS

#13058 [PE-6989] Add buy artist coin to mobile profile page
  packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
  packages/mobile/src/screens/profile-screen/BuyArtistCoinButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/BuyArtistCoinButton.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
Labels: size/L

#13082 [PE-6991] Update profile page buy artist coin card
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/S

#13085 Remove TX skip consensus behavior
  packages/discovery-provider/integration_tests/queries/test_set_indexing_error.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_index_skip_tx.py
  packages/discovery-provider/nginx_conf/nginx_container.conf
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/queries/confirm_indexing_transaction_error.py
  packages/discovery-provider/src/queries/get_skipped_transactions.py
  packages/discovery-provider/src/queries/skipped_transactions.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Labels: size/L

#13087 Fix e2e tests 404ing on relay
  dev-tools/compose/nginx_ingress.conf
Labels: size/M

#13070 trim prefix for comms pubkey recover
  comms/discovery/pubkeystore/recover_core.go
Labels: size/XS

#13090 Fix misc CI issues
  packages/common/src/hooks/useAccessAndRemixSettings.test.ts
  packages/create-audius-app/examples/react-hono/package.json
  packages/create-audius-app/examples/react/package.json
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/sdk/src/sdk/config/development.ts
  packages/sdk/src/sdk/config/production.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/web/src/pages/profile-page/ProfilePage.test.tsx
Labels: size/M

#13093 [PE-6851] Add link for artist coin help in insufficient balance modal
  packages/common/src/utils/route.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
Labels: size/S

#13095 [PE-6848] Update YourCoins buy button to show open app drawer on mobile web
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/asset-detail-page/components/OpenAppDrawer.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
Labels: size/L

#13102 Add feature flag to artist-coins nav item
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/ArtistCoinsNavItem.tsx
Labels: size/S

#13100 Misc artist coin QA finds
  packages/common/src/api/tan-query/coins/useArtistCoinByTicker.ts
  packages/common/src/messages/edit.ts
  packages/common/src/messages/launchpadMessages.ts
  packages/common/src/messages/walletMessages.ts
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/screens/coin-details-screen/CoinDetailsScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/CoinCard.tsx
  packages/web/src/components/CoinSuccessModal.tsx
  packages/web/src/components/address-tile/AddressTile.tsx
  packages/web/src/hooks/useClaimFees.ts
  packages/web/src/hooks/useLaunchCoin.ts
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
  packages/web/src/pages/artist-coins-launchpad-page/constants.ts
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/pay-and-earn-page/components/CoinCard.tsx
Labels: size/L

#13105 Fix app signing & create-audius-app
  .changeset/witty-wasps-search.md
  packages/create-audius-app/examples/react-hono/src/client/App.tsx
  packages/create-audius-app/examples/react-hono/src/index.tsx
  packages/create-audius-app/examples/react-hono/vite.config.ts
  packages/create-audius-app/examples/react/src/App.tsx
  packages/create-audius-app/examples/react/src/hooks/useSdk.ts
  packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
  packages/sdk/src/sdk/middleware/addAppInfoMiddleware.ts
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.ts
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManager.test.ts
Labels: size/L

#13107 [PE-7056] Misc fixes
  packages/web/src/hooks/useLaunchCoin.ts
  packages/web/src/pages/artist-coins-launchpad-page/constants.ts
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
Labels: size/S

#13109 Fix double $$ on $AUDIO
  packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/CoinCard.tsx
Labels: size/XS

#13113 [PE-7058] Fix signup skip flow and update UI
  packages/common/src/messages/sign-on/pages.ts
  packages/mobile/src/screens/sign-on-screen/components/SkipButton.tsx
  packages/mobile/src/screens/sign-on-screen/screens/AccountLoadingScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
  packages/web/src/pages/sign-up-page/components/SkipButton.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/sign-up-page/pages/MobileAppCtaPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
  packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/L

#13110 [PE-7022] Add checkbox to agree to artist-coin terms
  packages/common/src/models/Launchpad.ts
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/AgreeToTerms.tsx
  packages/web/src/pages/artist-coins-launchpad-page/pages/ReviewPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/validation.ts
Labels: size/M

#13117 fix comms base endpoint
  .changeset/clean-hotels-end.md
  packages/sdk/src/sdk/sdk.ts
Labels: size/XS

#13079 Use CoinGecko for AUDIO stats
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useCoinGeckoCoin.ts
  packages/common/src/utils/coinMetrics.ts
  packages/common/src/utils/route.ts
  packages/mobile/src/screens/coin-details-screen/components/CoinInsightsCard.tsx
  packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/pages/asset-detail-page/components/mobile/ArtistCoinDetailsPage.tsx
  packages/web/src/pages/sign-up-page/components/layout.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/L

#13099 [PE-7021] Mobile artist coin edit details
  packages/mobile/src/components/core/FixedFooter.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/coin-details-screen/CoinDetailsScreen.tsx
  packages/mobile/src/screens/coin-details-screen/EditCoinDetailsScreen.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
  packages/mobile/src/screens/coin-details-screen/index.ts
Labels: size/L

#13125 [PE-7060] Remove dollar sign on fee claim amount
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
Labels: size/S

#13128 [PE-7072] Add artist coin terms link
  packages/common/src/utils/route.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/AgreeToTerms.tsx
Labels: size/XS

#13129 Misc artist coins QA
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/claim_fees.ts
  packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
Labels: size/M

#13131 [PE-7090] Don't allow empty profile image
  packages/common/src/schemas/sign-on/finishProfileSchema.ts
  packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Labels: size/M

#13137 [PE-7083] Add $ to ticker in mobile chat blast
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
  packages/web/src/pages/artist-coins-launchpad-page/validation.ts
Labels: size/XS

#13104 [PE-7050] Add dollar sign to ticker
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
  packages/mobile/src/screens/user-list-screen/CoinLeaderboardScreen.tsx
Labels: size/M

#13135 [PE-7084] Add filter to token dropdown
  packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
  packages/web/src/components/buy-sell-modal/components/OutputTokenSection.tsx
  packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Labels: size/S

#13138 Launchpad buy audio flow fix
  packages/web/src/hooks/useExternalWalletSwap.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
Labels: size/L

#13140 [PE-7100] Highlight artist coin left nav on coins
  packages/web/src/components/nav/desktop/nav-items/ArtistCoinsNavItem.tsx
Labels: size/XS

#13145 [PE-7103] Invalidate audio after claim
  packages/web/src/hooks/useClaimFees.ts
Labels: size/XS

#13146 [PE-7097] Hide balance/wallet-related coin assets details for anon users
  packages/web/src/pages/asset-detail-page/AssetDetailContent.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailTabs.tsx
Labels: size/M

#13152 [PE-7078] Prevent user from buying too much $AUDIO
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
Labels: size/M

#13153 [PE-7105] Fix help icon not clickable on CTA
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
Labels: size/S

#13159 [PE-7104] Fix optimistic token gate unlock
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
Labels: size/S

#13151 [PE-6843] Mobile artist coin explore pagination
  packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
Labels: size/L

#13149 [PE-6779] Use sol_keypairs table to populate artist coin mints
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/getKeypair.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/launch_coin.ts
  packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
Labels: size/XXL

#13160 [PE-6947] Fix buy/sell/swap optimistic updates
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/mobile/src/screens/wallet-screen/components/AudioCoinCard.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
Labels: size/L

#13161 [PE-7113] Add acceptable use to policy checkbox
  packages/common/src/utils/route.ts
  packages/web/src/pages/artist-coins-launchpad-page/components/AgreeToTerms.tsx
Labels: size/S

#13143 Reapply "[PE-7084] Add filter to token dropdown (#13135)" (#13141)
  packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
  packages/web/src/components/buy-sell-modal/components/OutputTokenSection.tsx
  packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Labels: size/S

#13162 Fix route conflict
  packages/common/src/utils/route.ts
Labels: size/XS

#13165 Enable ToS banner
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/XS

#13166 Fix lint
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/XS

#13150 [PE-7093] Fix claiming provider issues
  packages/common/src/messages/coinDetailsMessages.ts
  packages/common/src/utils/decimal.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinDynamicBondingCurve.ts
  packages/web/src/hooks/useClaimFees.ts
  packages/web/src/hooks/useConnectAndAssociateWallets.ts
  packages/web/src/hooks/useConnectWallets.ts
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
Labels: size/L

#13169 [PE-7114] Use buy/sell even if not enough balance
  packages/common/src/store/ui/modals/add-cash-modal/index.ts
  packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellModalScreen.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
Labels: size/M

#13168 Fix layout in frosted component
  packages/web/src/components/frosted/Frosted.tsx
Labels: size/XS

#13170 [PE-7038] Remove confirm details title
  packages/mobile/src/screens/buy-sell-screen/ConfirmSwapScreen.tsx
Labels: size/XS

#13171 [PE-7115] Remove $ from AUDIO_TICKER
  packages/common/src/store/ui/buy-sell/constants.ts
  packages/common/src/utils/route.ts
  packages/mobile/src/screens/coin-details-screen/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/components/CoinSuccessModal.tsx
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
  packages/web/src/pages/edit-coin-details-page/EditCoinDetailsPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Labels: size/L

#13172 Various UI fixes
  packages/common/src/api/tan-query/coins/useUserCreatedCoins.ts
  packages/common/src/messages/buySell.ts
  packages/mobile/src/components/artist-coin-details-drawer/ArtistCoinDetailsDrawer.tsx
  packages/mobile/src/components/buy-sell/CryptoBalanceSection.tsx
  packages/mobile/src/components/core/BalanceSection.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensConfirmation.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensFailure.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensInput.tsx
  packages/mobile/src/components/send-tokens-drawer/components/SendTokensSuccess.tsx
  packages/mobile/src/screens/buy-sell-screen/components/PoweredByJupiter.tsx
  packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
  packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
  packages/web/src/components/send-tokens-modal/SendTokensFailure.tsx
  packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
  packages/web/src/components/send-tokens-modal/SendTokensSuccess.tsx
  packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/edit-coin-details-page/EditCoinDetailsPage.tsx
Labels: size/M

#13173 [PE-7118] Caret in mobile artist coin discover
  packages/mobile/src/screens/wallet-screen/components/AudioCoinCard.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
Labels: size/S

#13174 Add filter input to token dropdown
  packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Labels: size/L

#13175 [PE-7011] Add help link
  packages/common/src/utils/route.ts
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/receive-tokens-drawer/ReceiveTokensDrawer.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/receive-tokens-modal/ReceiveTokensModal.tsx
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/WalletSetupCard.tsx
Labels: size/S

#13180 [PE-7116|PE-7117] Refactor explore pagination & add mobile token ticker filter
  packages/common/src/api/tan-query/coins/useArtistCoins.ts
  packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
  packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
Labels: size/L

#13182 [PE-7043][PE-7096] Some refactoring for buy/sell keyboard avoidance
  packages/mobile/src/components/core/KeyboardAvoidingView.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
Labels: size/L

#13187 [PE-7120] Update available to trade tooltip copy
  packages/common/src/messages/buySell.ts
  packages/mobile/src/components/buy-sell/InputTokenSection.tsx
  packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
  packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
Labels: size/S

#13189 Ellipsize ticker on mobile coin screen
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
Labels: size/S

#13191 [PE-7130] Fix mobile audio details
  packages/mobile/src/components/artist-coin-details-drawer/ArtistCoinDetailsDrawer.tsx
  packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
Labels: size/M

#13192 [PE-7131] Fix wallet connect
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Labels: size/XS

#13188 [PE-7026] Re-enable dismissing of toasts on Android
  packages/mobile/src/components/toasts/Toast.tsx
Labels: size/XS

#13194 Add validator service type to ganache dev container
  eth-contracts/Dockerfile
  eth-contracts/scripts/setup-dev.js
Labels: size/S

#13198 Artist coin chat blast fixes
  packages/common/src/hooks/chats/useFirstAvailableBlastAudience.ts
  packages/common/src/hooks/useArtistCoinMessageHeader.ts
  packages/mobile/src/screens/chat-screen/ArtistCoinHeader.tsx
  packages/web/src/components/buy-sell-modal/TokenIcon.tsx
  packages/web/src/pages/chat-page/components/ArtistCoinHeader.tsx
Labels: size/M

#13154 [PE-7110] Fix PlainButton link wrapping
  packages/harmony/src/components/button/PlainButton/PlainButton.tsx
  packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
  packages/web/src/pages/track-page/components/shared/RemixTab.tsx
Labels: size/M

#13200 [PE-7023] Fix saga phone deploy
  .circleci/src/commands/@mobile-commands.yml
  packages/mobile/dapp-store/.asset-manifest.json
  packages/mobile/dapp-store/README.md
  packages/mobile/dapp-store/config.yaml
  packages/mobile/dapp-store/media/banner_graphic.png
  packages/mobile/dapp-store/media/feature_graphic.png
  packages/mobile/dapp-store/package.json
  packages/mobile/dapp-store/pnpm-lock.yaml
Labels: size/S

#13205 Fix artist coin details title
  packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
  packages/web/src/components/page/Page.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
Labels: size/M

#13207 Solana Relay: Don't confirm error transactions
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
Labels: size/XS
