Repository AudiusProject/apps, pull requests merged in 2025-04, with the labels that each got.

#11707 Fix sdk init
  .changeset/strange-taxis-work.md
  packages/sdk/src/sdk/sdk.ts
Labels: size/XS

#11709 Update 🙌 emoji
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tastemaker.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/tastemaker.test.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
Labels: size/M

#11705 Add cosign cooldown reward email
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/rewardInCooldown.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts
Labels: size/S

#11710 [PE-5840] Add basic setup for tan-query hooks for events
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/batchers/getEventsBatcher.ts
  packages/common/src/api/tan-query/events/index.ts
  packages/common/src/api/tan-query/events/useAllEvents.ts
  packages/common/src/api/tan-query/events/useCreateEvent.ts
  packages/common/src/api/tan-query/events/useDeleteEvent.ts
  packages/common/src/api/tan-query/events/useEvent.ts
  packages/common/src/api/tan-query/events/useEvents.ts
  packages/common/src/api/tan-query/events/useUpdateEvent.ts
  packages/common/src/api/tan-query/events/utils.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/models/ErrorReporting.ts
Labels: size/L

#11711 Fix notification error boundary due to missing entity
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
Labels: size/XS

#11706 [PE-5882] Web submit to remix contest flow
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadModalScreen.tsx
  packages/mobile/src/screens/upload-screen/types/ParamList.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/hooks/useNavigateToPage.ts
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
Labels: size/L

#11718 add types to protobuf for mypy
  packages/discovery-provider/requirements.txt
Labels: size/XS

#11716 [API-13] Fix celery getting stuck
  packages/discovery-provider/scripts/start.sh
Labels: size/XS

#11714 [QA-2030] Fix email and mentions in DMs
  packages/common/src/utils/email.ts
  packages/common/src/utils/handle.ts
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/M

#11720 Remove block-gating for tastemaker challenge
  packages/discovery-provider/src/challenges/tastemaker_challenge.py
  packages/discovery-provider/src/queries/get_health.py
Labels: size/M

#11721 use openresty compatible version for alpine:18
  packages/discovery-provider/Dockerfile.prod
Labels: size/XS

#11723 Fix local dev use http not https
  packages/sdk/src/sdk/config/development.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
Labels: size/XS

#11722 Fix user card bug
  packages/mobile/src/components/user-list/UserCard.tsx
  packages/web/src/components/user-card/UserCard.tsx
Labels: size/XS

#11727 [PE-5899] Add new cash wallet UI
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
Labels: size/L

#11730 Disable lua scripts in nginx_container.conf
  packages/discovery-provider/nginx_conf/nginx_container.conf
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/utils/helpers.py
  packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
Labels: size/L

#11731 Fix artist pick on profile page
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/L

#11732 Skip busy work in plays indexer if not a play tx
  packages/discovery-provider/src/tasks/index_core_plays.py
Labels: size/XS

#11733 [QA-2016] Fix play button getting out of sync
  packages/web/src/components/play-bar/PlayButton.tsx
Labels: size/S

#11736 Fix user card bug
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
Labels: size/XS

#11726 Updates to run-always cursor rule
  .cursor/rules/run-always.mdc
Labels: size/M

#11713 [PE-5881] Reduce data stored in lineup caches
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/usePremiumTracks.ts
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/common/src/api/tan-query/useRemixes.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/tan-query/useTrendingPlaylists.ts
  packages/common/src/api/tan-query/useTrendingUnderground.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/common/src/models/ErrorReporting.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
Labels: size/L

#11738 [PE-5900] Add audio wallet banner
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/M

#11737 [API-13] Only update scores when they need to be
  packages/discovery-provider/src/tasks/update_aggregates.py
Labels: size/XS

#11740 Fix search due to my bad pythoning creating invalid ES queries
  packages/discovery-provider/src/queries/search_es.py
Labels: size/XS

#11739 Fix broken listen streak challenge state
  packages/discovery-provider/ddl/migrations/0129_update_challenge_listen_streak.sql
Labels: size/M

#11734 [QA-2034] Fix notification loading state
  packages/common/src/api/tan-query/useNotifications.ts
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/S

#11745 Fix mobile tile layout bug
  packages/web/src/components/lineup/TanQueryLineup.tsx
Labels: size/S

#11725 [PE-5891] Get event by entity ID endpoint
  .changeset/quick-stingrays-march.md
  packages/discovery-provider/src/api/v1/events.py
  packages/discovery-provider/src/queries/get_events.py
  packages/sdk/src/sdk/api/generated/default/apis/EventsApi.ts
Labels: size/L

#11742 Add index and use indexes better in block confirmation
  packages/discovery-provider/ddl/migrations/0129_core_blockhash_index.sql
  packages/discovery-provider/src/queries/get_block_confirmation.py
  packages/discovery-provider/src/queries/get_block_confirmation_unit_test.py
Labels: size/M

#11555 Improve trending rewards plugin
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/sdk.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts
Labels: size/S

#11743 Show comment-badges in preview
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentBlock.tsx
Labels: size/XS

#11750 Fix follow artist gate ui
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/GiantTrackTile.module.css
Labels: size/M

#11752 [QA-2038] Fix mobile social link text truncation
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
Labels: size/M

#11749 Revert "[PE-5863] Migrate Follow/Unfollow user to tan-query (#11316)
  packages/common/src/api/index.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/social/users/actions.ts
  packages/common/src/store/tipping/slice.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/web/src/common/store/social/users/errorSagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/follow-button/FollowButton.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/UnfollowConfirmationModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/components/UnfollowConfirmationModal.tsx
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/TrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/XL

#11729 [PE-5897] Mobile stems download experience
  packages/common/src/api/tan-query/useDownloadTrackStems.ts
  packages/common/src/context/appContext.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/models/ErrorReporting.ts
  packages/common/src/services/track-download/TrackDownload.ts
  packages/mobile/src/app/AppContextProvider.tsx
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/core/DrawerHeader.tsx
  packages/mobile/src/components/core/HarmonyModalHeader.tsx
  packages/mobile/src/components/download-track-archive-drawer/DownloadTrackArchiveDrawer.tsx
  packages/mobile/src/components/download-track-archive-drawer/index.ts
  packages/mobile/src/components/drawers/OfflineListeningDrawer.tsx
  packages/mobile/src/components/manager-mode-drawer/ManagerModeDrawer.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/services/sdk/audius-sdk.ts
  packages/mobile/src/services/track-download.ts
  packages/web/src/app/AppContextProvider.tsx
  packages/web/src/components/download-track-archive-modal/DownloadTrackArchiveModal.tsx
  packages/web/src/services/track-download.ts
Labels: size/XL

#11746 [PE-5887] Add host contest modal and add ability to start remix contests
  packages/common/src/store/ui/modals/host-remix-contest-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/discovery-provider/src/tasks/entity_manager/entities/event.py
  packages/harmony/src/components/select/Select/Select.tsx
  packages/web/src/components/edit/fields/DatePickerField.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L

#11754 Update archiver endpoint to use load-balanced API
  packages/mobile/src/services/env/env.prod.ts
  packages/mobile/src/services/env/env.stage.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
Labels: size/XS

#11755 Use : instead of _ in challenge specifiers
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_challenge_base.py
Labels: size/XS

#11758 Revert "[QA-2026] Migration to change challenge specifiers from _ to …
  packages/discovery-provider/ddl/migrations/0130_update_challenge_specifier_format.sql
Labels: size/S

#11728 Add chat block to AAO
  packages/discovery-provider/ddl/functions/shadowban_users.sql
  packages/discovery-provider/ddl/functions/user_scores.sql
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
  packages/discovery-provider/src/tasks/update_aggregates.py
Labels: size/L

#11760 Fix shadowban push notif using pg function
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
Labels: size/XS

#11751 Show cosign on feed and search
  packages/discovery-provider/src/utils/elasticdsl.py
Labels: size/S

#11753 [PE-5903] Feed & trending tan query-fied
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useFeed.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/types.ts
Labels: size/XL

#11744 Am tq docs
  packages/common/src/api/tan-query/README.md
Labels: size/L

#11761 Penalize audius impersonators
  packages/discovery-provider/ddl/functions/user_scores.sql
Labels: size/S

#11763 Revert "Penalize audius impersonators (#11761)"
  packages/discovery-provider/ddl/functions/user_scores.sql
Labels: size/S

#11765 Hotfix tracks/reposts infinite load on mobile
  packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
Labels: size/M

#11735 fix date math for clm report
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
Labels: size/S

#11764 Drop user_score function before replacing
  packages/discovery-provider/ddl/functions/user_scores.sql
Labels: size/S

#11747 [PE-5902] Add transaction history page
  packages/common/src/utils/route.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/pages/transaction-history-page/TransactionHistoryPage.tsx
  packages/web/src/pages/transaction-history-page/desktop/TransactionHistoryPage.tsx
  packages/web/src/pages/transaction-history-page/mobile/TransactionHistoryPage.tsx
  packages/web/src/pages/transaction-history-page/types.ts
Labels: size/L

#11767 [QA-2041] Fix notification panel closing
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/XS

#11766 [PE-5888] Add host contest drawer for mobile
  packages/common/src/store/ui/mobile-overflow-menu/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#11768 [PE-5919] Migration to change challenge specifiers from _ to :
  packages/discovery-provider/ddl/migrations/0130_update_challenge_specifier_format.sql
Labels: size/M

#11770 Update anti abuse UI to include impersonator
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/M

#11772 [QA-2043] Fix sharing uploaded track to DM
  packages/web/src/pages/upload-page/components/ShareBanner.tsx
Labels: size/XS

#11773 Convert remixes lineup to tq
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useRemixes.ts
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/src/common/store/pages/remixes-page/lineups/tracks/sagas.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/remixes-page/components/desktop/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/RemixesPage.tsx
Labels: size/L

#11776 [PE-5893] Group + count like stems during upload
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
Labels: size/M

#11779 Update mobile versions to 148
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#11781 [QA-2045] Fix notification entity prefetch
  packages/common/src/api/tan-query/useNotifications.ts
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
  packages/web/src/components/notification/NotificationPage.tsx
Labels: size/S

#11757 Remove lua entirely from nginx
  packages/discovery-provider/Dockerfile.nginx
  packages/discovery-provider/Dockerfile.prod
  packages/discovery-provider/nginx_conf/config.lua
  packages/discovery-provider/nginx_conf/log_json.lua
  packages/discovery-provider/nginx_conf/main.lua
  packages/discovery-provider/nginx_conf/plugins.lua
  packages/discovery-provider/nginx_conf/port.lua
  packages/discovery-provider/nginx_conf/utils.lua
Labels: size/XL

#11785 Make playlist query deterministic wrt ordering to fix test.
  packages/discovery-provider/src/queries/get_user_playlist_update.py
Labels: size/XS

#11786 Enable cosign reward
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/XS

#11784 [QA-2039] Fix audio balance display
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/S

#11780 [PE-5728] Improve android performance with app lifecycle hooks
  packages/common/src/models/Analytics.ts
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.kt
  packages/mobile/src/app/App.tsx
  packages/mobile/src/hooks/useAndroidAppLifecycleManager.ts
  packages/mobile/src/hooks/useAppState.ts
Labels: size/L

#11782 Fix issue where notification button doesn't close panel
  packages/web/src/components/notification/NotificationPanel.tsx
Labels: size/XS

#11787 [PE-5884] Add new Buy/Sell modal UI
  packages/common/src/messages/buySell.ts
  packages/common/src/messages/index.ts
  packages/common/src/store/ui/modals/buy-sell-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/constants.ts
  packages/web/src/components/buy-sell-modal/index.ts
  packages/web/src/components/buy-sell-modal/types.ts
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/L

#11529 [C-5813] Improve reply performance
  packages/discovery-provider/integration_tests/queries/test_get_track_comments.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/comments.py
  packages/discovery-provider/src/queries/comments/__init__.py
  packages/discovery-provider/src/queries/comments/replies.py
  packages/discovery-provider/src/queries/comments/track_comments.py
  packages/discovery-provider/src/queries/comments/utils.py
Labels: size/XL

#11789 Show (1) counts for stem categories in upload
  packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
Labels: size/XS

#11790 [PE-5928] Event modal quality of life fixes
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/M

#11788 Fix lineup empty state
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/feed-page/components/FollowUsers.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
Labels: size/S

#11792 Fix artist pick divider issue
  packages/web/src/components/lineup/TanQueryLineup.tsx
Labels: size/S

#11793 [QA-2047] Fix profile left nav tile shadow
  packages/web/src/components/notification/Notification/components/ProfilePicture.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
Labels: size/S

#11791 [QA-2050] Fix gated access UI
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/XS

#11795 [QA-2056] Fix message blast CTA showing on user list modals erroneously
  packages/mobile/src/screens/chat-screen/ChatBlastWithAudienceCTA.tsx
  packages/web/src/pages/chat-page/components/ChatBlastWithAudienceCTA.tsx
Labels: size/M

#11771 [PE-5917] Increase max description length to 2500, show UI toggle
  .changeset/curly-laws-kiss.md
  packages/common/src/api/tan-query/events/useEventsByEntityId.ts
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/mobile/src/screens/edit-track-screen/fields/DescriptionField.tsx
  packages/mobile/src/screens/track-screen/TrackDescription.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/sdk/src/sdk/api/tracks/constants.ts
  packages/sdk/src/sdk/api/tracks/types.ts
  packages/sdk/src/sdk/index.ts
  packages/web/src/components/edit/fields/TrackMetadataFields.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/L

#11796 [QA-2052] Format number commas on claim all rewards
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
  packages/web/src/components/rewards/modals/ClaimAllRewardsModal.tsx
Labels: size/S

#11801 Randomly use rendezvous nodes
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/query_helpers.py
Labels: size/M

#11800 [PE-5941] Prefetch supporters on comments page
  packages/common/src/context/comments/commentsContext.tsx
  packages/mobile/src/components/comments/CommentBadge.tsx
  packages/web/src/components/comments/CommentBadge.tsx
Labels: size/M

#11794 [PE-5936] Add mobile for pinned comment
  packages/mobile/src/components/challenge-rewards-drawer/PinnedCommentChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/challengeContentRegistry.ts
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
Labels: size/L

#11804 [PE-5937] Make pinned comment challenge repeatable
  packages/discovery-provider/integration_tests/challenges/test_pinned_comment_challenge.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/mobile/src/components/challenge-rewards-drawer/PinnedCommentChallengeContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/PinnedCommentChallengeModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/challengeContentRegistry.ts
Labels: size/L

#11805 (hotfix) Revert tan-query selector in audioplayer
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/XS

#11806 [QA-2046] Fix more by lineup on mobile showing dups
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
Labels: size/S

#11803 [PE-5927] Update event mutation hooks
  packages/common/src/api/tan-query/events/useCreateEvent.ts
  packages/common/src/api/tan-query/events/useEventsByEntityId.ts
  packages/common/src/api/tan-query/events/useUpdateEvent.ts
  packages/common/src/api/tan-query/events/utils.ts
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/L

#11762 Try to fix publish packages command
  .github/workflows/publish-packages.yml
Labels: size/XS

#11807 Fix milestone bug
  packages/discovery-provider/ddl/functions/handle_play.sql
Labels: size/XS

#11810 [PE-5938] Fix timezone issues for events
  packages/common/src/adapters/event.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#11812 [QA-2054] Fix overflowing remix text
  packages/web/src/components/data-entry/ContextualMenu.module.css
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsField.module.css
  packages/web/src/components/edit/fields/RemixSettingsField/TrackInfo.tsx
  packages/web/src/components/track/TrackArtwork.tsx
Labels: size/M

#11813 Debounce mobile search input
  packages/mobile/src/screens/search-screen/SearchBar.tsx
Labels: size/XS

#11802 [C-5669] Migrate track rank to tan-query
  packages/common/src/adapters/trending.ts
  packages/common/src/api/index.ts
  packages/common/src/models/Trending.ts
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/pages/track/reducer.ts
  packages/common/src/store/pages/track/selectors.ts
  packages/common/src/store/pages/track/types.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/pages/track/sagas.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#11817 Fix TQ lineup issues on mobile
  packages/common/src/api/tan-query/useFeed.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/mobile/src/components/lineup/TanQueryLineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
Labels: size/XL

#11819 Update EditTrackPage to use the useUpdateTrack hook
  packages/common/src/api/index.ts
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
Labels: size/M

#11820 Throw an error if SDK consumer attempts an upload with "All Genres" as the genre
  packages/sdk/src/sdk/api/tracks/types.ts
Labels: size/XS

#11824 Fix duplicate 'Your Feed' problem in e2e tests
  packages/web/e2e/auth.setup.ts
Labels: size/XS

#11821 [C-5668] Migrate remix page to tan-query (#11034)
  packages/common/src/store/index.ts
  packages/common/src/store/pages/remixes/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/remix-settings/index.ts
  packages/common/src/store/remix-settings/selectors.ts
  packages/common/src/store/remix-settings/slice.ts
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/remixes-page/sagas.ts
  packages/web/src/common/store/remix-settings/sagas.ts
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#11823 Revert tq-lineups
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
  packages/mobile/src/screens/trending-screen/TrendingLineup.tsx
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/trending/lineups/trending/sagas.ts
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
Labels: size/XXL

#11825 [QA-2058] Max height for description text input
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
  packages/web/src/components/edit/fields/TrackMetadataFields.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#11829 Update validation for end_date for events
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_event.py
  packages/discovery-provider/src/tasks/entity_manager/entities/event.py
Labels: size/M

#11827 Add missing package
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/archiver/package.json
Labels: size/XS

#11818 [API-41] Clean up old trending versions add query idx
  packages/discovery-provider/ddl/migrations/0133_trending_cleanup.sql
Labels: size/XS

#11828 [PE-5949] Migrate track page fetch to tan-query
  package-lock.json
  packages/common/src/api/tan-query/useTrackByParams.ts
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/pages/track/selectors.ts
  packages/mobile/package.json
  packages/mobile/src/components/comments/RecentUserCommentsDrawer.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track/TrackLink.tsx
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/utils.ts
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/track/sagas.ts
  packages/web/src/pages/track-page/DesktopServerTrackPage.tsx
  packages/web/src/pages/track-page/MobileServerTrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/ssr/track/+onRenderHtml.tsx
Labels: size/XL

#11830 Fix flakey discovery node test
  packages/discovery-provider/src/queries/get_track_library.py
Labels: size/S

#11837 Add splits validation in usdc purchases check
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#11839 Improve core health check block diff
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/queries/get_health_unit_test.py
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/M

#11822 [PE-5942] Add new flair hover card item
  packages/harmony/src/components/hover-card/HoverCard.mdx
  packages/harmony/src/components/hover-card/HoverCard.stories.tsx
  packages/harmony/src/components/hover-card/HoverCard.tsx
  packages/harmony/src/components/hover-card/HoverCardHeader.tsx
  packages/harmony/src/components/hover-card/index.ts
  packages/harmony/src/components/hover-card/types.ts
  packages/harmony/src/components/index.ts
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/hover-card/HoverCardBody.tsx
  packages/web/src/components/hover-card/index.ts
Labels: size/L

#11841 Hide premium upload UI when feature flag off
  packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
Labels: size/M

#11840 [PE-5958, PE-5960] Events QA 2
  packages/common/src/utils/dayjs.ts
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/utils/dayjs.ts
Labels: size/L

#11842 Add stage starting block for pinned comment staging challenge
  packages/discovery-provider/src/challenges/challenges.stage.json
Labels: size/XS

#11834 Mobile track description scrolls to toggle button on collapse
  packages/mobile/src/components/core/VirtualizedScrollView.tsx
  packages/mobile/src/screens/track-screen/TrackDescription.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#11838 Don't check USDC_PURCHASES FeatureFlag in upload, default to on
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/upload/sagaHelpers.ts
Labels: size/S

#11831 Remove api check
  packages/discovery-provider/src/queries/get_health.py
Labels: size/M

#11832 Web remix submissions page
  packages/common/src/api/tan-query/useRemixes.ts
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_remixes_of.py
  packages/sdk/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/remixes-page/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/remixes-page/hooks.ts
Labels: size/L

#11836 [PE-5955] Don't include type in stem filenames
  packages/common/src/utils/fileUtil.test.ts
  packages/common/src/utils/fileUtil.ts
Labels: size/M

#11844 [PE-5962, PE-5918] Migrate stems to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useFileSizes.ts
  packages/common/src/api/tan-query/useStems.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useStems.ts
  packages/common/src/hooks/useUploadingStems.ts
  packages/common/src/store/cache/tracks/selectors.ts
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/queries/get_track_inspect_info.py
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/default/models/TrackInspectList.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/StemsSEOHint.tsx
  packages/web/src/store/application/ui/stemsUpload/sagas.ts
Labels: size/XL

#11846 [PE-5964] Improve event api, hooks, and performance
  .changeset/short-suits-punch.md
  packages/common/src/api/tan-query/events/useCreateEvent.ts
  packages/common/src/api/tan-query/events/useEventsByEntityId.ts
  packages/common/src/api/tan-query/events/useRemixContest.ts
  packages/common/src/api/tan-query/events/useUpdateEvent.ts
  packages/common/src/api/tan-query/events/utils.ts
  packages/discovery-provider/src/api/v1/events.py
  packages/discovery-provider/src/queries/get_events.py
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/sdk/src/sdk/api/generated/default/apis/EventsApi.ts
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/L

#11850 [QA-2064] Fix deactivated showing on playlist tiles
  packages/web/src/components/track/desktop/TrackListItem.tsx
Labels: size/XS

#11847 Show not supported drawer on mobile web for Connected Wallets modal
  packages/web/src/pages/audio-page/components/modals/ConnectedWalletsModal.tsx
Labels: size/M

#11852 [PE-5940] Add turn off option for remix contests
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
Labels: size/M

#11849 [PE-5966] Add new wallets page with the m1 components
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useTokenPrice.ts
  packages/common/src/api/tan-query/useWalletOwner.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/utils/route.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/components/payout-wallet-display/PayoutWalletDisplay.tsx
  packages/web/src/components/payout-wallet-display/index.tsx
  packages/web/src/components/user-badges/TieredUserBadge.tsx
  packages/web/src/components/user-badges/index.ts
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/EditableName.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
  packages/web/src/pages/wallet-page/index.ts
  packages/web/src/utils/zIndex.ts
Labels: size/XL

#11848 [PE-5951] Remix contest ended UI
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#11855 [PE-5933] Remix countdown UI
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useRemixCountdown.ts
  packages/common/src/utils/formatUtil.ts
  packages/mobile/src/screens/track-screen/RemixContestCountdown.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/web/src/components/track/RemixContestCountdown.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/L

#11856 Mobile remix submissions page
  packages/common/src/api/tan-query/useRemixes.ts
  packages/common/src/messages/index.ts
  packages/common/src/messages/remixes.ts
  packages/mobile/src/components/lineup/TanQueryLineup.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/src/pages/remixes-page/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
  packages/web/src/pages/remixes-page/hooks.ts
Labels: size/L

#11859 [PE-5939] Disallow remix contests for remixes
  packages/discovery-provider/src/tasks/entity_manager/entities/event.py
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/menu/TrackMenu.tsx
Labels: size/XS

#11845 [API-2] Add additional ddex fields to tracks data model
  packages/discovery-provider/ddl/migrations/0134_ddex_majors_fields.sql
  packages/discovery-provider/src/models/tracks/track.py
Labels: size/M

#11851 Update challenge config starting block for comment pin challenge
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/XS

#11860 Make updates to m1 for wallet ui updates
  packages/common/src/utils/route.ts
  packages/harmony/src/assets/icons/TokenBronze.png
  packages/harmony/src/assets/icons/TokenGold.png
  packages/harmony/src/assets/icons/TokenNoTier.png
  packages/harmony/src/assets/icons/TokenPlatinum.png
  packages/harmony/src/assets/icons/TokenSilver.png
  packages/harmony/src/assets/icons/Verified.svg
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/user-badges/TieredUserBadge.tsx
Labels: size/M

#11861 [PE-5972] Mobile download all alignment fix
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
Labels: size/L

#11862 Small m1 updates for wallet UI updates
  packages/web/src/components/payout-wallet-display/PayoutWalletDisplay.tsx
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
Labels: size/S

#11809 Fix AAO error on missing timestamp
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/XS

#11835 Cursor rule to avoid unnecessary code changes
  .cursor/rules/run-always.mdc
Labels: size/M

#11857 [PE-5973, PE-5968] Migrate track page lineups to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useTrackPageLineup.ts
  packages/common/src/messages/trackPage.ts
  packages/common/src/store/pages/track/actions.ts
  packages/mobile/src/components/lineup/TanQueryLineup.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenLineup.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
  packages/web/src/common/store/pages/track/lineups/sagas.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/section-button/SectionButton.module.css
  packages/web/src/components/section-button/SectionButton.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/TrackPageLineup.tsx
  packages/web/src/pages/track-page/components/ViewOtherRemixesButton.tsx
  packages/web/src/pages/track-page/components/desktop/Remixes.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/Remixes.module.css
  packages/web/src/pages/track-page/components/mobile/Remixes.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/XXL

#11863 Remove filename from mobile DownloadRow
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
Labels: size/L

#11869 [PE-5984] Mobile web remix contest track page UI
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#11868 QA-2060 Fix middleware to have same account fetching logic as the account endpoint
  packages/discovery-provider/src/queries/get_users.py
  packages/discovery-provider/src/utils/auth_middleware.py
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/S

#11870 [PE-5978] Update events tan-query state to be more normalized
  packages/common/src/api/tan-query/events/useCreateEvent.ts
  packages/common/src/api/tan-query/events/useDeleteEvent.ts
  packages/common/src/api/tan-query/events/useEventsByEntityId.ts
  packages/common/src/api/tan-query/events/useRemixContest.ts
  packages/common/src/api/tan-query/events/useUpdateEvent.ts
  packages/common/src/api/tan-query/events/utils.ts
Labels: size/L

#11872 [PE-5988] Disable upload more stems dropzone when max stems
  packages/web/src/components/edit/fields/StemFilesView.tsx
Labels: size/XS

#11874 [PE-5995, PE-5996] Fix mobile remix end-date input
  packages/common/src/api/tan-query/events/useRemixContest.ts
  packages/mobile/src/components/core/DateTimeInput.tsx
  packages/mobile/src/components/expandable/ExpandableArrowIcon.tsx
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/screens/track-screen/RemixContestCountdown.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/track/RemixContestCountdown.tsx
Labels: size/M

#11873 Fix remix page filter buttons
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Labels: size/S

#11876 [PE-5959, PE-5969] Fix some small styling issues around remix contests
  packages/harmony/src/components/popup-menu/PopupMenu.tsx
  packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
Labels: size/XS

#11879 [PE-5979] Remix countdown styling updates
  packages/common/src/hooks/useRemixCountdown.ts
  packages/mobile/src/screens/track-screen/RemixContestCountdown.tsx
  packages/web/src/components/track/RemixContestCountdown.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Labels: size/L

#11880 [PE-5954] Download section styling updates
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadRow.tsx
Labels: size/M

#11875 [PE-5998] Address m1 QA comments for Wallet UI updates
  packages/common/src/api/tan-query/useTokenPrice.ts
  packages/common/src/utils/route.ts
  packages/harmony/src/components/hover-card/HoverCard.tsx
  packages/harmony/src/components/hover-card/HoverCardHeader.tsx
  packages/harmony/src/components/hover-card/types.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/payout-wallet-display/PayoutWalletDisplay.tsx
  packages/web/src/components/user-badges/TieredUserBadge.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/components/user-badges/index.ts
  packages/web/src/pages/audio-page/AudioPage.tsx
  packages/web/src/pages/chat-page/components/ChatUser.tsx
  packages/web/src/pages/chat-page/components/ComposePreviewInfo.tsx
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/components/EditableName.tsx
  packages/web/src/pages/transaction-history-page/desktop/TransactionHistoryPage.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
Labels: size/XL

#11881 [PE-5986] Mobile-web expandable description
  packages/web/src/pages/track-page/components/mobile/TrackDescription.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#11883 [PE-5980] Disallow duplicate stems
  packages/web/src/components/edit/fields/StemFilesView.tsx
Labels: size/M

#11882 Identify email to amplitude
  packages/common/src/audius-query/AudiusQueryContext.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/storeContext.ts
  packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
  packages/mobile/src/services/analytics.ts
  packages/web/src/common/store/analytics/actions.ts
  packages/web/src/common/store/analytics/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/pages/sign-in-page/SignInPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
  packages/web/src/services/analytics/amplitude.ts
  packages/web/src/services/analytics/index.ts
Labels: size/M

#11884 [PE-6000] Add media queries to harmony and update media queries in wallet UI
  packages/harmony/README.md
  packages/harmony/src/contexts/MediaContext.tsx
  packages/harmony/src/contexts/index.ts
  packages/harmony/src/foundations/breakpoints/breakpoints.ts
  packages/harmony/src/foundations/breakpoints/index.ts
  packages/harmony/src/foundations/index.ts
  packages/harmony/src/hooks/index.ts
  packages/harmony/src/hooks/useMedia.ts
  packages/harmony/src/hooks/useMediaQueryListener.ts
  packages/harmony/src/index.ts
  packages/harmony/src/utils/createResponsiveStyles.ts
  packages/harmony/src/utils/index.ts
  packages/harmony/src/utils/makeResponsiveStyles.ts
  packages/web/src/app/AppProviders.tsx
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.styles.ts
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
Labels: size/XL

#11885 Add distinct tracks played to AAO score
  packages/discovery-provider/ddl/functions/user_scores.sql
Labels: size/S

#11888 [PE-5961] Fix event form AM/PM value position
  packages/harmony/src/components/select/Select/Select.tsx
Labels: size/XS

#11887 [PE-6003, PE-6004] Add 90 day limit to contest end-date, Add time-input, default to 11:59
  packages/harmony/src/components/select/Select/Select.tsx
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/edit/fields/DatePickerField.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/components/host-remix-contest-modal/TimeInput.tsx
Labels: size/L

#11886 [PE-5999] Fix submission disappearing
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/track-page/components/TrackPageLineup.tsx
Labels: size/M

#11878 [PE-5989] Remove web dayjs
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/utils/dateUtils.ts
  packages/web/src/utils/dayjs.ts
Labels: size/S
