Repository AudiusProject/apps, pull requests merged in 2025-01, with the labels that each got.

#10860 [C-5581] Remove default props
  packages/harmony/src/components/scrubber/Scrubber.tsx
  packages/harmony/src/components/scrubber/types.ts
  packages/mobile/src/components/scrubber/Scrubber.tsx
  packages/web/src/components/actions-tab/ActionsTab.jsx
  packages/web/src/components/ai-attribution-modal/SearchBarResult.jsx
  packages/web/src/components/data-entry/DatePicker.jsx
  packages/web/src/components/data-entry/DropdownInput.jsx
  packages/web/src/components/data-entry/Input.jsx
  packages/web/src/components/data-entry/LabeledInput.jsx
  packages/web/src/components/data-entry/TagInput.jsx
  packages/web/src/components/data-entry/TextArea.jsx
  packages/web/src/components/delineator/Delineator.jsx
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/image-selection/ImageSelectionButton.jsx
  packages/web/src/components/image-selection/ImageSelectionPopup.jsx
  packages/web/src/components/image-selection/PropTypes.js
  packages/web/src/components/lineup/EndOfLineup.jsx
  packages/web/src/components/lineup/Lineup.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/mask/Mask.jsx
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/more/More.jsx
  packages/web/src/components/navigation/Dropdown.jsx
  packages/web/src/components/page/Page.tsx
  packages/web/src/components/play-bar/PlayButton.jsx
  packages/web/src/components/play-bar/VolumeBar.jsx
  packages/web/src/components/play-bar/repeat-button/RepeatButton.jsx
  packages/web/src/components/play-bar/shuffle-button/ShuffleButton.jsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/components/search-bar/ConnectedSearchBar.jsx
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/components/search-bar/SearchBarResult.module.css
  packages/web/src/components/search-bar/SearchBarResult.tsx
  packages/web/src/components/search-bar/SearchTag.tsx
  packages/web/src/components/search/SearchBar.jsx
  packages/web/src/components/search/SearchBarResult.jsx
  packages/web/src/components/segmented-progress-bar/SegmentedProgressBar.jsx
  packages/web/src/components/status-message/StatusMessage.tsx
  packages/web/src/components/toast/Toast.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/mobile/TrackList.tsx
  packages/web/src/components/upload/InvalidFileType.jsx
  packages/web/src/components/upload/PreviewButton.jsx
  packages/web/src/components/upload/UploadArtwork.jsx
  packages/web/src/pages/dashboard-page/components/TotalPlaysChart.jsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XXL

#10876 only relay em in dev
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
Labels: size/XS

#10814 Add DashGo
  packages/ddex/entrypoint/src/App.tsx
  packages/ddex/entrypoint/src/distributors/prod.json
Labels: size/M

#10883 [PAY-3739] Fix folder expansion
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
Labels: size/XS

#10888 Fix mobile prettier
  package-lock.json
  packages/eslint-config-audius/package.json
  packages/mobile/package.json
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/comments/CommentBadge.tsx
  packages/mobile/src/components/comments/useScrollEventHandlers.ts
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/core/ContextualMenu.tsx
  packages/mobile/src/components/core/LockedStatusBadge.tsx
  packages/mobile/src/components/core/RadioButton.tsx
  packages/mobile/src/components/core/Screen/Screen.tsx
  packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx
  packages/mobile/src/components/core/TagInput.tsx
  packages/mobile/src/components/core/Text.tsx
  packages/mobile/src/components/edit/PriceAndAudienceField/SpecialAccessRadioField.tsx
  packages/mobile/src/components/edit/VisibilityField/VisibilityField.tsx
  packages/mobile/src/components/edit/VisibilityField/VisibilityScreen.tsx
  packages/mobile/src/components/fields/TextAreaField.tsx
  packages/mobile/src/components/image/primitiveToImageSource.ts
  packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/now-playing-drawer/useCurrentTrackDuration.ts
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/status-message/StatusMessage.tsx
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/harmony-native/components/Artwork.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/FastImage/FastImage.tsx
  packages/mobile/src/harmony-native/components/MusicBadge/MusicBadge.tsx
  packages/mobile/src/harmony-native/components/Radio/Radio.tsx
  packages/mobile/src/harmony-native/components/Text/Text.tsx
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/harmony-native/components/layout/Box/Box.tsx
  packages/mobile/src/hooks/useNavigation.ts
  packages/mobile/src/screens/audio-screen/Panel.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatScreen.tsx
  packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
  packages/mobile/src/screens/edit-collection-screen/CollectionArtworkField.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/ReactionList.tsx
  packages/mobile/src/screens/search-screen/BpmFilter.tsx
  packages/mobile/src/screens/sign-on-screen/components/PasswordCompletionChecklist.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/mobile/src/screens/wallet-connect/ConnectNewWalletButton.tsx
  packages/mobile/src/store/offline-downloads/selectors.ts
  packages/mobile/src/utils/launchImageLibrary.e2e.ts
  packages/mobile/src/utils/theme.ts
  packages/web/package.json
Labels: size/L

#10886 [C-5589] Migrate collections to react query
  packages/common/src/api/collection.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useUpdateCollection.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/hooks/chats/usePurchasersAudience.ts
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/hooks/useCollectionMetadata.ts
  packages/common/src/hooks/useGeneratePlaylistArtwork.ts
  packages/common/src/hooks/useRemoteVar.ts
  packages/common/src/store/cache/syncWithReactQuery.ts
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx
  packages/mobile/src/screens/collection-screen/CollectionDownloadStatusRow.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collection/desktop/EditButton.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/mobile/CollectionHeader.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/track/OwnerActionButtons.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumPurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/AlbumSaleModalContent.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ComposePreviewInfo.tsx
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
  packages/web/src/pages/edit-collection-page/mobile/EditCollectionPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
  packages/web/src/pages/search-page/RecentSearches.tsx
Labels: size/XL

#10885 Misc web package cleanup
  package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/ui/vip-discord-modal/sagas.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/web/index.html
  packages/web/package.json
  packages/web/src/services/audius-backend/audius-backend-instance.ts
  packages/web/src/types/scrollbar-width.d.ts
Labels: size/M

#10894 Fix cache syncing
  packages/common/src/store/index.ts
  packages/web/src/common/store/cache/sagas.ts
Labels: size/XS

#10893 Refactor primeData helpers
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useUpdateTrack.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
Labels: size/L

#10895 [PAY-3741] Fix playback immediately after purchase
  packages/common/src/store/gated-content/sagas.ts
Labels: size/XS

#10889 [C-5588] Replace useGetTrackById usages with useTrack
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/track.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/hooks/chats/usePurchasersAudience.ts
  packages/common/src/hooks/useTrackMetadata.ts
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx
  packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/web/src/components/comments/CommentPreview.tsx
  packages/web/src/components/composer-input/ComposerInput.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsField.tsx
  packages/web/src/components/edit/fields/RemixSettingsField/TrackInfo.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/now-playing/components/ActionsBar.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/track/DynamicTrackArtwork.tsx
  packages/web/src/components/track/OwnerActionButtons.tsx
  packages/web/src/components/track/TrackStats.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackPurchaseModalContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ComposePreviewInfo.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
  packages/web/src/pages/search-page/RecentSearches.tsx
  packages/web/src/pages/track-page/components/TrackRemixes.tsx
  packages/web/src/pages/track-page/components/ViewOtherRemixesButton.tsx
Labels: size/L

#10877 [PAY-3743][PAY-3707] Finish page separation and add rewards notification on navitem
  packages/common/src/utils/route.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-transactions-page/AudioWalletTransactions.module.css
  packages/web/src/pages/audio-transactions-page/AudioWalletTransactions.tsx
  packages/web/src/pages/audio-transactions-page/index.ts
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
  packages/web/src/pages/rewards-page/Tiers.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/components/modals/HCaptchaModal.tsx
Labels: size/L

#10891 [PAY-3729] Fix issues with cover photos and challenges
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/challenges/selectors/profile-progress.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
Labels: size/M

#10899 Add missing dependency for CRA react example
  .changeset/tough-starfishes-play.md
  packages/create-audius-app/examples/react/package.json
Labels: size/XS

#10897 [PAY-3750] Remove dead code in web - part 1
  packages/web/src/app/HistoryProvider.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/hooks/useModalState.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/notifications/parseAndProcessNotifications.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/search-bar/types.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/tipping/storageUtils.ts
  packages/web/src/common/store/user-list/purchasers/sagas.ts
  packages/web/src/common/store/user-list/related-artists/sagas.ts
  packages/web/src/common/store/user-list/remixers/sagas.ts
  packages/web/src/components/actions-tab/ActionsTab.jsx
  packages/web/src/components/add-to-collection/mobile/AddToCollection.tsx
  packages/web/src/components/ai-attribution-modal/AiAttributionButton.tsx
  packages/web/src/components/ai-attribution-modal/AiAttributionModal.module.css
  packages/web/src/components/ai-attribution-modal/AiAttributionModal.tsx
  packages/web/src/components/ai-attribution-modal/index.ts
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/web/src/components/artist/ArtistCover.tsx
  packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx
  packages/web/src/components/avatar/AvatarLegacy.module.css
  packages/web/src/components/avatar/AvatarLegacy.tsx
  packages/web/src/components/avatar/index.ts
  packages/web/src/components/banner/DirectMessagesBanner.tsx
  packages/web/src/components/buy-audio-modal/components/useCoinbasePay.ts
  packages/web/src/components/change-email/ChangeEmailModal.tsx
  packages/web/src/components/change-password/ChangePasswordModal.tsx
  packages/web/src/components/client-only/ClientOnly.tsx
  packages/web/src/components/collectibles-playlist-table/index.ts
  packages/web/src/components/comment-settings-modal/CommentSettingsModal.tsx
  packages/web/src/components/comments/CommentSection.tsx
  packages/web/src/components/comments/CommentSkeletons.tsx
  packages/web/src/components/lineup/LineupTileSkeleton.tsx
  packages/web/src/components/notification/Notification/utils.ts
  packages/web/src/utils/network.js
  packages/web/src/utils/queueUtil.js
  packages/web/src/utils/route.ts
  packages/web/src/utils/theme/theme.ts
  packages/web/src/utils/withNullGuard.tsx
Labels: size/XXL

#10890 Fix entrypoint for /rewards
  packages/common/src/utils/route.ts
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/XS

#10900 Fix wrong data getting written to queryClient
  packages/common/src/store/cache/syncWithReactQuery.ts
Labels: size/XS

#10901 [PAY-3750] Remove unused exports and dead code - part 2
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/backend/sagas.ts
  packages/web/src/common/store/cache/sagas.ts
  packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
  packages/web/src/common/store/notifications/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/common/store/saved-collections/actions.ts
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/settings-page/store/selectors.ts
  packages/web/src/pages/sign-up-page/SignUpPage.tsx
  packages/web/src/pages/sign-up-page/components/EmailTakenHint.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateLoginDetailsPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
  packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
  packages/web/src/pages/something-wrong/SomethingWrong.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
  packages/web/src/pages/upload-page/types.ts
  packages/web/src/pages/visualizer/store/slice.ts
  packages/web/src/public-site/pages/landing-page/LandingPage.tsx
  packages/web/src/public-site/pages/landing-page/components/CaseStudies.module.css
  packages/web/src/public-site/pages/landing-page/components/CaseStudies.tsx
  packages/web/src/public-site/pages/landing-page/components/Hero.tsx
  packages/web/src/services/audio-player/AudioPlayer.ts
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/services/remote-config/remote-config-instance.ts
  packages/web/src/services/solana/solana.ts
  packages/web/src/ssr/collection/+onBeforeRender.ts
  packages/web/src/ssr/util.ts
  packages/web/src/store/account/sagas.ts
  packages/web/src/store/application/ui/cookieBanner/sagas.ts
  packages/web/src/store/application/ui/notifications/notificationsUISelectors.ts
  packages/web/src/store/application/ui/scrollLock/sagas.ts
  packages/web/src/store/configureStore.ts
  packages/web/src/store/reachability/sagas.ts
  packages/web/src/store/testHelper.js
  packages/web/src/test/redux-state.ts
  packages/web/src/utils/browserNotifications.ts
  packages/web/src/utils/constants.ts
  packages/web/src/utils/dateUtils.ts
  packages/web/src/utils/effects.js
  packages/web/src/utils/gdpr.ts
  packages/web/src/utils/imageProcessingUtil.ts
  packages/web/src/utils/logger.js
  packages/web/src/workers/averageRgb.worker.js
Labels: size/XL

#10905 Switch react-lottie for lottie-react
  package-lock.json
  packages/embed/package.json
  packages/harmony/package.json
  packages/harmony/src/components/loading-spinner/LoadingSpinner.tsx
  packages/web/package.json
  packages/web/patches/react-lottie+1.2.3.patch
  packages/web/src/components/animated-button/AnimatedButtonProvider.tsx
  packages/web/src/components/cover-photo/CoverPhoto.tsx
  packages/web/src/components/follow-artist-card/FollowArtistCard.tsx
  packages/web/src/components/loading-spinner/LoadingSpinner.tsx
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
  packages/web/src/components/notification/NotificationPage.tsx
  packages/web/src/components/play-bar/PlayButton.tsx
  packages/web/src/components/play-bar/repeat-button/RepeatButton.tsx
  packages/web/src/components/play-bar/repeat-button/RepeatButtonProvider.tsx
  packages/web/src/components/play-bar/shuffle-button/ShuffleButton.tsx
  packages/web/src/components/play-bar/shuffle-button/ShuffleButtonProvider.tsx
  packages/web/src/components/profile-picture/ProfilePicture.jsx
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/components/search-bar/SearchBar.tsx
  packages/web/src/components/track/mobile/TrackListItem.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/not-found-page/NotFoundPage.tsx
  packages/web/src/pages/profile-page/components/mobile/UploadStub.tsx
  packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
  protocol-dashboard/package.json
Labels: size/L

#10898 [C-5595] Migrate useGetUserTracksByHandle to react-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
  packages/common/src/api/track.ts
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
Labels: size/L

#10908 Update tcr cron
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
Labels: size/XS

#10915 Add migration to revert corrupted CIDs
  packages/discovery-provider/ddl/migrations/0111_fix_corrupted_cid_metadata.sql
Labels: size/M

#10916 delete resized Qm image variatns.
  pkg/mediorum/server/repair.go
Labels: size/S

#10909 [C-5597] Migrate favorites api to tan-query
  packages/common/src/api/favorites.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useFavoritedTracks.ts
Labels: size/M

#10918 [C-5601] Migrate related-artists to tan query
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/feed/selectors.ts
  packages/common/src/store/pages/feed/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_related_artists.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.pyi
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2_grpc.py
  packages/mobile/src/components/suggested-follows/ArtistCategoryButton.tsx
  packages/mobile/src/components/suggested-follows/ContinueButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/components/suggested-follows/index.ts
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/mobile/src/store/sagas.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/store/sagas.ts
Labels: size/XXL

#10919 [QA-1900] Fix track downloads by not having download service rely on window
  packages/common/src/services/track-download/TrackDownload.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/services/track-download.ts
Labels: size/S

#10920 Bring back window.store
  packages/web/src/app/AppProviders.tsx
  packages/web/src/app/ReduxProvider.tsx
  packages/web/src/test/test-utils.tsx
Labels: size/M

#10914 Rely on backend to do Wormhole redemption
  package-lock.json
  packages/common/package.json
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/mobile/ios/Podfile.lock
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/services/audius-sdk/audiusSdk.ts
Labels: size/M

#10922 [C-3613] Fix issue with theme persistence
  packages/web/src/app/AppProviders.tsx
Labels: size/S

#10923 [C-5602] Don't set default icon fill
  svgr-template.js
Labels: size/XS

#10912 Add staking plugin to replace other system checks
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/workflows/discovery.yml
  dev-tools/compose/docker-compose.pedalboard.dev.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.yml
  package-lock.json
  packages/compose/package.json
  packages/discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/approveManagerRequest.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/comment.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/commentMention.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/commentReaction.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/commentThread.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/multipleMappings.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseBuyer.test.ts.snap
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap
  packages/discovery-provider/plugins/pedalboard/apps/staking/.eslintrc.js
  packages/discovery-provider/plugins/pedalboard/apps/staking/README.md
  packages/discovery-provider/plugins/pedalboard/apps/staking/package.json
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/logger.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/routes/balance.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/routes/health.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/routes/initRound.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/server.ts
  packages/discovery-provider/plugins/pedalboard/apps/staking/tsconfig.json
Labels: size/L

#10925 Fix edit track shows errors
  packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
Labels: size/S

#10927 [C-5596] Fix lowercase tabs
  packages/common/src/store/pages/explore/types.ts
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
  packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/M

#10928 [QA-1903] Fix collections tab
  packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
Labels: size/M

#10913 [C-5600] Use followers hook to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useCurrentUser.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/user.ts
  packages/common/src/hooks/chats/useAudienceUsers.ts
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
Labels: size/L

#10931 [PAY-3732] Fix BuyAudio flow with SDK
  .changeset/wicked-sloths-develop.md
  packages/sdk/src/sdk/services/Solana/programs/types.ts
  packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/services/audius-backend/Jupiter.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/L

#10924 [C-5614] Migrate mutuals to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#10934 Remove Solana wrappers
  packages/common/src/hooks/useCoinflowAdapter.ts
  packages/common/src/hooks/useCreateUserbankIfNeeded.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/store/buy-usdc/sagas.ts
  packages/common/src/store/buy-usdc/utils.ts
  packages/common/src/store/index.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/solana/index.ts
  packages/common/src/store/solana/sagas.ts
  packages/common/src/store/solana/selectors.ts
  packages/common/src/store/solana/slice.ts
  packages/mobile/src/store/sagas.ts
  packages/sdk/src/sdk/api/challenges/types.ts
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/L

#10937 [C-5627] Fix download track after replace
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/S

#10933 [C-5547] Fix track download
  packages/discovery-provider/src/queries/get_track_signature.py
Labels: size/S

#10936 [C-5630] Add track replace analytics
  packages/common/src/models/Analytics.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackConfirmationDrawer.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/L

#10938 [C-5498] Fix track file name overflow
  packages/harmony/src/components/button/BaseButton/BaseButton.tsx
  packages/harmony/src/components/button/PlainButton/PlainButton.tsx
  packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
  packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx
  packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
  packages/web/src/components/file-replace-container/FileReplaceContainer.tsx
  packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
Labels: size/M

#10939 [C-5496] Improve hit-slop for IconButton
  packages/mobile/src/components/lineup-tile/VanityMetrics.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/harmony-native/index.ts
Labels: size/XS

#10940 [C-5624] Fix entity image skeleton
  packages/mobile/src/components/skeletons/EntitySkeleton.tsx
Labels: size/XS

#10930 Replace appContext with audiusQueryContext for sdk usage
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useCurrentUser.ts
  packages/common/src/api/tan-query/useFavoritedTracks.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useSupportedUsers.ts
  packages/common/src/api/tan-query/useSupporter.ts
  packages/common/src/api/tan-query/useSupporters.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUpdateCollection.ts
  packages/common/src/api/tan-query/useUpdateTrack.ts
  packages/common/src/api/tan-query/useUpdateUser.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
  packages/common/src/api/tan-query/useUsers.ts
Labels: size/L

#10932 [C-5615] Migrate ai-pages to tan-query
  packages/common/src/store/pages/ai/selectors.ts
  packages/common/src/store/pages/ai/slice.ts
  packages/common/src/store/pages/index.ts
  packages/mobile/src/components/details-tile/DetailsTileAiAttribution.tsx
  packages/mobile/src/screens/ai-generated-tracks-screen/AiGeneratedTracksScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/pages/ai/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/ai/sagas.ts
  packages/web/src/components/track/AiTrackSection.tsx
  packages/web/src/pages/ai-attributed-tracks-page/AiPageProvider.tsx
  packages/web/src/pages/ai-attributed-tracks-page/components/desktop/AiPage.tsx
  packages/web/src/pages/ai-attributed-tracks-page/components/mobile/AiPage.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#10941 [QA-1904] Fix profile tab SSR
  packages/common/src/store/pages/profile/types.ts
  packages/web/src/utils/route/userRouteParser.ts
Labels: size/S

#10947 Fix track replace dependencies
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/S

#10949 [PAY-3169] Remove sdkMigrationutils
  package-lock.json
  packages/common/package.json
  packages/common/src/utils/index.ts
  packages/common/src/utils/sdkMigrationUtils.ts
Labels: size/M

#10950 Pause track preview when replacing track file
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/XS

#10952 [C-556] Fix sign-up completion link navigation
  packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/M

#10948 Temporarily disable track replace downloads until the DN code goes out
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/S

#10929 [C-5598] Migrate usePurchases and usePurchasesCount to tan-query
  packages/common/src/adapters/purchase.ts
  packages/common/src/api/index.ts
  packages/common/src/api/purchases.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/usePurchases.ts
  packages/common/src/api/tan-query/usePurchasesCount.ts
  packages/common/src/api/tan-query/useSales.ts
  packages/common/src/api/tan-query/useSalesCount.ts
  packages/common/src/api/tan-query/utils/parsePurchase.ts
  packages/common/src/api/track.ts
  packages/web/src/hooks/useErrorPage.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
  packages/web/src/pages/pay-and-earn-page/mobile/PayAndEarnPage.tsx
Labels: size/XL

#10954 [C-5618] Remove social fetching
  packages/common/src/hooks/useTwitterButtonStatus.ts
  packages/common/src/store/cache/users/actions.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/ai-attribution-modal/SearchBarResult.jsx
  packages/web/src/components/notification/Notification/components/TwitterShareButton.tsx
  packages/web/src/components/twitter-share-button/TwitterShareButton.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Labels: size/L, size/XXL

#10956 [C-5632] Use react-query Config type
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useCurrentUser.ts
  packages/common/src/api/tan-query/useFavoritedTracks.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/usePurchasesCount.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useSalesCount.ts
  packages/common/src/api/tan-query/useSupportedUsers.ts
  packages/common/src/api/tan-query/useSupporter.ts
  packages/common/src/api/tan-query/useSupporters.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
Labels: size/L

#10957 [C-5642] Migrate signUp api to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/signUp.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useEmailInUse.ts
  packages/common/src/api/tan-query/useHandleInUse.ts
  packages/common/src/api/tan-query/useHandleReservedStatus.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/schemas/sign-on/emailSchema.ts
  packages/common/src/schemas/sign-on/pickHandleSchema.ts
  packages/common/src/schemas/sign-on/signInSchema.ts
Labels: size/L

#10955 [PAY-3752] Update header styles for new nav
  packages/web/src/components/header/desktop/Header.module.css
  packages/web/src/components/header/desktop/Header.tsx
  packages/web/src/components/page/Page.module.css
  packages/web/src/components/page/Page.tsx
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/pages/ai-attributed-tracks-page/components/desktop/AiPage.module.css
  packages/web/src/pages/ai-attributed-tracks-page/components/desktop/AiPage.tsx
  packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
  packages/web/src/pages/chat-page/components/ChatHeader.module.css
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
  packages/web/src/pages/dashboard-page/DashboardPage.tsx
  packages/web/src/pages/deactivate-account-page/components/desktop/DeactivateAccountPage.tsx
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.module.css
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
  packages/web/src/pages/premium-tracks-page/desktop/PremiumTracksPageContent.tsx
  packages/web/src/pages/remixes-page/components/desktop/RemixesPage.module.css
  packages/web/src/pages/remixes-page/components/desktop/RemixesPage.tsx
  packages/web/src/pages/rewards-page/RewardsPage.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/search-page/SearchHeader.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
  packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx
  packages/web/src/pages/trending-underground/TrendingUndergroundPage.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
Labels: size/L

#10906 plays core health check
  dev-tools/compose/docker-compose.discovery.dev.yml
  dev-tools/compose/docker-compose.discovery.prod.yml
  packages/discovery-provider/ddl/migrations/0112_core_indexed_block_slot.sql
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/models/core/core_indexed_blocks.py
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/tasks/core/core_client.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.pyi
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/tasks/index_core_cutovers.py
  packages/discovery-provider/src/tasks/index_core_plays.py
  pkg/core/gen/core_proto/protocol.pb.go
  pkg/core/gen/core_proto/protocol.swagger.json
  pkg/core/gen/models/protocol_block_response.go
  pkg/core/protocol/protocol.proto
  pkg/core/server/cache.go
  pkg/core/server/grpc.go
  pkg/core/server/server.go
  pkg/mediorum/server/play_event_queue.go
  pkg/mediorum/server/serve_blob.go
Labels: size/XL

#10943 Fix app creation with signMessage
  .changeset/beige-dolphins-smoke.md
  packages/sdk/src/sdk/api/developer-apps/DeveloperAppsApi.ts
Labels: size/XS

#10942 [QA-1895] Fix deactivate account styles
  packages/web/src/pages/deactivate-account-page/components/desktop/DeactivateAccountConfirmationModal.module.css
  packages/web/src/pages/deactivate-account-page/components/desktop/DeactivateAccountConfirmationModal.tsx
Labels: size/M

#10963 fix reversed core health check
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/XS

#10960 [C-5431] Fix web upload flow artwork overwrites when track is replaced
  packages/web/src/components/edit-track/EditTrackForm.tsx
Labels: size/S

#10944 [C-5617] Migrate explore to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useExploreContent.ts
  packages/common/src/api/tan-query/useFeaturedPlaylists.ts
  packages/common/src/api/tan-query/useFeaturedProfiles.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/store/pages/explore/selectors.ts
  packages/common/src/store/pages/explore/slice.ts
  packages/common/src/store/pages/explore/types.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/profile/types.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/index.ts
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/FeaturedPlaylistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/FeaturedProfilesTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/assets/img/publicSite/AudiusWeeklyPlaylistArt.png
  packages/web/src/assets/img/publicSite/HotAndNewPlaylistArt.jpeg
  packages/web/src/assets/img/publicSite/MoombahtonPlaylistArt.png
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/pages/explore-page/ExplorePage.tsx
  packages/web/src/pages/explore-page/ExplorePageProvider.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/public-site/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/store/sagas.ts
Labels: size/XXL

#10964 Challenge tables indexes on user_id
  packages/discovery-provider/ddl/migrations/0113_challenge_user_id.sql
Labels: size/XS

#10966 [QA-1906] Fix reaction size
  packages/web/src/components/notification/Notification/components/Reaction/Reaction.tsx
  packages/web/src/components/notification/Notification/components/Reaction/index.tsx
  packages/web/src/pages/chat-page/components/ReactionPopupMenu.module.css
Labels: size/XS

#10969 Fix pagination due to missing main-contont-context-provider
  packages/web/src/app/AppProviders.tsx
Labels: size/S

#10971 Only init store once per mount of AppProviders
  packages/web/src/app/AppProviders.tsx
Labels: size/M

#10962 Update default staking health check plugin port
  packages/discovery-provider/plugins/pedalboard/apps/staking/src/index.ts
Labels: size/XS

#10958 [PAY-3765][PAY-3761][PAY-3759][PAY-3757][PAY-3756][PAY-3755] Address navbar comments
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/harmony/src/components/notification-count/NotificationCount.tsx
  packages/harmony/src/components/notification-count/types.ts
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/L

#10972 [QA-1907] Refresh only if not playing/uploading
  packages/web/src/store/reload/sagas.ts
Labels: size/XS

#10965 add index_core celery queue
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/S

#10975 Pass args to plugins
  packages/discovery-provider/nginx_conf/nginx_container.conf
Labels: size/XS

#10974 [PAY-3779] Update createAppWalletClient to take in raw strings not wallets/hex
  .changeset/kind-flowers-visit.md
  packages/sdk/src/sdk/api/albums/AlbumsApi.test.ts
  packages/sdk/src/sdk/api/developer-apps/DeveloperAppsApi.ts
  packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.test.ts
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/services/AudiusWalletClient/createAppWalletClient.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManager.test.ts
  packages/sdk/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
Labels: size/M

#10981 fix next_slot
  packages/discovery-provider/src/tasks/index_core_plays.py
Labels: size/XS

#10987 rm mediorum in releases
  .circleci/src/workflows/release.yml
Labels: size/XS

#10970 Cleanup account sagas and migrate to TS
  packages/common/src/models/User.ts
  packages/common/src/services/auth/hedgehog.ts
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/slice.ts
  packages/web/src/common/store/account/sagas.js
  packages/web/src/common/store/account/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XL

#10976 remove `test-discovery-api` job because output is ignored
  .circleci/src/jobs/@discovery-jobs.yml
  .circleci/src/workflows/discovery.yml
Labels: size/S

#10988 Init history outside of context so it can't change
  packages/web/src/app/HistoryProvider.tsx
Labels: size/M

#10978 [PAY-3721] Mobile left nav updates
  packages/common/src/hooks/useAudioBalance.ts
  packages/harmony/src/assets/icons/TokenNoTier.png
  packages/harmony/src/foundations/color/semantic.ts
  packages/mobile/src/components/audio-balance-pill/AUDIOBalancePill.tsx
  packages/mobile/src/components/usdc-balance-pill/USDCBalancePill.tsx
  packages/mobile/src/harmony-native/components/BalancePill/BalancePill.tsx
  packages/mobile/src/harmony-native/components/NotificationCount/NotificationCount.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavLink.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/VanityMetrics.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
Labels: size/XL

#10985 [PAY-3715][PAY-3754] Update playlists in navbar
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/NotificationsButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/usePlaylistPlayingStatus.ts
Labels: size/L

#10983 [PAY-3593] Revert "[PAY-3592] Always mark chat as read (temp fix) (#10397)"
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/S

#10991 don't forward sol listens in dev or stage
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
  packages/identity-service/src/routes/trackListens.js
Labels: size/S

#10994 rm unused plugins from ci
  .circleci/src/workflows/discovery.yml
Labels: size/S

#10992 Add missing plugin build
  .circleci/src/workflows/release.yml
Labels: size/XS

#10995 rm mediorum from docker tag
  .circleci/src/commands/@docker-commands.yml
Labels: size/XS

#10996 Delete more audiusd ci
  .circleci/src/commands/@audiusd-commands.yml
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/jobs/deploy-stage-nodes-just-tag.yml
  .hooks/pre-commit.json
  monitoring/go.mod
  packages/go.mod
  protocol-dashboard/go.mod
Labels: size/M

#10999 [C-5651] Update start scripts to default to spa
  packages/web/package.json
Labels: size/S

#11001 Remove sla-auditor from ci
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/workflows/release.yml
Labels: size/S

#10998 Fix updating playlist/track artwork
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/components/upload/UploadArtwork.module.css
Labels: size/S

#10946 [C-5616] Improve listening history performance
  packages/discovery-provider/integration_tests/queries/test_get_user_listening_history.py
  packages/discovery-provider/src/queries/get_user_listening_history.py
  packages/web/src/common/store/smart-collection/sagas.ts
Labels: size/M

#11003 [QA-1908] Fix supporting tiles text in dark mode
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/components/layout/Box/types.ts
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/mobile/ios/Podfile.lock
  packages/web/src/components/cover-photo/CoverPhotoV2.tsx
  packages/web/src/components/tipping/support/SupportingTile.module.css
  packages/web/src/components/tipping/support/SupportingTile.tsx
Labels: size/L

#11004 Init history with useState to fix tests
  packages/web/src/app/HistoryProvider.tsx
Labels: size/XS

#10979 [C-5644] Migrate top-artists to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useSuggestedArtists.ts
  packages/common/src/api/tan-query/useTopArtists.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/topArtists.ts
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/pages/feed-page/components/FollowUsers.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#10980 [C-5647] Migrate audio transactions to tan-query
  packages/common/src/adapters/audioTransactions.ts
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useAudioTransactions.ts
  packages/common/src/api/tan-query/useAudioTransactionsCount.ts
  packages/common/src/store/pages/audio-transactions/selectors.ts
  packages/common/src/store/pages/audio-transactions/slice.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/reducers.ts
  packages/web/src/common/store/pages/audio-transactions/sagas.ts
  packages/web/src/pages/audio-transactions-page/AudioWalletTransactions.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#10990 [C-5648] Migrate user list to tan-query
  packages/common/src/api/tan-query/useFollowers.ts
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListV2.tsx
  packages/web/src/components/user-list-modal/components/UserListModalV2.tsx
  packages/web/src/components/user-list-modal/components/lists/FavoritesUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/FollowersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/FollowingUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/MutualsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/NotificationUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/PurchasersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RelatedArtistsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RemixersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RepostsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/SupportingUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/TopSupportersUserList.tsx
  packages/web/src/components/user-list/UserListV2.module.css
  packages/web/src/components/user-list/UserListV2.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/XL

#11007 Default private playlist
  packages/common/src/schemas/metadata.ts
Labels: size/XS

#10968 MRVR: start from country list
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/mrvr.ts
Labels: size/M

#10982 Add audiusd container to vector log capture
  monitoring/vector/vector.toml
Labels: size/XS

#11006 [PAY-3784] Split and Rewards Screens
  packages/mobile/src/assets/images/tokenSpinStill.png
  packages/mobile/src/components/core/Tile/Tile.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/audio-screen/Tier.tsx
  packages/mobile/src/screens/audio-screen/TrendingRewards.tsx
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/screens/rewards-screen/Panel.tsx
  packages/mobile/src/screens/rewards-screen/RewardsClaimTile.tsx
  packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
  packages/mobile/src/screens/rewards-screen/index.ts
Labels: size/XXL

#10986 [PAY-3724] Add tier levels to badges table
  packages/web/src/components/user-badges/TierExplainerDrawer.tsx
  packages/web/src/components/user-badges/TierExplainerModal.tsx
  packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
  packages/web/src/pages/audio-rewards-page/Tiers.module.css
  packages/web/src/pages/audio-rewards-page/Tiers.tsx
  packages/web/src/pages/audio-rewards-page/TrendingRewardsTile.tsx
  packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
  packages/web/src/pages/rewards-page/Tiers.tsx
Labels: size/XXL

#11009 [PAY-3706] Add history settings card
  packages/web/src/pages/settings-page/components/desktop/ListeningHistory/ListeningHistorySettingsCard.tsx
  packages/web/src/pages/settings-page/components/desktop/ListeningHistory/index.ts
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Labels: size/M

#10993 [C-5557 C-5554] Guest checkout ui fixes
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
  packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
Labels: size/L

#11010 [C-5655] Fix the margin on the mobile profile screen tabs
  packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
Labels: size/XS

#10997 [C-5645] Migrate trending slice to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/comments.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/usePurchases.ts
  packages/common/src/api/tan-query/useSales.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/trending.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
Labels: size/L

#11017 Bump android to 1.1.462
  packages/mobile/android/app/build.gradle
Labels: size/XS

#11012 [PAY-3694] Update coinflow on web
  package-lock.json
  packages/web/package.json
  packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawModal.tsx
Labels: size/S

#11002 [PAY-3783] Update UI for Rewards page
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/pages/rewards-page/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/RewardsPage.tsx
  packages/web/src/pages/rewards-page/RewardsTile.module.css
  packages/web/src/pages/rewards-page/Tiers.module.css
  packages/web/src/pages/rewards-page/Tiers.tsx
  packages/web/src/pages/rewards-page/TrendingRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/StatusPill.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/hooks/useRewardIds.ts
  packages/web/src/pages/rewards-page/components/ClaimAllRewardsPanel.tsx
  packages/web/src/pages/rewards-page/components/TrendingRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/TrendingRewards/TrendingRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/TrendingRewards/hooks/useRewardIds.ts
  packages/web/src/pages/rewards-page/messages.tsx
Labels: size/XXL

#11022 [C-5658] Remove local saves slice from library
  packages/common/src/store/pages/saved-page/actions.ts
  packages/common/src/store/pages/saved-page/reducer.ts
  packages/common/src/store/pages/saved-page/selectors.ts
  packages/common/src/store/pages/saved-page/types.ts
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
  packages/mobile/src/store/offline-downloads/sagas/requestDownloadAllFavoritesSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/pages/saved/lineups/sagas.ts
  packages/web/src/common/store/social/collections/sagas.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
Labels: size/XL

#11021 Address bugbash comments
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/harmony/src/components/notification-count/NotificationCount.tsx
  packages/web/src/app/SvgGradientProvider.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/RestrictedExpandableNavItem.tsx
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
Labels: size/L

#11014 Mobile left nav drawer not scrollable
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
Labels: size/M

#11023 Rename to ClaimAllRewardsTile + fix padding
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/screens/rewards-screen/ClaimAllRewardsTile.tsx
  packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
Labels: size/S

#11016 [C-5641] Migrate library collections to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
Labels: size/L

#11027 [PAY-3796] Update nav top
  packages/harmony/src/assets/icons/AudiusLogoHorizontalNew.svg
  packages/harmony/src/icons/logos.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/NotificationsButton.tsx
Labels: size/L

#11029 [C-5657] Adopt standard useInfiniteQuery props
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/useAudioTransactions.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/usePurchases.ts
  packages/common/src/api/tan-query/useSales.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/hooks/chats/useAudienceUsers.ts
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/screens/user-list-screen/UserListV2.tsx
  packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
  packages/web/src/components/user-list-modal/components/lists/FollowersUserList.tsx
  packages/web/src/pages/audio-transactions-page/AudioWalletTransactions.tsx
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
  packages/web/src/pages/pay-and-earn-page/mobile/PayAndEarnPage.tsx
Labels: size/L

#11030 Fix playback in unauthenticated state
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/web/src/common/store/player/sagas.ts
Labels: size/L

#11032 Update amplitude key on staging & revert change to use gain2
  packages/common/src/services/env.ts
  packages/mobile/src/env/env.dev.ts
  packages/mobile/src/env/env.prod.ts
  packages/mobile/src/env/env.stage.ts
  packages/mobile/src/services/analytics.ts
  packages/web/src/services/env/env.dev.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
Labels: size/S

#11033 Fix missing comma in vector toml
  monitoring/vector/vector.toml
Labels: size/XS

#10959 Guest checkout QA fixes
  packages/common/src/audius-query/createApi.ts
  packages/common/src/hooks/purchaseContent/validation.ts
  packages/common/src/hooks/useFeatureFlag.ts
  packages/common/src/store/pages/saved-page/reducer.ts
  packages/common/src/utils/route.ts
  packages/discovery-provider/src/queries/get_users.py
  packages/identity-service/src/authMiddleware.js
  packages/mobile/src/screens/sign-on-screen/components/GuestEmailHint.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/premium-content-purchase-modal/pages/GuestCheckoutPage.tsx
  packages/web/src/hooks/useRequiresAccount.ts
  packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
  packages/web/src/pages/sign-in-page/SignInRootPage.tsx
  packages/web/src/pages/sign-on-page/GuestEmailHint.tsx
  packages/web/src/pages/sign-on-page/SignOnPage.tsx
  packages/web/src/pages/sign-up-page/components/EmailField.tsx
  packages/web/src/pages/sign-up-page/components/NewEmailField.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#11031 Remove z-index on edit form button row to not block the profile complete tooltip
  packages/web/src/components/edit/AnchoredSubmitRow.module.css
  packages/web/src/components/edit/AnchoredSubmitRowEdit.module.css
Labels: size/XS

#11024 [PAY-3794] New mobile rewards UI
  packages/harmony/src/assets/icons/Sparkles.svg
  packages/harmony/src/components/text/constants.ts
  packages/harmony/src/icons/UtilityIcons.stories.mdx
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/core/AccessTypeLabel.tsx
  packages/mobile/src/components/core/DogEar.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/edit/PriceAndAudienceField/SpecialAccessRadioField.tsx
  packages/mobile/src/components/progress-bar/ProgressBar.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/screens/rewards-screen/Panel.tsx
  packages/web/src/components/access-type-label/AccessTypeLabel.tsx
  packages/web/src/components/dog-ear/DogEar.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
  packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/LockedContentDetailsTile.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/dashboard-page/components/hooks.ts
  packages/web/src/pages/rewards-page/components/ChallengeRewards/StatusPill.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#11036 [PAY-3799] Re-add playlist update dot
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/harmony/src/components/nav-item/types.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Labels: size/S

#11039 [C-5542] Fix play counting bug on web track edits
  packages/web/src/components/edit-track/EditTrackForm.tsx
  packages/web/src/pages/edit-page/EditTrackPage.tsx
Labels: size/M

#11037 More mobile left nav drawer UI tweaks
  packages/harmony/src/assets/icons/AudiusLogoHorizontalNew.svg
  packages/harmony/src/foundations/color/semantic.ts
  packages/harmony/src/icons/Logos.stories.mdx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/VanityMetrics.tsx
  packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
Labels: size/M

#11018 Add back new privacy policy banner
  packages/web/public/documents/PrivacyPolicy.pdf
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/banner/CallToActionBanner.module.css
  packages/web/src/components/banner/CallToActionBanner.tsx
  packages/web/src/components/banner/TermsOfServiceUpdateBanner.tsx
Labels: size/S

#11034 [C-5668] Migrate remix page to tan-query
  packages/common/src/store/index.ts
  packages/common/src/store/pages/remixes/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/remix-settings/index.ts
  packages/common/src/store/remix-settings/selectors.ts
  packages/common/src/store/remix-settings/slice.ts
  packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/remixes-page/sagas.ts
  packages/web/src/common/store/remix-settings/sagas.ts
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/store/sagas.ts
Labels: size/L

#11035 [C-5669] Migrate track rank to tan-query
  packages/common/src/adapters/trending.ts
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useTrackRank.ts
  packages/common/src/models/Trending.ts
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/pages/track/reducer.ts
  packages/common/src/store/pages/track/selectors.ts
  packages/common/src/store/pages/track/types.ts
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/common/store/pages/track/sagas.ts
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/L

#11026 Update to solana 1.98.0
  .changeset/famous-bananas-poke.md
  package-lock.json
  packages/commands/package.json
  packages/common/package.json
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json
  packages/embed/package.json
  packages/identity-service/package.json
  packages/libs/package.json
  packages/mobile/package.json
  packages/sdk/package.json
  packages/sdk/rollup.config.ts
  packages/spl/package.json
  packages/web/package.json
Labels: size/M

#10961 Upgrade year in discovery notif tests
  packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/requestManager.ts
Labels: size/XS

#11042 [PAY-3792] Persist upload state between navigations
  packages/common/src/store/upload/actions.ts
  packages/common/src/store/upload/reducer.ts
  packages/common/src/store/upload/selectors.ts
  packages/common/src/store/upload/types.ts
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/forms/UploadCollectionForm.tsx
  packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
  packages/web/src/pages/upload-page/pages/EditPage.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
  packages/web/src/pages/upload-page/types.ts
Labels: size/L

#11040 Add revelator and clean up ddex-entrypoint
  .circleci/config.yml
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.ddex.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/config.json
  package-lock.json
  package.json
  packages/ddex-entrypoint/.env.dev
  packages/ddex-entrypoint/.env.prod
  packages/ddex-entrypoint/.env.stage
  packages/ddex-entrypoint/.eslintrc.cjs
  packages/ddex-entrypoint/.gitignore
  packages/ddex-entrypoint/README.md
  packages/ddex-entrypoint/gitignore
  packages/ddex-entrypoint/index.html
  packages/ddex-entrypoint/package.json
  packages/ddex-entrypoint/public/favicon.ico
  packages/ddex-entrypoint/public/logos/audiosalad.png
  packages/ddex-entrypoint/public/logos/fuga.png
  packages/ddex-entrypoint/src/App.tsx
  packages/ddex-entrypoint/src/assets/audius.png
  packages/ddex-entrypoint/src/components/ConnectDistributor.tsx
  packages/ddex-entrypoint/src/components/DistributorCard.tsx
  packages/ddex-entrypoint/src/components/DistributorsList.tsx
  packages/ddex-entrypoint/src/components/Footer.tsx
  packages/ddex-entrypoint/src/components/PreloadImage.tsx
  packages/ddex-entrypoint/src/components/RequestCard.tsx
  packages/ddex-entrypoint/src/components/Success.tsx
  packages/ddex-entrypoint/src/contexts/AuthProvider.tsx
  packages/ddex-entrypoint/src/contexts/types.ts
  packages/ddex-entrypoint/src/distributors/dev.json
  packages/ddex-entrypoint/src/distributors/prod.json
  packages/ddex-entrypoint/src/distributors/stage.json
  packages/ddex-entrypoint/src/hooks/useDistributors.ts
  packages/ddex-entrypoint/src/hooks/useSdk.ts
  packages/ddex-entrypoint/src/main.tsx
  packages/ddex-entrypoint/src/types/emotion.d.ts
  packages/ddex-entrypoint/src/types/vite-env.d.ts
  packages/ddex-entrypoint/tsconfig.json
  packages/ddex-entrypoint/tsconfig.node.json
  packages/ddex-entrypoint/vite.config.ts
  packages/ddex-entrypoint/wrangler.toml
  packages/ddex/.gitignore
  packages/ddex/.vscode/settings.json
  packages/ddex/entrypoint/src/components/DistributorsList.tsx
  packages/ddex/package-lock.json
  packages/harmony/src/icons/deprecatedIcons.ts
  packages/harmony/src/icons/logos.ts
  packages/harmony/src/icons/specialIcons.ts
  packages/harmony/src/icons/utilityIcons.ts
  scripts/get-release-dirs.sh
Labels: size/XXL

#11045 [PAY-3801] Update coinflow on mobile
  package-lock.json
  packages/mobile/package.json
  packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
Labels: size/XS

#11043 [C-5593] Migrate track pages to use tan-query fetches
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useTrackByParams.ts
  packages/common/src/store/pages/track/actions.ts
  packages/common/src/store/pages/track/selectors.ts
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/app/App.tsx
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/track/sagas.ts
  packages/web/src/pages/react-query/ReactQueryReduxCacheSyncPage.tsx
  packages/web/src/pages/track-page/DesktopServerTrackPage.tsx
  packages/web/src/pages/track-page/MobileServerTrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/ssr/track/+onRenderHtml.tsx
Labels: size/XL

#11048 [C-5673] Migrate user pages to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useUserByParams.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/XL

#11046 Address navbar nits
  packages/common/src/assets/img/imageProfilePicEmpty.png
  packages/common/src/assets/index.ts
  packages/harmony/src/components/balance-pill/BalancePill.tsx
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/harmony/src/components/scrollbar/Scrollbar.module.css
  packages/harmony/src/utils/index.ts
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/NavItemKebabButton.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/RestrictedExpandableNavItem.tsx
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
Labels: size/L

#11051 [PAY-3809] Fix bad claim all format on mobile web
  packages/web/src/pages/rewards-page/RewardsPage.module.css
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/ClaimAllRewardsPanel.tsx
Labels: size/XS

#11049 Use PNG icons on web left nav
  package-lock.json
  packages/harmony/package.json
  packages/harmony/rollup.config.mjs
  packages/harmony/src/assets/icons/LogoCircleUSDC.png
  packages/harmony/src/icons/logos.ts
  packages/harmony/src/icons/specialIcons.ts
  packages/harmony/src/utils/createImageIcon.tsx
  packages/web/src/components/artist/ArtistCardCover.tsx
  packages/web/src/components/audio-balance-pill/AUDIOBalancePill.module.css
  packages/web/src/components/audio-balance-pill/AUDIOBalancePill.tsx
  packages/web/src/components/nav/desktop/NavHeader.tsx
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
  packages/web/src/components/track/AiTrackSection.tsx
  packages/web/src/components/usdc-balance-pill/USDCBalancePill.module.css
  packages/web/src/components/usdc-balance-pill/USDCBalancePill.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/dashboard-page/components/ArtistCard.tsx
  packages/web/src/pages/profile-page/components/EditableName.tsx
Labels: size/L

#11052 [PAY-3806] Show NowPlaying indicator on left nav items
  packages/common/src/store/queue/types.ts
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/components/nav/desktop/useNavSourcePlayingStatus.ts
Labels: size/L

#11053 [PAY-3807] Show folder kebab when open
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
Labels: size/S

#11057 [PAY-3812] Fix balance display in nav
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
Labels: size/XS

#11055 [PAY-3803] Fix web nav item hover/active states
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/expandable-nav-item/types.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
Labels: size/L

#11058 [PAY-3808] Add proper spacing for sub item
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/harmony/src/components/nav-item/types.ts
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
Labels: size/M

#11061 Add analytics on nav link clicks
  packages/common/src/models/Analytics.ts
  packages/web/src/components/nav/desktop/LeftNavLink.tsx
Labels: size/S

#11060 Refactor route matching logic and fix logged out disable state
  packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
  packages/harmony/src/components/nav-item/NavItem.tsx
  packages/web/src/components/nav/desktop/NavSpeakerIcon.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#11063 [QA-1917] Conditional render for dashboard button
  packages/web/src/components/nav/desktop/NavHeader.tsx
Labels: size/S

#10989 [PAY-3548] Split account metadata out of user metadata
  packages/common/src/adapters/user.ts
  packages/common/src/api/user.ts
  packages/common/src/models/Track.ts
  packages/common/src/models/User.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/account/index.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/selectors.ts
  packages/common/src/store/account/slice.ts
  packages/common/src/store/account/types.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/challenges/selectors/profile-progress.ts
  packages/common/src/store/playlist-library/selectors.ts
  packages/mobile/ios/Podfile.lock
  packages/web/src/common/store/pages/saved/lineups/sagas.ts
  packages/web/src/common/store/pages/saved/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/playlist-library/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/pages/audio-rewards-page/WalletModal.tsx
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/L

#11054 [C-5675] Migrate collection page to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useCollectionByParams.ts
  packages/common/src/models/Collection.ts
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/store/pages/collection/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
  packages/mobile/src/screens/collection-screen/useHasCollectionChanged.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/EntityLink.tsx
  packages/mobile/src/screens/notifications-screen/Notification/utils.ts
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/store/cache/collections/createPlaylistRequestedSaga.ts
  packages/web/src/common/store/cache/collections/utils/index.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/collection/lineups/sagas.js
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/XL

#11065 Fix restriction
  packages/web/src/components/nav/desktop/useNavConfig.tsx
Labels: size/XS

#11066 fix should index plays check
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/XS

#11067 Add missing query params
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
Labels: size/XS

#11068 Always include preview url if necessary (even when logged out)
  packages/discovery-provider/src/queries/query_helpers.py
Labels: size/S
