Repository AudiusProject/apps, pull requests merged in 2025-06, with the labels that each got.

#12250 [PE-6288] Use tan-query useUSDCBalance everywhere
  packages/common/src/api/tan-query/wallets/useUSDCBalance.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/usePurchaseMethod.ts
  packages/common/src/hooks/useUSDCBalance.ts
  packages/mobile/src/components/add-funds-drawer/CashBalanceSection.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/hooks/usePurchaseContentFormState.ts
  packages/mobile/src/components/usdc-balance-row/USDCBalanceRow.tsx
  packages/mobile/src/harmony-native/components/BalancePill/BalancePill.tsx
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
  packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx
  packages/web/src/components/add-cash/AddCash.tsx
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
  packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseContentFormState.ts
  packages/web/src/components/premium-content-purchase-modal/pages/PurchaseContentPage.tsx
  packages/web/src/components/usdc-balance-fetcher/USDCBalanceFetcher.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ErrorPage.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/L

#12255 [QA-2131] Fix library page infinite spinning
  packages/common/src/api/tan-query/collection/useCollections.ts
  packages/common/src/api/tan-query/tracks/useTracks.ts
  packages/common/src/api/tan-query/users/useUsers.ts
Labels: size/S

#12251 Track upload notification test
  packages/web/src/components/notification/Notification/UserSubscriptionNotification.test.tsx
Labels: size/L

#12257 Add karma to user scores
  packages/discovery-provider/ddl/functions/get_user_scores.sql
Labels: size/XS

#12259 Fix playlist nav 404s
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
Labels: size/S

#12262 [QA-2112] Fix max lines prop spreading
  packages/web/src/components/link/TrackLink.tsx
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Labels: size/XS

#12261 [PE-6249] Improve artwork loading animation
  packages/harmony/src/components/artwork/Artwork.tsx
Labels: size/XS

#12258 Add search dropdown scrollbar
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
Labels: size/S

#12266 Fix track link
  packages/web/src/components/link/TrackLink.tsx
Labels: size/XS

#12268 [PE-6257] Web coinflow withdraw UI updates
  packages/common/src/messages/walletMessages.ts
  packages/web/src/components/add-cash/CashBalanceSection.tsx
  packages/web/src/components/tooltip/Tooltip.module.css
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
Labels: size/M

#12270 [PE-6318] Fix album embed
  packages/web/src/components/embed-modal/EmbedModal.tsx
Labels: size/XS

#12272 Fix playlists disappearing when stale & lots of user fetches
  packages/common/src/api/tan-query/batchers/getCollectionsBatcher.ts
  packages/common/src/api/tan-query/collection/useCollection.ts
  packages/common/src/api/tan-query/collection/useCollections.ts
  packages/common/src/api/tan-query/saga-utils/queryTrack.ts
  packages/common/src/api/tan-query/saga-utils/queryUser.ts
  packages/common/src/api/tan-query/tracks/useTrack.ts
  packages/common/src/api/tan-query/tracks/useTracks.ts
  packages/common/src/api/tan-query/users/useUser.ts
  packages/common/src/api/tan-query/users/useUsers.ts
  packages/common/src/api/tan-query/utils/entityCacheOptions.ts
Labels: size/M

#12264 [API-185] Update DN trending to follow the same logic as bridge
  packages/discovery-provider/integration_tests/tasks/test_index_trending.py
  packages/discovery-provider/integration_tests/tasks/test_index_trending_notification.py
  packages/discovery-provider/integration_tests/tasks/test_index_trending_playlist_notifications.py
  packages/discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
  packages/discovery-provider/integration_tests/tasks/test_trending_playlist_notifications.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/queries/generate_unpopulated_trending_tracks.py
  packages/discovery-provider/src/queries/get_premium_tracks.py
  packages/discovery-provider/src/queries/get_recommended_tracks.py
  packages/discovery-provider/src/queries/get_trending_ids.py
  packages/discovery-provider/src/queries/get_trending_playlists.py
  packages/discovery-provider/src/queries/get_trending_tracks.py
  packages/discovery-provider/src/queries/get_underground_trending.py
  packages/discovery-provider/src/tasks/cache_trending_playlists.py
  packages/discovery-provider/src/tasks/index_trending.py
  packages/discovery-provider/src/trending_strategies/pnagD_underground_trending_tracks_strategy.py
  packages/discovery-provider/src/trending_strategies/trending_strategy_factory.py
Labels: size/XXL

#12274 Fix accountCollection is undefined
  packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
Labels: size/S

#12278 [PE-6323] Pass track artwork and genre to upload form for remix contest entries
  packages/mobile/src/screens/track-screen/UploadRemixFooter.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
Labels: size/M

#12279 [PE-6325] Fix upload instability due to stale data
  packages/common/src/api/tan-query/saga-utils/queryTrack.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#12277 Update tipping flow balance loading state
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
Labels: size/M

#12281 [PE-6320] Update remixes page to display winners in the submissions section
  packages/common/src/api/tan-query/remixes/useRemixesLineup.ts
Labels: size/XS

#12282 [PE-6324] Skip select upload type step when submitting to contest
  packages/web/src/pages/upload-page/UploadPage.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
Labels: size/M

#12286 Update mobile to take remix contest image when submitting
  packages/mobile/src/screens/track-screen/UploadRemixFooter.tsx
Labels: size/M

#12289 [PE-6339] (account fix) Fix mobile app taking you to sign up when signed in
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/XS

#12293 Add search functionality to mobile explore
  packages/harmony/src/assets/icons/Bell.svg
  packages/harmony/src/assets/icons/CloudUp.svg
  packages/harmony/src/assets/icons/Feed.svg
  packages/harmony/src/assets/icons/Gift.svg
  packages/harmony/src/assets/icons/Library.svg
  packages/harmony/src/assets/icons/Messages.svg
  packages/harmony/src/assets/icons/Playlists.svg
  packages/harmony/src/assets/icons/Search.svg
  packages/harmony/src/assets/icons/Trending.svg
  packages/harmony/src/assets/icons/Wallet.svg
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/ExploreButton.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/animations/iconFeed.lottie
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/animations/iconLibrary.lottie
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/animations/iconNotifications.lottie
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/animations/iconSearchExplore.lottie
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/animations/iconTrending.lottie
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
Labels: size/L

#12292 (account fix) Fix left nav not showing
  packages/common/src/api/tan-query/users/account/useAccountStatus.ts
  packages/common/src/store/account/sagas.ts
Labels: size/S

#12288 Fix library loading
  packages/common/src/adapters/collection.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/TracksTab.tsx
  packages/mobile/src/screens/favorites-screen/useLibraryCollections.ts
Labels: size/L

#12290 [PE-6181] Mobile withdraw flow
  packages/common/src/messages/walletMessages.ts
  packages/common/src/store/sagas.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/withdraw-usdc/sagas.ts
  packages/common/src/store/wallet/utils.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/assets/images/emojis/raised-hand.png
  packages/mobile/src/components/coinflow-withdraw-drawer/CoinflowWithdrawDrawer.tsx
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/drawer/Drawer.tsx
  packages/mobile/src/components/loading-spinner/LoadingSpinner.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/WithdrawUSDCDrawer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CoinflowConfirmTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CoinflowWithdrawPage.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CryptoConfirmTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/EnterTransferDetails.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/ErrorPage.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/PrepareTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/TransferInProgress.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/TransferSuccessful.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/index.ts
  packages/mobile/src/components/withdraw-usdc-drawer/types.ts
  packages/mobile/src/screens/wallet-screen/components/CashWallet.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.tsx
  packages/web/src/pages/audio-page/components/SendInputBody.tsx
  packages/web/src/services/solana/solana.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#12296 [PE-6335] Address mobile wallet UI M2 QA finds
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/api/tan-query/jupiter/utils.ts
  packages/common/src/store/ui/buy-sell/useTokenAmountFormatting.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/mobile/src/components/buy-sell/TokenAmountSection.tsx
  packages/mobile/src/components/core/FixedFooter.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/screens/app-screen/AppScreen.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellModalScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/ConfirmSwapScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/TransactionResultScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/index.ts
  packages/mobile/src/screens/wallet-screen/WalletScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
  packages/web/src/components/buy-sell-modal/hooks/useTokenAmountFormatting.ts
Labels: size/XL

#12299 Fix mobile web track artwork loading
  packages/web/src/components/track/TrackArtwork.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/M

#12263 [PE-6143] Fix comment reaction indexing
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Labels: size/M

#12297 [PE-6245 PE-6246] Fix mobile/web drawer behavior
  packages/web/src/components/add-cash-modal/AddCashModal.module.css
  packages/web/src/components/add-cash-modal/AddCashModal.tsx
  packages/web/src/components/add-cash/AddCash.module.css
  packages/web/src/components/add-cash/AddCash.tsx
  packages/web/src/components/modal-drawer/ModalDrawer.tsx
  packages/web/src/components/modal/ResponsiveModal.tsx
  packages/web/src/components/modal/ResponsiveModalContent.tsx
  packages/web/src/components/modal/index.ts
Labels: size/L

#12301 Fix mobile upload stuck at 100%
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Labels: size/S

#12305 Fix missing track in upload complete screen
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/S

#12304 [PE-6379] Fix refetching collection by permalink
  packages/common/src/api/tan-query/collection/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/saga-utils/queryCollection.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/M

#12209 Update bundler version to fix android builds
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#12311 Improve feature flag performance
  packages/common/src/hooks/useFeatureFlag.ts
  packages/common/src/hooks/useRemoteVar.ts
Labels: size/M

#12313 [PE-6224] Refactor mobile lineup-tiles for simplicity and performance
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileArt.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/index.ts
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/XL

#12314 Refactor mobile left nav drawer to improve performance
  packages/common/src/api/tan-query/users/account/accountSelectors.ts
  packages/common/src/context/comments/commentsHooks.ts
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/common/src/hooks/useAccountHasClaimableRewards.ts
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/common/src/hooks/useCanSendChatBlast.ts
  packages/common/src/store/wallet/utils.ts
  packages/mobile/src/components/edit/VisibilityField/VisibilityScreen.tsx
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/components/track-flair/TrackFlair.tsx
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/hooks/useRemoteConfig.ts
  packages/mobile/src/hooks/useUpdateRequired.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/FeatureFlagsNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/LeftNavDrawer.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/MessagesNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/ProfileNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/RewardsNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/SettingsNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/UploadNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/WalletNavItem.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/nav-items/index.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentMentionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentThreadNotification.tsx
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
  packages/mobile/src/screens/rewards-screen/TrendingRewardsTile.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/mobile/src/screens/tip-artist-screen/DegradationNotice.tsx
  packages/mobile/src/screens/tip-artist-screen/SupporterPrompt.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
  packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
  packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
  packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/track/TrackStats.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/XL

#12320 QA fixes for mobile explore: reseting search params and scroll + more
  packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/collections.ts
  packages/mobile/src/screens/explore-screen/components/ColorTile.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
  packages/mobile/src/screens/search-screen/BpmFilter.tsx
  packages/mobile/src/screens/search-screen/SearchCategoriesAndFilters.tsx
  packages/mobile/src/screens/search-screen/SearchFilters.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
Labels: size/L

#12310 Stop error message flash on sell tab of Buy/Sell
  packages/common/src/store/ui/buy-sell/swapFormSchema.ts
  packages/common/src/store/ui/buy-sell/useBuySellTransactionData.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/mobile/src/screens/buy-sell-screen/components/BuyScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SellScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
Labels: size/M

#12324 [QA-2138] Remove max-width on playlist tiles for mobile web
  packages/web/src/components/track/mobile/PlaylistTile.module.css
Labels: size/XS

#12327 More withdraw UI cleanup
  packages/common/src/hooks/useFormattedUSDCBalance.ts
  packages/common/src/messages/walletMessages.ts
  packages/mobile/src/components/add-funds-drawer/CashBalanceSection.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/WithdrawUSDCDrawer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CoinflowConfirmTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/ErrorPage.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/TransferSuccessful.tsx
  packages/web/src/components/add-cash/AddCash.tsx
  packages/web/src/components/add-cash/CashBalanceSection.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawPage.module.css
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawPage.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ErrorPage.module.css
  packages/web/src/components/withdraw-usdc-modal/components/ErrorPage.tsx
  packages/web/src/components/withdraw-usdc-modal/components/Hint.module.css
  packages/web/src/components/withdraw-usdc-modal/components/Hint.tsx
  packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.module.css
  packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TextRow.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TextRow.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Labels: size/L

#12328 Add avoidable keyboard to buy/sell flow
  packages/mobile/src/components/core/FixedFooter.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellScreen.tsx
Labels: size/M

#12321 [PE-6389] Explore screen refactor and performance
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ArtistSpotlight.tsx
  packages/mobile/src/screens/explore-screen/components/BestOfAudiusTiles.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreSection.tsx
  packages/mobile/src/screens/explore-screen/components/FeaturedPlaylists.tsx
  packages/mobile/src/screens/explore-screen/components/FeaturedRemixContests.tsx
  packages/mobile/src/screens/explore-screen/components/LabelSpotlight.tsx
  packages/mobile/src/screens/explore-screen/components/MoodsGrid.tsx
  packages/mobile/src/screens/explore-screen/components/ProgressiveScrollView.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
  packages/mobile/src/screens/explore-screen/components/SearchInput.tsx
  packages/mobile/src/screens/search-screen/RecentSearches.tsx
  packages/mobile/src/screens/search-screen/SearchScreen.tsx
  packages/mobile/src/screens/search-screen/searchState.tsx
Labels: size/XXL

#12330 Fix guest account check for home page routing
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/S

#12333 Revert "Update bundler version to fix android builds"
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#12336 Misc staging fixes (integration-test)
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/common/src/context/comments/commentsHooks.ts
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/common/src/hooks/useCanSendChatBlast.ts
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentMentionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentThreadNotification.tsx
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
  packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
  packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
  packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/track/TrackStats.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
Labels: size/L

#12340 Fix album edit crashing - use playlist_contents for trackIds
  packages/common/src/api/tan-query/batchers/getCollectionsBatcher.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
Labels: size/M

#12334 Add trending experiment for log(karma)
  packages/discovery-provider/src/trending_strategies/AnlGe_trending_tracks_strategy.py
  packages/discovery-provider/src/trending_strategies/trending_strategy_factory.py
  packages/discovery-provider/src/trending_strategies/trending_type_and_version.py
Labels: size/L

#12341 [QA-2148] Fix album track reorder, improve edit-collection loading
  packages/common/src/adapters/collection.ts
  packages/sdk/src/sdk/api/albums/types.ts
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/collections/createAlbumSaga.ts
  packages/web/src/common/store/upload/sagas.ts
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
  packages/web/src/pages/edit-collection-page/utils.ts
Labels: size/M

#12344 [QA-2155] Fix mobile tastemaker notif
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestSubmissionsNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
Labels: size/M

#12343 [PE-6393] Normalize users in the wallet account slices & dep redundant hooks
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/hooks/chats/useFirstAvailableBlastAudience.ts
  packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/common/src/store/account/sagas.ts
  packages/mobile/src/components/drawers/ArtistPickConfirmationDrawer.tsx
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
Labels: size/L

#12353 [QA-2147] Fix user link with popover height
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/link/UserLink.tsx
Labels: size/S

#12338 Fix missing permalink runtime issue in upload complete screen
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Labels: size/S

#12347 Update tip flows to use fixed-decimal
  packages/common/src/hooks/useSupporterPrompt.ts
  packages/common/src/hooks/useUIAudio.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/wallet-client/WalletClient.ts
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/utils.ts
  packages/common/src/utils/wallet.ts
  packages/harmony/src/components/input/TokenAmountInput/TokenAmountInput.stories.tsx
  packages/harmony/src/components/input/TokenAmountInput/TokenAmountInput.tsx
  packages/harmony/src/components/input/TokenAmountInput/types.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
  packages/mobile/src/screens/rewards-screen/TiersTile.tsx
  packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SupporterPrompt.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/artist/ArtistChipSupportFor.tsx
  packages/web/src/components/artist/ArtistChipSupportFrom.tsx
  packages/web/src/components/buy-audio-modal/components/AudioAmountPicker.tsx
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/SupporterPrompt.tsx
  packages/web/src/components/token-value-slider/TokenValueSlider.tsx
  packages/web/src/components/token-value-slider/types.ts
  packages/web/src/pages/audio-page/WalletModal.tsx
  packages/web/src/pages/audio-page/components/DashboardTokenValueSlider.tsx
  packages/web/src/pages/audio-page/components/SendInputBody.tsx
  packages/web/src/pages/audio-page/components/SendInputConfirmation.tsx
  packages/web/src/pages/audio-page/components/SendInputSuccess.tsx
  packages/web/src/pages/audio-page/components/SendingModalBody.tsx
  packages/web/src/pages/audio-page/components/WalletManagementTile.tsx
  packages/web/src/pages/rewards-page/Tiers.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
  packages/web/src/store/token-dashboard/sagas.ts
Labels: size/XL

#12339 Improve search input performance, collapse on search + more
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/components/remix-carousel/RemixContestCard.tsx
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ProgressiveScrollView.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
  packages/mobile/src/screens/search-screen/RecentSearches.tsx
  packages/mobile/src/screens/search-screen/SearchItem.tsx
  packages/mobile/src/screens/search-screen/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen/searchState.tsx
Labels: size/L

#12371 [API-166] Add recently listed premium tracks API to SDK
  .changeset/fifty-parrots-repeat.md
  packages/discovery-provider/src/api/v1/tracks.py
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/TracksApi.ts
Labels: size/L

#12372 Update calculation to use fixed decimal
  packages/common/src/services/Jupiter.ts
Labels: size/XS

#12359 [PE-6391] Actually fix confetti this time (localstorage account data issue)
  packages/common/src/api/tan-query/users/account/useCurrentAccount.ts
  packages/common/src/api/tan-query/users/account/useSyncLocalStorageUser.tsx
  packages/common/src/store/account/sagas.ts
Labels: size/M

#12366 Improve play bar performance
  packages/common/src/hooks/useCurrentTrack.ts
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
  packages/web/src/components/play-bar/VolumeBar.jsx
  packages/web/src/components/play-bar/desktop/PlayBar.jsx
  packages/web/src/components/play-bar/desktop/PlayBar.tsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/play-bar/repeat-button/RepeatButtonProvider.tsx
  packages/web/src/components/play-bar/shuffle-button/ShuffleButtonProvider.tsx
  packages/web/src/utils/theme/theme.ts
Labels: size/XL

#12367 Improve desktop left-nav performance
  packages/common/src/store/search/selectors.ts
  packages/web/src/components/nav/Navigator.tsx
  packages/web/src/components/nav/desktop/LeftNav.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/usePlaylistPlayingStatus.ts
  packages/web/src/components/nav/desktop/RestrictedExpandableNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/DevToolsNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/ExploreNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/FeedNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/LibraryNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/MessagesNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/PlaylistsNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/RewardsNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/TrendingNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/UploadNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/WalletNavItem.tsx
  packages/web/src/components/nav/desktop/nav-items/index.ts
  packages/web/src/components/nav/desktop/useNavConfig.tsx
Labels: size/XL

#12364 [QA-1680] Fix shuffle order generation
  packages/common/src/store/queue/slice.test.ts
  packages/common/src/store/queue/slice.ts
Labels: size/L

#12373 Upgrade android build in prep for next release
  packages/mobile/android/app/build.gradle
Labels: size/XS

#12379 [QA-1985] Remove multiselect prop to fix upload tag delete on click functionality
  packages/web/src/components/data-entry/TagInput.jsx
Labels: size/XS

#12378 Refactor TrendingPageProvider to funcitonal component
  CLAUDE.md
  packages/web/src/pages/trending-page/TrendingPageProvider.jsx
  packages/web/src/pages/trending-page/TrendingPageProvider.tsx
  packages/web/src/pages/trending-page/constants.ts
  packages/web/src/pages/trending-page/hooks/useTrendingActions.ts
  packages/web/src/pages/trending-page/hooks/useTrendingLineups.ts
  packages/web/src/pages/trending-page/hooks/useTrendingPageCleanup.ts
  packages/web/src/pages/trending-page/hooks/useTrendingPageState.ts
  packages/web/src/pages/trending-page/hooks/useTrendingUrlParams.ts
  packages/web/src/pages/trending-page/providerTypes.ts
  packages/web/src/pages/trending-page/selectors.ts
  packages/web/src/pages/trending-page/utils.ts
Labels: size/XXL

#12377 [QA-2166] Fix broken mobile playback
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/XS

#12349 [PE-6403] Fix mobile library radio buttons not working
  packages/mobile/src/screens/library-screen/useFavoritesLineup.ts
Labels: size/XS

#12375 Optimize search and explore performance + animation
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/BestOfAudiusTiles.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreSection.tsx
  packages/mobile/src/screens/explore-screen/components/ProgressiveScrollView.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Labels: size/L

#12381 [API-167][API-229] Add user recommend tracks to sdk and fix urls for other explore endpoints
  .changeset/strong-spies-hope.md
  packages/discovery-provider/src/api/v1/explore.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/api/v1/users.py
  packages/sdk/src/sdk/api/generated/default/apis/ExploreApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/ExploreApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
Labels: size/L

#12382 [PE-6383] Fix ATA of ATA bug in withdraw flow
  packages/common/src/services/audius-backend/solana.ts
Labels: size/M

#12383 Increase aao override score
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/sdk.ts
Labels: size/M

#12384 [PE-6419|PE-6434] Fix flash of sign up on mobile apps due to default account status
  packages/common/src/api/tan-query/users/account/useAccountStatus.ts
Labels: size/XS

#12392 [PE-6435] Fix selectable pill isSelected color
  packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
Labels: size/S

#12393 [PE-6432] Reduce mobile web explore page tiles
  packages/web/src/pages/explore-page/components/mobile/ColorTile.module.css
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Labels: size/S

#12390 [QA-2160 PE-6438] Fix Android icon colors
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
  packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
Labels: size/M

#12389 [PE-6427] Fix play bar duration
  packages/web/src/components/play-bar/desktop/PlayBar.tsx
Labels: size/M

#12396 Fix header snapping and improve content scrolling
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Labels: size/L

#12397 Add retries on swaps
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellModalScreen.tsx
  packages/mobile/src/types/navigation.ts
Labels: size/L

#12399 Add reactotron for RN network debugging
  packages/mobile/.eslintrc.js
  packages/mobile/REACTOTRON_SETUP.md
  packages/mobile/README.md
  packages/mobile/ReactotronConfig.js
  packages/mobile/index.js
  packages/mobile/package.json
Labels: size/L

#12401 [PE-6436] Fix mobile withdraw flow scrolling and validation
  packages/common/src/store/ui/withdraw-usdc/schema.ts
  packages/mobile/src/components/core/SegmentedControl.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/WithdrawUSDCDrawer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CoinflowConfirmTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/CryptoConfirmTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/EnterTransferDetails.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/ErrorPage.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/PrepareTransfer.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/components/TransferSuccessful.tsx
  packages/mobile/src/components/withdraw-usdc-drawer/types.ts
Labels: size/L

#12404 [PE-6441] Fix create new collection
  packages/web/src/common/store/cache/collections/createAlbumSaga.ts
  packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/S

#12400 [PE-6433] Fix signed out search
  packages/common/src/api/tan-query/search/useSearchResults.ts
  packages/mobile/src/screens/explore-screen/components/BestOfAudiusTiles.tsx
  packages/web/e2e/search.test.ts
Labels: size/M

#12406 [PE-6431] Fix extra user/handle API calls
  packages/common/src/api/tan-query/batchers/getUsersBatcher.ts
  packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
  packages/common/src/api/tan-query/users/useUserAlbums.ts
  packages/common/src/api/tan-query/users/useUserByHandle.ts
  packages/common/src/api/tan-query/users/useUserCollectibles.ts
  packages/common/src/api/tan-query/users/useUserPlaylists.ts
  packages/common/src/api/tan-query/users/useUserTracksByHandle.ts
Labels: size/S

#12412 [PE-6450] Fix mobile audio balance formatting
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Labels: size/M

#12414 Update AudioBreakdownDrawer to use balance hooks and harmony
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx
Labels: size/L

#12417 [QA-2184] Fix double $ signs in purchase flow
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
Labels: size/XS

#12419 Fix another incorrect instance of waitForValue
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XS

#12422 Drop search test
  packages/web/e2e/search.test.ts
Labels: size/S

#12421 Use prime functions for entity updates
  packages/common/src/api/tan-query/collection/useUpdateCollection.ts
  packages/common/src/api/tan-query/tracks/useFavoriteTrack.ts
  packages/common/src/api/tan-query/tracks/useUnfavoriteTrack.ts
  packages/common/src/api/tan-query/tracks/useUpdateTrack.ts
  packages/common/src/api/tan-query/users/useFollowUser.ts
  packages/common/src/api/tan-query/users/useUnfollowUser.ts
  packages/common/src/api/tan-query/users/useUpdateUser.ts
  packages/common/src/api/tan-query/utils/updateCollectionData.ts
  packages/common/src/api/tan-query/utils/updateTrackData.ts
Labels: size/L

#12423 [HOTFIX] Fix manager mode not letting you swap from managee
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/common/src/store/account/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
Labels: size/L

#12415 Add analytics to Buy/Sell flow
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useAnalytics.ts
  packages/common/src/hooks/useBuySellAnalytics.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/ui/buy-sell/types.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/common/src/store/ui/buy-sell/useSwapDisplayData.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/ConfirmSwapScreen.tsx
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/ConfirmSwapScreen.tsx
Labels: size/XL

#12425 Prime search results to improve autocomplete performance
  packages/common/src/adapters/search.ts
  packages/common/src/api/tan-query/search/useSearchAutocomplete.ts
  packages/common/src/api/tan-query/search/useSearchResults.ts
Labels: size/L

#12424 [PE-6452] Refactor web lineup tiles
  packages/web/src/components/collection/CollectionTileStats.tsx
  packages/web/src/components/lineup/Lineup.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/track/ViewerActionButtons.module.css
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/desktop/ConnectedPlaylistTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.module.css
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.module.css
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.module.css
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/desktop/TrackTileDuration.module.css
  packages/web/src/components/track/desktop/TrackTileDuration.tsx
  packages/web/src/components/track/mobile/CollectionTile.tsx
  packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
Labels: size/XXL

#12427 [PE-6455] Migrate all wallet balance reads to tan-query
  packages/common/src/api/tan-query/notifications/useNotificationUnreadCount.ts
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/common/src/api/tan-query/wallets/useConnectedWallets.ts
  packages/common/src/store/wallet/index.ts
  packages/common/src/store/wallet/selectors.ts
  packages/common/src/store/wallet/slice.ts
  packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
  packages/mobile/src/screens/audio-screen/AudioScreen.tsx
  packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/pages/audio-page/AudioPage.tsx
  packages/web/src/pages/audio-page/WalletModal.tsx
  packages/web/src/pages/audio-page/components/WalletManagementTile.tsx
  packages/web/src/pages/audio-page/components/modals/AudioBreakdownModal.tsx
  packages/web/src/pages/dashboard-page/store/sagas.ts
  packages/web/src/pages/rewards-page/RewardsPage.tsx
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/XL

#12429 [PE-6461] Change Twitter share button to X
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useTwitterButtonStatus.ts
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
  packages/web/src/components/ai-attribution-modal/SearchBarResult.module.css
  packages/web/src/components/ai-attribution-modal/SearchBarResult.tsx
  packages/web/src/components/notification/Notification/AddTrackToPlaylistNotification.tsx
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/components/notification/Notification/MilestoneNotification.tsx
  packages/web/src/components/notification/Notification/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/SupporterDethronedNotification.tsx
  packages/web/src/components/notification/Notification/TastemakerNotification.tsx
  packages/web/src/components/notification/Notification/TierChangeNotification.tsx
  packages/web/src/components/notification/Notification/TipReactionNotification.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
  packages/web/src/components/notification/Notification/TipSentNotification.tsx
  packages/web/src/components/notification/Notification/TopSupporterNotification.tsx
  packages/web/src/components/notification/Notification/TopSupportingNotification.tsx
  packages/web/src/components/notification/Notification/TrendingPlaylistNotification.tsx
  packages/web/src/components/notification/Notification/TrendingTrackNotification.tsx
  packages/web/src/components/notification/Notification/TrendingUndergroundNotification.tsx
  packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
  packages/web/src/components/notification/Notification/components/NotificationFooter.tsx
  packages/web/src/components/notification/Notification/components/NotificationHeader.tsx
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
  packages/web/src/components/notification/Notification/components/TwitterShareButton.module.css
  packages/web/src/components/notification/Notification/components/TwitterShareButton.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/components/ShareDialog.tsx
  packages/web/src/components/share-modal/components/ShareDrawer.tsx
  packages/web/src/components/share-modal/messages.ts
  packages/web/src/components/share-modal/types.ts
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/components/twitter-share-button/TwitterShareButton.tsx
  packages/web/src/components/x-share-button/XShareButton.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/XL

#12433 Remove extra dollar signs
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/XS

#12434 Fix more double dollar signs
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/XS

#12437 [QA-2188] Fix sign out not working
  packages/mobile/src/store/sign-out/sagas.ts
  packages/web/src/store/sign-out/sagas.ts
Labels: size/S

#12435 [PE-6464] Mobile change twitter to x
  packages/common/src/utils/index.ts
  packages/common/src/utils/route.ts
  packages/common/src/utils/twitter.ts
  packages/common/src/utils/xShare.ts
  packages/mobile/src/components/challenge-rewards-drawer/ReferralChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/TwitterShareButton.tsx
  packages/mobile/src/components/challenge-rewards-drawer/XShareButton.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/mobile/src/components/share-drawer/messages.ts
  packages/mobile/src/components/share-drawer/utils.ts
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/mobile/src/components/twitter-button/TwitterButton.tsx
  packages/mobile/src/components/twitter-button/index.ts
  packages/mobile/src/components/x-button/XButton.tsx
  packages/mobile/src/components/x-button/index.ts
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.stories.tsx
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
  packages/mobile/src/harmony-native/components/Button/SocialButton/types.ts
  packages/mobile/src/harmony-native/icons.tsx
  packages/mobile/src/screens/edit-profile-screen/EditProfileScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationTwitterButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/NotificationXButton.tsx
  packages/mobile/src/screens/notifications-screen/Notification/index.ts
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/SupporterDethronedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipSentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingPlaylistNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingTrackNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TrendingUndergroundNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SocialsAndSites.tsx
  packages/mobile/src/screens/settings-screen/AboutScreen.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/components/x-share-button/XShareButton.tsx
  packages/web/src/pages/settings-page/components/mobile/AboutSettingsPage.tsx
  packages/web/src/public-site/components/Footer.tsx
  packages/web/src/public-site/components/NavOverlay.tsx
  packages/web/src/utils/tweet.ts
  packages/web/src/utils/xShare.ts
Labels: size/XL
