Repository AudiusProject/apps, pull requests merged in 2025-02, with the labels that each got.

#11220 [C-5733] Migrate history-page to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useFeed.ts
  packages/common/src/api/tan-query/usePremiumTracks.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/tan-query/useTrendingPlaylists.ts
  packages/common/src/api/tan-query/useTrendingUnderground.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/mobile/src/components/filter-input/FilterInput.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/web/src/common/store/pages/history/lineups/sagas.ts
  packages/web/src/components/lineup/hooks.ts
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/components/tracks-table/index.ts
  packages/web/src/components/tracks-table/types.ts
  packages/web/src/pages/history-page/HistoryPage.tsx
  packages/web/src/pages/history-page/HistoryPageProvider.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.module.css
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Labels: size/XXL

#11223 [PAY-3857] Replace cognito verification with plaid
  package-lock.json
  packages/common/src/services/auth/identity.ts
  packages/identity-service/package.json
  packages/identity-service/src/cognitoFlowMiddleware.js
  packages/identity-service/src/config.js
  packages/identity-service/src/models/cognitoFlowIdentities.js
  packages/identity-service/src/models/cognitoFlows.js
  packages/identity-service/src/routes/cognito.js
  packages/identity-service/src/routes/plaid.js
  packages/identity-service/src/utils/cognitoHelpers.js
  packages/identity-service/src/utils/cognitoHelpersTest.js
  packages/identity-service/src/utils/rewardsReporter.js
  packages/web/package.json
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/pages/check-page/CheckPage.tsx
  packages/web/src/services/audius-backend/Cognito.ts
  packages/web/src/utils/constants.ts
Labels: size/XL

#11225 Ignore svg in harmony image rollup config
  .changeset/ninety-geckos-refuse.md
  packages/harmony/rollup.config.mjs
Labels: size/XS

#11228 [qa-1915] Fix upload image error copy
  packages/web/src/components/image-selection/ImageSelectionButton.jsx
  packages/web/src/components/image-selection/ImageSelectionPopup.jsx
  packages/web/src/components/image-selection/ImageSelectionPopup.module.css
  packages/web/src/components/upload/InvalidFileType.jsx
  packages/web/src/components/upload/InvalidFileType.module.css
  packages/web/src/components/upload/InvalidFileType.tsx
  packages/web/src/pages/upload-page/pages/SelectPage.tsx
Labels: size/L

#11231 Use bundler for cocoapods installs and update version
  packages/mobile/ios/Gemfile
  packages/mobile/ios/Gemfile.lock
  scripts/postinstall.sh
Labels: size/M

#11109 [PAY-3398] Use new playlist contents format
  .changeset/young-teachers-tap.md
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
Labels: size/M

#11234 Return aggregate challenges regardless of completion state
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/XS

#11210 Fix wallet serialization for userMetadataToSdk
  packages/common/src/adapters/user.ts
Labels: size/XS

#11222 [C-5643] Suggested tracks to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/useSuggestedPlaylistTracks.ts
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
Labels: size/L

#11237 [QA-1966] Update track tile heart icon to 24px
  packages/web/src/components/alt-button/FavoriteButton.module.css
Labels: size/XS

#11239 Clean up env before running tests
  .circleci/src/jobs/test.yml
  dev-tools/compose/docker-compose.discovery.dev.yml
  dev-tools/compose/docker-compose.test.yml
Labels: size/S

#11240 Make pushing DN images into one single job instead of 10
  .circleci/src/workflows/discovery.yml
  dev-tools/compose/docker-compose.discovery.dev.yml
  dev-tools/compose/docker-compose.test.yml
Labels: size/L

#11236 [C-5736] Migrate explore featured content to tan-query
  packages/common/src/api/index.ts
  packages/common/src/store/pages/explore/selectors.ts
  packages/common/src/store/pages/explore/slice.ts
  packages/common/src/store/pages/explore/types.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/reducers.ts
  packages/mobile/src/screens/app-screen/ExploreTabScreen.tsx
  packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/index.ts
  packages/mobile/src/screens/explore-screen/tabs/ArtistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/FeaturedPlaylistsTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/FeaturedProfilesTab.tsx
  packages/mobile/src/screens/explore-screen/tabs/PlaylistsTab.tsx
  packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/store/pages/explore/sagas.ts
  packages/web/src/components/card-legacy/desktop/CollectionArtCard.module.css
  packages/web/src/components/card-legacy/desktop/CollectionArtCard.tsx
  packages/web/src/components/collection/CollectionImage.tsx
  packages/web/src/components/link/CollectionLink.tsx
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/stats/FavoriteStats.tsx
  packages/web/src/components/stats/RepostStats.tsx
  packages/web/src/pages/explore-page/ExplorePage.tsx
  packages/web/src/pages/explore-page/ExplorePageProvider.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/UserArtCard.module.css
  packages/web/src/pages/explore-page/components/desktop/UserArtCard.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
  packages/web/src/public-site/pages/landing-page/components/FeaturedContent.tsx
  packages/web/src/store/sagas.ts
Labels: size/XXL

#11238 Fix auth for purchase and sale count
  packages/discovery-provider/src/api/v1/authorization_helpers.py
  packages/discovery-provider/src/api/v1/users.py
Labels: size/S

#11243 Improve history table performance
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
  packages/web/src/components/skeleton/Skeleton.module.css
  packages/web/src/components/skeleton/Skeleton.tsx
  packages/web/src/components/table/Table.tsx
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
Labels: size/L

#11245 Fix test-contracts and test-eth-contracts in ci
  contracts/Dockerfile
  eth-contracts/Dockerfile
Labels: size/S

#11246 Allow testing multiple services at once in CI
  .circleci/src/jobs/test.yml
Labels: size/XS

#11248 Allow multiple services to be pushed at once
  .circleci/src/jobs/push-docker-image.yml
Labels: size/XS

#11241 [PAY-3866] Listen Streak Challenge Web UI
  packages/common/src/hooks/useAudioRewards.ts
  packages/common/src/utils/challenges.ts
  packages/harmony/src/assets/icons/Headphones.svg
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressDescription.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressReward.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
Labels: size/L

#11230 rm remaining audiusd code
  .circleci/config.yml
  cmd/core/infra/Dockerfile.tests
  cmd/core/infra/dev_config/content-one.docker.env
  cmd/core/infra/dev_config/content-three.docker.env
  cmd/core/infra/dev_config/content-two.docker.env
  cmd/core/infra/dev_config/discovery-one.docker.env
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.yml
  eth-contracts/scripts/setup-dev.js
  pkg/core/gen/core_proto/protocol.pb.go
  pkg/core/gen/core_proto/protocol.swagger.json
  pkg/core/gen/models/protocol_block_response.go
  pkg/core/protocol/protocol.proto
  pkg/core/server/cache.go
  pkg/core/server/grpc.go
  pkg/core/server/server.go
  pkg/mediorum/.version.json
  pkg/mediorum/server/play_event_queue.go
  pkg/mediorum/server/repair.go
  pkg/mediorum/server/serve_blob.go
  scripts/get-release-dirs.sh
Labels: size/XXL

#11249 Add fixed-decimal to identity test cache in CI
  .circleci/src/jobs/@identity-jobs.yml
Labels: size/XS

#11247 Remove @pedalboard/backfill-audio-analyses
  dev-tools/compose/docker-compose.pedalboard.dev.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.yml
  package-lock.json
  packages/compose/package.json
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/.eslintrc.js
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/package.json
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_content.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/logger.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/tsconfig.json
Labels: size/XL

#11250 [PAY-3884] Fix plaid verification layout
  packages/web/src/pages/check-page/CheckPage.tsx
Labels: size/XS

#11251 Fix npm root cache issue on test-discovery-notifications
  monitoring/healthz/Dockerfile
  packages/discovery-provider/plugins/notifications/Dockerfile
Labels: size/S

#11242 [QA-1960] Update harmony in create-react-app
  packages/create-audius-app/examples/react-hono/.gitignore
  packages/create-audius-app/examples/react-hono/package-lock.json
  packages/create-audius-app/examples/react-hono/package.json
  packages/create-audius-app/examples/react/.gitignore
  packages/create-audius-app/examples/react/package-lock.json
  packages/create-audius-app/tests/e2e/react-hono/react-hono.test.ts
Labels: size/S

#11244 [C-5719] Add default cache invalidation behavior
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCurrentAccount.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/mobile/src/services/query-client.ts
  packages/web/src/services/query-client.ts
Labels: size/M

#11256 A few more small CAA fixes
  .changeset/eight-stingrays-deny.md
  packages/create-audius-app/tests/e2e/react/react.test.ts
Labels: size/S

#11232 [C-5728] Improve Android perf through strategic cache clearing
  packages/common/src/models/Analytics.ts
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.kt
  packages/mobile/src/app/App.tsx
  packages/mobile/src/hooks/useAndroidAppLifecycleManager.ts
  packages/mobile/src/hooks/useAppState.ts
Labels: size/L

#11258 Revert "[C-5728] Improve Android perf through strategic cache clearin…
  packages/common/src/models/Analytics.ts
  packages/mobile/android/app/src/main/java/co/audius/app/MainActivity.kt
  packages/mobile/src/app/App.tsx
  packages/mobile/src/hooks/useAndroidAppLifecycleManager.ts
  packages/mobile/src/hooks/useAppState.ts
Labels: size/L

#11257 Airdrop pt 1
  packages/common/src/hooks/useAudioRewards.ts
  packages/common/src/hooks/useFeatureFlag.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/common/src/utils/challenges.ts
  packages/common/src/utils/route.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  packages/mobile/src/assets/images/emojis/parachute.png
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/assets/fonts/emojis/parachute.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/components/banner/AirdropAppBanner.tsx
  packages/web/src/components/banner/DownloadAppBanner.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/L

#11261 Add fees to rewards claim evaluate
  .changeset/honest-boxes-explain.md
  packages/sdk/src/sdk/api/challenges/ChallengesApi.ts
Labels: size/XS

#11262 Add compute budget limit to buildTransaction
  .changeset/sixty-pans-bow.md
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/services/Solana/programs/SolanaClient.ts
  packages/sdk/src/sdk/services/Solana/programs/getDefaultConfig.ts
  packages/sdk/src/sdk/services/Solana/programs/types.ts
Labels: size/L

#11260 [C-5743] Migrate supporting and supporters to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/user.ts
  packages/common/src/hooks/chats/useAudienceUsers.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useGetFirstOrTopSupporter.ts
  packages/common/src/hooks/useRankedSupporters.ts
  packages/common/src/hooks/useSupporterPrompt.ts
  packages/mobile/src/components/comments/CommentBadge.tsx
  packages/mobile/src/components/feed-tip-tile/FeedTipTile.tsx
  packages/mobile/src/components/feed-tip-tile/FeedTipTileSkeleton.tsx
  packages/mobile/src/components/feed-tip-tile/PressableText.tsx
  packages/mobile/src/components/feed-tip-tile/ReceiverDetails.tsx
  packages/mobile/src/components/feed-tip-tile/SendTipButton.tsx
  packages/mobile/src/components/feed-tip-tile/SenderDetails.tsx
  packages/mobile/src/components/feed-tip-tile/constants.ts
  packages/mobile/src/components/feed-tip-tile/index.ts
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeFirstSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/BecomeTopSupporter.tsx
  packages/mobile/src/screens/tip-artist-screen/SendTipScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/SupporterPrompt.tsx
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/common/store/tipping/sagas.ts
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/comments/CommentBadge.tsx
  packages/web/src/components/lineup/LineupProvider.tsx
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css
  packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx
  packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
  packages/web/src/components/tipping/tip-audio/SendTip.tsx
  packages/web/src/components/tipping/tip-audio/SupporterPrompt.tsx
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
  packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePageNavSectionTitle.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePageNavSectionTitle.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.module.css
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/pages/profile-page/components/desktop/SupportingList.tsx
  packages/web/src/pages/profile-page/components/desktop/SupportingTile.tsx
  packages/web/src/pages/profile-page/components/desktop/TopSupporters.module.css
  packages/web/src/pages/profile-page/components/desktop/TopSupporters.tsx
Labels: size/XXL

#11253 [PAY-3885] Fix email access sharing
  packages/common/src/store/purchase-content/sagas.ts
  packages/discovery-provider/ddl/migrations/0117_add_is_initial_for_dev.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_email_entity_manager.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/tasks/entity_manager/entities/email.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/EmailAccess.ts
  packages/sdk/src/sdk/api/generated/default/models/EmailAccessResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/EmailKeyResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
Labels: size/XL

#11255 [PAY-3880] Add missing validated wallets to associated_wallets table
  packages/discovery-provider/ddl/migrations/0117_insert_missing_wallets.sql
Labels: size/L

#11185 [PAY-3879] Update wallet add/remove to use new transactions
  .changeset/fast-parrots-warn.md
  packages/common/src/adapters/user.ts
  packages/common/src/models/User.ts
  packages/common/src/schemas/metadata.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/mobile/src/store/wallet-connect/sagas/signMessageSaga.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.ts
  packages/sdk/src/sdk/api/users/types.ts
  packages/sdk/src/sdk/services/EntityManager/types.ts
  packages/sdk/src/sdk/types/ChainAddress.ts
  packages/sdk/src/sdk/types/SolanaAddress.ts
  packages/web/src/common/store/pages/token-dashboard/addWalletToUser.ts
  packages/web/src/common/store/pages/token-dashboard/associateNewWallet.ts
  packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts
  packages/web/src/common/store/pages/token-dashboard/sagas.ts
  packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Labels: size/XL

#11221 [C-5731] Search lineup to tan-query + search query hook updates
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/utils/infiniteQueryLoadNextPage.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/common/src/models/Analytics.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/screens/search-screen/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen/search-results/ProfileResults.tsx
  packages/mobile/src/screens/search-screen/search-results/TrackResults.tsx
  packages/mobile/src/screens/search-screen/searchState.ts
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
  packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/pages/search-page/hooks.ts
  packages/web/src/pages/search-page/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
  packages/web/src/pages/search-page/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
  packages/web/src/pages/search-page/search-results/TrackResults.tsx
Labels: size/XL

#11266 [C-5719] Add default cache invalidation behavior (#11244)
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCurrentAccount.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/mobile/src/services/query-client.ts
  packages/web/src/services/query-client.ts
Labels: size/M

#11267 Fix history page filter empty state
  packages/web/src/components/tracks-table/EmptyTable.tsx
  packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
Labels: size/S

#11263 [C-5744] Migrate mutuals to tan-query
  packages/common/src/api/index.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#11270 Fix mobile env location and import
  packages/mobile/src/app/AppContextProvider.tsx
  packages/mobile/src/app/AudiusQueryProvider.tsx
  packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
  packages/mobile/src/components/composer-input/ComposerInput.tsx
  packages/mobile/src/components/hcaptcha/HCaptcha.tsx
  packages/mobile/src/components/oauth/OAuthWebView.tsx
  packages/mobile/src/components/share-drawer/useShareToStory.tsx
  packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampEmbed.tsx
  packages/mobile/src/hooks/useTikTokAuth.ts
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/MilestoneNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupporterNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TopSupportingNotification.tsx
  packages/mobile/src/screens/settings-screen/AppearanceSettingsRow.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpPolicyText.tsx
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/mobile/src/services/analytics.ts
  packages/mobile/src/services/audius-backend-instance.ts
  packages/mobile/src/services/coinflow.ts
  packages/mobile/src/services/env/env.dev.ts
  packages/mobile/src/services/env/env.prod.ts
  packages/mobile/src/services/env/env.stage.ts
  packages/mobile/src/services/env/index.ts
  packages/mobile/src/services/fingerprint.ts
  packages/mobile/src/services/query-client.ts
  packages/mobile/src/services/remote-config/remote-config-instance.ts
  packages/mobile/src/services/sdk/audius-sdk.ts
  packages/mobile/src/services/sdk/auth.ts
  packages/mobile/src/services/sdk/discoveryNodeSelector.ts
  packages/mobile/src/services/sdk/identity.ts
  packages/mobile/src/store/storeContext.ts
  packages/mobile/src/utils/reachability.ts
  packages/mobile/src/utils/routes.tsx
  packages/mobile/src/utils/share.ts
Labels: size/M

#11269 More mobile rewards UI improvements
  packages/mobile/src/components/challenge-rewards-drawer/AudioMatchingChallengeDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ListenStreakEndlessChallengeDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ReferralRewardContents.tsx
Labels: size/L

#11264 [C-5601] Migrate related-artists to tan query
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/feed/selectors.ts
  packages/common/src/store/pages/feed/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_related_artists.py
  packages/mobile/src/components/suggested-follows/ArtistCategoryButton.tsx
  packages/mobile/src/components/suggested-follows/ContinueButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/mobile/src/store/sagas.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#11274 Add 'e' to sdk challenge enum
  .changeset/quick-rules-tie.md
  packages/sdk/src/sdk/api/challenges/types.ts
Labels: size/XS

#11273 Misc tan-query changes
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/search.ts
  packages/web/src/common/store/pages/premium-tracks/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/pages/premium-tracks-page/PremiumTracksPage.tsx
Labels: size/L

#11268 [C-5685] Migrate top-tags to tan-query
  packages/common/src/api/index.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/common/src/store/pages/profile/types.ts
  packages/web/src/common/store/profile/fetchTopTagsSaga.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.tsx
Labels: size/L

#11276 Stop adding ComputeBudget limits in ClaimableTokensClient
  packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
Labels: size/S

#11275 Refactor profile left nav
  packages/harmony/src/components/layout/Divider/Divider.tsx
  packages/harmony/src/components/skeleton/Skeleton.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileMutuals.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePageNavSectionItem.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePageNavSectionTitle.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePageNavSectionTitle.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.module.css
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/pages/profile-page/components/desktop/SupportingList.tsx
  packages/web/src/pages/profile-page/components/desktop/TopSupporters.module.css
  packages/web/src/pages/profile-page/components/desktop/TopSupporters.tsx
Labels: size/XL

#11279 Fix stale time usage to respect client defaults
  packages/common/src/api/tan-query/developerApps.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useAudioTransactions.ts
  packages/common/src/api/tan-query/useAudioTransactionsCount.ts
  packages/common/src/api/tan-query/useAuthorizedApps.ts
  packages/common/src/api/tan-query/useCollectionFavorites.ts
  packages/common/src/api/tan-query/useCollectionReposts.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useCurrentUser.ts
  packages/common/src/api/tan-query/useEmailInUse.ts
  packages/common/src/api/tan-query/useExploreContent.ts
  packages/common/src/api/tan-query/useFavoritedTracks.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useFollowing.ts
  packages/common/src/api/tan-query/useHandleInUse.ts
  packages/common/src/api/tan-query/useHandleReservedStatus.ts
  packages/common/src/api/tan-query/useMutedUsers.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/usePremiumTracks.ts
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/common/src/api/tan-query/usePurchasers.ts
  packages/common/src/api/tan-query/usePurchasersCount.ts
  packages/common/src/api/tan-query/usePurchasesCount.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useRemixedTracks.ts
  packages/common/src/api/tan-query/useRemixers.ts
  packages/common/src/api/tan-query/useRemixersCount.ts
  packages/common/src/api/tan-query/useRemixes.ts
  packages/common/src/api/tan-query/useSalesAggregate.ts
  packages/common/src/api/tan-query/useSalesCount.ts
  packages/common/src/api/tan-query/useSearchAutocomplete.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/useSuggestedArtists.ts
  packages/common/src/api/tan-query/useSupportedUsers.ts
  packages/common/src/api/tan-query/useSupporters.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTopTags.ts
  packages/common/src/api/tan-query/useTrackFavorites.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useTrackPageLineup.ts
  packages/common/src/api/tan-query/useTrackReposts.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/tan-query/useTrendingPlaylists.ts
  packages/common/src/api/tan-query/useTrendingUnderground.ts
  packages/common/src/api/tan-query/useUSDCTransactions.ts
  packages/common/src/api/tan-query/useUSDCTransactionsCount.ts
  packages/common/src/api/tan-query/useUserAlbums.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/api/tan-query/useUserPlaylists.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
  packages/common/src/api/tan-query/useUsers.ts
Labels: size/L

#11280 Fix discovery node registration for core on local dev
  dev-tools/compose/docker-compose.yml
Labels: size/XS

#11272 Aggregate step_count for listen streak challenge response
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/XS

#11281 [QA-1972] Fix a bug in the mutate function of the post comment tan-query hook
  packages/common/src/api/tan-query/comments.ts
Labels: size/S

#11271 Turn off broadcast for listens on solana relay
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/XS

#11284 [PAY-3896] Fix large reward amount text getting clipped
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressReward.tsx
Labels: size/M

#11124 suppress TURBO_TEAM and TURBO_TOKEN warning if not set
  dev-tools/compose/docker-compose.identity.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.test.yml
Labels: size/M

#11286 Revert "[C-5601] Migrate related-artists to tan query (#11264)"
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/feed/selectors.ts
  packages/common/src/store/pages/feed/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_related_artists.py
  packages/mobile/src/components/suggested-follows/ArtistCategoryButton.tsx
  packages/mobile/src/components/suggested-follows/ContinueButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/mobile/src/store/sagas.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#11283 [QA-1971] Fix original track downloads when download-gated
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/XS

#11289 Merge all DN docker image push jobs into one for release workflow
  .circleci/src/workflows/release.yml
Labels: size/M

#11292 Fix for npm run protocol up --prod
  .circleci/src/jobs/@integration-jobs.yml
Labels: size/XS

#11291 Revert "Return aggregate challenges regardless of completion state"
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/XS

#11297 Address QA feedback from home landing page
  packages/common/src/utils/route.ts
  packages/harmony/src/assets/icons/AudiusLogoHorizontalColorNew.svg
  packages/harmony/src/icons/Logos.stories.mdx
  packages/harmony/src/icons/logos.ts
  packages/web/src/assets/img/publicSite/HeroBG.webp
  packages/web/src/assets/img/publicSite/HeroBG@2x.webp
  packages/web/src/assets/img/publicSite/HeroBG@3x.webp
  packages/web/src/assets/img/publicSite/ProductShot1.webp
  packages/web/src/public-site/components/Footer.module.css
  packages/web/src/public-site/components/Footer.tsx
  packages/web/src/public-site/components/NavBanner.tsx
  packages/web/src/public-site/components/NavOverlay.module.css
  packages/web/src/public-site/components/NavOverlay.tsx
  packages/web/src/public-site/pages/landing-page/components/Description.module.css
  packages/web/src/public-site/pages/landing-page/components/Hero.module.css
  packages/web/src/public-site/pages/landing-page/components/PlatformFeatures.module.css
  packages/web/src/public-site/pages/landing-page/components/PlatformFeatures.tsx
Labels: size/L

#11299 [PAY-3911] Center align mobile reward drawer text
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeReward.tsx
  packages/mobile/src/components/challenge-rewards-drawer/styles.ts
Labels: size/S

#11296 Change airdrop month and fix progress reward amount
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Labels: size/XS

#11298 [PAY-3912] Claimable challenges always on top, pill colors
  packages/common/src/utils/challenges.ts
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/StatusPill.tsx
Labels: size/M

#11300 [PAY-3923] Show airdrop banner when logged out and in
  packages/web/src/components/banner/AirdropAppBanner.tsx
Labels: size/S

#11301 [PAY-3924][PAY-3925] Misc. small rewards page UI fixes
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
  packages/web/src/pages/rewards-page/components/Tile.module.css
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
Labels: size/M

#11305 rm notifs tests for stage deploy
  .circleci/src/workflows/discovery.yml
Labels: size/XS

#11304 Fix PlatformFeatures alignment, update product screenshot
  packages/web/src/assets/img/publicSite/ProductShot1.webp
  packages/web/src/public-site/pages/landing-page/components/PlatformFeatures.module.css
  packages/web/src/public-site/pages/landing-page/components/PlatformFeatures.tsx
Labels: size/S

#11307 Revert "Aggregate step_count for listen streak challenge response (#1…
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/XS

#11308 [PAY-3929] Fix claiming reward button state on mobile
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
Labels: size/S

#11310 [QA-1962] Update the get verified modal to keep the X button when loading
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
Labels: size/XS

#11309 [PAY-3899] Fix reward modal padding and claim progress styling on web
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressDescription.tsx
Labels: size/S

#11314 Add turbo remote caching to solana-relay, verified-notifications, and audius-cmd
  dev-tools/compose/docker-compose.dev-tools.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  packages/commands/Dockerfile.prod
Labels: size/S

#11311 [C-5765] Profile nav fixes
  packages/web/src/components/ai-generated-button/AiGeneratedCallout.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
  packages/web/src/pages/profile-page/components/desktop/SupportingList.tsx
  packages/web/src/pages/profile-page/components/desktop/TopSupporters.tsx
Labels: size/M

#11315 Fix bulk query fetching order
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUsers.ts
Labels: size/S

#11317 fix local dev
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/environment/audiusd-1.env
  dev-tools/environment/audiusd-2.env
  dev-tools/environment/audiusd-3.env
  dev-tools/environment/audiusd-4.env
Labels: size/L

#11313 [PAY-3926] Fix mobile-web header notif/reward count positions
  packages/web/src/components/nav/mobile/NavBar.module.css
  packages/web/src/components/nav/mobile/NavBar.tsx
Labels: size/M

#11322 Update the logic for associated wallets to not brick DNs due to the db level constraint
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/M

#11323 Fix audius-cmd turbo args
  dev-tools/compose/docker-compose.dev-tools.prod.yml
Labels: size/XS

#11324 Small fix for the associated wallet logic update
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/XS

#11282 [C-5690] Profile search pagination
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/search-page/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
  packages/web/src/pages/search-page/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
Labels: size/L

#11125 shutoff sol relay for plays
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Labels: size/M, do-not-merge

#11302 Upgrade elasticsearch to 8.17.1 Fix discovery tests
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/docker-compose.test.yml
Labels: size/XS

#11329 Prod airdrop QA
  packages/discovery-provider/ddl/data/0118_prod_airdrop/prod_qa_airdrop.csv
  packages/discovery-provider/ddl/migrations/0118_prod_airdrop_qa.sql
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/M

#11330 Fix airdrop qa migration naming
  packages/discovery-provider/ddl/data/0118_prod_airdrop_qa/prod_airdrop_qa.csv
  packages/discovery-provider/ddl/migrations/0118_prod_airdrop_qa.sql
Labels: size/XS

#11306 Update airdrop copy and add X icon
  .changeset/rich-peaches-rhyme.md
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
  packages/harmony/src/assets/icons/X.svg
  packages/harmony/src/icons/Logos.stories.mdx
  packages/harmony/src/icons/logos.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/mobile/src/screens/rewards-screen/Panel.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/M

#11327 Sign out from oauth should not go to trending
  packages/common/src/store/sign-out/slice.ts
  packages/common/src/utils/challenges.ts
  packages/web/src/components/banner/AirdropAppBanner.tsx
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
  packages/web/src/store/sign-out/sagas.ts
Labels: size/M

#11321 Fix explore page featured content
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useFeaturedPlaylists.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedProfiles.tsx
  packages/web/src/pages/explore-page/components/desktop/Section.tsx
Labels: size/L

#11320 Bump android resources for CI
  .circleci/src/commands/@mobile-commands.yml
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/XS

#11331 Bump android version to 468
  packages/mobile/android/app/build.gradle
Labels: size/XS

#11316 [C-5740] Follow/Unfollow user to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useFollowUser.ts
  packages/common/src/api/tan-query/useUnfollowUser.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/social/users/actions.ts
  packages/common/src/store/tipping/slice.ts
  packages/mobile/ios/Podfile.lock
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/web/src/common/store/social/users/errorSagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/UnfollowConfirmationModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/components/UnfollowConfirmationModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/TrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/XXL

#11332 Fix harmony and web lint
  packages/harmony/src/icons/Logos.stories.mdx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
Labels: size/XS

#11333 Update discovery lint to lint and fix
  packages/discovery-provider/scripts/lint.sh
Labels: size/XS

#11337 Fix reward claim error gap too large
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
Labels: size/S

#11336 [QA-1959] Hide referred tile with new challenge name
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
Labels: size/XS

#11335 Airdrop pt one migration
  packages/discovery-provider/ddl/data/0119_prod_airdrop_pt_one/prod_airdrop_pt_one.csv
  packages/discovery-provider/ddl/migrations/0119_prod_airdrop.sql
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/XXL

#11334 Endless listen streak in-progress step-count
  packages/discovery-provider/integration_tests/queries/test_get_challenges.py
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/L

#11338 [QA-1891] Fix track tile icon clipping and zero state
  packages/mobile/src/components/lineup-tile/TrackTileStats.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
Labels: size/XS

#11339 [QA-1768] Improve now playing drawer close arrow
  packages/mobile/src/components/drawer/DrawerHeader.tsx
  packages/mobile/src/components/now-playing-drawer/TitleBar.tsx
  packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
Labels: size/M

#11340 [QA-1772] Fix windows app frame
  packages/web/src/electron.js
Labels: size/S

#11342 Listen streak challenge different specifier for stage
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Labels: size/XS

#11344 [QA-1909] Fix playlist menu min-width
  packages/web/src/components/suggested-tracks/SuggestedTracks.module.css
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/M

#11345 Feature flag on claim all button
  packages/common/src/services/remote-config/feature-flags.ts
  packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
Labels: size/S

#11341 [QA-1977] Fix notifications tests
  packages/discovery-provider/plugins/notifications/package.json
Labels: size/XS

#11343 Fix listen streak challenge amount
  packages/discovery-provider/integration_tests/queries/test_get_challenges.py
  packages/discovery-provider/src/queries/get_challenges.py
Labels: size/S

#11349 Format number commas for all reward amounts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
  packages/web/src/pages/rewards-page/messages.tsx
Labels: size/S

#11350 Ineligible oneshot instead of incomplete on mobile
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
Labels: size/S

#11346 Prod airdrop migration
  packages/discovery-provider/ddl/data/0119_prod_airdrop/prod_airdrop.csv
  packages/discovery-provider/ddl/data/0119_prod_airdrop_pt_one/prod_airdrop_pt_one.csv
  packages/discovery-provider/ddl/functions/handle_user_challenges.sql
  packages/discovery-provider/ddl/migrations/0119_prod_airdrop.sql
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_rewards_manager.py
Labels: size/XXL

#11351 Don't show oneshot expiry if ineligible
  packages/common/src/utils/challenges.ts
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeDescription.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/M

#11354 filter chain health on these nodes
  packages/discovery-provider/src/queries/get_health.py
Labels: size/XS

#11353 Filter out listen streak endless notifications
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
Labels: size/M

#11352 [PAY-3941] Claim all rewards tile respects optimistic challenges
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/rewards-screen/ClaimAllRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ClaimAllRewardsPanel.tsx
Labels: size/M

#11303 [C-5767] Migrate related-artists to tan-query #2
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/relatedArtists.ts
  packages/common/src/store/pages/feed/reducer.ts
  packages/common/src/store/pages/feed/selectors.ts
  packages/common/src/store/pages/feed/types.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/related-artists/sagas.ts
  packages/common/src/store/ui/related-artists/selectors.ts
  packages/common/src/store/ui/related-artists/slice.ts
  packages/common/src/store/ui/related-artists/types.ts
  packages/discovery-provider/integration_tests/queries/test_get_related_artists.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_related_artists.py
  packages/mobile/src/components/suggested-follows/ArtistCategoryButton.tsx
  packages/mobile/src/components/suggested-follows/ContinueButton.tsx
  packages/mobile/src/components/suggested-follows/PickArtistsForMeButton.tsx
  packages/mobile/src/components/suggested-follows/SelectArtistCategoryButtons.tsx
  packages/mobile/src/components/suggested-follows/SuggestedArtistsList.tsx
  packages/mobile/src/components/suggested-follows/SuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/EmptyFeedSuggestedFollows.tsx
  packages/mobile/src/screens/feed-screen/FeedScreen.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/mobile/src/store/sagas.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/pages/signon/actions.ts
  packages/web/src/common/store/pages/signon/reducer.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/pages/signon/selectors.ts
  packages/web/src/common/store/pages/signon/types.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
  packages/web/src/store/sagas.ts
Labels: size/XXL

#11285 [C-5763 C-5603] Migrate profile collections to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useUserAlbums.ts
  packages/common/src/api/tan-query/useUserPlaylists.ts
  packages/common/src/store/pages/profile/actions.ts
  packages/common/src/store/pages/profile/reducer.ts
  packages/common/src/store/pages/profile/selectors.ts
  packages/discovery-provider/integration_tests/queries/test_get_playlists.py
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_playlists.py
  packages/discovery-provider/src/queries/query_helpers.py
  packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/UsersApi.ts
  packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts
  packages/web/src/common/store/profile/sagas.js
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/XXL

#11347 Tag audiusd with protocol releases to allow reverts
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/jobs/deploy-foundation-nodes.yml
Labels: size/S

#11358 Revert "filter chain health on these nodes"
  packages/discovery-provider/src/queries/get_health.py
Labels: size/XS

#11361 Fix plays indexing starvation
  packages/discovery-provider/integration_tests/queries/test_get_playlists.py
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_payment_router.py
  packages/discovery-provider/src/tasks/index_rewards_manager.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/L

#11359 entity manager through core on dev
  dev-tools/compose/docker-compose.audiusd.yml
  dev-tools/environment/audiusd-1.env
  dev-tools/environment/audiusd-2.env
  dev-tools/environment/audiusd-3.env
  dev-tools/environment/audiusd-4.env
  packages/discovery-provider/ddl/migrations/0119_add_em_block.sql
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/core-sdk/protocol_pb.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/models/core/core_indexed_blocks.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.py
  packages/discovery-provider/src/tasks/core/gen/protocol_pb2.pyi
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/tasks/index_core_entity_manager.py
  packages/discovery-provider/src/tasks/index_core_manage_entities.py
  packages/discovery-provider/src/tasks/index_core_plays.py
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
Labels: size/L

#11355 [C-5769] Use batch fetching to normalize core entity hooks
  package-lock.json
  packages/common/package.json
  packages/common/src/api/tan-query/batchers/__tests__/getCollectionsBatcher.test.ts
  packages/common/src/api/tan-query/batchers/__tests__/getTracksBatcher.test.ts
  packages/common/src/api/tan-query/batchers/__tests__/getUsersBatcher.test.ts
  packages/common/src/api/tan-query/batchers/getCollectionsBatcher.ts
  packages/common/src/api/tan-query/batchers/getTracksBatcher.ts
  packages/common/src/api/tan-query/batchers/getUsersBatcher.ts
  packages/common/src/api/tan-query/batchers/types.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUpdateProfile.ts
  packages/common/src/api/tan-query/useUpdateTrack.ts
  packages/common/src/api/tan-query/useUpdateUser.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/tan-query/utils/__tests__/combineQueryResults.test.ts
  packages/common/src/api/tan-query/utils/combineQueryResults.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
  packages/common/src/models/ErrorReporting.ts
  packages/protocol-dashboard/package.json
Labels: size/XXL

#11364 Hide endless challenge audio
  packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
Labels: size/XS

#11365 core block diff health check
  packages/discovery-provider/src/queries/get_health.py
Labels: size/S

#11367 🪦 poa ganache
  .circleci/config.yml
  .circleci/src/workflows/contracts.yml
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.blockchain.yml
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/docker-compose.identity.prod.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/docker-compose.test.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/compose/nginx_ingress.conf
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
  packages/identity-service/src/audiusLibsInstance.js
Labels: size/L

#11360 [C-5270 C-5269 C-5268 C-5629] Comment layout improvements
  packages/common/src/messages/comments.ts
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/harmony/src/components/icon-text/IconText.tsx
  packages/harmony/src/components/send-icon/SendIcon.tsx
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentPreview.tsx
  packages/mobile/src/harmony-native/components/IconText/IconText.tsx
  packages/web/src/components/comments/CommentActionBar.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/NoComments.tsx
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/data-entry/TextAreaV2.tsx
  packages/web/src/components/link/UserLink.tsx
Labels: size/L

#11118 MRVR country fixes
  packages/discovery-provider/ddl/migrations/0115_fix_netherlands.sql
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/mrvr.ts
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Labels: size/L

#11369 Disable endless listen streak challenge, delete rows
  packages/discovery-provider/ddl/migrations/0120_delete_listen_streak_endless_challenges.sql
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/XS

#11371 Randomize storage node ordering in StorageNodeSelector.
  packages/sdk/src/sdk/api/albums/AlbumsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
  packages/sdk/src/sdk/api/users/UsersApi.test.ts
  packages/sdk/src/sdk/sdk.ts
  packages/sdk/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
  packages/sdk/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
  packages/sdk/src/sdk/services/StorageNodeSelector/types.ts
Labels: size/M

#11372 Listen streak challenge fix 2 plays in one day
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Labels: size/M

#11374 [C5778] Update web profile page layout
  packages/web/src/common/utils/layout.ts
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/cover-photo/CoverPhoto.module.css
  packages/web/src/components/nav-banner/NavBanner.module.css
  packages/web/src/components/nav-banner/NavBanner.tsx
  packages/web/src/components/stat-banner/StatBanner.module.css
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/user-badges/ProfilePageBadge.module.css
  packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx
  packages/web/src/pages/profile-page/components/EmptyTab.jsx
  packages/web/src/pages/profile-page/components/EmptyTab.module.css
  packages/web/src/pages/profile-page/components/EmptyTab.tsx
  packages/web/src/pages/profile-page/components/SocialLinkInput.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
  packages/web/src/pages/profile-page/components/desktop/constants.ts
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/utils/zIndex.ts
Labels: size/XXL

#11287 [PAY-3881][PAY-3883] Add indexing/endpoints for separated collectibles data
  .changeset/fresh-poems-visit.md
  packages/discovery-provider/ddl/migrations/0118_add_collectibles.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/models/users/collectibles.py
  packages/discovery-provider/src/queries/get_collectibles.py
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/Collectibles.ts
  packages/sdk/src/sdk/api/generated/default/models/CollectiblesResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
Labels: size/XL

#11318 [C-5768] New fetch single entity pattern
  packages/common/src/api/tan-query/useAudioTransactions.ts
  packages/common/src/api/tan-query/useCollectionReposts.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useFollowing.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/useMutedUsers.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/usePurchasers.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useRemixers.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTrackFavorites.ts
  packages/common/src/api/tan-query/useTrackReposts.ts
  packages/common/src/api/tan-query/useUserAlbums.ts
  packages/common/src/api/tan-query/useUserPlaylists.ts
  packages/common/src/api/tan-query/useUserTracksByHandle.ts
Labels: size/L

#11378 fix integration test
  dev-tools/compose/docker-compose.discovery.prod.yml
  packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
Labels: size/S

#11366 [C-5782, C-5783] Add user comments endpoint and tan query hook
  packages/common/src/api/tan-query/comments.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_comments.py
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/Comment.ts
  packages/sdk/src/sdk/api/generated/default/models/UserCommentsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/web/src/components/comments/CommentThread.tsx
Labels: size/L

#11380 [PAY-3946] Fix multiple plays in same batch breaking listen streak
  packages/discovery-provider/ddl/migrations/0120_delete_listen_streak_endless_challenges.sql
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Labels: size/XS

#11382 [C-1984] Improve left-nav buttons with IconButton improvements
  .changeset/honest-swans-share.md
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/web/src/components/nav/desktop/NavHeaderButton.tsx
Labels: size/M

#11383 [C-5771 QA-1983] Fix harmony white and static white
  packages/harmony/src/foundations/color/primitive.css
  packages/web/src/assets/styles/colors.css
  packages/web/src/components/action-drawer/ActionDrawer.module.css
  packages/web/src/components/ai-generated-button/AiGeneratedCallout.module.css
  packages/web/src/components/banner/Banner.module.css
  packages/web/src/components/banner/CallToActionBanner.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/data-entry/TextAreaV2.module.css
  packages/web/src/components/dragndrop/Draggable.module.css
  packages/web/src/components/edit/fields/DatePickerField.module.css
  packages/web/src/components/modal-drawer/ModalDrawer.module.css
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/notice/Notice.module.css
  packages/web/src/components/notification/Notification/components/TwitterShareButton.module.css
  packages/web/src/components/notification/Notification/components/UserProfilePictureList.module.css
  packages/web/src/components/perspective-card/PerspectiveCard.module.css
  packages/web/src/components/play-bar/mobile/PlayBar.module.css
  packages/web/src/components/profile-progress/components/ProfileCompletionHeroCard.module.css
  packages/web/src/components/profile-progress/components/TaskCompletionItem.module.css
  packages/web/src/components/reward-claimed-toast/RewardClaimedToast.module.css
  packages/web/src/components/rewards/ClickableAddress.module.css
  packages/web/src/components/rewards/PurpleBox.module.css
  packages/web/src/components/rewards/modals/TrendingRewards.module.css
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
  packages/web/src/components/search-bar/SearchBarResult.module.css
  packages/web/src/components/table/Table.module.css
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/toast/Toast.module.css
  packages/web/src/components/toast/mobile/ToastLinkContent.module.css
  packages/web/src/components/tooltip/Tooltip.module.css
  packages/web/src/components/track/Artwork.module.css
  packages/web/src/components/track/GatedConditionsPill.module.css
  packages/web/src/components/track/mobile/BottomButtons.module.css
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/components/track/mobile/TrackTile.module.css
  packages/web/src/components/user-badges/FollowsYouBadge.module.css
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
  packages/web/src/pages/audio-page/AudioPage.module.css
  packages/web/src/pages/audio-page/components/SendInputConfirmation.module.css
  packages/web/src/pages/audio-page/components/WalletManagementTile.module.css
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageList.module.css
  packages/web/src/pages/dashboard-page/DashboardPage.module.css
  packages/web/src/pages/dashboard-page/components/TotalPlaysChart.module.css
  packages/web/src/pages/explore-page/components/mobile/ColorTile.module.css
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.module.css
  packages/web/src/pages/profile-page/components/mobile/UploadStub.module.css
  packages/web/src/pages/rewards-page/RewardsPage.module.css
  packages/web/src/pages/trending-page/components/GenreSelectionList.module.css
  packages/web/src/pages/trending-page/components/RewardsBanner.module.css
  packages/web/src/pages/visualizer/VisualizerProvider.module.css
  packages/web/src/public-site/components/NavBanner.module.css
  packages/web/src/public-site/components/NavOverlay.module.css
  packages/web/src/public-site/pages/landing-page/LandingPage.module.css
  packages/web/src/public-site/pages/landing-page/components/PlatformFeatures.module.css
Labels: size/L

#11375 [C-5766] Paginate profile collections
  packages/common/src/api/tan-query/useUserAlbums.ts
  packages/common/src/api/tan-query/useUserPlaylists.ts
  packages/mobile/src/components/collection-list/CollectionList.tsx
  packages/mobile/src/components/core/CardList.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
  packages/web/src/pages/profile-page/components/desktop/AlbumsTab.tsx
  packages/web/src/pages/profile-page/components/desktop/EmptyTab.module.css
  packages/web/src/pages/profile-page/components/desktop/EmptyTab.tsx
  packages/web/src/pages/profile-page/components/desktop/PlaylistsTab.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/AlbumsTab.tsx
  packages/web/src/pages/profile-page/components/mobile/EmptyTab.tsx
  packages/web/src/pages/profile-page/components/mobile/PlaylistsTab.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/XL

#11384 Fix infinite query return args
  packages/common/src/api/tan-query/useCollectionFavorites.ts
  packages/common/src/api/tan-query/useCollectionReposts.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useFollowing.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/usePurchasers.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useRemixers.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTrackFavorites.ts
  packages/common/src/api/tan-query/useTrackReposts.ts
Labels: size/L

#11379 [PAY-3850][PAY-3849] Add listen streak noti on web
  packages/common/src/adapters/notification.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/ddl/functions/handle_user_challenges.sql
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/sdk/src/sdk/api/generated/full/models/ChallengeRewardNotificationActionData.ts
  packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/M

#11392 Fix "Complete Upload" crash
  packages/common/src/api/tan-query/useUserCollectibles.ts
Labels: size/XS

#11393 Fix top tracks
  packages/common/src/api/tan-query/useTopTags.ts
Labels: size/S

#11376 [C-5784] Use normalized batch entities in lineup queries
  packages/common/src/api/tan-query/batchers/contextCacheResolver.ts
  packages/common/src/api/tan-query/batchers/getCollectionsBatcher.ts
  packages/common/src/api/tan-query/batchers/getTracksBatcher.ts
  packages/common/src/api/tan-query/batchers/getUsersBatcher.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/mobile/src/services/query-client.ts
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
  packages/web/src/services/query-client.ts
Labels: size/L

#11389 [PAY-3848] Add ListenStreakReminder notification
  packages/common/src/adapters/notification.ts
  packages/common/src/messages/index.ts
  packages/common/src/messages/notifications.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/integration_tests/tasks/test_create_listen_streak_reminder_notifications.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/scripts/lint.sh
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/discovery-provider/src/tasks/create_listen_streak_reminder_notifications.py
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ListenStreakReminderNotification.tsx
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/ListenStreakReminderNotification.ts
  packages/sdk/src/sdk/api/generated/full/models/ListenStreakReminderNotificationAction.ts
  packages/sdk/src/sdk/api/generated/full/models/ListenStreakReminderNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/Notification.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/common/store/notifications/fetchNotifications.ts
  packages/web/src/components/notification/Notification/ListenStreakReminderNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/components/icons.tsx
Labels: size/XL

#11399 Enable listen streak endless challenge, delete prior notifs
  packages/discovery-provider/ddl/migrations/0121_delete_listen_streak_endless_notifications.sql
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/XS

#11398 Add mobile notification for endless streak
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
Labels: size/M

#11401 Fix drag n drop playlist reordering
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Labels: size/XS

#11402 [PAY-3949] Add fire emoji to notification
  packages/mobile/src/screens/notifications-screen/Notification/NotificationHeader.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ListenStreakReminderNotification.tsx
Labels: size/M

#11404 Flush listen streak updates before adding user challenge
  packages/discovery-provider/src/challenges/challenge.py
Labels: size/XS

#11400 Fix text clipping for rewards text
  packages/mobile/src/components/challenge-rewards-drawer/ListenStreakEndlessChallengeDrawerContent.tsx
  packages/mobile/src/screens/rewards-screen/Panel.tsx
Labels: size/S

#11406 Fix create playlists for users with capcase handle
  packages/web/src/hooks/useManagedAccountNotAllowedRedirect.ts
Labels: size/XS

#11403 Fix edit playlist nav link when unfetched
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
Labels: size/XS
