Repository AudiusProject/apps, pull requests merged in 2025-03, with the labels that each got.

#11489 [PAY-3975] First weekly comment mobile UI
  packages/common/src/utils/challenges.ts
  packages/harmony/src/assets/icons/ArrowRotate.svg
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/components/challenge-rewards-drawer/FirstWeeklyCommentChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/challengeContentRegistry.ts
  packages/mobile/src/harmony-native/icons.ts
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/FirstWeeklyCommentChallengeModalContent.tsx
Labels: size/L

#11444 Get user pubkey from registered peer if unable to recover.
  comms/discovery/discovery_main.go
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/server/server.go
Labels: size/M

#11431 [C-5738] favoriteTrack and unfavoriteTrack to tan-query
  packages/common/src/adapters/search.ts
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useFavoriteTrack.ts
  packages/common/src/api/tan-query/useNotifications.ts
  packages/common/src/api/tan-query/useSearchAutocomplete.ts
  packages/common/src/api/tan-query/useSupportedUsers.ts
  packages/common/src/api/tan-query/useSupporters.ts
  packages/common/src/api/tan-query/useToggleFavoriteTrack.ts
  packages/common/src/api/tan-query/useTopTags.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useUnfavoriteTrack.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
  packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/store/offline-downloads/sagas/watchSaveTrackSaga.ts
  packages/mobile/src/store/offline-downloads/sagas/watchUnsaveTrackSaga.ts
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/PlayBarProvider.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.jsx
  packages/web/src/components/play-bar/mobile/PlayBar.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/XXL

#11493 Update trending copy and challenge config
  packages/discovery-provider/src/challenges/challenges.json
  packages/mobile/src/components/trending-rewards-drawer/TrendingRewardsDrawer.tsx
  packages/web/src/components/rewards/modals/TrendingRewards.tsx
Labels: size/S

#11494 Fix trending page
  packages/common/src/store/pages/trending/reducer.ts
Labels: size/S

#11497 No cooldown days on dev/stage for first weekly comment challenge
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.stage.json
Labels: size/XS

#11496 Fix first comment status label
  packages/common/src/hooks/useAudioRewards.ts
  packages/common/src/utils/challenges.ts
  packages/mobile/src/screens/rewards-screen/Panel.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/FirstWeeklyCommentChallengeModalContent.tsx
  packages/web/src/pages/rewards-page/messages.tsx
Labels: size/M

#11498 Update trending modal header
  packages/web/src/components/rewards/modals/TrendingRewards.tsx
Labels: size/S

#11473 [PAY-3954] Add backend for play count challenge
  packages/discovery-provider/integration_tests/challenges/test_play_count_milestones_challenge.py
  packages/discovery-provider/src/challenges/challenge_event.py
  packages/discovery-provider/src/challenges/challenge_event_bus.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/play_count_milestones_challenge.py
  packages/discovery-provider/src/tasks/index_core_plays.py
Labels: size/XL

#11492 indexing side effects
  packages/discovery-provider/src/api_helpers.py
  packages/discovery-provider/src/gated_content/signature.py
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/tasks/index_core_side_effects.py
  packages/discovery-provider/src/utils/helpers.py
Labels: size/L

#11500 fix max width for flex page container
  packages/web/src/components/page/FlushPageContainer.tsx
Labels: size/XS

#11499 AAO UI
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/package.json
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/tsconfig.json
Labels: size/XXL

#11503 [PAY-3985] More misc first weekly comment challenge UI fixes
  packages/common/src/utils/challenges.ts
  packages/mobile/src/components/challenge-rewards-drawer/ClaimError.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ClaimButton.tsx
Labels: size/S

#11502 Enable stage AAO plugin config
  packages/discovery-provider/src/api_helpers.py
  packages/mobile/src/services/env/env.stage.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
  packages/sdk/src/sdk/services/AntiAbuseOracle/types.ts
  packages/sdk/src/sdk/services/AntiAbuseOracleSelector/AntiAbuseOracleSelector.ts
  packages/web/src/services/env/env.stage.ts
Labels: size/S

#11505 Use cross fetch in AAO plugin
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/package.json
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
Labels: size/XS

#11506 [PAY-3983] Fix missing status label on reward panels
  packages/common/src/hooks/useAudioRewards.ts
Labels: size/S

#11507 [PAY-3947] Fix challenge error UI
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsLayout.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ClaimError.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsLayout.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/S

#11508 Make stage first weekly comment backend match prod
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/first_weekly_comment_challenge.py
Labels: size/XS

#11511 Remove invalid model fields for create track/playlist notifs
  packages/discovery-provider/src/api/v1/models/notifications.py
Labels: size/XS

#11504 [C-5820] Update trending rewards modal UI
  packages/harmony/src/foundations/shadows/shadows.ts
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/locked-content-modal/LockedContentModal.tsx
  packages/web/src/components/modal-drawer/ModalDrawer.module.css
  packages/web/src/components/modal-drawer/ModalDrawer.tsx
  packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
  packages/web/src/components/rewards/modals/TrendingRewards.module.css
  packages/web/src/components/rewards/modals/TrendingRewardsModal.tsx
  packages/web/src/components/rewards/modals/VipDiscordModal.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
  packages/web/src/pages/audio-page/WalletModal.tsx
  packages/web/src/pages/audio-page/components/modals/AudioBreakdownModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Labels: size/L

#11513 Revert "[C-5204] Fix android comment input clipping (#11386)"
  packages/mobile/src/components/comments/CommentDrawer.tsx
Labels: size/S

#11512 Fix missing cover-photo error log
  packages/discovery-provider/src/schemas/user_schema.json
Labels: size/S

#11515 Remove unused notification data fields from sdk
  .changeset/four-foxes-beg.md
  packages/sdk/src/sdk/api/generated/full/models/CreatePlaylistNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CreateTrackNotificationActionData.ts
Labels: size/S

#11516 core block updated in redis
  packages/discovery-provider/src/api_helpers.py
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/tasks/index_latest_block.py
  packages/discovery-provider/src/utils/core.py
Labels: size/M

#11517 Rename AAO plugin docker image
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/release.yml
  dev-tools/compose/docker-compose.pedalboard.dev.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
Labels: size/S

#11509 Add cors to attestation plugin
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/XS

#11514 [C-5821] Recent comments final QA
  packages/common/src/api/tan-query/comments.ts
  packages/common/src/api/tan-query/comments/useCommentReplies.ts
  packages/common/src/api/tan-query/comments/useComments.ts
  packages/common/src/api/tan-query/comments/useTrackComments.ts
  packages/common/src/api/tan-query/comments/useUserComments.ts
  packages/common/src/context/comments/commentsContext.tsx
  packages/discovery-provider/integration_tests/queries/test_get_user_comments.py
  packages/discovery-provider/src/queries/comments/utils.py
  packages/mobile/src/components/comments/RecentUserCommentsDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/pages/comment-history/components/desktop/CommentHistoryPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
Labels: size/L

#11527 Fix audius compose up for AAO plugin
  dev-tools/compose/docker-compose.yml
Labels: size/XS

#11528 Add migration to update audio match amounts
  packages/discovery-provider/ddl/migrations/0122_patch_incorrect_audio_match_amount.sql
Labels: size/M

#11524 [QA-2003] Fix overflow menu share
  packages/web/src/components/menu/CollectionMenu.tsx
  packages/web/src/components/menu/TrackMenu.tsx
Labels: size/M

#11531 only update blocks when indexing em
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/S

#11530 [QA-1999] Fix dashboard shadows and link styles
  package-lock.json
  packages/protocol-dashboard/package.json
  packages/protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx
  packages/protocol-dashboard/src/components/Stat/Stat.tsx
  packages/protocol-dashboard/vite.config.ts
Labels: size/S

#11458 Search pagination
  packages/discovery-provider/src/api/v1/helpers.py
  packages/discovery-provider/src/api/v1/playlists.py
  packages/discovery-provider/src/api/v1/tracks.py
  packages/discovery-provider/src/api/v1/users.py
  packages/sdk/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
Labels: size/M

#11522 Use score in aao response
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/S

#11533 [PAY-3782] Update reward banners
  packages/web/src/pages/trending-page/components/RewardsBanner.module.css
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/L

#11532 Shadowban notifications
  packages/discovery-provider/ddl/functions/shadowban_users.sql
  packages/discovery-provider/nginx_conf/nginx_container.conf
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  packages/discovery-provider/src/queries/get_notifications.py
Labels: size/L

#11534 Fix banner on mobile web
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/XS

#11535 Fix embed node polyfills and clean up deps
  package-lock.json
  packages/embed/package.json
  packages/embed/vite.config.js
Labels: size/S

#11537 Make banner closer to figma
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/M

#11538 Move trending job to 12:15 pt
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
Labels: size/XS

#11541 fix bad package-lock for vite-plugin-node-polyfills
  package-lock.json
Labels: size/XS

#11539 Use paper component
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/M

#11544 Update collectibles modal UI
  packages/web/src/components/collectibles/components/CollectibleRow.tsx
  packages/web/src/components/collectibles/components/CollectiblesPage.module.css
  packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Labels: size/L

#11547 Add breakpoint on rewards banner
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/XS

#11548 Fix now playing jitter and nav icon spacing in mobile web
  packages/web/src/components/nav/mobile/NavBar.module.css
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/now-playing/NowPlayingDrawer.tsx
Labels: size/XS

#11525 fix trending with core
  packages/discovery-provider/src/tasks/calculate_trending_challenges.py
  packages/discovery-provider/src/tasks/index_trending.py
Labels: size/M

#11549 Revert "[PAY-3865] Don't deeplink on android oauth"
  packages/mobile/android/app/src/main/AndroidManifest.xml
Labels: size/M

#11550 Revert shadowban in-app notifs
  packages/discovery-provider/integration_tests/queries/test_notifications/test_follow_notification.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_get_unread_notification_count.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_paginate_notification.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_repost_notification.py
  packages/discovery-provider/integration_tests/queries/test_notifications/test_save_notification.py
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  packages/discovery-provider/src/queries/get_notifications.py
Labels: size/M

#11540 Fix now playing artwork visualizer button
  packages/harmony/src/components/button/IconButton/IconButton.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
Labels: size/S

#11510 [C-5759] DeleteTrack to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useDeleteTrack.ts
  packages/common/src/api/tan-query/useUpdateTrack.ts
  packages/common/src/api/tan-query/utils/handleStemUpdates.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/primeUserData.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/ui/modals/delete-track-confirmation-modal/index.ts
  packages/mobile/src/components/drawers/DeleteTrackConfirmationDrawer.tsx
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/components/delete-track-confirmation-modal/DeleteTrackConfirmationModal.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/L

#11551 [C-5826] Add combineQueryStatuses helper
  packages/common/src/api/tan-query/comments/useComments.ts
  packages/common/src/api/tan-query/comments/useTrackComments.ts
  packages/common/src/api/tan-query/comments/useUserComments.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useNotifications.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/tan-query/utils/combineQueryStatuses.ts
  packages/common/src/api/tan-query/utils/index.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/web/src/components/notification/Notification/components/NotificationTile.tsx
Labels: size/L

#11553 Fix useDeleteTrack, sagas, and confirmation modal
  packages/common/src/store/ui/modals/delete-track-confirmation-modal/index.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/components/delete-track-confirmation-modal/DeleteTrackConfirmationModal.tsx
Labels: size/S

#11518 [PAY-3699] Show upload chip if you have deleted all your tracks
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Labels: size/S

#11543 [PAY-3992] Improve suggested follows loading
  packages/web/src/components/artist-recommendations/ArtistRecommendationsDropdown.tsx
  packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
Labels: size/M

#11556 Remove wildcard match in search queries
  packages/discovery-provider/src/queries/search_es.py
Labels: size/S

#11545 [PAY-3994] Prevent -1 fetches in tan query hooks
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUsers.ts
Labels: size/S

#11520 Summary Table for first weekly comment challenge
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsLayout.tsx
  packages/mobile/src/components/challenge-rewards-drawer/DefaultChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/FirstWeeklyCommentChallengeContent.tsx
  packages/mobile/src/components/summary-table/SummaryTable.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/FirstWeeklyCommentChallengeModalContent.tsx
Labels: size/S

#11557 Remove ES from health check
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/queries/get_health_unit_test.py
Labels: size/L

#11521 [PAY-3979][PAY-3990] Update play count challenge BE and Add the FE
  packages/common/src/models/AudioRewards.ts
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/integration_tests/challenges/test_play_count_milestones_challenge.py
  packages/discovery-provider/src/challenges/challenge_event_bus.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/play_count_milestone_10000_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_1000_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_250_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_challenge_base.py
  packages/discovery-provider/src/challenges/play_count_milestones_challenge.py
  packages/mobile/src/components/challenge-rewards-drawer/PlayCountMilestoneContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/challengeContentRegistry.ts
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/hooks/useRewardIds.ts
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/PlayCountMilestoneContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/challengeContentRegistry.ts
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/XXL

#11560 Remove dependency on getCurrentBlock in SDK
  package.json
  packages/sdk/src/sdk/api/albums/AlbumsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
  packages/sdk/src/sdk/services/EntityManager/types.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
Labels: size/M

#11561 Delete pc challenge
  packages/discovery-provider/ddl/migrations/0123_delete_pc_challenge.sql
Labels: size/XS

#11562 Fix marshalling for playlist notifs
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/XS

#11566 [PAY-4017] Update embed collections gallery to use sdk collectibles endpoint
  packages/embed/src/components/collectibles/CollectibleGallery.jsx
  packages/embed/src/util/BedtimeClient.js
Labels: size/S

#11564 [PAY-3893][PAY-3894] Remove legacy indexing of associated_wallets and collectibles
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/L

#11563 Remove end_date on play count challenge and update query
  packages/discovery-provider/integration_tests/challenges/test_play_count_milestones_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_challenge_base.py
Labels: size/L

#11568 Fix unlocked gated content section on web
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/M

#11552 fix attest endpoint
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/XS

#11573 dual write to acdc and core
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
Labels: size/M

#11576 fix core cutover
  packages/discovery-provider/src/tasks/index_core_cutovers.py
Labels: size/XS

#11567 [PAY-3935][PAY-3828] Remove remaining references to metadata_multihash in client and discovery
  .changeset/nasty-papayas-boil.md
  packages/common/src/adapters/user.ts
  packages/common/src/models/User.ts
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/models/users.py
  packages/discovery-provider/src/models/users/user.py
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/metadata.py
  packages/mobile/src/models/User.ts
  packages/sdk/src/sdk/api/generated/full/models/UserFull.ts
  packages/web/src/common/store/pages/token-dashboard/getAccountMetadataCID.ts
Labels: size/L

#11577 Update playcount milestones challenge config & add icons
  .changeset/yellow-falcons-mate.md
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/sdk/src/sdk/api/challenges/types.ts
  packages/web/src/assets/fonts/emojis/play-pause.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/M

#11570 Add user scoring for in app notif
  packages/discovery-provider/ddl/migrations/0123_add_user_score.sql
  packages/discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
  packages/discovery-provider/src/models/users/aggregate_user.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/discovery-provider/src/tasks/update_aggregates.py
Labels: size/L

#11580 rm deregistered nodes from sdk cached list
  monitoring/healthz/es_debug/broken.txt
  monitoring/healthz/es_debug/fix.md
  monitoring/healthz/es_debug/hosts.txt
  monitoring/healthz/es_debug/indices.sh
  monitoring/healthz/es_debug/results.txt
  monitoring/healthz/es_debug/results2.txt
  monitoring/healthz/es_debug/sps.ts
  monitoring/healthz/es_debug/verbose.sh
  packages/sdk/src/sdk/config/production.ts
Labels: size/L

#11434 [C-5739] Repost track to tan query (web only)
  package-lock.json
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/writes/useRepostTrack.ts
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/now-playing/NowPlaying.tsx
  packages/web/src/components/play-bar/desktop/PlayBar.jsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/track/ViewerActionButtons.tsx
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/components/track/desktop/PlaylistTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/track/mobile/ConnectedTrackTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
  packages/web/src/hooks/useRepost.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Labels: size/L

#11582 Audius Client (Web and Mobile) v1.5.125
  package-lock.json
  package.json
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
  packages/mobile/package.json
  packages/web/package.json
Labels: size/S

#11585 change up discprov healthz to reflect core
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/M

#11583 rm acdc from health check
  packages/discovery-provider/src/queries/get_health.py
Labels: size/M

#11546 [C-5815] Migrate followers user-list to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/mobile/src/harmony-native/components/index.ts
  packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserListV2.tsx
  packages/web/src/components/user-list-modal/ConnectedUserListModal.tsx
  packages/web/src/components/user-list-modal/components/UserListModalV2.tsx
  packages/web/src/components/user-list-modal/components/lists/FavoritesUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/FollowersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/FollowingUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/MutualsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/NotificationUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/PurchasersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RelatedArtistsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RemixersUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/RepostsUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/SupportingUserList.tsx
  packages/web/src/components/user-list-modal/components/lists/TopSupportersUserList.tsx
  packages/web/src/components/user-list/UserListItemSkeleton.tsx
  packages/web/src/components/user-list/UserListV2.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/store/application/ui/userListModal/types.ts
Labels: size/XL

#11591 Fix dashboard job on release
  .circleci/src/workflows/protocol-dashboard.yml
Labels: size/XS

#11589 Remove aggregate index monthly plays job in favor of trigger
  packages/discovery-provider/ddl/functions/handle_play.sql
  packages/discovery-provider/integration_tests/tasks/test_index_aggregate_monthly_plays.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_aggregate_monthly_plays.py
Labels: size/L

#11587 core stuck health check
  packages/discovery-provider/src/queries/get_health.py
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/utils/core.py
Labels: size/S

#11595 put correct total chain blocks in healthz
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/S

#11596 Shadowban notifs via trigger
  packages/discovery-provider/ddl/functions/handle_follow.sql
  packages/discovery-provider/ddl/functions/handle_repost.sql
  packages/discovery-provider/ddl/functions/handle_save.sql
  packages/discovery-provider/src/queries/get_notifications.py
Labels: size/M

#11590 rm index_nethermind and index_latest_block tasks
  packages/discovery-provider/integration_tests/challenges/test_trending_challenge.py
  packages/discovery-provider/integration_tests/conftest.py
  packages/discovery-provider/integration_tests/tasks/test_index_nethermind.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/scripts/start.sh
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/calculate_trending_challenges.py
  packages/discovery-provider/src/tasks/index_core.py
  packages/discovery-provider/src/tasks/index_core_entity_manager.py
  packages/discovery-provider/src/tasks/index_core_side_effects.py
  packages/discovery-provider/src/tasks/index_latest_block.py
  packages/discovery-provider/src/tasks/index_nethermind.py
Labels: size/XL

#11597 adjust relay to work in non dev without acdc
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
Labels: size/S

#11599 Increase undisbursed challenge req limit to 500
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
Labels: size/XS

#11542 [C-5795] Tan-query search to main
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useFeed.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/common/src/api/tan-query/useRemixes.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useTrending.ts
  packages/common/src/api/tan-query/useTrendingPlaylists.ts
  packages/common/src/api/tan-query/useTrendingUnderground.ts
  packages/common/src/api/tan-query/utils/infiniteQueryLoadNextPage.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/lineup/types.ts
  packages/mobile/src/screens/search-screen/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen/search-results/AllResults.tsx
  packages/mobile/src/screens/search-screen/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen/search-results/ProfileResults.tsx
  packages/mobile/src/screens/search-screen/search-results/TrackResults.tsx
  packages/mobile/src/screens/search-screen/searchState.ts
  packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
  packages/web/src/common/store/queue/sagas.ts
  packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/pages/search-page/hooks.ts
  packages/web/src/pages/search-page/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
  packages/web/src/pages/search-page/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
  packages/web/src/pages/search-page/search-results/TrackResults.tsx
  packages/web/src/pages/search-page/types.ts
Labels: size/XXL

#11604 Add rate limiter to otp on /authentication route
  packages/identity-service/default-config.json
  packages/identity-service/src/app.js
  packages/identity-service/src/audiusLibsInstance.js
Labels: size/S

#11605 Remove chain pubkey recovery.
  comms/discovery/pubkeystore/backfill.go
Labels: size/M

#11606 [PAY-4021] Address bug bash comments for play count milestones
  packages/common/src/store/pages/audio-rewards/slice.ts
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/integration_tests/challenges/test_play_count_milestones_challenge.py
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/discovery-provider/src/challenges/play_count_milestone_10000_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_1000_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_250_challenge.py
  packages/discovery-provider/src/challenges/play_count_milestone_challenge_base.py
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
  packages/web/src/common/store/social/tracks/recordListen.ts
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/PlayCountMilestoneContent.tsx
Labels: size/L

#11607 Use hex in first weekly comment challenge specifier
  packages/discovery-provider/src/challenges/first_weekly_comment_challenge.py
Labels: size/XS

#11601 [C-5833] Avoid spreading queryResults
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/tan-query/utils/combineQueryStatuses.ts
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Labels: size/L

#11602 Process challenge events sequentially
  packages/discovery-provider/integration_tests/challenges/test_listen_streak_endless_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_referral_challenge.py
  packages/discovery-provider/integration_tests/challenges/test_trending_challenge.py
  packages/discovery-provider/src/challenges/challenge_event_bus.py
Labels: size/S

#11610 Add count for play count cards
  packages/common/src/utils/challenges.ts
  packages/web/src/common/store/pages/audio-rewards/sagas.ts
Labels: size/M

#11612 Revert "[C-5833] Avoid spreading queryResults (#11601)"
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/tan-query/utils/combineQueryStatuses.ts
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
  packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Labels: size/L

#11613 Improve AAO tool UI
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/L

#11614 Fix index_tastemaker tests
  packages/discovery-provider/integration_tests/tasks/test_index_tastemaker.py
Labels: size/S

#11616 Fix local eth ganache url
  packages/sdk/src/sdk/config/development.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
Labels: size/XS

#11615 [PAY-3998] Tastemaker challenge UI
  .changeset/hungry-pandas-destroy.md
  packages/common/src/models/AudioRewards.ts
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/src/challenges/tastemaker_challenge.py
  packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsLayout.tsx
  packages/mobile/src/components/challenge-rewards-drawer/TastemakerChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/challengeContentRegistry.ts
  packages/mobile/src/components/challenge-rewards-drawer/index.ts
  packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/sdk/src/sdk/api/challenges/types.ts
  packages/web/src/assets/fonts/emojis/smiling-face-licking-lips.png
  packages/web/src/pages/rewards-page/components/ChallengeRewards/hooks/useRewardIds.ts
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsLayout.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/TastemakerChallengeModalContent.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/challengeContentRegistry.ts
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/L

#11617 Add summary table to tastemaker mobile UI
  packages/mobile/src/components/challenge-rewards-drawer/TastemakerChallengeContent.tsx
Labels: size/XS

#11609 [C-5827] Tan-query profile reposts to main (web)
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/track/mobile/PlaylistTile.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/L

#11619 Remove unnecessary web3-core dep from SDK
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
  packages/sdk/src/sdk/services/EntityManager/types.ts
Labels: size/M

#11621 Add redis back to solana-relay
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json
Labels: size/XS

#11603 [C-5832] Typechecking for tan-query selector option
  packages/common/src/api/tan-query/developerApps.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useAudioTransactionsCount.ts
  packages/common/src/api/tan-query/useAuthorizedApps.ts
  packages/common/src/api/tan-query/useCollection.ts
  packages/common/src/api/tan-query/useCollectionByParams.ts
  packages/common/src/api/tan-query/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useCurrentAccount.ts
  packages/common/src/api/tan-query/useCurrentUser.ts
  packages/common/src/api/tan-query/useEmailInUse.ts
  packages/common/src/api/tan-query/useExploreContent.ts
  packages/common/src/api/tan-query/useMutedUsers.ts
  packages/common/src/api/tan-query/useRemixedTracks.ts
  packages/common/src/api/tan-query/useSalesAggregate.ts
  packages/common/src/api/tan-query/useTopArtists.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTrack.ts
  packages/common/src/api/tan-query/useTrackByPermalink.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByParams.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
Labels: size/L

#11622 Set pubkey for wallet if missing.
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/server/mutate_test.go
  comms/discovery/server/server.go
  comms/discovery/server/signed_request.go
Labels: size/M

#11623 Fix type errors that slipped through to main
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
Labels: size/S

#11598 move current block up so num accessible down below
  packages/discovery-provider/src/tasks/index_trending.py
Labels: size/S

#11625 Update TS for archiver to fix build errors
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/archiver/package.json
Labels: size/XS

#11627 Fix challenge reward sort
  packages/common/src/utils/challenges.ts
Labels: size/M

#11626 ⚠️ Misc reward QA fixes
  packages/common/src/utils/challenges.ts
  packages/discovery-provider/src/challenges/challenges.stage.json
  packages/mobile/src/assets/images/emojis/smiling-face-licking-lips.png
  packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ListenStreakReminderNotification.tsx
  packages/mobile/src/utils/challenges.tsx
  packages/web/src/app/web-player/WebPlayer.module.css
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
  packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
Labels: size/M

#11630 Check cache before trying to get key from peers.
  comms/discovery/server/server.go
Labels: size/XS

#11631 Refactor mobile banner code
  packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
Labels: size/M

#11632 [PAY-4025] Fix listen streak, comment challenge inconsistent state
  packages/discovery-provider/ddl/data/0125_listen_streak_comment_challenges/listen_streak_comment_challenges.csv
  packages/discovery-provider/ddl/migrations/0125_listen_streak_comment_challenges.sql
Labels: size/XXL

#11635 add on conflict fix
  packages/discovery-provider/ddl/migrations/0125_listen_streak_comment_challenges.sql
Labels: size/XS

#11636 Activate play count on prod
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/XS

#11637 Batch events better
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/index_challenges.py
Labels: size/M

#11641 Update cooldown days
  packages/discovery-provider/src/challenges/challenges.json
Labels: size/S

#11640 Bump iOS and Android build numbers
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/AudiusReactNative/Info.plist
Labels: size/XS

#11642 add try around lock release in index_core.py
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/XS

#11643 always use local web3 provider
  packages/discovery-provider/src/utils/web3_provider.py
Labels: size/S

#11645 add try wrap to engagement task lock
  packages/discovery-provider/src/tasks/create_engagement_notifications.py
Labels: size/XS

#11644 Fix purchase button layout on web track page
  packages/web/src/components/track/GatedContentSection.tsx
Labels: size/M

#11647 Dedupe track download indexing
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Labels: size/S

#11648 hotfix: Route DM CreateChat RPCs to AAO
  comms/discovery/rpcz/apply.go
  comms/discovery/rpcz/validator.go
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/nginx_ingress.conf
Labels: size/M

#11649 Recover pubkeys from core_transactions table
  comms/discovery/pubkeystore/backfill.go
  comms/discovery/pubkeystore/recover.go
  comms/discovery/pubkeystore/recover_core.go
  comms/go.mod
  comms/go.sum
Labels: size/L

#11638 Improve dashboard loading perf
  packages/protocol-dashboard/src/services/Audius/setup.ts
  packages/protocol-dashboard/src/services/SelfId/SelfId.ts
  packages/protocol-dashboard/src/services/SelfId/index.ts
  packages/protocol-dashboard/src/services/SelfId/types.ts
  packages/protocol-dashboard/src/store/cache/user/hooks.ts
  packages/protocol-dashboard/src/utils/fetch.ts
  packages/protocol-dashboard/src/utils/routes.ts
Labels: size/L

#11646 Raise stem limit to 200
  packages/web/src/components/edit/fields/StemFilesView.tsx
Labels: size/XS

#11620 [C-5839] Profile tracks to main (web)
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/utils/formatTrackData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Labels: size/XL

#11651 Properly expose and run archiver in compose stack
  dev-tools/compose/docker-compose.pedalboard.dev.yml
  dev-tools/compose/docker-compose.pedalboard.prod.yml
  dev-tools/compose/nginx_ingress.conf
  packages/discovery-provider/nginx_conf/nginx_container.conf
  packages/discovery-provider/plugins/pedalboard/apps/archiver/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/archiver/src/index.ts
  packages/discovery-provider/plugins/pedalboard/apps/archiver/src/workers/createStemsArchive/createStemsArchive.ts
  packages/discovery-provider/plugins/pedalboard/apps/archiver/src/workers/ensureTempDirectory.ts
Labels: size/M

#11650 [PAY-4039] Start tastemaker challenge only after certain block
  packages/discovery-provider/src/challenges/tastemaker_challenge.py
  packages/discovery-provider/src/queries/get_health.py
Labels: size/M

#11628 [C-5833] Avoid spreading tan-query results
  packages/common/src/api/tan-query/comments/useCommentReplies.ts
  packages/common/src/api/tan-query/comments/useComments.ts
  packages/common/src/api/tan-query/comments/useTrackComments.ts
  packages/common/src/api/tan-query/comments/useUserComments.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/useAiTracks.ts
  packages/common/src/api/tan-query/useAudioTransactions.ts
  packages/common/src/api/tan-query/useCollectionFavorites.ts
  packages/common/src/api/tan-query/useCollectionReposts.ts
  packages/common/src/api/tan-query/useCollections.ts
  packages/common/src/api/tan-query/useFeed.ts
  packages/common/src/api/tan-query/useFollowers.ts
  packages/common/src/api/tan-query/useFollowing.ts
  packages/common/src/api/tan-query/useLibraryCollections.ts
  packages/common/src/api/tan-query/useLibraryTracks.ts
  packages/common/src/api/tan-query/useMutualFollowers.ts
  packages/common/src/api/tan-query/useNotifications.ts
  packages/common/src/api/tan-query/usePremiumTracks.ts
  packages/common/src/api/tan-query/useProfileReposts.ts
  packages/common/src/api/tan-query/useProfileTracks.ts
  packages/common/src/api/tan-query/usePurchasers.ts
  packages/common/src/api/tan-query/usePurchases.ts
  packages/common/src/api/tan-query/useRelatedArtists.ts
  packages/common/src/api/tan-query/useRemixers.ts
  packages/common/src/api/tan-query/useRemixes.ts
  packages/common/src/api/tan-query/useSales.ts
  packages/common/src/api/tan-query/useSearchResults.ts
  packages/common/src/api/tan-query/useTopArtistsInGenre.ts
  packages/common/src/api/tan-query/useTrackFavorites.ts
  packages/common/src/api/tan-query/useTrackHistory.ts
  packages/common/src/api/tan-query/useTrackPageLineup.ts
  packages/common/src/api/tan-query/useTrackReposts.ts
  packages/common/src/api/tan-query/useTracks.ts
  packages/common/src/api/tan-query/useTrendingPlaylists.ts
  packages/common/src/api/tan-query/useTrendingUnderground.ts
  packages/common/src/api/tan-query/useUSDCTransactions.ts
  packages/common/src/api/tan-query/useUserAlbums.ts
  packages/common/src/api/tan-query/useUserPlaylists.ts
  packages/common/src/api/tan-query/useUsers.ts
  packages/common/src/api/tan-query/utils/combineQueryStatuses.ts
  packages/common/src/api/tan-query/utils/index.ts
  packages/common/src/api/tan-query/utils/useLineupQuery.ts
  packages/common/src/api/tan-query/utils/useQueries.tsx
  packages/web/src/components/tracks-table/TrackTableLineup.tsx
  packages/web/src/components/tracks-table/TracksTable.tsx
  packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx
  packages/web/src/pages/search-page/search-results/AlbumResults.tsx
  packages/web/src/pages/search-page/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
Labels: size/XL

#11656 Add run-always cursor rules
  .cursor/rules/run-always.mdc
Labels: size/S

#11655 [PE-5844] Migrate track selector usages to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/models.ts
  packages/common/src/hooks/content/useIsTrackUnlockable.ts
  packages/common/src/hooks/useGatedContent.ts
  packages/common/src/hooks/useTrackDogEar.tsx
  packages/common/src/store/cache/tracks/selectors.ts
  packages/mobile/src/components/image/TrackImage.tsx
  packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx
  packages/mobile/src/components/lineup-tile/TrackTileStats.tsx
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx
  packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/mobile/src/screens/track-screen/DownloadRow.tsx
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/mobile/src/screens/track-screen/TrackScreen.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/components/link/TrackLink.tsx
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx
  packages/web/src/components/play-bar/desktop/components/SocialActions.tsx
  packages/web/src/components/remix-card/ConnectedRemixCard.tsx
  packages/web/src/components/stats/FavoriteStats.tsx
  packages/web/src/components/stats/RepostStats.tsx
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/components/track/TrackTileMetrics.tsx
  packages/web/src/components/track/TrackTileStats.tsx
  packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
  packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx
  packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
  packages/web/src/pages/remixes-page/components/desktop/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/RemixesPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XL

#11660 Faster + more correct mutuals endpoint.
  packages/discovery-provider/integration_tests/queries/test_mutual_follows.py
  packages/discovery-provider/src/api/v1/users.py
  packages/discovery-provider/src/queries/get_follow_intersection_users.py
Labels: size/L

#11661 Add archiver to image builds
  .circleci/src/commands/@docker-commands.yml
  .circleci/src/workflows/discovery.yml
  .circleci/src/workflows/release.yml
Labels: size/XS

#11662 [PE-5849] Change listen streak window to 16-48 hours
  packages/discovery-provider/integration_tests/challenges/test_listen_streak_endless_challenge.py
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Labels: size/L

#11663 fix missing types for archiver
  package-lock.json
  packages/discovery-provider/plugins/pedalboard/apps/archiver/package.json
Labels: size/XS

#11666 hotfix: Unblock payment router indexing with duplicate wallets
  packages/discovery-provider/src/tasks/index_payment_router.py
Labels: size/XS

#11667 hotfix: Prioritize users with handles when fetching users by wallet
  packages/discovery-provider/src/queries/get_users_account.py
Labels: size/XS

#11664 [PE-5863] Migrate Follow/Unfollow user to tan-query (#11316)
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useFollowUser.ts
  packages/common/src/api/tan-query/useUnfollowUser.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/social/users/actions.ts
  packages/common/src/store/tipping/slice.ts
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
  packages/web/src/common/store/social/users/errorSagas.ts
  packages/web/src/common/store/social/users/sagas.ts
  packages/web/src/common/store/social/users/store.test.ts
  packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/stat-banner/StatBanner.tsx
  packages/web/src/components/track-overflow-modal/ConnectedMobileOverflowModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/UnfollowConfirmationModal.tsx
  packages/web/src/components/unfollow-confirmation-modal/components/UnfollowConfirmationModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/UserListV2.tsx
  packages/web/src/pages/collection-page/CollectionPage.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/TrackPage.tsx
  packages/web/src/pages/track-page/TrackPageProvider.tsx
Labels: size/XXL

#11668 Gate new listen streak specifier on block number
  packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Labels: size/M

#11669 [PE-5865] Fix list index out of range for audio matching challenges
  packages/discovery-provider/src/challenges/audio_matching_challenge.py
Labels: size/XS

#11670 Fix track screen params
  packages/common/src/api/tan-query/useTrackByParams.ts
Labels: size/XS

#11653 [PE-5843] Migrate user selector usages to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/useUser.ts
  packages/common/src/api/tan-query/useUserByHandle.ts
  packages/common/src/store/cache/users/selectors.ts
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
  packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/components/core/UserDisplayName.tsx
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/components/image/CoverPhoto.tsx
  packages/mobile/src/components/image/UserImage.tsx
  packages/mobile/src/components/lineup-tile/VanityMetrics.tsx
  packages/mobile/src/components/overflow-menu-drawer/ProfileOverflowMenuDrawer.tsx
  packages/mobile/src/components/user-badges/UserBadgesV2.tsx
  packages/mobile/src/components/user-link/UserLink.tsx
  packages/mobile/src/components/user-list/UserCard.tsx
  packages/mobile/src/components/user/FollowButton.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListScreen.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx
  packages/mobile/src/screens/profile-screen/TipAudioButton.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/web/src/components/artist/ArtistPopover.tsx
  packages/web/src/components/avatar/Avatar.tsx
  packages/web/src/components/collection/CollectionCard.test.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx
  packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
  packages/web/src/components/user-card/UserCard.test.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/hooks/useCollectionCoverArt.ts
  packages/web/src/hooks/useCoverPhoto.ts
  packages/web/src/hooks/useProfilePicture.ts
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
  packages/web/src/pages/pay-and-earn-page/components/BuyerUserLink.tsx
  packages/web/src/test/test-utils.tsx
Labels: size/XL

#11671 Fix buy audio swap and polling
  packages/web/src/services/audius-backend/BuyAudio.ts
  packages/web/src/store/application/ui/buy-audio/sagas.ts
Labels: size/M

#11673 Fix search layout issues
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/user-card/UserCard.tsx
Labels: size/XS

#11654 Manual block/allow from AAO
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/L

#11665 [PE-5845] Migrate collection selector usages to tan-query
  packages/common/src/api/collection.ts
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/models.ts
  packages/common/src/hooks/useCollectionDogEar.tsx
  packages/common/src/store/cache/collections/selectors.ts
  packages/mobile/src/components/collection-list/CollectionCard.tsx
  packages/mobile/src/components/delete-playlist-confirmation-drawer/DeletePlaylistConfirmationDrawer.tsx
  packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
  packages/mobile/src/components/drawers/RemoveDownloadedCollectionDrawer.tsx
  packages/mobile/src/components/duplicate-add-confirmation-drawer/DuplicateAddConfirmationDrawer.tsx
  packages/mobile/src/components/image/CollectionImage.tsx
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileMetrics.tsx
  packages/mobile/src/components/lineup-tile/CollectionTileStats.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/types.ts
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/overflow-menu-drawer/CollectionOverflowMenuDrawer.tsx
  packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/collection/CollectionTileMetrics.tsx
  packages/web/src/components/collection/CollectionTileStats.tsx
  packages/web/src/components/collection/desktop/Artwork.tsx
  packages/web/src/components/collection/desktop/FavoriteButton.tsx
  packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
  packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
  packages/web/src/components/collection/desktop/PublishButton.tsx
  packages/web/src/components/collection/desktop/RepostButton.tsx
  packages/web/src/components/collection/desktop/ViewerActionButtons.tsx
  packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/edit-collection/DeleteCollectionConfirmationModal.tsx
  packages/web/src/components/link/CollectionLink.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/CollectionNavItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
Labels: size/XL

#11677 Notifications performance improvements
  packages/discovery-provider/ddl/migrations/0127_notification_announcement_index.sql
  packages/discovery-provider/src/tasks/create_engagement_notifications.py
Labels: size/XS

#11680 potential undefined
  monitoring/healthz/src/pages/Nodes.tsx
Labels: size/XS
