Repository AudiusProject/apps, pull requests merged in 2025-05, with the labels that each got.

#12009 [API-103] Prevent multiple users with the same wallet address
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Labels: size/L

#12011 Allow audio swap via sol relay
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
Labels: size/S

#11985 CLM report: use first album.
  packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
Labels: size/S

#12008 Misc upload improvements
  packages/common/src/models/Analytics.ts
  packages/common/src/store/ui/stripe-modal/sagas.ts
  packages/sdk/src/sdk/services/Storage/Storage.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#12012 Fix user handle
  packages/discovery-provider/ddl/migrations/0137_patch_user_handle.sql
Labels: size/XS

#12013 Update UserLinks to correctly contain and center text
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/collection/desktop/CollectionHeader.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
Labels: size/M

#12014 Fallback to null instead of 0
  packages/common/src/hooks/useAudioBalance.ts
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/harmony/src/components/balance-pill/BalancePill.tsx
  packages/harmony/src/components/balance-pill/types.ts
  packages/mobile/src/harmony-native/components/BalancePill/BalancePill.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/useNavConfig.tsx
  packages/web/src/components/nav/desktop/WalletsNestedContent.tsx
Labels: size/M

#12016 Add merged search / explore page
  packages/common/src/services/remote-config/feature-flags.ts
  packages/web/src/assets/img/publicSite/imageSearchHeaderBackground.webp
  packages/web/src/assets/img/publicSite/imageSearchHeaderBackground@2x.webp
  packages/web/src/pages/explore-page/ExplorePage.tsx
  packages/web/src/pages/explore-page/collections.ts
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
Labels: size/L

#11998 Add global sentry error logging for tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/utils/defaultConfig.ts
  packages/common/src/api/tan-query/utils/defaultRetryConfig.ts
  packages/mobile/src/services/query-client.ts
  packages/web/src/services/query-client.ts
Labels: size/M

#12007 [PE-6059] Deprecate audius-query purchases.ts
  packages/common/src/api/index.ts
  packages/common/src/api/purchases.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/collection/useCollections.ts
  packages/common/src/api/tan-query/purchases/usePurchases.ts
  packages/common/src/api/tan-query/purchases/useSales.ts
  packages/common/src/api/tan-query/tracks/useTracks.ts
  packages/common/src/api/tan-query/users/useUsers.ts
  packages/common/src/api/tan-query/utils/combineQueryResults.ts
  packages/common/src/api/track.ts
  packages/web/src/hooks/useErrorPageOnFailedStatus.ts
  packages/web/src/hooks/useTrackCoverArt.ts
  packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
  packages/web/src/pages/pay-and-earn-page/components/TrackNameWithArtwork.tsx
Labels: size/XL

#12022 Add pinned comment challenge to valid challenges enum
  .changeset/fair-ears-look.md
  packages/sdk/src/sdk/api/challenges/types.ts
Labels: size/S

#12017 Add content nodes to lookup table script
  packages/sdk/src/sdk/scripts/manageRewardsLookupTable.ts
Labels: size/M

#12025 Update to use pin icon
  packages/web/src/assets/fonts/emojis/pin.png
  packages/web/src/assets/styles/emoji.css
  packages/web/src/pages/rewards-page/config.tsx
Labels: size/XS

#12021 [PE-6085] Remix contest started notification
  packages/common/src/adapters/notification.ts
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/ddl/functions/handle_event.sql
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_started_notification.py
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/RemixContestStartedNotification.tsx
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/Notification.ts
  packages/sdk/src/sdk/api/generated/full/models/RemixContestStartedNotification.ts
  packages/sdk/src/sdk/api/generated/full/models/RemixContestStartedNotificationAction.ts
  packages/sdk/src/sdk/api/generated/full/models/RemixContestStartedNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/components/notification/Notification/Notification.tsx
  packages/web/src/components/notification/Notification/RemixContestStartedNotification.tsx
  packages/web/src/components/notification/Notification/components/TrackContent.tsx
Labels: size/XL

#12023 Add support for claiming all challenges via bridge (in dev) to SDK
  .changeset/tough-ways-bow.md
  dev-tools/compose/docker-compose.discovery.prod.yml
  dev-tools/compose/nginx_ingress.conf
  dev-tools/startup/discovery-provider.sh
  packages/commands/src/index.ts
  packages/commands/src/misc/claim-reward.ts
  packages/discovery-provider/scripts/createSender.ts
  packages/discovery-provider/src/challenges/challenges.dev.json
  packages/sdk/src/sdk/api/challenges/ChallengesApi.ts
  packages/sdk/src/sdk/api/challenges/types.ts
Labels: size/L

#12028 [PE-6044] Add remix contest section to explore page
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/collection/useExploreContent.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/harmony/src/components/text-link/TextLink.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
  packages/web/src/pages/explore-page/components/desktop/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedRemixContests.tsx
  packages/web/src/pages/explore-page/components/desktop/TrackArtCard.tsx
  packages/web/src/pages/track-page/components/desktop/RemixContestDetailsTab.tsx
Labels: size/L

#12030 Hotfix trackByPermalink not showing correct gated status
  packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
Labels: size/S

#12029 Fix remix contest section submission count
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
Labels: size/S

#12020 [PE-6095] Deprecate audius-query user saga fetches
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/tracks/useDeleteTrack.ts
  packages/common/src/api/tan-query/users/account/useCurrentUser.ts
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/common/src/api/tan-query/users/useUpdateUser.ts
  packages/common/src/api/user.ts
  packages/common/src/store/account/sagas.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/hooks/useConnectAndAssociateWallets.ts
Labels: size/L

#12034 Fix formatting issues for artist links on web and mobile web
  packages/web/src/components/track/GiantTrackTile.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/XS

#12033 Fix remix contest started notif test
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_started_notification.py
Labels: size/XS

#12037 Fix account switcher toggle
  packages/common/src/api/account.ts
  packages/common/src/api/tan-query/comments/useGetTrackCommentNotificationSetting.ts
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
Labels: size/L

#12039 Fix GiantTrackTile skeletons
  packages/web/src/components/track/GiantArtwork.module.css
  packages/web/src/components/track/GiantTrackTile.module.css
  packages/web/src/components/track/GiantTrackTile.tsx
Labels: size/S

#12024 [PE-6055] Deprecate audius-query topArtists
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/topArtists.ts
  packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx
  packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Labels: size/L

#12042 Fix decimal places on balance
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/common/src/utils/decimal.ts
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/M

#12035 [PE-6089] Remix co-signed notification updates
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCosignNotification.tsx
  packages/web/src/components/notification/Notification/RemixCosignNotification.tsx
Labels: size/S

#12041 Refactor remix contest notifications to single task
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ended_notification.py
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ending_soon_notification.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/create_remix_contest_notifications.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/__init__.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ended.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ending_soon.py
Labels: size/L

#12043 fix health check block diff default
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/XS

#12051 Fix ffmpeg-kit-react-native podspec path
  packages/mobile/ios/Podfile
  packages/mobile/ios/Podfile.lock
Labels: size/XS

#12052 Fix android release needing cached libs
  .circleci/src/jobs/@mobile-jobs.yml
Labels: size/XS

#12053 Revert "Refactor remix contest notifications to single task"
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ended_notification.py
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ending_soon_notification.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/create_remix_contest_ended_notifications.py
  packages/discovery-provider/src/tasks/create_remix_contest_ending_soon_notifications.py
  packages/discovery-provider/src/tasks/create_remix_contest_notifications.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/__init__.py
Labels: size/L

#12048 Fix DN tests: Add challenge_event_bus to tests
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_email_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_index_notification.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_index_playlist_seen.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_index_skip_tx.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_tip_reactions.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
Labels: size/M

#12054 Refactor remix contest notifications to single task V2
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ended_notification.py
  packages/discovery-provider/integration_tests/tasks/test_remix_contest_ending_soon_notification.py
  packages/discovery-provider/src/app.py
  packages/discovery-provider/src/tasks/create_remix_contest_notifications.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/__init__.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ended.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ending_soon.py
Labels: size/L

#12055 Remove RemixContestStarted from notifs valid types
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
Labels: size/XS

#12044 [PE-6132] Artist-side remix contest ended notification
  .changeset/giant-files-explain.md
  packages/common/src/adapters/notification.ts
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ended_notification.py
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ended.py
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndedNotification.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndedNotificationAction.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndedNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/Notification.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/components/notification/Notification/ArtistRemixContestEndedNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/XL

#12061 [PE-6058] Delete aquery search
  packages/common/src/api/reducer.ts
  packages/common/src/api/search.ts
  packages/common/src/models/Search.ts
  packages/common/src/utils/route.ts
Labels: size/L

#12062 Fix notif test with missing cooldown days and fix remix contest typing
  packages/discovery-provider/integration_tests/tasks/test_create_engagement_notifications.py
  packages/discovery-provider/integration_tests/utils.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
Labels: size/S

#12045 [QA-2085] Fix mobile top supporters user list
  packages/common/src/store/tipping/index.ts
  packages/common/src/store/tipping/selectors.ts
  packages/common/src/store/tipping/slice.ts
  packages/common/src/store/tipping/types.ts
  packages/common/src/store/tipping/utils.ts
  packages/common/src/store/user-list/index.ts
  packages/common/src/store/user-list/selectors.ts
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingList.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTileSkeleton.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
  packages/mobile/src/screens/profile-screen/ProfileHeader/ViewAllSupportingTile.tsx
  packages/mobile/src/screens/user-list-screen/SupporterInfo.tsx
  packages/mobile/src/screens/user-list-screen/SupportingInfo.tsx
  packages/mobile/src/screens/user-list-screen/Tip.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
Labels: size/XXL

#12049 [QA-2089] Fix tip success icon
  packages/harmony/src/components/completion-check/CompletionCheck.tsx
  packages/harmony/src/components/completion-check/types.ts
  packages/web/src/components/tipping/tip-audio/TipAudio.module.css
  packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx
Labels: size/S

#12057 [PE-6062] Migrate developer apps to tan-query
  packages/common/src/api/authorizedApps.ts
  packages/common/src/api/developerApps.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/authorized-apps/developerApps.ts
  packages/common/src/api/tan-query/authorized-apps/useRemoveAuthorizedApp.ts
  packages/common/src/api/tan-query/developer-apps/developerApps.ts
  packages/common/src/api/tan-query/developer-apps/useAddDeveloperApp.ts
  packages/common/src/api/tan-query/developer-apps/useDeleteDeveloperApp.ts
  packages/common/src/api/tan-query/developer-apps/useDeveloperApps.ts
  packages/common/src/api/tan-query/developer-apps/useEditDeveloperApp.ts
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/YourAppsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/EditAppPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
Labels: size/XL

#12068 Update routes to fix profile page and track pages not rendering
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/S

#12038 [PE-6065] Deprecate audius-query account.ts
  packages/common/src/api/account.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/users/account/useApproveManagedAccount.ts
  packages/common/src/api/tan-query/users/account/useCurrentAccount.ts
  packages/common/src/api/tan-query/users/account/useManagedAccounts.ts
  packages/common/src/api/tan-query/users/account/useManagers.ts
  packages/common/src/api/tan-query/users/account/useRemoveManager.ts
  packages/common/src/api/tan-query/users/account/useRequestAddManager.ts
  packages/common/src/api/tan-query/users/account/useResetPassword.ts
  packages/common/src/api/tan-query/users/account/useWalletUser.ts
  packages/common/src/api/tan-query/utils/isValidId.ts
  packages/common/src/hooks/useAccountSwitcher.ts
  packages/common/src/store/pages/chat/selectors.ts
  packages/mobile/src/screens/reset-password-screen/ResetPasswordScreen.tsx
  packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
  packages/web/src/hooks/useManagedAccountNotAllowedRedirect.ts
  packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagedUserListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagerListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
  packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
Labels: size/XL

#12060 [PE-6064] Migrate authorized apps to tan-query
  packages/common/src/api/authorizedApps.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/authorized-apps/useRemoveAuthorizedApp.ts
  packages/common/src/api/tan-query/developer-apps/useAddDeveloperApp.ts
  packages/common/src/api/tan-query/developer-apps/useDeleteDeveloperApp.ts
  packages/common/src/api/tan-query/developer-apps/useDeveloperApps.ts
  packages/common/src/api/tan-query/developer-apps/useEditDeveloperApp.ts
  packages/common/src/schemas/developerApps.ts
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/AuthorizedAppListItem.tsx
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/AuthorizedAppsSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/RemoveAppConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/YourAppsPage.tsx
  packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/types.ts
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/CreateNewAppPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeleteAppConfirmationPage.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsModal.module.css
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsModal.tsx
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/YourAppsPage.tsx
Labels: size/L

#12070 Fix developer app lint
  packages/web/src/pages/settings-page/components/desktop/DeveloperApps/EditAppPage.tsx
Labels: size/XS

#12058 [PE-6113] Add linear gradient background to paper
  packages/harmony/src/components/layout/Box/Box.tsx
  packages/harmony/src/foundations/color/semantic.ts
Labels: size/XS

#12071 Increase bundlesize max chunk size
  packages/web/bundlesize.prod.config.json
  packages/web/bundlesize.stage.config.json
Labels: size/XS

#12056 [API-113] Fix local dev not setting blockchainUserId and handle in identity
  .circleci/src/jobs/@integration-jobs.yml
  packages/commands/src/utils.ts
  packages/common/src/store/account/sagas.ts
  packages/discovery-provider/plugins/pedalboard/apps/archiver/src/workers/createStemsArchive/createStemsArchive.ts
  packages/identity-service/src/authMiddleware.js
  packages/identity-service/src/index.ts
  packages/sdk/src/sdk/api/challenges/ChallengesApi.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/sdk/src/sdk/sdk.ts
  packages/web/e2e/auth.setup.ts
  packages/web/e2e/data.seed.ts
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/L

#12069 [PE-6133] Artist remix contest ending soon notification
  .changeset/dirty-dots-think.md
  packages/common/src/adapters/notification.ts
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ending_soon_notification.py
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/discovery-provider/src/tasks/create_remix_contest_notifications.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ending_soon.py
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndingSoonNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/index.ts
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndingSoonNotification.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndingSoonNotificationAction.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestEndingSoonNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/Notification.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/components/notification/Notification/ArtistRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/XL

#12036 Fix challenge count num in AAO UI
  packages/discovery-provider/ddl/functions/get_user_score.sql
Labels: size/XS

#12066 Ensure python 3.11 is installed
  .circleci/src/jobs/@web-jobs.yml
Labels: size/S

#12065 [PE-6060] Migrate library collections to tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/library.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/tan-query/collection/useLibraryCollections.ts
  packages/common/src/api/tan-query/lineups/useLibraryTracks.ts
  packages/common/src/api/tan-query/lineups/useLineupQuery.ts
  packages/common/src/api/tan-query/purchases/usePurchases.ts
  packages/common/src/api/tan-query/purchases/useSales.ts
  packages/common/src/api/tan-query/purchases/useUSDCTransactions.ts
  packages/common/src/api/tan-query/search/useSearchResults.ts
  packages/common/src/api/tan-query/types.ts
  packages/common/src/api/tan-query/utils/index.ts
  packages/common/src/api/tan-query/utils/infiniteQueryLoadNextPage.ts
  packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
  packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
  packages/mobile/src/screens/favorites-screen/useLibraryCollections.ts
  packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx
  packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
  packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
  packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
  packages/web/src/pages/saved-page/hooks/useLibraryCollections.tsx
Labels: size/XL

#12072 Few dev tools updates
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/hooks/useEnvironment.ts
  packages/web/src/hooks/useIsDevOrStaging.ts
  packages/web/src/pages/dev-tools/DevTools.tsx
  packages/web/src/pages/dev-tools/messages.ts
Labels: size/M

#12074 [PE-6048] Update embed track cards for remix contests
  packages/embed/src/assets/img/iconTrophy.svg
  packages/embed/src/components/app.jsx
  packages/embed/src/components/track/TrackPlayerCard.jsx
  packages/embed/src/components/track/TrackPlayerCard.module.css
  packages/embed/src/components/track/TrackPlayerCompact.jsx
  packages/embed/src/components/track/TrackPlayerCompact.module.css
  packages/embed/src/components/track/TrackPlayerContainer.jsx
  packages/embed/src/util/BedtimeClient.js
Labels: size/L

#12076 Drop mobile builds in PRs
  .circleci/src/workflows/mobile.yml
Labels: size/S

#12073 [PE-6056|PE-6061|PE-6054] Migrate playlist suggested tracks from a-query
  packages/common/src/api/favorites.ts
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/suggestedTracks.ts
  packages/common/src/api/tan-query/tracks/useSuggestedPlaylistTracks.ts
  packages/common/src/api/trending.ts
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/web/src/components/suggested-tracks/SuggestedTracks.tsx
Labels: size/L

#12079 [PE-6130] Small notif copy change
  packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndedNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestEndedNotification.tsx
Labels: size/XS

#12077 [QA-2091] Fix mobile sign-up route-on-exit
  packages/eslint-config-audius/src/index.js
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/sign-up-page/components/NavHeader.tsx
  packages/web/src/pages/track-page/components/mobile/DownloadSection.tsx
  packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Labels: size/S

#12082 [PE-6047] Fix track page play
  packages/common/src/api/tan-query/lineups/useTrackPageLineup.ts
  packages/common/src/api/tan-query/tracks/useTrackByParams.ts
  packages/mobile/src/screens/track-screen/TrackScreenLineup.tsx
  packages/web/src/common/store/queue/sagas.ts
Labels: size/M

#12087 Handle TokenAccountNotFoundError in recoverPurchaseIfNecessary
  packages/common/src/store/buy-usdc/sagas.ts
Labels: size/S

#12090 [API-112] Add AAO block/unblock commands to audius-cmd
  packages/commands/src/index.ts
  packages/commands/src/misc/aao.ts
  packages/commands/src/utils.ts
Labels: size/M

#12088 [API-111] [API-110] Preregister local dev senders
  dev-tools/startup/discovery-provider.sh
  packages/discovery-provider/scripts/createSender.ts
  solana-programs/Dockerfile.dev
  solana-programs/README.md
  solana-programs/fixtures/aao-sender.json
  solana-programs/fixtures/cn1-sender.json
  solana-programs/fixtures/cn2-sender.json
  solana-programs/fixtures/cn3-sender.json
  solana-programs/fixtures/cn4-sender.json
  solana-programs/fixtures/dn1-sender.json
  solana-programs/scripts/init-dev-fixtures.sh
Labels: size/L

#12089 Fix AAO on local dev by querying for wallet instead of user ID
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
  packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Labels: size/S

#12083 Migrate withdrawals tab logic and remove user aq files
  packages/common/src/api/index.ts
  packages/common/src/api/reducer.ts
  packages/common/src/api/user.ts
  packages/common/src/store/reducers.ts
  packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Labels: size/L

#12078 [PE-6086] Remix contest submission milestone notifs
  .changeset/unlucky-seas-hope.md
  packages/common/src/adapters/notification.ts
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/ddl/functions/handle_track.sql
  packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_submissions_notification.py
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestSubmissionsNotification.tsx
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestSubmissionsNotification.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestSubmissionsNotificationAction.ts
  packages/sdk/src/sdk/api/generated/full/models/ArtistRemixContestSubmissionsNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/Notification.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
  packages/web/src/components/notification/Notification/ArtistRemixContestSubmissionsNotification.tsx
  packages/web/src/components/notification/Notification/Notification.tsx
Labels: size/XL

#12091 30 second interval for remix notifs
  packages/discovery-provider/src/app.py
Labels: size/XS

#12092 Fix remix contest web notif links
  packages/web/src/components/notification/Notification/ArtistRemixContestEndedNotification.tsx
  packages/web/src/components/notification/Notification/ArtistRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/ArtistRemixContestSubmissionsNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestEndedNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestStartedNotification.tsx
Labels: size/M

#11937 [PE-6141] Add swap functionality and swap UI for Wallet update M2
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/jupiter/constants.ts
  packages/common/src/api/tan-query/jupiter/types.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/api/tan-query/jupiter/utils.ts
  packages/common/src/messages/buySell.ts
  packages/common/src/services/Jupiter.ts
  packages/common/src/services/remote-config/feature-flags.ts
  packages/harmony/src/assets/icons/JupiterLogo.svg
  packages/harmony/src/icons/utilityIcons.ts
  packages/mobile/src/harmony-native/icons.tsx
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/constants.ts
  packages/web/src/components/buy-sell-modal/hooks/index.ts
  packages/web/src/components/buy-sell-modal/hooks/useTokenAmountFormatting.ts
  packages/web/src/components/buy-sell-modal/hooks/useTokenSwapForm.ts
  packages/web/src/components/buy-sell-modal/schemas/swapFormSchema.ts
  packages/web/src/components/buy-sell-modal/types.ts
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/XXL

#12094 [PE-6158] Remix contest push notifications
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestEnded.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestEndingSoon.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestSubmissions.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestEnded.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestEndingSoon.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestStarted.test.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestEnded.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestEndingSoon.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestSubmissions.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestEnded.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestEndingSoon.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestStarted.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
  packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
Labels: size/XXL

#12098 Update import to fix main
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
Labels: size/XS

#12101 Fix mobile remix contest notifs
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndingSoonNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestSubmissionsNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndingSoonNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestStartedNotification.tsx
Labels: size/M

#12102 Fix download all follow gated logic on web
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/track-page/components/mobile/DownloadSection.tsx
Labels: size/M

#12100 Fix missing remix contest section
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
Labels: size/S

#12103 [PE-6160] Add new stacked balance and error messages
  packages/common/src/messages/buySell.ts
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/constants.ts
  packages/web/src/components/buy-sell-modal/types.ts
Labels: size/L

#12080 Fix recent searches persisting in IndexedDB
  packages/common/src/utils/route.ts
  packages/web/src/app/AppProviders.tsx
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/components/search-bar/SearchBarResult.tsx
  packages/web/src/pages/explore-page/collections.ts
  packages/web/src/store/configureStore.ts
Labels: size/L

#12108 Web NotificationBody to UserLink
  packages/web/src/components/notification/Notification/FanRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/components/NotificationBody.tsx
Labels: size/S

#12110 [PE-6173] Add confirm swap to modal
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/messages/buySell.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/ConfirmSwapScreen.tsx
  packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/USDCBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/hooks/index.ts
  packages/web/src/components/buy-sell-modal/hooks/useBuySellScreen.ts
  packages/web/src/components/buy-sell-modal/hooks/useBuySellSwap.ts
  packages/web/src/components/buy-sell-modal/hooks/useBuySellTabs.ts
  packages/web/src/components/buy-sell-modal/hooks/useBuySellTransactionData.ts
  packages/web/src/components/buy-sell-modal/index.ts
  packages/web/src/components/buy-sell-modal/types.ts
Labels: size/XL

#12112 [PE-6177] Add loading state to confirmation buy/sell flow
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/buy-sell-modal/USDCBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/hooks/useBuySellSwap.ts
  packages/web/src/components/modal-loading/ModalLoading.tsx
  packages/web/src/components/modal-loading/index.ts
Labels: size/L

#12113 [PE-6166, PE-6167] Add Pick Winners Page for remix contests
  packages/common/src/messages/remixes.ts
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/pick-winners/lineup/actions.ts
  packages/common/src/store/pages/pick-winners/lineup/reducer.ts
  packages/common/src/store/pages/pick-winners/selectors.ts
  packages/common/src/store/pages/pick-winners/slice.ts
  packages/common/src/store/reducers.ts
  packages/common/src/utils/route.ts
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
  packages/web/src/pages/pick-winners-page/hooks.ts
  packages/web/src/pages/remixes-page/RemixesPage.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
  packages/web/src/utils/route.ts
Labels: size/L

#12115 More remix contest notif fixes
  packages/web/src/components/notification/Notification/ArtistRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/ArtistRemixContestSubmissionsNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestEndedNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestEndingSoonNotification.tsx
  packages/web/src/components/notification/Notification/FanRemixContestStartedNotification.tsx
Labels: size/M

#12118 [PE-6185] Remixes QA pass
  packages/common/src/messages/remixes.ts
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/src/components/track/CardTitle.tsx
  packages/web/src/components/track/DownloadRow.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
Labels: size/M

#12117 [PE-6183] Contest entries filter selected by default
  packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Labels: size/XS

#12119 Fix redux persist in web causing navigation issues
  packages/web/src/store/configureStore.ts
Labels: size/S

#12120 Include contest entries param in remix submissions tab
  packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Labels: size/XS

#12122 Fix bug where queryUser was not priming old cache
  packages/common/src/api/tan-query/saga-utils/queryUser.ts
  packages/common/src/api/tan-query/users/useUser.ts
Labels: size/M

#12116 Fix web track page lineup
  packages/common/src/api/tan-query/tracks/useTrackByParams.ts
Labels: size/S

#12123 Add explore carousel, label spotlight, mood tags
  packages/common/src/api/tan-query/collection/useExploreContent.ts
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/search-page/SearchResults.tsx
  packages/web/src/pages/search-page/search-results/TrackResults.tsx
Labels: size/L

#12125 Fix ios build by adding back prod bundle logic
  packages/mobile/ios/AudiusReactNative/AppDelegate.mm
Labels: size/XS

#12126 Fix loading state for featured remix contests
  packages/web/src/pages/explore-page/components/desktop/FeaturedRemixContests.tsx
Labels: size/S

#12129 Fix tan-query 400 retry logic
  packages/common/src/api/tan-query/utils/defaultConfig.ts
Labels: size/XS

#12131 Don't suggest artists from staging when running dev
  packages/common/src/api/tan-query/users/useSuggestedArtists.ts
  packages/mobile/src/services/env/env.dev.ts
  packages/web/src/services/env/env.dev.ts
Labels: size/XS

#12136 Wait for artwork to load before clicking save
  packages/web/e2e/page-object-models/editCollection.ts
  packages/web/src/components/upload/UploadArtwork.jsx
Labels: size/XS

#12135 Fix handle for hopeless recs
  packages/discovery-provider/ddl/migrations/0140_fix_handle.sql
Labels: size/S

#12138 Fix SSR
  packages/web/bundlesize.prod.config.json
  packages/web/bundlesize.stage.config.json
  packages/web/src/app/web-player/ServerWebPlayer.tsx
Labels: size/S

#12134 [API-119] Clean duplicate user rows, prevent it from happening
  packages/discovery-provider/ddl/migrations/0139_clean_user_rows.sql
  packages/discovery-provider/src/tasks/index_core.py
Labels: size/S

#12133 [PE-6168] Add winners section to pick winners page
  packages/common/src/api/tan-query/events/useRemixContest.ts
  packages/common/src/store/queue/types.ts
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
Labels: size/L

#12105 [PE-6165] Remove now-playing artwork top margin
  packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
Labels: size/M

#12132 [PE-6190] Deprecate getUserHandle
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/saga-utils/queryUser.ts
  packages/common/src/api/tan-query/users/account/useAddToPlaylistFolder.ts
  packages/common/src/api/tan-query/users/account/useCurrentAccount.ts
  packages/common/src/api/tan-query/users/account/usePlaylistLibrary.ts
  packages/common/src/api/tan-query/users/account/useReorderLibrary.ts
  packages/common/src/api/tan-query/users/account/useUpdatePlaylistLibrary.ts
  packages/common/src/api/tan-query/users/useFollowUser.ts
  packages/common/src/api/tan-query/users/useUnfollowUser.ts
  packages/common/src/api/tan-query/users/useUpdateUser.ts
  packages/common/src/api/tan-query/users/useUser.ts
  packages/common/src/hooks/useUploadCompletionRoute.ts
  packages/common/src/models/Analytics.ts
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/selectors.ts
  packages/mobile/src/components/challenge-rewards-drawer/ProfileCompletionChallengeContent.tsx
  packages/mobile/src/components/challenge-rewards-drawer/ReferralChallengeContent.tsx
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
  packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/common/store/cache/tracks/sagaHelpers.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/sagas.js
  packages/web/src/common/store/pages/profile/lineups/tracks/watchUploadTracksSaga.ts
  packages/web/src/common/store/recovery-email/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
  packages/web/src/components/duplicate-add-confirmation-modal/DuplicateAddConfirmationModal.tsx
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/PlaylistLibrary/AudioNftPlaylistNavItem.tsx
  packages/web/src/components/nav/desktop/useNavUploadStatus.ts
  packages/web/src/components/nav/mobile/ConnectedBottomBar.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/components/tipping/tip-audio/TipSent.tsx
  packages/web/src/hooks/useManagedAccountNotAllowedRedirect.ts
  packages/web/src/pages/check-page/CheckPage.tsx
  packages/web/src/pages/dashboard-page/store/sagas.ts
  packages/web/src/pages/fb-share-page/FbSharePage.tsx
  packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx
  packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterPage.tsx
  packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ReferralsChallengeModalContent.tsx
  packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/AccountSettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/SettingsPage.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
  packages/web/src/pages/upload-page/pages/FinishPage.tsx
Labels: size/XXL

#12142 Allow calculation of trending scores for albums
  packages/discovery-provider/src/trending_strategies/pnagD_trending_playlists_strategy.py
Labels: size/S

#12143 Up connection pool
  packages/discovery-provider/default_config.ini
Labels: size/XS

#12081 Add missing indexes
  packages/discovery-provider/ddl/migrations/0138_missing_indexes.sql
Labels: size/S

#12144 Fix pw remix upload test throwing on 404
  packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Labels: size/XS

#12130 [PE-6178] Web add cash modal updates
  packages/web/src/components/add-funds-modal/AddFundsModal.tsx
  packages/web/src/components/add-funds/AddFunds.tsx
  packages/web/src/components/add-funds/CashBalanceSection.tsx
  packages/web/src/components/address-tile/AddressTile.tsx
  packages/web/src/components/payment-method/PaymentMethod.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.module.css
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Labels: size/L

#12128 Fix recent search and autocomplete styling
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
Labels: size/M

#12145 [PE-6201] Add feature flag for pick winners milestone
  packages/common/src/services/remote-config/feature-flags.ts
  packages/mobile/src/screens/track-screen/RemixContestSection.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
  packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSection.tsx
Labels: size/M

#12151 [QA-2106] Fix mobile track navigation params
  packages/mobile/src/components/core/UserGeneratedText.tsx
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/M

#12153 [PE-6193] Update winners tiles to be reorderable
  packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
  packages/web/src/store/dragndrop/slice.ts
Labels: size/L

#12154 [PE-6200] Only send remix contest start notif when track is public
  packages/discovery-provider/ddl/functions/handle_event.sql
  packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_started_notification.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/discovery-provider/src/tasks/entity_manager/entities/track.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/discovery-provider/src/tasks/publish_scheduled_releases.py
Labels: size/XXL

#12106 [PE-6152] Remove search results state
  packages/common/src/store/pages/index.ts
  packages/common/src/store/pages/search-results/actions.ts
  packages/common/src/store/pages/search-results/reducer.ts
  packages/common/src/store/pages/search-results/selectors.ts
  packages/common/src/store/pages/search-results/types.ts
  packages/mobile/src/store/sagas.ts
  packages/web/src/common/store/pages/search-page/sagas.ts
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#12146 [PE-6172] Deprecate retrieveTracks
  packages/common/src/api/tan-query/saga-utils/queryTrack.ts
  packages/common/src/api/tan-query/tracks/useTrack.ts
  packages/common/src/api/tan-query/tracks/useTracks.ts
  packages/common/src/store/lineup/selectors.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/cache/tracks/utils/fetchAndProcessRemixes.ts
  packages/web/src/common/store/cache/tracks/utils/index.ts
  packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts
  packages/web/src/common/store/pages/collection/lineups/sagas.js
  packages/web/src/common/store/pages/saved/lineups/sagas.ts
  packages/web/src/common/store/upload/sagas.test.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/L

#12157 [PE-6169] Add PickWinners drawer for mobile
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
  packages/mobile/src/screens/track-screen/PickWinnersDrawer.tsx
  packages/mobile/src/screens/track-screen/RemixContestDetailsTab.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/mobile/src/store/drawers/slice.ts
Labels: size/M

#12155 Passthru throwOnError for trackByPermalink query
  packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
  packages/common/src/api/tan-query/types.ts
Labels: size/S

#12158 Remove parent track title from new remix notif
  packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
Labels: size/XS

#12150 [PE-6188] Address comments from M2 bugbash
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/constants.ts
  packages/web/src/components/buy-sell-modal/types.ts
Labels: size/L

#12162 [PE-6179] Mobile add cash UI updates
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/add-funds-drawer/AddFundsDrawer.tsx
  packages/mobile/src/components/add-funds-drawer/CashBalanceSection.tsx
  packages/mobile/src/components/add-funds-drawer/StripeSection.tsx
  packages/mobile/src/components/core/AddressTile.tsx
  packages/mobile/src/components/payment-method/PaymentMethod.tsx
  packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
  packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx
  packages/mobile/src/components/usdc-manual-transfer-drawer/index.ts
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Labels: size/XL

#12160 Increase some e2e test timeouts
  packages/web/e2e/editCollection.test.ts
  packages/web/e2e/uploadCollection.test.ts
  packages/web/e2e/uploadTrack.test.ts
Labels: size/XS

#12165 Fix loading on cash balance
  packages/mobile/src/screens/wallet-screen/components/CashWallet.tsx
Labels: size/S

#12166 [PE-6225] Rename AddFunds to AddCash
  packages/common/src/messages/walletMessages.ts
  packages/common/src/store/ui/modals/add-cash-modal/index.ts
  packages/common/src/store/ui/modals/add-funds-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
  packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx
  packages/mobile/src/screens/wallet-screen/components/CashWallet.tsx
  packages/web/src/components/add-cash-modal/AddCashModal.module.css
  packages/web/src/components/add-cash-modal/AddCashModal.tsx
  packages/web/src/components/add-cash/AddCash.module.css
  packages/web/src/components/add-cash/AddCash.tsx
  packages/web/src/components/add-cash/CashBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuySellModal.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
  packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx
Labels: size/L

#12161 Fix account profile not loading in instantly
  packages/common/src/api/tan-query/users/account/useCurrentAccount.ts
  packages/common/src/services/local-storage/LocalStorage.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/test/mocks/local-storage.ts
Labels: size/M

#12163 Web search / explore merge QA fixes
  packages/common/src/api/tan-query/collection/useExploreContent.ts
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/input/TextInput/TextInput.module.css
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/input/TextInput/types.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/components/perspective-card/PerspectiveCard.module.css
  packages/web/src/components/remix-contest-card/RemixContestCard.tsx
  packages/web/src/components/search-bar/DesktopSearchBar.module.css
  packages/web/src/components/search-bar/DesktopSearchBar.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/hooks/useTabs/useTabs.tsx
  packages/web/src/pages/explore-page/collections.ts
  packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/search-page/SearchResults.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
Labels: size/L

#12167 Don't send remix contest notifs for private tracks
  packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ended_notification.py
  packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ending_soon_notification.py
  packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_ended_notification.py
  packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_ending_soon_notification.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ended.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ending_soon.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ended.py
  packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ending_soon.py
Labels: size/L

#12169 Retrigger pod install
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#12170 [PE-6227] Remove blocknumber from remix contest to prevent dups
  packages/discovery-provider/ddl/functions/handle_event.sql
  packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_started_notification.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
Labels: size/S

#12173 Use HTTPS for api.audius.co
  packages/mobile/src/services/env/env.prod.ts
  packages/web/src/services/env/env.prod.ts
Labels: size/XS

#12172 Make edit collection e2e test retryable
  packages/web/e2e/editCollection.test.ts
  packages/web/e2e/uploadCollection.test.ts
  packages/web/e2e/uploadTrack.test.ts
Labels: size/S

#12174 [PE-6198] Add analytic events for remix contests
  packages/common/src/api/tan-query/events/useEventsByEntityId.ts
  packages/common/src/models/Analytics.ts
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Labels: size/L

#12176 [PE-6170] Update contest ended notif to navigate to pick winners
  packages/web/src/components/notification/Notification/ArtistRemixContestEndedNotification.tsx
Labels: size/M

#12175 Fix animated-event error leading to crash
  packages/mobile/mobile-patches/react-native+0.76.9.patch
  scripts/patch-package.sh
Labels: size/S

#12178 [PE-6202] Add confirmation modal for pick winners
  packages/common/src/store/ui/modals/finalize-winners-confirmation-modal/index.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/finalize-winners-confirmation-modal/FinalizeWinnersConfirmationModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
Labels: size/L

#12171 [PE-6229] Link by Stripe logo on web add cash modal
  packages/common/src/messages/walletMessages.ts
  packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
  packages/web/src/components/add-cash-modal/AddCashModal.tsx
Labels: size/M

#12179 [QA-2102] Fix touch target on notification icon
  packages/web/src/components/nav/desktop/NotificationsButton.tsx
Labels: size/S

#12180 Add logs to rate limit
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
Labels: size/M

#12182 [PE-6192] Add winners to remixes page on web
  packages/common/src/api/tan-query/events/useRemixContest.ts
  packages/common/src/api/tan-query/remixes/useRemixes.ts
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
  packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
Labels: size/L

#12184 Fix search tracks lineup
  packages/mobile/src/store/sagas.ts
  packages/web/src/store/sagas.ts
Labels: size/XS

#12185 [PE-6194] Add winners to remixes page on mobile
  packages/mobile/src/components/lineup/TanQueryLineup.tsx
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/src/components/lineup/TanQueryLineup.tsx
  packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
Labels: size/M

#12187 Add Cash QA feedback
  packages/common/src/messages/walletMessages.ts
  packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/components/add-cash-modal/AddCashModal.tsx
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
Labels: size/S

#12189 [PE-6259] Display winners tab by default on finished remix contests
  packages/mobile/src/screens/track-screen/RemixContestSection.tsx
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
  packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSection.tsx
Labels: size/M

#12191 Update pick winners button text to edit winners
  packages/common/src/messages/remixes.ts
  packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Labels: size/XS

#12188 [PE-6256] Update callback dependencies to properly update lineup data
  packages/common/src/api/tan-query/lineups/useLineupQuery.ts
  packages/common/src/api/tan-query/remixes/useRemixes.ts
Labels: size/XS

#12192 Web search/explore merge QA pass 2
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/harmony/src/components/input/TextInput/TextInput.module.css
  packages/harmony/src/components/input/TextInput/TextInput.tsx
  packages/harmony/src/components/popup/Popup.tsx
  packages/harmony/src/hooks/useClickOutside.ts
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/nav/desktop/useNavConfig.tsx
  packages/web/src/components/remix-contest-card/RemixContestCard.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
  packages/web/src/pages/search-page/search-results/PlaylistResults.tsx
  packages/web/src/pages/search-page/search-results/ProfileResults.tsx
Labels: size/L

#12195 Remove ci pod cache
  .circleci/src/commands/@mobile-commands.yml
Labels: size/XS

#12190 [PE-6175, PE-6176] Replace track cache add and update with tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/utils/index.ts
  packages/common/src/api/tan-query/utils/updateTrackData.ts
  packages/common/src/store/cache/index.ts
  packages/common/src/store/cache/mergeCustomizer.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/purchase-content/sagas.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/users/sagas.ts
  packages/web/src/common/store/social/tracks/sagas.ts
Labels: size/L

#12193 [PE-6261] Remove redux track cache
  packages/common/src/api/tan-query/comments/useDeleteComment.ts
  packages/common/src/api/tan-query/comments/usePinComment.ts
  packages/common/src/api/tan-query/comments/usePostComment.ts
  packages/common/src/api/tan-query/comments/useReportComment.ts
  packages/common/src/api/tan-query/comments/useTrackCommentCount.ts
  packages/common/src/api/tan-query/comments/utils.ts
  packages/common/src/api/tan-query/tracks/useTracks.ts
  packages/common/src/api/tan-query/utils/primeCollectionData.ts
  packages/common/src/api/tan-query/utils/primeTrackData.ts
  packages/common/src/api/tan-query/utils/updateTrackData.ts
  packages/common/src/store/cache/actions.ts
  packages/common/src/store/cache/collections/reducer.ts
  packages/common/src/store/cache/index.ts
  packages/common/src/store/cache/reducer.ts
  packages/common/src/store/cache/selectors.ts
  packages/common/src/store/cache/tracks/actions.ts
  packages/common/src/store/cache/tracks/reducer.ts
  packages/common/src/store/cache/tracks/types.ts
  packages/common/src/store/cache/types.ts
  packages/common/src/store/cache/users/reducer.ts
  packages/common/src/store/gated-content/sagas.ts
  packages/common/src/store/lineup/index.ts
  packages/common/src/store/lineup/selectors.ts
  packages/common/src/store/lineup/useLineupTable.ts
  packages/common/src/store/reducers.ts
  packages/harmony/src/components/input/TextInput/TextInput.module.css
  packages/mobile/src/components/track-list/types.ts
  packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts
  packages/mobile/src/screens/favorites-screen/useFavoritesLineup.ts
  packages/mobile/src/store/offline-downloads/sagas/rehydrateOfflineDataSaga.ts
  packages/web/src/app/ServerReduxProvider.tsx
  packages/web/src/common/store/cache/collections/utils/addTracksFromCollections.ts
  packages/web/src/common/store/cache/sagas.ts
  packages/web/src/common/store/cache/tracks/sagas.ts
  packages/web/src/common/store/cache/tracks/utils/index.ts
  packages/web/src/common/store/cache/tracks/utils/processAndCacheTracks.ts
  packages/web/src/common/store/cache/tracks/utils/reformat.ts
  packages/web/src/common/store/pages/ai/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/feed/lineup/sagas.ts
  packages/web/src/common/store/pages/premium-tracks/lineups/tracks/sagas.ts
  packages/web/src/common/store/pages/profile/lineups/feed/retrieveUserReposts.ts
  packages/web/src/common/store/pages/profile/lineups/tracks/retrieveUserTracks.ts
  packages/web/src/common/store/pages/saved/sagas.ts
  packages/web/src/common/store/pages/trending-underground/lineups/sagas.ts
  packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
  packages/web/src/common/store/recommendation/sagas.ts
  packages/web/src/common/store/smart-collection/sagas.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
  packages/web/src/pages/saved-page/SavedPageProvider.tsx
  packages/web/src/ssr/collection/+onBeforeRender.ts
  packages/web/src/ssr/collection/+onRenderHtml.tsx
  packages/web/src/ssr/track/+onRenderHtml.tsx
Labels: size/XXL

#12199 Improve CI install cache
  .circleci/config.yml
Labels: size/M

#12186 [PE-6180] Web withdraw crypto UI updates
  packages/common/src/models/Analytics.ts
  packages/web/src/components/add-cash/CashBalanceSection.tsx
  packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.module.css
  packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.module.css
  packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.module.css
  packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Labels: size/L

#12148 [PE-6156] Deprecate fetch collections
  packages/common/src/api/tan-query/collection/useCollection.ts
  packages/common/src/api/tan-query/collection/useCollectionByPermalink.ts
  packages/common/src/api/tan-query/collection/useCollections.ts
  packages/common/src/api/tan-query/saga-utils/queryCollection.ts
  packages/common/src/store/pages/collection/actions.ts
  packages/common/src/store/pages/collection/reducer.ts
  packages/common/src/store/pages/collection/selectors.ts
  packages/common/src/store/pages/collection/types.ts
  packages/web/src/common/store/account/sagas.ts
  packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/collections/confirmOrderPlaylist.ts
  packages/web/src/common/store/cache/collections/utils/index.ts
  packages/web/src/common/store/cache/collections/utils/processAndCacheCollections.ts
  packages/web/src/common/store/cache/collections/utils/queryTracksForCollections.ts
  packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts
  packages/web/src/common/store/pages/collection/sagas.js
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/common/store/saved-collections/sagas.ts
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/XL

#12203 Fix query track gc time
  packages/common/src/api/tan-query/saga-utils/queryTrack.ts
  packages/web/src/common/store/upload/sagas.ts
Labels: size/S

#12205 Drop fallback cache keys
  .circleci/config.yml
Labels: size/XS

#12206 Fix cache key save
  .circleci/config.yml
Labels: size/XS

#12200 Web search/explore merge QA third pass
  packages/harmony/src/components/button/FilterButton/FilterButton.tsx
  packages/web/src/components/remix-contest-card/RemixContestCard.tsx
  packages/web/src/components/search-bar/SearchBarResult.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/hooks/useTabs/TabStyles.module.css
  packages/web/src/pages/explore-page/ExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/search-page/SearchFilters.tsx
  packages/web/src/pages/search-page/hooks.ts
  packages/web/src/pages/search-page/search-results/TrackResults.tsx
Labels: size/XL

#12201 [PE-6275, PE-6276, PE-6279, PE-6282] Pick Winners Milestone QA 1
  packages/common/src/api/tan-query/remixes/useRemixes.ts
  packages/common/src/store/ui/modals/finalize-winners-confirmation-modal/index.ts
  packages/web/src/components/finalize-winners-confirmation-modal/FinalizeWinnersConfirmationModal.tsx
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
  packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
Labels: size/M
