Repository AudiusProject/apps, pull requests merged in 2025-07, with the labels that each got.

#12442 Update sdk gen script to use bridge server
  packages/sdk/src/sdk/api/generator/README.md
  packages/sdk/src/sdk/api/generator/gen.js
Labels: size/S

#12445 Update the amout of decimal places we show
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/common/src/store/ui/buy-sell/useTokenAmountFormatting.ts
  packages/common/src/utils/decimal.ts
Labels: size/L

#12447 Revert "Add rich notifications to enable image urls (#12428)"
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/Gemfile
  packages/mobile/ios/Gemfile.lock
  packages/mobile/ios/NotificationService/Info.plist
  packages/mobile/ios/NotificationService/NotificationService.swift
  packages/mobile/ios/Podfile.lock
Labels: size/XL

#12451 [QA-2190] Fix download all button text
  packages/mobile/src/screens/track-screen/DownloadSection.tsx
  packages/web/src/components/track/DownloadSection.tsx
  packages/web/src/pages/track-page/components/mobile/DownloadSection.tsx
Labels: size/M

#12460 [QA-2193] Fix android playback stuck on one track
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/M

#12452 [QA-2198] Fix collection tile play/pause
  packages/common/src/api/tan-query/collection/useCollectionTracksWithUid.ts
  packages/harmony/src/components/scrollbar/Scrollbar.module.css
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
Labels: size/S

#12457 [QA-2197] Update related artists count add follows idx
  packages/discovery-provider/ddl/migrations/0143_follows_ix.sql
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/web/src/pages/profile-page/components/desktop/RelatedArtists.tsx
Labels: size/S

#12465 Add hook to prevent changes to discovery-provider api
  packages/discovery-provider/.hooks/pre-commit.json
Labels: size/XS

#12464 Add total_track_count to aggregate_user table
  packages/discovery-provider/ddl/functions/handle_track.sql
  packages/discovery-provider/ddl/migrations/0143_add_user_total_tracks.sql
  packages/discovery-provider/integration_tests/models/test_aggregate_counters.py
  packages/discovery-provider/src/models/users/aggregate_user.py
Labels: size/M

#12461 Fix collection tile link
  packages/web/src/components/track/desktop/CollectionTile.tsx
Labels: size/XS

#12471 [PE-6489] Make buy/sell work on stage
  packages/common/src/api/tan-query/jupiter/constants.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/store/ui/buy-audio/constants.ts
  packages/common/src/store/ui/buy-sell/constants.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/common/src/store/ui/shared/tokenConstants.ts
Labels: size/L

#12472 [HOTFIX] Small ui bugs - UserLink margin & trending playlist indices
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/CollectionTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
Labels: size/S

#12473 Remove ToS banner update
  packages/web/src/app/web-player/WebPlayer.jsx
Labels: size/XS

#12467 Search explore milestone 2: for you, recent premium, best selling
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/explore/useBestSelling.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/tracks/useRecentPremiumTracks.ts
  packages/common/src/api/tan-query/tracks/useRecommendedTracks.ts
  packages/common/src/messages/explore.ts
  packages/common/src/store/queue/types.ts
  packages/mobile/src/components/track/TrackCard.tsx
  packages/mobile/src/components/track/TrackCardSkeleton.tsx
  packages/mobile/src/screens/explore-screen/components/BestSelling.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/RecentPremiumTracks.tsx
  packages/mobile/src/screens/explore-screen/components/RecommendedTracks.tsx
  packages/mobile/src/screens/explore-screen/components/TrackTileCarousel.tsx
  packages/sdk/src/sdk/sdk.ts
  packages/web/src/components/best-selling-card/BestSellingCard.tsx
  packages/web/src/components/best-selling-card/index.ts
  packages/web/src/components/track/TrackCard.tsx
  packages/web/src/pages/explore-page/components/desktop/BestSellingSection.tsx
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
Labels: size/XL

#12469 [API-168][API-171] Add history, recently commented, and feeling lucky endpoints to SDK
  .changeset/dull-colts-collect.md
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/HistoryResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/sdk/src/sdk/api/generated/full/apis/TracksApi.ts
Labels: size/L

#12479 Fix X icon color on mobile
  .changeset/green-bikes-destroy.md
  packages/harmony/src/assets/icons/X.svg
Labels: size/XS

#12475 Fix podcast playback rate on mobile
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
  packages/mobile/src/components/scrubber/Slider.tsx
  packages/mobile/src/components/scrubber/usePosition.ts
Labels: size/L

#12481 Rename integration-test to e2e-test
  .circleci/src/jobs/@integration-jobs.yml
  .circleci/src/workflows/e2e.yml
Labels: size/XS

#12483 Add more distros to distro.audius.co
  packages/distro/src/distributors/prod.json
Labels: size/S

#12484 Fix search result scroll cutoff
  packages/mobile/src/screens/search-screen/search-results/AlbumResults.tsx
  packages/mobile/src/screens/search-screen/search-results/PlaylistResults.tsx
  packages/mobile/src/screens/search-screen/search-results/ProfileResults.tsx
Labels: size/XS

#12478 Fix mobile profile navving to reposts tab for artists sometimes
  packages/common/src/api/tan-query/users/useUserByParams.ts
  packages/common/src/hooks/useIsArtist.ts
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
  packages/web/src/pages/profile-page/ProfilePageProvider.tsx
  packages/web/src/pages/transaction-history-page/desktop/TransactionHistoryPage.tsx
  packages/web/src/pages/transaction-history-page/mobile/TransactionHistoryPage.tsx
Labels: size/M

#12485 Temporarily change staging rewards cd to 0
  packages/discovery-provider/src/challenges/challenges.stage.json
Labels: size/M

#12482 [API-256] Add Action.Share to EM and index it
  .changeset/tough-crabs-vanish.md
  packages/commands/src/playlist/index.ts
  packages/commands/src/playlist/share-playlist.ts
  packages/commands/src/track/index.ts
  packages/commands/src/track/share-track.ts
  packages/discovery-provider/ddl/functions/handle_share.sql
  packages/discovery-provider/ddl/functions/notify_on_row.sql
  packages/discovery-provider/ddl/migrations/0145_create_shares_table.sql
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
  packages/discovery-provider/src/models/social/share.py
  packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py
  packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
  packages/discovery-provider/src/tasks/entity_manager/utils.py
  packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
  packages/sdk/src/sdk/api/playlists/types.ts
  packages/sdk/src/sdk/api/tracks/TracksApi.ts
  packages/sdk/src/sdk/api/tracks/types.ts
  packages/sdk/src/sdk/services/EntityManager/types.ts
Labels: size/L

#12491 [PE-6492] Mobile hex tokens
  packages/mobile/src/harmony-native/components/HexagonalIcon.tsx
  packages/mobile/src/harmony-native/components/IconTokenAUDIO.tsx
  packages/mobile/src/harmony-native/index.ts
Labels: size/M

#12476 [QA-2185] Fix user link flow
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/pages/comment-history/components/desktop/CommentHistoryPage.tsx
Labels: size/S

#12487 [PE-6458] Update SDK and getComment hook
  packages/common/src/api/tan-query/comments/useComment.ts
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/CommentsApi.ts
  packages/sdk/src/sdk/api/generated/default/models/Comment.ts
  packages/sdk/src/sdk/api/generated/default/models/CommentResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/ReplyComment.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/CommentsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/Comment.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentResponse.ts
  packages/sdk/src/sdk/api/generated/full/models/ReplyComment.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
Labels: size/L

#12499 Fix e2e-init
  .circleci/src/jobs/@integration-jobs.yml
  .circleci/src/workflows/e2e.yml
Labels: size/XS

#12496 Fix guest account issues
  packages/common/src/store/account/sagas.ts
  packages/common/src/store/account/slice.ts
  packages/web/src/common/store/pages/signon/sagas.ts
  packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Labels: size/S

#12500 Fix scrolling in recent searches
  packages/mobile/src/screens/search-screen/RecentSearches.tsx
Labels: size/M

#12488 feat: Add core token registry infrastructure
  packages/common/src/services/env.ts
  packages/common/src/services/index.ts
  packages/common/src/services/tokens/TokenRegistry.ts
  packages/common/src/services/tokens/index.ts
  packages/common/src/services/tokens/tokenConfigs.ts
  packages/common/src/services/tokens/types.ts
  packages/common/src/services/tokens/utils.ts
  packages/mobile/src/services/env/env.dev.ts
  packages/mobile/src/services/env/env.prod.ts
  packages/mobile/src/services/env/env.stage.ts
  packages/web/src/services/env/env.dev.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
Labels: size/L

#12505 Remove foreign key cascade delete for blocks/shares
  packages/discovery-provider/ddl/migrations/0145_create_shares_table.sql
  packages/discovery-provider/src/models/social/share.py
Labels: size/S

#12489 feat: Add BONK token support to backend and SDK
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config/tokenConfig.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/tokenUtils.ts
  packages/fixed-decimal/src/currencies.ts
  packages/fixed-decimal/src/index.ts
  packages/sdk/src/sdk/config/development.ts
  packages/sdk/src/sdk/config/production.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/sdk/src/sdk/config/types.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
  packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
  packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/getDefaultConfig.ts
  packages/sdk/src/sdk/services/Solana/types.ts
  packages/sdk/src/sdk/utils/mintFixedDecimalMap.ts
Labels: size/L

#12504 [QA-2207] Fix double scrollbars
  packages/harmony/src/components/scrollbar/Scrollbar.module.css
  packages/web/src/components/track/desktop/CollectionTile.tsx
Labels: size/XS

#12492 [API-261] Fire async share action when opening the share modal/drawer for content
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useShareAction.ts
  packages/mobile/src/components/share-drawer/ShareDrawer.tsx
  packages/web/src/components/share-modal/ShareModal.tsx
Labels: size/M

#12508 Fix useHighlightComment hook
  packages/common/src/api/tan-query/comments/useComment.ts
  packages/common/src/api/tan-query/comments/useHighlightComment.ts
  packages/common/src/api/tan-query/comments/utils.ts
Labels: size/S

#12509 [QA-2205] Fix remix section scrolling to top (properly this time)
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/hooks/useTabs/useTabs.tsx
Labels: size/S

#12510 Add getMostSharedTracks to SDK
  .changeset/sharp-paws-breathe.md
  packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
  packages/sdk/src/sdk/api/generated/full/apis/TracksApi.ts
Labels: size/L

#12511 Migrate to UserBadgesV2 on mobile
  packages/mobile/src/components/card/Card.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/details-tile/DeletedTile.tsx
  packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
  packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
  packages/mobile/src/components/inbox-unavailable-drawer/InboxUnavailableDrawer.tsx
  packages/mobile/src/components/lineup-tile/LineupTileCoSign.tsx
  packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx
  packages/mobile/src/components/suggested-tracks/SuggestedTracks.tsx
  packages/mobile/src/components/track-details-tile/TrackDetailsTile.tsx
  packages/mobile/src/components/track-list/TrackListItem.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/components/user-badges/UserBadgesV2.tsx
  packages/mobile/src/components/user-badges/index.ts
  packages/mobile/src/components/user-link/UserLink.tsx
  packages/mobile/src/screens/ai-generated-tracks-screen/AiGeneratedTracksScreen.tsx
  packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx
  packages/mobile/src/screens/chat-screen/ChatListItem.tsx
  packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
  packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/TipReactionNotification.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
  packages/mobile/src/screens/settings-screen/AccountVerificationScreen.tsx
  packages/mobile/src/screens/settings-screen/CommentSettingsScreen.tsx
  packages/mobile/src/screens/tip-artist-screen/ReceiverDetails.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
  packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
Labels: size/L

#12512 Replace packages/discovery-provider/ddl with new api version
  packages/discovery-provider/ddl/README.md
  packages/discovery-provider/ddl/local-test-replicas.sh
  packages/discovery-provider/ddl/local-test.sh
  packages/discovery-provider/ddl/pg_migrate.sh
  packages/discovery-provider/ddl/run_migrations.go
Labels: size/L

#12514 Drop coming soon offline mode features
  packages/mobile/src/components/drawers/OfflineListeningDrawer.tsx
Labels: size/M

#12520 Fix follower count formatting
  packages/common/src/utils/formatUtil.test.ts
  packages/common/src/utils/formatUtil.ts
Labels: size/S

#12523 Fix TOKEN_ACCOUNT_NOT_FOUND events
  packages/common/src/store/buy-usdc/sagas.ts
Labels: size/XS

#12529 Fix incorrect comment display
  packages/web/src/components/comments/CommentSection.tsx
Labels: size/S

#12531 Add examples to @packages/fixed-decimal
  packages/fixed-decimal/README.md
  packages/fixed-decimal/examples/audio.ts
  packages/fixed-decimal/examples/fixedDecimal.ts
  packages/fixed-decimal/examples/math.ts
  packages/fixed-decimal/examples/usdc.ts
Labels: size/M

#12524 [PE-6420] Improve useCurrentAccount local-storage perf
  packages/common/src/api/tan-query/users/account/useCurrentAccount.ts
Labels: size/XS

#12527 Clicking on token badges shows hover card too
  packages/harmony/src/components/hover-card/HoverCard.tsx
  packages/harmony/src/components/hover-card/types.ts
  packages/harmony/src/hooks/useHoverDelay.ts
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/L

#12521 Mobile web top right menu
  packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
  packages/web/src/components/nav/mobile/NavBar.tsx
  packages/web/src/components/nav/mobile/NavBarActionDrawer.tsx
  packages/web/src/components/nav/mobile/NavContext.tsx
  packages/web/src/pages/audio-page/AudioPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/deactivate-account-page/components/mobile/DeactivateAccountPage.tsx
  packages/web/src/pages/not-found-page/NotFoundPage.tsx
  packages/web/src/pages/rewards-page/RewardsPage.tsx
  packages/web/src/pages/search-page/SearchPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
Labels: size/L

#12532 Improve mobile app refocus rerenders
  packages/mobile/src/app/App.tsx
  packages/mobile/src/hooks/useAndroidAppLifecycleManager.ts
Labels: size/L

#12535 [QA-2212] Improve bottom bar haptics
  packages/mobile/src/components/bottom-tab-bar/BottomTabBar.tsx
  packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
Labels: size/S

#12539 Sync ddl
  packages/discovery-provider/ddl/migrations/0146_request_metrics.sql
  packages/discovery-provider/ddl/migrations/0147_add_new_solana_indexing_tables.sql
Labels: size/L

#12540 [PE-6502, PE-6504] Add comment highlighting for mobile
  packages/common/src/messages/comments.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentOverflowMenu.tsx
  packages/mobile/src/components/comments/CommentPreview.tsx
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
Labels: size/L

#12543 [QA-2218] Fix artist popover badge
  packages/web/src/components/artist/ArtistCard.tsx
  packages/web/src/components/artist/ArtistCardCover.module.css
  packages/web/src/components/artist/ArtistCardCover.tsx
Labels: size/S

#12528 [PE-6516] YourCoins supports BONK on web
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/BonkCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/CoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/L

#12542 Fix misc mobile tile layout issues
  packages/mobile/src/components/lineup-tile/CollectionTile.tsx
  packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
  packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx
  packages/mobile/src/components/lineup-tile/TrackTileStats.tsx
  packages/mobile/src/components/lineup-tile/styles.ts
Labels: size/M

#12517 [PE-6507] Artist coin message blasts
  .changeset/late-dancers-tie.md
  comms/discovery/rpcz/chat_blast_test.go
  comms/discovery/schema/schema.go
  packages/discovery-provider/ddl/functions/chat_blast_audience.sql
  packages/sdk/src/sdk/api/chats/serverTypes.ts
Labels: size/L

#12538 [PE-6519] Send artist coin holder blast UI
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/M

#12545 [PE-6524] Add scroll to comment section on comment link
  packages/web/src/components/comments/CommentSection.tsx
Labels: size/S

#12548 [PE-6537] Add comment_id to notification action data
  packages/common/src/adapters/notification.ts
  packages/common/src/store/notifications/types.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentMention.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentReaction.test.ts
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentThread.test.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentMention.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentReaction.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentThread.ts
  packages/discovery-provider/plugins/notifications/src/types/notifications.ts
  packages/discovery-provider/src/api/v1/models/notifications.py
  packages/discovery-provider/src/api/v1/utils/extend_notification.py
  packages/discovery-provider/src/queries/get_notifications.py
  packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
  packages/harmony/src/hooks/useHoverDelay.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentMentionNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentReactionNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentThreadNotificationActionData.ts
Labels: size/L

#12551 Add msw for coin endpoints
  packages/common/src/utils/route.ts
  packages/web/package.json
  packages/web/public/mockServiceWorker.js
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/CoinApiMocks.tsx
  packages/web/src/index.tsx
  packages/web/src/pages/dev-tools/DevTools.tsx
  packages/web/src/pages/dev-tools/messages.ts
  packages/web/src/test/mocks/browser.js
  packages/web/src/test/mocks/wallet-api.ts
Labels: size/XXL

#12555 Speed up mobile app warm start by another ~75%
  packages/mobile/src/app/App.tsx
  packages/mobile/src/app/ConnectivityManager.tsx
  performance-log.md
Labels: size/M

#12558 Create bonk artist coin account on stage
  packages/discovery-provider/ddl/migrations/0150_bonk_artist_coin_stage.sql
Labels: size/S

#12552 Update eth rpc urls
  monitoring/exporters/sdk/main.js
  monitoring/prometheus/.env.prod
  monitoring/prometheus/.env.stage
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/scripts/sandbox.ts
  packages/mobile/src/services/env/env.prod.ts
  packages/mobile/src/services/env/env.stage.ts
  packages/protocol-dashboard/.env.stage
  packages/sdk/src/sdk/config/production.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
  packages/web/src/services/env/env.prod.ts
  packages/web/src/services/env/env.stage.ts
Labels: size/M

#12559 [PE-6530] Conditionally show chat message artist coin header
  packages/common/src/api/tan-query/coins/useArtistCoin.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useArtistCoinMessageHeader.ts
  packages/mobile/src/screens/chat-screen/ArtistCoinHeader.tsx
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/sdk/src/sdk/api/chats/ChatsApi.ts
  packages/sdk/src/sdk/api/chats/serverTypes.ts
  packages/web/src/pages/chat-page/components/ArtistCoinHeader.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/L

#12560 [PE-6539] Fix artist coin badge showing when 0 balance
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/S

#12556 [PE-6509] Add web coin leaderboard modal
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useArtistCoinMembers.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/user-list/coin-leaderboard/actions.ts
  packages/common/src/store/user-list/coin-leaderboard/reducers.ts
  packages/common/src/store/user-list/coin-leaderboard/selectors.ts
  packages/common/src/store/user-list/coin-leaderboard/types.ts
  packages/common/src/store/user-list/index.ts
  packages/web/src/components/CoinApiMocks.tsx
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/user-list-modal/UserListModal.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/lists/CoinLeaderboardUserList.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/store/application/ui/userListModal/sagas.ts
  packages/web/src/store/application/ui/userListModal/types.ts
  packages/web/src/test/mocks/browser.js
  packages/web/src/test/mocks/coin-api.ts
Labels: size/XL

#12562 Search/explore mobile web pass
  packages/harmony/src/components/radio-group/RadioGroup.tsx
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/Artwork.tsx
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
  packages/web/src/pages/search-page/RecentSearches.tsx
  packages/web/src/pages/search-page/search-results/AllResults.tsx
  packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Labels: size/L

#12567 Fix mobile lint
  packages/mobile/src/screens/explore-screen/components/TrackTileCarousel.tsx
Labels: size/XS

#12564 Restore gesture handler
  packages/mobile/src/app/App.tsx
Labels: size/M

#12566 Only skip top 20 trending in underground trending
  packages/discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
  packages/discovery-provider/src/queries/get_underground_trending.py
Labels: size/M

#12571 Temp fix missing comment_id in notification endpoint
  packages/common/src/adapters/notification.ts
Labels: size/S

#12572 [PE-6563] Mobile web comment highlighting
  packages/common/src/api/tan-query/comments/index.ts
  packages/common/src/api/tan-query/comments/useHighlightedComment.ts
  packages/mobile/src/components/comments/CommentBlock.tsx
  packages/mobile/src/components/comments/CommentDrawer.tsx
  packages/mobile/src/components/comments/CommentPreview.tsx
  packages/mobile/src/components/comments/CommentThread.tsx
  packages/web/src/components/comments/CommentBlock.tsx
  packages/web/src/components/comments/CommentList.tsx
  packages/web/src/components/comments/CommentPreview.tsx
  packages/web/src/components/comments/CommentSection.tsx
  packages/web/src/components/comments/CommentThread.tsx
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
  packages/web/src/pages/track-page/TrackCommentsPage.tsx
Labels: size/L

#12574 Update og image urls in web app and ssr
  packages/web/src/components/meta-tags/MetaTags.tsx
  packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
  packages/web/src/components/page/Page.tsx
  packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
  packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
  packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
  packages/web/src/utils/seo.ts
Labels: size/M

#12577 [QA-2239] Fix unable to start new chat
  packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/S

#12585 [PAY-3974] Add NOT /check to ASA
  packages/web/public/.well-known/apple-app-site-association
  packages/web/public/.well-known/apple-app-site-association-stage
Labels: size/XS

#12588 Update commentId types and fix mobile notification linking
  packages/common/src/adapters/notification.ts
  packages/common/src/store/notifications/types.ts
  packages/mobile/src/components/comments/CommentPreview.tsx
  packages/mobile/src/hooks/useNotificationNavigation.ts
  packages/mobile/src/screens/notifications-screen/Notifications/CommentNotification.tsx
  packages/mobile/src/screens/notifications-screen/Notifications/CommentThreadNotification.tsx
  packages/sdk/src/sdk/api/generated/full/models/CommentMentionNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentReactionNotificationActionData.ts
  packages/sdk/src/sdk/api/generated/full/models/CommentThreadNotificationActionData.ts
  packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
  packages/web/src/components/notification/Notification/CommentNotification.tsx
  packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
  packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
  packages/web/src/components/notification/Notification/components/EntityLink.tsx
Labels: size/L

#12582 Update rate limit mechanism in solana relay
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
  packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
  packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawPage.tsx
Labels: size/M

#12590 Fix relay empty metadata bug
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
Labels: size/XS

#12592 Lowercase wallet in relay recovery check
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
Labels: size/XS

#12589 [PE-6542] Replace msw with CoinsApi
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useArtistCoin.ts
  packages/common/src/api/tan-query/coins/useArtistCoinMembers.ts
  packages/common/src/api/tan-query/coins/useCoin.ts
  packages/common/src/api/tan-query/coins/useUserCoins.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/sdk/src/sdk/sdk.ts
  packages/web/package.json
  packages/web/public/mockServiceWorker.js
  packages/web/src/app/web-player/WebPlayer.jsx
  packages/web/src/components/CoinApiMocks.tsx
  packages/web/src/index.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
  packages/web/src/pages/dev-tools/DevTools.tsx
  packages/web/src/pages/dev-tools/messages.ts
  packages/web/src/test/mocks/browser.js
  packages/web/src/test/mocks/coin-api.ts
Labels: size/XXL

#12351 Fix comment on eth rewards manager v2 migration file
  eth-contracts/migrations/14_eth_rewards_manager_v2_migration.js
Labels: size/XS

#12596 Remove more coins section
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/S

#12594 Fix local entity writes
  .changeset/unlucky-rice-flow.md
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
Labels: size/XS

#12598 Add meta-externalfetcher to isBot check
  packages/web/scripts/workers-site/index.js
Labels: size/XS

#12601 [QA-2229] Fix special access track tile
  packages/common/src/hooks/useGatedContent.ts
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/components/track/GatedContentSection.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
Labels: size/L

#12595 [PE-6574] Mobile Token Leaderboard
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/user-list-screen/CoinLeaderboardScreen.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  packages/mobile/src/screens/user-list-screen/UserListItem.tsx
  packages/mobile/src/screens/user-list-screen/index.ts
  packages/mobile/src/screens/wallet-screen/WalletScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/BonkLeaderboardButton.tsx
Labels: size/L

#12600 [QA-2230] Fix trending navigation issues
  packages/common/src/utils/route.ts
Labels: size/XS

#12587 [PE-6556] Adds trending playlists to explore page
  packages/common/src/api/index.ts
  packages/common/src/messages/explore.ts
  packages/mobile/src/screens/explore-screen/components/ActiveDiscussions.tsx
  packages/mobile/src/screens/explore-screen/components/CollectionLineupCarousel.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/MostSharedTracks.tsx
  packages/mobile/src/screens/explore-screen/components/RecentPremiumTracks.tsx
  packages/mobile/src/screens/explore-screen/components/RecommendedTracks.tsx
  packages/mobile/src/screens/explore-screen/components/TrackTileCarousel.tsx
  packages/mobile/src/screens/explore-screen/components/TrendingPlaylists.tsx
  packages/mobile/src/screens/explore-screen/components/UndergroundTrendingTracks.tsx
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/mobile/CollectionTile.tsx
  packages/web/src/components/track/mobile/PlaylistTile.module.css
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
  packages/web/src/pages/explore-page/components/desktop/Carousel.tsx
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/TrendingPlaylists.tsx
  packages/web/src/pages/explore-page/components/desktop/UndergroundTrendingTracks.tsx
  packages/web/src/pages/explore-page/components/desktop/constants.ts
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
  packages/web/src/pages/trending-playlists/TrendingPlaylistPage.tsx
Labels: size/XL

#12605 [QA-2177] Fix collectible deep links
  packages/mobile/src/components/navigation-container/NavigationContainer.tsx
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/app-screen/ProfileTabScreen.tsx
  packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
  packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
  packages/web/src/components/collectibles/components/CollectibleDetails.tsx
  packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
Labels: size/M

#12606 [QA-2176] Fix top supporter text
  packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
  packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
Labels: size/S

#12610 [QA-2254] Fix unable to unlock special access tracks
  packages/common/src/hooks/useGatedContent.ts
  packages/mobile/src/components/details-tile/DetailsTileGatedAccess.tsx
  packages/mobile/src/components/lineup-tile/TrackTile.tsx
  packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
Labels: size/M

#12613 Squash unnecessary sentry reports
  comms/discovery/rpcz/validator.go
  comms/discovery/server/server.go
  packages/common/src/store/pages/chat/sagas.ts
Labels: size/M

#12612 [QA-2259] Fix sentry errors and warnings for logged out user
  packages/common/src/api/tan-query/wallets/useConnectedWallets.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.test.ts
  packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.ts
Labels: size/M

#12614 Fix crash on AudioBreakdownModal
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/web/src/pages/audio-page/components/WalletsTable.tsx
  packages/web/src/pages/audio-page/components/modals/AudioBreakdownModal.tsx
Labels: size/M

#12580 Migrate buy-sell modal to use API-driven token data
  CLAUDE.md
  packages/common/src/adapters/coin.ts
  packages/common/src/adapters/index.ts
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/tokenUtils.ts
  packages/common/src/api/tan-query/coins/useArtistCoin.ts
  packages/common/src/api/tan-query/coins/useArtistCoins.ts
  packages/common/src/api/tan-query/coins/useCoin.ts
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/hooks/useArtistCoinMessageHeader.ts
  packages/common/src/hooks/useFormattedTokenBalance.ts
  packages/common/src/messages/buySell.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/ui/buy-sell/constants.ts
  packages/common/src/store/ui/buy-sell/index.ts
  packages/common/src/store/ui/buy-sell/types.ts
  packages/common/src/store/ui/buy-sell/useAvailableTokens.ts
  packages/common/src/store/ui/buy-sell/useCurrentTokenPair.ts
  packages/common/src/store/ui/buy-sell/useTokenStates.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/common/src/utils/decimal.ts
  packages/common/src/utils/route.ts
  packages/harmony/src/components/artwork/Artwork.tsx
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/mobile/src/harmony-native/components/Artwork.tsx
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/TokenIcon.tsx
  packages/web/src/components/buy-sell-modal/constants.ts
  packages/web/src/components/buy-sell-modal/hooks/useTokenBalanceManager.ts
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
  packages/web/src/pages/asset-detail-page/AssetDetailTabs.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/asset-detail-page/constants.ts
  packages/web/src/pages/asset-detail-page/types.ts
  packages/web/src/pages/chat-page/components/ArtistCoinHeader.tsx
  packages/web/src/pages/pay-and-earn-page/components/BonkCoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/CoinCard.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/utils/coinMetrics.ts
Labels: size/XXL

#12617 Fix ConnectedWallets typeerror in mobile
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/web/src/pages/audio-page/components/modals/AudioBreakdownModal.tsx
Labels: size/M

#12621 [QA-2241] Fix DMs playlist tile playback
  packages/common/src/hooks/chats/useTrackPlayer.ts
  packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
Labels: size/S

#12619 [PE-6591] Add imageUrl to comment notification
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
  packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
  packages/discovery-provider/plugins/notifications/src/utils/env.ts
Labels: size/S

#12625 Fix staging ios build by avoiding harmony build
  packages/mobile/turbo.json
Labels: size/S

#12623 [QA-2260] Update end_date logic for remix contest
  packages/discovery-provider/src/tasks/entity_manager/entities/event.py
  packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
  packages/web/src/components/edit/fields/DatePickerField.tsx
  packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
Labels: size/M

#12627 Adhere to ios rich push naming standards
  packages/discovery-provider/plugins/notifications/src/sns.ts
  packages/mobile/ios/RichPushExtension/NotificationService.swift
Labels: size/M

#12628 Fix comment notification test
  packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
Labels: size/XS
