Repository AudiusProject/apps, pull requests merged in 2025-08, with the labels that each got.

#12626 Filter for actually shadow banned users
  packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
Labels: size/XS

#12629 [PE-6589] Improve mobile search/explore header
  packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Labels: size/L

#12620 Update buy/sell flow to use API driven approach and get rid of `TokenRegistry`
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/tokenUtils.ts
  packages/common/src/api/tan-query/jupiter/constants.ts
  packages/common/src/api/tan-query/jupiter/types.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/hooks/useArtistCoinMessageHeader.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/services/audius-backend/solana.ts
  packages/common/src/services/index.ts
  packages/common/src/services/tokens/TokenRegistry.ts
  packages/common/src/services/tokens/index.ts
  packages/common/src/services/tokens/tokenConfigs.ts
  packages/common/src/services/tokens/types.ts
  packages/common/src/services/tokens/utils.ts
  packages/common/src/store/ui/buy-audio/constants.ts
  packages/common/src/store/ui/buy-sell/constants.ts
  packages/common/src/store/ui/buy-sell/index.ts
  packages/common/src/store/ui/buy-sell/useTokens.ts
  packages/common/src/store/ui/shared/tokenConstants.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/modal-loading/ModalLoading.tsx
  packages/web/src/pages/chat-page/components/ArtistCoinHeader.tsx
Labels: size/XL

#12632 Update prod bundlesize check to 111 kB
  packages/web/bundlesize.prod.config.json
Labels: size/XS

#12631 [QA-2217] Add unread indicator for minimized chat list items
  packages/web/src/components/link/UserLink.tsx
  packages/web/src/pages/chat-page/components/ChatListItem.module.css
  packages/web/src/pages/chat-page/components/ChatListItem.tsx
  packages/web/src/pages/chat-page/components/ChatUser.tsx
Labels: size/M

#12635 Update SDK types to match swagger
  .changeset/stupid-lamps-worry.md
  packages/sdk/src/sdk/api/generated/default/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/default/apis/CoinsApi.ts
  packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
  packages/sdk/src/sdk/api/generated/default/models/Coin.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinInsights.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinInsightsExtensions.ts
  packages/sdk/src/sdk/api/generated/default/models/CoinInsightsResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/EncodedUserId.ts
  packages/sdk/src/sdk/api/generated/default/models/UserAssociatedWalletResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/UserIdAddress.ts
  packages/sdk/src/sdk/api/generated/default/models/UserIdsAddressesResponse.ts
  packages/sdk/src/sdk/api/generated/default/models/index.ts
Labels: size/XL

#12602 Disable discord release message
  .circleci/src/workflows/release.yml
Labels: size/XS

#12641 Fix type errors from last SDK update
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useCoinInsights.ts
  packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
  packages/web/src/common/store/pages/token-dashboard/checkIsNewWallet.ts
  packages/web/src/pages/asset-detail-page/components/AssetInsights.tsx
Labels: size/M

#12639 [PE-6558][PE-6559][PE-6560] Empty search/explore states
  packages/common/src/api/tan-query/explore/useBestSelling.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/search/useSearchResults.ts
  packages/common/src/api/tan-query/tracks/useMostSharedTracks.ts
  packages/common/src/api/tan-query/tracks/useRecentPremiumTracks.ts
  packages/common/src/api/tan-query/tracks/useRecentlyCommentedTracks.ts
  packages/common/src/api/tan-query/tracks/useRecentlyPlayedTracks.ts
  packages/common/src/api/tan-query/tracks/useRecommendedTracks.ts
  packages/common/src/api/types.ts
  packages/common/src/messages/explore.ts
  packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
  packages/mobile/src/screens/explore-screen/components/ActiveDiscussions.tsx
  packages/mobile/src/screens/explore-screen/components/BestSelling.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
  packages/mobile/src/screens/explore-screen/components/ExploreSection.tsx
  packages/mobile/src/screens/explore-screen/components/FeelingLucky.tsx
  packages/mobile/src/screens/explore-screen/components/MoodsGrid.tsx
  packages/mobile/src/screens/explore-screen/components/MostSharedTracks.tsx
  packages/mobile/src/screens/explore-screen/components/ProgressiveScrollView.tsx
  packages/mobile/src/screens/explore-screen/components/RecentPremiumTracks.tsx
  packages/mobile/src/screens/explore-screen/components/RecentlyPlayed.tsx
  packages/mobile/src/screens/explore-screen/components/RecommendedTracks.tsx
  packages/mobile/src/screens/explore-screen/components/UndergroundTrendingTracks.tsx
  packages/mobile/src/screens/search-screen/SearchCategoriesAndFilters.tsx
  packages/web/src/pages/explore-page/components/desktop/ActiveDiscussionsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/ArtistSpotlightSection.tsx
  packages/web/src/pages/explore-page/components/desktop/BestSellingSection.tsx
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.module.css
  packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylistsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedProfiles.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedRemixContests.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedRemixContestsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/FeelingLuckySection.tsx
  packages/web/src/pages/explore-page/components/desktop/JustForYouSection.tsx
  packages/web/src/pages/explore-page/components/desktop/LabelSpotlightSection.tsx
  packages/web/src/pages/explore-page/components/desktop/MoodGrid.tsx
  packages/web/src/pages/explore-page/components/desktop/MostSharedSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/RecentPremiumTracksSection.tsx
  packages/web/src/pages/explore-page/components/desktop/RecentlyPlayedSection.tsx
  packages/web/src/pages/explore-page/components/desktop/RecommendedTracksSection.tsx
  packages/web/src/pages/explore-page/components/desktop/TrendingPlaylistsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/UndergroundTrendingTracksSection.tsx
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
  packages/web/src/pages/search-page/types.ts
Labels: size/XXL

#12622 [PE-6535] Optimize list performance (lineups & more) with FlashList
  package-lock.json
  packages/mobile/ios/Podfile.lock
  packages/mobile/package.json
  packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
  packages/mobile/src/components/lineup/Lineup.tsx
  packages/mobile/src/components/track-list/TrackList.tsx
  packages/mobile/src/screens/chat-screen/ChatListScreen.tsx
  packages/mobile/src/screens/notifications-screen/NotificationList.tsx
  packages/mobile/src/screens/user-list-screen/UserList.tsx
  performance-log.md
Labels: size/L

#12648 Fix provisioning profiles for local dev
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Labels: size/S

#12650 Update copy for sharing with X
  packages/mobile/src/components/share-drawer/messages.ts
Labels: size/XS

#12654 Fix web card user links
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/remix-contest-card/RemixContestCard.tsx
  packages/web/src/components/track/TrackCard.tsx
  packages/web/src/components/user-card/UserCard.tsx
Labels: size/S

#12652 [QA-2273] Fix type issue in useAudioBalance
  packages/common/src/api/tan-query/jupiter/optimisticUpdates.ts
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
Labels: size/L

#12656 [QA-2274] Fix cosign icon
  packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/L

#12642 Be smarter are about completed block number
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
  packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
Labels: size/M

#12653 [QA-2268] Fix X sign-up button
  packages/common/src/messages/sign-on/socialMediaMessages.ts
  packages/common/src/models/User.ts
  packages/common/src/schemas/sign-on/pickHandleSchema.ts
  packages/harmony/src/components/button/SocialButton/SocialButton.stories.tsx
  packages/harmony/src/components/button/SocialButton/SocialButton.tsx
  packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
  packages/mobile/src/screens/sign-on-screen/components/SignUpFlowXAuth.tsx
  packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
  packages/mobile/src/screens/sign-on-screen/utils/socialMediaMessages.ts
  packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
  packages/web/src/components/social-proof/SocialProof.tsx
  packages/web/src/components/x-auth/XAuthButton.tsx
  packages/web/src/pages/profile-page/components/SocialLink.tsx
  packages/web/src/pages/profile-page/components/SocialLinkInput.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
  packages/web/src/pages/profile-page/components/mobile/EditProfile.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
  packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
  packages/web/src/pages/rewards-page/components/modals/VerifiedUpload.tsx
  packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
  packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
  packages/web/src/pages/sign-up-page/components/HandleField.tsx
  packages/web/src/pages/sign-up-page/components/SignupFlowXAuth.tsx
  packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
  packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
Labels: size/L

#12647 [PE-6601] Enable communication notifs
  packages/discovery-provider/plugins/notifications/src/sns.ts
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/NotificationContentExtension/Base.lproj/MainInterface.storyboard
  packages/mobile/ios/NotificationContentExtension/Info.plist
  packages/mobile/ios/NotificationContentExtension/NotificationViewController.swift
  packages/mobile/ios/NotificationContentExtension/README.md
  packages/mobile/ios/RichPushExtension/NotificationService.swift
  packages/mobile/ios/fastlane/Fastfile
  packages/mobile/package.json
Labels: size/XL

#12662 [PE-6592] Update chat composer line indexing logic
  packages/web/src/components/composer-input/ComposerInput.tsx
Labels: size/S

#12666 [QA-2272] Fix X share
  packages/common/src/utils/xShare.ts
Labels: size/XS

#12668 Fix mobile lint
  packages/mobile/src/components/buy-sell/TokenAmountSection.tsx
  packages/mobile/src/screens/buy-sell-screen/BuySellFlow.tsx
  packages/mobile/src/screens/buy-sell-screen/ConfirmSwapScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/TransactionResultScreen.tsx
Labels: size/S

#12669 Remove get valid types from notifications query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/notifications/useNotificationUnreadCount.ts
  packages/common/src/api/tan-query/notifications/useNotificationValidTypes.ts
  packages/common/src/api/tan-query/notifications/useNotifications.ts
  packages/sdk/src/sdk/api/generated/full/apis/NotificationsApi.ts
  packages/sdk/src/sdk/index.ts
Labels: size/M

#12673 Fix race condition of social icons not being loaded before being used
  .changeset/wet-cycles-look.md
  packages/harmony/src/components/button/SocialButton/SocialButton.tsx
Labels: size/S

#12674 Revert "Remove harmony workflow (#10314)"
  .circleci/config.yml
  .circleci/src/@continue_config.yml
  .circleci/src/jobs/@harmony-jobs.yml
  .circleci/src/workflows/harmony.yml
Labels: size/M

#12672 Fix rich push notifications
  packages/discovery-provider/plugins/notifications/src/sns.ts
  packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
  packages/mobile/ios/NotificationContentExtension/Base.lproj/MainInterface.storyboard
  packages/mobile/ios/NotificationContentExtension/Info.plist
  packages/mobile/ios/NotificationContentExtension/NotificationViewController.swift
  packages/mobile/ios/NotificationContentExtension/README.md
  packages/mobile/ios/RichPushExtension/NotificationService.swift
  packages/mobile/ios/fastlane/Fastfile
  packages/mobile/package.json
Labels: size/XL

#12676 Fix web test failures with TOKEN_LISTING_MAP and USDC_MINT_ADDRESS
  packages/common/src/hooks/useFormattedAudioBalance.ts
  packages/web/src/test/test-utils.tsx
Labels: size/S

#12677 [QA-2255] Revert "[QA-2193] Fix android playback stuck on one track (#12460)"
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/M

#12679 Fix supporter error for chat user search results
  packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx
Labels: size/XS

#12680 Increase the debounce time of the chat user search
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Labels: size/XS

#12681 Update create chat modal to fetch chat permissions for user results
  packages/web/src/components/search-users-modal/SearchUsersModal.tsx
  packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Labels: size/S

#12671 Replace top albums with trending albums
  packages/protocol-dashboard/src/store/cache/music/hooks.ts
  packages/sdk/src/sdk/api/generated/default/apis/PlaylistsApi.ts
  packages/sdk/src/sdk/api/generated/full/.openapi-generator/FILES
  packages/sdk/src/sdk/api/generated/full/apis/PlaylistsApi.ts
  packages/sdk/src/sdk/api/generated/full/models/FullPlaylistWithScore.ts
  packages/sdk/src/sdk/api/generated/full/models/FullPlaylistWithScoreResponse.ts
  packages/sdk/src/sdk/api/generated/full/models/index.ts
Labels: size/XL

#12659 [QA-2275] Fix hidden playlist artwork validation
  packages/common/src/schemas/upload/uploadFormSchema.ts
  packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
  packages/web/src/common/store/upload/sagas.ts
Labels: size/M

#12678 Fix animated value warning
  packages/mobile/patches/README.md
  packages/mobile/patches/react-native-collapsible-tab-view+8.0.1.patch
  packages/mobile/src/components/core/PullToRefresh.tsx
Labels: size/L

#12685 Add address lookup table to minimize swap size
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/services/Jupiter.ts
Labels: size/S

#12651 Drop user-link touch target in track-list-item
  packages/mobile/src/components/track-list/TrackListItem.tsx
Labels: size/XS

#12670 Unrevert #12658 - Add artist coin discord logic
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/users/account/useDiscordCode.ts
  packages/common/src/store/reducers.ts
  packages/common/src/store/ui/index.ts
  packages/common/src/store/ui/vip-discord-modal/sagas.ts
  packages/common/src/store/ui/vip-discord-modal/selectors.ts
  packages/common/src/store/ui/vip-discord-modal/slice.ts
  packages/common/src/store/ui/vip-discord-modal/types.ts
  packages/mobile/src/components/vip-discord-drawer/VipDiscordDrawer.tsx
  packages/mobile/src/screens/rewards-screen/TiersTile.tsx
  packages/mobile/src/store/sagas.ts
  packages/web/src/components/rewards/ClickableAddress.tsx
  packages/web/src/components/rewards/PurpleBox.module.css
  packages/web/src/components/rewards/modals/VipDiscordModal.module.css
  packages/web/src/components/rewards/modals/VipDiscordModal.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/UpdateDiscordRoleModal.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/pages/rewards-page/Tiers.tsx
  packages/web/src/store/sagas.ts
Labels: size/XL

#12689 [QA-2278] Fix layout left align on small screens
  packages/web/src/components/page/FlushPageContainer.tsx
Labels: size/XS

#12687 [PE-6626][PE-6580][PE-6581] Fix slow loading when switching explore tabs on web
  package-lock.json
  packages/common/src/api/tan-query/collection/useExploreContent.ts
  packages/web/package.json
  packages/web/src/components/best-selling-card/BestSellingCard.tsx
  packages/web/src/components/collection/CollectionCard.tsx
  packages/web/src/components/dynamic-image/DynamicImage.tsx
  packages/web/src/components/remix-contest-card/RemixContestCard.tsx
  packages/web/src/components/remix-contest-card/index.ts
  packages/web/src/components/track/Artwork.tsx
  packages/web/src/components/track/TrackCard.tsx
  packages/web/src/components/track/TrackTileStats.tsx
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/desktop/TrackListItem.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/mobile/CollectionTile.tsx
  packages/web/src/components/track/mobile/TrackTile.tsx
  packages/web/src/components/track/mobile/TrackTileArt.tsx
  packages/web/src/components/track/types.ts
  packages/web/src/components/user-card/UserCard.tsx
  packages/web/src/components/user-card/index.ts
  packages/web/src/pages/explore-page/components/desktop/ActiveDiscussionsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/ArtistSpotlightSection.tsx
  packages/web/src/pages/explore-page/components/desktop/BestSellingSection.tsx
  packages/web/src/pages/explore-page/components/desktop/Carousel.tsx
  packages/web/src/pages/explore-page/components/desktop/ExploreSection.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylistsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/FeaturedRemixContestsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/FeelingLuckySection.tsx
  packages/web/src/pages/explore-page/components/desktop/LabelSpotlightSection.tsx
  packages/web/src/pages/explore-page/components/desktop/MoodGrid.tsx
  packages/web/src/pages/explore-page/components/desktop/MostSharedSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/QuickSearchGrid.tsx
  packages/web/src/pages/explore-page/components/desktop/RecentPremiumTracksSection.tsx
  packages/web/src/pages/explore-page/components/desktop/RecentSearchesSection.tsx
  packages/web/src/pages/explore-page/components/desktop/RecentlyPlayedSection.tsx
  packages/web/src/pages/explore-page/components/desktop/RecommendedTracksSection.tsx
  packages/web/src/pages/explore-page/components/desktop/TileHelpers.tsx
  packages/web/src/pages/explore-page/components/desktop/TrendingPlaylistsSection.tsx
  packages/web/src/pages/explore-page/components/desktop/UndergroundTrendingTracksSection.tsx
  packages/web/src/pages/explore-page/components/desktop/useDeferredElement.ts
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
Labels: size/XXL

#12691 [PE-6336] Fix web track/collection tile overflow
  packages/common/src/utils/isLongFormContent.ts
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/components/track/desktop/TrackTile.tsx
  packages/web/src/components/track/desktop/TrackTileDuration.module.css
  packages/web/src/components/track/desktop/TrackTileDuration.tsx
  packages/web/src/pages/search-page/search-results/TrackResults.tsx
Labels: size/L

#12693 Artist coin blast UI improvements
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useArtistCoinMembers.ts
  packages/common/src/api/tan-query/coins/useArtistCoinMembersCount.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/hooks/chats/useAudienceUsers.ts
  packages/common/src/hooks/chats/useChatBlastAudienceContent.ts
  packages/common/src/utils/chatUtils.ts
  packages/mobile/src/screens/chat-screen/ArtistCoinHeader.tsx
  packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
  packages/web/src/pages/chat-page/components/ArtistCoinHeader.tsx
  packages/web/src/pages/chat-page/components/ChatBlastAudienceDisplay.tsx
  packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Labels: size/L

#12695 [PE-6570] Hide user contextual content when logged out
  packages/common/src/api/tan-query/users/account/useCurrentUserId.ts
  packages/web/src/pages/explore-page/components/desktop/MoodGrid.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/QuickSearchGrid.tsx
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
Labels: size/L

#12705 [PE-6605] Add dropdown menu to artist coins
  package-lock.json
  package.json
  packages/web/src/components/buy-sell-modal/DropdownSection.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
Labels: size/L

#12715 [PE-6656] Fix dupe playlist track uids
  packages/common/src/api/tan-query/collection/useCollectionTracksWithUid.ts
Labels: size/XS

#12711 Fix left-align page container
  packages/web/src/components/page/FlushPageContainer.tsx
Labels: size/XS

#12700 [QA-2163] Delete collections with tan-query
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/collection/useDeleteCollection.ts
  packages/common/src/store/cache/collections/actions.ts
  packages/mobile/src/components/delete-playlist-confirmation-drawer/DeletePlaylistConfirmationDrawer.tsx
  packages/mobile/src/components/drawers/ConfirmationDrawer.tsx
  packages/mobile/src/screens/collection-screen/CollectionScreen.tsx
  packages/web/src/common/store/cache/collections/commonSagas.ts
  packages/web/src/common/store/cache/collections/errorSagas.ts
  packages/web/src/components/delete-confirmation/DeleteConfirmationModal.tsx
  packages/web/src/components/delete-playlist-confirmation-modal/DeletePlaylistConfirmationModal.tsx
  packages/web/src/components/edit-collection/DeleteCollectionConfirmationModal.tsx
  packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Labels: size/XL

#12716 Allow unchecked transfers
  packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
Labels: size/S

#12712 Fix trending playlists playback on web
  packages/web/src/components/track/desktop/CollectionTile.tsx
  packages/web/src/pages/explore-page/components/desktop/TrendingPlaylistsSection.tsx
Labels: size/S

#12714 [PE-6643] Add unauth state for Wallet pages
  packages/common/src/utils/route.ts
  packages/web/src/components/nav/desktop/nav-items/WalletNavItem.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/wallet-page/WalletPage.tsx
Labels: size/M

#12719 Parallelize and cache user pubkeys in chat create
  packages/sdk/src/sdk/api/chats/ChatsApi.ts
Labels: size/M

#12721 [PE-6637, PE-6639] Artist Coin QA 1
  packages/common/src/utils/decimal.ts
  packages/harmony/src/components/hover-card/HoverCardHeader.tsx
  packages/harmony/src/components/hover-card/types.ts
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
  packages/web/src/utils/coinMetrics.ts
Labels: size/M

#12697 [PE-6621] Connected wallets UI
  packages/common/src/api/tan-query/jupiter/optimisticUpdates.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/api/tan-query/wallets/useUSDCBalance.ts
  packages/web/src/pages/asset-detail-page/AssetDetailContent.tsx
  packages/web/src/pages/asset-detail-page/components/ExternalWallets.tsx
Labels: size/XL

#12723 [PE-6588] Add downloads available section to search/explore
  packages/common/src/messages/explore.ts
  packages/web/src/pages/explore-page/components/desktop/DownloadsAvailableSection.tsx
  packages/web/src/pages/explore-page/components/desktop/NewExplorePage.tsx
  packages/web/src/pages/explore-page/components/desktop/TileHelpers.tsx
  packages/web/src/pages/explore-page/components/mobile/SearchExplorePage.tsx
Labels: size/M

#12729 [PE-6659] Update get new blasts in comms to match api
  comms/discovery/db/queries/get_new_blasts.go
Labels: size/S

#12730 [PE-6638] Update coin leaderboard user list to handle long user names
  packages/web/src/components/artist/ArtistChip.module.css
  packages/web/src/components/artist/ArtistChip.tsx
  packages/web/src/components/user-list/UserList.tsx
Labels: size/S

#12732 Remove grpc from client connections
  packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
Labels: size/M

#12726 Add audius/api to local development stack (audius-compose)
  dev-tools/audius-compose
  dev-tools/compose/docker-compose.api.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/compose/nginx_ingress.conf
  dev-tools/environment/api.env
  packages/sdk/src/sdk/config/development.ts
  packages/sdk/src/sdk/config/production.ts
  packages/sdk/src/sdk/config/staging.ts
  packages/sdk/src/sdk/scripts/generateServicesConfig.ts
Labels: size/M

#12728 Fix buy-sell modal error handling and UI improvements
  packages/common/src/store/ui/buy-sell/swapFormSchema.ts
  packages/common/src/store/ui/buy-sell/useGroupCoinPairs.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/DropdownSection.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Labels: size/L

#12722 Adjust remix contest timezone
  packages/common/src/utils/timeUtil.test.ts
  packages/common/src/utils/timeUtil.ts
  packages/mobile/src/screens/track-screen/RemixContestDetailsTab.tsx
  packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Labels: size/M

#12725 [PE-6636] Add receive-tokens modal.
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useUserbank.ts
  packages/common/src/messages/walletMessages.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/receive-tokens-modal/index.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/utils/route.ts
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/mobile/src/services/buyCrypto.ts
  packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
  packages/web/src/components/receive-tokens-modal/ReceiveTokensModal.tsx
  packages/web/src/components/receive-tokens-modal/index.ts
  packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/audio-page/WalletModal.tsx
  packages/web/src/pages/audio-page/components/ReceiveBody.module.css
  packages/web/src/pages/audio-page/components/ReceiveBody.tsx
  packages/web/src/pages/modals/Modals.tsx
  packages/web/src/services/solana/solana.ts
Labels: size/XL

#12736 Fix chat create blast seeding
  comms/discovery/db/queries/get_new_blasts.go
Labels: size/XS

#12731 Fix listening history
  packages/common/src/api/tan-query/tracks/useTrackHistory.ts
  packages/web/src/components/tracks-table/TracksTable.tsx
Labels: size/XS

#12742 Sync some DDL trigger handle functions from API
  packages/discovery-provider/ddl/functions/handle_sol_claimable_accounts.sql
  packages/discovery-provider/ddl/functions/handle_sol_token_balance_change.sql
  packages/discovery-provider/ddl/functions/update_sol_user_balance.sql
Labels: size/M

#12738 [PE-6667] Fix token balance swap issues
  packages/common/src/api/tan-query/wallets/useUSDCBalance.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
  packages/mobile/src/screens/buy-sell-screen/components/BuyScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SellScreen.tsx
  packages/mobile/src/screens/buy-sell-screen/components/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/BuyTab.tsx
  packages/web/src/components/buy-sell-modal/ConvertTab.tsx
  packages/web/src/components/buy-sell-modal/SellTab.tsx
  packages/web/src/components/buy-sell-modal/SwapTab.tsx
  packages/web/src/components/buy-sell-modal/hooks/index.ts
  packages/web/src/components/buy-sell-modal/hooks/useTokenBalanceManager.ts
  packages/web/src/components/buy-sell-modal/types.ts
Labels: size/L

#12743 Fix coin options
  packages/common/src/api/tan-query/coins/useArtistCoin.ts
  packages/common/src/api/tan-query/coins/useArtistCoinInsights.ts
  packages/common/src/api/tan-query/coins/useArtistCoins.ts
  packages/common/src/api/tan-query/coins/useUserCoin.ts
Labels: size/S

#12744 More synced ddl updates
  packages/discovery-provider/ddl/functions/handle_artist_coins.sql
  packages/discovery-provider/ddl/functions/handle_associated_wallet.sql
  packages/discovery-provider/ddl/migrations/0150_trending_scores_idx.sql
  packages/discovery-provider/ddl/migrations/0151_edit_sol_slot_checkpoints.sql
  packages/discovery-provider/ddl/migrations/0152_migrate_user_banks.sql
  packages/discovery-provider/ddl/migrations/0153_fix_blocktimestamp_index.sql
  packages/discovery-provider/ddl/migrations/0154_add_sol_user_balances.sql
  packages/discovery-provider/ddl/migrations/0155_add_artist_coins_logo_description.sql
  packages/discovery-provider/ddl/migrations/0156_sol_unprocessed_txs.sql
Labels: size/L

#12741 Update qr code colors
  packages/mobile/src/components/core/QRCode.tsx
  packages/mobile/src/components/core/index.ts
  packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
  packages/web/src/components/core/QRCode.tsx
  packages/web/src/components/core/index.ts
  packages/web/src/components/receive-tokens-modal/ReceiveTokensModal.tsx
Labels: size/M

#12734 [PE-6657] Artist coin leaderboard card
  packages/common/src/api/tan-query/coins/useArtistCoinMembers.ts
  packages/common/src/api/tan-query/wallets/useTokenBalance.ts
  packages/common/src/hooks/chats/useAudienceUsers.ts
  packages/web/src/components/artist/ArtistSupporting.tsx
  packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
  packages/web/src/components/notification/Notification/CommentNotification.tsx
  packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
  packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
  packages/web/src/components/notification/Notification/FavoriteNotification.tsx
  packages/web/src/components/notification/Notification/FavoriteOfRepostNotification.tsx
  packages/web/src/components/notification/Notification/FollowNotification.tsx
  packages/web/src/components/notification/Notification/RepostNotification.tsx
  packages/web/src/components/notification/Notification/RepostOfRepostNotification.tsx
  packages/web/src/components/user-list/UserList.tsx
  packages/web/src/components/user-list/lists/CoinLeaderboardUserList.tsx
  packages/web/src/components/user-profile-picture-list/UserProfilePictureList.module.css
  packages/web/src/components/user-profile-picture-list/UserProfilePictureList.tsx
  packages/web/src/components/user-profile-picture-list/index.ts
  packages/web/src/pages/asset-detail-page/AssetDetailContent.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/asset-detail-page/components/AssetLeaderboardCard.tsx
  packages/web/src/pages/chat-page/components/ChatBlastAudienceDisplay.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
Labels: size/L

#12746 Update postgres version in local dev to 15.5
  dev-tools/compose/docker-compose.yml
Labels: size/XS

#12747 Added loaded addresses to account_keys in user bank indexer
  dev-tools/compose/docker-compose.test.yml
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
  packages/discovery-provider/integration_tests/tasks/user_bank_mock_transactions.py
  packages/discovery-provider/src/tasks/index_user_bank.py
Labels: size/XL

#12758 Fix sort order
  packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
Labels: size/XS

#12748 Fix E2E tests by fixing remix notification
  .circleci/src/jobs/@integration-jobs.yml
  packages/common/src/adapters/notification.ts
  packages/common/src/api/tan-query/notifications/useNotifications.ts
  packages/web/e2e/auth.setup.ts
  packages/web/e2e/data.seed.ts
  packages/web/e2e/data.ts
  packages/web/playwright.config.ts
  packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
  packages/web/src/components/notification/Notification/utils.ts
Labels: size/L

#12751 Fix share profile drawer issue
  packages/mobile/src/components/audio-rewards/TiersExplainerDrawer.tsx
  packages/mobile/src/components/profile-actions-drawer/ProfileActionsDrawer.tsx
  packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
Labels: size/S

#12760 Setup elasticsearch for bridge in local dev
  dev-tools/compose/docker-compose.api.yml
  dev-tools/compose/docker-compose.yml
  dev-tools/environment/api.env
Labels: size/M

#12766 Fix bug with purchase split calculation
  packages/sdk/src/sdk/utils/preparePaymentSplits.ts
Labels: size/S

#12773 Swap prod dashboard rpc
  packages/protocol-dashboard/.env.prod
Labels: size/XS

#12772 [PE-6670] Redo discord flow with OAuth
  packages/common/src/hooks/index.ts
  packages/common/src/hooks/useDiscordOAuthLink.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/types.ts
  packages/common/src/store/wallet/utils.ts
  packages/common/src/utils/route.ts
  packages/mobile/src/app/Drawers.tsx
  packages/mobile/src/components/vip-discord-drawer/VipDiscordDrawer.tsx
  packages/mobile/src/components/vip-discord-drawer/index.ts
  packages/mobile/src/screens/rewards-screen/TiersTile.tsx
  packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
  packages/web/src/pages/rewards-page/Tiers.tsx
Labels: size/L

#12683 Fix types and type safety in useConnectedWallets, useAudioBalance, useWalletAudioBalance, and useWalletAudioBalances
  packages/common/src/api/tan-query/jupiter/optimisticUpdates.ts
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/common/src/api/tan-query/wallets/useConnectedWallets.ts
  packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
  packages/web/src/common/store/wallet/sagas.ts
  packages/web/src/pages/audio-page/components/modals/AudioBreakdownModal.tsx
Labels: size/XL

#12779 [PE-6725] Remove ai-attribution from uploadTrack e2e test
  packages/web/e2e/data.ts
  packages/web/e2e/uploadTrack.test.ts
Labels: size/S

#12780 Drop track tile on upload complete screen
  packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Labels: size/S

#12781 Raise priority fee max
  packages/sdk/src/sdk/services/Solana/programs/SolanaClient.ts
Labels: size/XS

#12775 [PE-6732, PE-6733, PE-6734, PE-6517] Add mobile AllCoinsScreen and CoinDetailsScreen
  packages/mobile/src/screens/all-coins-screen/AllCoinsScreen.tsx
  packages/mobile/src/screens/all-coins-screen/index.ts
  packages/mobile/src/screens/app-screen/AppTabScreen.tsx
  packages/mobile/src/screens/coin-details-screen/CoinDetailsScreen.tsx
  packages/mobile/src/screens/coin-details-screen/components/BalanceCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinInsightsCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/CoinLeaderboardCard.tsx
  packages/mobile/src/screens/coin-details-screen/components/coinMetricsUtil.ts
  packages/mobile/src/screens/coin-details-screen/index.ts
  packages/mobile/src/screens/user-list-screen/CoinLeaderboardScreen.tsx
  packages/mobile/src/screens/wallet-screen/WalletScreen.tsx
  packages/mobile/src/screens/wallet-screen/components/BonkLeaderboardButton.tsx
  packages/mobile/src/screens/wallet-screen/components/CoinCard.tsx
  packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
Labels: size/XXL

#12704 [QA-1076] Fix notification drawer top inset
  packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Labels: size/XS

#12703 [QA-2182] Fix selected tip reaction
  packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
  packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
  packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
Labels: size/XS

#12763 Remove hardcoded decimals values from Swap flow
  packages/common/src/api/tan-query/coins/tokenUtils.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/services/Jupiter.ts
  packages/common/src/store/ui/buy-sell/useTokenSwapForm.ts
Labels: size/M

#12788 [PE-6717] Update default buy/sell token pair based on path
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
Labels: size/S

#12790 $AUDIO balance includes staked
  packages/common/src/api/tan-query/wallets/useAudioBalance.ts
  packages/web/src/pages/audio-page/components/WalletManagementTile.tsx
Labels: size/XS

#12791 [QA-2290] Mobile USDC purchase recovery
  packages/mobile/src/screens/root-screen/RootScreen.tsx
Labels: size/XS

#12770 Remove revert blocks test
  packages/discovery-provider/integration_tests/tasks/entity_manager/test_index_revert_blocks.py
Labels: size/L

#12782 [PE-6729|PE-6728|PE-6724] Various minor artist coin tweaks
  packages/common/src/api/index.ts
  packages/common/src/api/tan-query/coins/useUserCoins.ts
  packages/common/src/api/tan-query/coins/useUserCreatedCoins.ts
  packages/common/src/api/tan-query/queryKeys.ts
  packages/common/src/messages/walletMessages.ts
  packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
  packages/web/src/components/buy-sell-modal/DropdownSection.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/buy-sell-modal/TokenIcon.tsx
  packages/web/src/pages/asset-detail-page/components/AssetLeaderboardCard.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
  packages/web/src/pages/profile-page/ProfilePage.test.tsx
  packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
  packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
Labels: size/L

#12797 [QA-2255] Fix android playback issue
  packages/mobile/src/components/audio/AudioPlayer.tsx
Labels: size/XS

#12800 [PE-6681] Fix DMs Header right padding issue
  packages/web/src/pages/chat-page/components/ChatHeader.tsx
Labels: size/XS

#12801 [PE-6706] Fix userbadge gap
  packages/web/src/components/nav/desktop/AccountDetails.tsx
  packages/web/src/components/user-badges/UserBadges.module.css
Labels: size/XS

#12796 [PE-6745] Change 'likes' to 'favorites' on remix sort dropdown
  packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
  packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Labels: size/XS

#12778 Fix flakey ampm test
  packages/common/src/utils/timeUtil.test.ts
Labels: size/XS

#12803 [QA-2287] Use X handles in x shares
  packages/common/src/utils/xShare.ts
  packages/mobile/src/components/share-drawer/utils.ts
  packages/mobile/src/screens/tip-artist-screen/TipSentScreen.tsx
  packages/web/src/components/share-modal/utils.ts
  packages/web/src/components/x-share-button/XShareButton.tsx
Labels: size/M

#12804 [PE-6641|PE-6642] Artist coin popover fixes
  packages/harmony/src/components/hover-card/HoverCard.tsx
  packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
  packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
  packages/web/src/components/hover-card/AudioHoverCard.tsx
Labels: size/M

#12812 [QA-2296|QA-2298] RC QA Fixes
  packages/mobile/src/components/comments/CommentDrawerContext.tsx
  packages/mobile/src/components/fields/PickArtworkField.tsx
Labels: size/M

#12813 [QA-2299] "View Profile" instead of "Artist Page"
  packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
  packages/web/src/components/menu/TrackMenu.tsx
  packages/web/src/components/menu/UserMenu.tsx
  packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
Labels: size/XS

#12814 [QA-2255] Fix mobile lineup & playback bugs (continues playing same track after playing a new lineup page)
  packages/mobile/src/components/audio/AudioPlayer.tsx
  packages/web/src/common/store/lineup/sagas.ts
Labels: size/L

#12817 [QA-2295] Fix web chat messages getting cut off
  packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
  packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Labels: size/XS

#12811 [PE-6752][PE-6697] Swap flow QA updates
  packages/common/src/api/tan-query/jupiter/indirectSwapViaAudio.ts
  packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
  packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
  packages/common/src/api/tan-query/jupiter/utils.ts
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
  packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
  packages/web/src/components/buy-sell-modal/TransactionSuccessScreen.tsx
Labels: size/L

#12818 [PE-6710] Fix optimistic updates after token swaps
  packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
Labels: size/S

#12819 Hide tier for official Audius account
  packages/mobile/src/components/user-badges/UserBadges.tsx
  packages/web/src/components/user-badges/UserBadges.tsx
Labels: size/M

#12824 Finalize send audio flow
  packages/common/src/api/tan-query/wallets/useSendTokens.ts
  packages/common/src/services/audius-backend/AudiusBackend.ts
  packages/common/src/store/ui/modals/index.ts
  packages/common/src/store/ui/modals/parentSlice.ts
  packages/common/src/store/ui/modals/reducers.ts
  packages/common/src/store/ui/modals/send-tokens-modal/index.ts
  packages/common/src/store/ui/modals/types.ts
  packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
  packages/web/src/components/send-tokens-modal/SendTokensModal.tsx
  packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
  packages/web/src/pages/audio-page/components/WalletManagementTile.tsx
  packages/web/src/pages/modals/Modals.tsx
Labels: size/L
